### ISSUE TITLE
Fade watched videos instance-wide

### ISSUE THREAD

**Issue by yidakra** [iv-org/invidious#1001]
Really useful and unhealthy feature for those of us with compulsive disorders

**Comment by Zero3K** [comment]
I agree.

**Comment by omarroth** [comment]
Could you provide some more information on the requested feature? I'm having trouble understanding what you mean.

**Comment by Zero3K** [comment]
He wants a visual indicator of the video already being viewed if it has been.

**Comment by BaconCatBug** [comment]
Yes, this please! Videodeck implements this but Videodeck also breaks every few weeks. Basically what we would like is a button to fade the video to mark it as watched as well as auto-fading it when you click on the video link.

This is how Video deck does it.

Hover Over Video Element
![image](https://user-images.githubusercontent.com/4897163/73882947-f2717600-485a-11ea-9385-bf176a770d0a.png)
Hover Over Button
![image](https://user-images.githubusercontent.com/4897163/73883036-1c2a9d00-485b-11ea-9d26-81449619ce0a.png)
And auto-fading when you click the video link.

**Comment by Zero3K** [comment]
*bump*
