### ISSUE TITLE
Where to insert the proxy list?

### ISSUE THREAD

**Issue by wilsden** [iv-org/invidious#1036]
I have 100 + proxies ipv4
I registered in the config force_resolve : ipv4
Where to register my proxies? i can't understand it
Please help, thanks!

**Comment by unixfox** [comment]
There is currently no way of using an external proxy in the configuration, what you have to do is to use a "wrapper" like proxychains to redirect the requests of invidious to your proxies.

**Comment by unixfox** [comment]
Bump, now that we can use http2 it's possible to implement that.

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/301
