### ISSUE TITLE
Can't see video statistics

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1039]
Hello,

Sometimes, invidious is unable to retrieve statistics from a video: views, comments, likes, dislike are at 0, even when it is actually higher on the original video, the channel pic is broken and give a 404 error and the comments list is empty.

**Comment by wilsden** [comment]
Тоже самое сейчас у меня

**Comment by haizrul** [comment]
> Hello,
> 
> Sometimes, invidious is unable to retrieve statistics from a video: views, comments, likes, dislike are at 0, even when it is actually higher on the original video, the channel pic is broken and give a 404 error and the comments list is empty.

From my experience with my instance, that problem happen when google is rate limiting/blocked the instance. Should be okay if you use https://anti-captcha.com.

**Comment by stemy2** [comment]
> > Hello,
> > Sometimes, invidious is unable to retrieve statistics from a video: views, comments, likes, dislike are at 0, even when it is actually higher on the original video, the channel pic is broken and give a 404 error and the comments list is empty.
> 
> From my experience with my instance, that problem happen when google is rate limiting/blocked the instance. Should be okay if you use https://anti-captcha.com.

Is it really legal ?

**Comment by haizrul** [comment]
> Is it really legal ?

Don't really know about that, but it solved the issue.

**Comment by Perflyst** [comment]
It is probably against the Google ToS but I wouldnt call that "illegal"
