### ISSUE TITLE
Suggestion, pinned player

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#1044]
Option to enable pinned player in a corner of the screen while scrolling through comments so you can view video and comments at the same time. (with a couple size settings on the pinned player?)

**Comment by elypter** [comment]
not for or against this feature but you can just open it in a new window and then place them side by side

**Comment by nathgit** [comment]
youtube has this feature & it would be nice to see in this.

**Comment by SamantazFox** [comment]
Is this still relevant, given that most browsers implement picture in picture nowadays?
