### ISSUE TITLE
My way of redirecting youtube to invidious. Add it to the docs?

### ISSUE THREAD

**Issue by rakamanja** [iv-org/invidious#1052]
I use the Redirector extension (the one by Einar Egilsson - that's not me). It's available for, at least, chrome and firefox but I haven't checked other browsers. 

With my settings it redirects youtube urls on the address bar, searches through the search bar and embedded videos in iframes (like the ones on 4chan).
I find this setup to be very nice. I keep the channels I like organized in my bookamarks (with the youtube url) and when an instance is down I only have to change the Redirector rule.

The Redirector rule is as follows:
Decription: `Anything you want`
Example url: `www.youtube.com/123`
Include pattern: `www.youtube.com/(.*)`
Redirect to: `https://invidio.us/$1`
Pattern type: Mark `Regular expression`
In advanced options...
Apply to: Mark `Main window(address bar)` and `IFrames`

After writing this I noticed that the extension is linked on the [wiki](https://github.com/omarroth/invidious/wiki/Extensions) but there are no listed settings for it. Configuring this extension might be hard for some people.

**Comment by r-a-y** [comment]
@rakamanja - I removed Redirector from the Extensions wiki page because Redirector is a general purpose redirecting extension, which doesn't specifically target Invidious.

You could technically use any redirecting extension to accomplish the same thing.

It might be handy to have another wiki page to outline settings for usage with other extensions like Redirector though.

**Comment by mendel5** [comment]
@rakamanja @r-a-y 
Previously I also used the [Redirector](https://addons.mozilla.org/de/firefox/addon/redirector/) add-on for Firefox.
In my opinion there is an even better add-on for redirecting requests for YouTube.com to Invidious:
* [Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) add-on for Mozilla Firefox
* [Privacy Redirect](https://chrome.google.com/webstore/detail/privacy-redirect/pmcmeagblkinmogikoikkdjiligflglb) add-on for Google Chrome

**Comment by r-a-y** [comment]
Privacy Redirect is already listed on the Extensions wiki page: https://github.com/omarroth/invidious/wiki/Extensions

**Comment by mendel5** [comment]
You're right. Thanks!

**Comment by mendel5** [comment]
Maybe this issue can be closed because the addon is already listed in the docs?

**Comment by r-a-y** [comment]
Only the OP, rakamanja, or omarroth can close this issue.

**Comment by Seirdy** [comment]
If you use HTTPS Everywhere, you can create a custom rule for it instead of getting an additional addon. On youtube.com, click "See more" > "Add a rule for this site" > "Show advanced". It supports the same regex syntax as Redirector.
