### ISSUE TITLE
[Feature request] End screen related videos

### ISSUE THREAD

**Issue by narcolepticinsomniac** [iv-org/invidious#106]
NBD, but sometimes it's useful when YT embeds show half a dozen thumbnails for related videos once the current video ends. If there's an API, obviously that'd be the way to go, but I imagine it wouldn't be too difficult to make one of your own that'd return even more relevant suggestions.

**Comment by omarroth** [comment]
I think on YouTube the recommended videos at the end screen are the same ones it would recommend on the right-hand side, so it shouldn't be too hard to add. I don't think I could compete with YouTube's recommendation engine at this point, so I probably will just use what I mentioned earlier.
