### ISSUE TITLE
No Picture-in-Picture button in Firefox desktop

### ISSUE THREAD

**Issue by Bout2GitIt** [iv-org/invidious#1063]
Firefox recently introduced a new [Picture-in-Picture feature](https://support.mozilla.org/en-US/kb/about-picture-picture-firefox) in their desktop browser.

With the new Picture-in-Picture mode, video players get a small blue button. When the button is pressed, the video moves into a new floating window. It's great!

But on Invidious, the blue button doesn't appear. I can still get into Picture-in-Picture mode by right-clicking the video and selecting "Picture-in-Picture." But where's the blue button?

**Comment by agraven** [comment]
The blue button shows up for me, both in my self-hosted instance and invidio.us

**Comment by ExpandingMan** [comment]
I can confirm that I do indeed see the blue picture-in-picture button in firefox on manjaro, ubuntu and windows on all invidious instances I've seen.

**Comment by ssokolow** [comment]
The blue button is buggy. Sometimes, it just doesn't show up. I've seen that happen on plain old YouTube too.

**Comment by Mennaruuk** [comment]
This seems to have been fixed by early 2021.


https://user-images.githubusercontent.com/52135169/106369688-92a09480-6321-11eb-947b-7358b0f0b48d.mp4

**Comment by SamantazFox** [comment]
Closing, as this has been fixed by Mozilla.
