### ISSUE TITLE
Specific link causes error

### ISSUE THREAD

**Issue by narFnarF** [iv-org/invidious#1073]
Hi

I don't know if it's a known issue already, but I have a link that consistently produces errors.

If you open this link: https://invidio.us/watch?v=4QtgpzBwcNo

You'll see this error: 
`Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com.`

I'm not sure but I think this link was a livestream? Maybe it's related but I'm not sure because other livestreams usually work fine.

I found the link on this channel: https://invidio.us/channel/UCGIFf8o_h0uescDO-_FcOVg

**Comment by Perflyst** [comment]
Yes, this was a livestream `Streamed live 15 hours ago`
Other recorded and published livestreams work, example: https://invidio.us/watch?v=5j06g0TE_Ao

**Comment by narFnarF** [comment]
It's strange because other livestream recordings usually work fine.
