### ISSUE TITLE
middle mouse button click inside player pauses the video

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#1074]
the middle mouse button behaves like a left mouse button click which it should not. an [issue at the videojs repo](https://github.com/videojs/video.js/issues/4689) states that it is already fixed. is this a regression or undetected instance of the bug or does invidio.us use an outdated version?

im using firefox on windows10

**Comment by omarroth** [comment]
I can reproduce this on the example player [here](https://videojs.com/city), so I expect it's a regression in Videojs.
