### ISSUE TITLE
CURRENT_VERSION = {{ "#{`git describe --tags --abbrev=0`.strip}" }}

### ISSUE THREAD

**Issue by hhuseyn** [iv-org/invidious#1088]
Hello i try install invidous api only branch. But GET CURRENT_VERSION = {{ "#{`git describe --tags --abbrev=0`.strip}" }} error.
I using Ubuntu 18.04.3 (LTS) x64 and you script all commands using step step. But get this error, How can fix this ?
My crystal version

**Comment by leonklingele** [comment]
Works fine for me, are you by chance building from a release tarball? Make sure a `.git` folder exists at the root of the project. What are your build commands?

**Comment by hhuseyn** [comment]
i install docker,docker-compose1.25.4,crystal 0.33.0  then i create git  repostories with api-only and clone api-only then cd /home/invidious/invidious command:docker-compose build and show this error.


Error: error executing command: git describe --tags --abbrev=0, got exit status 128
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1

but i install master branch not showing this error.

**Comment by Craeckie** [comment]
Same here, I'm using the docker-compose.yml to build directly from github:
```
Step 10/22 : RUN crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"
 ---> Running in cba4d222145b
fatal: No names found, cannot describe anything.
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:64:25

 64 | CURRENT_VERSION = {{ "#{`git describe --tags --abbrev=0`.strip}" }}
                              ^
Error: error executing command: git describe --tags --abbrev=0, got exit status 128
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1
Error creating invidious!
```

This is my config:
```
build:
      context: https://github.com/omarroth/invidious.git
      dockerfile: docker/Dockerfile
```

It's probably because compose only creates a shallow clone (`--depth 1`). It would be great if support for this could be added, so I don't have to update the repository to get the current version.

**Comment by Craeckie** [comment]
Seems like you've already struggled with this before: #766
Not sure just getting the version is worth the effort.. maybe store the current version in a file?

**Comment by mshavliuk** [comment]
I ran into same error after I added the https://github.com/omarroth/invidious.git as a git submodule to my main project
```bash
git submodule add https://github.com/omarroth/invidious.git
```

The command above pulls the repository and write it into `./invidious` dir. Thus, the `./invidious/.git` is not a git directory with all necessary metadata, but just a text file with the following content:
```txt
gitdir: ../.git/modules/invidious
```

So the following line does not actually copy the proper git files:
https://github.com/omarroth/invidious/blob/8ed1c77e47d489637bebc48e556a4ca525bbd65d/docker/Dockerfile#L15

**Comment by SamantazFox** [comment]
Closing, as the `api-only` branch is not maintained anymore. Please use `master` instead.
