### ISSUE TITLE
Player UI not disappearing after changing video quality

### ISSUE THREAD

**Issue by psychedelic-fox** [iv-org/invidious#1090]
as shown in this [screenshot](https://imgur.com/M0305qT.png), the player information and interactive UI will not fade back out after interacting with it.

if it is not touched while playing a video, it disappears after a few seconds like normal. for example, if video quality is changed from "auto" to "720p", it will not disappear for the rest of the video.

**Comment by gwennshinguji** [comment]
to add onto this, i have tested this using both https://invidious.snopyta.org/ and https://invidio.us/

**Comment by Latrolage** [comment]
bump
