### ISSUE TITLE
Bug: YouTube channel URL not loading channel page but youtube startpage

### ISSUE THREAD

**Issue by gloschtla** [iv-org/invidious#1091]
If you click on https://invidio.us/c/channelUsername ([example](https://invidio.us/c/eingeSCHENKTtv)), you will wrongly be forwarded to invidio.us while being on youtube.com you correctly arrive to the linked channel page.

The URL /user/username works ([example](https://invidious.snopyta.org/user/wwwKenFMde))

**Comment by omarroth** [comment]
Should be fixed with b37f51bd7f5c8bc921a72ab3e549e878746e98de.
