### ISSUE TITLE
[Feature Set Request] Make invidious usable in teaching

### ISSUE THREAD

**Issue by cstamas** [iv-org/invidious#1103]
In general, YT is not meant for users under 13, typically grade school pupils. Still, video materials are of great value in teaching. In current COVID-19 pandemic situation, almost all pupils are stuck doing "remote classes" (at least here in Europe).  Hence, Invidious could be a cool application to offer "curated" videos for pupils in safe manner, and not breaking ToS of YT.

- teachers could still use YT to create unlisted videos, use YT Studio, their smartphones to create video content.
- pupils (13-) could go to an Invidious instance (class wide, school wide or any kind) to watch the course related videos, but at the same time not breach ToS of YT, not be distracted by YT commercials, the "related videos" and inappropriate content (only curated videos would be accessible).

I tried on my local dockerized instance to achieve this, so far good but still lacking some features:

- [ ] Support "unlisted" videos add to playlists (https://github.com/omarroth/invidious/issues/1101)
- [ ] Make possible to hide "Watch on YT" link (kids should not be able to get to YT)
- [ ] Optionally, hide the "like/dislike/view" stats, are irrelevant

What is cool so far, as I could do it locally:

- [x] Turn off "Popular" and "Trending" links, instance should "offer" only explicitly added videos (eg. on playlists)
- [x] Create course related playlists (well, partial success, as I could not add "unlisted" videos)
- [x] Disable "Related videos" -- irrelevant, or make it choose from current playlist (ie. course related)
- [x] Disable comments -- irrelevant, pupils will discuss the video on class (and again, they are grade school pupils, most probably not having reddit accounts)

So, in the end, this would be "best of two worlds", as:
- tutors could still use YT and YT Studio to produce (usually unlisted) video content, hence smartphones and all that could be used as now
- pupils would not be exposed to YT commercials, distracted or get to inappropriate videos, they would have access to a curated, topic/course related videos ONLY
- ideally, the invidious instance would be public, so no need for consumers (pupils) account/registration, just for content creators (teachers), as they create/update course related playlists
- make playlists available to anonymous pupil users (did not try this feature).

**Comment by elypter** [comment]
while i would welcome those changes couldnt you at least temporarily download those videos and distribute them by file hosting or a video gallery software?

**Comment by cstamas** [comment]
We have 2 actors:
- teacher(s)
- kids

By having this, teacher (each producing new material) would just need to create content, and add it to course playlist. Nothing more.

By doing like you describe, we would need a third actor, "admin", who would perform these steps (download, upload). Given classes happen on daily basis, this would be real chore for "admin". Not to mention the need for storage as well...

**Comment by elypter** [comment]
but you need a server anyway for invidio.us and you need to upload the videos to youtobe too regardless of whether you feel the need for an admin. you really only need youtube if you expect a high bandwidth or quota. nothing against you plan. its great that you make teaching material available for everyone im just giving ideas for a workaround if it cannot be done with invidio.us

**Comment by cstamas** [comment]
IMO, invidious is "almost there" :smile: Instance could be run on a minimal 5US$ droplet, in docker with constraints (AFAIK, currently are some RAM issues, see https://github.com/omarroth/invidious/issues/1051) and done.

If media needs to be hosted as well, that's probably a different story, and would become a constant battle with growing storage, or would complicate things involving multiple services or who knows what. In short, more complication and probably more costs as well.

**Comment by cstamas** [comment]
Related https://github.com/omarroth/invidious/pull/1112
