### ISSUE TITLE
Make invidious to work with SyncPlay

### ISSUE THREAD

**Issue by OrionRandD** [iv-org/invidious#1109]
Hi, omarroth,
Could you make invidious to work with SyncPlay?
Thx
https://syncplay.pl/

**Comment by omarroth** [comment]
What changes would need to be made to support SyncPlay?

**Comment by OrionRandD** [comment]
I think I can add a invidious there in the preferences. I will see...
Thx anyway.

**Comment by TheFrenchGhosty** [comment]
Out of scope.
