### ISSUE TITLE
The "single file cluster" could use some refactoring?

### ISSUE THREAD

**Issue by grkek** [iv-org/invidious#1121]
### Problem description

Hi, I was browsing through the chaos that is the main file of the invidious web app and since I have experienced the same problem with the chaotic route distribution I had to fork the Kemal framework and add additional features to it which lead me to creation of the [Grip](https://github.com/grip-framework/grip) framework.

### Suggestion

My suggestion is that the current code can be ported over to Grip with which you could benefit by having a file structure, better routing mediums, additional features like route grouping and object oriented distribution of your endpoints, pipes, etc.

**Comment by omarroth** [comment]
PR welcome :)

**Comment by grkek** [comment]
> PR welcome :)

Sounds lovely to me

**Comment by TheFrenchGhosty** [comment]
Fixed in #1399 #1403 #1420 by @matthewmcgarvey

**Comment by grkek** [comment]
@TheFrenchGhosty I don't see how this resolves the issue of a one single 2000k+ line file having all of the routes and logic.

**Comment by TheFrenchGhosty** [comment]
@grkek Because this single file has been replaced by multiples one

**Comment by matthewmcgarvey** [comment]
@grkek @TheFrenchGhosty it hasn't been fully pulled out. There's just sooo much code that I wouldn't dare do it in one PR.
