### ISSUE TITLE
Bug: could not extend file "base/1648927386/2353465378.6": No space left on device

### ISSUE THREAD

**Issue by Starfruit515** [iv-org/invidious#1127]
Encountered this bug when using `Invidition` add-on for firefox browser to open a youtube link, not sure if it causes this problem. After this, `invidio.us` seems broken and cannot access any video. When I tried to open more video links, it sometimes shows a message like `cannot access transaction 0` I tried to close the browser and log in again, it shows `Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com.` and I cannot log in. After waiting several minutes, everything is back to normal again.

**Comment by TheFrenchGhosty** [comment]
Instance issue.
