### ISSUE TITLE
https://invidio.us/watch?v=j0EOhF5v48M error

### ISSUE THREAD

**Issue by ousia** [iv-org/invidious#1130]
@omarroth,

https://invidio.us/watch?v=j0EOhF5v48M only displays a link to report a bug.

Many thanks for your help.

**Comment by mendel5** [comment]
Original video here:
* https://www.youtube.com/watch?v=j0EOhF5v48M

**Comment by Hi-Phile** [comment]
The video plays fine, perhaps it's your browser setting?  https://github.com/iv-org/invidious/issues/1314#issuecomment-667644413

**Comment by ousia** [comment]
@Hi-Phile, many thanks for your reply.

The video plays fine now.
