### ISSUE TITLE
https://invidio.us/watch?v=rnZulWumiig&quality=hd720 errors out as unsupported.

### ISSUE THREAD

**Issue by WandeingLagomorph793** [iv-org/invidious#1131]
When I try to load this video, it gives an error of "The media could not be loaded, either because the server or network failed or because the format is not supported.", I've tried several other instances of invidious and none of them worked, accessing it with regular Youtube or Youtube-DL shows clean results, so the video itself hasn't been blocked for copyright or anything.

**Comment by mendel5** [comment]
Links to reproduce the issue:
* https://www.youtube.com/watch?v=rnZulWumiig (original video on YouTube.com)
* https://invidio.us/watch?v=rnZulWumiig (not working)
* https://invidio.us/watch?v=rnZulWumiig&quality=hd720 (not working, as reported by @WandeingLagomorph793 )
* https://invidio.us/watch?v=rnZulWumiig&quality=dash (working :+1: )

Can someone confirm this?

**Comment by williamd1k0** [comment]
Just one thing I noticed: using `quality=dash` fixed all the videos (I tested) that had this bug, but `listen=1` still doesn't work.

**Comment by Hi-Phile** [comment]
https://github.com/iv-org/invidious/issues/1314#issuecomment-667644413
