### ISSUE TITLE
https://www.invidio.us/watch?v=xcRhNy-6iok

### ISSUE THREAD

**Issue by mugdhosapiens** [iv-org/invidious#1134]
Found A Bug

**Comment by mendel5** [comment]
Links to reproduce the issue:
* https://www.youtube.com/watch?v=xcRhNy-6iok (original video on YouTube.com)
* https://www.invidio.us/watch?v=xcRhNy-6iok (not working, as reported by OP)
* https://www.invidio.us/watch?v=xcRhNy-6iok&quality=hd720 (not working)
* https://www.invidio.us/watch?v=xcRhNy-6iok&quality=dash (working :+1: )

Console for https://www.invidio.us/watch?v=xcRhNy-6iok :
* `GET https://r3---sn-ab5l6n67.googlevideo.com/videoplayback?expire=... [HTTP/1.1 403 Forbidden 282ms]`

Seems to be related to https://github.com/omarroth/invidious/issues/1131 .
