### ISSUE TITLE
Unable to Import Subscriptions? (Invidio.us)

### ISSUE THREAD

**Issue by WandeingLagomorph793** [iv-org/invidious#1136]
This is with the xml exported from Youtube itself
If I use import via Invidious it bugs out, but if I use Import Youtube Subscriptions then nothing happens, the page starts its process but nothing happens for a good while. 

On the invidious account I have 9 subscribers, should I remove those? Eventually when it finished I looked back and it was on the subscriptions page, but it was still the same 9 that I had before.

EDIT; It was a subscription list of over 100, but even after cutting it down to less than 80 it gives the "you found a bug in invidious" error

I also see this no matter the preferences I set, it doesn't show any videos at all
https://i.imgur.com/ie8osGD.png

**Comment by TheFrenchGhosty** [comment]
Instance issue.
