### ISSUE TITLE
Some Text Annotations are Blank

### ISSUE THREAD

**Issue by AgentGrady** [iv-org/invidious#1139]
On some videos the annotations are blank with no text even when it seems they should have had text on them. I noticed this when they were first archived back in 2019 and thought that this would be an issue with the player. Though as this doesn’t seem to have happened or be brought up I thought I would raise this issue.

**Comment by Perflyst** [comment]
Can you give an example video?

**Comment by TheFrenchGhosty** [comment]
Not an invidious bug.
