### ISSUE TITLE
Video src url api request not found

### ISSUE THREAD

**Issue by hhuseyn** [iv-org/invidious#1142]
Hi.I using invidious for get video src url.example:https://invidio.us/api/v1/videos/tzi6tkCbHBc.
But this video and all other vevo videos src url not working.if i open this example video in invidious with dash(https://invidio.us/watch?v=tzi6tkCbHBc&quality=dash) this video work.How can i using this api request get video src url?.

**Comment by Perflyst** [comment]
Try to use another instance: https://invidious.13ad.de/api/v1/videos/tzi6tkCbHBc
This appears to be working for me with 13ad

**Comment by TheFrenchGhosty** [comment]
Instance issue.
