### ISSUE TITLE
Videos have wrong title

### ISSUE THREAD

**Issue by Justin-CB** [iv-org/invidious#1146]
The title in the <title> tag is often wrong. It seems that it's always an actual video's title, tho.

**Comment by NoVa-UX** [comment]
Can confirm...I sometimes like to listen to music on here just whenever I feel like it.  And for example Josh A's DISGRACE turns into "Billey Ellish rejected THIS rapper" or something odd like that

**Comment by mendel5** [comment]
@NoVa-UX Do you mean this video?
* https://www.youtube.com/watch?v=DYcUt0DGK6w
* https://www.invidio.us/watch?v=DYcUt0DGK6w

Does the error occur in the "normal" video mode or the "listen" mode? e.g. this one:
* https://www.invidio.us/watch?v=DYcUt0DGK6w&listen=1

**Comment by Justin-CB** [comment]
I think it happens in both. I noticed a couple times that the wrong title was a video that I'd watched recently, if that helps any.

**Comment by TheFrenchGhosty** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/1285
