### ISSUE TITLE
Tor instance is not working properly

### ISSUE THREAD

**Issue by mastercoldcoder** [iv-org/invidious#1149]
Hello, I’m reporting a recurring bug. When I go to the following instance:
http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion
I can play videos without problems, but when I log in with my username I can no longer watch any video...
The media could not be loaded...... i do not use proxy for charging videos on my account.
What is the problem ?
I still wanted to thank you for your excellent work and plan to start programming soon
Thank you very much for your great work !!

**Comment by TheFrenchGhosty** [comment]
Instance issue.
