### ISSUE TITLE
[Feature Request] Lazy Loading Images

### ISSUE THREAD

**Issue by haizrul** [iv-org/invidious#1162]
https://invidio.us have a lot of images on all pages. I think its good idea to implement lazy load for all images so that the loading speed will be much faster especially for mobile users. Implementing lazy load for images also can save a lot of server bandwidth when a user does not scroll to the bottom of the page, the thumbnails images of related videos will not be loaded all at once. Just a suggestion to make this website more user friendly. Cheers.

**Comment by elypter** [comment]
i wonder if jpgs could be converted to progressive jpgs on the fly and if browsers could pause loading the jpg once it loaded the low res version until you scroll down and then load the rest.

**Comment by haizrul** [comment]
> i wonder if jpgs could be converted to progressive jpgs on the fly and if browsers could pause loading the jpg once it loaded the low res version until you scroll down and then load the rest. thats probably a feature to better implement in the browser.

Great idea. 👍

**Comment by cloudrac3r** [comment]
Cool idea, but doing this with JavaScript would remove all images for people that have scripts turned off. Doing this without JavaScript? It's not quite here yet. https://caniuse.com/#feat=loading-lazy-attr

**Comment by Gert-dev** [comment]
Native lazy loading as proposed by @cloudrac3r sounds like a good idea, as it's fairly low effort, works without JavaScript, adding the attribute will work for browsers supporting it, and it should gracefully degrade to the current behavior for other browsers.

**Comment by unixfox** [comment]
done
