### ISSUE TITLE
All annotaions have the same tooltip text

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#1164]
noticed in [this video](https://invidio.us/watch?v=ypMCK7NcbxU&autoplay=0&continue=0&dark_mode=true&listen=0&local=0&loop=0&nojs=0&player_style=youtube&quality=hd720&thin_mode=false)

**Comment by TheFrenchGhosty** [comment]
Not an invidious bug.

**Comment by elypter** [comment]
i then assume it is a bug in videojs. could you tell me where it goes wrong so i submit a bug report on their page?
