### ISSUE TITLE
Do you get this error too?

### ISSUE THREAD

**Issue by CSDUMMI** [iv-org/invidious#1165]
This is a pretty simple issue:
When I open: https://invidio.us/watch?v=t3217H8JppI
I get an error:
Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. 

I don't see anything special about this video in particular.
I have reloaded the page and got the same error again
and can still watch other videos on Invidious, just not this particular one.

**Comment by flori4nk** [comment]
That sometimes happens to me too, I just force reload the page using CTRL+SHIFT+R (bypasses cache) and it works again.

**Comment by stemy2** [comment]
Workaround doesn't work for me.

**Comment by TheFrenchGhosty** [comment]
Instance issue.
