### ISSUE TITLE
Video not loading with "The media could not be loaded, either because the server or network failed or because the format is not supported."

### ISSUE THREAD

**Issue by WandeingLagomorph793** [iv-org/invidious#1167]
https://invidio.us/watch?v=dMfakO0jmr4

When I load the video all I get is the "The media could not be loaded, either because the server or network failed or because the format is not supported.", trying it with instances like Snopyta doesn't work and reloading the page doesn't fix i either, this is both while logged in or not too.

**Comment by williamd1k0** [comment]
Try using `quality=dash`.

Possibly related to #1131

**Comment by Noryub** [comment]
> @WandeingLagomorph793 is quality=dash working for you?

This, quality=dash no longer works.
The issue is really annoying.

**Comment by Zero3K** [comment]
https://www.invidio.us/watch?v=5C8yvJUVB-0 is also a video that shows the mentioned error message.

**Comment by mpaunovic** [comment]
This one too...

https://www.invidio.us/watch?v=MuxnH0VAkAM

**Comment by Zero3K** [comment]
The video plays but I am also getting "could not extract video info".

**Comment by TheFrenchGhosty** [comment]
Instance issue.
