### ISSUE TITLE
streamlink + invidious plugins

### ISSUE THREAD

**Issue by OrionRandD** [iv-org/invidious#1168]
Is that possible to make invidious to work with streamlink?
Since there is no streamlink plugin for invidious?
e.g.
$ streamlink https://invidio.us/watch?v=CvKywSV3fiI&pbjreload=10
$ error: No plugin can handle URL: https://invidio.us/watch?v=CvKywSV3fiI

$ streamlink --plugins

**Comment by TheFrenchGhosty** [comment]
Streamlink issue.
