### ISSUE TITLE
Docker instructions: Wrong or incomplete?

### ISSUE THREAD

**Issue by kalak-sudo** [iv-org/invidious#1172]
Hi everyone! 

I have been trying for 4 days to deploy the docker image, with no success. 

I have tried: 

`docker run omarroth/invidious`

And

`
docker run -p 80:3000 omarroth/invidious`

And always get the following error:

```
Unhandled exception: (no message) (DB::ConnectionRefused)
  from ???
  from ???
```

What I am doing wrong??  

Thanks in advanced.

K.

**Comment by unixfox** [comment]
Try to use docker-compose instead.

**Comment by kalak-sudo** [comment]
Thanks for your answer! I will try it later!

**Comment by Perflyst** [comment]
Was your test successful?

**Comment by kalak-sudo** [comment]
Nope. I just gave up with this. I will try it again when I have some time, and I hope everything is easier and goes well :)

**Comment by omar-elnaggar** [comment]
@kalak-sudo after you clone invidious go into the cloned folder and run `docker-compose build`

After you build it you can either run `docker-compose up` or run it as detached `docker-compose up -d`
