### ISSUE TITLE
Invidious Not Syncing When Using Services Like cytu.be (synchtube) 

### ISSUE THREAD

**Issue by grravity** [iv-org/invidious#1173]
So, not entirely sure if this is an Invidious issue or an issue with the extension I am using ([Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect)), I brought this up with the developer of that extension on his Github in a [slightly related issue](https://github.com/SimonBrazell/privacy-redirect/issues/27) (towards the bottom).

To put it **simply**, when using cytu.be, if I have Privacy Redirect set to redirect YouTube to Invidious, the video plays but does not sync the time with the cytu.be server, so if I refresh the page, the video restarts making it out of sync with everyone else watching. This completely defeats the purpose of cytu.be (FOSS fork of synchtube). If I disable redirects with Invidious, and use YouTube, it works, but that's not ideal if Invidious could work. I will copy-paste my statement that's a bit more detailed from my issue on privacy redirect.

**More detailed:**
Basically if I open cytu.be on Firefox, then open on Chromium, Firefox has the Privacy Redirect extension (Chromium doesn't), if I add a video into cytu.be using the YouTube URL, it appears and starts playing on both Chromium and Firefox (on Firefox it redirects through the Invidious embed as expected and as it should **without the whitelist on**). 
Now if I wait say a minute into the video, and refresh the page on Firefox, it starts the video back to 0:00 on Firefox (and obviously continues on Chromium no issue). 
Now as Chromium is continuing, and Firefox is playing from 0:00, if I disable the "Invidious Redirect" option in your privacy redirect extension on Firefox, and refresh the page, it starts playing through YouTube as expected.. but, when playing through YouTube it IS in sync with the chromium browser now (it jumped up to 4:00 or wherever the Chromium instance is at, unlike it did when Firefox was redirecting the embed through Invidious).
I don't think it has anything to do with my [Firefox user.js](https://raw.githubusercontent.com/grravity/firefox-config/master/user.js) or anything as when I disable the Invidious redirect in your extension it works no issues, which makes me think it's either your extension or Invidious. But I could be wrong.

Again, this is all with the whitelist **disabled**, just running through Invidious.
I know this kinda "defeated the purpose" of implementing the whitelist, but sometimes Invidious does have slowdowns depending on your instance, and YouTube would be more coherent. But I know not everyone would want to whitelist YouTube IF Invidious can work, the Whitelist is nice to have if Invidious can't work.
Invidious IS working in this situation, it's just having trouble with syncing. Again, not sure if this is an Invidious issue or a cytu.be issue (I'm using Snopyta's Invidious instance if that helps for more granular troubleshooting). But either Invidious isn't working properly with sync, or your extension/embeds implementation is having trouble with sync. It would be very nice to be able to use Invidious through cytu.be though in sync if possible.

**Comment by TheFrenchGhosty** [comment]
Out of scope, use case is too small.
