### ISSUE TITLE
Subscriptions aren't updating on self-hosted copy?

### ISSUE THREAD

**Issue by ChaseHall** [iv-org/invidious#1175]
I have a self hosted copy of invidious, my subscriptions page isn't updating.

The current list is from when I created my account, [screenshot here](https://i.imgur.com/88ackBb.jpg)

and this is what [the public instance of invidious shows](https://i.imgur.com/6Ip6fqz.jpg)

Subscriptions are identical across both sites.

Any ideas?

**Comment by Perflyst** [comment]
Maybe your IP got blocked. Check the following:
https://github.com/omarroth/invidious/issues/811#issuecomment-539943148
https://github.com/omarroth/invidious/issues/811#issuecomment-540017772

**Comment by ChaseHall** [comment]
That didn't appear to help. I was able to grab the entire curl, as opposed to it error'ing. YouTube still plays videos with no captcha as well.

Video playback  on my instance also works, just the subscriptions don't update.

**Comment by ChaseHall** [comment]
@Perflyst What's also strange is I can see new videos on the search page, but not subscriptions, got any ideas? I'm totally stumped. Am i missing some sort of cronjob or something that needs to run?

**Comment by unixfox** [comment]
Try to open a YouTube channel on your instance and see if it works. If it doesn't work then your IP is blocked.

**Comment by ChaseHall** [comment]
@unixfox I am able to look at channels and play their latest videos, it's just that, that video won't show in the subscriptions tab.

**Comment by 999eagle** [comment]
I have the exact same issue on my instance. Subscriptions aren't updating, but my IP doesn't seem to be blocked.

**Comment by 98WuG** [comment]
Can also confirm same bug. I can search, look at channels, and play their latest videos, but subscriptions are not updating.

**Comment by chantisnake** [comment]
I have the same problem on https://invidio.us/. I can watch video, but I cannot see my subscription vidos.

**Comment by ChaseHall** [comment]
Appears to work on latest version. Will reopen if I encounter it again.

**Comment by ChaseHall** [comment]
Reopening since it seems to freeze randomly, am on 0.20.1-8c65b8c.

**Comment by ChaseHall** [comment]
Closing (again), as it appears to be fixed running [several maintenance crontab jobs](https://git.chasehall.net/NebulaHost/Scripts/src/branch/master/Crontabs.txt#L88-L93).

**Comment by unixfox** [comment]
For the sake of archiving or if one doesn't want to take time to filter only the interesting part, here are the crontabs:
```
@hourly psql invidious -c "DELETE FROM nonces * WHERE expire < current_timestamp;" > /dev/null
@hourly psql invidious -c "TRUNCATE TABLE videos;" > /dev/null
@daily vacuumdb --dbname=invidious --analyze --verbose --table 'videos' > /dev/null
@daily reindexdb --dbname=invidious > /dev/null
```

**Comment by LennyPenny** [comment]
are there any plans on having these issues fixed inside of invidious? These crontabs are not easily added to a docker setup and might have some side effects?

**Comment by thatHguy** [comment]
I am having this issue on a fresh local install. 

`systemctl restart invidious.service `

Running the above command in a terminal appears to update the subscriptions page, but then it won't update again until the invidious service is manually restarted again. It's not really a solution.
