### ISSUE TITLE
Allow Access-Control-Allow-Origin header for RSS feeds

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#1186]
I noticed that this response header seems to be [blacklisted in invidious.cr](https://github.com/omarroth/invidious/blob/750ef296c63d20dfcd8ea311a44c5cfa28ca196e/src/invidious.cr#L59).

Using this header for RSS feeds specifically would make it possible for statically hosted JavaScript pages, such as RSS feed readers, to access them directly.

**Comment by omarroth** [comment]
The code you linked has a bit of a misleading name. `RESPONSE_HEADERS_BLACKLIST` refers to which headers are prevented from being _forwarded_ from YouTube through Invidious, not headers Invidious is blacklisted from sending.

Would you mind providing an example of a project that needs CORS access on RSS feeds? Most feeds don't provide them so I would be surprised if there's something like an RSS reader that won't work.

**Comment by tadan0** [comment]
Apologies for the misunderstanding with the blacklist!

There are a few JavaScript RSS parsers (notably [rss-parser](https://github.com/rbren/rss-parser)) that usually depend on simple proxies which add the appropriate header to get feeds to a client running in a web browser, but it adds a more centralized middleman to the whole process. Maybe I'm overthinking things, but considering that the RSS feeds are publicly accessible from Invidious in the first place, it seems like making it possible to be fetched by browsers would just help to benefit any serverless web readers out there.

**Comment by SamantazFox** [comment]
Closing as there doesn't seem to be any activity related to this issue, and the OP's account has been deleted, meaning that we can't get more details on the problem/feature requested.
