### ISSUE TITLE
/api/v1/playlists/:plid returns wrong authorId

### ISSUE THREAD

**Issue by lekma** [iv-org/invidious#1190]
example:
https://invidio.us/api/v1/playlists/PLYH8WvNV1YEn9PkI2stxJWMs8GRit66Rz

'authorId' does not return the correct value and returns the content of 'author' instead (see https://invidio.us/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw for reference).

**Comment by oleg131** [comment]
I get 
```
{"error":"Playlist does not exist."}
```
for the above example

**Comment by lekma** [comment]
it seems invidio.us is blocked right now but you can try with any other instance still up.

for example:

https://invidious.snopyta.org/api/v1/playlists/PLYH8WvNV1YEn9PkI2stxJWMs8GRit66Rz

https://invidious.snopyta.org/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw

**Comment by omarroth** [comment]
Appears to have been fixed as part of 8c65b8c16fe06375b7b8c29514a065626a12fe04.
