### ISSUE TITLE
New Feature: Leave comments in Invidious

### ISSUE THREAD

**Issue by cyberchief1984** [iv-org/invidious#1191]
I would like the ability to leave anonymous comments to videos in Invidious. Can this even be done?

**Comment by trymeouteh** [comment]
I use the Dissenter extension by Gab to do this. I made a request to embed youtube dissenter comments into invidious but it was rejected for now since dissenter is not that popular.

**Comment by TheFrenchGhosty** [comment]
Out of scope.
