### ISSUE TITLE
Clickable timestamps in video descriptions don't work properly

### ISSUE THREAD

**Issue by mascherone108** [iv-org/invidious#1192]
They only seem to work when clicked on from comments
Edit: example here https://invidious.13ad.de/watch?v=wf807bOwsyU

**Comment by YeldhamDev** [comment]
I've seen cases where if there's too many timestamps, they will all break as well.

**Comment by matthewmcgarvey** [comment]
@mascherone108 Is this issue still happening? I've looked at a couple videos with timestamps and found no issues. The link you gave no longer works and I'm not able to load that video id in any of the instances I tried for whatever reason.

Here is a video I tried on a couple different instances.
https://yewtu.be/watch?v=FDMq9ie0ih0

**Comment by mascherone108** [comment]
@matthewmcgarvey the same video, but on snopyta instance, works as it should (check here: https://invidious.snopyta.org/watch?v=wf807bOwsyU) but last time I checked on yewtu.be, clicking the timestamps made the video go to max duration, effectively stopping the video
