### ISSUE TITLE
Improve error messages / error pages

### ISSUE THREAD

**Issue by girst** [iv-org/invidious#1194]
It'd be great if error pages would have a link to the original youtube URL and/or a small selection of reliable other instances. This would allow the user to watch the video elsewhere.

Instances should probably have to opt-in to being listed on invidio.us (e.g. by asking for inclusion themselves with a PR/issue), since traffic to them would likely increase. maybe instances.invidio.us or uptime.invidio.us can be queried before suggesting an alternative instance.

Also, when the instance is blocked, visiting a /channel/ page returns `This channel does not exist.`, which is not true. this was fixed for /watch with 0e1d6aa85c40d071270092de0195a75f928e3506, but not for other pages.

**Comment by exilexi** [comment]
Yep I’d love a link to the original youtube or other instances, or even better, other P2P formats ( #328)

**Comment by SamantazFox** [comment]
Closing, as this has been fixed ("next steps" message, improved bug page, etc...)
