### ISSUE TITLE
Add grey filter over thumbnails of watched videos, do not hide from feed.

### ISSUE THREAD

**Issue by Zebrazilla** [iv-org/invidious#1195]
Please add grey filter over thumbnails of watched videos, I don't want them to be completely hidden from my feed.

_Originally posted by @utlasidyo in https://github.com/omarroth/invidious/issues/129#issuecomment-471329015_

**Comment by Zebrazilla** [comment]
Didn't find much other than this comment about it when looking for issues sharing this sentiment.

I would like to see this also and I would suggest adding in preferences the ability to toggle visualizing watched videos; which if active will pull entries from watch history and add a grey filter/fade and/or watched icon to show that a video has been watched.

This would be a great middle-ground for people who would like to clean up their subscription feed without hiding watched videos.

It would also be great if this was shown on videos in the related videos sidebar.

**Comment by sdfg2** [comment]
Actually I'd extend this to 'any watched video' in any place.  If I'm watching back a channel that's been going for years it is very confusing to remember/find where I left off in the video list of the channel.
