### ISSUE TITLE
Use speech recognition (if available) to resolve CAPTCHA

### ISSUE THREAD

**Issue by wuniversales** [iv-org/invidious#1208]
I've seen an extension that allows you to use speech recognition (if available) to resolve Google CAPTCHA.

Just "Listen to the audio" and decode what the audio says.
Source: https://github.com/dessant/buster
Firefox extension: https://addons.mozilla.org/en/firefox/addon/buster-captcha-solver/?src=search

It would be interesting to implement something similar in Invidious as an alternative to save money on the use of "anti-captcha.com" or any similar service.

**Comment by rustynail1984** [comment]
This does not work because if your IP is banned due to "very" much requests, then the audio playback does not work with the captcha.

**Comment by wuniversales** [comment]
Apparently there is a tool called "ReBreakCaptcha" that does this in computer scripts.
In case it's of any use ...
https://github.com/eastee/rebreakcaptcha

**Comment by TheFrenchGhosty** [comment]
> This does not work because if your IP is banned due to "very" much requests, then the audio playback does not work with the captcha.
