### ISSUE TITLE
Add Onion-Location

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#1217]
Since TBB 9.5 Onion-Locations are available.
https://community.torproject.org/onion-services/advanced/onion-location/

`add_header Onion-Location "http://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion";`

**Comment by sm01man** [comment]
Its best to use apache to proxy to invidious, just set up a vhost for your instance which proxys to localhost:<invidious port> and then add 
`Header set Onion-Location "https://onionsite.onion"`
to your vhost config.

**Comment by Perflyst** [comment]
Yes I am aware of this, but I want to request this header on https://invidio.us

**Comment by TheFrenchGhosty** [comment]
This is an instance issue.
