### ISSUE TITLE
Create database schema on startup, if it doesn't exist

### ISSUE THREAD

**Issue by RealOrangeOne** [iv-org/invidious#1225]
Currently, when setting up a docker environment, you either have to use the custom container in the repo (which isn't available on dockerhub too), or manually run all the `.sql` files.

Neither of these are especially handy when trying to do updates.

What would be ideal is if the application tried to create the schema on start, and also tried to run any migrations on top, to ensure no DB interaction is required. 

Looks like this is related to (or at least help to solve) #1172 and #976,

**Comment by SuperSandro2000** [comment]
> Currently, when setting up a docker environment, you either have to use the custom container in the repo (which isn't available on dockerhub too), or manually run all the .sql files.

No, see #1211
