### ISSUE TITLE
Cannot open localhost:3000

### ISSUE THREAD

**Issue by pichongas** [iv-org/invidious#1229]
Installed Invidious and deployed on Docker with "invidious-updater" script. According to the script everything was installed correctly and Docker is running, but when I try to access to localhost:3000 page didn't load. I tested with telnet and wget and it tells me "connection refused". Is there any solution for this problem?

**Comment by Perflyst** [comment]
Invidious is probably not running then. Are you using docker or normal installation?

**Comment by TheFrenchGhosty** [comment]
Instance issue.
