### ISSUE TITLE
Broken Storyboard Thumbnail URLs

### ISSUE THREAD

**Issue by samihda** [iv-org/invidious#1231]
Hi, thanks for your work on Invidious!

I just noticed that currently `/api/v1/storyboards/:id` returns thumbnail URLs with incorrect host for some Invidious instances (yewtu.be and invidious.13ad.de for example), which result in Content Security Policy error.

I'm not sure if this is just a misconfiguration on the instance, but in any case, from my quick observation, it looks like it probably has something to do with the string building logic for the host's port and protocol/scheme.

![20200610_18h46m54s_grim](https://user-images.githubusercontent.com/14859913/84295690-6fc73300-ab3a-11ea-8fc3-b7ea79c4ae8f.png)

**Comment by samihda** [comment]
Hmm, so I had a further look. I think for invidious.13ad.de in particular, it's caused by the protocol mismatch in the storyboard image links. That is, the API produces HTTP links instead of HTTPS. I'm guessing it boils down to the logic that [generates the links](https://github.com/omarroth/invidious/blob/ceb252986e2f836f36d2f2d5a54c87ebec607120/src/invidious/helpers/utils.cr#L273-L297). I hope that's helpful.

Here's the results of a GET request to https://invidious.13ad.de/api/v1/storyboards/sPcxB5xJDPQ?height=90 at the moment:

```
WEBVTT

00:00:00.000 --> 00:00:05.000
http://invidious.13ad.de/sb/sPcxB5xJDPQ/storyboard3_L2/M0.jpg?sqp=-oaymwECSEGi85f_AwYI-PL09gU%3D&sigh=rs%24AOn4CLDts09OeJDDI0Ost10xotru381aEA#xywh=0,0,160,90

00:00:05.000 --> 00:00:10.000
http://invidious.13ad.de/sb/sPcxB5xJDPQ/storyboard3_L2/M0.jpg?sqp=-oaymwECSEGi85f_AwYI-PL09gU%3D&sigh=rs%24AOn4CLDts09OeJDDI0Ost10xotru381aEA#xywh=160,0,160,90

00:00:10.000 --> 00:00:15.000
http://invidious.13ad.de/sb/sPcxB5xJDPQ/storyboard3_L2/M0.jpg?sqp=-oaymwECSEGi85f_AwYI-PL09gU%3D&sigh=rs%24AOn4CLDts09OeJDDI0Ost10xotru381aEA#xywh=320,0,160,90

...
```

**Comment by omarroth** [comment]
This will happen if `domain:` isn't set in `config.yml`, since the plugin that provides storyboards will request storyboards *relative to the storyboard URL*. In this case `/api/v1/storyboards/sb/...` which will fail.

**Comment by TheAssassin** [comment]
I've set `domain:` to a value now, but it certainly doesn't fix the issue. My Invidious instance is behind a reverse proxy, and Invidious tries to build URLs with the internal port 3000 (which is not what I use even in the forwarding).

It shouldn't be needed to set `domain:`. Also, I think `domain:` doesn't really cut it, maybe introduce a `base_url` or something instead, the full-qualified root URL on which Invidious is hosted.
