### ISSUE TITLE
API download file ?

### ISSUE THREAD

**Issue by stephane-r** [iv-org/invidious#1249]
Hello community,

I've check the wiki about the API public and auth. If I don't say stupidity, i don't see any API for download videoId.

Does a url exist ? On form action, i see `/latest_version` URL, but maybe an other API exist ?

Thank you for your very very great work :)

**Comment by gloschtla** [comment]
The download function works in the UI of other instances. Regarding the API code, I cannot help.

**Comment by unixfox** [comment]
The API is in the docs: https://docs.invidious.io/api/#get-apiv1stats
