### ISSUE TITLE
The uploader has not made this video available in your country.

### ISSUE THREAD

**Issue by rustynail1984** [iv-org/invidious#1250]
Hi,

my Server is Hosted by OVH UK and i have 2 IP Addresses.

Unfortunately, the Main IP is geographically blocked for many videos. For whatever reason.
My 2nd IP works very well for all videos.
is it somehow possible that invidious uses the 2nd IP instead of the main ip.

Main IP is **eth0**  and second IP is **eth0:0**

**Comment by Perflyst** [comment]
You can replace your default route, see https://unix.stackexchange.com/a/192288
