### ISSUE TITLE
Entity to large

### ISSUE THREAD

**Issue by gregf** [iv-org/invidious#1252]
I am getting an "Entity to large" error while trying to import my large list of YouTube subscriptions.

```
1.2M    subscriptions.json
```

**Comment by unixfox** [comment]
On which website are you getting this error? invidio.us?

**Comment by gregf** [comment]
@unixfox yes invidio.us, sorry should have stated that before.

**Comment by unixfox** [comment]
Could you please try on another Invidious instance: https://github.com/omarroth/invidious/wiki/Invidious-Instances?
This error is probably only specific to invidio.us due to the fact that the official instance is using a setting that restrict the max body size in NGINX.

**Comment by TheFrenchGhosty** [comment]
Instance issue.
