### ISSUE TITLE
Version of lsquic and boringssl used

### ISSUE THREAD

**Issue by tuxor1337** [iv-org/invidious#1257]
https://github.com/omarroth/invidious/blob/1f435522b4c469e0a2c34dfc41da27db93db2803/docker/Dockerfile#L11
For people who are manually compiling invidious without Docker, it would be extremely helpful to know the version of lsquic and boringssl that you use for your `lsquic.a`. Would it be possible to mention these in the README or a similar place?

**Comment by Perflyst** [comment]
You can find it here: https://github.com/iv-org/lsquic.cr

**Comment by tuxor1337** [comment]
I'm asking for the version number of the [LSQUIC](https://github.com/litespeedtech/lsquic) library that is used to generate the `lsquic.a` file. I can't find that information under the link you specified.

**Comment by omarroth** [comment]
The version number is listed [here](https://github.com/iv-org/lsquic.cr/blob/master/src/lsquic/liblsquic.cr#L8-L10) which obviously isn't very easy to find.

The latest release of lsquic.cr and future releases will track the parent library. So for example [v2.18.1](https://github.com/iv-org/lsquic.cr/releases/tag/v2.18.1) is built against the current latest version of lsquic (v2.18.1). There are also build instructions included as release notes that should provide the information you need to build it yourself.
