### ISSUE TITLE
Like/Dislike Videos and comments on Invidious

### ISSUE THREAD

**Issue by trymeouteh** [iv-org/invidious#1259]
It would be cool if you can like or dislike a video on invidious but the like/dislikes are separate from the YouTube like/dislikes. Same for YouTube comments to be able to like/dislike them on invidious.

To also have this federated were all the like/dislikes of a video can be tallied up from all the invidious instances will be amazing.

**Comment by minidogg** [comment]
Put this on requests

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheFrenchGhosty** [comment]
Out of scope.
