### ISSUE TITLE
"Next page" link does not show up in some channels' video listing

### ISSUE THREAD

**Issue by nachanon** [iv-org/invidious#1262]
While I was viewing video info page on Invidio.us, I stumbled on some channel which the video I just viewed) is _much_ older than the one shown at bottommost of the channel's page, and there is no "Next page" link; which should not be possible (unless the alleged video was "unlisted").

I was curious, so I clicked "oldest" link, and other whole lot of old videos shown up (still not including the video I just viewed), again with no "Next page" link at the bottom of the page; even there were supposed to be many pages of videos listing between the newest and oldest page.

This left a whole lot of videos in pages between "newest" and "oldest" inaccessible.

### Exact Steps to Reproduce ###

1. Start a new private browsing session **with JavaScript disabled**
1. Go to this video page: <https://invidio.us/watch?v=XBaL8ME53co>
1. Note down video title and post date ("_Let Yourself Sing - Idina Menzel vs. My Chemical Romance (Mashup)_", 8-Jan-2016)
1. Click on the user who uploaded the video ("_oneboredjeu Mashup_")
1. It would lead to the channel: <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA>
1. You would see that the view is channel's "Videos", and chronological order is "newest"
1. As expected, you won't find the video you noted down in step 3; only videos shared today down to 1-year back
1. Scroll to the bottom of the page
1. **You would _not_ find the "Next page" link**
1. Scroll back to the top of the page
1. Click "oldest" chronological order
1. It would lead to this page: <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=1&sort_by=oldest>
1. Look around; you would find videos shared around 4-years back (and you still won't find the video you noted down in step 3)
1. Scroll to the bottom of the page
1. **You would _not_ find the "Next page" link**

### Workaround ###

A workaround is by adding/changing `page=` query parameter in the URL by hand, and keep shifting number until there is no more video coming up. For example:

In reverse-chronological (default) order...

* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=1> (Has no _Next page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=2> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=3>
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=4> (Has only _Previous page_ link) 
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=5> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=6> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=7> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=8> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=9> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=10> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=11>
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=12> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=13> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=14> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=15>

In forward-chronological order...

* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=1&sort_by=oldest> (Has no _Next page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=2&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=3&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=4&sort_by=oldest>
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=5&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=6&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=7&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=8&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=9&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=10&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=12&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=13&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=14&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=15&sort_by=oldest> (Has only _Previous page_ link)
* <https://invidio.us/channel/UC_sMbyQqtLPZ9WjPcvOpbOA?page=16&sort_by=oldest>

Note that I have not checked whether _all_ off videos shown up on Invidious' listing, or some were missing.

### Compare and Contrast ###

For some reason, other channels are affected by this in different ways. For example:

* <https://invidio.us/channel/JefferzKM> (a.k.a. <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg>)
	
	This channel has _Previous page_ link on its front page, but pagination does not go all the way back.
	
	In reverse-chronological (default) order...
	
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=1>
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=2> (Has only _Previous page_ link)
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=3>
	
	In forward-chronological order...
	
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=1&sort_by=oldest>
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=2&sort_by=oldest> (Has only _Previous page_ link)
	* <https://invidio.us/channel/UCZEToMNeDh49WetzKqIq_fg?page=3&sort_by=oldest>

### System Information ###

Invidious: <https://invidio.us/>  
Browser: Pale Moon 25.8.1 (32-bit binary)  
System: Debian GNU/Linux 7.0 "Wheezy" i386

**Comment by SuperSandro2000** [comment]
You should definitely update your Debian regardless of this issue.

**Comment by NintendoManiac64** [comment]
I'm having this issue occur on the following channel without even having to do anything:
https://invidio.us/channel/chainbearf1

Javascript was enabled, the cache was empty (save for previously loading LinusTechTips as a control for a known-working channel), but it still doesn't work even in a completely different browser (Chrome rather than my usual Pale Moon), but yet a "page 2" definitely exists:
https://invidio.us/channel/chainbearf1?page=2

**Comment by NintendoManiac64** [comment]
Found another channel that's doing the same thing whereby it's just always missing the "Next page" even on a first-time load with javascript enabled in two very different browsers despite a second page definitely existing:

(beware of spoilers if you're an F1 fan) https://invidio.us/channel/formula1

**Comment by NintendoManiac64** [comment]
Interestingly, with the newest updates that makes channel pages work again, the chainbearf1 channel still does not show a "next page" link while the formula1 channel now _does_.


I had also discovered a channel that not only doesn't show a "next page" link when it should, but appending "?page=2" to the URL doesn't even work anymore (it used to before channel paged borked, but now that those are fixed the "?page=2" stopped working for this specific channel dispite many more older videos being present on the channel when viewed on youtube.com).

Beware though, a lot of the content on this channel is risque and NSFW:
https://youtube.com/channel/UCkQYnyP2iPUWfzjHoRMBWKA/videos
https://invidious.snopyta.org/channel/UCkQYnyP2iPUWfzjHoRMBWKA
https://invidious.snopyta.org/channel/UCkQYnyP2iPUWfzjHoRMBWKA?page=2

**Comment by NintendoManiac64** [comment]
Interestingly, with the newest updates that makes channel pages work again, the chainbearf1 channel still does not show a "next page" link while the formula1 channel now _does_.

**Comment by SamantazFox** [comment]
Closing, as this was fixed back in April. #660 still remains, though.
