### ISSUE TITLE
❗️ The Listening mode doesn't work anymore

### ISSUE THREAD

**Issue by gloschtla** [iv-org/invidious#1268]
When I append &listen=1 to the video URL, there is no playback anymore. This is the error message:

_The media playback was aborted due to a corruption problem or because the media used features your browser did not support._

**Comment by Perflyst** [comment]
Check if you have "Proxy videos?" enabled in settings

**Comment by gloschtla** [comment]
This problem still occurs, also on other instances, @omarroth 
https://invidious.sunsetravens.com/watch?v=p5ex6ZC2Yts&dark_mode=true&autoplay=1&listen=1
https://invidious.snwmds.com/watch?v=p5ex6ZC2Yts&dark_mode=true&autoplay=1&listen=1
https://invidious.13ad.de/watch?v=p5ex6ZC2Yts&listen=1

**Comment by seuri** [comment]
Works fine  for me. 
Which OS/browser are you using? 
Have you tried downloading the file and play it in the browser?

**Comment by TheFrenchGhosty** [comment]
This is an instance issue.

**Comment by gloschtla** [comment]
It works again. I just tried on the instance of 13ad.de and here: https://invidio.us/watch?v=p5ex6ZC2Yts&listen=1
