### ISSUE TITLE
Buffering/quality issues with a live stream

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#127]
The live stream I linked to before (https://www.invidio.us/watch?v=RES7_hm1SH8) is buffering often and is low quality.

**Comment by omarroth** [comment]
Is this an issue with all livestreams or only the one linked? There could be a variety of factors. Author is not uploading in good quality, user's internet is slow, etc. Unfortunately it looks like the livestream above has ended, so I can't really test it. Let me know if you encounter this again.

**Comment by Zero3K** [comment]
Here's another stream:

https://www.invidio.us/watch?v=RWpK79dIH4U

**Comment by Zero3K** [comment]
Here's another one https://www.invidio.us/watch?v=8_Gfuzg7zrc.

**Comment by PrasannaVenkadesh** [comment]
Watched couple of LIVE streams from two different Channels. And these two Channels are professional NEWS channels in TamilNadu, India. Video quality of both their live streams on invidious is of low quality, while they are of good quality in Youtube.

Channel 1 Live Stream - https://www.invidio.us/watch?v=VOceN5RWb0s
Channel 2 Live Stream - https://www.invidio.us/watch?v=42G4eRV8P-I

**Comment by Zero3K** [comment]
*bump*

**Comment by Zero3K** [comment]
Bump

**Comment by unixfox** [comment]
> Bump

Can you still replicate this issue?

**Comment by Zero3K** [comment]
Right now its not possible to watch any live streams.

**Comment by unixfox** [comment]
Could you tell us the instance that you used?
Closing as the livestreams are working perfectly.

**Comment by Zero3K** [comment]
Livestreams are failing to play for me when using the invidious.fdn.fr instance.

**Comment by SamantazFox** [comment]
@Zero3K have you tried enabling DASH in the preferences?

**Comment by Zero3K** [comment]
The "Preferred video quality" is set to DASH.

**Comment by unixfox** [comment]
The livestreams work on most instances from the official list: https://api.invidious.io/

For some of them it doesn't work probably due to a misconfiguration with the reverse proxy and we can't fix that on our end. You will have to ask the maintainer to fix it or switch to another instance or run invidious locally.

**Comment by Zero3K** [comment]
I tried invidious.namazso.eu. The livestream I tried worked.
