### ISSUE TITLE
Cant watch videos

### ISSUE THREAD

**Issue by Meandmyfurbies** [iv-org/invidious#1271]
I am using the invidio.us instance and whenever I try to watch a video I get "500 internal server error" or "could not access status of transaction 0". It was working fine for me and then this started happening suddenly.

**Comment by hotsoularrow2** [comment]
Yes, me too. I tried multiple devices and waited an hour, still says the same errors.

**Comment by Perflyst** [comment]
Please check again. At least for me it is working fine again.

**Comment by TheFrenchGhosty** [comment]
This is an instance issue.
