### ISSUE TITLE
Domain Fronting: Invidious Instances -> YouTube Traffic.

### ISSUE THREAD

**Issue by arch-btw** [iv-org/invidious#1272]
Has this been discussed and/or considered? <sup>**[[0](https://www.icir.org/vern/papers/meek-PETS-2015.pdf)][[1](https://www.bamsoftware.com/papers/fronting/)][[2](https://digi.ninja/blog/cloudfront_example.php)]**</sup>.

[0] https://www.icir.org/vern/papers/meek-PETS-2015.pdf (PDF)
[1] https://www.bamsoftware.com/papers/fronting/
[2] https://digi.ninja/blog/cloudfront_example.php

**Comment by Perflyst** [comment]
Can you please explain a bit more what exact feature you want to request?

**Comment by arch-btw** [comment]
Hi @Perflyst , my apologies for the lack of explanation on what I was requesting.
I was not sure if it had been discussed before, hence my short comment.

The suggestion is to use domain fronting to prevent YouTube from banning invidious instances.

I'm still relatively new to domain fronting, so feel free to correct mistakes and/or let me know if it's impossible to implement.

Please see diagram:

![invidious](https://user-images.githubusercontent.com/57669023/86527063-0f34c880-be50-11ea-9666-4b8b132190a2.png)

**Comment by Perflyst** [comment]
As far as I know Google blocks any IP address if it has too many requests. There was another idea in https://github.com/iv-org/invidious/issues/1256 which mentioned shared IP addresses from 4G

Feel free to mention this issue / your idea in https://github.com/iv-org/invidious/issues/1256 again, but I am closing this in favor of https://github.com/iv-org/invidious/issues/1256

**Comment by elypter** [comment]
afaik doain fronting is used to circumvent network level censors. you can only use a domain that belongs to the same service and the service always knows the real destination. so you could fool the nsa or chinas governement (at least if google doesnt collaborate) but not google itself.
