### ISSUE TITLE
Videos missing on channel

### ISSUE THREAD

**Issue by blubberinggit** [iv-org/invidious#1276]
https://invidio.us/channel/UCeGvPo46W6K3XgDDs-JB6UA

You can see that some of the videos such as "RTÉ Home School Hub | Thursday 18 June" is not shown in Invidious. Similiar ones like "RTÉ Home School Hub | Tuesday 26 May" are though.

**Comment by unixfox** [comment]
Probably geolocked videos, duplicate of https://github.com/iv-org/invidious/issues/92
