### ISSUE TITLE
Lemmy as comment source

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1278]
Is it possible to add other sources for comments than just youtube & reddit? I trust reddit way less than I trust youtube. There is a federated reddit alternative called  [Lemmy.](https://dev.lemmy.ml/). The github is [here.](https://github.com/LemmyNet/lemmy) Would it be possible to add comment support for that?

**Comment by Dragnucs** [comment]
Can this be revived?

**Comment by SamantazFox** [comment]
See https://github.com/iv-org/invidious/issues/264
