### ISSUE TITLE
Import is only partial

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1282]
Hello,

I exported my subscriptions list to import it into another instance. But i have 50 subscription and only 12 of them have been imported, and i don't understand why.

**Comment by miku86** [comment]
So I can partially reproduce it.

I created my first account on: https://invidious.snopyta.org and imported from YouTube.
I exported my data with `Export data as JSON`, 32 subscriptions.

I created a new account on: https://invidious.toot.koeln.
I imported my data with `Import Invidious data`.
It imported all settings, but only 8/32 subscriptions.
Re-importing as `JSON` didn't solve it.
Re-importing as `OPML` didn't solve it.

I created a new account on: https://yewtu.be.
I imported my data with `Import Invidious data`.
It imported all settings, and all subscriptions.

Both times I used the same export file.

On both instances, it sends the correct data (= 32 subscriptions) in the `POST` request to the server.

Let me know if you need some additional information.
