### ISSUE TITLE
Timestamp links?

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1283]
Is there a way to go to a timestamp in a video? You can add "#t=180s" to the end of a youtube url to start the video at the 3 minute mark. Is that possible with invidious or will it be in the future?

**Comment by dentistformyeye** [comment]
For both Youtube and Invidious, you can add "&t=180s" or "&t=3m". With Invidious only, you can even change the order of the units: "&t=37s2m" is the same as "&t=2m37s".

Parameter | Setting
-- | --
start=TIME, t=TIME, time_continue=TIME | Start playback at TIME seconds into the video. Supports TIME as either an integer specifying seconds or using 12h30m10s22ms syntax. For example, t=12m9s is equivalent to t=729
end=TIME | Stop playback at either TIME seconds or using the above mentioned 12h56m10s22ms syntax.

**Comment by TheFrenchGhosty** [comment]
It needs to be properly integrated in the UI, however it's properly integrated in the backend.

**Comment by Mennaruuk** [comment]
Unfortunately, I haven’t been able to get the time parameter to work. Example:

https://invidious.fdn.fr/watch?v=8K0399dwYrw&t=3m

Regardless of what time I specify, video always starts from zero.

**Comment by dentistformyeye** [comment]
Do you have JavaScript turned on?

**Comment by Mennaruuk** [comment]
Yes, I have JS on:
![33BB2951-3653-4F69-9055-B7EA94FA0CB8](https://user-images.githubusercontent.com/52135169/106403804-598a2200-63fe-11eb-95c4-5319cd42f84d.jpeg)

**Comment by Mennaruuk** [comment]
This is intriguing: there is a red marker around the third minute, matching the URL’s time parameter. Yet, the video doesn’t start at the third minute.
![9E67AF8C-8A3A-4AE4-8084-9D309E258EC5](https://user-images.githubusercontent.com/52135169/106407250-93145a80-6409-11eb-9937-3519af6f06bc.jpeg)

**Comment by nathgit** [comment]
@Mennaruuk I can even get any videos to play on the instance in the link you posted but it works fine on the [Invidious.snopyta.org](https://invidious.snopyta.org/watch?v=8K0399dwYrw&t=3m) instance.

**Comment by Mennaruuk** [comment]
The videos do play. But not at the timestamp specified in the URL. There is a red marker at the time stamp, but that’s the best Safari for iOS does. It unfortunately doesn’t play the video at that market/timestamp.

**Comment by nathgit** [comment]
> The videos do play. But not at the timestamp specified in the URL. There is a red marker at the time stamp, but that’s the best Safari for iOS does. It unfortunately doesn’t play the video at that marker/timestamp.

I just tried that url again. I tried 3 videos. None play.

**Comment by nathgit** [comment]
Videos do play from the timestamp. I only tried the invidious.snopyta.org domain, but I assume it works for all of them.

**Comment by SamantazFox** [comment]
@nathgit Is it still the case?

**Comment by unixfox** [comment]
Works for me

**Comment by nathgit** [comment]
> @nathgit Is it still the case?

It works now. I had forgotten about opening this issue.

**Comment by garoto** [comment]
> So if I get this right, a UI feature is out of question?

This is probably one of the lowest priority issues to be dealt by the main devs right now.

**Comment by SamantazFox** [comment]
> So if I get this right, a UI feature is out of question?

If you mean an UI element to skip to a defined timestamp, yes, this is waay outside of my priorities atm.
Imho, the progress bar is enough for rough seeking, and the URL can be edited if a precise timestamp is required.

Do note that timestamps in description do work. So if your favorite youtuber listed chapters or musics titles with timestamps in there, you can click them ^^ Same goes with comments!

If you judge that something is still missing, feel free to propose a PR for a JS widget that does the trick :)
