### ISSUE TITLE
Displays wrong video name in tab title.

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#1285]
When clicking on a video, sometimes it displays a random URL or video name, but still plays the correct video. It is fixed by refreshing the page, but it can be very annoying.
(I've only seen it on the invidio.us web app, which I use the most.)

**Comment by TheFrenchGhosty** [comment]
URL example? Is it consistent?

**Comment by stemy2** [comment]
It's purely random.

**Comment by Kreyren** [comment]
Same issue observed on snopyta's invidius `0.20.1-4bc2cd0 @ master`.. FWIW that seem more like on purpose then on random..

![image](https://user-images.githubusercontent.com/11302521/99971220-cc3ea780-2d94-11eb-8020-f27ed98d5bdf.png)

**Comment by SamantazFox** [comment]
This has been fixed.
