### ISSUE TITLE
Weird Page behaviors (Player changing, Pages not loading right)

### ISSUE THREAD

**Issue by WandeingLagomorph793** [iv-org/invidious#1288]
So one thing I notice is sometimes I load pages and videos and they just don't look right, particularly on videos, where it either breaks entirely or the player is radically different.

![Screenshot from 2020-07-15 10-19-26](https://user-images.githubusercontent.com/41207981/87556546-c61d1980-c684-11ea-8e66-4eef73e0dca1.png)
![Screenshot from 2020-07-15 10-17-19](https://user-images.githubusercontent.com/41207981/87556547-c6b5b000-c684-11ea-88d3-0ea2c8131f80.png)

Here's what the player normally looks like, which lets me adjust quality and controls the volume better

![Screenshot from 2020-07-15 10-18-56](https://user-images.githubusercontent.com/41207981/87556614-dc2ada00-c684-11ea-84d1-c74a81c18750.png)

The main home page also looks weird but i'll have to get a good screenshot for that one.

This is with the player style set to Invidious on all three of those screenshots, not sure if it's something on my end, maybe relating to internet issues, or if it's something with Invidious itself (The site I tested was the normal invidio.us domain)

**Comment by TheFrenchGhosty** [comment]
Instance issue.
