### ISSUE TITLE
Dash as default?

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1290]
I've heard so many times people saying about Invidious they don't like it because "quality is bad", "there is no 1080p", "I can't choose quality"…

Dash, which is available with `&quality=dash` or in settings: `preferred default quality: dash` would fix it. Why isn't dash the default way?

**Comment by PotatoBrain** [comment]
Great question, I wonder, too, after I found out about it the other day.

**Comment by rderensy** [comment]
It would be very good if we could set a default value for dash, like automatically select the highest available dash quality or something

**Comment by TheFrenchGhosty** [comment]
Because dash require the instance to do some work, and a public instance with 50 000 users can't do it for "cheap".

**Comment by Perflyst** [comment]
On invidious.snopyta.org the default quality is set to dash now, lets see how it works out.

**Comment by unixfox** [comment]
Dash by default is not a bad idea, for big public instances if they don't want to have dash by default then they just have to disable it but at least by default for private instances one wouldn't have to mess with the settings and have a good video quality.

**Comment by TheFrenchGhosty** [comment]
Definitely! Dash should be enabled by default and we should mention that people hosting public instances should disable it.

**Comment by unixfox** [comment]
closing in favor of https://github.com/iv-org/invidious/issues/4847
