### ISSUE TITLE
Missing hash key: "itemSectionRenderer" 

### ISSUE THREAD

**Issue by stodge** [iv-org/invidious#1293]
I tried searching on https://yewtu.be for "Ford escape phev" and I got an error with no search results:

Missing hash key: "itemSectionRenderer" 

https://yewtu.be/search?q=Ford+escape+phev

Their site is using version: 0.20.1-e88ee26 @ master

**Comment by tuxayo** [comment]
Also on main instance:
https://invidio.us/search?q=pootle+admin+rights&page=1

**Comment by omarroth** [comment]
Should be fixed with b5f79444f9c32dcd090c06e3bf48c1c0bb63bb22.

**Comment by tuxayo** [comment]
Confirmed for the test case on invidio.us , thanks a lot!! :D

**Comment by stodge** [comment]
https://invidio.us has installed the version referenced above and these search terms now work. Thanks!

Current version: 0.20.1-b5f7944 @ master
