### ISSUE TITLE
Looks like you've found a bug in Invidious.

### ISSUE THREAD

**Issue by icf20** [iv-org/invidious#1297]
> Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. 

i got that message and now idea why

**Comment by maxigaz** [comment]
As it happens, I see the exact same message, which I can reproduce by the following steps:

1. Go to <https://invidious.fdn.fr/>
2. Click on any channel name. [Here’s](https://invidious.fdn.fr/channel/UCLx053rWZxCiYWsBETgdKrQ) a random example.

@icf20 If your case happens to be different, I think it would be very helpful for the developers if you provided the context as well. :)

**Comment by ChaseHall** [comment]
I recommend closing this issue as it's on one instance only. [In the future, other instances are available here.](https://instances.invidio.us/)

**Comment by TheFrenchGhosty** [comment]
The FDN instance is month outdated, don't use it, they don't care about it to even update it once a month...
