### ISSUE TITLE
Playlist with (supposedly) 1 video are broken: " Index out of bounds "

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1299]
If a playlist only contain 1 video (Supposedly, it seems to be working with more video), it will trigger " Index out of bounds "

Example: https://invidio.us/playlist?list=PLlyH1UkI-UbNnJVC2JB73wsPljtE1FZcN

**Comment by omarroth** [comment]
Should be fixed with 1e4022680a341ceb8c032d79b60aacb161e7fc86.

**Comment by TheFrenchGhosty** [comment]
Amazing, thanks!
