### ISSUE TITLE
Fix Import youtube subscriptions link

### ISSUE THREAD

**Issue by protodrew** [iv-org/invidious#1301]
it redirects to https://support.google.com/youtube/answer/6224202?hl=en

which is a depreciated solution.

redirect to https://www.youtube.com/subscription_manager instead

**Comment by fazlerabbi37** [comment]
> redirect to https://www.youtube.com/subscription_manager instead

this seems to get redirected to https://www.youtube.com/feed/channels where I don't see any option to export sub list. any idea?

**Comment by schwukas** [comment]
From my latest research on this it seems there is no way to export your subscriptions anymore.

**Comment by fazlerabbi37** [comment]
Haven't tested it yet, but there is a new instruction for NewPipe which may be applicable for this as well? The new link there is: https://takeout.google.com/takeout/custom/youtube

**Comment by schwukas** [comment]
Seems to work fine and produces output like this:

```
[ {
  "contentDetails" : {
    "activityType" : "all",
    "newItemCount" : 0,
    "totalItemCount" : 51
  },
  "etag" : "XK-zfi9HThstwtdK7I-lj77puOw",
  "id" : "C_9pstbkHjNjllqH3C0S1ERFUH5xidQoExsN8wRwc94",
  "kind" : "youtube#subscription",
  "snippet" : {
    "channelId" : "UCkX5ePSBJFiw8TzmxfzXx1A",
    "description" : "Go to www.c90adventures.co.uk for more C90 related adventure and stupidity.",
    "publishedAt" : "2018-05-25T21:20:54.022Z",
    "resourceId" : {
      "channelId" : "UCVqpNG1R72i21jh-nAxEk4A",
      "kind" : "youtube#channel"
    },
    "thumbnails" : {
      "default" : {
        "url" : "https://yt3.ggpht.com/ytc/AAUvwnj4GweWE0W7V7QZIcD5wWZv99Iwkfs_pxJ0KQ=s88-c-k-c0xffffffff-no-rj-mo"
      },
      "high" : {
        "url" : "https://yt3.ggpht.com/ytc/AAUvwnj4GweWE0W7V7QZIcD5wWZv99Iwkfs_pxJ0KQ=s800-c-k-c0xffffffff-no-rj-mo"
      },
      "medium" : {
        "url" : "https://yt3.ggpht.com/ytc/AAUvwnj4GweWE0W7V7QZIcD5wWZv99Iwkfs_pxJ0KQ=s240-c-k-c0xffffffff-no-rj-mo"
      }
    },
    "title" : "c90adventures"
  }
}]
```
I haven't had success importing it into Invidious, though. It should be as easy as adjusting the JSON parser to the (probably) new structure.

**Comment by tim-tx** [comment]
Using this link: https://takeout.google.com/takeout/custom/youtube
If you click on "Multiple formats" Google tells you it's giving you a JSON file for subscriptions. However, when I tried this, it gave me a CSV file. Invidious seems to expect a JSON file though, based on instructions here: https://github.com/iv-org/documentation/blob/master/Export-YouTube-subscriptions.md

I tried importing the CSV file anyway, got a JSON parsing error on Invidious instance as expected:
~~~
Title: `Unexpected char 'C' at line 1, column 1 (JSON::ParseException)`
Date: `2021-08-04T15:31:30Z`
Route: `/data_control?referer=%2Ffeed%2Fsubscriptions`
Version: `2021.08.03-1321c90 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'C' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:247:7 in 'consume_number'
...
~~~

**Comment by unixfox** [comment]
YouTube changed their file format for exporting the subscriptions.
Closing in favor of #2319
