### ISSUE TITLE
Subscriptions feed is blank

### ISSUE THREAD

**Issue by ProtoChoco** [iv-org/invidious#1302]
I have successfully imported 128 subscriptions from both newpipe and youtube, I verified this by checking the manage subscriptions tab on invidious. However, when I go to https://invidio.us/feed/subscriptions it simply reads "0 unseen notifications"

As far as I can tell this is either a bug completely, or an issue in not showing older videos from subscribed channels. I can edit this in a few hours because a channel I subscribe to will have uploaded a new video by then.

**Comment by andrezgz** [comment]
Same thing happened here. I've tried subscribing with the button "Subscribe" from a video page and the channel page.
Without that feature working, having an account is useless.

**Comment by ProtoChoco** [comment]
actually for me it just needed a bit to update. Everything seems fine now!
