### ISSUE TITLE
how to get admin ID

### ISSUE THREAD

**Issue by Miosame** [iv-org/invidious#1303]
The wiki mentions `admins (default []) List of user IDs that have access to administrator preferences` but not what ID to put there, I've tried the psql ID (`1`, since it's only me), tried to check if any URL contains an ID, see if there's some sort of "my profile" page, but there's none - putting it like that: `admins: [1]` doesn't add anything to my preferences page after a `docker-compose down && docker-compose up -d`.

**Comment by Perflyst** [comment]
admin id is in column `email`, so either username or actual email address

**Comment by Miosame** [comment]
That worked, thanks! maybe the docs should be updated to reflect that?

**Comment by Perflyst** [comment]
The wiki can be edited by everyone, feel free to update it :)
