### ISSUE TITLE
Cannot Login no error message

### ISSUE THREAD

**Issue by bam2000** [iv-org/invidious#1305]
Hi, installed invidious on my VServer, its working i can play videos and search, i can also register to the side.
But when i try to login, it just reloads and nothing happens, i'm not logged in :( 
What can i do to get it working?
It seems like the Login Cookie is not working properly 
Thanks

**Comment by Perflyst** [comment]
Please check if https_only is configured and also the domain in config.yml

**Comment by TheFrenchGhosty** [comment]
No answer, I'm considering this issue solved.
