### ISSUE TITLE
Huge size /var/lib/postgresql/11/main/base

### ISSUE THREAD

**Issue by DrDRECoder** [iv-org/invidious#1306]
Hello,
Can I clear these files? They are taking so many space.
Why they have the same size?

![post](https://user-images.githubusercontent.com/63642313/88553078-8ca5c000-d02d-11ea-98bc-d5a06cfd33e3.PNG)

**Comment by SuperSandro2000** [comment]
> Can I clear these files?

No, or you corrupt your database.

>  Why they have the same size?

They are split at the same size.

Try if https://github.com/iv-org/invidious/wiki/Database-Information-and-Maintenance helps.

**Comment by DrDRECoder** [comment]
Thank you so much!
