### ISSUE TITLE
Requesting addition of ID-attributes to the DOM elements

### ISSUE THREAD

**Issue by ErskaConti** [iv-org/invidious#1307]
Could somebody add in id attributes to the elements.

This would facilitate easier user-side customization through Userscripts... 

Right now the Channel-navigation panel is identified by only `class="pure-g h-box"`, the Channel info (such as the banner, name, subscription counter, RSS-feed etc) are all `class="pure-g h-box"` or `class="h-box"`... and one can't really consistently identify them through `document.querySelectorAll()` array index either, because some channels don't include all those elements... and so on.

**Comment by SamantazFox** [comment]
Poke @syeopite : can you consider that in your UI rewrite?

**Comment by syeopite** [comment]
:+1:
