### ISSUE TITLE
YouTube's new "chapter" feature breaks invidious copies.

### ISSUE THREAD

**Issue by ChxseH** [iv-org/invidious#1313]
YouTube added a new "Chapter" feature, and invidious doesn't know how to handle these videos.

[Invidious (My Self-Hosted Copy) Video](https://invidious.cmh.pw/watch?v=Xs9rnAH3VAQ) | [Invidious (Public Copy) Video](https://invidio.us/watch?v=Xs9rnAH3VAQ) | [YouTube (Chapter) Video](https://www.youtube.com/watch?v=Xs9rnAH3VAQ)

2nd Example:
[Invidious SH Copy](https://invidious.cmh.pw/watch?v=JKqMif4TyHk) | [Public Host](https://invidio.us/watch?v=JKqMif4TyHk) | [YT](https://www.youtube.com/watch?v=JKqMif4TyHk)

**Comment by omar-elnaggar** [comment]
Seems to work if you change the quality to "medium"

**Comment by ChaseHall** [comment]
The issue with this, is I can't adjust my quality as the video just [won't load](https://i.imgur.com/FhOgVYr.jpeg).

**Comment by omar-elnaggar** [comment]
That particular video seems to work for me. Do you have another video that this doesn't work on?

![image](https://user-images.githubusercontent.com/34067868/90068850-34fe8a00-dca6-11ea-8f97-a71f1144ef56.png)

**Comment by ChxseH** [comment]
Closing this as I haven't seen this be broken in a while.
