### ISSUE TITLE
Cannot access videos

### ISSUE THREAD

**Issue by blanchfor** [iv-org/invidious#1314]
Cannot access videos, when I click on them nothing comes up.

**Comment by pshane4** [comment]
Same problem--maybe he's reformatting outdated codes because youtube upgraded?
Never had the problem before.

**Comment by pshane4** [comment]
Yes--not sure what to do...

**Comment by tuxayo** [comment]
The problem seems to be the instance(server) or the Invidious version running or it.

One this other instance, for example, it seem most videos work: https://invidious.snopyta.org/

List of instances: https://instances.invidio.us/

**Comment by Hi-Phile** [comment]
Please try to disable the browser setting:
``Use hardware acceleration when available``
In Chrome Settings > Advanced > System 
In Firefox Settings https://support.mozilla.org/en-US/kb/performance-settings?as=u&utm_source=inproduct

**Comment by TheFrenchGhosty** [comment]
This is an instance issue, not a software issue.
