### ISSUE TITLE
Not opening videos now

### ISSUE THREAD

**Issue by TheTux-source** [iv-org/invidious#1315]
Even though i have all the codecs installed (epiphany with flatpak), nothing comes up, just says about the license and the cryptowallets

**Comment by tuxayo** [comment]
You mean the page is empty like that?

![Screenshot_2020-07-30_23-01-13](https://user-images.githubusercontent.com/2678215/88974233-9a22aa80-d2b8-11ea-895a-a58a6211bfc8.png)

**Comment by pshane4** [comment]
Tuxayo -- mine looks like that.

I can view the channel, and videos,
but when I click on individual ones,
it gives me that error.

Linux. Using Brave. Doesnt work on RSS or other browsers the same way.
Any suggestions?

-Much appreciation

**Comment by TheTux-source** [comment]
> You mean the page is empty like that?
> 
> ![Screenshot_2020-07-30_23-01-13](https://user-images.githubusercontent.com/2678215/88974233-9a22aa80-d2b8-11ea-895a-a58a6211bfc8.png)


yeah, just like that, forgot to post the img, thank you

**Comment by tuxayo** [comment]
The problem seems to be the instance(server) or the Invidious version running or it.

One this other instance, for example, it seem most videos work: https://invidious.snopyta.org/

List of instances: https://instances.invidio.us/

**Comment by TheTux-source** [comment]
> The problem seems to be the instance(server) or the Invidious version running or it.
> 
> One this other instance, for example, it seem most videos work: https://invidious.snopyta.org/watch?v=PJIsiuSdpq8
> 
> List of instances: https://instances.invidio.us/

great then, thanks, problem "solved", now the people who take care of the instance will be able to solve it
