### ISSUE TITLE
Can’t access invidio.us instance

### ISSUE THREAD

**Issue by GitGangGuy** [iv-org/invidious#1316]
The invidio.us instance appears to be down or at least partially non-functional, as I and multiple others have experienced (https://www.reddit.com/r/privacy/comments/i0t7oi/is_invidious_down/, recent issues). I specifically am receiving a 500 internal server error anytime I open the page. Note that other instances like snopyta are fully functional.  
I hope everything is going alright with the servers and this is just a temporary issue and not a huge change in YouTube's APIs or such. Id love to see the main instance back up again for all!

**Comment by Perflyst** [comment]
The issue has been fixed according to other users in the matrix channel.
