### ISSUE TITLE
Cannot register - password complexity?

### ISSUE THREAD

**Issue by hifirestone** [iv-org/invidious#1317]
I attempted to register for the site for the first time. I used a 32 character generated password in my attempt to register. It contains these special characters such as:  ?#$*][> . The error it gave me was something like "you've encountered an error, please report it"

**Comment by schwukas** [comment]
I can register just fine on my instance, even with passwords longer than 32 characters and including all sorts of special symbols. 
It would be helpful to know which site you tried to register on. Maybe you could provide a password (not used by you, of course) that definitely fails to make reproduction of the error easier.

**Comment by unixfox** [comment]
Is this bug still applicable? Has anyone ever reproduced this issue apart from schwukas?

**Comment by unixfox** [comment]
Can't reproduce I tried with a very long password (over 32 characters), with special characters and it works fine.
