### ISSUE TITLE
Can't play videos with "[musician/musical group] Topic" in the username

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1322]
Hello,

No matter what video i try to watch, no matter what instance i use, if the username is "[musician/musical group] - Topic", i can't watch it.

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

The video itself give a HTTP 403 error.

**Comment by TheFrenchGhosty** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/392
