### ISSUE TITLE
Version 0.20.1-62f015f doesn't accept default_user_preferences in config.yml:

### ISSUE THREAD

**Issue by tharrisone** [iv-org/invidious#1323]
What ever changes I make under the default_user_preferences nothing changes.
This is my config:

channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
external_port:
check_tables: true
domain: invidious.us
port: 7777

default_user_preferences:
dark_mode: true
player_style: youtube
quality: dash
local: true

**Comment by TheFrenchGhosty** [comment]
Works on my instance, I'm guessing you have a cookie set in your browser.
