### ISSUE TITLE
Log in with Google Broken

### ISSUE THREAD

**Issue by madprogramer** [iv-org/invidious#1324]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/3719664/89376030-a911be80-d6f7-11ea-82c7-e6a1a449665e.png">

Attempting to to log in with Google gave me the following error:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/3719664/89376086-c8a8e700-d6f7-11ea-9895-fa4a2ac2f7db.png">
`Unexpected char 'T' at 1:1
Traceback:
Getting lookup...
`

Doesn't seem that your credentials being right or wrong matters, I'm getting it with a faulty password as well.

**Comment by TheFrenchGhosty** [comment]
Is that only on 1 instance? Did you try another one?

**Comment by madprogramer** [comment]
Nope, I've only tried http://invidious.snopyta.org

**Comment by SuperSandro2000** [comment]
Related #754 and #755

**Comment by ChaseHall** [comment]
As an alternative, create a normal account and import your subscriptions.

**Comment by madprogramer** [comment]
@ChaseHall I guess there is nothing stopping me from making a new account on invidio.us and giving myself the same name, profile picture etc. And that does make complete sense based on what kind of a project this is. 

But still, I hope this can be fixed to allow me to just log-in and like a comment without having to use YouTube proper. Seeing as #754 and #755 are related, I'll be closing this issue for now.
