### ISSUE TITLE
QUESTION: How does Invidious handle video streams?

### ISSUE THREAD

**Issue by pluja** [iv-org/invidious#1325]
I'm working on a [project](https://github.com/pluja/Parasitter) and I want to know how does Invidious handle the video streaming without making any connection to googlevideo from the client. Is it streaming the video through the invidious server to the client? If so, how is it done?

I have taken a look to the code, but I don't really undestand the structure and I've never worked with Crystal nor Ruby on rails so it's a bit slow for me. I can read and investigate the part of the code that is doing that if you can tell me where it is.

Thanks!

**Comment by afrmtbl** [comment]
I may be mistaken but it seems like these would be the relevant lines: https://github.com/iv-org/invidious/blob/62f015fc34194979ef2cbb5bfef2f8df608177bc/src/invidious.cr#L5376-L559747

This comment might also be helpful: https://github.com/iv-org/invidious/issues/453#issuecomment-477574597
