### ISSUE TITLE
Popular feed is just my subscriptions

### ISSUE THREAD

**Issue by thechadraccoon** [iv-org/invidious#1326]
Popular feed is just my subscriptions as i am the only user on the instance.

it is so for all users including those who have not logged in.

Is there a way to disable the feature other than hide the top button from users? ( which isn't effective as you can simply add "/feed/popular/" to the url )

**Comment by TheFrenchGhosty** [comment]
Add "top_enabled: false" to your config.

**Comment by filipeluna** [comment]
This fix does not work for me. I've tried to rebuild multiple times, delete the user, purge the database but, alas, still have my subscriptions plastered all over the homepage for every single user. I've searched the source and there are no references to the "top_enabled" parameter. Is this featured totally broken?

**Comment by TheFrenchGhosty** [comment]
@filipeluna top_enabled just disable the instance top page.

**Comment by filipeluna** [comment]
Thanks for the response!

**Comment by thechadraccoon** [comment]
I think its meant to be more diverse once it has a lot of users. but if you're the only one that uses the instance then it only parses yours.

**Comment by filipeluna** [comment]
@thechadraccoon Yeah, I get the idea. It's just not compatible with having an instance just for you or your family/friends. For instance, you might not want your friends to know you're subscribed to x or y. With micro user bases (<10 people) it's just a leak I can't deal with. Specially if you open it up to the internet and every visitor just knows what you follow. It just seems to contradict the whole privacy mantra the whole project is built around.

It would be really great if there was a way to simply disable that functionality.

**Comment by winteriscariot** [comment]
@thechadraccoon @filipeluna disable the 'Popular' link in your settings, then add this to your webserver config (assuming you're using nginx):

```
    location ~ ^/feed/popular {
	    allow 127.0.0.1;
	    deny all;
    }
```

**Comment by sigaloid** [comment]
`popular_enabled: false` is a thing now. :smile: 

What it looks like: 
![image](https://user-images.githubusercontent.com/69441971/111854229-0caecc00-8916-11eb-86a1-3f501ed72926.png)
