### ISSUE TITLE
Updating docker hub before Sept. 1

### ISSUE THREAD

**Issue by tscibilia** [iv-org/invidious#1332]
I really love this project, I was wondering if someone was going to update the docker image prior to the sept 1 hold on development. It looks like the last push was several commits ago.
https://hub.docker.com/r/omarroth/invidious/builds

**Comment by TheFrenchGhosty** [comment]
@Perflyst @leonklingele

**Comment by Perflyst** [comment]
Docker is updated automatically again https://hub.docker.com/r/omarroth/invidious/builds
