### ISSUE TITLE
How to insert own code in HTML?

### ISSUE THREAD

**Issue by DrDRECoder** [iv-org/invidious#1334]
Hello,
I would like to insert counter in template, but I can't.
1) I stop the process (service invidious stop),
2) try to edit these files /home/invidious/invidious/src/invidious/views/template.ecr or /home/invidious/invidious/src/invidious/views/watch.ecr
3) start the process (service invidious start)
and there's no effect.

**Comment by gripped** [comment]
You need to compile it again. You've edited the source but the executable remains the same.

**Comment by DrDRECoder** [comment]
Is there any instruction on how to do this?

**Comment by gripped** [comment]
crystal build src/invidious.cr --release

https://github.com/iv-org/invidious/wiki/Updating

**Comment by DrDRECoder** [comment]
Thank you!

**Comment by TheFrenchGhosty** [comment]
If your instance is public don't forget that you have to release the source code.
