### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by asorel1942** [iv-org/invidious#1338]
Exporting subscriptions from Invidious as OPML and attempting to import them into invidious.snopyta results in the "you have encountered a bug" screen appearing. Exporting as a Freetube OPML or as a JSON, and then importing, results in the same issue.

**Comment by GitWaifu** [comment]
all versions of invidious are currently blocked by google from importing any channel videos - see #1333
and other bugs

**Comment by asorel1942** [comment]
How does importing channel videos from youtube prevent exporting a list of subscriptions from one instance to another?

**Comment by GitWaifu** [comment]
i have no idea because i personally don`t run any invidio servers - i just mentioned a bug that potentially could be related to your issue so your issue will appear in that bug thread and send a notification to anyone who tracks that bug.
 If you find a bug thread you want your issue to be displayed in - you can mention it instead and delete my comment

**Comment by Perflyst** [comment]
Some exports can be imported some cant, I cannot tell you why exactly that happens. Does an import to another instance works? https://instances.invidio.us

**Comment by asorel1942** [comment]
I tried a couple more on the list, neither worked.

**Comment by asorel1942** [comment]
I tried a couple more on the list, neither worked.

**Comment by afrmtbl** [comment]
@asorel1942 Just curious: which import button were you trying? (import invidious data, import youtube subscriptions, etc)

**Comment by asorel1942** [comment]
I was using Import Invidious data. When that didn't work I tried exporting as the Newpipe and Freetube filetypes, then using those buttons to try and import.

**Comment by afrmtbl** [comment]
It should work if you use the `Import YouTube subscriptions` button with the OPML.
The `Import Invidious data` button expects JSON data and throws that error when OPML/XML data is given instead.

It's pretty confusing and should probably be clarified on the page.

**Comment by afrmtbl** [comment]
@asorel1942 Was this able to fix the issue?

**Comment by asorel1942** [comment]
I can check now. I'd already moved all of my subscriptions over manually, so I didn't think to test it again.

**Comment by asorel1942** [comment]
Seems to work now, yes.

**Comment by WandeingLagomorph793** [comment]
I'm getting something similar with Snopyta and I get similar errors, either 504 gateway errors or "You found a bug in Invidious", if I do it on an existing account, it doesn't change anything, testing it with a fresh account throws similar errors, this was from importing via the Yewtu.be instance, tested with OPML and .JSON from both Import via Invidious and Import via Youtube.

One behavior that's weird is sometimes it'll import playlists, but it won't import all of them, having tested from an instance with four playlists and it only imported two of them, and the ones that are imported don't have all the videos, going from 168 to 144, I don't know if it's a bug on that instances end or if it just didn't format right when exporting from Yewtu.be

**Comment by v7rzlhb3xg** [comment]
Still not working.

**Comment by xanoni** [comment]
It works for me if I export as JSON on instance A and then reimport as JSON on instance B. The same doesn't work with OPML/XML. In that case, I get an error message that indicates that it's trying to parse the XML with the JSON library. See below.

```
Title: `Unexpected char '<' at line 1, column 1 (JSON::ParseException)`
Date: `2021-10-14T22:13:10Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.10.14-961c574 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
Unexpected char '<' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:376:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:372:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:371:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:225:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

</p>
</details>
```
