### ISSUE TITLE
Freetube 0.7.3 app overloading Invidious servers on startup

### ISSUE THREAD

**Issue by wdub** [iv-org/invidious#1341]
I've just noticed that I'm unable to set the landing page to **History**(which is disabled/empty) or **Favorites**. It falls back to **Subscriptions** so every time I open Freetube, it checks for new videos.

Because of bugs like this I guess a considerable amount of bandwidth and API hits are wasted, leading to unnecessary CPU load and IP bans.

Considering that most of us open Invidious just for listening a song from Favorites or search for a video, syncing dozens of channels and hundreds of videos multiple times a day is unacceptable.

I see two solutions to this problem: someone patch Freetube or ban it(if possible) entirely from accessing invidious instances.

**Comment by TheFrenchGhosty** [comment]
FreeTube was never an issue until then. I don't really see how banning it will change anything.

**Comment by cloudrac3r** [comment]
If you run an instance and would like to block it from being used by FreeTube, simply disallow the user-agent, or even the entirety of /api/, in nginx.
