### ISSUE TITLE
Video download broken

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#1344]
Video download is not working anymore and returns HTTP 404 error

Examples:
https://yewtu.be/watch?v=bhq3AzEXLm0
https://yewtu.be/latest_version?download_widget=%7B%22id%22%3A%22bhq3AzEXLm0%22%2C%22itag%22%3A%2218%22%2C%22title%22%3A%22Can%2Bthey%2Bwin%2Bme%2Bback%253F%253F%2B-%2BLG%2BGram%2B2020%2BLineup%2BShowcase-bhq3AzEXLm0.mp4%22%7D

https://invidious.snopyta.org/watch?v=-TWj-biXpLo
https://invidious.snopyta.org/latest_version?download_widget=%7B%22id%22%3A%22-TWj-biXpLo%22%2C%22itag%22%3A%22134%22%2C%22title%22%3A%22This%2B%252410%252C000%2Blaptop%2BISN%2527T%2Boverpriced...--TWj-biXpLo.mp4%22%7D

**Comment by Aquariu** [comment]
Dear all,

I can confirm the behavior on my own instance as well as on public ones.
Clicking the "download" button for every audio/video format available results in a 404 error in the logs.

Strangely, subtitles download is perfectly ok (at least on my instance).
log snipet:
`2020-11-28 09:19:55 UTC 404 GET /latest_version?download_widget=%7B%22id%22%3A%22DEWZ53E1okE%22%2C%22itag%22%3A%2218%22%2C%22title%22%3A%22Bad%2BBunny%253A%2BYO%2BVISTO%2BAS%25C3%258D-DEWZ53E1okE.mp4%22%7D 1.54ms`

**Comment by TheFrenchGhosty** [comment]
Fixed in #1654
