### ISSUE TITLE
Finish the implementation of HTTP proxy that anti-CAPTCHA can use

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1349]
@omarroth worked on a branch to add proxy support: https://github.com/iv-org/invidious/tree/add-proxy

According to him:

>It would provide a HTTP proxy that anti-CAPTCHA could use. It’s WIP IIRC.

Most of the code seems to be here, but it needs to be finished.

**Comment by unixfox** [comment]
We don't need anticaptcha anymore.
