### ISSUE TITLE
Alternative To Invidious

### ISSUE THREAD

**Issue by zaheerhakim** [iv-org/invidious#1352]
Your service was amazing and it's sad that we will no longer be able to access it after the 1st of September, is there any other alternative to Invidious?

**Comment by Scaledi** [comment]
the specific instance is shutting down, not the project.

**Comment by zaheerhakim** [comment]
> the specific instance is shutting down, not the project. 

So I’ll be still able to use the website to watch YouTube videos?

**Comment by diazepan** [comment]
> So I’ll still able to use the website to watch YouTube videos?

It's more like you have to use other instance. Here's a list
https://invidious-redirect.cadence.moe/

**Comment by zaheerhakim** [comment]
> > So I’ll still able to use the website to watch YouTube videos?
> 
> 
> 
> It's more like you have to use other instance. Here's a list
> 
> https://invidious-redirect.cadence.moe/

Thank you 😃

Stay Safe!

**Comment by TheFrenchGhosty** [comment]
> the specific instance is shutting down, not the project.

Yes, but no.

The instance is shutting down, yes, but the only developer is also quitting. If Invidious don't get a new developer the project is dead.



> > the specific instance is shutting down, not the project.
> 
> So I’ll still able to use the website to watch YouTube videos?

As long as Invidious doesn't get a new developer the project is dying, currently if YouTube change something and no one can fix it, the project will be dead.

**Comment by zaheerhakim** [comment]
> > the specific instance is shutting down, not the project.
> 
> 
> 
> Yes, but no.
> 
> 
> 
> The instance is shutting down, yes, but the only developer is also quitting. If Invidious doesn't get a new developer the project is dead.
> 
> 
> 
> 
> 
> 
> 
> > > the specific instance is shutting down, not the project.
> 
> > 
> 
> > So I’ll still able to use the website to watch YouTube videos?
> 
> 
> 
> As long as Invidious doesn't get a new developer the project is dying, currently if YouTube change something and no one can fix it, the project will be dead.

Thank you. 

Understood. 

Hope everything goes well. 

Stay Safe!

**Comment by SolAZDev** [comment]
> The instance is shutting down, yes, but the only developer is also quitting. If Invidious doesn't get a new developer the project is dead.
> As long as Invidious doesn't get a new developer the project is dying, currently if YouTube change something and no one can fix it, the project will be dead.

Begs the question; is this not about to become a community-developed project? If so, how come? I'm pretty sure Invidious could benefit from itt

**Comment by Scaledi** [comment]
> > The instance is shutting down, yes, but the only developer is also quitting. If Invidious doesn't get a new developer the project is dead.
> 
> > As long as Invidious doesn't get a new developer the project is dying, currently if YouTube change something and no one can fix it, the project will be dead.
> 
> Begs the question; is this not about to become a community-developed project? If so, how come? I'm pretty sure Invidious could benefit from it.

it was always community developed, to an extent. we can all contribute, but, the main person who contributed the most by far is stepping down.

**Comment by TheFrenchGhosty** [comment]
>it was always community developed, to an extent. we can all contribute, but, the main person who contributed the most by far is stepping down.

Exactly, it was always a community project, no one other than the main developer bothered to work on it, and today, we get he consequence of that sadly.

**Comment by aurianer** [comment]
I'll be willing to help, but I think I need the help of the main developer for that..
This is a great project which gives hope for privacy! I'd be sad to watch it die.

**Comment by zaheerhakim** [comment]
Hope it doesn't die. Excellent project for privacy.

**Comment by grravity** [comment]
I'm hoping we can find some devs, shame it was written in Crystal.
It would be nice not to have to move to another frontend (again), as Invidious has been integrated into so many things.

However, if we did, I cannot say I am +1 for the implementations I have seen so far which seem to all be written in Python unless I am missing something. Not against a popular language obviously, But I cannot say I am for moving to a python based frontend lol

**Comment by craftyguy** [comment]
> I'm hoping we can find some devs, shame it was written in Crystal.


Yeah, that's a problem.

> Not against a popular language obviously, But I cannot say I am for moving to a python based frontend lol

You don't give any reasons why you're against it. I'd rather it be written in something with more potential contributors (e.g. python) than in something like Crystal where there are far fewer potential contributors (and even less who will actually care enough to contribute to this project...)

**Comment by chaosmonk1** [comment]
> Not against a popular language obviously, But I cannot say I am for moving to a python based frontend lol

The fact that it is easier to find people willing and able to reimplement Invidious in Python than it is to find people willing and able to maintain the existing Crystal codebase is enough to convince me that Python is the right choice, if we want to avoid ending up in this situation again.

**Comment by rachmadaniHaryono** [comment]
i got affected by #1388 and find this issue

my need for invidious is to get all video from channel and process it with another program

so far i found 3 program

- https://github.com/pluja/Yotter , unfortunately no api and it only got few video from channel
- https://github.com/cloudrac3r/youtubedl-invidious / https://git.sr.ht/~cadence/Second , i haven't try both of them but it seem promising
- https://github.com/ytdl-org/youtube-dl , still try to write the script for this

**Comment by rdhox** [comment]
Just discover MotionBox: http://omega.gg/MotionBox/ (https://github.com/omega-gg/MotionBox)
Really good app to stream from different servers (youtube, dailymotion, vimeo, etc...), with lot of options. A newPipe's like desktop app in a sort. Definitely worth a try 👍

**Comment by grravity** [comment]
>Motionbox

I wouldn't call this an alternative to Invidious. Invidious was simply a web based front-end to YouTube. Not an application.

**Comment by rdhox** [comment]
> > Motionbox
> 
> I wouldn't call this an alternative to Invidious. Invidious was simply a web based front-end to YouTube. Not an application.

Invidious was also an API used by almost all the desktop application :)
One of the only alternative is new pipe which not exist on desktop.

**Comment by TheFrenchGhosty** [comment]
Freetube exist on desktop. But some people, including me, still want to have invidious.

**Comment by Serkan-devel** [comment]
> > Not against a popular language obviously, But I cannot say I am for moving to a python based frontend lol
> 
> The fact that it is easier to find people willing and able to reimplement Invidious in Python than it is to find people willing and able to maintain the existing Crystal codebase is enough to convince me that Python is the right choice, if we want to avoid ending up in this situation again.

While I'm much more familiar with Python than with Crystal, a Python implementation would be more resource intensive thus making it significantly harder to independently host.

**Comment by deep-gaurav** [comment]
If anyone is interested I wrote a rust port of newpipe (not invidious), and a WIP frontend
It's available at
https://rustypipe.deepraven.co/
Project is open source at
https://github.com/deep-gaurav/rusty_pipe

**Comment by SwiftWinds** [comment]
> If anyone is interested I wrote a rust port of newpipe (not invidious), and a WIP frontend
> 
> It's available at
> 
> https://rustypipe.deepraven.co/
> 
> Project is open source at
> 
> https://github.com/deep-gaurav/rusty_pipe

Thanks for developing this! However, the link seems to redirect to some adware website. What's going on?

**Comment by TheFrenchGhosty** [comment]
@SwiftWinds The project obviously died and the domain was taken over.

**Comment by deep-gaurav** [comment]
> > If anyone is interested I wrote a rust port of newpipe (not invidious), and a WIP frontend
> > It's available at
> > https://rustypipe.deepraven.co/
> > Project is open source at
> > https://github.com/deep-gaurav/rusty_pipe
> 
> Thanks for developing this! However, the link seems to redirect to some adware website. What's going on?

@SwiftWinds , yeah that domain expired, project now is live on https://rustypipe.deepraven.xyz
I'm not developing is currently, but will try to pick it back up later when have some time,..

**Comment by boehs** [comment]
@TheFrenchGhosty please consider reopening. a lot of valid discussion has happened here and it is still relevant today.

**Comment by TheFrenchGhosty** [comment]
@boehs This issue was about projects that could replace invidious after the main instance shutdown in case the whole project died.

This isn't really relevant today since invidious is very much alive, and a rewrite is coming.

**Comment by boehs** [comment]
> @boehs This issue was about projects that could replace invidious after the main instance shutdown in case the whole project died.
> 
> This isn't really relevant today since invidious is very much alive, and a rewrite is worked on.

Omg really? this is wonderful news. last I checked in it was looking for maintainers and it looked like it was slowly dying. wonderful to hear people are coming to help out :)
