### ISSUE TITLE
Annotations are not showing up

### ISSUE THREAD

**Issue by aquatorrent** [iv-org/invidious#1354]
Hello,
I just realized that annotations are deleted from youtube. I wanted to backup the annotations from my video but it seems that the annotations aren't showing up. I also tried to hit the api to get the annotation text but it returns nothing.

video id: p-FGR60EZdw
video link: https://invidio.us/watch?v=p-FGR60EZdw&iv_load_policy=1
annotations API: https://invidio.us/api/v1/annotations/p-FGR60EZdw

I also tried hitting [this](https://invidio.us/api/v1/videos/p-FGR60EZdw?iv_load_policy=1&quality=dash) API, hoping that it will show the annotations but it seems that it's not there either. I already try the export button on the [site](https://invidio.us/data_control) too but I can't seem to find it.
Does this mean that the annotations for my video isn't backed up? Or am I doing this wrong?

Sorry if I put this in the wrong place, and thanks for backing this up (regardless whether my video is backed up or not).
It's sad to see that it's going to end next week though.

**Comment by TheFrenchGhosty** [comment]
Annotations aren't available for every video, obviously, since it was a community project.

If you can't get them, it means that the video you used didn't have it's annotation saved.
