### ISSUE TITLE
Donations after 2020-09-01

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#1357]
With the shutting down of invidio.us and the focus shifting towards a pool of instances it become more complicated to direct donations to where they are needed. there are all the individual instances that have to pay and maintain their servers, there is the development and project management and there is also the redirect page and domain hosting which is a lot less traffic than it used to be but still not nothing.

What do you think should be done? which sonation page should the footer point to? where should readme.md point to? should the redirect page have a donation link or should it have a link for each instance? @cloudrac3r who is behind iv-org that Omar Roth points to [here](https://omar.yt/posts/stepping-away-from-open-source)?

I know, it's not a nice topic to talk about but it can easily become a source of trouble and i think the project is much better off in the future if evrey contributor can pay his/her expenses or gets a little compensation for their contribution.

**Comment by unixfox** [comment]
For the instance side I think if the maintainer wants to have some kind of donation then he can ask that through a notice on top of the website page like https://invidious.tube is already doing it.

I don't know how is the future going to look like but for the moment most of the maintainers are paying at their own expense and it's probably fine.

**Comment by elypter** [comment]
> he can ask that through a notice on top of the website page like https://invidious.tube is already doing it.

but there is still a donation and crypto links to omar roth in the footer. i think it would be better to make that a custom field that you can change in settings or during setup. the footer is also less obtrusive which i think many owners of instances would prefer. i mean, everyone should know for themselves if they want to ask for donations but everything should be as little obstacles in the way as possible. some people might think it's better if they dont have to pay anything anyway but its just about donations. you dont have to pay anything anyway. and if you fear annoying donation reminders thats not a feature i think should be added and i dont think many contributers would be willing to add that. and an instance owner who wants to do that can still add it manually and nobody could stop them. so its just positive for instance owners, donors and eventually users because instances are lesslikely to go offline if they recieve donations.

**Comment by Perflyst** [comment]
Informations about donations are in this new announcement: https://github.com/iv-org/invidious/issues/1411#issue-722497739

**Comment by FireMasterK** [comment]
> For the instance side I think if the maintainer wants to have some kind of donation then he can ask that through a notice on top of the website page like https://invidious.tube is already doing it.

If I may ask, how did you that? I didn't find any configuration options to create such a notice. @unixfox

**Comment by unixfox** [comment]
> > For the instance side I think if the maintainer wants to have some kind of donation then he can ask that through a notice on top of the website page like https://invidious.tube is already doing it.
> 
> If I may ask, how did you that? I didn't find any configuration options to create such a notice. @unixfox 

It's in the "banner" parameter of the config.yml: https://github.com/iv-org/invidious/wiki/Configuration
