### ISSUE TITLE
Video timestamps don't show up in all places

### ISSUE THREAD

**Issue by git-bruh** [iv-org/invidious#1358]
On the popular feed page, video timestamps are shown for some videos, but not for others. Timestamps are not visible on the channel page either, but show up in search results. Views seem to be less up to date on the main feed aswell.

Example:
[Popular feed](https://invidious.snopyta.org/)
![Popular](https://i.ibb.co/NC6kbzt/popular.png)

[Search results](https://invidious.snopyta.org/search?q=NVIDIA+just+made+EVERYTHING+ELSE+obsolete.)
![Search](https://i.ibb.co/qxqxtMG/search.png)

[Channel page](https://invidious.snopyta.org/channel/UCXuqSBlHAE6Xw-yeJA0Tunw)

Results seem to vary instance to instance too, the [snopyta instance](https://invidious.snopyta.org/api/v1/popular?fields=title,lengthSeconds,author) doesn't show timestamps for some videos whereas [this instance](https://invidious.13ad.de/api/v1/popular?fields=title,lengthSeconds,author) does. Seems to be pretty random.

The trending page is not affected by this.
Views are sometimes reported as 0 too, but very few videos seem to be affected, and if the channel is opened, views show up there properly.

**Comment by git-bruh** [comment]
Seems to be fixed on this instance https://invidious.13ad.de, the snopyta instance is probably not using the latest commit.

**Comment by SamantazFox** [comment]
Seems fixed. Feel free to re-open if this isn't the case
