### ISSUE TITLE
Why is Invidious written in Crystal?

### ISSUE THREAD

**Issue by mendel5** [iv-org/invidious#1361]
I am asking this question out of curiosity. The initial commit for Invidious can be found at https://github.com/iv-org/invidious/tree/26959020b732b5d729432294df6246307819e32f . Even back then the backend of Invidious (src) was written in Crystal (.cr) and the frontend (views) in Embedded Crystal (.ecr).  So Invidious was not refactored to use Crystal but rather has this been the case since the beginning.

What were the reasons to choose Crystal and not any other language? I am only trying to understand the reasoning of this decision.

Maybe you @omarroth can help us.

**Comment by markozajc** [comment]
I'd assume that was due to familiarity with the language, which is also the reason I (and a lot of people that I know) use languages that they know the best, even if they're obscure.

**Comment by mendel5** [comment]
> I'd assume that was due to familiarity with the language

That's what I am thinking as well.
