### ISSUE TITLE
List of instances on invidio.us not updated

### ISSUE THREAD

**Issue by guser-sudo** [iv-org/invidious#1362]
The list of instances here on github was updated alot the last days, e.g. owners wanted their instance to be removed to avoid too high traffic. However this won't work that well as long as the official instance is still suggesting them as an available alternative. So I suggest updating invidio.us accordingly (at least now and then).

**Comment by TheFrenchGhosty** [comment]
It's maybe an invidious-redirect issue.

**Comment by cloudrac3r** [comment]
I disagree. I cannot find any instances listed on invidio.us that are not listed on the wiki page. Got any specific examples to point at?

**Comment by guser-sudo** [comment]
Sorry, I had JavaScript disabled, which gave me an outdated list.
