### ISSUE TITLE
RSS links port 3000 (Common Misconfiguration)

### ISSUE THREAD

**Issue by RandomErrorMessage** [iv-org/invidious#1363]
While attempting to replace my use of the original instance I found that the majority of alternative instances have misconfigured RSS feeds that link to port 3000, which I assume is an internal port. I'd probably contact these admins directly but there isn't a standard contact page as far as I'm aware.

This is clearly a common misconfiguration issue, maybe something could be done to make this more clear to instance operators.

Eg.
https://invidious.xyz/feed/channel/UC3ts8coMP645hZw9JSD3pqQ
https://invidious.toot.koeln/feed/channel/UC3ts8coMP645hZw9JSD3pqQ
https://invidious.site/feed/channel/UC3ts8coMP645hZw9JSD3pqQ
https://yewtu.be/feed/channel/UC3ts8coMP645hZw9JSD3pqQ

**Comment by unixfox** [comment]
Should be fixed for yewtu.be

**Comment by GauthierPLM** [comment]
@unixfox How did you fix this? Maybe we could find a way to fix it for all instances by making sure the links always point to the right place?

**Comment by unixfox** [comment]
I just added `external_port: 443` to the `config.yml`.
