### ISSUE TITLE
Could not extract video info. Instance is likely blocked.

### ISSUE THREAD

**Issue by wapfalls** [iv-org/invidious#1365]
I have created this instance, invidious.site
It was running fine till yesterday, and from today it says this error message, "Could not extract video info. Instance is likely blocked.
" on every video page.

Can someone help fix this? Does it say that youtube probably blocked my server IP from pulling video information?

**Comment by TheFrenchGhosty** [comment]
Yes. Setup anticaptcha.

**Comment by wapfalls** [comment]
@TheFrenchGhosty Thanks for your response, but now the videos seem to play without issues.

Can you please direct me to guide (if any) to configure anti-captcha or help me get started by pointing the right files that needs to be updated.

**Comment by TheFrenchGhosty** [comment]
@wapfalls https://github.com/iv-org/invidious/wiki/How-to-setup-Anti-Captcha
