### ISSUE TITLE
Thanks to everyone maintaining invidio.us/instances

### ISSUE THREAD

**Issue by linuxgirl22** [iv-org/invidious#1366]
Just wanted to say a big thankyou to everyone involved in maintaining invidio.us and instances. Yesterday, with the captcha being added as a block by google, no watch/download was possible anywhere ... today, e.g. https://yewtu.be/ works perfectly! Appreciate this immensely. 

Realise that blockages could be mixed up with big tech increasingly blocking VPNs too e.g. this last week or two I've had to switch IPs to access Amazon, for the first time, and don't know if the captcha (seen via 'open in tab' in Liferea) was a google action everyone's being affected by or mostly those with a VPN ... never seen that before the last week or two either. 

Whatever it is, grateful can still access videos. :-)

(I understand thread will close as it isn't an issue; no worries. )

**Comment by TheFrenchGhosty** [comment]
We'll be here as long as no proper alternative is born.

**Comment by linuxgirl22** [comment]
Thank you @TheFrenchGhosty ... really appreciate. :-)

**Comment by tiotrom** [comment]
Can I ask how do you check the "health" status for each instance?

**Comment by TheFrenchGhosty** [comment]
@tiotrom Uptime / Total time
