### ISSUE TITLE
Channel pages wont show videos

### ISSUE THREAD

**Issue by letmerest** [iv-org/invidious#1368]
When I try to look at a channel, it'll load the page but the list of their uploads is completely empty. This goes for most channels, however some pages WILL show their uploads. From what I've seen, it appears that whether a channel loads or does not load their uploads is arbitrary. This also effects subscription loading with FreeTube. Anyone else experience this?

(To clarify this does NOT effect being able to watch videos from the particular channel, just showing their uploads on their channel page)

**Comment by TheFrenchGhosty** [comment]
Instance issue.
