### ISSUE TITLE
Documentation about how to set up anti-CAPTCHA needed

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1373]
There is currently no documentation/wiki page written about how to set up anti-CAPTCHA.

I personally have no idea about how to set it up, and I'm guessing it's the same for most.

Related #1365

**Comment by unixfox** [comment]
Done: https://github.com/iv-org/invidious/wiki/How-to-setup-Anti-Captcha

**Comment by TheFrenchGhosty** [comment]
Thank you! So it's really that simple, good to know.
