### ISSUE TITLE
Opening a channel on invidious.fdn.fr causes an error

### ISSUE THREAD

**Issue by adampusf** [iv-org/invidious#1376]
So the detail is that I was surfing the internet using invidious.fdn.fr (health 100). Then I suddenly came across a channel (https://invidious.fdn.fr/channel/UCq5vbuUnBth6wtcUANAakRQ) but when I clicked on it, it gave me this error:

Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com.
I'll give more details if required!

**Comment by TheFrenchGhosty** [comment]
Instance issue.

FDN hasn't been updated in month.
