### ISSUE TITLE
channels disappear after two subscriptions

### ISSUE THREAD

**Issue by imapotatoalso** [iv-org/invidious#1377]
Hey guys, I'm using the latest commit of invidious. And the videos themselves are fine. But whenever I subscribe on my instance more than one channel. all channels disappear with the message " Looks like you've found a bug in Invidious." after I scrub my database + a few hours it returns to normal. but goes the same way when I try to sub to two or more channels.

**Comment by Vladeeg** [comment]
I'm experiencing the same problem.

Also the following stacktrace is appearing in the logs:
```Exception: Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:247:7 in 'consume_number'
  from ../usr/share/crystal/src/json/lexer.cr:63:7 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:108:11 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:9:5 in 'initialize'
  from ../usr/share/crystal/src/json/parser.cr:6:3 in 'new'
  from ../usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:910:20 in 'get_60_videos'
  from src/invidious.cr:3579:20 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

Not really sure, but seems like loading videos from the channel is broken?

**Comment by Vladeeg** [comment]
I'm experiencing the same problem.

Also the following stacktrace is appearing in the logs:

```Exception: Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:247:7 in 'consume_number'
  from ../usr/share/crystal/src/json/lexer.cr:63:7 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:108:11 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:9:5 in 'initialize'
  from ../usr/share/crystal/src/json/parser.cr:6:3 in 'new'
  from ../usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:895:18 in 'get_channel_videos_response'
  from src/invidious/channels.cr:913:5 in 'get_60_videos'
  from src/invidious.cr:3575:20 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

Not really sure, but seems like loading videos from the channel is broken?

**Comment by iamoverit** [comment]
have the same problem, here is more expanded log:
`2020-10-25 16:59:41 UTC 200 GET /opensearch.xml 1.19ms
2020-10-25 16:59:41 UTC 200 GET /api/v1/auth/subscriptions?fields=authorId 1.82ms
Exception: Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../usr/share/crystal/src/json/lexer.cr:247:7 in 'consume_number'
  from ../usr/share/crystal/src/json/lexer.cr:63:7 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:108:11 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:9:5 in 'initialize'
  from ../usr/share/crystal/src/json/parser.cr:6:3 in 'new'
  from ../usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:931:20 in 'get_60_videos'
  from src/invidious.cr:3483:20 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???

2020-10-25 16:59:43 UTC 500 GET /channel/UCbt5BCs0aUDgNwRaUnKtXwA 1142.16ms`

**Comment by imapotatoalso** [comment]
Not sure if invidious is dead or not, but I'll close the issue I guess

**Comment by TheFrenchGhosty** [comment]
@imapotatoalso why? Is the problem solved?

**Comment by imapotatoalso** [comment]
I'm not dealing with any issues anymore, so I assume the bug has been patched.
