### ISSUE TITLE
Playlists missing first video

### ISSUE THREAD

**Issue by Dougley** [iv-org/invidious#1382]
When playlists are loaded on Invidious, playlists are missing the first video in the playlist.

To reproduce, go to any Invidious instance and load a playlist ([example](https://invidious.snopyta.org/playlist?list=PLSfegfOiC2Ayz10yngrfQoe-GZtdI3ZIM)), you'll notice how the first video in the playlist is missing.

![](https://user-images.githubusercontent.com/9768134/94053686-eed73300-fdda-11ea-99d2-da9657dbc6ef.png)

**Comment by GauthierPLM** [comment]
I confirm this issue with this playlist ([Youtube](https://www.youtube.com/playlist?list=PLdo4fOcmZ0oX7uTkjYwvCJDG2qhcSzwZ6), [Snoopyta](https://invidious.snopyta.org/playlist?list=PLdo4fOcmZ0oX7uTkjYwvCJDG2qhcSzwZ6&autoplay=0)) missing the first episode. Same for all other playlists I opened.
