### ISSUE TITLE
Pop-up with captions?

### ISSUE THREAD

**Issue by jtagcat** [iv-org/invidious#1383]
![image](https://user-images.githubusercontent.com/38327267/94127293-48297b80-fe48-11ea-8dae-e4091ba9254d.png)

Captions are not included with the Firefox Picture-in-Picture mode.

I understand including captions would probably involve embedding them in to the video on the fly. I have a dream.

**Comment by r-a-y** [comment]
This is a browser issue and not related to Invidious.

For Firefox, keep track of this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1551058
For Chromium, this ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=854935
