### ISSUE TITLE
ERROR - http.server: Unhandled exception on HTTP::Handler Missing hash key: "preferences" (KeyError)

### ISSUE THREAD

**Issue by wapfalls** [iv-org/invidious#1386]
Am getting the following error on my hosted invidious instance server (invidious.site), instance was working fine till yesterday. Can someone help me understand the error and possible causes of this error to fix it? 

2020-09-24T20:02:52.978310Z  ERROR - http.server: Unhandled exception on HTTP::Handler
Missing hash key: "preferences" (KeyError)
  from ../../../usr/share/crystal/src/hash.cr:1030:9 in 'get'
  from src/invidious/views/template.ecr:2:17 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from src/invidious/helpers/logger.cr:17:33 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???

**Comment by Perflyst** [comment]
The error ` Missing hash key: "preferences" (KeyError)` is quite common. You should be able to just start invidious again

**Comment by wapfalls** [comment]
Yea, after multiple retries, it started fine now 👍
