### ISSUE TITLE
Channels show only recent videos twice and sometimes nothing

### ISSUE THREAD

**Issue by dentistformyeye** [iv-org/invidious#1388]
This issue seems to have started after commit 4a6e920, which was intended to fix #1333.
The videos that should show up on the first channel page (i.e. the most recent videos) appear twice. In addition, all pages of a channel show only the videos that are on the first channel page.

Furthermore, perhaps as frequently as once a day for a few tens of minutes, all channels spontaneously show nothing except for the "you've found a bug in Invidious" message. I haven't encountered it in the past three days, but I haven't seen anyone else bring it up, so I doubt the latest commits have fixed it.

**Comment by Perflyst** [comment]
The API was changed again, there is another PR in the pipeline https://github.com/iv-org/invidious/pull/1381

**Comment by TheFrenchGhosty** [comment]
Should be fixed in https://github.com/iv-org/invidious/pull/1406
