### ISSUE TITLE
Clicking on a channel shows an empty page

### ISSUE THREAD

**Issue by ManinderjitS** [iv-org/invidious#1392]
None of the videos of the channel show up after click on any Youtuber channel.

**Comment by unixfox** [comment]
Are you using the latest version of Invidious?

**Comment by TheFrenchGhosty** [comment]
Instance issue.

**Comment by ManinderjitS** [comment]
Sorry, I am not sure what you mean by the latest version of invidious @unixfox, because I was watching videos on invidious.site. 
This channel not showing videos was also an issue in invidio.us website as well, but there was a way around sometimes by clicking on the playlists link or one of the other links (or maybe that was deliberate, I am not too sure). 
What would be the solution here in this case?
Thank you guys for replying still.

**Comment by unixfox** [comment]
Unfortunately invidious.site is partially blocked by Google so that's why it's not possible to view the videos of a channel. Please use another instance if you want to have the videos of a youtube channel.

**Comment by ManinderjitS** [comment]
I see, thank you I will try other instances.
