### ISSUE TITLE
Invalid signature server response on trying to subscribe to a channel

### ISSUE THREAD

**Issue by goodness-from-me** [iv-org/invidious#1396]
Steps to reproduce.
0. Open up browser network panel to see requests and server responses.
1. Open a video page.
2. Click "Subscribe" button.
3. Notice 400 Forbidden response from server with the response: "Invalid signature"

**Comment by unixfox** [comment]
I think you are talking about https://yewtu.be. If that's the case then close this issue because it's fixed.

For any administrators that are running multiple processes of Invidious, set `hmac_key` to a fixed value because without that it will generate a random hmac key for each processes.
