### ISSUE TITLE
syntax error at or near "ON"

### ISSUE THREAD

**Issue by CaptainTyphoo** [iv-org/invidious#1397]
I am trying to selfhost invidious on CentOS 7. I followed the instructions from the README.md and was able to successfully build and run invidious. When I open the startpage it is blank, but clicking on "TRENDING" or searching for a video yields some videos that I can click on. Upon clicking on a video, only the message `syntax error at or near "ON"` is displayed without a video. In the console output of invidious the same message is printed, preceded  by the video ID.
Is there any possibility to increase the verbosity of the log?

The version that I tested is: 0.20.1-30a2c28 @ master

**Comment by matthewmcgarvey** [comment]
@CaptainTyphoo can you verify that you are running (could be multiple versions installed) Postgres version 9.5 or later? `ON CONFLICT` was only added in 9.5 https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

**Comment by CaptainTyphoo** [comment]
I was using Postgres 9.2. After switching to Postgres 12 the error disappeared and the videos started to work.
The issue with the POPULAR tab seems to be unrelated to this one (see #955).
I guess we can close the issue. Thanks for your support!
