### ISSUE TITLE
Is lsquic usage worth it?

### ISSUE THREAD

**Issue by matthewmcgarvey** [iv-org/invidious#1400]
Related: https://github.com/iv-org/invidious/issues/1328

I've been checking out invidious for a few days now and still am not able to build the lsquic c library for my machine. [Google just released a blog post](https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html) talking about quic/http3 and it states that they saw "YouTube rebuffer time decreased by over 9%."  Without knowing exactly what that means, I'm feeling rather unimpressed with the benefits when I have to rebuild and restart my docker container every time I make a change.

Were there any tests done to see the performance difference between using lsquic and regular http requests?

**Comment by TheFrenchGhosty** [comment]
If it was done it was done by @omarroth

I personally don't know what is, and why lsquick is needed.

**Comment by omarroth** [comment]
#957

**Comment by matthewmcgarvey** [comment]
@omarroth just what I was looking for, thanks 👍
