### ISSUE TITLE
Links in header overlap

### ISSUE THREAD

**Issue by kdkasad** [iv-org/invidious#1401]
With my browser window at a width of half my screen (960px), the links in the homepage header overlap. This appears on multiple instances, so it is not an issue with just one:
![image](https://user-images.githubusercontent.com/63574107/95404777-d41cb800-08ca-11eb-99e9-1338a1d28fc8.png)
![image](https://user-images.githubusercontent.com/63574107/95404823-f7476780-08ca-11eb-9f80-0dc4bd718c30.png)

**Comment by matthewmcgarvey** [comment]
Thanks for bringing this up! Just for clarity, this is a duplicate of https://github.com/iv-org/invidious/issues/1122

**Comment by kdkasad** [comment]
I figured this would've popped up already. I tried searching the existing issues but didn't see that one.

**Comment by matthewmcgarvey** [comment]
@kdkasad I pushed up a potential fix if you'd like to try it out https://github.com/iv-org/invidious/pull/1402

**Comment by kdkasad** [comment]
I have no idea how to set up a local instance of invidious, but from the pics in the PR it looks great!
