### ISSUE TITLE
Googlevideo scripts questions

### ISSUE THREAD

**Issue by Ghuzlrud** [iv-org/invidious#1405]
I want to preface this post by first stating I am a tech noob trying to foster a more intentional relationship to technology, especially better practices online. 

I've recently (within the last month or so) noticed many videos on invidious having 'googlevideo' scripts (I have 'noscripts' running) and am wondering why invidious would have these scripts on their videos. Doesn't this defeat the purpose of being a proxy? Is allowing these scripts to run not giving more information to the beast that is google? If so does anyone know of any developing youtube proxies for desktops?

**Comment by TheFrenchGhosty** [comment]
Googlevideo doesn't use any script.

NoScript do block media by default, this is what you're blocking.
