### ISSUE TITLE
Project future, after omarroth departure

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1411]
This is a follow up to #1320 providing some information about the current state of the project.

Now that @omarroth completely left Invidious (he left the Github organization, and the Matrix room), we are not expecting him to come back.

The project is currently managed by @Perflyst and me (@TheFrenchGhosty).

### Introduction:

First thing first, the project is still alive, thanks to the hard work of @Perflyst @girst and @afuous they were able to fix the first major YouTube change since @omarroth left (#1381 and #1406).

Some new work started by other contributors, this include @matthewmcgarvey that started a [project restructure](https://github.com/iv-org/invidious/commits?author=matthewmcgarvey) and @vhuynh3000 that is [currently looking to fix](https://github.com/iv-org/lsquic.cr/pull/2) one of the biggest issue Invidious currently has (#1375 and #578).

We truly hope for this to continue, so that we will be able to use Invidious for years, with new fixes and new features!

### Donations:

Donation URL and cryptocurrency addresses haven't been updated **yet**, and the project still link to those owned by omarroth.

We don't have access, nor do we know what will happen to the donations that were (maybe?) sent to the [old liberapay page](https://liberapay.com/omarroth) (the page currently [doesn't have donations enabled](https://liberapay.com/omarroth/donate), so nothing should have been sent) and to the old cryptocurrency wallets.

@Perflyst will soon create new cryptocurrency wallets. For reasons, Liberapay will be dropped.

Donations we be kept on hold on those wallets until we can discuss _who_ should get them.

### Finish line:

Invidious is still here, and alive! I would personally like to thank everyone who worked on it, and still maintain instances of it today.

My deepest thanks goes to @omarroth for allowing us to even have this discussion, and to @Perflyst who is just an amazing guy!

PS: if you want to know anything more, feel free to ask questions bellow.

**Comment by resynth1943** [comment]
You guys are awesome. ❤️

> We don't have access

Hmm. I would have suggested reaching out to Omar, but you're dropping them anyway so...

> First thing first, the project is still alive, thanks to the hard work of @Perflyst @girst and @afuous they were able to fix the first major YouTube change since @omarroth left (#1381 and #1406).

Thanks so much guys. 👍🏼 Hope Invidious keeps going, it's a solid project.

**Comment by TheFrenchGhosty** [comment]
>Hmm. I would have suggested reaching out to Omar, but you're dropping them anyway so...

Well, for the Liberapay page he created a new one for the organization (the old one was his nickname) but since we're dropping it, it doesn't mater.

We aren't dropping the crypto however (we will maybe replace BCH with XMR though, since BCH and BTC kind of have the same purpose) we will however replace the addresses with new one.

We could technically ask him to give us the wallet, but it's easy enough to create new one, so there is no need to bother him with that.

**Comment by mattbk** [comment]
Organization Liberapay is https://liberapay.com/iv-org/.

**Comment by TheFrenchGhosty** [comment]
@mattbk "For reasons, Liberapay will be dropped."

**Comment by GitWaifu** [comment]
now that google deprecated HTML as a technology and forces WebComponents Polymer on old devices that cannot open nonHTML websites - invidous instances are the easiest way to access youtube without installing addons or downloading videos to the hard drive. I wish you to get some solid sponsorship and revive the main .us instance as well

**Comment by funnyflowerpot** [comment]
Thank you all for putting in much effort to continue this project! :pray: 

I also appreciate your service of providing an update of recent developments here. I think many other people appreciate this---or would appreciate it, if they knew. I would like to kindly suggest communicating the (great) updates on Invidious via other channels, too, such as Twitter, Mastodon, or maybe a dedicated website. 

This might have the additional effect to further promote the service and possibly finding more people interested in actively supporting the project by means of code or funding.

Please keep up the good work!

**Comment by resynth1943** [comment]
> now that google deprecated HTML as a technology

That's not quite how it works. 😅 
Nevertheless, their page is quite JS-heavy, as you stated below.
I can say with confidence that Invidious is much faster than YouTube *when it works.*
When it doesn't, it's sadly a matter of playing musical chairs with your URL bar...

**Comment by TheFrenchGhosty** [comment]
> > now that google deprecated HTML as a technology
> 
> That's not quite how it works. sweat_smile


That is indeed absolutely not how it works. Google uses other technology, it doesn't mean that they are "killing" HTML in any way.

**Comment by TheFrenchGhosty** [comment]
@funnyflowerpot 

>I also appreciate your service of providing an update of recent developments here. I think many other people appreciate this---or would appreciate it, if they knew. I would like to kindly suggest communicating the (great) updates on Invidious via other channels, too, such as Twitter, Mastodon, or maybe a dedicated website.

I shared this update on [Reddit](https://old.reddit.com/r/privacy/comments/jbr8n8/invidious_project_future_after_omarroth_departure/) and in the Invidious' Matrix room. I have no desire to use something else, but others are free to share it if they want.

**Comment by simoniz0r** [comment]
If you guys aren't aware yet, [youtube-dl](https://github.com/ytdl-org/youtube-dl) has been taken down due to DMCA.  IMO, this does not bode well for the future of Invidious.

**Comment by resynth1943** [comment]
@simoniz0r

> If you guys aren't aware yet, [youtube-dl](https://github.com/ytdl-org/youtube-dl) has been taken down due to DMCA. IMO, this does not bode well for the future of Invidious.

We've got copies. Lots and lots of copies. DMCA away.

**Comment by elypter** [comment]
what are the reasons liberapay is being discontinued?

**Comment by TheFrenchGhosty** [comment]
> @simoniz0r
> 
> > If you guys aren't aware yet, [youtube-dl](https://github.com/ytdl-org/youtube-dl) has been taken down due to DMCA. IMO, this does not bode well for the future of Invidious.
> 
> We've got copies. Lots and lots of copies. DMCA away.

Indeed, we already have a mirror of the code, and a copy of everything else (issues, pr, wiki...)

**Comment by elypter** [comment]
and the problem with that is privacy or fees? if possible maybe use the donations instead to donate to upstream projects.

**Comment by Perflyst** [comment]
Some kind of privacy and we dont want to mix money for invidious and personal stuff. If there is a new maintainer (as in active developer) Liberapay could be re-added of course.

**Comment by GitWaifu** [comment]
"That is indeed absolutely not how it works. Google uses other technology, it doesn't mean that they are "killing" HTML in any way, they don't own the web, and everyone is free to use the technology they want to, including dead technologies."
Google Chromium project tracker explicitly states that all WebKit compatible "developers" agreed to deprecate free web by 2021 and youtube webcomponents polymer is just the first step. 
Considering that current antitrust lawsuit against google doesn't include their illegal monopoly over web development no one will be free to use non monetisable technologies.
Also it is disappointing to see people on a project advertised as privacy conscious and compatible with non JS Tor call a website that is completely inaccessible by truly free non webkit browsers as "JS heavy"

**Comment by funnyflowerpot** [comment]
> Google Chromium project tracker explicitly states that all WebKit compatible "developers" agreed to deprecate free web by 2021 and youtube webcomponents polymer is just the first step.

@GitWaifu "agreed to deprecate free web", do you have a reference or link for this statement? I would like to learn more. I don't understand how that "deprecation" is supposed to look like. I don't believe they will just throw a 505 and show a banner at the user saying "this website is not supported". 

Besides, if Google was really to control web standards _completely_, then even they could not break backwards compatibility of HTTP and then establish a new standard _for all users of the entire internet_ within one or two years. Apart from that there will be a community that would resist such breaking changes, similar to the very recent case of youtube-dl, but bigger.

**Comment by resynth1943** [comment]
> Google Chromium project tracker explicitly states that all WebKit compatible "developers" agreed to deprecate free web by 2021 and youtube webcomponents polymer is just the first step.

Any references?

I *heavily* doubt Google are going to deprecate HTML. They're just pushing people to use their AMP nonsense, that's all. We need more competition against Google. [Ridiculous corporate dilettantes](https://web.archive.org/web/20201021120443/https://blog.mozilla.org/blog/2020/10/20/mozilla-reaction-to-u-s-v-google/) are the opposite of what we need.

Look at YouTube. It's scary that we need a whole new project to browse YouTube, while adhering to our threat models. Regardless, rant over.

> Also it is disappointing to see people on a project advertised as privacy conscious and compatible with non JS Tor call a website that is completely inaccessible by truly free non webkit browsers as "JS heavy"

Well, I don't like it, but if the maintainers aren't ready to seek refuge elsewhere, I'm fine with that. Whatever's easiest for the maintainers, really. Let's not place burden on an already strained project.

**Comment by Coaggly** [comment]
Hwaiting!
