### ISSUE TITLE
Killed with signal 11

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1418]
```
Invalid memory access (signal 11) at address 0x0
[0x7f1b256f46e6] ???
[0x7f1b25053d15] ???
[0x7f1b26038930] ???
[0x7f1b2604fdf6] ???
```

The invidious process dies because of this.

**Comment by matthewmcgarvey** [comment]
@FireMasterK can you give us more details like
- how are you trying to run it
- have you run it successfully before

**Comment by FireMasterK** [comment]
> * how are you trying to run it

Using Docker

> * have you run it successfully before

Yes, I run a public instance, this just happens randomly every few minutes/hours and the container hence restarts.

**Comment by matthewmcgarvey** [comment]
Try increasing the amount of memory allocated to docker if you can.

**Comment by FireMasterK** [comment]
Ok, will try that 👍

**Comment by TheFrenchGhosty** [comment]
If this fixes your issue I will write some stuff in the readme about it. This isn't the first issus caused by low docker memory.

**Comment by FireMasterK** [comment]
Unfortunately, I couldn't test this as currently all my free ram is allocated to Invidious (800-900MB), and from some quick research, the only way to set the resource limits for docker-compose v3 is by deploying it as a swarm.

**Comment by FireMasterK** [comment]
From a quick search, it could be an issue in crystal: https://github.com/crystal-lang/crystal/issues/8584

**Comment by Perflyst** [comment]
> all my free ram is allocated to Invidious

You could try to add some swap to your machine.

**Comment by TheFrenchGhosty** [comment]
@FireMasterK Add swap and try again, otherwise I consider this fixed.

**Comment by FireMasterK** [comment]
If I add swap, my server would crash due to kswap0 using 100% cpu (due to my low specs), unfortunately it's impossible for me to do that.

**Comment by TheFrenchGhosty** [comment]
@FireMasterK I will consider the low spec as the issue then. No one ever reported this issue before, and no one came here saying they had the problem.
