### ISSUE TITLE
[YouTube Change] Search result are sometimes empty

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1422]
Since October 16, the day [we updated lsquic.cr](https://github.com/iv-org/lsquic.cr/pull/2) and the day we pushed #1412 search results are sometimes empty.

This isn't consistent and doesn't happen every time, but when it does usually a refresh fixes it.

This affect every instance, public or private, with a lot of users or not, with anti-captcha setup or not.

~I'm guessing that something about the lsquic.cr update is causing this, but I have really no idea.~  **This is wrong, see the edit bellow.**

The issue can appear at anytime, even with the same search term sent.

**Nothing is displayed in the log.**

25 seconds gif of the issue:
![bug](https://user-images.githubusercontent.com/47571719/96353152-0f806900-10b9-11eb-8cb8-98b43c8accc1.gif)

Link used: https://invidious.snopyta.org/search?q=test

Edit:

@afuous and @tleydxdy both reported that it was happening for them even without any recent update 

@PrestonN (developer of [FreeTube](https://github.com/FreeTubeApp/FreeTube)) reported that he was also having issue on other project.

It's maybe a new YouTube change, or a YouTube bug (but it seems weird that it's still not fixed on their end though, we'll see next week I guess) that started to happen the day we pushed those change. 

Related: https://github.com/TimeForANinja/node-ytsr/issues/71

**Comment by TheFrenchGhosty** [comment]
This issue seems fixed, and will be closed soon.

If you still notice the issue, please comment here.

**Comment by FireMasterK** [comment]
Isn't this related to https://github.com/TeamNewPipe/NewPipeExtractor/pull/415

**Comment by pieninja1** [comment]
hey its still happening to me on snopyta.

**Comment by TheFrenchGhosty** [comment]
It's still happening, I don't know why but I didn't have problem for some hours today, then it started again.

It's inconsistent.

**Comment by ChaseHall** [comment]
can confirm on my instance, very inconsistent also.

**Comment by FireMasterK** [comment]
Seems very similar to https://github.com/TeamNewPipe/NewPipe/issues/4201

This was [fixed in newpipe](https://github.com/iv-org/invidious/issues/1422#issuecomment-713059019).
