### ISSUE TITLE
Help optimize memory utilization

### ISSUE THREAD

**Issue by wapfalls** [iv-org/invidious#1425]
Right now am running invidious with Docker on my VPS having 2 cores, 2GB ram with 2GB swap on. 

Every one hour or so, physical memory is touching its peak, and instance returns 'read timeout'. Can anyone suggest best way to optimize memory utilization or free up ram when it reaches threshold set.

Right now, I have a cron setup to restart docker-compose every 1hr., coz that was the easiest option to my current knowledge, as am completely new to docker.

Also curious how other public instance holders are holding up when traffic is high on their instance. Please share your suggestions :)

Thanks!

**Comment by TheFrenchGhosty** [comment]
Cronjob that restart the instance every 1 or 2 hour, that's what everyone does.

**Comment by raycheung** [comment]
Besides the memory leakage issue, I actually found the instance may miss background refresh (not pulling videos) if I don't schedule constant restarts..
