### ISSUE TITLE
Weblate translations updates

### ISSUE THREAD

**Issue by milotype** [iv-org/invidious#1426]
Please update with Weblate translations.

Ideally, automate the process of merging Weblate translations – per change/daily/weekly/monthly or whatever seems good.

**Comment by TheFrenchGhosty** [comment]
We currently don't have access to the Weblate @omarroth 

So... it's a problem.

**Comment by omarroth** [comment]
@comradekingu should have access. Otherwise if you have a weblate account I can add you as an administrator.

**Comment by comradekingu** [comment]
I can add all admins here as Weblate admins, or cite what the setup is for anyone interested.
Adding hooks ala https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github and adding the user on here I can't do, but that is just the general way of doing it.

**Comment by milotype** [comment]
I'm no programmer, just a translator.
So, in the mean time, should I simply send a PR with my translation here at GitHub until the issue of automatic updating is resolved?

**Comment by comradekingu** [comment]
@milotype That adds some finesse to the potential merge errors, so I think we should just solve it the right wayTM :)

**Comment by TheFrenchGhosty** [comment]
@comradekingu I created an account if you can add me as an admin: https://hosted.weblate.org/user/TheFrenchGhosty/

**Comment by hackerncoder** [comment]
What is the status? Seems like @comradekingu has still not given admin to Ghosty.

**Comment by TheFrenchGhosty** [comment]
@hackerncoder Yep, I'm not admin yet.

I'll try to contact him soon-ish.

**Comment by comradekingu** [comment]
@TheFrenchGhosty Sorry I missed that. I stopped coming here to fix things when I was removed from the project. Fixed now.

**Comment by TheFrenchGhosty** [comment]
@comradekingu As I said in the email I sent you, I removed everyone that were inactive if you want to be re-added feel free to tell me.

**Comment by TheFrenchGhosty** [comment]
Done in #1696 and #1700
