### ISSUE TITLE
Read timed out.

### ISSUE THREAD

**Issue by CadenceFella2005** [iv-org/invidious#1430]
This error has been going on far too long. Ever since the real Invidious got terminated, we have to go onto its alternate websites, which can be found at dev.invidio.us . Lately, it's been giving me no search results, "media failed to download part way," read timed out, and nil assertion failure. It's giving me a major headache and I can see lots of these other guys are getting sick and tired of it too. Please do something to fix this issue. Please. We're begging you. (Or at least, tell us what we can do to help.)

**Comment by CadenceFella2005** [comment]
This error has been going on far too long. Ever since the real Invidious got terminated, we have to go onto its alternate websites, which can be found at dev.invidio.us . Lately, it's been giving me no search results, "media failed to download part way," read timed out, and nil assertion failure. It's giving me a major headache and I can see lots of these other guys are getting sick and tired of it too. Please do something to fix this issue. Please. We're begging you. (Or at least, tell us what we can do to help.)

**Comment by TheFrenchGhosty** [comment]
Instance issue.
