### ISSUE TITLE
Search doesn't work, can't view channels, when I could view channels, it kept on just showing the past 5 -10 videos they made on a loop. 

### ISSUE THREAD

**Issue by stewpidtnlvr** [iv-org/invidious#1432]
Search doesn't work, can't view profile pages, when I could view profile pages, it kept on just showing the past 5 -10 videos they made on a loop. 
![image](https://user-images.githubusercontent.com/61797693/97040418-81323a00-1533-11eb-8fd9-acb938285a53.png)

**Comment by stewpidtnlvr** [comment]
besides in https://invidious.snopyta.org/watch?v=mnNqS5d6UB8 all that doesn't work in that, is viewing channels

**Comment by TheFrenchGhosty** [comment]
Instance issue.
