### ISSUE TITLE
Use the lbry.tv server for youtube videos available on that platform

### ISSUE THREAD

**Issue by wuniversales** [iv-org/invidious#1441]
The title says it all, I think it is better to use a server other than YouTube to upload the videos. (If the video is available on lbry.tv)
So we try to reduce youtube captcha.
By the way, with lbry.tv, if you log into an account, the invidius hosting owners would receive cryptocurrencies.
Greetings

**Comment by TheFrenchGhosty** [comment]
Out of scope.
