### ISSUE TITLE
Nil assertion failed (NilAssertionError)

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1442]
Cannot get channel https://invidio.us/channel/UCITk7Ky4iE5_xISw9IaHqpQ

It's because you do not support redirect channels. The url you get on youtube is https://invidious.snopyta.org/channel/UCrxkwepj7-4Wz1wHyfzw-sQ. See https://github.com/TeamNewPipe/NewPipeExtractor/pull/440

**Comment by charliebarber** [comment]
I would like to try and fix this. Do you have any more information about redirect channels?

**Comment by B0pol** [comment]
Date: `2020-11-30T15:30:26Z`
Route: `/channel/UCITk7Ky4iE5_xISw9IaHqpQ`
Version: `0.20.1-78ae9ff @ master`
Backtrace: 
```
Nil assertion failed (NilAssertionError)
  from ../../../usr/lib/crystal/nil.cr:106:5 in 'not_nil!'
  from src/invidious/channels.cr:804:12 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/lib/crystal/http/server.cr:498:5 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ???
```

**Comment by B0pol** [comment]
On pussthecat.org, updated to last commit, the error is now different:


Date: `2020-11-30T19:37:33Z` Route: `/channel/UCITk7Ky4iE5_xISw9IaHqpQ` Version: `0.20.1-4acfd2c @ master` Backtrace: ``` Missing hash key: "metadata" (KeyError) from ../../../usr/lib/crystal/hash.cr:1030:9 in '[]' from src/invidious/channels.cr:804:12 in 'get_about_info' from src/invidious.cr:2475:15 in '->' from ../../../usr/lib/crystal/primitives.cr:255:3 in '->' from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from src/invidious/helpers/static_file_handler.cr:189:11 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call' from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process' from ../../../usr/lib/crystal/http/server.cr:498:5 in '->' from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run' from ??? ```
