### ISSUE TITLE
Blank page after logging in

### ISSUE THREAD

**Issue by MMDaino** [iv-org/invidious#1444]
![firefox_HtK0pCZLDP](https://user-images.githubusercontent.com/44116104/97340471-badcab00-187b-11eb-999f-03c4bbf3c645.png)

**Comment by petterreinholdtsen** [comment]
I see this too.  Did youtube change again?

**Comment by TheFrenchGhosty** [comment]
Is the instance updated?

**Comment by Perflyst** [comment]
Does this still happen?
