### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1445]
When you perform a search, There are no results. As soon as I logged in, it gave a message saying something like "you've found a bug. report it here".

**Comment by nathgit** [comment]
I don't know if it's related or if I should open a new issue, but I also get an error when I try to watch a link from youtube.

**Comment by TheFrenchGhosty** [comment]
Instance issue.

>Too bad. Without the lead developer is there any chance of this even being fixed or should I just consider invidious to be dead & move on?

Invidious is fine. You should consider using an updated instance.

**Comment by nathgit** [comment]
Now it says "502 bad gateway". The problem is if I switch to another instance, how long before it acts up too & I have to switch instances again? There's only a few instances & many of them don't even support new accounts.
