### ISSUE TITLE
On some channels, videos tab is missing

### ISSUE THREAD

**Issue by dentistformyeye** [iv-org/invidious#1446]
On some channels, the videos tab, which is selected by default, doesn't appear in Invidious even though there is a videos tab on the Youtube channel. When this happens, the playlists tab is shown instead.

### Actual result
Example from the [Yewtube instance
](https://yewtu.be/channel/UCpa-Zb0ZcQjTCPP1Dx_1M8Q)

Invidious page:
![image](https://user-images.githubusercontent.com/51429646/97479715-ec5f8000-1928-11eb-95f8-da35c804e27b.png)

Youtube page for reference:
![image](https://user-images.githubusercontent.com/51429646/97480070-50824400-1929-11eb-8cb9-1d2e89da82bd.png)

### Expected result
The Invidious page should show a videos tab:
![image](https://user-images.githubusercontent.com/51429646/97479994-347ea280-1929-11eb-9d8d-72bafd46fdf8.png)

**Comment by GitWaifu** [comment]
joe rogan experience and some other million+ subs channels have the same issue
