### ISSUE TITLE
Playlist video count does not update accordingly

### ISSUE THREAD

**Issue by raycheung** [iv-org/invidious#1448]
Issue:
The playlist video count is wrong on add / drop video.

Steps to reproduce:
- Create a playlist / pick an existing playlist
- Add a video with the drop down menu on the left
- Go to playlist page and observe the video count, it's not updated
- Remove a video from an existing playlist, the video count is also not updated

**Comment by Perflyst** [comment]
Closed via https://github.com/iv-org/invidious/pull/1449
