### ISSUE TITLE
Playlist starts from the beginning after the first play, disregard the sequence

### ISSUE THREAD

**Issue by raycheung** [iv-org/invidious#1451]
Issue:
For a playlist with a few videos, play a video in the middle of it. When that video finishes, the beginning of the playlist is played next, instead of the immediate video according to the sequence.

Steps to reproduce:
- Go to playlist, select a playlist with multiple videos
- Click on a thumbnail of a video in the middle of the sequence to start playing
- After that video finishes, the beginning of the playlist is played, not the next in sequence

**Comment by raycheung** [comment]
The playlist rendering misses the `index` (an offset count) in https://github.com/iv-org/invidious/blob/master/src/invidious/views/playlist.ecr#L91 when passing on to link generation at https://github.com/iv-org/invidious/blob/master/src/invidious/views/components/item.ecr#L55 .

I couldn't figure a way to pass the offset around with `rendered`.

**Comment by TheFrenchGhosty** [comment]
@raycheung I just tested, and I actually don't have this issue.

I tried a playlist with 116 videos, played a video at around the middle, the following video was the next one in the playlist.

I also tried a playlist with 8 videos, same result.

Do you have an example playlist? Right no I can't reproduce the issue.

**Comment by raycheung** [comment]
Let me test it over again, I doubt if it was my browser issue.

**Comment by raycheung** [comment]
> 
> 
> @raycheung I just tested, and I actually don't have this issue.
> 
> I tried a playlist with 116 videos, played a video at around the middle, the following video was the next one in the playlist.
> 
> I also tried a playlist with 8 videos, same result.
> 
> Do you have an example playlist? Right now, I can't reproduce the issue.

I'm looking my local playlist,
```
{"title":"點播","description":"","privacy":"Public","videos":["WQzU0zVG4hg","kTzUwhPuIwg","8RcLFOCJiww","zxq8mp5LcBo","tsVXQwE_MuY","DXjN9aIn2yc","UL3rtnZB93s","gGcHv7NxLh0","UeBB_9R_FHY","ttFcm7-IBLQ","HjA8JMYrZoY","Qc6Hlg1wyfs","FjS50ATT1v0","LGz4CGazqNQ","8wB0S5nZMJw","3DGOlguqseQ","AP-jOWm7Fu4","RyoFapcT8o4","-olEFyZJ77g"]}
```

Let say I click on `LGz4CGazqNQ` at the playlist to start playing, when it finishes it would jump to `kTzUwhPuIwg` instead of `8wB0S5nZMJw`. Worse, somehow no matter which video of the playlist I started with, the immediate next would by stickily `kTzUwhPuIwg` and continue from there.

**Comment by TheFrenchGhosty** [comment]
@raycheung So I guess this only affect playlist made in Invidious?

**Comment by raycheung** [comment]
Yes the playlist was created within Invidious
