### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [iv-org/invidious#1454]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/iv-org/invidious/blob/master/screenshots/03_subscriptions.png?raw=true

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by TheFrenchGhosty** [comment]
Fixed in #1543
