### ISSUE TITLE
Yewtu.be is unable to view a channel’s playlists

### ISSUE THREAD

**Issue by CatsLover2006** [iv-org/invidious#1458]

**Comment by TheFrenchGhosty** [comment]
Instance issue.

**Comment by elypter** [comment]
where are we supposed to report instance issues?

**Comment by TheFrenchGhosty** [comment]
@elypter To their owner.

**Comment by elypter** [comment]
it is often unclear where the problem stems from and the instances direct users to this github page by default and there usually is no way to contanct the admin. i think there sould either be a separate infrastructure to deal with these problems or it should be allowed to be addressed here maybe with an [instance] tag.
