### ISSUE TITLE
Error on video page: "Missing hash key: "playabilityStatus""

### ISSUE THREAD

**Issue by tennessean** [iv-org/invidious#1467]
A few hours ago, while attempting to watch a video on the Yewtu.be instance of Invidious, I started encountering this error:

>Missing hash key: "playabilityStatus"

I tried a number of other videos at random, and they all gave this same error.  I tried several other Invidious instances (e.g. Snopyta and others), and the same thing happened there.  I even waited a few hours before trying again; no dice there either.  I'm not sure what would cause this (could Google have changed something regarding their videos, or could something in the Invidious coding have gotten borked, or something else?), but nonetheless I am hoping that the source(s) of the problem can be located and fixed by people who are far more knowledgeable than I am on stuff like this.

I thought I'd bring it to your attention, and if anyone else is having similar issues, please share them here.  If it turns out that at least a few other people are having similar issues, then that would almost certainly indicate that there's a major issue.

**Comment by omar-elnaggar** [comment]
YouTube had gone down when you tried to watch those videos. I encountered the same thing. Try again now. YouTube fixed their side.

**Comment by TheFrenchGhosty** [comment]
YouTube issue.
