### ISSUE TITLE
[Feature Request] Featured Channels

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1470]
Request originally sent to my e-mail address on October 31, 2020:

Add option to promote interesting channels on the homepage or in an extra tab.

Bibliogram has a similar feature, example is on https://bibliogram.art/ at the bottom "Featured profiles".

**Comment by pythonInRelay** [comment]
If this is mandatory then no way. If it is optional then I suppose when every other more important feature has been implemented sure. Though if you really want something this, why not just use Youtube?

**Comment by TheFrenchGhosty** [comment]
>If this is mandatory then no way. If it is optional then I suppose when every other more important feature has been implemented sure.

It's optional on Bibliogram, so it will have to be optional in Invidious too.

>Though if you really want something this, why not just use Youtube?

You're not wrong, I guess some people just want to advertise some creators?

>You can expect that mirrors that had such a feature could be seen as endorsing those channels, which opens up a whole world of problems.

I guess.

**Comment by PrestonN** [comment]
Isn't the Popular tab already a "Featured Channels" page since it's just the top 40 channels subscribed to that instance?  I'm trying to see what's different about this as a "Featured Channels" page would more or less be the same list of channels as Popular.

**Comment by TheFrenchGhosty** [comment]
@PrestonN Like Bibliogram, channel choosen by the instance admins.

**Comment by syeopite** [comment]
I'm personally against this though if we were to implement it then perhaps we should use the page added by #1977 and create something along the lines of the top sites widget from Firefox's homepage.
