### ISSUE TITLE
Feature Request: Add embed link

### ISSUE THREAD

**Issue by ubone** [iv-org/invidious#1471]
Add embed link to YT next to the watch on YT link ie https://www.youtube.com/embed/some-id

**Comment by Obosobrio** [comment]
Gone. !!

——-
Warning : May contain misinformation. Recipients must take responsibility
for fact checking content.
——-

On Nov 12, 2020, at 09:15, ubone <notifications@github.com> wrote:

﻿
Add embed link to YT next to the watch on YT link ie https://www.youtube.com/embed/some-id

**Comment by TheFrenchGhosty** [comment]
@Obosobrio What?
