### ISSUE TITLE
invideo.us no longer lists instances

### ISSUE THREAD

**Issue by tamis-laan** [iv-org/invidious#1472]
I was using `invidio.us` to get a list of instances and to randomly select a healthy one to use. This in order to spread load between the instances instead of always relying on a single instance. However `invidio.us` broke down and is no longer listing any instances!

**Comment by unixfox** [comment]
related to https://github.com/iv-org/instances.invidio.us/issues/12

**Comment by unixfox** [comment]
@TheFrenchGhosty this can be closed.

**Comment by Perflyst** [comment]
Closed via https://github.com/iv-org/instances.invidio.us/pull/13
