### ISSUE TITLE
"Video unavailable." on some (random) videos but can still play the video, but can't view comments or some metadata

### ISSUE THREAD

**Issue by TheRealJohnCena92** [iv-org/invidious#1475]
Latest commit, DASH

Sometimes going on videos shows "Video unavailable." under the video display. The video still works fine, however

* Comments don't load

* Likes/dislikes are 0 but view count still works

* This is some other metadata, I will update if there are some differences between videos.
```
Genre:

Family friendly? No

Wilson score: 0.0

Rating: 4.9651 / 5

Engagement: 0.0%
```

* Channel profile picture is not shown

* Subscriber count is not shown

The issue cannot be reproduced by me. Restarting invidious sometimes works, changing IP sometimes works. But if you wait some hours the issue is gone but it happens with other videos. I have to use another instance.

The instance is private and self hosted.

I couldn't see any 403 in the logs but I will probably make an update after more investigation. But for now I want to notify that its happening.

**Comment by Feodor2** [comment]
This reproduce
https://yt.iswleuven.be/watch?v=rDrFyCgmR-U
Can play video only when disable scripts

**Comment by tirz** [comment]
Also related to https://github.com/iv-org/invidious/pull/1490
It should be fixed by updating Invidious.

You can try here: https://vid.encryptionin.space/watch?v=rDrFyCgmR-U
