### ISSUE TITLE
Search page result are the same

### ISSUE THREAD

**Issue by DavidHenryThoreau** [iv-org/invidious#1480]
The differences between the first search page :
https://invidious.snopyta.org/search?q=diresta
and others pages are the same :
https://invidious.snopyta.org/search?q=diresta&page=2
https://invidious.snopyta.org/search?q=diresta&page=3
https://invidious.snopyta.org/search?q=diresta&page=4

**Comment by girst** [comment]
here's how to solve this issue. for reference, here's the patch for s.gir.st:

https://git.gir.st/subscriptionfeed.git/commitdiff/ec4bfb8ab7a4c9cd492405b412705a42dffbaa3d

- the query parameter `q` has been renamed `search_query`
- the `page` query parameter has to be removed
- an offset `(page-1)*20` has to be given to the search_params object as field 9, type int64.

below is a patch against `fe73ecc`, not tested, since i don't run an instance.

CC: @Perflyst, @TheFrenchGhosty, @tirz (since you worked on search recently, hope that's ok).

```diff
--- search.cr.old	2020-11-29 02:14:58.078936252 +0100
+++ search.cr	2020-11-29 02:21:01.011372730 +0100
@@ -252,7 +252,7 @@
 def search(query, page = 1, search_params = produce_search_params(content_type: "all"), region = nil)
   return 0, [] of SearchItem if query.empty?
 
-  body = YT_POOL.client(region, &.get("/results?q=#{URI.encode_www_form(query)}&page=#{page}&sp=#{search_params}&hl=en").body)
+  body = YT_POOL.client(region, &.get("/results?search_query=#{URI.encode_www_form(query)}&sp=#{search_params}&hl=en").body)
   return 0, [] of SearchItem if body.empty?
 
   initial_data = extract_initial_data(body)
@@ -263,11 +263,12 @@
   return items.size, items
 end
 
-def produce_search_params(sort : String = "relevance", date : String = "", content_type : String = "",
+def produce_search_params(page : Int64 = 1, sort : String = "relevance", date : String = "", content_type : String = "",
                           duration : String = "", features : Array(String) = [] of String)
   object = {
     "1:varint"   => 0_i64,
     "2:embedded" => {} of String => Int64,
+    "9:varint"   => (page-1)*20,
   }
 
   case sort
@@ -439,10 +440,10 @@
       count = 0
     end
   else
-    search_params = produce_search_params(sort: sort, date: date, content_type: content_type,
+    search_params = produce_search_params(page: page, sort: sort, date: date, content_type: content_type,
       duration: duration, features: features)
 
-    count, items = search(search_query, page, search_params, region).as(Tuple)
+    count, items = search(search_query, search_params, region).as(Tuple)
   end
 
   {search_query, count, items}
```

```diff
--- invidious.cr.old	2020-11-29 02:22:09.383794037 +0100
+++ invidious.cr	2020-11-29 02:22:28.843851067 +0100
@@ -3461,14 +3461,14 @@
   content_type ||= "video"
 
   begin
-    search_params = produce_search_params(sort_by, date, content_type, duration, features)
+    search_params = produce_search_params(page, sort_by, date, content_type, duration, features)
   rescue ex
     env.response.status_code = 400
     error_message = {"error" => ex.message}.to_json
     next error_message
   end
 
-  count, search_results = search(query, page, search_params, region).as(Tuple)
+  count, search_results = search(query, search_params, region).as(Tuple)
   JSON.build do |json|
     json.array do
       search_results.each do |item|
```

**Comment by rozbb** [comment]
The above patch doesn't compile as-is. If you change `page` to `page.as_int64()` in the calls to `produce_search_params` above, it compiles.

But even when it does compile, this patch doesn't fix the issue for me.

**Comment by girst** [comment]
>But even when it does compile, this patch doesn't fix the issue for me.

Seems like that'll require switching to `&pbj=1` then. This parameter returns JSON directly instead of the plain HTML page to parse, so I replaced the call to
extract_initial_data with one to JSON.parse().

pbj=1 requires some 'x-youtube-client-*' headers to be present, but
afaics, are already added with src/invidious/helpers/utils.cr.

new patch below. (keep the invidious.cr one from above)


```diff
--- search.cr.old	2020-11-29 02:14:58.078936252 +0100
+++ search.cr	2020-11-29 12:33:36.696509629 +0100
@@ -252,10 +252,10 @@
 def search(query, page = 1, search_params = produce_search_params(content_type: "all"), region = nil)
   return 0, [] of SearchItem if query.empty?
 
-  body = YT_POOL.client(region, &.get("/results?q=#{URI.encode_www_form(query)}&page=#{page}&sp=#{search_params}&hl=en").body)
+  json_rsp = YT_POOL.client(region, &.get("/results?search_query=#{URI.encode_www_form(query)}&sp=#{search_params}&hl=en&pbj=1").body)
   return 0, [] of SearchItem if body.empty?
 
-  initial_data = extract_initial_data(body)
+  initial_data = JSON.parse(json_rsp).as_h
   items = extract_items(initial_data)
 
   # initial_data["estimatedResults"]?.try &.as_s.to_i64
@@ -263,11 +263,12 @@
   return items.size, items
 end
 
-def produce_search_params(sort : String = "relevance", date : String = "", content_type : String = "",
+def produce_search_params(page : Int64 = 1, sort : String = "relevance", date : String = "", content_type : String = "",
                           duration : String = "", features : Array(String) = [] of String)
   object = {
     "1:varint"   => 0_i64,
     "2:embedded" => {} of String => Int64,
+    "9:varint"   => (page.as_int64()-1)*20,
   }
 
   case sort
@@ -439,10 +440,10 @@
       count = 0
     end
   else
-    search_params = produce_search_params(sort: sort, date: date, content_type: content_type,
+    search_params = produce_search_params(page: page, sort: sort, date: date, content_type: content_type,
       duration: duration, features: features)
 
-    count, items = search(search_query, page, search_params, region).as(Tuple)
+    count, items = search(search_query, search_params, region).as(Tuple)
   end
 
   {search_query, count, items}
```

**Comment by rozbb** [comment]
This one has nontrivial issues compiling. You should try setting up a VM with invidious to use as a testbench. I did it recently and I gotta say it's not bad as long as 1. you're not trying to make it internet accessible, and 2. you make sure to give yourself at least 2GB of swap space.

**Comment by 138138138** [comment]
Tested the JSON format. Page=??? has no effect on results.
There is a "continuationItemRenderer", which make a POST to /youtubei/v1/search with a token when next page is clicked.

**Comment by tenpura-shrimp** [comment]
I can confirm this approach is working.  I also thought it didn't at first but it turns out we probably all made the same oopise whoopsie.

![fsdjflksajdlks](https://user-images.githubusercontent.com/74318225/109246397-102bb900-7797-11eb-9d9a-50ae2d220491.png)

Has type inference gone too far?

**Comment by tenpura-shrimp** [comment]
Specifically, if you applied this patch, then you removed page from the caller for search, but didn't remove it from the method signature.  This means that the args all got offset by 1 and the search_params ended up going to the page variable which gets ignored.

Removing page from the method signature and otherwise making any other necessary changes to make it compile will reach the next page.
