### ISSUE TITLE
how to add http proxy

### ISSUE THREAD

**Issue by srikanta159** [iv-org/invidious#1481]
I want to make all requests to youtube using an HTTP proxy.

**Comment by unixfox** [comment]
you can't, Invidious doesn't support HTTP proxy.

**Comment by FireMasterK** [comment]
You can do that by enabling "Proxy Videos" in the preferences.

**Comment by unixfox** [comment]
> You can do that by enabling "Proxy Videos" in the preferences.

No it's not the same feature, @srikanta159 would like to pass all the requests to YouTube using an HTTP proxy not proxy the requests from his browser through the invidious server.

**Comment by FireMasterK** [comment]
> No it's not the same feature, @srikanta159 would like to pass all the requests to YouTube using an HTTP proxy not proxy the requests from his browser through the invidious server.

Ah, I see, I believe Invidious already does this for circumventing geo-restrictions.

**Comment by unixfox** [comment]
> > No it's not the same feature, @srikanta159 would like to pass all the requests to YouTube using an HTTP proxy not proxy the requests from his browser through the invidious server.
> 
> Ah, I see, I believe Invidious already does this for circumventing geo-restrictions.

No it does not, it's not implemented yet.

**Comment by FireMasterK** [comment]
https://github.com/iv-org/invidious/blob/074497b0f66b055b663015e3ed4d674d24b5b9cd/src/invidious/helpers/utils.cr#L89-L98

**Comment by Perflyst** [comment]
Invidious only proxies some (dont ask me which exactly) through a proxy. It is not possible to proxy everything to a single proxy

**Comment by FireMasterK** [comment]
Furthermore, it seems that only SOCKS5 proxies supports UDP, which is a requirement for QUIC.
