### ISSUE TITLE
Opinion on using Arc.io for handling server costs

### ISSUE THREAD

**Issue by wapfalls** [iv-org/invidious#1484]
Hey all,

Just came across this peer-to-peer CDN, which pays website owners for enabling its users to share their unused bandwidth for content delivery across its network. Also, users if they don't want can easily opt-out from sharing their bandwidth.

Read their take on Privacy and handing user info, seems legit.
https://arc.io/about | https://arc.io/faq

I think it's one way to handle server costs without compromising user privacy with annoying ads.

Let me know your opinion, or if it violates any of the licensing/laws.

**Comment by FireMasterK** [comment]
It really looks like a nice way to describe a botnet. If I understand correctly, it allocates 300 MB of "cache" from other websites and let's you serve them to other visitors, thus serving non Invidious content. Also, this thing requires you to keep a widget visible on your site, which I as an instance owner would not like that. This thing seems more like a way to sell your user's bandwidth for money than a cdn...

**Comment by TheFrenchGhosty** [comment]
@FireMasterK Thank you for digging into this project.

Obviously this is a no.
