### ISSUE TITLE
Automatic refresh for error pages (idea)

### ISSUE THREAD

**Issue by Gert-dev** [iv-org/invidious#1486]
All kinds of errors can occur for end users that are not always the fault of the instance itself, such as captcha issues, temporary timeouts due to network issues (e.g. #1132), and so on. For end users, this usually means they need to refresh the page, which often fixes these issues, as they are of a temporary nature.

When you're listening to a playlist in the background that is automatically moving from video to video, you're sporadically suddenly thinking "why is no video or music playing anymore", and then it turns out such an error occurred and you just need to refresh to get it going again. This got me wondering if it would be interesting to add an (optional?) auto-refresh to the error pages; say after 5 or even 10 seconds.

It should probably not be set too low as it might strain the instance, especially if there are problems of a more permanent nature (i.e. code breakages due to API changes). Usually having to wait a couple of seconds longer for a next song to start is not a problem, I think.

**Comment by unixfox** [comment]
For HTML pages, like the search page or front page, this can be done using the web server, nothing has to be added to Invidious.

But after loading a video page or music page, Invidious should already retry by itself if one request errors out.

**Comment by unixfox** [comment]
Closing as we now display a message for easily retrying manually.
