### ISSUE TITLE
docker-compose: Unhandled exception: (no message) (DB::ConnectionRefused)

### ISSUE THREAD

**Issue by Kreyren** [iv-org/invidious#1487]
log: https://gist.githubusercontent.com/Kreyren/c1ec5c70e203d8c10c2aa7828a946788/raw/46a6737f90f446660c84e573ba3db3a1b650c45c/gistfile1.txt

Commit: 1973f93d4a2b54f7284cc407ef05da232272269b

**Comment by Perflyst** [comment]
looks like postgresql is not ready yet. can you check if you can reacht port 5432 with telnet or sth?

**Comment by Kreyren** [comment]
EDIT: Sorry!, forget to undo my changes, new log attached.

**Comment by Perflyst** [comment]
your database is still not initialized correctly
```
[0m[33mpostgres_1   |[0m 2020-11-23 19:40:45.355 UTC [46] FATAL:  role "postgres" does not exist
[33mpostgres_1   |[0m 2020-11-23 19:40:45.799 UTC [47] FATAL:  database "invidious" does not exist
```

**Comment by Kreyren** [comment]
Solved, It seemed to be some issue in my userland, but i wasn't able to figured out what caused it.
