### ISSUE TITLE
Search Broken

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1488]
![image](https://user-images.githubusercontent.com/20838718/100190182-b3a8cb80-2f13-11eb-8907-e5c096cbf92c.png)

https://invidious.kavin.rocks/search?q=bitcoin
https://invidious.snopyta.org/search?q=bitcoin

**Comment by carverh** [comment]
Can confirm is broken on my instance as well.

**Comment by dentistformyeye** [comment]
Is this due to a change in Youtube? Up to date instances worked just fine until late yesterday. Even an instance that's still on version 0.20.1-9995a8d shows a blank space, where there would be "nil assertion failed".
Video playback still works as usual.

**Comment by TheFrenchGhosty** [comment]
@dentistformyeye 

>Is this due to a change in Youtube?

Yes, supposedly.

**Comment by FireMasterK** [comment]
It's quite weird that these changes only broke Invidious, yt-dlc, and NewPipeExtractor work just fine.

**Comment by LostWanita21** [comment]
Can confirm it affects both Yewtube and the Snopyta instances, I'm thinking it's something on Youtubes end since I'm getting similar search issues on Freetube.

**Comment by qorg11** [comment]
Not working in my .onion (if that has something to do) instance

**Comment by andrigamerita** [comment]
I can confirm the bug started occurring on my locally hosted instance (0.20.1-1973f93@master) as well, from about 45 hours ago. The strange thing I have experienced is the search was not entirely broken: it had like 10% chance of working and displaying results. As of now it seems to have stopped working completely.

**Comment by Coaggly** [comment]
> I can confirm the bug started occurring on my locally hosted instance (0.20.1-1973f93@master) as well, from about 45 hours ago. The strange thing I have experienced is the search was not entirely broken: it had like 10% chance of working and displaying results. As of now it seems to have stopped working completely.

I'm also having a near identical experience.

**Comment by TheFrenchGhosty** [comment]
Locking since it's becoming a "me too" issue. The fix ( #1491 ) will be merged soon

**Comment by qorg11** [comment]
I updated invidious but my search is still not working...
