### ISSUE TITLE
Invidious and Javascript

### ISSUE THREAD

**Issue by jetrotal** [iv-org/invidious#1489]
Hi, I'm a newbie in javascript coding and I'm trying to write a browser-based karaoke front end that uses youtube embeds, here's what i made so far:

https://jetrotal.github.io/ytoke/ 
https://github.com/jetrotal/ytoke

Right now i'm using googles' search api to retrieve a bunch of links from site:youtube.com

But, google's api is too limited and too expensive.

Searching through opensource alternatives I found Invidious api. The thing is that everything in there looks kinda alien to me, due to my lack of experience on it.

So I'd like to ask some questions in order to learn how to use it:

- Is it possible to use the api to retrieve videos' IDs/Links?
- Do I need to install/host or run any npm or server stuff, 
Or could I just ask for the Json hosted online?

Thanks in advance!

**Comment by FireMasterK** [comment]
> - Is it possible to use the api to retrieve videos' IDs/Links?

Yes, check out the wiki pages as they have the documentation for it.

> - Do I need to install/host or run any npm or server stuff, 
> Or could I just ask for the Json hosted online?

You could use any of the Invidious instances for their APIs. You don't need to host any server to use the API.
