### ISSUE TITLE
Nil assertion failed upon opening channel links

### ISSUE THREAD

**Issue by LostWanita21** [iv-org/invidious#1494]
Whenever I click top open a channel, the page doesn't load anything and Invidious throws up a "Nil assertion failed" error, tested on both Snoypta and Yewtu.be

Quick example channel.
https://www.youtube.com/user/AdmiralMcFish

This happens regardless of channel and regardless of how I open it, either a redirect or from within Invidious.

**Comment by hackerncoder** [comment]
It's known, happened while trying to fix searching.

Btw, could you test if it works on https://vid.encryptionin.space/channel/UC2AtE_qJm8rjTotFuKxFMyQ ?

**Comment by LostWanita21** [comment]
> It's known, happened while trying to fix search.
> 
> Btw, could you test if it works on https://vid.encryptionin.space/channel/UC2AtE_qJm8rjTotFuKxFMyQ ?

It worked when I clicked on that link yeah.

**Comment by rderensy** [comment]
It works for me right now on Snopyta but not on my personal instance whereas we're on the same version.

**Comment by Coaggly** [comment]
This is happening to me too. Yewtube is still not displaying some channels.  https://vid.encryptionin.space is saying 'Read timed out ', yewtube is saying ' Nil assertion failed '.

**Comment by hackerncoder** [comment]
I just needed to update my instance, https://vid.encryptionin.space is now working again.

**Comment by stemy2** [comment]
It still happens for me. It's totally random. Sometimes it works, sometimes i have "nil assertion failed", sometimes i have this.

`Looks like you've found a bug in Invidious. Please open a new issue on GitHub and include the following text in your message:`

Date: `2020-11-30T20:40:29Z`
Route: `/channel/UCwa-qCAFghXwkcQvLadzRxQ`
Version: `0.20.1-78ae9ff @ master`
Backtrace: 
```
Nil assertion failed (NilAssertionError)
  from ../../../usr/share/crystal/src/nil.cr:106:5 in 'not_nil!'
  from src/invidious/channels.cr:805:16 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../../../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../../../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

**Comment by Coaggly** [comment]
> /channel/UCwa-qCAFghXwkcQvLadzRxQ

This worked for me in yewtu.be just now. Try this:

https://yewtu.be/channel/UCwa-qCAFghXwkcQvLadzRxQ

Is it working?

**Comment by stemy2** [comment]
> @stemy2
> 
> > /channel/UCwa-qCAFghXwkcQvLadzRxQ
> 
> This worked for me in yewtu.be just now. Try this:
> 
> https://yewtu.be/channel/UCwa-qCAFghXwkcQvLadzRxQ
> 
> Is it working?

Nope, i have "connection failed".
