### ISSUE TITLE
[AGPL Violation] invidious.q3host.com is running an unpublished modified source

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1495]
For everyone reading this, don't use the instance, obviously.

---

This is the second instance that's been caught running an unpublished modified source ( #1456 ).

The change that I can see are:

- Modified service name

- Source code link removed, and replaced with a company link

- Donation links and address replaced with some different one

Note: this is what I could find, but there's maybe more.

---

The instance has been removed from the instance list.

---

The instance was also added to the top of the instance list [here](https://github.com/iv-org/invidious/wiki/Invidious-Instances/_compare/d3129966b9294bf886f2ac863871227734d6596b...8c7c07a01f640f2a917e79095b28a9f9d21dbf27)... even though one of the first line of the list is "Note: Please add new instances on the bottom so that every user can see how old and how long an instance is listed here.". 

Considering the instance is hosted by a company, I'm guessing this was done on purpose.

---

More digging: 

I thought maybe "q3host" offered hosting on their subdomain, but couldn't find anything, this is why I'm guessing this is hosted by the company.

I can't find any information about the company. I can't even find proper legal information about its ownership.

**This almost looks like a scam company.**

---

@srikanta159 you seems to be the owner. You are currently violating the AGPL, explain yourself and publish your source code.

**Comment by srikanta159** [comment]
@TheFrenchGhosty thanks for letting me know. I didn't have any idea related to AGPL. I have removed the instance. will revert changes that I made into this instance. 
and Q3Host is not a scam. I'm running it as a sole proprietorship since 2014. 
I'm extremely sorry if I broke any rules of invidious open source project.
