### ISSUE TITLE
Missing error translations

### ISSUE THREAD

**Issue by saltycrys** [iv-org/invidious#1497]
Missing translations:
  - `Login has been disabled by administrator.`
  - `Account has temporarily been disabled`
  - `Registration has been disabled by administrator.`
  - `Administrator has disabled this endpoint.`
  - `Title cannot be empty.`
  - `Invalid privacy setting.`
  - `User cannot have more than 100 playlists.`
  - `Playlist cannot have more than 500 videos`
  - `This playlist is private.`
  - `Video is unavailable.`
  - `Invalid parameters.`
  - `Could not extract continuation.`
  - `Could not extract community tab.`
  - `Could not extract channel info. Instance is likely blocked.`
  - `Could not extract channel JSON`
  - `Could not extract playlist info. Instance is likely blocked.`
  - `Could not extract playlist info`
  - `Could not extract author info`
  - `Invalid scope`
  - `Invalid signature`

**Comment by saltycrys** [comment]
They are all missing from the locale files. I don't know how those are handled and if they can be edited directly or if they need to be updated through Weblate. If they can be edited directly I'll do so.

**Comment by TheFrenchGhosty** [comment]
Blocked because of  #1426

**Comment by syeopite** [comment]
#1426 has been resolved. Shouldn't this issue be unblocked?

**Comment by unixfox** [comment]
It would be great to have some documentation about how to add new translations in the code.

**Comment by SamantazFox** [comment]
Yes! Good idea!
