### ISSUE TITLE
Change default admin email address

### ISSUE THREAD

**Issue by saltycrys** [iv-org/invidious#1499]
Currently the default admin email address is `omarroth@protonmail.com`.

This is displayed in error messages:
>  Looks like you've found a bug in Invidious. Feel free to open a new issue <a href="https://github.com/iv-org/invidious/issues">here</a> or send an email to <a href="mailto:#{CONFIG.admin_email}">#{CONFIG.admin_email}</a>.

The default admin email address should be changed to one that belongs to a current maintainer so all bug reports end up in the issue tracker.

**Comment by TheFrenchGhosty** [comment]
I'll open an email for Invidious that will be shared between the people that maintain Invidious.

**Comment by FireMasterK** [comment]
Why not use something like https://fire.fundersclub.com/? Sending an email would create an issue here.

**Comment by saltycrys** [comment]
Another option is to not include the admin email address in the error message. And add more useful information while we're at it.

The message could be changed to something like:
> Looks like you've found a bug in Invidious. Please open a new issue <a href="https://github.com/iv-org/invidious/issues">on GitHub</a> and include the following text in your message:
> <pre>```
> Date: 2020-01-23T00:00:00+0
> Route: /route/here
> Version: 0.20.1-hashhere @ master
> ```</pre>

**Comment by Perflyst** [comment]
Sounds good to me
