### ISSUE TITLE
 SponsorBlock FR

### ISSUE THREAD

**Issue by ToughGuyKunio** [iv-org/invidious#1502]
Integrate [SponsorBlock](https://sponsor.ajay.app/about/).
>SponsorBlock is an open-source crowdsourced browser extension and open API for skipping sponsor segments in YouTube videos. Users submit when a sponsor happens from the extension, and the extension automatically skips sponsors it knows about. It also supports skipping other categories, such as intros, outros and reminders to subscribe.

Source: https://github.com/ajayyy/SponsorBlock

**Comment by anjum-ahmed** [comment]
SponsorBlock is already integrated. On SponsorBlock, click on "options", then click the slider for "Support Invidious".

**Comment by ToughGuyKunio** [comment]
Oops okay thanks!

**Comment by elypter** [comment]
@anjum-ahmed its not integrated. invidious is supported by sponsorblock but you need to have the addon installed. 

@TheFrenchGhosty there is still a benefit to have a dedicated implementation for people who cannot install browser addons or who are wary. clicking a link is a much lower barrier than installing a browser extension and thus could instrocuce people to a completely different youtube expierience. this doesnt need to be a high priority but i dont think it is an invalid feature suggestion.

**Comment by TheFrenchGhosty** [comment]
@elypter 
>there is still a benefit to have a dedicated implementation for people who cannot install browser addons

This is completely out of scope, and an addon already exist that works perfectly. No need to recreate something that already exist.

**Comment by mizzunet** [comment]
@ToughGuyKunio has SponsorBlock been removed? I cannot seem to find it? yewtu.be 
Mind to share screenshot?

**Comment by TheFrenchGhosty** [comment]
@mizzunet It's in the browser addons. Open its settings enable invidious support and set your instance.

**Comment by mizzunet** [comment]
> @mizzunet It's in the browser add-ons. Open its settings to enable invidious support and set your instance.

Oops, you were talking about browser extension, weren't you? I thought it's available in Invidious natively, I'm using Brave from phone, no extension support

**Comment by TheFrenchGhosty** [comment]
Yes, the addon is, and always will be the way to use Sponsorblock on Invidious, no need to recreate something that's already perfect.
