### ISSUE TITLE
social blade integration

### ISSUE THREAD

**Issue by xqk94524** [iv-org/invidious#152]
[https://socialblade.com/](url)

maybe will be interesting have a littel integration with social blade even if just a link
"See on Social Blade" like the "Watch video on YouTube" one

**Comment by omarroth** [comment]
Sounds good, does SocialBlade have a `video` page that Invidious should point to? All I see is a listing for videos as well as other information about the author.

**Comment by xqk94524** [comment]
social blade just have infos about channels, youtube has info about each video some time ago, I think 2010~2012, but was removed gradually, and totally with the new youtube design

http://tubularinsights.com/youtube-statistics-competition/ (June 20, 2010)

![image](https://user-images.githubusercontent.com/34273204/45093768-7021d700-b0e7-11e8-882c-615f4f79086d.png)

with this add-on https://addons.mozilla.org/pt-BR/firefox/addon/switch-for-youtube/
is possible to see some stats of some videos, after switch to previously design
(pt-br)
![image](https://user-images.githubusercontent.com/34273204/45093949-fdfdc200-b0e7-11e8-91b8-5ac2a365b6f4.png)
(pt-br)
![image](https://user-images.githubusercontent.com/34273204/45093996-166ddc80-b0e8-11e8-9ea2-f6603da273aa.png)

**Comment by xqk94524** [comment]
for short, Social Blade just show channels statistics

**Comment by omarroth** [comment]
Looks like YouTube still provides them. Using [this](https://stackoverflow.com/a/17236327) answer on SO, you can make a POST request to `https://www.youtube.com/insight_ajax?action_get_statistics_and_data=1&v=AAAAAAAAAAA` with body `session_token=SESSIONTOKEN`, which is very similar to how Invidious pulls comments, see [here](https://github.com/omarroth/invidious/blob/e6d2166bacf9398930020025e77ba6a2209d502e/src/invidious.cr#1818).

Example output: https://pastebin.com/H9TKuD9R

I'd be interested in providing this on the left side, similar to Genre, Views, etc.

**Comment by omarroth** [comment]
Would it make more sense to link on the `/channel` page since SocialBlade doesn't provide video info?

**Comment by xqk94524** [comment]
yes. that was my point

**Comment by xqk94524** [comment]
but I was seeing

> In order to best scale our tracking to meet the needs of millions that use Social Blade, we pull data from YouTube's public API. This means that we're getting the same information you see on public YouTube channel pages, we just work to examine that data across multiple days and aggregate it into a display format that is useful to you.

https://socialblade.com/youtube/help

these are the same public info from YouTube API, Social Blade just make information gathering, and process data.

**Comment by xqk94524** [comment]
I had suggested this because the information on the Invidious channel page are very poor in my view.
