### ISSUE TITLE
Auto-generated and Topic channels playlists are incomplete or empty

### ISSUE THREAD

**Issue by lekma** [iv-org/invidious#1530]
a few examples:

*  News:

    - https://invidious.snopyta.org/api/v1/channels/UCYfdidRxbB8Qhf0Nx7ioOYw/playlists
    - https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw/playlists

* Music:

    - https://invidious.snopyta.org/api/v1/channels/UC-9-kyTW8ZkZNDHQJ6FgpwQ/playlists
    - https://www.youtube.com/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ/playlists

* Live:

    - https://invidious.snopyta.org/api/v1/channels/UC4R8DWoMoI7CAwX8_LjQHig/playlists
    - https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig/playlists

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
