### ISSUE TITLE
Search return no result

### ISSUE THREAD

**Issue by vinyll** [iv-org/invidious#1547]
https://tube.connect.cafe/ works just fine displaying default videos and playing them.

However searching (ie: https://tube.connect.cafe/search?q=video) always returns no result.
Even after the system was updated to the latest and there's no specific log output.

Any tip where to search from here?

**Comment by TheFrenchGhosty** [comment]
Instance issue.

**Comment by vinyll** [comment]
Well yes, but I'm the maintainer of the instance…
I've been investigating on this for a while and I'm not sure how to solve this.
I guess I'll go for a full reinstall then…

**Comment by elypter** [comment]
i think instance issues should be allowed to be discussed here. the software itself links to this github, there is no proper place other than this and usually multiple instances are affected so discussing it in one place makes it easier to debug

**Comment by unixfox** [comment]
@vinyll a couple of possibles root cause:
- The ip of your server is blocked by google
- The disk space of your server is full

I got this observation based on the fact that your instance doesn't load any channel: https://tube.connect.cafe/channel/UCfwE_ODI1YTbdjkzuSi1Nag

I hope this help you find the bug.

**Comment by TheFrenchGhosty** [comment]
The instance has been moved to the broken section of the instance list.

An issue has been opened about a different issue: https://github.com/iv-org/documentation/issues/4

**Comment by TheFrenchGhosty** [comment]
@elypter 
> i think instance issues should be allowed to be discussed here. the software itself links to this github, there is no proper place other than this and usually multiple instances are affected so discussing it in one place makes it easier to debug

Reporting bug here is just more work for us, we can't fix an instance, and we especially can't do anything for instances that aren't maintained (this one obviously isn't, just look at how outdated it is).

To be clear: instances issues aren't our problem.

**Comment by vinyll** [comment]
That sounds fair enought. I do maintain this instance but I might have missed something.
I get this error when browsing some videos:

```
 Could not extract video info. Instance is likely blocked. 
```

I'll follow up at the mentioned ticket upgrading or eventually reinstalling if it persists.
Thanks for your support!

**Comment by nathgit** [comment]
I realize this is closed but I'm going to comment anyway. Obviously you can't "fix" an instance. However, if there is a problem with a specific instance, being able to post it here is a way to see if other people are having the same problem, meaning it's probably an instance issue, or if the poster is the only one with the issue. I see no better place to post something like that than here.
