### ISSUE TITLE
Wide mode

### ISSUE THREAD

**Issue by ChloeMackey** [iv-org/invidious#155]
Would it be possible to add a "wide mode" in settings so that the video hugs the left and right side of the browser window? I don't think it would be that hard to implement.

**Comment by ChloeMackey** [comment]
Also, when i tried to import my youtube subs, it didnt work :(, had to bring them all in manually. I tried it on firefox and safari.

**Comment by r-a-y** [comment]
Perhaps a duplicate of #33?

You can do this via CSS as a workaround.  See my comment here - https://github.com/omarroth/invidious/issues/33#issuecomment-418199482.

**Comment by omarroth** [comment]
@ChloeMackey I'd be interested in debugging the issue with subscriptions, if you'd like to open a new issue for that.

+1 for @r-a-y's uBlock filter. I think I'll probably spend more time on this once #34 is closed, which should only be blocking on videojs/http-streaming/issues#162.

**Comment by Fixer-007** [comment]
I'm watching it on 1280x1024 5:4 screen and window is too small for my taste, I would like wide view as well, r-a-y posted a workaround, that I've modified to work for my resolution, add this into your ublock origin rules:
```
invidio.us##.pure-u-md-20-24.pure-u-1:style(width:auto !important)
invidio.us##.player-dimensions.vjs-fluid:style(padding-top: 78vh !important)
invidio.us###player-container:style(padding-bottom: 78vh !important)
```

**Comment by Tharn** [comment]
I second that a 'perfect screen real estate' mode is needed. Perfect example being Iridium for Youtube. It makes the video able to fill the entire tab content (think windowed fullscreen). The default large mode is far too small for decent viewing, while switching into fullscreen is impractical.
