### ISSUE TITLE
Download Link doesn't Work.

### ISSUE THREAD

**Issue by r3mis** [iv-org/invidious#1550]
Hello Everyone. First time using Invidious.
Just noticed that the Download Button doesn't Work. It will just redirect you to a Blank Page. 
![image](https://user-images.githubusercontent.com/52204908/101410526-c7730b00-38df-11eb-8743-1dc7565dcd84.png)

Test this link: https://invidious.site/latest_version?download_widget=%7B%22id%22%3A%22AuHxbgikjGk%22%2C%22itag%22%3A%2218%22%2C%22title%22%3A%22What%2BHappens%2BWhen%2BYou%2BOrder%2BA%2B%252429%2BMini%2BLaptop%2BFrom%2BA%2BFacebook%2BAd%253F-AuHxbgikjGk.mp4%22%7D

This happens with EVERY video. You can still download it with the Right Click.
![image](https://user-images.githubusercontent.com/52204908/101410693-01441180-38e0-11eb-9a2f-bff66256188a.png)

**Comment by TheFrenchGhosty** [comment]
The white window isn't normal.

>You can still download it with the Right Click.

This is normal though.

**Comment by r3mis** [comment]
Thanks!

**Comment by TheFrenchGhosty** [comment]
Fixed in #1654
