### ISSUE TITLE
link shortener like youtu.be

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1553]
Are there any plans to create a url shortener for sharing links, as youtube does? https://www.youtube.com/watch?v=wprZkeULPSo becomes https://youtu.be/wprZkeULPSo. Many url shortener sites offer custom domains but I'm not aware of any that are free. If there is a better place to post this question feel free to let me know. I'm not aware of github pages for specific instances.

**Comment by TheFrenchGhosty** [comment]
There isn't really any point in that honestly (and I think https://URL.ext/ID is already supported)... but hey, why not I guess.

**Comment by nathgit** [comment]
@TheFrenchGhosty the URL.ext/ID does work. If you do want to use a url shortener, tny.im is a good free choice that can be used to shorten links without even visiting the site. Just prepend the invidious url with https://tny.im/ . For example tny.im/https://invidious.snopyta.org/wprZkeULPSo. It also has a bookmarklet that does the same thing. If you have an account you can keep a list of your shortened links which can be edited or deleted.

**Comment by nathgit** [comment]
[Yourls](http://yourls.org/) also lets you create your own url shortener.

**Comment by TheFrenchGhosty** [comment]
Those kind of link shortener services are mainly meant for analytic/statistic, something that obviously shouldn't be a thing in Invidious.

**Comment by Perflyst** [comment]
Looks like out of scope to me. `invidio.us/wprZkeULPSo` is the shortest url you can use, if you want it even shorter you need to host invidious or the redirect frontend on a shorter domain.

**Comment by TheFrenchGhosty** [comment]
Yes, indeed out of scope since https://URL.ext/ID is a thing.
