### ISSUE TITLE
Control bar broken on mobile

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1579]
With subtitles | Without subtitles
---- | -----
<img src="https://user-images.githubusercontent.com/58657617/102084058-db08ff00-3e14-11eb-8f54-068158dd4713.png" width="300"> | <img src="https://user-images.githubusercontent.com/58657617/102084065-dcd2c280-3e14-11eb-8317-82ba59826aa9.png" width="300">

Please always put fullscreen button on portrait mode on mobile, it's only available on landscape mode.

I think speed button should be ditched, then it would be

With subtitles | Without subtitles
---- | ----
subtitles ; video settings ; fullscreen | share ; video settings ; fullscreen

**Comment by TheFrenchGhosty** [comment]
Duplicates of: #912

Related: #1005

**Comment by TheFrenchGhosty** [comment]
Actually, let's use this issue.

**Comment by B0pol** [comment]
Also, time selection area is too short, I think -xx:xx time left should be removed, there is already xx:xx/xx:xx at the left

**Comment by Rjevski** [comment]
Can we use this opportunity to remove the share button? I don't see the point of it, especially on mobile where the browser has its own share feature.

**Comment by lucky13820** [comment]
Yes, please just ditch share button. It’s less useful, if we really need it, it should exist outside of the player.
