### ISSUE TITLE
[Bug] Playlists list continuation is broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1599]
Clicking on "Next page" on the playlists list of a channel will trigger a bug, because the continuation is broken.

Example:

https://invidious.snopyta.org/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/playlists

"Next page" continuation is ```?continuation=``` instead of an actual value:

https://invidious.snopyta.org/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/playlists?continuation=

**Comment by TheFrenchGhosty** [comment]
Updated example:

https://invidious.snopyta.org/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/playlists

https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/playlists

**Comment by greenfoo** [comment]
Is this bug still relevant?
I just checked with the latest version from `master` and the "Next" button works on PewDiePie's playlists without problems.
The API endpoint (`http://localhost:3000/api/v1/channels/playlists/UC-lHJZR3Gqxm24_Vd_AJ5Yw?continuation=...`) also seems to work ok.

**Comment by TheFrenchGhosty** [comment]
It is still relevant.

There's not next button here: https://invidious.snopyta.org/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/playlists

**Comment by greenfoo** [comment]
Snopyta is not using the latest commit from `master`:
![snopyta](https://user-images.githubusercontent.com/42691086/113520817-0bc49e00-9596-11eb-8a49-68a4972f9b2c.png)

I just tried with the latest `master` and the `Next` button is there:
![next](https://user-images.githubusercontent.com/42691086/113520832-1aab5080-9596-11eb-93a0-cfc33450662d.png)

It looks like the commit where this issue was fixed is c0997f951c9af58a844d6098398ce0a39e43d052

**Comment by TheFrenchGhosty** [comment]
mmh great then!

**Comment by SamantazFox** [comment]
It works on the few channels I tried, however, there is no "previous page" button.

**Comment by B0pol** [comment]
It is not broken anymore

**Comment by SamantazFox** [comment]
@B0pol filters don't work. For instance, both of these return the same thing:

- https://invidious.snopyta.org/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/playlists?sort_by=newest
- https://invidious.snopyta.org/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/playlists?sort_by=oldest

**Comment by B0pol** [comment]
But then open an issue for filters, and close this one about continuation

**Comment by SamantazFox** [comment]
Also, there is no "previous page" button
