### ISSUE TITLE
[Security Issue] videoplayback proxy is not restricted to youtube servers

### ISSUE THREAD

**Issue by tenpura-shrimp** [iv-org/invidious#1605]
## Issue
The videoplayback proxy is not restricted to youtube servers.  If any host is passed in as the query param to videoplayback, it will be honored.  This would result in the proxy hitting some other server besides the youtube server.  This is normally stuck at the /videoplayback path but because we follow redirects, it can end up proxying any arbitrary url in the end.

This can abused in ways including but not limited to:
1. An attacker can have the proxy hit a malicious server which sends data to invidious and causes a denial of service to invidious.
2. An attacker can have the proxy hit some innocent server, causing issues for that server.
3. An attacker can use the proxy to hit arbitrary urls, thereby effectively using invidious as an open proxy.

## Reproducing
1. go to the url http://localhost:3000/videoplayback?test=a&host=my.other.server.com
2. check the apache logs of the other server
   ```"HEAD /videoplayback?test=a HTTP/1.1" 404 3462 "-" "Crystal" ```

## Fix
I think we should implement a whitelist expression for the host server to restrict it to youtube servers.

**Comment by TheFrenchGhosty** [comment]
Is it possible to do it for proxi-ed videos?

(I guess by reading the configuration file?)

**Comment by jksladjflkjsadflkjsadf** [comment]
I'm not sure what you mean here.

**Comment by SuperSandro2000** [comment]
I can confirm that this does a GET request to the server under the host parameter with all other parameters. Example path like in the opening issue: ``/videoplayback?test=a``.

This means essentially all invidious instances are open proxies.

**Comment by FireMasterK** [comment]
I wouldn't consider this to be a huge issue considering that the path is forwarded, it's really hard to abuse this as a proxy server, and it only supports get requests.

However, it sure can be used to perform DDOS attacks, which makes it a mildly concerning issue.

**Comment by ckorder** [comment]
> can be used to perform DDOS attacks, which makes it a mildly concerning issue

i can only encourage you to use the following for nginx:
`limit_req_zone $binary_remote_addr zone=mylimit3:10m rate=10r/s;`
```
server {
bliblablub...
location / {
bliblablub...
limit_req zone=mylimit3 burst=20 nodelay;  }}
```

or use mod_evasive for apache2

`sudo apt install libapache2-mod-evasive`
`sudo nano /etc/apache2/mods-enabled/evasive.conf`

> DOSHashTableSize 3097
> DOSPageCount 2
> DOSSiteCount 50
> DOSPageInterval 1
> DOSSiteInterval 1
> DOSBlockingPeriod 10


`sudo systemctl reload apache2`

this prevents abuse

**Comment by Perflyst** [comment]
Next to googlevideo.com and youtube.com (apparently for HLS chunks) requests there are also requests to videoplayback which do not proxy anything (?)
`
/videoplayback?expire=1610482751&ei=36_9X9aMKpri4wKKyonYDg&ip=X.X.X.X&id=e1a19910551b8adf&itag=140&source=youtube&requiressl=yes&mh=NU&mm=31%2C26&mn=sn-5goeen7d%2Csn-i5h7lned&ms=au%2Conr&mv=m&mvi=1&pl=21&initcwndbps=807500&vprv=1&ratebypass=yes&mime=audio%2Fmp4&otfp=1&gir=yes&clen=30653811&lmt=1610456672810427&dur=1894.051&mt=1610460992&fvip=1&keepalive=yes&beids=9466588&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cratebypass%2Cmime%2Cotfp%2Cgir%2Cclen%2Clmt%2Cdur&sig=AOq0QJ8wRgIhANbfvXGpXmHHV5r1D0Eu00DY4qaN5cv2PNJHfisjojv5AiEAvc3Eh3ba_u8MWx4wpHpmOwm6Zkl97aS7ygnps6144Yw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgMdUrDWT8dkPxCgQNsBggOAvBB6Qp8Mvnko13Srsy-XECIQD-QYYmTaBrANYf7gBKBa4rpS2_5nrjOFoEgTqu3ybBVg%3D%3D&cmo=sensitive_content%3Dyes&range=30056351-30217980
`

**Comment by tenpura-shrimp** [comment]
> Next to googlevideo.com and youtube.com (apparently for HLS chunks) requests there are also requests to videoplayback which do not proxy anything (?)

I believe that #1658  should have changed that

**Comment by unixfox** [comment]
What's the best protection to implement in the code against that?

Using a regex for whitelisting all the subdomains of youtube.com and googlevideo.com? But what if new YouTube introduce new domains for serving the video?

Or having a key that set a unique token related to the request and only the server know how to generate the token? That's an idea taken from morty with its "Optional HMAC URL verifier key to prevent service abuse": https://github.com/asciimoo/morty

**Comment by TheFrenchGhosty** [comment]
@tenpura-shrimp Sorry I completely forgot to come back to explain my (badly written) comment:

Basically if we restrict the videoplayback to youtube server what will happen to proxied/dash video that are served by the instance itself? As I said "I guess by reading the configuration file?" That include the instance URL?

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by TheFrenchGhosty** [comment]
@tenpura-shrimp I would like to thank you a lot for reporting this MAJOR problem!

For reporting this (massive) security issue I and most of the organization members would like to reward you with 20$ (in BTC) If you want to receive your reward feel free to send me your BTC address or post it directly in the PR.

Every payment will be, as usual, reflected in the [transparency repository](https://github.com/iv-org/transparency), in our monthly financial reports.

**Comment by TheFrenchGhosty** [comment]
Ping @tenpura-shrimp

**Comment by TheFrenchGhosty** [comment]
Ping @tenpura-shrimp

**Comment by TheFrenchGhosty** [comment]
After multiples pings on GitHub, and a message on Matrix without reponse, this reward is considered refused.
