### ISSUE TITLE
googlevideo.com issues with HTTPS redirect in firefox

### ISSUE THREAD

**Issue by T4eus** [iv-org/invidious#161]
I saw there was a problem with ublock origin blocking pre-fetching

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-pre-fetching
https://en.wikipedia.org/wiki/Link_prefetching

If I uncheck "Disable pre-fetching" at ublock origin, whorks fine, with this checked (what is the default), invidio.us didn't work properly 

This just occurs at firefox, chrome doesn't have this issue, at least in my testes

this maybe related to #160  and #151

**Comment by T4eus** [comment]
I don't have any idea, why this occur, and even less how to fix this

note:

> On Chromium 51 and above (including browsers based on Chromium 51 and above), this setting does not block DNS lookups and preconnections.

maybe this explain why this not affect chrome, but I looked on the code and don't saw those things

**Comment by T4eus** [comment]
at Ublock Origin sub-reddit

https://www.reddit.com/r/uBlockOrigin/comments/9fvc28/question_invidious_isnt_working_with_disable/

**Comment by T4eus** [comment]
instance of uncheck "Disable pre-fetching", I can just use this rule
`||invidio.us/js/video.min.js$script,first-party`

**Comment by T4eus** [comment]
having the same problem again

**Comment by omarroth** [comment]
I think I'm going to close this in favor of #160, as it appears to be a duplicate and there is more information available there. 

As a workaround until #160 is closed, try disabling Fanboy's Social Blocking and Fanboy's Annoyance List. If that does not fix it, feel free to reopen this. If, after #160 is closed, you are still encountering this issue, again feel free to reopen.

**Comment by omarroth** [comment]
My mistake. If the workaround mentioned above resolves the issue, I'll close this in favor #160, until then I'd like to keep this issue open.

**Comment by T4eus** [comment]
I think is a problem related to latency, the player may not see the video URL in time, and show a error messenger.

UBO maybe just make firefox less tolerant with the latency for prevent pre-fetch.

is this what I think, because when I get error and look to the source code, the video is there, and when reopen on another tab the video plays.

**Comment by T4eus** [comment]
I think, I finally realize whats occuring at all.

This isn't related to UBO (but may this interfere in some way because in my tests looks that when using UBO have more chances to this occur).

Using [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) I noted that when I get the connection to googlevideo.com this is primary made using HTTP, and later redirected to HTTPS.

I also noted that googlevideo.com dosen't works without a HTTPS connection.

Well, I imagine invidio.us made connections using HTTP and the browser redirects to HTTPS, but sometimes this don't occurs in time for the player, and get the error.

Sometimes interations like open the video on other tab makes the video works (disable prefetch on UBO maybe have this effect, because this was why I proposed this relation).

This is also why I don't have problems with the firefox default player, this player wait the HTTP-to-HTTPS redirect.

As a temporary fix (and as a way to test) I'm using [HTTPS everywhere](https://www.eff.org/https-everywhere).

May this occurs to me, because the execive latency I have with invdios (200ms).

**Comment by T4eus** [comment]
![image](https://user-images.githubusercontent.com/43221359/45919589-ab513380-be65-11e8-94c1-2cba4b9b2b3d.png)

**Comment by omarroth** [comment]
That's interesting. As far as I know Invidious uses HTTPS for all resources it serves. What happens if you try to access video link directly? You can append `&raw=1` to the watch URL to redirect.

**Comment by T4eus** [comment]
> 
> 
> That's interesting. As far as I know Invidious uses HTTPS for all resources it serves. What happens if you try to access video link directly? You can append `&raw=1` to the watch URL to redirect.

works fine, but I undertand why

**Comment by T4eus** [comment]
looks this:
1. invidio.us send my a link like this, https://r6---sn-ab5szn7k.googlevideo.com/
2. who redirect me to this, https://r2---sn-cg51pauxax-28ie.googlevideo.com/
3. and finally this, https://r6---sn-bg0e7n7r.googlevideo.com/

all diferrent URL, this may because invidio.us generate a link based on american region, but I'm outside america.

googlevideos take me to a closer server, and the player can't follow this.
