### ISSUE TITLE
URL parameters don't work

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#1610]
Example: https://invidious.snopyta.org/watch?v=jNQXAC9IVRw&dark_mode=true&autoplay=true
Dark mode doesn't kick in and video doesn't autoplay. Other instances seem to be affected as well.

**Comment by GauthierPLM** [comment]
dark_mode works as expected, and autoplay works if the browser allows autoplay (depends on user settings).
In Firefox, you can check if autoplay is enabled from the URL bar, in the permission pop-up.

**Comment by SamantazFox** [comment]
The parameters are bulky and incoherent (for instance, `dark_mode` works everywhere, but some others parameters don't work at all or aren inconsitent over pages.

@GauthierPLM See here for all the other issues related to that problem: https://github.com/orgs/iv-org/projects/1#column-14721774

**Comment by SamantazFox** [comment]
Works as expected
