### ISSUE TITLE
Community - Channel name not shown

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1612]
#1611 happens on most of channels, so here is one to test: 
https://invidio.us/channel/UCAcAnMF0OrCtUep3Y4M-ZPw/community

**Comment by B0pol** [comment]
still relevant and applicable

**Comment by AHOHNMYC** [comment]
Bug is somewhere around this line:
https://github.com/iv-org/invidious/blob/4c1a5f84fa3310a2d2d6752d4bc8d42580c9baa0/src/invidious/comments.cr#L347
