### ISSUE TITLE
Invidious still contain mention of omarroth in a lot of places

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1621]
Invidious, obviously, will always be a project that exist because of Omarroth. 

However, Invidious should be updated to reflect his departure.

I noticed *some* places where either the old Github URL appears, his nickname, or his email address (example: https://github.com/iv-org/invidious/blob/master/src/invidious/users.cr#L430 )

This should be updated to mention the new Github URL, "invidious" instead of his nickname, the Github URL instead of his email address.

**Comment by hackerncoder** [comment]
I have started on this. There are a few FIXMEs and one where I am not sure if I should remove him. I have also not touched src/invidious/comments.cr line 245, and CHANGELOG.md.

https://github.com/hackerncoder/invidious/commit/4d512d908dfaf9b726602c77bcf555d36445f88f

**Comment by saltycrys** [comment]
The changelog shouldn't be changed retroactively, but we should add a note at the top to indicate that it isn't being updated anymore.

**Comment by hackerncoder** [comment]
I was more talking about the fact that it points to omarroths (non-existent) invidious repo. Anyways I have added a note at the top and added your suggestions.

**Comment by hackerncoder** [comment]
I did a grep for just Omar (for some reason I didn't last time), and there are still remaining mentions of him:
In the src/invidious.cr file at the top, it says "Copyright (C) 2019  Omar Roth".
In the src/invidious/views/template.ecr the "Released under the AGPLv3 by Omar Roth", and all locales as a translation of that.

Should I change any of it?

**Comment by TheFrenchGhosty** [comment]
@hackerncoder Good question, I guess it should be replaced by "Copyright (C) 2021 Invidious team"
