### ISSUE TITLE
[Discussion] Re-branding Invidious

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1626]
I've been thinking of re-branding Invidious to something else, Perflyst don't like it, but we decided to ask you guys for your opinion.

Basically the issue is that "Invidious" isn't really self-explaining, the words itself means "likely to cause unhappiness or be unpleasant, especially because it is unfair" so this isn't completely unrelated but unlike PeerTube, Nitter, Bibliogram, SearX it isn't self-explaining... and also: https://github.com/invidious is taken (so we're stuck with iv-org), and since we need a new domain (to replace invidio.us) we can't get .org, because it's taken (and currently sold for $1,300).

**Comment by nathgit** [comment]
Maybe something like "Vidaro"? It's easy to pronounce, the "vid" part gives you a clue what the site is, & if they happen to speak Esperanto they know it means "a group of videos".

**Comment by orbitneons** [comment]
How about fronttube! https://github.com/fronttube is available too.

**Comment by btdmaster** [comment]
For (some) reverse compatibility, does this give any ideas? Though I personally lean towards Perflyst here.
![image](https://user-images.githubusercontent.com/59375667/103456800-734a2380-4cf1-11eb-8b34-da6bfd385d8e.png)

**Comment by TheFrenchGhosty** [comment]
After discussing it, Invidious won't be re-branded.

**Comment by RandomErrorMessage** [comment]
Even though this issue is already closed, I agree with not rebranding it. I don't see anything wrong with the name (I even kinda like it), people who already use invidious know what invidious is.
