### ISSUE TITLE
Exponential retry growth bug in comments retry

### ISSUE THREAD

**Issue by tenpura-shrimp** [iv-org/invidious#1638]
Hi,

I saw that the comments endpoint was getting spammed on my instance.

I investigated this and found bug where the comments retry function causes exponentially increasing requests
https://github.com/iv-org/invidious/blob/master/assets/js/watch.js#L349

This is using setInterval, which calls the inside function repeatedly on the time interval.  So, we will call the next function once a second.  Assuming those are failing too, then each of those will start calling at one per second.  This leads to an exponential growth in repeated calls to the comments endpoint

It looks like we should have used setTimeout for all these cases in the js.

**Comment by jksladjflkjsadflkjsadf** [comment]
For an instance, this will pretty much automatically get ip banned by google.
