### ISSUE TITLE
status.invidio.us

### ISSUE THREAD

**Issue by Discookie** [iv-org/invidious#164]
I guess with transitioning to a container (such as #162), more advanced monitoring tools should be made available. (for [invidio.us](invidio.us) this could be [status.invidio.us](status.invidio.us))

You could send more metrics such as "Youtube updates in the last hour", "Channels in queue" or "Error rate", as well as a general uptime data.

It would also help separate deployment-related issues from project-related issues.

There's many good status pages out there such as [Cachet](https://cachethq.io/) or [Staytus](https://staytus.co/).

**Comment by omarroth** [comment]
That's interesting. I'm taking a look at them now, do either of them expose an API that could be updated with the metrics suggested? I'd also like to be able to integrate metrics which my host provides (DigitalOcean), so it would be possible to see number of 500, 200 response per second, etc.

If anyone knows of any other status pages out there as well, feel free to share them here.

**Comment by TylerHobanDotCom** [comment]
@omarroth consider https://www.statuspage.io/

**Comment by Discookie** [comment]
Here's their demo pages:
Statuspage: https://reddit.statuspage.io/
Cachet: https://demo.cachethq.io/
Staytus: https://demo.staytus.co/

Here are the API docs for metrics (and for anything else too):
Statuspage: https://doers.statuspage.io/api/v1/metrics
Cachet; https://docs.cachethq.io/v1.0/reference#get-metrics
Staytus:

**Comment by TylerHobanDotCom** [comment]
Cachet is cool but requires selfhosting, which may not be the best option for a status page.

**Comment by omarroth** [comment]
I'm currently looking into making metrics from DigitalOcean available for displaying in a similar format to https://reddit.statuspage.io/#week. Unfortunately there doesn't appear to be any documentation  (that I can find) on how to do this. I'm still looking into it though and it should be possible.

At this point Cachet and Statuspage are the two services I'm considering. I agree that self-hosting may be a problem for a status page, but I would prefer FOSS where possible. Unfortunately I haven't had much time to look more into this more.

There was some discussion in #356 about providing some info that could be used for a status page. Maybe `/api/v1/stats` could provide additional metrics that might be useful here, such as a "latest channel refreshed at" or a similar field that might indicate a problem with updating subscriptions.

**Comment by omarroth** [comment]
Added `lastChannelRefreshedAt` to `/api/v1/stats` with f0cc7a925c3e936c30b5b4781ff27c9f03a34071.

**Comment by omarroth** [comment]
@Perflyst has very kindly set up a monitor with http://uptimerobot.com, you can view it [here](https://uptime.invidio.us).
