### ISSUE TITLE
duplicate playlists when I export data...?

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1643]
If I export data from one instance to another, it results in duplicate playlists. Is it possible to automatically overwrite/iupdate existing playlists instead of simply creating duplicate playlists that have to be deleted?

**Comment by saltycrys** [comment]
Yes, here's the code that needs to be changed: https://github.com/iv-org/invidious/blob/168376b04671c6e362468267a3b07dd332b40702/src/invidious.cr#L711-L755

**Comment by nathgit** [comment]
I don't know how to code. I'm just a user (mostly the snopyta instance), but maybe somebody on the team could change the code?
