### ISSUE TITLE
Fix --release builds in docker

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1652]
Building with the --release option results in the following error:
```
Step 9/23 : RUN crystal build ./src/invidious.cr     --release --static --warnings all     --link-flags "-lxml2 -llzma"
 ---> Running in 916b8da23935
Invalid memory access (signal 11) at address 0x7f465560af88
[0x7f467c282f96] ???
[0x7f467c1ccbeb] ???
[0x7f467d050831] ???

**Comment by Perflyst** [comment]
It was removed because of https://github.com/iv-org/invidious/issues/917

**Comment by unixfox** [comment]
It can be closed I guess then if `--release` still doesn't work.

**Comment by Perflyst** [comment]
Instead of closing I updated this issue to track the issue that `--release` is broken.

**Comment by FireMasterK** [comment]
It makes sense to fix `--release`. It would fix the `signal 11` crashes, as well as allow for `--release` builds.

**Comment by TheFrenchGhosty** [comment]
Is there any actual point in having a --release build? What does this provide that's not already done with a "normal" build?

**Comment by gripped** [comment]
From https://crystal-lang.org/reference/using_the_compiler/index.html
> Release builds¶
By default, the generated executables are not fully optimized. The --release flag can be used to enable optimizations.
$ crystal build hello_world.cr --release
Compiling without release mode is much faster and the resulting binaries still offer pretty good performance.
Building in release mode should be used for production-ready executables and when performing benchmarks. For simple development builds, there is usually no reason to do so.

I've built the 'release' build several times over the last few hours with no errors. Whether there truly are any benefits I have no clue, but the quoted page suggests there are.

**Comment by TheFrenchGhosty** [comment]
Alright, thanks.

I'm changing the priority then.

**Comment by GauthierPLM** [comment]
I confirm I have no issue to build invidious in release mode using `crystal build src/invidious.cr --release -o invidious-release` based on master c2f7487 and using crystal 0.36.0.

**Comment by SamantazFox** [comment]
@TheFrenchGhosty That can be closed, I guess. I always build from master with --release, which goes nicely since we passed to crystal 0.36.0

**Comment by FireMasterK** [comment]
In that case, the Dockerfile should be updated.

Also, LTO optimizations could be enabled to further improve performance.

**Comment by unixfox** [comment]
> @TheFrenchGhosty That can be closed, I guess. I always build from master with --release, which goes nicely since we passed to crystal 0.36.0

Not before invidious has been thoroughly tested on big instances.

**Comment by unixfox** [comment]
`--release` is just broken for the Docker image, I think we should just stop using alpine or use glibc in alpine with a project like this: https://github.com/sgerrand/alpine-pkg-glibc because musl is probably the issue of those `Invalid memory access` errors.

**Comment by FireMasterK** [comment]
Another solution is to use a slim Debian container.

https://github.com/crystal-lang/crystal/issues/8732 MUSL is a Tier 2 platform according to this.

**Comment by SamantazFox** [comment]
> I think we should just stop using alpine or use glibc in alpine with a project like this: https://github.com/sgerrand/alpine-pkg-glibc

PSA: Using GlibC on Alpine is a dangerous footgun. It can lead to vritical system instabilities.
See: https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/
