### ISSUE TITLE
Dash video

### ISSUE THREAD

**Issue by RouterCFW** [iv-org/invidious#1665]
Hi when I use the dash video option is always buffers at 10 seconds on the video is there anything you could do to fix it ?

**Comment by unixfox** [comment]
Which Invidious instance are you using?

**Comment by RouterCFW** [comment]
> Which Invidious instance are you using?

All of them do the same thing for me

**Comment by TheFrenchGhosty** [comment]
@RouterCFW The issue is on your end.

**Comment by unixfox** [comment]
> > Which Invidious instance are you using?
> 
> All of them do the same thing for me

Are you using Google chrome or chromium or a clone like brave, opera or edge?

Maybe this issue is a duplicate of https://github.com/iv-org/invidious/issues/1630

**Comment by RouterCFW** [comment]
I’m on iOS using safari
