### ISSUE TITLE
Download video button

### ISSUE THREAD

**Issue by ckorder** [iv-org/invidious#1666]
>  Make download disabled by default > No more bandwidth speed waste on instances that aren't configured completely

Relating towards: https://github.com/iv-org/invidious/issues/1563

I quickly searched within src/invidious/views/watch.ecr
` <% if CONFIG.dmca_content.includes?(video.id) || CONFIG.disabled?("downloads") %>
                <p id="download"><%= translate(locale, "Download is disabled.") %></p>
            <% else %>`

Can we "improve" the download button by just offering the mp3 / mp4 stream as one click download option forwarding to the googlevideo servers? 

`<a target="_blank" rel="noopener noreferrer" href="https://r4---sn-awdynez.googlevideo.com/videoplayback?expire=16106...">Download</a>`

Advantage: No instance server resources are used, no DMCA headaches and downloads are working.

**Comment by TheFrenchGhosty** [comment]
*Maybe*.

Please comment on the meta issue.
