### ISSUE TITLE
[Bug] Unexpected char '<' at 1:1 (JSON::ParseException) - On videos

### ISSUE THREAD

**Issue by M86xKC** [iv-org/invidious#1673]
When trying to open a video it give the following error, it is worth noting that this only happens on certain videos ([this is one of them](https://youtube.com/watch?v=VQOdmckqNro)):

steps to reproduce:
open: `https://<instance name>/watch?v=VQOdmckqNro`
observe the resulted exception

```
Title: `Unterminated string at 1:34677 (JSON::ParseException)`
Date: `2021-01-16T19:14:42Z`
Route: `/watch?v=VQOdmckqNro`
Version: `2021.01.03-28dac81 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
Unterminated string at 1:34677 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer/string_based.cr:63:8 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:107:11 in 'extract_polymer_config'
  from src/invidious/videos.cr:965:10 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
</p>
</details>

```

**Comment by M86xKC** [comment]
amusingly different instances behave differently, here is a list of all public instances with their behaviour and the version/commit they're based on:

Instance | Version | Behaviour
----------|----------|----------
[invidious.snopyta.org](https://invidious.snopyta.org/watch?v=VQOdmckqNro) | 2021.01.12- cc3f019 | Error: Unterminated string at 1:34450 (JSON::ParseException)
[invidious.fdn.fr](https://invidious.fdn.fr/watch?v=VQOdmckqNro) | 0.20.1-29e85d7 | Works as expected
[invidious.kavin.rocks](https://invidious.kavin.rocks/watch?v=VQOdmckqNro) | 2021.01.13- c7e65ce | Error: Unterminated string at 1:35368 (JSON::ParseException)
[invidious.zapashcanon.fr](https://invidious.zapashcanon.fr/watch?v=VQOdmckqNro) | 2021.01.12- cc3f019 | Error: Unterminated string at 1:34738 (JSON::ParseException)
[yewtu.be](https://yewtu.be/watch?v=VQOdmckqNro) | c7e65ce | Works as expected
[invidious.048596.xyz](https://invidious.048596.xyz/watch?v=VQOdmckqNro) | 2021.01.12- cc3f019 | Error: Unterminated string at 1:34450 (JSON::ParseException)
[invidiou.site](https://invidiou.site/watch?v=VQOdmckqNro) | c98c7d4 | Works as expected
[invidious.tube](https://invidious.tube/watch?v=VQOdmckqNro) | 2021.01.03- 28dac81 | Error: Unterminated string at 1:34677 (JSON::ParseException)

\* some instances were excluded because they were down or were blocked

**Comment by TheFrenchGhosty** [comment]
@M86xKC Thanks for the testing, it looks like outdated instances are working, and updated one aren't (it definitely doesn't work on the latest commit), I guess a recent change broke them.

**Comment by saltycrys** [comment]
The problem is the interaction of this regexp https://github.com/iv-org/invidious/blob/c7e65ce795df7858ed1cdb161e3c40165f80e0ac/src/invidious/videos.cr#L820 with the video description. The description contains `};` so the JSON gets cut off.
One possible solution would be to find the surrounding `<script>` tags first and then do a non-greedy match.

**Comment by TheFrenchGhosty** [comment]
Supersede #783

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by SamantazFox** [comment]
Mmmh, yep, I got that here too with OP's first video.

Title: `Unterminated string at line 1, column 55222 (JSON::ParseException)`
Date: `2021-03-29T18:54:11Z`
Route: `/watch?v=VQOdmckqNro`
Version: `2021.03.28-2c1cf42 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unterminated string at line 1, column 55222 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from /usr/share/crystal/src/json/lexer/string_based.cr:63:8 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:107:11 in 'extract_polymer_config'
  from /root/invidious/src/invidious/videos.cr:966:10 in 'get_video:region'
  from /root/invidious/src/invidious/routes/watch.cr:61:15 in 'handle'
  from /root/invidious/lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /root/invidious/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /root/invidious/src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /root/invidious/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment]
Does anyone have any other links that can consistently reproduce this error? I think I've fixed it but this link is the only sample I have to test with.
