### ISSUE TITLE
Use environment variables for configuration

### ISSUE THREAD

**Issue by Rjevski** [iv-org/invidious#1677]
I would prefer if Invidious used environment variables for config natively, to make it easier for Docker-based deploys as well as for PaaS platforms such as Heroku/Dokku. At the moment I am using the following workaround as a start script:

```bash
#!/usr/bin/env sh

export INVIDIOUS_CONFIG="
channel_threads: ${CHANNEL_THREADS:-1}
feed_threads: ${FEED_THREADS:-1}
db_url: $DATABASE_URL
full_refresh: ${FULL_REFRESH:-false}
https_only: ${HTTPS_ONLY:-false}
domain: $DOMAIN
hmac_key: $HMAC_KEY
use_pubsub_feeds: ${USE_PUBSUB_FEEDS:-false}
login_enabled: ${LOGIN_ENABLED:-false}
registration_enabled: ${REGISTRATION_ENABLED:-false}
statistics_enabled: ${STATISTICS_ENABLED:-false}
external_port: ${EXTERNAL_PORT:-443}
default_user_preferences:
  autoplay: ${DEFAULT_USER_PREFS_AUTOPLAY:-false}
  continue: ${DEFAULT_USER_PREFS_CONTINUE:-false}
  player_style: ${DEFAULT_USER_PREFS_PLAYER_STYLE:-invidious}
  local: ${DEFAULT_USER_PREFS_LOCAL:-true}
  default_home: ${DEFAULT_USER_PREFS_DEFAULT_HOME:-Trending}
  feed_menu: ${DEFAULT_USER_PREFS_FEED_MENU:-[\"Trending\"]}
  quality: ${DEFAULT_USER_PREFS_QUALITY:-dash}
"

exec ./invidious
```

I think it would be better if Invidious read those environment variables natively, and if there is still a need for a `config.yml` then a helper (either in Crystal or in shell) script could be provided that would do the reverse of the above - read the YAML file, populate the environment variables and then call the Invidious binary.

Related: https://github.com/iv-org/invidious/pull/1676

**Comment by TheFrenchGhosty** [comment]
From what I know it's already a thing, see: https://github.com/iv-org/invidious/blob/master/docker-compose.yml#L25

**Comment by Rjevski** [comment]
Yeah that's what I'm using now. I don't think it's good enough though - it requires you to format a YAML file at runtime. Ideally each setting would be its own environment variable.

**Comment by unixfox** [comment]
Very good idea. Config files are difficult to deal with in the container ecosystem.
