### ISSUE TITLE
There is too many duplicates

### ISSUE THREAD

**Issue by hackerncoder** [iv-org/invidious#1684]
The new error page, while great and gives us a lot of information, also produces too many duplicate issues. We should find a way to lower that number, e.g. add some text about checking for duplicates, maybe (also) here on github.

~HackerNCoder.

**Comment by Perflyst** [comment]
A link to the github issue tracker with the correct search terms would be nice. It would automatically show the end user if a bug with the same error already exists.

**Comment by hackerncoder** [comment]
Searching for the title should reveal if any has already been opened or a closed issue with the duplicate tag.

**Comment by saltycrys** [comment]
Somebody suggested to add a button to copy the issue template which would help with formatting.

It's possible to get the file and line that caused the error by matching `src/invidious` on backtrace frames. This would help with common errors that can be caused in multiple files, like JSON parsing or accessing. The suggested title should include this information. See https://github.com/crystal-lang/crystal/blob/5999ae29beacf4cfd54e232ca83c1a46b79f26a5/src/exception.cr#L59

<hr>

The error message is created here: https://github.com/iv-org/invidious/blob/d8629e61d615e2c0c7fc4d4ee1d88324170b2cb8/src/invidious/helpers/errors.cr#L25-L44 and is rendered with this template: https://github.com/iv-org/invidious/blob/d8629e61d615e2c0c7fc4d4ee1d88324170b2cb8/src/invidious/views/error.ecr#L1-L7

When editing the template keep in mind that expected errors (`InfoException`s) get rendered with the error template, too.

**Comment by hackerncoder** [comment]
The issue template is a good idea, but it might not be done correctly. People are still opening the issue, but also not providing a title. I might take a look at creating something I think is better.

**Comment by unixfox** [comment]
Was solved a while ago thanks to https://github.com/iv-org/close-potential-duplicates
