### ISSUE TITLE
Expose version by default on api/v1/stats

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#1690]
The version is public of the invidious instance is public in the footer anyways and for the instance list it would be nice if every instance shows its version

**Comment by FireMasterK** [comment]
We have to think about the impact for private instances too, which are a lot more in number.

**Comment by Perflyst** [comment]
Which impact?

**Comment by SamantazFox** [comment]
You mean that `statistics_enabled` wouldn't affect the display of `"software":{...}` on `/api/v1/stats` ?

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
