### ISSUE TITLE
HQ Thumbnails

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#170]
Please consider to replace `mqdefault.jpg` thumbnails on the subscribions page with `hqdefault.jpg` ones. For example:
* https://www.invidio.us/vi/YE7VzlLtp-4/mqdefault.jpg
* https://www.invidio.us/vi/YE7VzlLtp-4/hqdefault.jpg

**Comment by omarroth** [comment]
I think my only concern with this would be bandwidth. Also, for users that have `maxresults` set higher in their preferences, loading the feed could take quite a bit longer (if it doesn't crash).

Although, when taking a look at the thumbnails there doesn't appear to be much size difference (~16 KB vs ~11 KB), so I will absolutely consider it.

**Comment by dimqua** [comment]
Are you concerned about your server bandwidth usage or about users with limited bandwidth (such as mobile internet users) or both?

**Comment by omarroth** [comment]
Mostly concerned about users with limited bandwidth (of which I would probably include myself).  Server bandwidth usage has actually been surprisingly good, so I'm not as worried about that.

**Comment by dimqua** [comment]
In this case, you can add an option to use hq thumbnails (at least on desktop). I prefer `maxresdefault` personally, since even `hqdefault` has these ugly visible artifacts.

**Comment by omarroth** [comment]
That's fair enough. Would it make sense then for a `Use high-res thumbnails` to be used site-wide?

**Comment by dimqua** [comment]
To use `maxres.jpg` for all thumbnails? Yes. But what will be used with deactivated preference? I guess `hqdefault.jpg` can be a good candidate.
