### ISSUE TITLE
Captions without any Captions

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1707]
Yes, it's a strange thing and seems to affect the two instances I've tested.
https://invidious.kavin.rocks/api/v1/captions/w3j3tivcm50?label=English%20(auto-generated)&hl=en-US
https://invidious.snopyta.org/api/v1/captions/w3j3tivcm50?label=English%20(auto-generated)&hl=en-US

On YouTube, the captions work as expected: https://www.youtube.com/watch?v=w3j3tivcm50

This is not related to #1703 as that contains an error and this doesn't.

**Comment by tenpura-shrimp** [comment]
This seems different, but it's actually the same.  While regular captions are proxied directly through the invidious, the auto generated captions need to be processed to work.  This regenerating the vtt file means that even if the yt server returns garbage, you will get an empty but valid vtt as the output.

https://github.com/iv-org/invidious/blob/master/src/invidious.cr#L1984
