### ISSUE TITLE
360 video support

### ISSUE THREAD

**Issue by Discookie** [iv-org/invidious#172]
I know the quality of 360 videos is terrible unless it's at least 1080p, but later down the line something should be done about 360 videos.

Here's one: https://www.youtube.com/watch?v=YP0Q-cBPjSE

I don't know if [videojs/videojs-vr](https://github.com/videojs/videojs-vr) has support for 'pancake' devices, but if not, [yanwsh/videojs-panorama](https://github.com/yanwsh/videojs-panorama) seems like another good candidate.

**Comment by elypter** [comment]
same with stereoscopic videos. both combined are vr videos. so going for vr should cover both topics,

**Comment by omarroth** [comment]
There's [videojs-vr](https://github.com/videojs/videojs-vr), although I think that should probably be opt-in :)

**Comment by elypter** [comment]
i dont think this should be forgotten

**Comment by petterreinholdtsen** [comment]
In case it is helpful, https://invidious.kavin.rocks/watch?v=HcRW3FMuttY is another 360 / 3D video example.
