### ISSUE TITLE
403 on subscriptions

### ISSUE THREAD

**Issue by 138138138** [iv-org/invidious#1728]
When running on my own instance with docker I got 
403 GET /api/v1/auth/subscriptions?fields=authorId
when I load the subscription page.

`postgres_1   | 
postgres_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1   | 
postgres_1   | 2021-01-30 16:22:19.124 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1   | 2021-01-30 16:22:19.125 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1   | 2021-01-30 16:22:19.134 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1   | 2021-01-30 16:22:19.158 UTC [25] LOG:  database system was shut down at 2021-01-30 16:22:17 UTC
postgres_1   | 2021-01-30 16:22:19.166 UTC [1] LOG:  database system is ready to accept connections
invidious_1  | [development] Kemal is ready to lead at http://0.0.0.0:3000
invidious_1  | 2021-01-30 16:25:04 UTC [info] 302 GET / 3.08ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 200 GET /feed/subscriptions 16.38ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 97.85ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 103.81ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.66ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 87.06ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 72.24ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 57.33ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 65.65ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 14.95ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.91ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 15.49ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 46.78ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 48.03ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 16.22ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.75ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.86ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 18.69ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 15.11ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.74ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.88ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 16.28ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 18.13ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.53ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 19.36ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 15.79ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 15.92ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.12ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 16.07ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.6ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.02ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 18.16ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 15.63ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 16.62ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.7ms
invidious_1  | 2021-01-30 16:25:04 UTC [info] 304 GET /vi/XXX/mqdefault.jpg 17.65ms
invidious_1  | 2021-01-30 16:25:05 UTC [info] 403 GET /api/v1/auth/subscriptions?fields=authorId 692.62µs
invidious_1  | 2021-01-30 16:30:50 UTC [info] 403 GET /api/v1/auth/subscriptions?fields=authorId 671.72µs`

**Comment by TheFrenchGhosty** [comment]
"PostgreSQL Database directory appears to contain a database"
