### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ssbrawler** [iv-org/invidious#1731]
Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-01-31T01:52:56Z`
Route: `/channel/UC160PtNX6uGWLsOOCraDLzw`
Version: `2021.01.30-f1d7644 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment]
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.
