### ISSUE TITLE
https://www.youtube.com/watch/videoid support

### ISSUE THREAD

**Issue by rezad1393** [iv-org/invidious#1736]
can this be added to the support?
like this?
https://invidious.kavin.rocks/watch/ZvWn5xBflUs

**Comment by B0pol** [comment]
There is also youtube.com/v/videoId https://github.com/TeamNewPipe/NewPipeExtractor/issues/534

**Comment by B0pol** [comment]
There is also youtube.com/w/videoId https://github.com/TeamNewPipe/NewPipe/issues/4283

**Comment by B0pol** [comment]
And /shorts/

**Comment by B0pol** [comment]
and /e/ https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L382

**Comment by syeopite** [comment]
> And /shorts/
Isn't shorts another Youtube feature separate from normal videos though?

**Comment by B0pol** [comment]
It's just short videos (less than one minute) with #shorts in description / title and works like regular videos. It may have a special tab in youtube app in countries where you can create shorts in-app but it doesn't matter
