### ISSUE TITLE
Search video function not working

### ISSUE THREAD

**Issue by aaaaa1234554321** [iv-org/invidious#1740]
If I try to search a video, then nothing shows up. This is on invidious.snopyta.org 
![Screenshot 2021-02-02 at 8 01 44 PM](https://user-images.githubusercontent.com/78455202/106682941-8f134480-6591-11eb-8bcf-c23c7ad6e72e.png)

**Comment by hackerncoder** [comment]
This seems to be a issue with the instance and therefore we cannot do anything about it.

**Comment by aaaaa1234554321** [comment]
> This seems to be a issue with the instance and therefore we cannot do anything about it.

how do i fix it then?
