### ISSUE TITLE
[Feature request] Force login option for private instances

### ISSUE THREAD

**Issue by alexw1982** [iv-org/invidious#1741]
It would be nice to be able to redirect to the login/registration page when not logged in to force a login before viewing videos. The idea is to only allow logged in users to view videos when hosting a private instance for a limited user base without having to add additional creditionals / authentification mechanisms

**Comment by TheFrenchGhosty** [comment]
Would be a cool feature.

In the meantine, you can use the nginx basic authentication:

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by alexw1982** [comment]
Actually I am using authelia for authentication but I would love to have that additional layer of authentication removed for obvious usability reasons

**Comment by saltycrys** [comment]
The implementation of this could be based on or use https://github.com/kemalcr/kemal-basic-auth

**Comment by jtagcat** [comment]
Duplicate of #446
