### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by maxpearl** [iv-org/invidious#1743]
I'm running into this error on compilation: 
```
$ crystal build src/invidious.cr --release
Showing last frame. Use --error-trace for full trace.

In src/invidious/helpers/proxy.cr:76:7

 76 | @io = nil
      ^
Error: instance variable @io of HTTPClient was inferred to be Nil, but Nil alone provides no information
```

I've installed all of the dependencies, and the `shards update && shards install` step went mostly without a hitch. This error was the only glitch: `Shard "lsquic" version (2.18.1) doesn't match tag version (2.18.1-1)`

Suggestions?

**Comment by hackerncoder** [comment]
Problems with upgrade to 0.36.0 I am guessing. #1734.

**Comment by maxpearl** [comment]
No, I don't think so:
```
 crystal --version
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
I'm using this apt repo:
`deb https://dist.crystal-lang.org/apt crystal main`

**Comment by hackerncoder** [comment]
Well, ```Rename HTTPClient@socket to HTTPClient@io``` so it has to do something with it, you might want to update to 36 then try again.

**Comment by maxpearl** [comment]
I'm not a crystal (nor invidious) developer - I'm working to implement this for an organization. It looks like if it's in this shape, it's not quite ready for an organizational deployment. Which is fine, but it would be good to know that. I'll have a look at the docker option.

**Comment by GauthierPLM** [comment]
Following #1734, Invidious no longer build on Crystal 0.35.
Also, the Crystal team changed their repo and the one you use has not been updated yet.

You can easily install version 0.36 by running this command ([source](https://crystal-lang.org/2020/08/24/announcing-new-apt-and-rpm-repositories.html)):
`curl -fsSL https://crystal-lang.org/install.sh | sudo bash`

The APT repositories will be updated with the new ones.

I reported the issue to Invidious Updater here: Invidious-Updater#48

**Comment by GauthierPLM** [comment]
Invidious Updater has been updated a few hours ago to install Crystal 0.36.0 and use the new repository to install crystal.
