### ISSUE TITLE
[Bug] [error] UpdateDecryptFunctionJob : Nil assertion failed

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#1762]
**Describe the bug**
Invidious is stuck on the UpdateDecryptFunction job and doesn't refresh any YouTube channel.

**Steps to Reproduce**
1. Enable `decrypt_polling` in the config.
2. Run Invidious

It seems like it's only reproducible with an instance that have a lot of users

**Logs**
```
[development] Kemal is ready to lead at http://0.0.0.0:3000
2021-02-12 08:40:23 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
2021-02-12 08:41:23 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
2021-02-12 08:42:23 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
2021-02-12 08:43:24 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
2021-02-12 08:44:24 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
2021-02-12 08:45:25 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
```

**Screenshots**
N/A

**Additional context**
This issue appeared yesterday at around 1PM (CET).

**Comment by SamantazFox** [comment]
> It seems like it's only reproducible with an instance that have a lot of users

I confirm that it is not related to user count. I have the same issue on my private instance (I'm the only user).

**Comment by philippnagel** [comment]
Is this the same bug or should I open another issue:

Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-04T03:25:55Z`
Route: `/watch?v=XqAiGeEzctQ&autoplay=1&listen=true&continue=1`
Version: `2021.04.02-c4c2e01 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment]
Still relevant
