### ISSUE TITLE
[Bug] Links in the descriptions of a YouTube playlist don't appear correctly

### ISSUE THREAD

**Issue by andrigamerita** [iv-org/invidious#1767]
**Describe the bug**

When opening the page of a YouTube playlist on Invidious, links in the description of that playlist don't appear correctly.
Specifically, the links appear in cut form if long enough (example: https://example.com/abcdefghijklmnopqrst...) like they do on YouTube, but they are not clickable, unlike on YouTube. This means that long links in a playlist description become useless.

**Steps to Reproduce**

1. Go on [invidious instance]/playlist?list=PLNj_ZJF3LtBzxeoqwagc30AgrNvhSUu1L (or on the page for any other YouTube playlist with links)
2. Notice how long links get cut and how they cannot be clicked, meaning they are useless

**Logs**

No errors appear in the browser console.

**Screenshots**

Attached are two screenshots, one that shows how the playlist description section appears on YouTube (and should appear on Invidious), and one that shows how it actually appears on Invidious.
![YouTube](https://user-images.githubusercontent.com/37557992/107828312-e5019c80-6d88-11eb-9270-ea4446140473.png)
![Invidious](https://user-images.githubusercontent.com/37557992/107828311-e337d900-6d88-11eb-9381-d32bd6d5a9d2.png)

**Additional context**

The problem has been noticed on my private locally hosted instance, and on two random public instances (yewtu.be, invidiou.site), on 3 different browsers (Ungoogled Chromium and Firefox on Linux Mint 20, and Bromite on Android Nougat).

**Comment by ingvar-lynn** [comment]
Example html:
` <a href="javascript:void(0)" data-onclick="jump_to_time" data-jump-time="0">https://www.youtube.com/watch?v=ibnr_...</a>​ `

**Comment by dentistformyeye** [comment]
> Example html:
> `<a href="javascript:void(0)" data-onclick="jump_to_time" data-jump-time="0">https://www.youtube.com/watch?v=ibnr_...</a>​`

The example that @ingvar-lynn corresponds to YouTube links in the description that include a time parameter, even if `<time>` is left blank and regardless of whether the URL gets truncated by `...`:
```https://www.youtube.com/watch?v=<videoID>&t=<time>```
```https://youtu.be/<videoID>?t=<time>```

It seems to not affect embed links:
`https://www.youtube.com/embed/<videoID>?t=<time>`

Hovering over the affected links causes `javascript:void(0)` to show as the URL in the lower left of the browser.
If one of the affected links is clicked, the following red error appears in the browser console:
![image](https://user-images.githubusercontent.com/51429646/107926013-2f2e7d80-6f43-11eb-8151-274a34b9cd96.png)

```
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```
Example: https://invidious.kavin.rocks/watch?v=qOxAMlKygBg
If you check the video on YouTube, the link in the description is supposed to have the following destination:
```https://www.youtube.com/watch?v=8YjFjyGOZlw&t=0s```

It might also happen for links in the comments sections, but I haven't confirmed that yet.

I don't know for sure if this is related to the issue that @andrigamerita described. If not, feel free to split this time parameter bug into its own Github issue.

**Comment by TheFrenchGhosty** [comment]
It's also an issue in video description.

**Comment by B0pol** [comment]
Linked issues: https://github.com/iv-org/invidious/issues/1769 https://github.com/TeamNewPipe/NewPipeExtractor/pull/540

**Comment by SamantazFox** [comment]
@TheFrenchGhosty This can be closed :)
