### ISSUE TITLE
[Bug] Shard "lsquic" version (2.18.1) doesn't match tag version (2.18.1-1)

### ISSUE THREAD

**Issue by diolwe** [iv-org/invidious#1775]
**Describe the bug**

Compilation fails with the following message when following install guide:

````
crystal build src/invidious.cr --release
Showing last frame. Use --error-trace for full trace.

In src/invidious/helpers/proxy.cr:76:7

 76 | @io = nil
      ^
Error: instance variable @io of HTTPClient was inferred to be Nil, but Nil alone provides no information

````

**Steps to Reproduce**

Follow installation guide. At

````shards update && shards install````

you get

````
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/omarroth/protodec.git
Fetching https://github.com/iv-org/lsquic.cr.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Shard "lsquic" version (2.18.1) doesn't match tag version (2.18.1-1)
Installing db (0.10.0)
Installing pg (0.23.1)
Installing sqlite3 (0.18.0)
Installing radix (0.3.9)
Installing kilt (0.4.0)
Installing exception_page (0.1.4)
Installing kemal (0.27.0)
Installing pool (0.2.3)
Installing protodec (0.1.3)
Installing lsquic (2.18.1-1)
Writing shard.lock
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/omarroth/protodec.git
Fetching https://github.com/iv-org/lsquic.cr.git
Shard "lsquic" version (2.18.1) doesn't match tag version (2.18.1-1)
Using db (0.10.0)
Using pg (0.23.1)
Using sqlite3 (0.18.0)
Using radix (0.3.9)
Using kilt (0.4.0)
Using exception_page (0.1.4)
Using kemal (0.27.0)
Using pool (0.2.3)
Using protodec (0.1.3)
Using lsquic (2.18.1-1)

````
I assume that the bug could be connected with 

````Shard "lsquic" version (2.18.1) doesn't match tag version (2.18.1-1)````

When calling the next step 

````crystal build src/invidious.cr --release````

the error above is shown and invidious is not compiled.

**Comment by gripped** [comment]
That warning has been present for a while with successful compilations.
I'm almost certain you are getting that error because you are using an old (Crystal < 0.36) version of crystal.
https://crystal-lang.org/install/ has instructions an how to update.

**Comment by diolwe** [comment]
See install guide section: https://github.com/iv-org/invidious#install-the-dependencies
I end up with:

````
crystal --version
Crystal 0.35.1 [5999ae29b] (2020-06-19)
````

**Comment by gripped** [comment]
From https://crystal-lang.org/install/on_ubuntu/
Manual setup

The deb repository declared with deb_distribution=all and deb_component is used for the channel.

    The valid channels are stable, unstable, or nightly.

Replace the desired {CHANNEL} in the following script and you are all set.
```
echo "deb https://dl.bintray.com/crystal/deb all {CHANNEL}" | tee /etc/apt/sources.list.d/crystal.list

# Add repo metadata signign key (shared bintray signing key)
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
apt-get update
```

You'll need too add sudo unless logged in as root.
Or just run the script to do it automatically. Note the address is different to the one in the invidious instructions 
Our wrong instructions https://dist.crystal-lang.org/apt/setup.sh
Crystal site https://crystal-lang.org/install.sh

**Comment by diolwe** [comment]
Thank you for putting me on the right tracks!

The "bug" is in the install instructions. One needs crystal  0.36.1-1 to successfully compile the invidious binary and should therefore use the right repository for crystal: https://crystal-lang.org/install/on_ubuntu/

**Comment by gripped** [comment]
Yeah I'm going to fix it now

**Comment by diolwe** [comment]
Thank-you again!
