### ISSUE TITLE
[Feature request] Auto-fullscreen option in preferences for better 10 foot experience

### ISSUE THREAD

**Issue by TheShanMan** [iv-org/invidious#1780]
**Is your feature request related to a problem? Please describe.**

Using invidious on an HTPC (PC hooked up to a TV), I can launch a video URL and even auto play the video (by enabling it in preferences), but I'd like to avoid having to manually make it full screen ("f" key or via mouse).

**Describe the solution you'd like**

I'd like a preference and/or URL parameter to auto-fullscreen a video. This preference and parameter should work when pasting a video url into a new tab, not just when an invidious page opens a video (this relates to issue 1782).

**Describe alternatives you've considered**

I've considered assigning a button on my remote control to send the "f" key but buttons on a TV remote are a precious commodity, and adds avoidable complexity.

**Additional context**

**Comment by saltycrys** [comment]
Automatic fullscreen is not possible, fullscreen can only be activated by user action for security reasons.

One way to get a fullscreen like experience is to use the embed and a fullscreen browser (F11 in Firefox).

**Comment by TheShanMan** [comment]
I didn't realize Invidious had "embed" just like youtube does, so that's a very helpful suggestion. It's not so terrible to have the video fill the window... it leaves the option of manually full-screening it if desired but for the sake of wife approval factor, that's not strictly necessary with video loading as full-window. Now if we can just get autoplay working (issue 1782), like it does for youtube!
