### ISSUE TITLE
[Enhancement] Autoplay preference and url parameter doesn't work unless the video is opened by invidious

### ISSUE THREAD

**Issue by TheShanMan** [iv-org/invidious#1782]
**Is your enhancement request related to a problem? Please describe.**

If I launch an invidious video link from the OS or by pasting it into a new browser tab, the autoplay preference and url parameter are both ignored. It doesn't autoplay. My goal is to use invidious on an HTPC (PC hooked up to a TV), where I want a button on my remote to load and play a video so minimizing extra steps is important (I also have issue 1780 open for an auto-fullscreen option). I have everything working except the invidious side of things.

**Describe the solution you'd like**

If I have autoplay turned on in preferences, pasting a url like "https://vid.puffyan.us/watch?v=myvideoid" into a new tab should start playing automatically. If I don't have that preference set but I paste a url like "https://vid.puffyan.us/watch?v=myvideoid&autoplay=1" into a new tab, it should also start playing automatically.

**Comment by TheShanMan** [comment]
FWIW autoplay=1 partially works for youtube so I know it's technically possible. It doesn't seem to work for youtube if the browser is launched as a result of the OS launching a url, but if the browser is already running and the OS launches a url (i.e. a 2nd tab), youtube autoplays it. Hopefully that quirk is more of a youtube quirk and something invidious can do better, but it's possible it's a browser quirk (Brave in my case).

**Comment by saltycrys** [comment]
This is browser dependent. In Firefox it's enough to give Invidious the autoplay permission, Brave probably has something similar.

**Comment by TheShanMan** [comment]
I'm sure there are browser dependent subtleties to this (and launching by the OS might be one of them), but not in all cases. If I paste "https://youtu.be/watch?v=myvideoid&autoplay=1" into a new tab, it'll play, but if I do the same with "https://vid.puffyan.us/watch?v=X64VAXlbhgE&autoplay=1", it won't.

**Comment by TheFrenchGhosty** [comment]
saltycrys answered.
