### ISSUE TITLE
[Question] Auto refresh subscription list

### ISSUE THREAD

**Issue by excodex** [iv-org/invidious#1786]
Hello,

Is it possible to enable some auto refresh function? Because my subscription list only refreshes when I restart my docker container.

Am I missing something?

Thanks in advance!

**Comment by JackHewson** [comment]
This has already been working (without restarting container), but doesn't work since a few commits to master. Does anybody know why?

**Comment by TheFrenchGhosty** [comment]
It's supposed to be working but it sometimes break for days.
