### ISSUE TITLE
[Bug] I CAN’T LOGIN USING Google!

### ISSUE THREAD

**Issue by Damacy-Bissonnette** [iv-org/invidious#1788]
**Describe the bug**
Whenever I choose an instance and try to login into invidious using my Google account I get an error saying “ Unexpected char 'l' at line 1, column 2
Traceback:
Getting lookup...”

**Steps to Reproduce**
 Unexpected char 'l' at line 1, column 2
Traceback:
Getting lookup...

**Logs**
Don’t know how to do this

**Comment by Schmarotzer** [comment]
same problem

**Comment by pavelshin** [comment]
Same problem. Any ideas?
