### ISSUE TITLE
More user-friendly search

### ISSUE THREAD

**Issue by omarroth** [iv-org/invidious#179]
There should be a form similar to YouTube so users can more easily use advanced search. Currently search filters have the advantage that they can be used anywhere, but they are much more opaque and less documented than they should be. An optional search form could also provide tooltips for text filters.

_Originally posted by @dimqua in https://github.com/omarroth/invidious/issues/126#issuecomment-417133791_

**Comment by sebma** [comment]
@omarroth Do you plan to release that functionality soon ?

**Comment by omarroth** [comment]
No work has been done on this currently.

**Comment by SamantazFox** [comment]
Still relevant (related issues #1923 and #1969)

**Comment by syeopite** [comment]
I'll be fixing this in the PR for #1950

**Comment by SamantazFox** [comment]
Closed by #2956
