### ISSUE TITLE
[Bug] Videojs infinite retries / not refreshing

### ISSUE THREAD

**Issue by tenpura-shrimp** [iv-org/invidious#1794]
It looks like videojs has infinite retries, and they happen quite rapidly.  When the retries go on for a while, the instance will likely get rate limited by google.  We should probably limit these or take some other action.

I saw two scenarios where this happened: 

1. Leaving a dash video open for too long, so that the manifest expires.  Videojs will retry fetching the chunks but never fetch an updated manifest.  This leads to unlimited requests to /videoplayback until the window is closed.
2. A bad video url gets cached in the database.  I'm not sure how this happens in the first place, but if this happens the video player will keep retrying on latest_version until the database gets refreshed.

**Comment by tenpura-shrimp** [comment]
related videojs issues:
https://github.com/videojs/video.js/issues/5849
https://github.com/videojs/http-streaming/issues/1064

**Comment by SamantazFox** [comment]
@unixfox that should be fixed now, right?
