### ISSUE TITLE
[Discussion] About Cloudflare

### ISSUE THREAD

**Issue by hackerncoder** [iv-org/invidious#1809]
Moving the discussion of Cloudflare from #1694: https://github.com/iv-org/invidious/issues/1694#issuecomment-785632864 and https://github.com/iv-org/invidious/issues/1694#issuecomment-785819393.

Any discussion of Cloudflare is welcome, not just based on the above.

**Comment by hackerncoder** [comment]
> Do they actively try to suppress and/or hurt the TOR network itself (as you imply) or do they just block exit nodes?

They block exit nodes. I was speaking from feelings, that was wrong.

> inclined to abuse public resources such as TOR exit nodes for actually nefarious and malicious purposes.

Yes.

> I don't think it's a good idea to burden the TOR network with large amounts of data such as video 

I don't think it's a problem. The Tor Network has [a lot of unused bandwidth](https://metrics.torproject.org/bandwidth.html). Tor also needs cover traffic, e.g. day-to-day and other random traffic to keep others anonymous.

> but that would indeed be a use-case where being behind CF may be adverse.

:+1: 

&nbsp;

> If they really were against Tor, they would not do these things.

I was speaking from feelings, that was wrong.

> And why do they make blog posts about how they are working to get TOR working?
> https://blog.cloudflare.com/the-trouble-with-tor/

That's good. Also: https://blog.torproject.org/trouble-cloudflare.

\<pedantic> [It's Tor](https://support.torproject.org/about/why-is-it-called-tor/). Not [TOR](https://matt.traudt.xyz/posts/tor_spelling/) \</pedantic>

**Comment by TheFrenchGhosty** [comment]
It's been a week an no one added something. Closing.

**Comment by jloqfjgk** [comment]
> They block exit nodes.

But I can successfully visit the 3 Invidious instances marked with "uses Cloudflare" [listed here](https://docs.invidious.io/Invidious-Instances.md) using Tor Browser.

Note that browser console will display something like:
`Alternate Service Mapping found: https://invidious.site:-1 to https://cflareub6dtu7nvs3kqmoigcjdwap2azrkx5zohb2yk7gqjkwoyotwqd.onion:443`

Also note [this Cloudflare post](https://blog.cloudflare.com/cloudflare-onion-service/).
