### ISSUE TITLE
[Bug] Error message isn't HTML escaped

### ISSUE THREAD

**Issue by saltycrys** [iv-org/invidious#1810]
The error message isn't HTML escaped, leading to messages like https://github.com/iv-org/invidious/issues/1755.

> Route: `/feed/trending?type=News®ion=US`

should be

> Route: `/feed/trending?type=News&region=US`

<hr>

The error message is created here: https://github.com/iv-org/invidious/blob/b29e60a97aaef1d513208e177ecae8ffc671a3d9/src/invidious/helpers/errors.cr#L25-L44
See https://crystal-lang.org/api/0.35.1/HTML.html#escape(string:String):String-class-method

**Comment by hackerncoder** [comment]
Don't you mean #1755

**Comment by saltycrys** [comment]
> Don't you mean #1755

Yes, thank you.

**Comment by hackerncoder** [comment]
#1838 Is another one that shows this problem.
