### ISSUE TITLE
[Bug] Comments replies are broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1811]
**Describe the bug**

Comments replies don't work and just load the comments.

**Steps to Reproduce**

Go to any video, and try to load the replies of a comment.

**Logs**

N/A

**Screenshots**

Gif:

![gif](https://user-images.githubusercontent.com/47571719/109194890-c7253600-7791-11eb-86f9-5f716309e75c.gif)

**Additional context**

 - Browser (if applicable): N/A
 - OS (if applicable): N/A

Related PR: https://github.com/iv-org/invidious/pull/1795

**Comment by hackerncoder** [comment]
Maybe see the comments... https://github.com/iv-org/invidious/pull/1795#issuecomment-782844421

**Comment by tenpura-shrimp** [comment]
Looks like the problem is here
https://github.com/iv-org/invidious/blob/705e4fca06c4f895e434324d12d5f180d5c3b4d4/src/invidious/comments.cr#L91

I looked at the youtube ajaxes and it wants action_get_comment_replies=1

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been rewarded to @tenpura-shrimp for fixing this issue.

Transaction (953f8767f3332309009afe24ce19192bee0f8bf0dbf5ffdc3a082896c1137264):

Amount sent: 0.00036395 BTC (~16.73€ or ~20$)

Mining fees (30 sat/byte): 0.0000426 BTC (~1.96€)
