### ISSUE TITLE
[Meta] Channel pages are currently broken on YouTube

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1814]
**Please do not report issues about channel pages not working, they are currently broken on YouTube.**

Invidious will report on every channel:

```
Title: `Missing hash key: "metadata" (KeyError)`
Date: `[DATE]`
Route: `/channel/[ID]`
Version: `2021.02.25-705e4fc @ master`
```

**This isn't an Invidious issue.**

Channels don't load on YouTube, and the page will (mostly) be blank.

Example: https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw

**Comment by TheFrenchGhosty** [comment]
Issue seems fixed on the YouTube end.

**Comment by gotmax23** [comment]
This still appears to be an issue. I've tested it on multiple instances and have gotten this error:
https://bin.disroot.org/?9d28845074dba5aa#3YPGH2U8v54tMz9ZPgcBCD2qbJNtEr8PdGoNSo7Jbb83

**Comment by hackerncoder** [comment]
That is a different issue.#1637.
