### ISSUE TITLE
[Bug] PubSub is dead (maybe)

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1822]
**Describe the bug**

Google changed something and PubSub doesn't work with YouTube anymore.

Google PubSubHubbub block the subscriptions of URLs related to www.youtube.com

**We should for an answer by Google**, but otherwise everything PubSub related can be removed.

**Steps to Reproduce**

N/A

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

- https://developers.google.com/youtube/v3/guides/push_notifications

- https://issuetracker.google.com/issues/181221330 (requires a Google account): this is supposedly a bug report about it.
Screenshot (thanks to kavin on Matrix):

![image](https://user-images.githubusercontent.com/47571719/109315799-d6b08780-7842-11eb-80b5-d146f78be19c.png)

**Comment by TheFrenchGhosty** [comment]
![image](https://user-images.githubusercontent.com/47571719/109317407-97833600-7844-11eb-8169-24eec77df295.png)

Shared by unixfox on Matrix.

**Comment by unixfox** [comment]
![image](https://user-images.githubusercontent.com/4016501/109333865-de2e5b80-7857-11eb-8d65-4e4bfdf30a52.png)

**Comment by unixfox** [comment]
Got fixed on YouTube side:
![image](https://user-images.githubusercontent.com/4016501/109354602-fca34f80-7875-11eb-80c7-9033f04fd8ec.png)

**Comment by TheFrenchGhosty** [comment]
Fixed by YouTube 🎉
