### ISSUE TITLE
[Bug] DASH quality selection doesn't work reliably

### ISSUE THREAD

**Issue by saltycrys** [iv-org/invidious#1825]
Selecting the quality for a DASH video doesn't work reliably. This also affects the preferred DASH video quality.

This might be related to the recent Video.js update (from `v7.6.6` to `v7.10.2`).

**Comment by tenpura-shrimp** [comment]
May be related to this upstream issue.  https://github.com/videojs/http-streaming/issues/1064

If someone can repro the issue, the console logs will help.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

Do note that PRs are reviewed by @saltycrys his approval is required before we merge the PR, and reward you.

**Comment by TheFrenchGhosty** [comment]
Note:

Dash quality seems to be completely broken currently.
