### ISSUE TITLE
[Bug] Some videos that don't work with youtube-dl don't work with invidious

### ISSUE THREAD

**Issue by Dev380** [iv-org/invidious#1826]
**Describe the bug**

Some videos, (most of which are songs) keep showing "not supported" errors and such. I suspect it's an issue with DRM.
**Steps to Reproduce**

1. Go to 'https://invidious.snopyta.org/watch?v=cpyuolKoeAY'
2. See the error

**Additional context**

 - Browser (if applicable): Firefox Developer Edition
 - OS (if applicable): Pop! GNU/Linux (Ubuntu based)

**Comment by mostfunkyduck** [comment]
seeing this in vivaldi on windows with https://invidious.moistgarbage.info/watch?v=dQw4w9WgXcQ

**Comment by unixfox** [comment]
Probably just a region restricted video. On my instance with Proxy videos enabled it works great: https://yewtu.be/watch?v=cpyuolKoeAY

**Comment by mostfunkyduck** [comment]
I don't understand the internals, but should that work for me in the US? it currently shows the same error as it did before for both videos.

**Comment by unixfox** [comment]
What do you mean by you in the US? When using the "proxy videos" feature in the settings the video is fetched from the country of the instance.

Did you really enable "proxy videos"?

**Comment by mostfunkyduck** [comment]
sorry! i thought you were saying that was an option on the *instance*, not something in preferences. works for me as well.

**Comment by Dev380** [comment]
Nah, not geoblocked, I watched the exact video on YT and it works. With proxy videos on the same error shows.

**Comment by DontUseGithub** [comment]
some videos are specially protected
see [here](https://tyrrrz.me/blog/reverse-engineering-youtube) for more
> You may notice that some videos, mostly the ones uploaded by verified channels, are protected. This means that their media streams and DASH manifests cannot be directly accessed by URL — a 403 error code is returned instead. To be able to access them, you need to decipher their signatures and then modify the URL appropriately.
> 
> For muxed and adaptive streams, the signatures are part of the extracted metadata. DASH streams themselves are never protected, but the actual manifest may be — the signature is stored as part of the URL.
> 
> A signature is a string made out of two sequences of uppercase letters and numbers, separated by period. Here’s an example: 537513BBC517D8643EBF25887256DAACD7521090.AE6A48F177E7B0E8CD85D077E5170BFD83BEDE6BE6C6C.
> 
> When your browser opens a YouTube video, it transforms these signatures using a set of operations defined in the player source code, putting the result as an additional parameter inside URLs. To repeat the same process from code, you need to locate the JavaScript source of the player used by the video and parse it.
>

**Comment by TheFrenchGhosty** [comment]
YouTube issue.
