### ISSUE TITLE
[Enhancement] Small Button Next To Audio Icon For Youtube URL

### ISSUE THREAD

**Issue by grravity** [iv-org/invidious#1833]
Currently, for users who use Invidious simply for browsing or subscriptions, but choose to watch in something external like mpv using the original Youtube url, this is a bit tedious. If they wish to grab the original YouTube link they need to click onto the video, then right click the YouTube button to grab the link. Or manually edit the link.

My solution to make this easier, can come in two ways I imagine.
The first would be an option to rewrite all links as YouTube links, however this would only work if the user is using something such as Privacy Redirect. If they click the link, it redirects to the invidious link, if they right click it and copy it's the Youtube link.

The more ideal solution imo would come at the cost of adding an extra button, however it seems there is space. Right next to the headphones icon  for listen=1, could add a little YouTube icon that simply contains the original YouTube url. Users can then choose to grab the original Youtjbe url, or click the video title for the invidious url, without ever having to click into the video.

**Comment by comradekingu** [comment]
@grravity The better option is to land support in whatever other tool doesn't support invidious links alike.

**Comment by btdmaster** [comment]
@comradekingu @grravity mpv uses youtube-dl, which, according to https://github.com/ytdl-org/youtube-dl/issues/26153, considers invidious support out of scope. However, mpv [invidious url] works just fine, fetching from YouTube and hence making almost no unnecessary connections. Nonetheless, I would still consider it useful to give a 'watch on YouTube' option for whenever the playback breaks (I would personally usually skip out on the video or use mpv in that case, but I understand threat models vary).

**Comment by grravity** [comment]
Invidious does work, however I believe it doesn't grab in highest quality, because it doesn't passthrough dash? I could be wrong.

That being said I don't see the harm in a small icon next to the the audio only icon, that provides the youtube url.
The space exists.

I can send a photo example of what I am suggesting if you want.
It would simply make it so the user can grab the YouTube url without clicking into the actual video.

**Comment by TheFrenchGhosty** [comment]
Tell mpv to use yt-dlp.

This is a lot better than "standard' youtube-dl since they actually care about user requests: https://github.com/yt-dlp/yt-dlp/issues/92

**Comment by grravity** [comment]
My point isn't an attempt to target usage only at mpv, but simply provide users who browse invidious a quick way to grab the original youtube url if they want it, without needing to click on the video just to do so.

**Comment by TheFrenchGhosty** [comment]
I get your point, however I don't think encouraging users to use youtube is a good idea.

Feel free to try to change my opinion though.

**Comment by grravity** [comment]
Firstly, if an invidious instance goes down then the Invidious link becomes invalid. Yes it's simple to change it, however it's a bit to ask to non-technical users. Ontop of this, not all players support opening Invidious links (users with the default YouTube app, etc. which again, I suggest against but you can only do so much, and when they complain about Invidious opening in the browser, yk.)

Secondly, by sharing to a dedicated instance, it can add extra load onto it, instead of simply sharing the youtube link and allowing end users to select their instance (or using something like PrivacyRedirect for assistance) and more evenly distribute load.

I am in no way against sharing invidious links, and again it's not just about sharing, it's just the simple ability to have the original youtube link on the other browse page. It's already available on the video page itself ("view on youtube"), this just utilizes the blank space and adds a link so users don't need to make that extra click.

**Comment by grravity** [comment]
https://imgur.com/q2rxdWZ

**Comment by grravity** [comment]
Appreciate it!

**Comment by TheFrenchGhosty** [comment]
@grravity :) Enjoy
