### ISSUE TITLE
[Bug] fork: Cannot allocate memory (RuntimeError)

### ISSUE THREAD

**Issue by loud1337** [iv-org/invidious#1835]
**Describe the bug**

The website cannot allocate enough memory to the process, therefore shows an error.

**Steps to Reproduce**
1. Go to the route ‘/login’
2. Click on 'Log in/register'
3. Enter your invidious details
4. Click 'Sign in/register'

**Logs**

Title: `fork: Cannot allocate memory (RuntimeError)`
Date: `2021-02-28T18:21:40Z`
Route: `/login?referer=%2Flogin%3Ftype%3Dgoogle&type=invidious`
Version: `2021.02.04-ec82c1f @ master`
   
```
fork: Cannot allocate memory (RuntimeError)
  from /usr/share/crystal/src/signal.cr:121:3 in 'fork:will_exec'
  from /usr/share/crystal/src/crystal/system/unix/process.cr:123:5 in 'spawn'
  from /usr/share/crystal/src/process.cr:238:21 in 'login'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```

**Additional context**
 - Browser (if applicable): Chrome 87.0.4280.77 (Official Build) stable (64-bit)
 - OS (if applicable): iPadOS 14.2

I've attached a screenshot of the error.
![B6F0B3B2-E2A0-4725-80A9-DF16394D61EC](https://user-images.githubusercontent.com/75097279/109429285-08535b00-79c9-11eb-85b9-f74218f0d413.jpeg)

The site it was located on is **invidious.tube**

**Comment by unixfox** [comment]
probably an instance issue because the instance ran out of memory
