### ISSUE TITLE
Upscaling of user avatars

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#184]
Currently invidious always links to 76px resolution avatar versions, regardless of your screen resolution. This leads to upscaling of users' avatars on high-resolution screens (even 1920x1080). But you can instead links to any avatar versions, depending on the viewer screen resolution.

I'm talking about youtube users avatars in the comments section.

**Comment by omarroth** [comment]
Looks like YouTube uses `48x48`. Maybe using `176x176` if the user has `Use high-res thumbnails` enabled? Similar to #170.

**Comment by dimqua** [comment]
To my understanding, YouTube uses `40x40` previews and `76x76` images regardless of screen resolution.

> Maybe using 176x176

I like the idea, but why 176?

Also note that on low-res screens invidious' previews are very small, you are probably need to set min and max sizes for them.

**Comment by omarroth** [comment]
> why 176x176?
Not any particular reason, but YouTube uses it elsewhere on the site.

As for the issue with thumbnail sizes on mobile, acknowledged :)
