### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bruv989** [iv-org/invidious#1844]
Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-03T15:58:15Z`
Route: `/channel/UCR1D15p_vdP3HkrH8wgjQRw`
Version: `2021.02.26-489d015 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment]
This appears to be a duplicate of #1838. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.
