### ISSUE TITLE
How to disable JavaScript using queries?

### ISSUE THREAD

**Issue by btdmaster** [iv-org/invidious#1853]
When using a browser with bad JavaScript support, the noscript fallback does not kick in. How is this done manually?

**Comment by TheFrenchGhosty** [comment]
You can just block it entirely, with something like uMatrix or NoScript.

**Comment by btdmaster** [comment]
@TheFrenchGhosty this is unavailable in said browser. We're talking 2012 Internet Explorer. I understand supporting this is highly unlikely, but that doesn't solve the problem.

**Comment by hackerncoder** [comment]
There is likely a setting or option somewhere to disable JS completely. Other than that we cannot help you.

**Comment by btdmaster** [comment]
I understand, but I've been searching through all the settings and documentation and I could only find the option to disable JavaScript for comments. There probably is an option, but I can't find it, so hence I asked.

**Comment by hackerncoder** [comment]
In your browser you may be able to disable JS. I do not believe there is anything in invidious to disable JS.

**Comment by btdmaster** [comment]
Fair enough, I misunderstood. I cannot find any such an option (only disabling cookies) and I understand this is a highly unlikely edge case to support. Thank you.
