### ISSUE TITLE
[Discussion]Create another version of Invidious using pure Javascript

### ISSUE THREAD

**Issue by 138138138** [iv-org/invidious#1859]
I am considering writing a pure Javascript version of Invidious, using ReactJS or AngularJS.
Users GET and POST to YouTube without third party servers.
Eventually the site will be static with JS codes that tell the browser to communicate with YouTube directly.
This fulfills the need to watch and search videos, through subscriptions may need more work.
Users can analyze and debug the POST and GET request using their browsers, without installing IDEs and numerous packages for the debugger and compiler.
As the site is static, it can be hosted on any services without using any resources.
This prevents speed issues with the current Invidious instances.
Self-hosters also don't need to host their servers anymore.

However the privacy community seems to hate Javascript a lot, saying that it has security vulnerabilities and "privacy concerns".
So what are your opinions? Do you want to use a pure Javascript version but all client side YouTube client, or the current server side Javascriptless Invidious?

**Comment by dentistformyeye** [comment]
The most important reason I use Invidious is that it bypasses YouTube's privacy-invasive tracking of end-users. Is it possible to preserve that with a client-side-only alternative?
I don't know enough about JavaScript to have a problem specifically with the language yet.

**Comment by unixfox** [comment]
You can't do requests to YouTube servers directly from a browser due to Cross-Origin Resource Sharing being disabled on YouTube servers.
You can read what Cross-Origin Resource Sharing mean here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

In summary, I'm sorry, but your project won't work.

**Comment by unixfox** [comment]
@TheFrenchGhosty this issue can be closed.
