### ISSUE TITLE
[Bug] The media could not be loaded, either because the server or network failed or because the format is not supported. Firefox v86.0 x64

### ISSUE THREAD

**Issue by samuraikidXDA** [iv-org/invidious#1874]
**Describe the bug**
Cannot play a video from https://invidious.snopyta.org when i click play it return me: "The media could not be loaded, either because the server or network failed or because the format is not supported"

**Steps to Reproduce**
1. Go to 'https://invidious.snopyta.org/watch?v=vqpyMy65mFU' using Firefox 86.0 x64
2. Click on 'play'
4. See error "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Screenshots**

![error](https://user-images.githubusercontent.com/46766062/110240530-51b12680-7f44-11eb-8ded-fe0b90e98742.png)

**Additional context**
 - Browser (if applicable): Firefox 86.0 x64
 - OS (if applicable): Win7 x64

Thanks !

**Comment by hackerncoder** [comment]
Instance issue, network issue or Browser/OS missing codec issue. We cannot do anything.

**Comment by samuraikidXDA** [comment]
Should i contact Firefox team then ?

**Comment by TheFrenchGhosty** [comment]
No.
