### ISSUE TITLE
Error when watching a video "video append of 3585661b failed for segment #95 in playlist 5-placehold-uri-5"

### ISSUE THREAD

**Issue by phourniner** [iv-org/invidious#1879]
This happened while playing a video on yewtu.be, (https://yewtu.be/watch?v=lxBfdk090YA for reference) to where it will play for about 3 minutes, and then freeze, citing the error below.
![image](https://user-images.githubusercontent.com/73620435/110545716-23be1480-80f3-11eb-81a2-967f0672f9d8.png)

Thought I'd bring it to your attention, thanks.

**Comment by TheFrenchGhosty** [comment]
Instance issue, reported to @unixfox

**Comment by unixfox** [comment]
It's due to https://github.com/iv-org/invidious/issues/1888
