### ISSUE TITLE
[Bug] Playlists with 100+ videos don't display any videos on any instance.

### ISSUE THREAD

**Issue by obscurerev** [iv-org/invidious#1883]
Once again, can't make the default template display correctly so...
OS: ChromeOS
Browser: Chrome Version 87.0.4280.152 (Official Build) (64-bit)

Steps to reproduce issue:
1. Go to any invidious instance
2. Go to any playlist with over 100 videos
3. See no videos whatsoever

Screenshots: 
![Screenshot 2021-03-11 at 2 09 52 PM](https://user-images.githubusercontent.com/77601184/110848622-ec2aa600-8273-11eb-9829-3bf880f95d63.png)
![Screenshot 2021-03-11 at 2 09 40 PM](https://user-images.githubusercontent.com/77601184/110848642-f351b400-8273-11eb-899c-46a72a414d4f.png)

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

Do note that PRs are reviewed by @saltycrys his approval is required before we merge the PR, and reward you.

**Comment by SamantazFox** [comment]
Is the JSON parsing managed by invidious, or is it part of the language/a shard?

I get this error message when I try to load the long playlist provided by OP:
![Error message says: Could not extract playlistSidebarRenderer.](https://user-images.githubusercontent.com/52980486/111553198-2ae4c280-8784-11eb-8a91-f79f8ebe80c1.png)

My understanding of it is that either the text buffer holding the JSON array may be too short, or the JSON parser doesn't handle properly that array (this specific playlist's JSON is 65k characters long).

**Comment by tenpura-shrimp** [comment]
I'm being silly doing stupid stuff when saltys already posted the answer

https://github.com/iv-org/invidious/pull/1849#issuecomment-798313756

**Comment by SamantazFox** [comment]
> I'm being silly doing stupid stuff when saltys already posted the answer
> 
> [#1849 (comment)](https://github.com/iv-org/invidious/pull/1849#issuecomment-798313756)

If I understand correctly, the issue with long playlists and the issue Saltycrys is mentionning are two separate things. On one hand, we can't get the videos when a playlist is more than 100 videos long, and on the other hand, in a channel's "playlist" tab, we can't have the playlists on other pages (stuck to page 1).

**Comment by TheFrenchGhosty** [comment]
Done in #1911
