### ISSUE TITLE
[Bug]  "this channel does not exist"

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1885]
**Describe the bug**

When I click on a channel I get the error "this channel does not exist."
**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by AVerm** [comment]
Can confirm, I see it on https://invidious.snopyta.org/channel/UC-8QAzbLcRglXeN_MY9blyw for one example

**Comment by TheFrenchGhosty** [comment]
> Can confirm, I see it on https://invidious.snopyta.org/channel/UC-8QAzbLcRglXeN_MY9blyw for one example

This channel works perfectly.

**Comment by btdmaster** [comment]
I had the same issue, but I solved it with a refresh bypassing cache (Ctrl-Shift-R).
