### ISSUE TITLE
Latest invidious buggin' out. Needs restarted about every 2 hours.

### ISSUE THREAD

**Issue by Incognify** [iv-org/invidious#1894]
I upgraded to the latest invidious version and about every two hours now I get this error, which requires me to restart the instance. Invidious has been running good for days without throwing errors requirinng a restart, however the latest update seems to have some conflicts requiring constant restarting of the script for it to function.

```
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-03-16T23:35:58Z`
Route: `/feed/trending`
Version: `2021.03.13-502e8da @ master`
<details>
<summary>Backtrace</summary>
<p>
   

Read timed out (IO::TimeoutError)
  from /usr/share/crystal/src/io/evented.cr:120:39 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from lib/pool/src/pool.cr:55:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:14 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???

</p>
</details>
```

**Comment by Incognify** [comment]
Furthermore, reviewing resources and graphs: It doesnt' appear I'm hitting any CPU/Memory limits, ever. Only time I pound the CPU is during rebuilds/upgrades. So the error doesn't seem to be related to that, and visitor usage is the same after the upgrade as before the upgrade so that shouldn't be the cause.

**Comment by TheFrenchGhosty** [comment]
Invidious has required hourly restart for months. Nothing changed.

**Comment by Incognify** [comment]
Ah, perhaps they should just package an hourly cron to restart it hourly then. I've got something running hourly now. Maybe future releases can restart hourly automatically until stable enough to remove that requirement?

Only been rocking an instance for about 3 weeks. For a week or, it was smooth sailing with no restarts needed.

**Comment by TheFrenchGhosty** [comment]
https://github.com/iv-org/invidious/issues/1875
