### ISSUE TITLE
[Bug] missing hash key on comments api

### ISSUE THREAD

**Issue by tenpura-shrimp** [iv-org/invidious#1900]
This is happening on my local but not remote.  Probably google is rolling something out.

```
error | "Missing hash key: \"1:0:string\""
-- | --
errorBacktrace | "Missing hash key: \"1:0:string\" (KeyError)\n  from /usr/share/crystal/src/hash.cr:1030:9 in '[]'\n  from lib/protodec/src/protodec/utils.cr:390:5 in 'extract_comment_cursor'\n  from src/invidious/comments.cr:224:84 in 'fetch_youtube_comments'\n  from src/invidious.cr:2068:18 in '->'\n  from lib/kemal/src/kemal/route.cr:13:9 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'\n  from /usr/share/crystal/src/http/server.cr:498:5 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from ???\n"


```

**Comment by tenpura-shrimp** [comment]
working
```
EkMSC1hrdmtmcHNObzY4yAEA4AEBogINKP___________wFAAMICHQgEGhdodHRwczovL3d3dy55b3V0dWJlLmNvbSIAGAYy3AIKxAJBRFNKX2kxYnNBNXpNM2pqTmVxcjhfM2ZwUjNid0xQTWZwN1VUcmtiNEltSzNpSU1GTEREY29HaXpsOGFYaVNsODBpTHdtc3FoV0Y0THJVSGhfak5WbzRBMkVjUmZUalpkSWd2Vmp6YXFqSUQwSnpXSDIzV0Jabl9KVlNnTmF5WDRoRmsxTWRBSC1HTjNTem1YUXdJMjBuLVpnTmgxSHpaVmZKNkQtamlhNzQ3amJya29vUkUwQzFTM19IcUZ4NTk2Si1la0pTMGhwQTRGMURZZmtEZ29QcXJPUzByWG1Wckx5elhaMTRBYmduY2xSN0czR05PR0RJWnZoZ1cwT0dacExVYWxLVlVTTHlCdVlNUGZYbHNRc2R5aC11WUc3aWpaWVUzRU9VSEFscXVnb0tSWm5pRzhKS0EwNW5UeXdmN2RzSVEiDyILWGt2a2Zwc05vNjgwACgoMAA%3D
{"2:0:embedded" => {"2:0:string" => "XkvkfpsNo68", "25:1:varint" => 0, "28:2:varint" => 1, "36:3:embedded" => {"5:0:varint" => -1, "8:1:varint" => 0}, "40:4:embedded" => {"1:0:varint" => 4, "3:1:string" => "https://www.youtube.com", "4:2:string" => ""}}, "3:1:varint" => 6, "6:2:embedded" => {"1:0:string" => "ADSJ_i1bsA5zM3jjNeqr8_3fpR3bwLPMfp7UTrkb4ImK3iIMFLDDcoGizl8aXiSl80iLwmsqhWF4LrUHh_jNVo4A2EcRfTjZdIgvVjzaqjID0JzWH23WBZn_JVSgNayX4hFk1MdAH-GN3SzmXQwI20n-ZgNh1HzZVfJ6D-jia747jbrkooRE0C1S3_HqFx596J-ekJS0hpA4F1DYfkDgoPqrOS0rXmVrLyzXZ14AbgnclR7G3GNOGDIZvhgW0OGZpLUalKVUSLyBuYMPfXlsQsdyh-uYG7ijZYU3EOUHAlqugoKRZniG8JKA05nTywf7dsIQ", "4:1:embedded" => {"4:0:string" => "XkvkfpsNo68", "6:1:varint" => 0}, "5:2:varint" => 40, "6:3:varint" => 0}}
```

not working
```
EkMSC1hrdmtmcHNObzY4yAEA4AEBogINKP___________wFAAMICHQgEGhdodHRwczovL3d3dy55b3V0dWJlLmNvbSIAGAYywgIKqgJnZXRfcmFua2VkX3N0cmVhbXMtLUNxWUJDSUFFRlJlMzBUZ2Ftd0VLbGdFSTJGOFFnQVFZQnlLTEFUdHhJOGxFSzFlNEluSEtqajBSUXd5N3RMVVkzMGdFcExTcXpwRmdlbzJMUDJ1QW1MRGlUNGlBOURqcndKSW9hRy1pMmR3OUhOT3JXbUs1VkR2T08xOU9SVVUwNzgzWk5yNjRjamVtcUp3NzJKMGF4STA0NjhJU25HODZpTVJ2aTdibFpIVEZEVEgweTZMNUF0UXd0ZndKOVMzWE9OV2hMenZJRi1ad0l4WFZkLXdZSjAxckw2Q3dpckFRRkJJRkNJZ2dHQUFTQlFpR0lCZ0FFZ1VJaVNBWUFCSUhDSVVnRUJRWUFSSUhDSWNnRUFFWUFBIg8iC1hrdmtmcHNObzY4MAAoKDAA
{"2:0:embedded" => {"2:0:string" => "XkvkfpsNo68", "25:1:varint" => 0, "28:2:varint" => 1, "36:3:embedded" => {"5:0:varint" => -1, "8:1:varint" => 0}, "40:4:embedded" => {"1:0:varint" => 4, "3:1:string" => "https://www.youtube.com", "4:2:string" => ""}}, "3:1:varint" => 6, "6:2:embedded" => {"1:0:base64" => {"261808:0:float64" => -2.631693650344714e-40, "351959459:1:embedded" => {"1:0:varint" => 512, "2:1:float32" => 9.999999747378752e-5, "3:2:embedded" => {"1:0:embedded" => {"1:0:varint" => 12248, "2:1:varint" => 512, "3:2:varint" => 7, "4:3:bytes" => [59, 113, 35, 201, 68, 43, 87, 184, 34, 113, 202, 142, 61, 17, 67, 12, 187, 180, 181, 24, 223, 72, 4, 164, 180, 170, 206, 145, 96, 122, 141, 139, 63, 107, 128, 152, 176, 226, 79, 136, 128, 244, 56, 235, 192, 146, 40, 104, 111, 162, 217, 220, 61, 28, 211, 171, 90, 98, 185, 84, 59, 206, 59, 95, 78, 69, 69, 52, 239, 205, 217, 54, 190, 184, 114, 55, 166, 168, 156, 59, 216, 157, 26, 196, 141, 56, 235, 194, 18, 156, 111, 58, 136, 196, 111, 139, 182, 229, 100, 116, 197, 13, 49, 244, 203, 162, 249, 2, 212, 48, 181, 252, 9, 245, 45, 215, 56, 213, 161, 47, 59, 200, 23, 230, 112, 35, 21, 213, 119, 236, 24, 39, 77, 107, 47, 160, 176, 138, 176]}, "2:1:varint" => 20}}, "2:2:embedded" => {"1:0:varint" => 4104, "3:1:varint" => 0}, "2:3:embedded" => {"1:0:varint" => 4102, "3:1:varint" => 0}, "2:4:embedded" => {"1:0:varint" => 4105, "3:1:varint" => 0}, "2:5:embedded" => {"1:0:varint" => 4101, "2:1:varint" => 20, "3:2:varint" => 1}, "2:6:embedded" => {"1:0:varint" => 4103, "2:1:varint" => 1, "3:2:varint" => 0}}, "4:1:embedded" => {"4:0:string" => "XkvkfpsNo68", "6:1:varint" => 0}, "5:2:varint" => 40, "6:3:varint" => 0}}
```


So apparently at youtube it's a normal thing to ram a base 64 encoded protobuf into the string field of another protobuf.  (protobuf doesn't understand this.  Protobuf thinks it's just a string)  Then, Omar had the crazy lazy idea of just automagically trying to decode all of the string fields and treating them like embedded objects.  That means that if any string field in the protobuf looks and smells like a base64 encoded protobuf binary, it will be treated like that, not as a string.

In this case, it looks like youtube is now sending something that looks and smells like a base64 encoded protobuf when they weren't before.  Now I don't know if we can just treat this thingy the same way and ram it back into youtube like we did before, but my guess is that treating this like a string will fix this issue.

**Comment by tenpura-shrimp** [comment]
Can we just revert this thingy? 
https://github.com/iv-org/invidious/commit/7b53b6bfeff1670c1c5d3dd299b7ed6162a5e3c0

It seems better for us to treat this continuation token as a dumb token rather than looking inside and trying to reconstruct it later.

**Comment by TheFrenchGhosty** [comment]
Does this actually cause more bugs than just spitting logs?

**Comment by tenpura-shrimp** [comment]
Comments don't work at all.  Happening on my local but not remote, so google is probably gradually rolling out a new cursor format.

**Comment by TheFrenchGhosty** [comment]
On every videos? Or just some?

**Comment by tenpura-shrimp** [comment]
every video.

**Comment by SamantazFox** [comment]
I've been looking at the comments recently. And yup, it seems that many changes are hapenning.

**Comment by TheFrenchGhosty** [comment]
We will see what happen next week.

YouTube sometimes deploy temporary changes.

**Comment by TheFrenchGhosty** [comment]
Copied from #1926 
---





**Describe the bug**


Comments are broken because the API url requested by the frontend contains ```?format=html&hl=en-US&thin_mode=false```, causing a 500 error.

**Steps to Reproduce**


Go on any video.

**Logs**


Output of the page using ```?format=html&hl=en-US&thin_mode=false```:
```
{"error":"Missing hash key: \"1:0:string\"","errorBacktrace":"Missing hash key: \"1:0:string\" (KeyError)\n  from /usr/lib/crystal/hash.cr:1030:9 in '[]'\n  from lib/protodec/src/protodec/utils.cr:390:5 in 'extract_comment_cursor'\n  from src/invidious/comments.cr:229:84 in 'fetch_youtube_comments'\n  from src/invidious.cr:2067:18 in '->'\n  from lib/kemal/src/kemal/route.cr:13:9 in '->'\n  from /usr/lib/crystal/primitives.cr:255:3 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'\n  from /usr/lib/crystal/http/server.cr:498:5 in '->'\n  from /usr/lib/crystal/primitives.cr:255:3 in 'run'\n  from ???\n"}
```

**Screenshots**

N/A

**Additional context**


Maybe related to #1911 (ping @SamantazFox )

**Comment by tenpura-shrimp** [comment]
That query param is always there.
https://github.com/iv-org/invidious/blob/master/assets/js/watch.js#L300

What I saw in the OP is that youtube is changing the format of the continuation key which is causing the issue.

**Comment by SamantazFox** [comment]
Yeah, I started working on it before the long playlist fix, but put it on hold.

Last time I checked, a ctoken can be found in the initial data, and has to be used to query the first batch of comments.

**Comment by SamantazFox** [comment]
> Maybe related to #1911 (ping @SamantazFox )

Oh, and nope, can't be, this issue was opened before I started working on the playlists fix ^^

**Comment by tenpura-shrimp** [comment]
@TheFrenchGhosty Asking again since other people are also seeing this issue now. (and @SamantazFox since you know about this I guess)

Any objection to "reverting" https://github.com/iv-org/invidious/commit/7b53b6bfeff1670c1c5d3dd299b7ed6162a5e3c0 ? It wouldn't be git revert because there's alot of conflicts, but logically reverting what that change does.

If you are ok with that, I can put together a PR.

**Comment by keshavbhatt** [comment]
This also happens with passing type parameter in api url (https://invidious.snopyta.org/api/v1/trending?region=us&type=music)
The response is :
`{"error":"Missing hash key: \"subMenu\"","errorBacktrace":"Missing hash key: \"subMenu\" (KeyError)\n  from /usr/share/crystal/src/hash.cr:1027:11 in '[]'\n  from /usr/share/crystal/src/json/any.cr:102:7 in '[]'\n  from src/invidious/trending.cr:15:12 in 'fetch_trending'\n  from src/invidious.cr:2218:22 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:212:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:17:35 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'\n  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'\n  from /usr/share/crystal/src/http/server.cr:468:13 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from /usr/share/crystal/src/fiber.cr:92:34 in '->'\n  from ???\n"}`

**Comment by SamantazFox** [comment]
> @TheFrenchGhosty Asking again since other people are also seeing this issue now. (and @SamantazFox since you know about this I guess)

Afaik, you proposed a PR to solve that comments issue, didn't you?

> Any objection to "reverting" [7b53b6b](https://github.com/iv-org/invidious/commit/7b53b6bfeff1670c1c5d3dd299b7ed6162a5e3c0) ? It wouldn't be git revert because there's alot of conflicts, but logically reverting what that change does.

Sure, you can try, but I think it won't do much. As I said above, the ctoken is in the initial data anyway, so that has to be assessed.

**Comment by keshavbhatt** [comment]
@SamantazFox sure i will. thanks for clarifying.

**Comment by tenpura-shrimp** [comment]
The problem isn't the initial ctoken but getting the second ctoken

We actually use hardcoded values for the first ctoken and this still works
https://github.com/iv-org/invidious/blob/master/src/invidious/comments.cr#L65

the issue is that the code tries to extract the cursor from the second ctoken (which is changed format).  My proposal is to use the second ctoken as-is instead of extracting the cursor.
