### ISSUE TITLE
[Bug] Playback "crash" *sometimes* when using dash

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1914]
**Describe the bug**

When playing any video with Dash enabled (and proxy), more specifically, with [this config](https://github.com/PussTheCat-org/PussTheCat.org-Configs/blob/master/Services/Invidious/config.yml) the playback will just stop after around 4 minutes for no reason.

Note: this is inconsistent, and doesn't always happen, this is maybe related to how "fresh" the instance start is.

**Steps to Reproduce**

1. Enabled dash and proxy
2. Play any video
3. See it crash after ~4 minutes

**Logs**

**Screenshots**

**Additional context**

Maybe related to #1825 and #1679

@unixfox reported the same issue when I asked people on Matrix.

**Comment by readall** [comment]
Have faced this a few times yesterday and today. For me it was happening independent of the video quality, whether dash was used or not. Just having the proxy video setting on causes this.

**Comment by TheFrenchGhosty** [comment]
Considered solved.
