### ISSUE TITLE
[Enhancement] Don't translate locales name

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#1916]
**Is your enhancement request related to a problem? Please describe.**
Yes and no. I've noticed that currently, the different languages are translated in `locales/*.json`.
Imho, this seems useless and a waste of translation effort, as the principal use of these is to select UI languages in the preferences.

**Describe the solution you'd like**
As on Wikipedia, language names are not translated.

E.g: A russian speaking person will perfectly be able to read "russian" written in cyrillic.

**Comment by TheFrenchGhosty** [comment]
Related: https://github.com/iv-org/invidious/pull/851

**Comment by SamantazFox** [comment]
Closing, as this was fixed in #2576
