### ISSUE TITLE
[Enhancement] For audio downloads, is it possible to use file extensions .MKA for Opus and .M4A for AAC?

### ISSUE THREAD

**Issue by NintendoManiac64** [iv-org/invidious#1917]
Minor suggestion regarding audio-only downloads - how realistic would it be to have them use the extensions .MKA and .M4A instead? (for reference, youtube-dl uses the .M4A extension for AAC audio, though it uses .WEBM for OPUS audio).

In my experience, even with media players that are very picky about the extension matching the format (e.g. foobar2000), simply renaming a .WEBM to .MKA as well as renaming a .MP4 to .M4A will still result in it working without any issue.  Furthermore, modern media players like MPC-HC and mpv will automatically load the audio of a WebM or MP4 video if the audio track uses exact same file name but with a different extension, and simply renaming the audio extensions to .MKA or .M4A is all that's needed to take advantage of this.

Or are the extensions determined by YouTube's servers and therefore cannot be changed?

**EDIT:** To clarify, foobar2000 already plays .WEBM files without issue. My point is purely that .WEBM and .MKA are so similar that even foobar2000, which is very picky about the format matching the extension, can even play a .WEBM renamed to .MKA, and the same goes for a .MP4 renamed to .M4A which foobar2000 plays without issue.

Therefore, if even a picky media player doesn't have a problem with the exertions being .MKA and .M4A, then I don't think it'd be a general issue overall if Invidious used those extensions specifically for the audio downloads.

**Comment by tenpura-shrimp** [comment]
yes it's possible but it's would need an extra bodge
https://github.com/iv-org/invidious/blob/c8cdc50d29a7a6684314bc5e53fc328c7d3f85c3/src/invidious/views/watch.ecr#L149

The proper extension for webm is .webm, so if your player won't play it then that's the player's problem.  I don't think it makes sense for invidious to change this due to the pickiness of one specific player.

**Comment by NintendoManiac64** [comment]
> The proper extension for webm is .webm, so if your player won't play it then that's the player's problem. I don't think it makes sense for invidious to change this due to the pickiness of one specific player.

I think you misunderstood that part of my comment.

To clarify, foobar2000 already plays .WEBM files without issue.  My point is purely that .WEBM and .MKA are so similar that even foobar2000, which is very picky about the format matching the extension, can even play a .WEBM renamed to .MKA, and the same goes for a .MP4 renamed to .M4A which foobar2000 plays without issue.

So the point I was trying to make is that, if even a picky media player doesn't have issues with the exertions being .MKA and .M4A, then I don't think it'd be a problem.

**Comment by TheFrenchGhosty** [comment]
>To clarify, foobar2000 already plays .WEBM files without issue. My point is purely that .WEBM and .MKA are so similar that even foobar2000, which is very picky about the format matching the extension, can even play a .WEBM renamed to .MKA, and the same goes for a .MP4 renamed to .M4A which foobar2000 plays without issue.

Foobar doing something doesn't mean it should be done.

Ideally opus should be in .opus not in .webm, and aac should be in .acc not in .m4a, however, since youtube provide those in those containers (yes, m4a is just a container, same for webm, they aren't codecs) it's perfectly acceptable this way.

In short: get a better player.

**Comment by NintendoManiac64** [comment]
...you are still completely not understanding.

Foobar2000 handles the existing behavior _perfectly fine_. 

Using .opus and .aac for the audio would also be _perfectly fine_, and in my eye is actually preferred vs the current use of .webm and .mp4.  Yes, foobar2000 with its pickiness wouldn't like it, but honestly I do not care as I'm more interested in using them with the likes of mpv or mpc-hc anyway.

Since you simply do not seem to understand why I keep bringing up foobar2000 as an example of how similar the webm and mk_ containers are, I will avoid mentioning it in the future.
