### ISSUE TITLE
[Bug] Huge performance impact of background tab

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#1919]
**Describe the bug**
Large lag spikes in Firefox (86.0 / Ubuntu).

**Steps to Reproduce**
1. Play some large video, and pause it (e.g: `/watch?v=8MsTNqK3o_w`
2. Let the tab open in background
3. Wait until tab crashes
4. Huge lag spikes on a regular interval (every 5s)

**Comment by SamantazFox** [comment]
This *may* be related to #1794

**Comment by tenpura-shrimp** [comment]
If you don't have dash enabled in settings it would probably be because it tries to buffer the entire video.  #1576

**Comment by SamantazFox** [comment]
> If you don't have dash enabled in settings it would probably be because it tries to buffer the entire video. #1576

I have "Preferred dash video quality" set to "auto"

**Comment by TheFrenchGhosty** [comment]
@SamantazFox 

Can you provide more details how long until the "tab crashes" after an user "let the tab open in background"?

**Comment by SamantazFox** [comment]
I'm trying to reproduce and mesure. I'll let you know of my findings.

**Comment by SamantazFox** [comment]
IUpdate: I can't reproduce the bug

**Comment by SamantazFox** [comment]
Closing, as I can't reproduce anymore.

**Comment by rezad1393** [comment]
I don't know if this is related or not but my firefox gets laggy (as in cant switch tabs and have to wait for tab switch to occur)  when I play the videos in the newest update. specially if I play and pause two of them to load.
I have unloadtab addon and if I unload the invidious tabs my lags get fixed instantly.
