### ISSUE TITLE
[Enhancement] Use a different extension for audio-only downloads? (e.g. .opus, .aac, etc)

### ISSUE THREAD

**Issue by NintendoManiac64** [iv-org/invidious#1924]
It was mentioned that it would indeed be possible to use a different extension for the audio-only downloads, such as .opus and .aac

Is there any possibility of doing this, or using any other extension that isn't .webm and/or .mp4 (e.g. .mka, .m4a, etc)

This would be useful for various video players like mpv and mpc-hc where, if you load a video file and there's an audio file that uses the exact same file name but with a different, audio-related extension such as .opus or .aac, then the media player will automatically load that audio track.

(Note that this requires using an audio-related extension, such as opus, mka, or even something completely wrong like wav.  The current webm and mp4 for audio tracks, such as using mp4 audio with webm video, or webm audio with mp4 video, simply does not work with this automatic-load function.)

Currently, because invidious uses the exact same filename and extension for video and audio tracks, the user has to manually rename the audio file to a different extension after downloading. Furthermore, if the user doesn't rename the audio file before downloading the video file, the OS will likely automatically append (1) to the end of the file name so as to avoid a filename conflict, which will then require the user to once again manually rename so as to match the audio file.

**Comment by TheFrenchGhosty** [comment]
Invidious provide what youtube provide.

This won't change.

Use yt-dlp / youtube-dl if you need something more.
