### ISSUE TITLE
[Enhancement] Find an alternative to the "pool" dependency

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1934]
**Is your enhancement request related to a problem? Please describe.**

Pool is an Invidious dependency (see: https://github.com/iv-org/invidious/blob/master/shard.yml#L22 ) however it hasn't been updated in 2 years: https://github.com/ysbaddaden/pool

**Describe the solution you'd like**

Find an alternative, that is maintained.

**Describe alternatives you've considered**

Drop it.

**Additional context**

N/A

**Comment by tenpura-shrimp** [comment]
Pool is a really small helper lib
you could just pull it into iv-org.  The maintenance burden won't be large
alternatively you could use the pool that ships with db http://crystal-lang.github.io/crystal-db/api/0.4.2/DB/Pool.html
it's meant for db connections but it's implemented generically so you can put a factory for whatever you want in there

**Comment by Perflyst** [comment]
pool got updated: https://github.com/ysbaddaden/pool/issues/8

**Comment by syeopite** [comment]
Pool hasn't been present within Invidious since #2115
