### ISSUE TITLE
RSS Feed [Feature request]

### ISSUE THREAD

**Issue by TROMsite** [iv-org/invidious#1936]
At this time Invidious only provides an Atom feed. And in some instances, this does not work with some RSS Readers. Would it be possible to provide an RSS feed?

**Comment by hackerncoder** [comment]
What part of invidious? You may want to see one of the following: #1378 #1261 #978 #855 #565

**Comment by TROMsite** [comment]
I think all of these refer to Atom feeds and not RSS

**Comment by SamantazFox** [comment]
As I can see in the source code, youtube provides Atom feeds (this is recognizable to the RFC 3339 formatted timestamps):
https://github.com/iv-org/invidious/blob/533c6cefee1076f32424af5f853ffb7d7a746062/src/invidious.cr#L1293-L1294

So I guess that the original author didn't want to implement the two, and just stick to what youtube did provide.

**Comment by TROMsite** [comment]
@SamantazFox  I see. Yes I added [Feature request]

**Comment by TheFrenchGhosty** [comment]
Atom and RSS are almost the same, even Github only provide atom feeds, there is 0 reason to have both.

If you RSS reader doesn't support atom, get a better one.

**Comment by TROMsite** [comment]
We wanted to use it for our curated videos https://tromnews.com/videos/ so that users could have an invidious experience rather than youtube... And the plugin we use doesn't support Atom despite us asking the dev to add support for that for years... But anyways...

**Comment by TheFrenchGhosty** [comment]
@TROMsite This is an issue with your plugin sadly.
