### ISSUE TITLE
[Enhancement] Fill entire window with video (cinema)

### ISSUE THREAD

**Issue by vonas** [iv-org/invidious#1943]
**Is your enhancement request related to a problem? Please describe.**

The video player is relatively small and there's no real way to make it big except going fullscreen.

**Describe the solution you'd like**

I'd like to be able to watch videos in cinema mode, i.e. where the video fills the entire window, similar to how it works with original YouTube.

**Describe alternatives you've considered**

I've hacked these uBlock Origin rules together to get the desired result.
```
! Hide left and right padding containers.
invidious.himiko.cloud#$#div.pure-u-md-2-24.pure-u-1:nth-of-type(1) { display: none !important }
invidious.himiko.cloud#$#div.pure-u-md-2-24.pure-u-1:nth-of-type(3) { display: none !important }

! Stretch the player horizontally and vertically.
invidious.himiko.cloud#$##player-container { width: 100vw !important; height: 100vh !important; }
invidious.himiko.cloud#$##player-container { padding: 0px !important; }
invidious.himiko.cloud#$##player { height: 100vh !important }

! Hide the scroll bars (WebKit).
invidious.himiko.cloud#$#html::-webkit-scrollbar { display: none !important }

! Minor visual changes
invidious.himiko.cloud#$#.vjs-big-play-button { border: .06666em solid rgba(0, 0, 0, 0.0) !important }

! Modify navbar height such that it equals window.scrollY (53px in my case).
! Scroll down once to focus entire video. You can use an extension like Redirector to redirect a video
! from  /watch\?v=([a-zA-Z_\-0-9]{11})  to  /watch?v=$1#player-container
! which will scroll down to the video container.
! You can then scroll up to use the navbar and scroll back down once to focus the entire player.
! Side note: You can also use Redirector to redirect any YouTube link to your Invidious instance.
invidious.himiko.cloud#$#.navbar { margin-top: 8.5px !important; margin-bottom: 8.5px !important; }
```

**Additional context**

This is similar to #1880 but instead the whole window is filled.

Also, the idea was inspired by the [Improve YouTube](https://chrome.google.com/webstore/detail/improve-youtube-open-sour/bnomihfieiccainjcjblhegjgglakjdd) extension for Chrome.

---

![invidious-capture](https://user-images.githubusercontent.com/24623262/112740477-a3663300-8f7d-11eb-802a-9d3b69a1fe78.gif)

**Comment by TheFrenchGhosty** [comment]
Duplicates of #504
