### ISSUE TITLE
[Enhancement] Distinguish AV1 from h.264 in some way in the "download" listing

### ISSUE THREAD

**Issue by NintendoManiac64** [iv-org/invidious#1948]
Currently the labels for AV1 and h.264 are completely identical in the "download" listing.

I don't suppose it'd be blasphemous to suggest changing the listing in some way so as to be able to actually distinguish which formats are AV1 and which formats are h.264?

The following is an example video with AV1 encodes:

invidious.snopyta.org/watch?v=A0FZIwabctw

**Comment by TheFrenchGhosty** [comment]
Not necessary because of: https://github.com/iv-org/invidious/issues/1563
