### ISSUE TITLE
[Discussion] UI Overhaul 

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#1950]
I think the current user interface could use some improvements. Here's some of the ideas I've been playing around with.

Stacked hyperlinks should be replaced with pure css menus instead. This would have the advantage of making them look more like tabs as well.

<details>
<summary>
Trending
</summary>

![purecssmenu](https://user-images.githubusercontent.com/70992037/112886499-8b97c780-90c1-11eb-8fa2-5d335689b1f1.png)
</details>

Anything related to sorting could be condensed into a dropdown menu.
<details>
<summary>
Channels
</summary>

![channel tabs](https://user-images.githubusercontent.com/70992037/112886955-22648400-90c2-11eb-98a9-3c6d0c0cfd6b.png)

</details>

<hr>

For the filters box perhaps we should change it to be more like Youtube. 

<details>
<summary>
Example 1
</summary>

![yt filter icon](https://user-images.githubusercontent.com/70992037/112887364-9dc63580-90c2-11eb-88e2-c0fb5ffcf716.png)

</details>

Or maybe just the normal detail widget.

<details>
<summary>
Example 2
</summary>

![details widget](https://user-images.githubusercontent.com/70992037/112887357-99018180-90c2-11eb-8b54-cf8fcefadc61.png)

</details>
<hr>

Either way the looks of the frontend needs to be improved. Any particular thoughts or ideas about this?

**Comment by tenpura-shrimp** [comment]
I hate hiding shit in dropdowns.  Why hide it when you have more than enough space to show it right there?

Anyways that's just my opinion you can do whatever the maintainers want.

**Comment by syeopite** [comment]
# Still editing! Don't read if I accidentally comment this!

I agree with you that there's definitely enough space to omit the dropdown. However, the main reason for using one is not to conserve space but rather to categorize the elements and in turn inform the end user of its functionality.

While some people would be able to infer the functionality based on terms like "newest" or "oldest", others can not.  In order to increase the general privacy of everyone Invidious has to be able to appeal to these clueless and tech illiterate users.

This means that we have to label almost everything. For a horizontal design like the prototype I have above, its rather difficult to do so. 

Here's some low effort mark ups as an example.
<details>
1

![sort-by-header](https://user-images.githubusercontent.com/70992037/113375518-13e6c880-935f-11eb-9642-2196d3c26604.png)

2

![sort_by_header_2](https://user-images.githubusercontent.com/70992037/113376207-b2bff480-9360-11eb-8a33-6da943853987.png)

3

![vertical header sortby](https://user-images.githubusercontent.com/70992037/113379252-83ad8100-9368-11eb-941d-b062c16e3d5a.png)

All of these look rather ugly. I'm no way skilled in UI design but I feel like no matter what we do it'll look roughly the same. 
</details>

It'll look fair nicer to just use a dropdown menu.

**Comment by markozajc** [comment]
I'd have to disagree here. Both of the two inline mockups look decent and explain their function well.

**Comment by diabolic-preacher** [comment]
this looks like a broad enough topic, to perhaps also add a request to add a separate button (perhaps a 'search' lens icon) next to the search field. It will help with devices where one needs to press select to activate the text field to enter search term but that button is also used to send a Return. so trying to press that again, to execute the search, just activates the text input again. Just a small request.

**Comment by syeopite** [comment]
Looks like the dropdown issue is settled then. I'll go ahead and include an inline label for them.

> this looks like a broad enough topic, to perhaps also add a request to add a separate button (perhaps a 'search' lens icon) ...

![search bar](https://user-images.githubusercontent.com/70992037/114390419-c7349600-9b85-11eb-8bd7-b30ba7bfdc4c.png)

Like this? Not sure how I can implement the second part of your request though.

**Comment by syeopite** [comment]
Any objections to moving the channel description information to a dedicated about page?

**Comment by diabolic-preacher** [comment]
> Looks like the dropdown issue is settled then. I'll go ahead and include an inline label for them.
> 
> > this looks like a broad enough topic, to perhaps also add a request to add a separate button (perhaps a 'search' lens icon) ...
> 
> ![search bar](https://user-images.githubusercontent.com/70992037/114390419-c7349600-9b85-11eb-8bd7-b30ba7bfdc4c.png)
> 
> Like this? Not sure how I can implement the second part of your request though.
exactly this. the lens thing will enable me to have something to 'click and trigger' the search. this was the entirety of the request. have a button or icon (search lens as you showed) to trigger the search.

**Comment by diabolic-preacher** [comment]
> Any objections to moving the channel description information to a dedicated about page?

is this because currently it pushes down the videos much further? any other reason to move it?

**Comment by kmk3** [comment]
> Any objections to moving the channel description information to a dedicated
> about page?

Yes: IME the description is usually short/one line long, so that would just
hide away information.

If the problem is with lengthy descriptions (e.g.: longer than 5 or 10 lines),
maybe those could be automatically served hidden behind `<details>`, like the
filters on /search.  Though I can't remember any channel that I watch that has
such an issue; do you have any example in mind?

But regardless of the default channel page, I would still like to see the an
about page, as on YouTube it contains extra information:

* Channel creation date
* Total views
* External links

**Comment by dentistformyeye** [comment]
> Any objections to moving the channel description information to a dedicated about page?

I like having the entire description on the video page as things are now, including when the descriptions are long ([example](https://invidious.snopyta.org/channel/UCpa-Zb0ZcQjTCPP1Dx_1M8Q)). When I'm evaluating whether I'm interested in an unfamiliar channel, I find it convenient to have all of that information on the same page as the video listing.

**Comment by syeopite** [comment]
> is this because currently it pushes down the videos much further? any other reason to move it?

Pretty much. I personally find it annoying having to scroll down so much in order to find the contents on Mobile though it seems like the consensus here is that nobody wants to move it.

Anyhow, here's the about page 
![about page](https://user-images.githubusercontent.com/70992037/115017664-628b7b00-9ea6-11eb-9b85-4c2a8e60cfa0.png)

**Comment by diabolic-preacher** [comment]
> > is this because currently it pushes down the videos much further? any other reason to move it?
> 
> Pretty much. I personally find it annoying having to scroll down so much in order to find the contents on Mobile though it seems like the consensus here is that nobody wants to move it.
> 
maybe collapsing it like the filters in search page, could be an option. maybe about can show say one line of text and then have a Read more or Show more. or have a jump link to jump to the videos section.

**Comment by dentistformyeye** [comment]
My bad, I didn't consider mobile.

> maybe collapsing it like the filters in search page, could be an option. maybe about can show say one line of text and then have a Read more or Show more. or have a jump link to jump to the videos section.

Either of these sounds fine. If @syeopite goes for the former, I assume the channel description will already be preloaded (as opposed to being loaded on-demand the way comment replies on video pages are).
The About page looks good. Would it be okay to have the channel description appear on both the Videos page and the About Page?

**Comment by diabolic-preacher** [comment]
> ![search bar](https://user-images.githubusercontent.com/70992037/114390419-c7349600-9b85-11eb-8bd7-b30ba7bfdc4c.png)
> 
> Like this? Not sure how I can implement the second part of your request though.
will you be tracking this in any other issue or along with this issue/discussion. i am keen on following when this search icon gets implemented. thanks in advance :)

**Comment by kmk3** [comment]
@syeopite commented 7 hours ago:

> > is this because currently it pushes down the videos much further? any other
> > reason to move it?
> 
> Pretty much. I personally find it annoying having to scroll down so much in
> order to find the contents on Mobile though it seems like the consensus here
> is that nobody wants to move it.

@dentistformyeye commented 2 hour ago:

> My bad, I didn't consider mobile.
> 
> > maybe collapsing it like the filters in search page, could be an option.
> > maybe about can show say one line of text and then have a Read more or Show
> > more. or have a jump link to jump to the videos section.
> 
> Either of these sounds fine. If @syeopite goes for the former, I assume the
> entire channel description will already be preloaded (as opposed to being
> loaded on-demand the way comment replies on video pages are).

I had not considered mobile either (I usually use NewPipe for that) and I agree
that having to scroll down on mobile is annoying.  My main concern is also the
preloading; I find it annoying having to make an extra network request for a
small amount of information.

The simplest way might be to put the description inside `<details open="">` and
make it "closed" by default on mobile.

There appears to be no way to do that with css[1], so the page would have to be
served without the "open" attribute on mobile.

If that's not feasible, the next best thing would probably be to either hide it
entirely with css (with `@media` or something) on mobile (so the user would
have to use the about page instead) or add some js on mobile to auto-close it
and to open it onclick (not a big fan of this).

> Anyways here's what I have for the about page.  ![about
> page](https://user-images.githubusercontent.com/70992037/115017664-628b7b00-9ea6-11eb-9b85-4c2a8e60cfa0.png)

Nice.  By the way, how did you get the icons in the upper right corner to show
up?  I think I've never seen them on Invidious instances.  Is this feature also
part of the about page development?

[1] https://github.com/w3c/csswg-drafts/issues/2084

**Comment by syeopite** [comment]
Apologies for the late reply everyone! I got slightly sidetracked with implementing another tab (see below). 


> The About page looks good. Would it be okay to have the channel description appear on both the Videos page and the About Page?

Certainly, though imho it looks a bit odd having it appear in two places at once; especially with them being so close to each other. 
![about-with-description](https://user-images.githubusercontent.com/70992037/115544688-c243a680-a257-11eb-91c9-1956d3cdbf0a.png)

I'll recommend we remove the upper description when a user is on the about page. Something along the lines of this:
![about without description](https://user-images.githubusercontent.com/70992037/115544844-f1f2ae80-a257-11eb-9f88-18ab2429728e.png)

>If that's not feasible, the next best thing would probably be to either hide it
entirely with css (with @media or something) on mobile

Yeah that's probably the only option we can actually do here. I'll go ahead and put that on the todo list. 


In other news I've implemented full support for featured channels. The details box is mainly there to allow for easier scrolling on channels that feature massive amounts of other channels.
![featured channels](https://user-images.githubusercontent.com/70992037/115545729-fec3d200-a258-11eb-8828-e4b3abce0e2f.png)

**Comment by syeopite** [comment]
> will you be tracking this in any other issue or along with this issue/discussion. i am keen on following when this search icon gets implemented. thanks in advance :)

Most likely just this discussion. The PR is also unlikely to be finished anytime soon since I have way too many plans for it. Plus, this PR uses #1920 and #1985 so those would have to be merged before this one as well. If you'd like I could just go ahead and make a quick PR for just that.

**Comment by diabolic-preacher** [comment]
> Most likely just this discussion. The PR is also unlikely to be finished anytime soon since I have way too many plans for it. Plus, this PR uses #1920 and #1985 so those would have to be merged before this one as well. If you'd like I could just go ahead and make a quick PR for just that.

I am fine with waiting for it to get done in this PR. Lots of new stuff and concepts to learn here for me. I just know I will be using the search much more from my firetv once this is available.  😁

**Comment by TheDidek** [comment]
![Screenshot_20220105-100850187_1](https://user-images.githubusercontent.com/26121666/148191226-2a4d7b17-35b7-4432-a5c5-d6ade1c00694.jpg)

Buttons on mobile are too close to each other, I logged out instead of entering settings many times
