### ISSUE TITLE
[Bug] New YouTube consent page break Invidious

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1959]
**Describe the bug**

YouTube has a consent page (instead of just a consent message) for privacy, this break Invidious on most EU server where this happen.

Pages will be empty, sometimes (one out of ten times) the page will load, but it seems super random.

**Steps to Reproduce**

Get an IP in the EU affected by the new consent page, and try to run an invidious instance on it.

**Logs**

Nothing in the instance logs.

**Screenshots**

N/A

**Additional context**

It's something that was reported in the Matrix room.

According to some people having a cookie to make the request seems to work.

Related https://github.com/TeamNewPipe/NewPipeExtractor/issues/592

**Comment by unixfox** [comment]
The essential cookie is this one: `CONSENT=YES+cb.20210328-17-p0.en+FX+775`. That's the cookie stored after agreeing to the terms of conditions of YouTube.

There is no need to some crazy code for automatically clicking "I AGREE" button. There is not even a need to pass the rest of the CONSENT cookie which is `FX+775`.

Just sending this cookie on every request will fix the issue: `CONSENT=YES+cb.20210328-17-p0.en`. It's concise and doesn't hurt the privacy because every single YouTube users get the same exact cookie.

**Comment by Lomanic** [comment]
youtube-dl counterpart https://github.com/ytdl-org/youtube-dl/issues/28602

**Comment by unixfox** [comment]
A temporary solution on Invidious is to add this parameter to the config.yml:
```yaml
cookies: CONSENT=YES+cb.20210328-17-p0.en
```

This will send the previously talked cookie on every request. That's what I did on yewtu.be at least.

**Comment by SamantazFox** [comment]
Alternatively, `CONSENT=PENDING+136` can be used, too. However, it seems that this is not possible with the current implementation (probably some URL parameters?), but it can be done easily with CURL. E.g:

``` bash
curl -o out.html -b <(echo "CONSENT=PENDING+136") 'https://www.youtube.com/user/nenoxxcraftdupeuple?gl=US&hl=en'
```

**Comment by markozajc** [comment]
> A temporary solution on Invidious is to add this parameter to the config.yml:
> 
> ```yaml
> cookies: CONSENT=YES+cb.20210328-17-p0.en
> ```
> 
> This will send the previously talked cookie on every request. That's what I did on yewtu.be at least.

This cookie seems to have a date in it (2021/03/28), not sure if that could turn out to be an issue.

**Comment by unixfox** [comment]
> > A temporary solution on Invidious is to add this parameter to the config.yml:
> > ```yaml
> > cookies: CONSENT=YES+cb.20210328-17-p0.en
> > ```
> > 
> > 
> > This will send the previously talked cookie on every request. That's what I did on yewtu.be at least.
> 
> This cookie seems to have a date in it (2021/03/28), not sure if that could turn out to be an issue.

I think it's a date corresponding to the deployment of that "youtube consent" full page. I don't think the date will change.

**Comment by markozajc** [comment]
> > > A temporary solution on Invidious is to add this parameter to the config.yml:
> > > ```yaml
> > > cookies: CONSENT=YES+cb.20210328-17-p0.en
> > > ```
> > > 
> > > 
> > > This will send the previously talked cookie on every request. That's what I did on yewtu.be at least.
> > 
> > 
> > This cookie seems to have a date in it (2021/03/28), not sure if that could turn out to be an issue.
> 
> I think it's a date corresponding to the deployment of that "youtube consent" full page. I don't think the date will change.

I've figured that all it really needs is `YES+`. I haven't done any extensive research on that matter, but it does womm.

**Comment by unixfox** [comment]
> > > > A temporary solution on Invidious is to add this parameter to the config.yml:
> > > > ```yaml
> > > > cookies: CONSENT=YES+cb.20210328-17-p0.en
> > > > ```
> > > > 
> > > > 
> > > > This will send the previously talked cookie on every request. That's what I did on yewtu.be at least.
> > > 
> > > 
> > > This cookie seems to have a date in it (2021/03/28), not sure if that could turn out to be an issue.
> > 
> > 
> > I think it's a date corresponding to the deployment of that "youtube consent" full page. I don't think the date will change.
> 
> After a bit of research I've figured that all it really needs is `YES+`. I haven't done any extensive research on that matter, but it does womm.

Good catch! I didn't think of just leaving the `+` after `YES`. I also tested a similar way as you with just `YES` and it didn't work so good to know that adding a simple plus sign works.
