### ISSUE TITLE
[Bug] Comments - "unexpected token '<EOF>' at line 1, column 1"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1965]
**Describe the bug**

Comments are broken again, the frontend report a 500 when requesting them, going to the api URL requested show that it contains: "unexpected token '<EOF>' at line 1, column 1"

**Steps to Reproduce**

Try to read the comment of a video.

**Logs**

`
{"error":"unexpected token '<EOF>' at line 1, column 1","errorBacktrace":"unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)\n  from /usr/lib/crystal/json/parser.cr:125:5 in 'parse_exception'\n  from /usr/lib/crystal/json/parser.cr:121:5 in 'unexpected_token'\n  from /usr/lib/crystal/json/parser.cr:23:28 in 'parse_value'\n  from /usr/lib/crystal/json/parser.cr:13:12 in 'fetch_youtube_comments'\n  from src/invidious.cr:2067:18 in '->'\n  from lib/kemal/src/kemal/route.cr:13:9 in '->'\n  from /usr/lib/crystal/primitives.cr:255:3 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'\n  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'\n  from /usr/lib/crystal/http/server.cr:498:5 in '->'\n  from /usr/lib/crystal/primitives.cr:255:3 in 'run'\n  from ???\n"}
`

**Screenshots**

N/A

**Additional context**

Maybe related to: https://github.com/iv-org/invidious/issues/1900

The recent youtube change is maybe what caused the issue: https://github.com/iv-org/invidious/issues/1959 https://github.com/iv-org/invidious/pull/1960

**Comment by tenpura-shrimp** [comment]
I did a quick check and youtube is returning literally nothing for this endpoint now.

Maybe it's related to how they changed the cursor or something but idk.

**Comment by TheFrenchGhosty** [comment]
@tenpura-shrimp the weird thing is that it seems to work on snopyta's instance, an instance that doesn't have the consent page fix.

**Comment by tenpura-shrimp** [comment]
oh I think you hit the nail right on the head

**Comment by tenpura-shrimp** [comment]
Comments sets the required cookie here:
https://github.com/iv-org/invidious/blob/master/src/invidious/comments.cr#L88

But then you overwrite it here:
https://github.com/iv-org/invidious/blob/master/src/invidious/helpers/utils.cr#L12

My personal recommendation is that we shouldn't have a bespoke code for the consent cookie, and you can just slap it in the default example config.  It looks like the config does not have this issue.

If you give a recommended config, then the cookie also won't be excessively sent where it's not needed.

**Comment by TheFrenchGhosty** [comment]
Having the consent cookie enforced is useful. Can't we just pass both cookies?

**Comment by tenpura-shrimp** [comment]
It's not needed outside the EU locations, so personally I would rather have a config.

It's your call which approach to take in the end though for fixing this.

**Comment by TheFrenchGhosty** [comment]
Having it enforced is the way to go. It's less configuration for administrators of new instances and no manual intervention required for adminisrators of existing instances.

Having it on servers outside the EU is useless, yes, but not an issue.
