### ISSUE TITLE
[Enhancement] Declutter the search bar of channel ID and search filters

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#1969]
**Is your enhancement request related to a problem? Please describe.**

The search bar can quickly become cluttered when Invidious is appending filters and channels onto it. Plus I don't really think it's a good idea to show that much logic to the end user.

**Describe the solution you'd like**
Make the channel and search filters into URL params and have the back end use that. I think it'll look much cleaner then it currently is.

**Describe alternatives you've considered**

Cookies?

**Additional context**

Example of clutter
![Screenshot_20210402-043029_1_1](https://user-images.githubusercontent.com/70992037/113412123-5662d200-936c-11eb-97a3-08840f7270b8.png)

**Comment by comradekingu** [comment]
@syeopite Do you have a mockup of an uncluttered look?

**Comment by syeopite** [comment]
I mean its pretty self explanatory. The only thing on the search bar would be the actual search query instead of any search filters or channel id. 

![decluttered-search-bar](https://user-images.githubusercontent.com/70992037/113461732-4f3fd080-940d-11eb-8b06-30cdae7e8de5.png)

I'm not too familiar with URL params but maybe something like
`search?q=Science&sort_type=Channel&sort_date=year&sort_duration=long&channel=UCZYTClx2T1of7BRZ86-8fow `

**Comment by SamantazFox** [comment]
This has been fixed.
