### ISSUE TITLE
[Bug] Empty "videos" array in channels/playlists/<channel_id> API endpoint

### ISSUE THREAD

**Issue by greenfoo** [iv-org/invidious#1978]
**Description**
The `/api/v1/channels/playlists/<channel_id>` API endpoint always returns an empty `videos` array (event if `videoCount` is != 0)

**Steps to Reproduce**
1. Go to `https://<server_url>/api/v1/channels/playlists/<channel_id>` (example: https://invidious.silkky.cloud/api/v1/channels/playlists/UCSMOQeBJ2RAnuFungnQOxLg)
2. Check the response: the "videos" array on each playlist is always empty

**Comment by SamantazFox** [comment]
It seems to be an instnance issue. It works here on my local instance and on snopyta.

**Comment by greenfoo** [comment]
Are you sure?
I just tried the latest master (c0997f951c9af58a844d6098398ce0a39e43d052) and the issue still happens (ie. the "videos" list is empty):

![capture](https://user-images.githubusercontent.com/42691086/114859898-9ce41200-9deb-11eb-8cb2-98c0f4d288b0.png)

**Comment by SamantazFox** [comment]
Oh, my bad, I thought you were speaking about the videos of a single playlist.

I'd say thas this is probably wanted, but I'm not sure about the original developper's idea here. It's very likely that it caused a large performance impact in the past, and that has been removed (on large channels (e.g music labels or TV channels) with very large playlists (1000+ videos), this can yield a ton of JSON and take minutes to load)

**Comment by SamantazFox** [comment]
Closing, as this is an expected behavior.
You'll need to make separate requests for the actual data of the different playlists.
