### ISSUE TITLE
[Bug] Community section is broken

### ISSUE THREAD

**Issue by greenfoo** [iv-org/invidious#1979]
**Description**
The `Community` sections of a `Channel` only shows 3 entries even if many more are available.

**Steps to Reproduce**
1. Go to https://invidious.snopyta.org/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/community
2. Notice how there are only 3 entries
3. Compare this with the results returned by YouTube (https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/community)

**More info**
When using the REST endpoint (ex: https://vid.puffyan.us/api/v1/channels/comments/UC-lHJZR3Gqxm24_Vd_AJ5Yw) the same behavior is observed (ie. only 3 results are returned) and, **in addition**, there is no `continuation` field (which, according to [the documentation](https://github.com/iv-org/documentation/blob/master/API.md), should be present)

**Comment by SamantazFox** [comment]
The invidious API is *very* broken, and I guess that a big overhaul is required.
As for the community tab, I guess that the recent youtube API changes are the reason to that. Almost everything broke recently (comments, playlists, ...)

**Comment by midn1** [comment]
Comments work on yewtu.be. Perhaps because it's an older version? I haven't checked.

**Comment by TheFrenchGhosty** [comment]
For whatever reason the community section of https://invidious.snopyta.org/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/community has more post but is still incomplete. Something is definitely wrong.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by SamantazFox** [comment]
Bump, still relevant!
