### ISSUE TITLE
[Enhancement] Use the YouTube internal API instead of parsing HTML pages in Invidious

### ISSUE THREAD

**Issue by TiA4f8R** [iv-org/invidious#1981]
**Is your enhancement request related to a problem? Please describe.**

Currently, Invidious parses YouTube HTML webpages. Due to the number of requests made by an instance, this can result in a big amount of Captchas (especially if an instance has a big amount of users). However, Google uses an internal API which seems to be non rate limited (maybe on the mobile API only, I don't know). Also, it should reduce the data transfer.

**Describe the solution you'd like**

Use the YouTube internal API for most of endpoints instead of parsing HTML webpages. It uses POST requests.
Examples:

- `https://www.youtube.com/youtubei/v1/player?key=youtube_internal_api_key` -> videos fetching (split into two requests  `https://www.youtube.com/youtubei/v1/next?key=youtube_internal_api_key` with the same headers)

   Headers:
   ```json
  {
    "videoId": "video_id",
    "playlistId": "playlistId (if there is a playlist associated with the video (&list=playlist_id) when calling the URL)",
    "context": {
      "client": {
        "hl": "en",
        "gl": "US",
        "clientName": "1 (or WEB)",
        "clientVersion": "desktop_client_version (like 2.20210401.08.00)",
      }
    }
  }
  ```
  **WARNING**: Decryption will result in 403 HTTP codes for protected streaming URLs if you don't add this data to the JSON after the `context` object:

  ```json
  "playbackContext": {
      "contentPlaybackContext": {
          "signatureTimestamp": "sts",
          "(and maybe also) html5Preference": "HTML5_PREF_WANTS"
      }
  }
  ```
  `"sts"` is the `signatureTimestamp` of the YouTube JS player (I found it three times in the JS player during my tests, `18772` for example).

- `https://www.youtube.com/youtubei/v1/browse?key=youtube_internal_api_key` -> playlists fetching

   Headers:
   ```json

  {
    "browseId": "VL + playlist_id",
    "context": {
      "client": {
        "hl": "en",
        "gl": "US",
        "clientName": "1 (or WEB)",
        "clientVersion": "desktop_client_version (like 2.20210401.08.00)",
      }
    },
  "params": "wgYCCAA%3D (use this param if you want to show unavailable videos)"
  }
  ```

- `https://www.youtube.com/youtubei/v1/search?key=youtube_internal_api_key` -> search fetching

   Headers:
   ```json

  {
    "query": "search_query",
    "context": {
      "client": {
        "hl": "en",
        "gl": "US",
        "clientName": "1 (or WEB)",
        "clientVersion": "desktop_client_version (like 2.20210401.08.00)",
      }
    },
  "params": "a param to filter type of contents (I don't know if they are equals to the params used in YouTube search URLs or not.)"
  }
  ```

- `https://www.youtube.com/youtubei/v1/browse?key=youtube_internal_api_key` -> trending fetching

   Headers:
   ```json

  {
    "browseId": "FEtrending",
    "context": {
      "client": {
        "hl": "en",
        "gl": "US",
        "clientName": "1 (or WEB)",
        "clientVersion": "desktop_client_version (like 2.20210401.08.00)",
      }
    }
  }
  ```
  (Maybe other params are required in order to filter the results to a category.)

Note that I haven't test if the API returns 403 or not at a time because of a big amount of requests, so I don't know if this solution is reliable or not for the Invidious project.

**Describe alternatives you've considered**

Use the pbj parameter of YouTube URLs for all endpoints (like `https://www.youtube.com/watch?v=video_id&pbj=1` for videos). However, I think this solution will result in the same amount of Captchas but it can reduce the data transfer. However, the YouTube website doesn't use it anymore.

**Additional context**

@FireMasterK findings with the mobile API here: TeamNewPipe/NewPipeExtractor#568, TeamNewPipe/NewPipeExtractor#562
Some examples of implementation of the pbj parameter in the NewPipe Extractor code : [videos](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L711), [playlists](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubePlaylistExtractor.java#L53), [trending](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeTrendingExtractor.java#L57)

**Comment by SamantazFox** [comment]
This is already done :)
We're using `www.youtube.com/youtubei/v1/browse` endpoint, which is basically the same.

It's here in the code: https://github.com/iv-org/invidious/blob/master/src/invidious/helpers/youtube_api.cr

(NB: some parts of the code still rely on older endpoints. This is probably because nobody wants to break something that works)

**Comment by TiA4f8R** [comment]
> For the playlists, I can tell that the browse endpoint is lacking some infos (like playlist size), meaning that we have to rely on HTML extract to get them.

Didn't know ... Maybe the pbj=1 JSON returns this info?

**Comment by SamantazFox** [comment]
> Didn't know ... Maybe the `&pbj=1` JSON returns this info?

What is that parameter?

> Also, the `youtubei.googleapis.com/youtubei` API is the same as `www.youtube.com/youtubei` API but maybe Google check less the IP traffic and it can reduce Captchas, I don't know 🤔.

Maybe. That's something that large instance owners have to test. But I'd say that in the end, this is the same server that are serving the content, just with a different domain name/proxy path.

**Comment by TiA4f8R** [comment]
> > Didn't know ... Maybe the `&pbj=1` JSON returns this info?
> 
> What is that parameter?

See the implementation in NewPipe Extractor by following the links in my top comment.

**Comment by FireMasterK** [comment]
> For the playlists, I can tell that the browse endpoint is lacking some infos (like playlist size), meaning that we have to rely on HTML extract to get them.

This is false, the playlist size is given...
```
      "numVideosText": {
        "runs": [
          {
            "text": "96"
          },
          {
            "text": " videos"
          }
        ]
      },
```

**Comment by SamantazFox** [comment]
> This is false, the playlist size is given...
> 
> ```
>       "numVideosText": {
>         "runs": [
>           {
>             "text": "96"
>           },
>           {
>             "text": " videos"
>           }
>         ]
>       },
> ```

That's nice, then! I probably missed it, as I have megabytes of youtube JSON on my laptop, so chances are high that I didn't read the right file, lol

I'll do some testing on my side, to see what can be done. If you've channels/videos/playlists to try, and especially unusual/exotic ones, feel free to add them here!

**Comment by SamantazFox** [comment]
Update: after some testing, it appears that the two endpoints (`www.youtube.wom` and youtubei.googleapis.com`) are the same, the returned data looks very similar when sending the exact same query (though I didn't bother checking further, as the JSON order is different among queries and makes it difficult to compare with a basic diff tool).

The `player` and `search` endpoind works pretty well, I'm going to try an Invidious implementation.

**Comment by 89z** [comment]
These endpoints dont seems to return metadata such as `publishDate` - any idea on that?

**Comment by unixfox** [comment]
>       **WARNING**: Decryption will result in 403 HTTP codes for protected streaming URLs if you don't add this data to the JSON after the `context` object:
>       ```json
>       "playbackContext": {
>           "contentPlaybackContext": {
>               "signatureTimestamp": "sts",
>               "(and maybe also) html5Preference": "HTML5_PREF_WANTS"
>           }
>       }
>       ```
We can fetch the cipher protected videos using the ANDROID client name: https://github.com/TeamNewPipe/NewPipeExtractor/issues/562

**Comment by TiA4f8R** [comment]
But for some 8k videos, you will only get 4K streams (I am not sure).

**Comment by unixfox** [comment]
> But for some 8k videos, you will only get 4K streams (I am not sure).

I tried with this video: https://www.youtube.com/watch?v=Zv11L-ZfrSg and I'm still getting the 8K videoplayback URL:
```json
{
   "itag":571,
   "url":"https://r3---sn-5hne6nsr.googlevideo.com/videoplayback?expire=1624851211&ei=q-7YYIDEM4H8yAWt2b3wAw&ip=2a02%3A578%3A85d3%3Ab00%3Af611%3A5d33%3A2ff9%3Aad1d&id=o-ALe0Z7SRKjQlk0vjZ8zAz538EM6Q7TtRBNGZ2KwIqUQv&itag=571&source=youtube&requiressl=yes&mh=O0&mm=31%2C26&mn=sn-5hne6nsr%2Csn-4g5edney&ms=au%2Conr&mv=m&mvi=3&pl=38&initcwndbps=1688750&vprv=1&mime=video%2Fmp4&gir=yes&clen=3705020346&dur=987.133&lmt=1621837348941166&mt=1624829327&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=9466585&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJDG_bvrCTxwy3qimGckcGqVurZYA-_J6o-ExLY1xWh4CIHw84FOVDX399Yc_D7ui4u7rWRKXBz_LzJQpPIdjbu-8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIry41muvfQUEijYR6G1X8THDAONlZ6gkzRc61Yhm3oQAiEAuMJvbNEu9622-_PrbylvnrqVmEcTiAT2cMn5yDPzSUU%3D",
   "mimeType":"video/mp4; codecs=\"av01.0.16M.08\"",
   "bitrate":36577909,
   "width":7680,
   "height":4320,
   "initRange":{
      "start":"0",
      "end":"700"
   },
   "indexRange":{
      "start":"701",
      "end":"3036"
   },
   "lastModified":"1621837348941166",
   "contentLength":"3705020346",
   "quality":"highres",
   "fps":30,
   "qualityLabel":"4320p",
   "projectionType":"RECTANGULAR",
   "averageBitrate":30026513,
   "colorInfo":{
      "primaries":"COLOR_PRIMARIES_BT709",
      "transferCharacteristics":"COLOR_TRANSFER_CHARACTERISTICS_BT709",
      "matrixCoefficients":"COLOR_MATRIX_COEFFICIENTS_BT709"
   },
   "approxDurationMs":"987133"
}
```

**Comment by FireMasterK** [comment]
> I'm still getting the 8K videoplayback URL

This must be something new on YouTube's end because I had investigated this with @TiA4f8R on the NewPipe room and we had concluded that 8k streams weren't being returned a few weeks back.

Either ways, this is good news!

**Comment by syeopite** [comment]
Closable? Invidious now fully using InnerTube
