### ISSUE TITLE
[Bug] No search filters shown

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#1984]
**Describe the bug**
The search feature added in #1629 doesn't show up.

**Steps to Reproduce**
Do any search

**Screenshots**
![image](https://user-images.githubusercontent.com/52980486/113775876-98ec2c00-9729-11eb-8ea6-14d78525c118.png)

**Additional context**
Instance version: `2021.04.06-ae353ce @ master`
Browser: Firefox 86.0 on Ubuntu 20.04

**Comment by TheFrenchGhosty** [comment]
Works for me on latest master.

**Comment by SamantazFox** [comment]
Is there anything in the preferences, or the config file?

**Comment by TheFrenchGhosty** [comment]
https://github.com/PussTheCat-org/PussTheCat.org-Configs/blob/master/Services/Invidious/config.yml

**Comment by SamantazFox** [comment]
Okay, nevermind, I'm dumb. With my current dev setup, I forgot to deploy the assets....

**Comment by TheFrenchGhosty** [comment]
Ahah no problem, it happens :)
