### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hrg71** [iv-org/invidious#1986]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-07T03:42:47Z`
Route: `/watch?v=Pnvf9wSMepg`
Version: `2021.04.02-c4c2e01 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by syeopite** [comment]
Maybe a duplicate of #1762?

**Comment by markozajc** [comment]
Works on b7eba3b, I assume this is also the same as #1996.
