### ISSUE TITLE
[Bug] Playlist creation seems to be broken due to negative offset

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#1989]
**Describe the bug**

Attempting to create a new playlist would result in the error:
```
Error encountered while retrieving playlist videos.
OFFSET must not be negative 
```

**Steps to Reproduce**

1. Go to the playlist tab and attempt to create a new one
2. See error

**Logs**

**Screenshots**

**Additional context**

**Comment by syeopite** [comment]
62e46b7 seems like the culprit. `0 % 100` is not greater than zero so page_count stays zero.

**Comment by SamantazFox** [comment]
> [62e46b7](https://github.com/iv-org/invidious/commit/62e46b7a366fa10d376a5a95eb9051f581fa7f60) seems like the culprit. `0 % 100` is not greater than zero so page_count stays zero.

Yeah, it gives zero (0) pages if you have zero videos. That's the expected behavior.

The error says that you have is a negative offset, which has nothing to do with this code :)

**Comment by syeopite** [comment]
Oh I'm an idiot. I misread the offset calculation and thought it uses page_count.

**Comment by SamantazFox** [comment]
Don't worry ^^

The actual issue is either:
* here: https://github.com/iv-org/invidious/blob/master/src/invidious/routes/playlists.cr#L448
* or here: https://github.com/iv-org/invidious/blob/master/src/invidious/playlists.cr#L440.

**Comment by SamantazFox** [comment]
Here you go :)
