### ISSUE TITLE
[Feature request] Disable recommended videos setting & blank page (Ethical Settings)

### ISSUE THREAD

**Issue by trymeouteh** [iv-org/invidious#1993]
I got this idea after watching the social dilemma documentary. A setting to disable the side video recommendation feed when your watching a video in invidious and another setting to have a blank page with just the search box which can be an option as an alternative to the popular and trending page.

Invidious is already very basic in its design and by adding this, I think it will make Invidious less addictive and used more as a information portal and not an addictive platform.

**Comment by syeopite** [comment]
Actually all of these are already included in Invidious! Just go to the user preferences page and disable the `Show related videos` videos option and set `Default homepage` to none.

**Comment by trymeouteh** [comment]
Didnt see that, thank you
