### ISSUE TITLE
[Bug] "Shared X ago" display is sometimes offset by one month

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2000]
**Describe the bug**
The line saying "shared x ago" under videos (on a channel's page) are offset by one month.
This seem to happen only to videos that are exactly between 2 and 3 months old.

**Steps to Reproduce**
1. Search for a two months old video
2. Shows "shared 1 month ago"

**Screenshots**
On one specific video, that is a little over two months old:
![image](https://user-images.githubusercontent.com/52980486/114116144-6e929e00-98e4-11eb-9f92-a04dc8df2001.png)
![image](https://user-images.githubusercontent.com/52980486/114116238-92ee7a80-98e4-11eb-9d27-76a16c150305.png)

On a channel that posts a video every two days, we can clearly see the jump:
![image](https://user-images.githubusercontent.com/52980486/114116800-9d5d4400-98e5-11eb-99cb-c126a81f511a.png)

**Comment by markozajc** [comment]
This seems to be caused by the assumption that a month has 30 days in utils.cr: https://github.com/iv-org/invidious/blob/b7eba3bc178b76a733a142f475cdb83921d591c1/src/invidious/helpers/utils.cr#L215

**Comment by SamantazFox** [comment]
> This seems to be caused by the assumption that a month has 30 days in utils.cr [...]

I don't think so. If that was the issue, we would be able to properly see the "2 months ago" mark after 60 days. But the issue I describe is that "2 months ago" never shows up.
