### ISSUE TITLE
videos won't play [Bug] 

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#2001]
**Describe the bug**

No videos will play. Every video I click on I'm presented with message "Could not extract video info. Instance is likely blocked.".
**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by nathgit** [comment]
This happens with every video I click on.

**Comment by SamantazFox** [comment]
It's in the error message: "Instance is likely blocked"! Try on another instance :)

**Comment by nathgit** [comment]
This happens off & on for me & when it has, I _have_ tried on other instances & they didn't work either, so it's not from the error above.
