### ISSUE TITLE
[Bug] Layout messed up on iOS 12.5.2 since latest invidious update

### ISSUE THREAD

**Issue by 138138138** [iv-org/invidious#2002]
**Describe the bug**

Layout is messed up on my iPhone 6 iOS 12.5.2 device. The footer is penetrated inside the text and the search bar is at the right. The problem does not exist on iOS 14 but I cannot upgrade.

**Steps to Reproduce**

1. Upgrade to version 2021.04.08-b7eba3b
2. Layout screwed up
3. Go back to version 2021.04.01-4b6d0fb, the layout is normal

**Logs**

**Screenshots**

<a href="https://ibb.co/mbHhNm8"><img src="https://i.ibb.co/MZRPBb6/IMG-00042.png" alt="IMG-00042" border="0"></a>
<a href="https://ibb.co/nwYv128"><img src="https://i.ibb.co/p1M8KDr/IMG-00052.png" alt="IMG-00052" border="0"></a>

**Additional context**

Browser (if applicable): Safari
OS (if applicable): iOS 12.5.2

**Comment by SamantazFox** [comment]
What diud you do to fix it?
