### ISSUE TITLE
[Bug] Invidious incorrectly interprets YouTube links with time parameters + error in JS console

### ISSUE THREAD

**Issue by dentistformyeye** [iv-org/invidious#2020]
**Describe the bug**
`https://www.youtube.com/watch?v=<video ID>&t=<time>`
`https://youtu.be/<video ID>?t=<time>`
Clicking a link in the format above or clicking a hyperlinked timestamp causes an error to appear in the browser console, but the latter still works otherwise. Invidious behaves as if the former is a timestamp for the current video, but should instead treat it as a link to a different page.

**Steps to Reproduce**
1. Go to https://invidious.snopyta.org/watch?v=zP5KoqzcwaU and start the video
2. Scroll down and click the first link in the description. Open the browser console. >> An error appears in the console and the video skips to the end.
3. Go to https://invidious.snopyta.org/watch?v=8WHgHx12eI0 in the same browser tab and start the video
4. Scroll to the description and click the timestamp 01:52. >> Video skips to 1:52, as expected, but error appears in console.

**Logs**
N/A

**Screenshots**
During steps 2 and 4, this error appears in the browser console.
![image](https://user-images.githubusercontent.com/51429646/115073433-557e8400-9ec6-11eb-8271-6609654a9ed3.png)

During steps 2 and 4, this appears as the URL in the lower left corner of the browser.
![image](https://user-images.githubusercontent.com/51429646/115126858-305e4400-9fa0-11eb-8195-278326b4c40a.png)
In step 2, it should instead say `https://invidious.snopyta.org/watch?v=9lGkyDsFW9g&t=767`

**Additional context**

**Comment by SamantazFox** [comment]
Mmmh, yup, the timestamp handling code needs a bit of cleanup!

I recall having issues with it when doing #1881 ...

**Comment by dentistformyeye** [comment]
As a minor consequence of the current handling of timestamps in combination with https://github.com/iv-org/invidious/pull/1881/commits/57ea45ff51f30b219a2902d441012471795f0265, clicking a `00:00` timestamp in a video description or comments section refreshes the page instead of merely changing the progress of the current video.
1. Go to https://invidious.kavin.rocks/watch?v=b1Fo_M_tj6w and start the video
2. Scroll down to the description and click the `00:00` timestamp.

It's not a big deal, but it is a bit unexpected.

**Comment by SamantazFox** [comment]
> As a minor consequence of the current handling of timestamps in combination with [57ea45f](https://github.com/iv-org/invidious/commit/57ea45ff51f30b219a2902d441012471795f0265), clicking a `00:00` timestamp in a video description or comments section refreshes the page instead of merely changing the progress of the current video.
> 
> [...] It's not a big deal, but it is a bit unexpected.

Yeah, I know. Back then, the problem was that clicking on a link with a `0` seconds timestamp would reset the current video to `00:00`, even if it was a link to a different video.

Fixing that would require to take into account the context: i.e if you're on the `watch` page, you have to check if destination vid = current vid in order to so the appropriate action. In any other situation where this code is used (like in the playlist description page) you have to redirect to the `watch` page in every case.
