### ISSUE TITLE
[Bug] Regression: links in the footer aren't underlined anymore

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2022]
**Describe the bug**

Regression introduced in #1977 

The links in the footer aren't underlined anymore.

**Steps to Reproduce**

N/A

**Logs**

N/A

**Screenshots**

![bug](https://user-images.githubusercontent.com/47571719/115162476-384ae080-a093-11eb-93e6-8b18790c7bdb.png)

**Additional context**

N/A

**Comment by syeopite** [comment]
Is this really an issue? I personally feel like it looks much cleaner without the underline.

**Comment by TheFrenchGhosty** [comment]
@syeopite Underlining links is more accessible, this is usually how links are handled if they aren't in a different color.
