### ISSUE TITLE
[Bug] psql eating up disk / housekeeping

### ISSUE THREAD

**Issue by diolwe** [iv-org/invidious#2023]
**Describe the bug**

Even though autovacuum is on, postgres DBs are growing and eating up lots of disk space.

/var/lib/postgres/12/main/base/16385 is at more than 7G at the moment

1.1G    base/16385/16398
1.1G    base/16385/16398.1
1.1G    base/16385/16398.2
1.1G    base/16385/16398.3
1.1G    base/16385/16398.4
1.1G    base/16385/16398.5

Any idea, what is causing this? 
And more importantly: How can one get rid of postgres data which one does not need on a use-only-instance without accounts?

postgres version 12.6
invidious version 2021.04.08-b7eba3b @ master 

Thank you in advance for pointing me into the right direction!

**Comment by unixfox** [comment]
https://docs.invidious.io/Database-Information-and-Maintenance.md

**Comment by diolwe** [comment]
... blushes and closes his bug report ...
Thank you very much!
