### ISSUE TITLE
[Feature request] Retain player position.

### ISSUE THREAD

**Issue by jtagcat** [iv-org/invidious#2024]
**Is your feature request related to a problem? Please describe.**
On 1h+ videos, having to refresh or re-open the browser makes you lose the position.

**Describe the solution you'd like**
Keep the last passed timestamp ±10s/20s in browser-local storage.

**Describe alternatives you've considered**
Keeping a timestamp journal.

***
Edit, to not send out a notification:  
`t=$(t)s` would be great! It enables faster sharing / linking as well — user can copy right away, and quickly remove the tail themselves.

Though, I imagine someone out there would be offended by their links being cluttered, an user switch, defaulting to on, might be a good idea.

**Comment by An-dz** [comment]
An alternative implementation without requiring to write to the localStorage – that is prone to getting cluttered and break subsequent views as the site can easily forget to clean those, is to add `t=${t}s` to the query string every 10s with `history.replaceState`.

**Comment by TheFrenchGhosty** [comment]
@An-dz It sound like something that's really CPU intensive. Unless it's proven to not be, it will have to be opt in.

**Comment by An-dz** [comment]
It won't be any worse than saving on localStorage as long as you keep the query string in memory and just put it.

But it does take some time to investigate into which event to attach. I can think of multiple way to implement this, and each must be tested 

- Attach an event into

**Comment by An-dz** [comment]
It can't be much worse than saving on localStorage I guess. You can keep the "search" string already parsed in memory so you don't keep reading, parsing and updating it all the time.

But it does take some time to investigate into which event to attach. I can think of multiple way to implement this, and each must be tested. I'm currently in the process of doing some tests but I can't promise any report or implementation as I don't have much time to get into this.

- timeupdate, floor and then modulus to get if in 10 second interval
- attach setInterval on play and remove on pause/crash/whatever
- global setInterval and get current time and then do simple maths to get in 10s intervals

It's more complicated than that but I guess it gives the big picture.

I added the following and could not see CPU difference, which is surprising, but I haven't dwelved deep and my laptop CPU is a 10th gen Intel which is quite new. It updates the `t` value every second and whenever you seek.

```js
document.getElementById("player").addEventListener("timeupdate", (e) => {
	const currentTime = Math.floor(e.target.currentTime);
	const newUrl = new URL(document.location);
	newUrl.searchParams.set("t", `${currentTime}s`);
	history.replaceState(null, "", newUrl);
});
```

**Comment by ExpandingMan** [comment]
Any news on this?  I recently switched from using FreeTube to a local invidious instance, partially because I want the power of all my browser plugins (it's also just a lot simpler and cleaner).  However, I find this to be a very significant feature loss relative to using FreeTube, it's definitely something I make a lot of use of.

For me at least, if this could somehow be done on local storage to save the server from having to do the work it would be fine.  A giant cookie might get pretty scary, could do a smaller one with only last few videos I guess.  Not sure if it's possible to actually use local file-system  storage.

**Comment by TheFrenchGhosty** [comment]
@ExpandingMan I'll put a bounty on it thanks for reminding me of this issue.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
