### ISSUE TITLE
[Enhancement] Show player position while 

### ISSUE THREAD

**Issue by jtagcat** [iv-org/invidious#2025]
**Is your enhancement request related to a problem? Please describe.**
This screen:  
![image](https://user-images.githubusercontent.com/38327267/115229091-22c0cf80-a102-11eb-8eae-304ee25544b0.png)

I can't look at the position (will lose position after page refresh) nor skip to another part while something is not loading right.

**Describe the solution you'd like**
Don't disable/cover the bottom bar with the timeline.

**Comment by unixfox** [comment]
We can't do anything about this.
