### ISSUE TITLE
[Feature request] Gezer translation format in Hebrew

### ISSUE THREAD

**Issue by omeritzics** [iv-org/invidious#2029]
Hello, the translation format of project Gezer is used by free software translators in Hebrew, and also by Google.
I'd like to apply this format on the Hebrew translation in order to improve the translation quality, if you accept this.

Link to the Gezer translation format (in Hebrew): https://wiki.hamakor.org.il/wiki/Gezer/%D7%9B%D7%9C%D7%9C%D7%99_%D7%94%D7%AA%D7%A8%D7%92%D7%95%D7%9D_%D7%94%D7%9E%D7%9C%D7%90%D7%99%D7%9D

**Comment by SamantazFox** [comment]
Can you please do a quick summary of what this translation format is? From the graps I could understand (I used an automatic translator), it seems to be a list of rules for proper english -> hebrew translations (using some sentences over another, preferring gender-neutral forms, etc...)?

**Comment by omeritzics** [comment]
> Can you please do a quick summary of what this translation format is? From the graps I could understand (I used an automatic translator), it seems to be a list of rules for proper english -> hebrew translations (using some sentences over another, preferring gender-neutral forms, etc...)?

The format of project Gezer contains proper spelling and translating rules, and gender-neutral forms.

**Comment by SamantazFox** [comment]
> The format of project Gezer contains proper spelling and translating rules, and gender-neutral forms.

Oh, I see. This is good! Just watch out for context, as the translation keys are not always explicit on where translated strings are used.

I see that you've also pushed new translations on weblate: https://github.com/iv-org/invidious/commit/492def3b76ed0f0ac676be47056950daf5adf4c6!
