### ISSUE TITLE
Invidious error or something

### ISSUE THREAD

**Issue by Slashisfire** [iv-org/invidious#2035]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-21T18:53:07Z`
Route: `/watch?v=16quqiJz8D0`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment]
Duplicate of #1996. Which is an instance issue. This instance is running an outdated version of Invidious at https://github.com/iv-org/invidious/commit/42be1321b2119b3a48935ddccf3a8d7bd544d03c.
