### ISSUE TITLE
[Bug] Can't watch live video

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2037]
**Describe the bug**
I keep getting "403 forbidden" errors when trying to watch a live.

**Steps to Reproduce**
1. Got to invidious instance, and try to watch any live
2. Player seems to load indefinitely, browser network logs show 403 on .m3u8 file

**Logs**
[Devtools network logs - gzipped (.har.gz)](https://github.com/iv-org/invidious/files/6364970/invidious.local.samantaz.fr_Archive.21-04-23.12-07-42.har.gz)

**Screenshots**
![image](https://user-images.githubusercontent.com/52980486/115853580-a0018280-a429-11eb-8aea-5603e0584eaf.png)

**Comment by unixfox** [comment]
Strange, when watching any live from a search with a keyword "live" it works fine for me.

**Comment by SamantazFox** [comment]
I'm thinking that disabling dash may cause that...

**Comment by Zero3K** [comment]
I also am experiencing this issue.

**Comment by unixfox** [comment]
I can't reproduce this issue. Livestreams are working fine for me.

**Comment by jonathonf** [comment]
I'm seeing this with 2022.08.17-b0bb156, built using the production Docker file and configured according to the production setup instructions,

```
2022-08-19 14:31:03 UTC [info] 403 GET /api/manifest/hls_playlist/expire/1660940257/ei/gZv_YpG3LtSIir4P3ouh-Ac/ip/${SERVER_IP_ADDRESS}/id/jfKfPfyJRdk.1/itag/93/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir=yes;itag=140/sgovp/gir=yes;itag=134/hls_chunk_host/rr1---sn-tt1e7n7l.c.youtube.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/mh/rr/mm/32/mn/sn-tt1e7n7l/ms/su/mv/u/mvi/1/pl/24/sc/yes/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1660917977/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRgIhAPiJCHv3Ddq-5Dg3IxG0Iq6OCi0fLm9CxHSi_ttZo1h3AiEAnE8WXJDs_L02kE8YM5nIMqdNFYPNO10z7jMNkYK1ESY=/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,sc/lsig/AG3C_xAwRgIhAMPV7zcktncD1qo9hsOLkmfAXrOeu4GZip0h6aU2lzM9AiEAg0UIb-QLAVeBEOWdDvUW67A8g2gH3Jhrf0x7Kvs9-mA=/playlist/index.m3u8?local=true 29.14ms
```

**Comment by unixfox** [comment]
> I'm seeing this with 2022.08.17-b0bb156, built using the production Docker file and configured according to the production setup instructions,
> 
> ```
> 2022-08-19 14:31:03 UTC [info] 403 GET /api/manifest/hls_playlist/expire/1660940257/ei/gZv_YpG3LtSIir4P3ouh-Ac/ip/${SERVER_IP_ADDRESS}/id/jfKfPfyJRdk.1/itag/93/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir=yes;itag=140/sgovp/gir=yes;itag=134/hls_chunk_host/rr1---sn-tt1e7n7l.c.youtube.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/mh/rr/mm/32/mn/sn-tt1e7n7l/ms/su/mv/u/mvi/1/pl/24/sc/yes/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1660917977/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRgIhAPiJCHv3Ddq-5Dg3IxG0Iq6OCi0fLm9CxHSi_ttZo1h3AiEAnE8WXJDs_L02kE8YM5nIMqdNFYPNO10z7jMNkYK1ESY=/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,sc/lsig/AG3C_xAwRgIhAMPV7zcktncD1qo9hsOLkmfAXrOeu4GZip0h6aU2lzM9AiEAg0UIb-QLAVeBEOWdDvUW67A8g2gH3Jhrf0x7Kvs9-mA=/playlist/index.m3u8?local=true 29.14ms
> ```
> 
> Livestreams have never worked for me on a self-hosted instance.

Please post the video ID of livestream.

**Comment by jonathonf** [comment]
Here's one example, https://www.youtube.com/watch?v=jfKfPfyJRdk

It would be interesting to see if a stream that's working for you also works for me...

**Comment by unixfox** [comment]
> Here's one example, [youtube.com/watch?v=jfKfPfyJRdk](https://www.youtube.com/watch?v=jfKfPfyJRdk)
> 
> It would be interesting to see if a stream that's working for you also works for me...

Seems to work fine here: https://yewtu.be/watch?v=jfKfPfyJRdk

Do you have DASH enabled in the preferences?

**Comment by jonathonf** [comment]
Yes, DASH is enabled.

I decided to try accessing the instance directly, rather than via the [nginx reverse proxy](https://docs.invidious.io/nginx/), and the livestream works. So, there's something going on with nginx. :confused:

**Comment by unixfox** [comment]
You shouldn't have to tweak the CSP rules through NGINX/reverse proxy, the ones provided by invidious are correct. Yewtu.be just have a different setup because it handles a lot of users at the same time.

Make sure you did correctly set these parameters, and you shouldn't have any CSP issue:
```
domain: yourexactdomain.name
external_port: 443
https_only: true
```

**Comment by jonathonf** [comment]
The server is running a very plain x86 Debian 11 Bullseye with the upstream Docker CE (no Cloudflare or anything else). I was running with Nginx from the Debian repo (1.18.0), and have just tried switching it out for the Nginx-provided repo version (1.22.0) (no change).

There are a few configuration elements in your example that don't seem to be part of (or configured by default in) a standard Nginx install:

* $connection_upgrade
* $proxy_add_forwarded
* $proxy_add_x_forwarded_for

I don't know if these make a difference?

**Comment by unixfox** [comment]
Idk, you might as well try it.
That's everything included into the NGINX config of the test instance. It is running NGINX version 1.18.0 on Debian.

If that doesn't work on your setup, then something is off with your NGINX.

**Comment by jonathonf** [comment]
Sorry, I meant that Nginx has no idea what those configuration items are, e.g. 
```
nginx: [emerg] unknown "proxy_add_forwarded" variable
```

**Comment by unixfox** [comment]
I don't have this variable `proxy_set_header Forwarded         $proxy_add_forwarded;` on my own setup (not the test instance) so it is optional.

**Comment by jonathonf** [comment]
It's not just that one variable, it's all three I listed above. Are any of those important to make this work?

**Comment by unixfox** [comment]
To be fair, for basic usage only the ones listed in https://docs.invidious.io/nginx/ are really needed.

**Comment by jonathonf** [comment]
OK, so the question for me is still why does adding nginx was a reverse proxy break livestreams? I'll do some more digging, maybe set up another instance on a different VPS provider... :thinking:

**Comment by unixfox** [comment]
Adding NGINX shouldn't break the livestreams, I'm using NGINX. It's not a bad idea to start from scratch.

You could also try this automated script: https://github.com/tmiland/Invidious-Updater. It should have the correct config for livestreams to work.

**Comment by jonathonf** [comment]
Good news, @SamantazFox spotted that the nginx proxy_pass config was incorrect. I've opened a [PR](https://github.com/iv-org/documentation/pull/269) to fix the documentation.
