### ISSUE TITLE
[Bug] recorded stream

### ISSUE THREAD

**Issue by porkmanager** [iv-org/invidious#2041]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-26T13:10:09Z`
Route: `/watch?v=ViUL9LKVzaM`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by markozajc** [comment]
The instance is out of date, please ask the administrator to update it. This issue seems to have been fixed on latest master.
