### ISSUE TITLE
[Bug] Invalid cookie value (IO::Error) while trying to save settings

### ISSUE THREAD

**Issue by frknkrc44** [iv-org/invidious#2044]
I'm using LibreWolf 88.0 AppImage. Also tried with Firefox and Chrome. it's my build and works on ubuntu container.

Title: `Invalid cookie value (IO::Error)`
Date: `2021-04-28T09:35:12Z`
Route: `/preferences?referer=%2Fwatch%3Fv%3DfuOgPU10THA`
Version: `2021.04.21-bfd02ac @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid cookie value (IO::Error)
  from /usr/share/crystal/src/http/cookie.cr:40:7 in 'new:name:value:expires:secure:http_only'
  from src/invidious/routes/preferences.cr:194:41 in 'update'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by sdfg2** [comment]
I get exactly the same error.

**Comment by SamantazFox** [comment]
@frknkrc44 @sdfg2 Can you please provide a screenshot of the preferences page (or better a browser devtool logs of the request). This would be really helpful :)

**Comment by sdfg2** [comment]
@SamantazFox what settings do you want in the screenshot?  It does it no matter what preferences I choose.

I had a look in the console and inspector and couldn't find anything you might be interested in, happy to help if you can direct me (Vivaldi).

**Comment by lyn1337** [comment]
Same problem here on a fresh installation plus host, when setting anything and then confirming.
![image](https://user-images.githubusercontent.com/10338543/120045651-cca04f80-c010-11eb-96a0-a6c02dde81bf.png)

Works however, when an account is created and when logged in.

**Comment by SamantazFox** [comment]
@sdfg2 when you are in the inspector, you have a tab called "network". In here, you can see all the requests that the browser sent to a website. Click on the `html` request to `/preferences?referer=...`, and copy the contents of the `request` tab. It will contain the data sent when you pressed "save".

**Note:** Make sure to open the inspector _before_ pressing "save preferences"!

![image](https://user-images.githubusercontent.com/52980486/120076962-53543b80-c0a8-11eb-8e40-b30df5d7b00b.png)

**Comment by sdfg2** [comment]
@SamantazFox here you go

![image](https://user-images.githubusercontent.com/5736478/120098724-72e27700-c12f-11eb-8903-a34ddfd44d4b.png)

**Comment by SamantazFox** [comment]
@sdfg2 Thanks :) However, I can't reproduce the error with my version of Firefox... Will try with Vivavldi later.

@frknkrc44 @lyn1337 @sdfg2 can you please tell more about your setups?
* is your instance running on bare metal? If yes, what distro are you using (ubuntu, debian, arch, ...)? Or is it running in docker?
* Do you have a reverse proxy, and if yes, which one (nginx, lighttpd, apache, ...)?
* Can you also post your server's `config.yml`(**Make sure to remove your database password before posting!!**)?

I'd like as many infos as possible to try to reproduce your bug :)

**Comment by syeopite** [comment]
This really isn't helpful but I've encountered this error a few times. A refresh always fixes it though so I've never been able to consistently reproduce it.

**Comment by sdfg2** [comment]
@SamantazFox 

VPS, Arch, nginx 1.19.10.  Turned off UO, same behaviour.  Cookies set to block third party (so if it's that, I have questions... ;) )  Probably makes no difference, but using postgres 13.2.

`channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: lolnope
  host: localhost
  port: 5432
  dbname: invidious
# alternatively, the database URL can be provided directly - if both are set then the latter takes precedence
# database_url: postgres://kemal:kemal@localhost:5432/invidious
full_refresh: false
registration_enabled: false
login_enabled: false
top_enabled: false
feed_menu: []
host_binding: 10.1.0.1
cookies: CONSENT=YES+
default_user_preferences:
  dark_mode: true
  comments: ["",""]
  local: true
  related_videos: false
  quality: dash
`

**Comment by SamantazFox** [comment]
> cookies: CONSENT=YES+

@sdfg2 can you try to remove this line from the config? PR #1960 fixed that :)

**Comment by SamantazFox** [comment]
@sdfg2 Thanks for the infos. I've tried with both your config.yml and a vivaldi browser, and I can't manage to reproduce it yet. I'll try to reproduce your whole server environment later (I don't have the time to install archlinux atm ^^)

**Comment by sdfg2** [comment]
@SamantazFox sorry it's been a busy few days.  I didn't realise that had been fixed!  I've taken that out, same behaviour.  And I tested in Firefox as well, same behaviour.

**Comment by unixfox** [comment]
@sdfg2 is this fixed then?

**Comment by sdfg2** [comment]
@unixfox Not unless there's a release I've missed?
