### ISSUE TITLE
Setup questions

### ISSUE THREAD

**Issue by RiversideRocks** [iv-org/invidious#2046]
Hello, I'm setting this up on my machine. How can I:

- Access the config file?
- Force videos to proxy?
- Force dark mode?
- Set what videos show up on the popular tab?

**Comment by hegdenischay** [comment]
Invidious' documentation is in [here](https://github.com/iv-org/documentation).
Everything you need is in the [configuration section](https://docs.invidious.io/Configuration.md), and the videos on the popular tab are the latest videos from the channels that the users have subscribed to.

**Comment by RiversideRocks** [comment]
Thanks, I'll review that. What is the exact path of of the config.yml file? I ran the invidious installer and I can't seem to find an invidious folder anywhere under /usr/share and /usr/local/share or anywhere else.

**Comment by RiversideRocks** [comment]
Found, under /home/invidious/invidious

**Comment by RiversideRocks** [comment]
I checked the docs and I'm still unsure how to force videos to proxy.

**Comment by hegdenischay** [comment]
Add `local: true` to your `default_user_preferences` options.

**Comment by RiversideRocks** [comment]
Thank you!
