### ISSUE TITLE
[Enhancement]  Discovery feed - random videos from subscriptions

### ISSUE THREAD

**Issue by valueforlife** [iv-org/invidious#2050]
**Is your enhancement request related to a problem? Please describe.**

Finding videos to watch is challenging

**Describe the solution you'd like**

A feed that took random videos from subscriptions would be great. It should be relatively easy to implement as well. 

**Describe alternatives you've considered**

I've considered learning crystal lang and building it myself. 

**Additional context**

**Comment by ytprivatecom** [comment]
I think the easiest method would be storing the recommended videos you get when you watch a video in a database and then have a page displaying all of those videos.
