### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nouoneq** [iv-org/invidious#2054]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-30T18:54:51Z`
Route: `/watch?v=A-rEb0KuopI`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>
**Screenshots**
https://i.imgur.com/ZbPxsBD.png

**Additional context**
 - Browser (Firefox)

**Comment by markozajc** [comment]
The instance is out of date, please ask the administrator to update it. This issue seems to have been fixed on latest master.
