### ISSUE TITLE
[Bug] I can't watch videos

### ISSUE THREAD

**Issue by frknkrc44** [iv-org/invidious#2055]
**Describe the bug**
I'm opening any video but it says "This is a modal window. The media could not be loaded, either because the server or network failed or because the format is not supported."

**Steps to Reproduce**
1- Compile latest source
2- Try to open video

**Logs**

**Screenshots**
![Screenshot_20210501-075555737](https://user-images.githubusercontent.com/45714956/116771323-136f4980-aa53-11eb-9289-d4a5e747e11f.jpg)

**Additional context**

**Comment by markozajc** [comment]
This happens on some videos when the requested quality (hd720 by default) is not available. Adding `&quality=dash` to the url to force usage of dash or setting dash as the preferred quality in the settings might fix the issue.

**Comment by code3z** [comment]
Hi @markozajc this seems to be especially the case for vevo videos. How about using quality=dash automatically if the video fails to load?

**Comment by SamantazFox** [comment]
Probably related to #602

**Comment by Computershik73** [comment]
Hello. I have this problem with most official music videos, for example, on Vevo. The links lead to videos that cannot be played by Symbian's system player (Nokia 808 PureView)...

**Comment by XXXBold** [comment]
I have a similar problem for some videos. I can work it around by enabling proxy redirection, which makes it work. 
![grafik](https://user-images.githubusercontent.com/30773753/180516633-9130b9b5-a522-4894-9545-f6889609b7d6.png)
(Language is German)

An example video where this is required: https://invidious.sethforprivacy.com/watch?v=ICaTsTkBPV8

I'm using Firefox on Linux mint (But other browser I've tested has the same problem)

If you need more info let me know.

**Comment by unixfox** [comment]
> I have a similar problem for some videos. I can work it around by enabling proxy redirection, which makes it work. ![grafik](https://user-images.githubusercontent.com/30773753/180516633-9130b9b5-a522-4894-9545-f6889609b7d6.png) (Language is German)
> 
> An example video where this is required: [invidious.sethforprivacy.com/watch?v=ICaTsTkBPV8](https://invidious.sethforprivacy.com/watch?v=ICaTsTkBPV8)
> 
> I'm using Firefox on Linux mint (But other browser I've tested has the same problem)
> 
> If you need more info let me know.

Thanks for reporting, we recently introduced a way to automatically try to proxy the video but that feature broke in recent commits... I'll have to review them.
