### ISSUE TITLE
[Feature request] Blocked instances could show youtube link to video ... or federate

### ISSUE THREAD

**Issue by diolwe** [iv-org/invidious#2056]
My invidious instance is used by 5 schools which seems to contribute to being blocked by YT rather often. It then shows "Could not extract video info. Instance is likely blocked. "

Idea / Request: Instead of simply informing the user that this "instance is likely blocked" invidious could

- show the youtube link (so that teachers do not have to post 2 links but only one)
- show a link to another invidious-instance which is not blocked (I know - this is much much more than a simple hack)

**Comment by hackerncoder** [comment]
> show the youtube link (so that teachers do not have to post 2 links but only one)

Already does. Below "Could not extract video info. Instance is likely blocked." There is "Watch on YouTube"

**Comment by diolwe** [comment]
I'm on 2021.04.29-8bc91ce @ master and it does not show this link ... there is only a header, a footer and the body is empty except for the error message. Is it part of a setting which I missed?

![ksnip_20210501-150337](https://user-images.githubusercontent.com/907156/116783337-80540500-aa8e-11eb-86ad-6fe60f088a67.png)

**Comment by hackerncoder** [comment]
https://vid.puffyan.us/watch?v=zK5WcXdbE00

No.

**Comment by diolwe** [comment]
puffyan.us is 2021.04.08-b7eba3b - could make a difference

I came across this error in the context of what I see on puffyan.us, too - that is: error message is shown and only the comment section is empty. This white window (see screenshot above from my invidious instance) seems to be something different: no comment section, no video section - just plain white nothing.

**Comment by sedding** [comment]
To bring this issue to the surface again: I am also affected by the problem. When the instance is blocked, the error message appears on an otherwise blank page. No comment section is displayed - and accordingly no link to the original YT page.

Of course, the best solution for this case would be to display a selection of other invidious instances and pass on the video URL to one of them (manually chosen...) correctly.

As an emergency solution, however, I would like at least the link to YT itself to be displayed.

**Comment by diolwe** [comment]
Even thought the mentioned error page could (should) be reworked to show the Youtube-Link - wouldn't an even better solution be to show the Google Captchas? 

If it is possible to use external services like anti-captcha with invidious to solve Captchas – why not hand them directly to the person who is on invidious? Or am I violating Clarke's third law here?

**Comment by SamantazFox** [comment]
> Of course, the best solution for this case would be to display a selection of other invidious instances and pass on the video URL to one of them (manually chosen...) correctly.

Yup, displaying a link to https://redirect.invidious.io/ and another to youtube seems a good idea.


> Why not hand them directly to the person who is on invidious?

Well, you can't provide a privacy-friendly service, and at the same time load the google/recaptcha scripts on the webpage whenever the instance is blocked. This is contradictory!

**Comment by SamantazFox** [comment]
Fixed by #1940
