### ISSUE TITLE
[Bug] wont let me watch any video 

### ISSUE THREAD

**Issue by dolordv** [iv-org/invidious#2057]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

![Screenshot 2021-05-01 11 01 01 AM](https://user-images.githubusercontent.com/83469346/116786480-dadc6980-aa6c-11eb-9c2b-d93748c6e1bf.png)

**Comment by SamantazFox** [comment]
The reason is in the error message. The instance you're using is being blocked by (or can't access) Youtube.
