### ISSUE TITLE
[Enhancement] Allow changing RefreshChannelsJob frequency

### ISSUE THREAD

**Issue by imiric** [iv-org/invidious#2060]
**Is your enhancement request related to a problem? Please describe.**

`RefreshChannelsJob` currently has a hardcoded 1 minute refresh time:
https://github.com/iv-org/invidious/blob/8bc91ced4fb22437dd8198536b331d76f82dd351/src/invidious/jobs/refresh_channels_job.cr#L61-L62

While it's great that subscriptions are being updated now, refreshing my 348 subscriptions takes about 90s and uses up ~2MBps of downstream bandwidth.

**Describe the solution you'd like**

I'd like to avoid the constant refreshing from using up my bandwidth and don't need this job to run every minute. Ideally there would be an admin page in the web UI that shows the status of all jobs and allows running them manually and configuring their schedule.

**Describe alternatives you've considered**

Since that is a large feature maybe allow changing the schedule at startup via the CLI.
In the meantime, I'll change the hardcoded value and rebuild it, and maybe learn Crystal... :sweat_smile:

**Comment by Jojonintendo** [comment]
That would explain the constant pinging I see on my PiHole too. As I don't even have subscriptions it's not really useful to me, and I'd love to be able to disable this, not necessarily via UI, config.yml would be fine too.
