### ISSUE TITLE
Looks like I've found a bug in Invidious

### ISSUE THREAD

**Issue by hargi** [iv-org/invidious#2064]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-05T18:16:43Z`
Route: `/watch?v=NCtzkaL2t_Y`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by Blackwidow-sudo** [comment]
Just had the same Bug:

Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-06T13:44:59Z`
Route: `/watch?v=CaJZnHHP7Bo`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>
