### ISSUE TITLE
Issue during log-in

### ISSUE THREAD

**Issue by Falleocrat** [iv-org/invidious#2066]
Title: `fork: Cannot allocate memory (RuntimeError)`
Date: `2021-05-05T22:48:45Z`
Route: `/login?referer=%2Fwatch%3Fv%3D4p0fRlCHYyg&type=invidious`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
fork: Cannot allocate memory (RuntimeError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment]
Seems the instance did/does not have enough memory.
