### ISSUE TITLE
[Bug] cant watch a video

### ISSUE THREAD

**Issue by dolordv** [iv-org/invidious#2070]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

![Screenshot 2021-05-08 10 42 56 AM](https://user-images.githubusercontent.com/83469346/117543296-31582380-afea-11eb-836a-cf13a504b65b.png)

**Comment by hackerncoder** [comment]
Use a different instance, that one is blocked.
