### ISSUE TITLE
Transfering invidious.site domain ownership to anyone interested

### ISSUE THREAD

**Issue by wapfalls** [iv-org/invidious#2071]
Hi All,

I bought this domain (invidious.site) from namecheap and have been hosting an invidious instance with it for a while now. But, since I couldn't actively maintain and bear the server costs, am willing to transfer the DOMAIN ownership free of cost to any of the active contributors or existing instance owners who are interested in taking ownership of this domain for good use (be it hosting another invidious instance for public use or in any way that adds value to this project).

Domain Expiry date: Aug 7, 2025

If interested, please contact me on my mail: wapfalls [at] gmail.com

Thanks!

**Comment by hackerncoder** [comment]
If no one else is interested I might take it.

**Comment by Perflyst** [comment]
@hackerncoder do you want to host an invidious instance on it? otherwise I would suggest you could just redirect it to https://redirect.invidious.io/

**Comment by hackerncoder** [comment]
Maybe. Possibly hosting an instance that could auto install PRs. Otherwise I can always do that.

**Comment by wapfalls** [comment]
@hackerncoder, can you please mail me over to my id mentioned above?

**Comment by hackerncoder** [comment]
@wapfalls I think I did so? Haven't heard from you.

**Comment by hackerncoder** [comment]
Update: I think I have the domain now. I'll set it up to redirect to redirect.invidious.io for now (btw, could/should we add something so I can make the redirect say "invidious.site is closed for now" instead of invidio.is being down?)
