### ISSUE TITLE
[Enhancement] Autodetect browser language

### ISSUE THREAD

**Issue by Elaborendum** [iv-org/invidious#2074]
**Is your enhancement request related to a problem? Please describe.**

Just a minor (and maybe specific?) incovenience as it is tedious to have to change the language of every instance visited, since some don't work from time to time and to avoid overloading just one instance (plus, they change a lot, one instance might go down or be down for a few days). It becomes specially annoying if you clear cookies constantly.

Maybe it could also help discover that Invidious is actually localized in the user's language.

**Describe the solution you'd like**

Invidious should automatically detect the browser language and display itself in it if available.

**Describe alternatives you've considered**

Whitelist available instances from the cookie deletion and add the new ones as they come.

**Comment by SamantazFox** [comment]
Good idea! We'll see what we can do :)

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
