### ISSUE TITLE
[Bug] The hitbox for the progress bar on the YouTube player style is far too small

### ISSUE THREAD

**Issue by sofoxe1** [iv-org/invidious#2080]
**Is your enhancement request related to a problem? Please describe.**

when i login to account on https://invidious.048596.xyz and enable javascript progress bar change and it is hard to hit it

**Describe the solution you'd like**

want to know how to get normall bar without log out or disabling javascript

**Describe alternatives you've considered**

try different instance on https://iteroni.com same
**Additional context**

![bar](https://user-images.githubusercontent.com/22683778/118198985-91fbbc00-b441-11eb-88e0-57ce7b18a042.png)

**Comment by syeopite** [comment]
Just go to preferences and change the player style option from Youtube to Invidious. 

And if you don't mind me asking in what way is it difficult to hit?

**Comment by sofoxe1** [comment]
> Just go to preferences and change the player style option from Youtube to Invidious.
> 
> And if you don't mind me asking in what way is it difficult to hit?

i don't know how to do it properly :
(in full screen)
on invidious style on invidious  bar is about 31 pixels and it is in down part of screen 
on youtube bar is about 28  pixels and when part of video i marked you have even more space to point bar
on youtube style on invidious bar is less than 8 pixels

**Comment by syeopite** [comment]
Ah I think I understand now. Thanks for explaining!

**Comment by Pablete1234** [comment]
Adding ontop of this, currently the buttons overlap the actual slider, in inspect-element this is how it shows:

![image](https://user-images.githubusercontent.com/11789291/119329639-ba778780-bc85-11eb-8ecc-ff44ad6d7118.png)
