### ISSUE TITLE
[Bug] Said to paste this on the bug reports so that's what I'm doing

### ISSUE THREAD

**Issue by BrainstormSurge** [iv-org/invidious#2082]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-14T04:19:42Z`
Route: `/watch?v=LmUrOXKHZiM`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment]
Hi! Thanks for reporting this issue. It however seems that the instance you are using is running an old version of invidious at 42be132. This is also seems to be a duplicate #1996.
