### ISSUE TITLE
How to add custom messages to top?

### ISSUE THREAD

**Issue by RiversideRocks** [iv-org/invidious#2084]
How can I add a custom message to the top of my instance? Would this violate AGPL?

**Comment by syeopite** [comment]
You can set a string for the banner text in config.yml.

`banner:  text`

**Comment by RiversideRocks** [comment]
Is HTML supported?

**Comment by syeopite** [comment]
Yes

**Comment by syeopite** [comment]
Closing the issue. Let me know if you have any other questions
