### ISSUE TITLE
[Bug] Nil assertion failed (NilAssertionError)

### ISSUE THREAD

**Issue by kryzar** [iv-org/invidious#2097]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-19T17:03:19Z`
Route: `/watch?v=vSAa_ls9grQ`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by rmorabia** [comment]
+1, getting the same issue.

```
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-19T17:38:29Z`
Route: `/watch?v=gGblzUc_Z1I`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>
```
