### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gcorbin** [iv-org/invidious#2103]
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-05-20T21:25:14Z`
Route: `/watch?v=O0znKAKlf2c`
Version: `2021.04.10-42be132 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment]
Duplicate of #1996. This should have been fixed, so ask the instance maintainer to update.
