### ISSUE TITLE
Status of health stats

### ISSUE THREAD

**Issue by 4caoi** [iv-org/invidious#2106]
Is there any plan to revive the monitor data previously provided by the api? Currently instances.json is returning null on monitor:

...  "type": "https",
 "uri": "https:// yewtu. be",
 "monitor": null ...

where as previously it provided information like "success":

...  monitor: {
monitorId: 782758961,
createdAt: 1558969602,
statusClass: "success", ...

I have removed the criteria from my response parsing, but would like to know if I should make it permanent.

**Comment by SamantazFox** [comment]
instances.json is returning null on monitor`instances.json`? Do you mean in the `instances-api`? If yes, can you please re-open

**Comment by SamantazFox** [comment]
> Currently instances.json is returning null on monitor

Can you please copy your issue to the [`instances-api` issues page](https://github.com/iv-org/instances-api/issues)?
