### ISSUE TITLE
[Meta] Check the "cookies" configuration setting

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2109]
The ```cookies``` configuration setting need to be checked.

We have to make sure that it doesn't override the cookies set by invidious itself since this will break stuff.

Related, kinda: https://github.com/iv-org/invidious/issues/1965#issuecomment-812619830

**Comment by SamantazFox** [comment]
I'm wondering why you'd want to enforce that. I think that keeping a way to override cookies in the config may be nice (so instance admins can deploy a quick fix if something like the consent cookie happens again), but we should in exchange document which cookies are used by invidious.

**Comment by SamantazFox** [comment]
Also, regarding what @tenpura-shrimp said:

> Comments sets the required cookie here:
> https://github.com/iv-org/invidious/blob/master/src/invidious/comments.cr#L88
> 
> But then you overwrite it here:
> https://github.com/iv-org/invidious/blob/master/src/invidious/helpers/utils.cr#L12

It is not overwritten. The code at `utils.cr` appends the consent cookie to the cookie header provided to the function, and then it prepends the cookies from the config.

**Comment by TheFrenchGhosty** [comment]
>I'm wondering why you'd want to enforce that. I think that keeping a way to override cookies in the config may be nice 

Some cookies are critical

>It is not overwritten. The code at utils.cr appends the consent cookie to the cookie header provided to the function, and then it prepends the cookies from the config.

Because it was fixed in https://github.com/iv-org/invidious/pull/1973

**Comment by SamantazFox** [comment]
> > It is not overwritten. The code at utils.cr appends the consent cookie to the cookie header provided to the function, and then it prepends the cookies from the config.
> 
> Because it was fixed in #1973

Oh, my bad, didn't see that the message was that old :X

**Comment by saltycrys** [comment]
That preference is handled here: https://github.com/iv-org/invidious/blob/00425670d7ad5b334d4f6ec060acea0f9a53b76f/src/invidious/helpers/utils.cr#L14-L16
As you can see it only adds cookies.
