### ISSUE TITLE
[Feature request] Frame by frame skipping

### ISSUE THREAD

**Issue by L1pE** [iv-org/invidious#2113]
The Youtube player allows to skip frame by frame using the "," and "." hotkeys to skip backwards and forwards respectively when paused. The Invidious player does not seem to support this.

It'd be nice if the Invidious player supported frame skipping via those same hotkeys.

**Comment by SamantazFox** [comment]
That's being worked on!

**Comment by seabass-labrax** [comment]
This already seems to be working for me with Firefox 102.10.0esr.
