### ISSUE TITLE
Link to instances.invidious.io/Invidious-Instances.md returns 404

### ISSUE THREAD

**Issue by antoooooooooooonie** [iv-org/invidious#2139]
**Describe the bug**
Hello, I was just checking out this project and wanted to see a demo. I clicked on the link to instances.invidious.io in the About section and it returned a 404.

**Steps to Reproduce**
1. Click on link to instances.invidious.io
2. It returns 404

**Logs**

```
$ curl https://docs.invidious.io/Invidious-Instances.md -I
HTTP/2 404
content-language: en
content-type: text/html; charset=utf-8
date: Wed, 09 Jun 2021 08:55:25 GMT
etag: W/"741-Kua68DCYvy4es3PWglg2f9+kn+k"
referrer-policy: same-origin
server: Caddy
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: deny
x-ua-compatible: IE=edge
x-xss-protection: 1; mode=block
content-length: 1857
```

**Screenshots**

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/71470021/121324857-6a4d2600-c911-11eb-9a65-adedb4b93f6e.png">

**Comment by syeopite** [comment]
Yeah we've been having some issues it. I'll recommend just [visiting the documentation repo on github instead](https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md). It's a lot more stable.

**Comment by unixfox** [comment]
It's now fixed.
