### ISSUE TITLE
[Bug] Incorrect search behavior if the query contains non-English letters or words.

### ISSUE THREAD

**Issue by noname946** [iv-org/invidious#2140]
**Describe the bug**
When trying to do a video search, if the query contains non-English letters or words, the search instead of what I entered in the query returns garbage in the search results.
And this is the case with all queries that contain non-English letters or words, which makes it almost impossible to use the search.
What's strange is that not all instances are affected by this problem, but only a certain part of them.
Attempts to experiment with the search filter parameters did not help either, the search results are still garbage.

Instances that are affected by this issue:
invidious.snopyta.org
yewtu.be
invidious.silkky.cloud

Instances that are not affected by this issue:
invidious.048596.xyz
inv.riverside.rocks

**Steps to Reproduce**
Try to enter a search, for example "Фильмы ужасов".

**Expected behavior:**
In the search results should appear videos, one way or another related to the horror genre.

**Actual behavior:**
The search results return "garbage" videos that have absolutely nothing to do with the horror genre.

**Screenshots**
Screenshot 1 which was taken on the instance yewtu.be is affected by this issue and is the actual behavior.
![test](https://user-images.githubusercontent.com/79874964/121374035-d9417380-c93f-11eb-8ad8-1bee7ff7dedb.png)
Screenshot 2 which was taken on the instance inv.riverside.rocks is not affected by this issue and is the expected behavior.
![test2](https://user-images.githubusercontent.com/79874964/121374049-dcd4fa80-c93f-11eb-885b-aa8c21c0d032.png)
**Additional context**
 - Browser: Firefox ESR 78.11.
 - OS: Windows 10.

**Comment by Mennaruuk** [comment]
Can confirm with Arabic too (باتلفيلد)
![5cqlro](https://user-images.githubusercontent.com/52135169/121460252-a5377400-c97a-11eb-9a24-688bc2352f0d.gif)

**Comment by SamantazFox** [comment]
Thanks for reporting this :) NB: Snopyta seems to work for me.

For the record, hare are the different instance versions, at the time of report:
```
invidious.snopyta.org   => 2021.05.26-4a45d10 @ master
yewtu.be                => 2021.06.08-c942a88 @ master
invidious.silkky.cloud  => 2021.06.10-a6e38e2 @ master
invidious.048596.xyz    => 2021.05.13-996dd1a @ serving12
inv.riverside.rocks     => 2021.05.26-4a45d10 @ master
```

And btw @tenpura-shrimp, your instance is not properly redirecting to HTTPs, and will need to be updated soon if you wanna stay in the official list :)

**Comment by noname946** [comment]
It seems that the problem is related to an attempt to convert the received request from UTF-8 and then transmit the converted version of YouTube.
As another test, I decided to search for "+100500".
Search results on instance yewtu.be.
![test](https://user-images.githubusercontent.com/79874964/121702243-ff971880-cad1-11eb-93e5-afdce5a19e6b.png)
Search results on instance inv.riverside.rocks.
![test2](https://user-images.githubusercontent.com/79874964/121702341-13db1580-cad2-11eb-918e-406ad873cc69.png)
As you can see, in screenshot 1, although videos with partially matching the search query are displayed, they have strange name "%2B100500".
If memory serves me correctly, "%2B" is the result of conversion from UTF-8 using some algorithm.
Because of which, I have an assumption that the search is behaving incorrectly due to the fact that after processing the search request by an instance, it tries to send it to YouTube no longer in the form "+100500", but in the form "%2B100500", from this videos with a similar name appear in search results.

**Comment by SamantazFox** [comment]
> If my memory serves me, "%2B" is the result of converting the "+" sign from UTF-8 by some algorithm.

It's called URL encoding ^^ Basically, some characters (like `./@?&=`) are reserved in URLs, and must be converted in order to respect the URL specification.


> @SamantazFox Do you think this could be related to the fact that #1985 changed something with the encoding on the search endpoint?

This is very likely, yep... I'll investigate and try a fix tonight or tomorrow.

**Comment by SamantazFox** [comment]
Patch live at https://test.invidious.io

@Mennaruuk @noname946 can you please try it? I'll make a PR in the meantime.

**Comment by Mennaruuk** [comment]
Search results are relevant again!!! Thank you sooo much.

**Comment by SamantazFox** [comment]
@Mennaruuk you're welcome :)

**Comment by noname946** [comment]
@SamantazFox Checked the search for "+100500" and "Фильмы ужасов", now the search results match the expected behavior and there are no more "garbage" videos.
