### ISSUE TITLE
[Bug] All thumbnails are generic

### ISSUE THREAD

**Issue by Mennaruuk** [iv-org/invidious#2146]
**Describe the bug**

The thumbnail behind the play button is the generic deleted video thumbnail. Video still plays fine.

**Steps to Reproduce**
1. Go to https://yewtu.be/watch?v=E3Huy2cdih0
2. Check out thumbnail

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/52135169/121749407-9f57a500-cad8-11eb-80bd-71daa1402435.png)

**Additional context**

So this only happens after clicking on a video to watch. So thumbnails in search results are okay. But when I click on a video, the thumbnail behind the player is the generic error one.
![image](https://user-images.githubusercontent.com/52135169/121749569-dfb72300-cad8-11eb-911a-ab5e4d3f677e.png)

**Comment by unixfox** [comment]
I can replicate this odd bug, YouTube changed something with their HTML.

**Comment by TheFrenchGhosty** [comment]
Thumbnails work perfectly on my instance.

**Comment by unixfox** [comment]
Seems to be an issue with my instance. I'll try to fix it later.

**Comment by syeopite** [comment]
I think it's something related to HTTP3. The same issue is present when using Invidious-quic-proxy.
