### ISSUE TITLE
[Enhancement] Disable FLoC on chrom* browsers via response header

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2153]
Add the `Permissions-Policy` response header to tell chrom*-based browsers to not use FLoC, an in-browser tracking/profiling anti-feature.

in essence: `Permissions-Policy: interest-cohort=()`

References:
* https://twitter.com/defcon/status/1404100959366639625
* https://blog.runcloud.io/google-floc/

**Comment by TheFrenchGhosty** [comment]
Done in #2168
