### ISSUE TITLE
[Enhancement] Disallow: /watch in robots.txt again

### ISSUE THREAD

**Issue by MrPaulBlack** [iv-org/invidious#2156]
**Is your enhancement request related to a problem? Please describe.**

Its it really weird that this commit 6c19f0f2420fe6845250e971e9c8372165b2b5fb allowed the /watch path for crawlers and bots in the robots.txt again. Because I switched on my server to display the Trending tab first, Google starts indexing videos from this category and follows the video recommendation on these videos and so on. Basically it starts indexing every video it can find. (I got 2500+ request from google in only the last 24h because of that)

**Describe the solution you'd like**

A solution would be to add the ```Disallow: /watch``` line in /assets/robots.txt again.

**Describe alternatives you've considered**

Is there a reason for allowing the /watch path?

**Additional context**
try ```site:youtube.paulgo.io``` in a google search to see all the indexed videos by google

![image](https://user-images.githubusercontent.com/38733246/121858814-487be680-ccf7-11eb-8417-9fd5606915d8.png)

**Comment by unixfox** [comment]
The robots.txt is available here: https://github.com/iv-org/invidious/blob/master/assets/robots.txt. Feel free to create a pull request with your requested changes.

**Comment by MrPaulBlack** [comment]
PR in #2157

**Comment by syeopite** [comment]
Merged
