### ISSUE TITLE
Would like to provide my server for invidious instance/redirect

### ISSUE THREAD

**Issue by vdbhb59** [iv-org/invidious#2159]
Hi Team,
I am new to this, but I have a server space, and would like to contribute towards the open source invidious. Kindly let me know how I can do that, and I would love to host.

Thanks,

FLOSSbOxIN

**Comment by hackerncoder** [comment]
If you want to host an invidious instance, you should see our documentation: https://github.com/iv-org/documentation#for-administrators

**Comment by SamantazFox** [comment]
Hello! If you want, you can run a public invidious instance, to help dispatching the traffic!

Some pre-requisities, if you want to do so:
* Some basic linux and postgreSQL administration knowledge (docker is a plus)
* A good internet connexion (i.e preferably having a server/VPS in a datacenter) 
* A server with at least 3G of RAM
* A domain name, with a TLS certificate

Then, you'll have to keep your instance up to date at least once a month in order to stay in the public instances list.

**Comment by vdbhb59** [comment]
Thanks. I will look into the documents and the criteria. :)

**Comment by vdbhb59** [comment]
Err one Q, and probably stupid one. Would I be needing much "disk space"?
Again, do not take me up for a beat, asking since this is fully new for me.

**Comment by hackerncoder** [comment]
Hey @SamantazFox, the docs say 2G RAM. If thats wrong it should probably be fixed.

**Comment by vdbhb59** [comment]
That is there, if you are saying 3GB, and probably since the change it may have increased too, but by disk space I did not mean RAM/SWAP, instead I meant hard disk space, if any required. As that is not mentioned anywhere (if needed or not).

**Comment by unixfox** [comment]
As long as you do an automatic cleanup every day (see https://docs.invidious.io/Database-Information-and-Maintenance.md), you shouldn't need more than 10GB of free disk space.

**Comment by vdbhb59** [comment]
Thanks, that helps me. I have 20GB extra space on my Linux and 50GB on Windows. Hope, I can understand the setup and work it out.

**Comment by unixfox** [comment]
Feel free to close this issue if you got all the necessary info. We are also on Matrix if you need a more direct help from us: https://matrix.to/#/#invidious:matrix.org

**Comment by vdbhb59** [comment]
Closing it out as of now. But will reach out here, rather than Matrix. If XMPP was there would have reached there, but not Matrix. I do not trust it mate.

**Comment by unixfox** [comment]
If you don't trust matrix, I think we are soon going to be also on librachat with the channel name invidious, but we are waiting for a bridge between the IRC channel and the matrix channel.

**Comment by SamantazFox** [comment]
> Hey @SamantazFox, the docs say 2G RAM. If thats wrong it should probably be fixed.

Yeah. Crystal compilation takes ~2G of RAM, so you should have >2G installed and 2G free.
