### ISSUE TITLE
[Feature request] Download link in HTTP only

### ISSUE THREAD

**Issue by Computershik73** [iv-org/invidious#2165]
Hello! I am developing a YouTube app for some old devices that do not support https videos online watching (only downloading). I will be very grateful if the API will also provide HTTP links to videos. I know, YouTube supports it, but via an old browser, and it is too difficult to decrypt the link. Please. 
At this moment, I have to proxify videos via http proxy, whick causes them to lag and buffer.

**Comment by unixfox** [comment]
Can you prove that youtube support HTTP links and that you can load it fine?

I tried to force the link of video stream from HTTPS to HTTP and I got a 403 HTTP error so I don't think this will work.

**Comment by Computershik73** [comment]
> Can you prove that youtube support HTTP links and that you can load it fine?
Nokia N8 on Symbian Belle Refresh with "Android 4.1" useragent plays videos online and gets http links.
the user-agent is : "Mozilla/5.0 (Linux; Android 4.1.2; GT-P3110; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.1.4 Mobile Safari/535.1 3gpp-gba"

**Comment by Computershik73** [comment]
It also works with Windows Phone 8 UserAgent. Here is the proof!
https://vikamobile.ru/images/_7ZwyYuious.jpg

**Comment by betabux** [comment]
I have just tested the app with my 808 PureView (Delight 1.5) and it works flawlessly.

**Comment by betabux** [comment]
http access would greatly benefit Symbian phone users as they would gain access to more content. Due to the restrictions on the old OS video playback is achieved by http access only and this limits what content we have access to. I believe many if not all users of the Symbian platform would benefit from gaining access to invidious if http access was granted. On behalf of all the diehard Symbian fanatics please allow this option for us, we will be eternally grateful 🙏🏻

**Comment by unixfox** [comment]
> http access would greatly benefit Symbian phone users as they would gain access to more content. Due to the restrictions on the old OS video playback is achieved by http access only and this limits what content we have access to. I believe many if not all users of the Symbian platform would benefit from gaining access to invidious if http access was granted. On behalf of all the diehard Symbian fanatics please allow this option for us, we will be eternally grateful 🙏🏻

We aren't against adding this feature, it's just that it's not a priority for the developers of Invidious.
If you want to add this feature the Invidious code is open source and you can contribute to it. That's the beauty of open source :)

**Comment by betabux** [comment]
I am happy to hear that you are not against it 👍🏻
I appreciate its not a priority for the developers of invidious.
Thank you for your consideration

**Comment by taraletti** [comment]
would be nice to have that feature, but understandable what you say too. It's interesting to work YouTube through invidious in Symbian ^3 phones

**Comment by Computershik73** [comment]
I am the author of the issue and the developer of SymTube, a Symbian and MeeGo YouTube app that uses Invidious instances. I have read what you had wrote above and just want to repeat that users will be grateful for adding this functionality.

**Comment by J34N-V3ND3TT4** [comment]
http access would benefit Symbian phone users and could be a start to ressurect the capabilities of this OS.
By now, winding videos can lag because the video is proxified via private server maintained by the developer of SymTube (https => http). Http links to videos are needed for old devices.
After Invidious's developers add them, the proxy can be disabled.
Please, look to the Symbian users. We are still here!

**Comment by unixfox** [comment]
I don't want to be rude, but please stop commenting if it doesn't help in adding this feature.

We already know that a community is seeking for this feature, and "polluting" this issue will make the job harder for future developers that would want to get useful information in order to develop this feature.

**Comment by unixfox** [comment]
Just wanted to add that if you run Invidious normally, so in HTTP, you can just replace the googlevideo URLs to the URL of invidious.

For example, this URL: `https://r1---sn-cxab5jvh-cg0ek.googlevideo.com/videoplayback?expire=1628918814&ei=vv8WYb6ZJ8L_gQecppCADA&&host=r1---sn-cxab5jvh-cg0ek.googlevideo.com` should be converted to `http://localhost:3000/videoplayback?expire=1628918814&ei=vv8WYb6ZJ8L_gQecppCADA&&host=r1---sn-cxab5jvh-cg0ek.googlevideo.com`. Then any HTTP only clients will be able to watch the video.

The traffic will be proxified through invidious, but that's fine.

**Comment by Computershik73** [comment]
> Just wanted to add that if you run Invidious normally, so in HTTP, you can just replace the googlevideo URLs to the URL of invidious.
Can we use this with other invidious instances, i guess? And  I did not find any invidious instances that allow to connect by HTTP. My server is not so powerful to launch it by itself, unfortunately. And even worse, the SSL certificate that is used on all instances is not supported on Symbian (it is too new), so I proxify the traffic through my server.

**Comment by unixfox** [comment]
Unfortunately no you can't do that, all the public instances are forcing to HTTPS because security.

I was talking about if you host invidious locally, but I guess if you are already proxify the traffic through your server, then you already have the same result as having the traffic through a local invidious instance.

**Comment by syeopite** [comment]
Well there is http://iteroni.com, but it isn't on the official instance list so we can't exactly assert it's quality. Though last time I checked, it does support http.

**Comment by Computershik73** [comment]
> Well there is http://iteroni.com, but it isn't on the official instance list so we can't exactly assert it's quality. Though last time I checked, it does support http.

yes, I checked it on my Nokia 808 and iPhone 4, it opens , but the videos do not play still.

**Comment by unixfox** [comment]
> > Well there is http://iteroni.com, but it isn't on the official instance list so we can't exactly assert it's quality. Though last time I checked, it does support http.
> 
> yes, I checked it on my Nokia 808 and iPhone 4, it opens , but the videos do not play still.

It's an entirely different problem here. Your initial feature request is getting video streams URLs with HTTP, syeopite gave you a workaround. You just have to apply the method that I talked here https://github.com/iv-org/invidious/issues/2165#issuecomment-898768295 but using the invidious instance http://iteroni.com.

We aren't going to support Symbian devices (or any VERY old devices) on the invidious frontend sorry, but we can try to provide streams URLs with HTTP on the invidious API.

Please clarify if that's the correct feature request that you are asking.

**Comment by Computershik73** [comment]
> but we can try to provide streams URLs with HTTP on the invidious API.
> 
> Please clarify if that's the correct feature request that you are asking.

Yes, this is the exact feature our community of Symbian users ask for.

**Comment by unixfox** [comment]
> > but we can try to provide streams URLs with HTTP on the invidious API.
> > 
> > Please clarify if that's the correct feature request that you are asking.
> 
> Yes, this is the exact feature our community of Symbian users ask for.

Can you explain how you got the HTTP links for googlevideo in the first place?
Explain how you manage to do that in https://github.com/iv-org/invidious/issues/2165#issuecomment-863261429

**Comment by Computershik73** [comment]
> Can you explain how you got the HTTP links for googlevideo in the first place?
> Explain how you manage to do that in [#2165 (comment)](https://github.com/iv-org/invidious/issues/2165#issuecomment-863261429)

Sure, 
1) I changed Symbian system browser's default user agent to Windows Phone 8 system standard useragent using another app (but it can also be changed by modifying some system files)
2) I tapped on the video before the page loaded completely, it opened the video I selected earlier and it started playing.
I attach my useragent string here.

**Comment by unixfox** [comment]
Closing as YouTube is certainly not providing any HTTP link anymore and is now locking down even more the ability to download videos from 3rd party clients. So we can't do anything anymore.
