### ISSUE TITLE
[Bug] Search results popping up when they normally shouldn't

### ISSUE THREAD

**Issue by tennessean** [iv-org/invidious#2170]
**Describe the bug**

I'm not sure if it's actually a bug, but I'll treat it as one unless I'm told otherwise.  Anyhow, whenever I get onto an Invidious instance, I prefer to set it up so that no videos are showing up on the initial page.  Previously, I had found that simply searching with "" (as in, *only* the quotation marks) tended to work well for my purpose, as shown in Image 1 under the Screenshots section of this post. This lines up quite well with how YouTube displays the same search "term" (if you will), as seen on Image 2 (specifically, the "No results found" message).

However, as of late (probably some time around the early June updates or thereabouts), the same search term will instead pull up various videos, as shown on Image 3.

I've tried other symbols that normally would give the same YouTube "No results found" message, but videos would pop up regardless of what I use.

As such, I would _**hugely**_ appreciate it if I were somehow able to have the "no videos" setting restored on Invidious instances, as that would greatly improve their usability back to what it was before the change.

**Steps to Reproduce**

(1.) Go onto YouTube, type "" into the search bar, and hit "Enter".
(2.) Go onto an Invidious instance whose most recent update was **before** June 2021 and repeat the process.
(3.) Go onto an Invidious instance that was most recently updated in June 2021 or later and repeat the process.
(4.) Compare the results on all three instances.

**Screenshots**

Image 1:

![Capture1](https://user-images.githubusercontent.com/40572131/122465398-ab7eaf00-cf7d-11eb-8aa7-37c427bd0764.PNG)

Image 2:

![Capture3](https://user-images.githubusercontent.com/40572131/122465510-ce10c800-cf7d-11eb-80a2-26047d547b00.PNG)

Image 3:

![Capture2](https://user-images.githubusercontent.com/40572131/122465829-26e06080-cf7e-11eb-854a-f699ca851607.PNG)

**Additional context**

It seems to occur on multiple browsers that I've tried it on, and on multiple OSes (Windows, iOS, etc.), suggesting that there's something in the codebase settings themselves that could be causing this.

Hopefully I've explained things about as well as I could.  If not, please let me know in the comments.  Thanks!

**Comment by syeopite** [comment]
Related to #2140 and possibly fixed by #2155

Also have you tried the newish search-engine-like page? It might suit your needs better than an empty result page.

**Comment by SamantazFox** [comment]
> possibly fixed by #2155

Yep, that should fix it. The problem was un-necessary encoding of the query, leading to weird results, ad in #2140

**Comment by SamantazFox** [comment]
Fixed by #2155
