### ISSUE TITLE
[Bug] Invidious fails to upgrade: Error: undefined method 'from_client_headers' for HTTP::Cookies.class

### ISSUE THREAD

**Issue by RiversideRocks** [iv-org/invidious#2175]
**Describe the bug**
Invidious fails to update.

**Steps to Reproduce**
1. Update + install shards (shards update && shards install)
2. crystal build src/invidious.cr --release

-->

**Logs**
```
# crystal build src/invidious.cr --release
Showing last frame. Use --error-trace for full trace.

In src/invidious/jobs/bypass_captcha_job.cr:115:37

 115 | cookies = HTTP::Cookies.from_client_headers(headers)
                               ^------------------
Error: undefined method 'from_client_headers' for HTTP::Cookies.class
```

**Screenshots**

**Additional context**

Ubuntu 20.04 @ 2021.06.18-96faa9d

**Comment by syeopite** [comment]
Invidious is now on Crystal v1.0.0 upgrade to that and Invidious should build.

**Comment by RiversideRocks** [comment]
Tried that, no idea why this is happening:
```
E: Failed to fetch https://dl.bintray.com/crystal/deb/crystal_1.0.0-1_amd64.deb  403  Forbidden [IP: 34.223.179.172 443]
```
Sorry, I'm not great with linux.

**Comment by syeopite** [comment]
Bintray has shutdown last month unfortunately. Just go ahead and uninstall Crystal via apt and [follow the instructions here to reinstall it. ](https://crystal-lang.org/install/on_ubuntu/)

**Comment by RiversideRocks** [comment]
Fixed by using Crystal's setup install script, you guys are lifesavers thank you!
