### ISSUE TITLE
[Bug] Video used for CAPTCHA check is selectively allowed

### ISSUE THREAD

**Issue by ItsSt0ne** [iv-org/invidious#2181]
In #2131 I mentioned having an issue with Anti-Captcha requests not being sent, and have diagnosed the issue. I'm not certain of whether or not this is an intentional measure by Google, but the [video](https://www.youtube.com/watch?v=jNQXAC9IVRw&gl=US&hl=en&has_verified=1&bpctr=9999999999) and [channel](https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A) hardcoded into the bypass job are being selectively allowed.

This means that my instance does not believe it is blocked, and therefore won't contact Anti-Captcha. There will be no output in logs explaining what happened, at least on Warn. If this hardcoded URL is changed to one that is blocked, the bypass job runs as expected.

**Steps to Reproduce**
1. Run invidious with configuration for anti-captcha
2. Attempt to access any video that isn't selectively allowed
3. Access is denied, no error in logs, captcha bypass job isn't run past the check

There are three options that come to mind for fixing this. Easiest would be to simply change the hardcoded link, but then Google may block that. Could also make it another configurable option, low-user instances wouldn't need to worry about changing it, and it would be up to administrators of larger instances to change it if this error occurs to them. The most robust solution would probably be to try and directly use a URL that is blocked, after it is blocked.

**Comment by unixfox** [comment]
I've doubts that it is "selectively allowed", it's just that Invidious has a cache of it. If you clear the videos postgresql table, does it still work or is the video blocked?

**Comment by SamantazFox** [comment]
Oooh, that's possible! Thanks for taking the time to investigate :)

> I've doubts that it is "selectively allowed", it's just that Invidious has a cache of it. If you clear the videos postgresql table, does it still work or is the video blocked?

AFAIK, the bypass job doesn't use the database cache. It even uses an old URL and does HTML scraping.

**Comment by unixfox** [comment]
What we could do it's to activate the anticaptcha mechanism on the video URL when the error `Could not extract video info. Instance is likely blocked.` is returned.
We should have some sort of lock though so that we don't launch hundreds of anti captcha validation processes.

**Comment by SamantazFox** [comment]
> What we could do it's to activate the anticaptcha mechanism on the video URL when the error `Could not extract video info. Instance is likely blocked.` is returned.

Yeah, though I'd really like to see what kind of error we'll get once we move the entire scraping to the youtube internal API.

> We should have some sort of lock though so that we don't launch hundreds of anti captcha validation processes at the same time.

Crystal fibers can do that, yep ;)

**Comment by unixfox** [comment]
> > What we could do it's to activate the anticaptcha mechanism on the video URL when the error `Could not extract video info. Instance is likely blocked.` is returned.
> 
> Yeah, though I'd really like to see what kind of error we'll get once we move the entire scraping to the youtube internal API.
Like discussed on matrix, we won't get any for a very long time.

**Comment by ItsSt0ne** [comment]
> I've doubts that it is "selectively allowed", it's just that Invidious has a cache of it. If you clear the videos postgresql table, does it still work or is the video blocked?

The result is the same. 

Additionally, when doing `curl -s https://www.youtube.com/watch?v=jNQXAC9IVRw&gl=US&hl=en&has_verified=1&bpctr=9999999999 -4` (the hardcoded test URL) from my instance's host, I do not get Google's /sorry/ page.

When doing `curl -s https://www.youtube.com/watch?v=T3EllvNBYj0&gl=US&hl=en&has_verified=1&bpctr=9999999999 -4` (a different, blocked video) I get the "The document has moved" page. 

Thank you both for replying so quickly.

**Comment by SamantazFox** [comment]
I realize that I should have posted the Matrix exchange in here. Well, here is the link: https://github.com/iv-org/invidious/issues/2131#issuecomment-864442793

**Comment by unixfox** [comment]
@ItsSt0ne If you know how to build crystal from source you can test this PR: https://github.com/iv-org/invidious/pull/2204
