### ISSUE TITLE
[Bug] any automated or semi automated packaed installs currently working?

### ISSUE THREAD

**Issue by controlfreakstudio** [iv-org/invidious#2186]
everything I've tried is breaking on crystal.

ive tried inividious_updater
yunohost regular
yunohost forcing the latest
tried installing crystal first before the above, they all just bomb out at crystal.

is there anything semi packaged working?

**Comment by unixfox** [comment]
Hello we don't support yunohost. Please ask for help on the dedicated yunohost github repository instead.

On our installation guide we offer a Docker guide for an easy installation: https://docs.invidious.io/Installation.md#docker

**Comment by controlfreakstudio** [comment]
OK but the docker page had red text that says depricated and do not use...

**Comment by unixfox** [comment]
> OK but the docker page had red text that says depricated and do not use...

No it's not Docker that is depreciated but Docker hub, a repository for images. In the example we provide another repository called "quay" so you must use this one.
