### ISSUE TITLE
[Bug]  invidious.snopyta.org instance won't play videos

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#2188]
When I try to watch any video on invidious.snopyta.org I get the following error message.

```Could not extract video info. Instance is likely blocked.
next_steps_error_message

next_steps_error_message_refresh
Switch Invidious Instance
next_steps_error_message_go_to_youtube
```

The last 3 rows are links:
https://invidious.snopyta.org/watch?v=[X]
https://invidious.snopyta.org/redirect?referer=%2Fwatch%3Fv%3D[X]
https://youtube.com/watch?v=[X]

*"[X]" is the ID of whatever video I'm trying to play.

**Steps to Reproduce**
Try to watch any video on the invidious.snopyta.org instance

The only instance I've tried that works is ytprivate.com, but they just recovered from a DDoS attack. so I wouldn't call them a reliable alternative.

**Additional context**
Chrome OS

**Comment by SamantazFox** [comment]
mmh, that's weird. You should see that instead
![image](https://user-images.githubusercontent.com/52980486/123000117-6e685180-d3af-11eb-9bb2-f8a2bba9a7c3.png)

**Comment by nathgit** [comment]
It started working again for now, but who knows how long that'll last. I only tend to use the snopyta instance because overall it seems to be more reliable than others, at least in my experience anyway.
