### ISSUE TITLE
[Security Issue] Channel names don't get sanitized for HTML

### ISSUE THREAD

**Issue by Davr1** [iv-org/invidious#2193]
**Describe the bug**
Channel names don't get sanitized for Html. While I myself don't have any experience with XSS, I feel like this could be used for more than just injecting a picture of a big rat.

**Screenshots**
![firefox - 2021 23 06 - 17 50 46 - 1903x967](https://user-images.githubusercontent.com/42148912/123144840-6d412e00-d45c-11eb-9a53-aabef6d60beb.png)
(channel:UCNQLe71USVnxc7kjFyc-Jiw)

**Comment by SamantazFox** [comment]
Indeed, that's quite a problem! Thanks for the report!

**Comment by BlackBunnyHunter** [comment]
![afbeelding](https://user-images.githubusercontent.com/8104256/123274193-98328d00-d503-11eb-9453-ed92244bed72.png)
Big Chungus

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by TheFrenchGhosty** [comment]
@Davr1 I would like to deeply thank you a lot for reporting this problem!

For reporting this (massive) security issue I and most of the organization members would like to reward you with 20$ (in BTC) If you want to receive your reward feel free to send me your BTC address or post it directly in the PR.

Every payment will be, as usual, reflected in the [transparency repository](https://github.com/iv-org/transparency), in our monthly financial reports.

**Comment by Davr1** [comment]
@TheFrenchGhosty `bc1qzunu09k7a74vh525ee0xz8y92u72yyyxzk6p55` this is my first time dealing with crypto, so I hope I don't mess up something lol

**Comment by TheFrenchGhosty** [comment]
@Davr1 Sorry I got busy and completely forgot to send your reward.

Is the address still good?

**Comment by syeopite** [comment]
Ping @Davr1

**Comment by TheFrenchGhosty** [comment]
Ping @Davr1

**Comment by Davr1** [comment]
@TheFrenchGhosty Sorry, I have also completely forgotten about this, and I didn't notice the github emails. Yes, the address is still good.
