### ISSUE TITLE
[Bug] YouTube throtle speed on some videos

### ISSUE THREAD

**Issue by rderensy** [iv-org/invidious#2194]
**Is your enhancement request related to a problem? Please describe.**

Not sure which category to chose, it's not a bug nor an enhancement.
I run a personal instance at home and it's really slow. I has gotten way worse recently, to the point where loading a video when clicking "play" (if it loads at all) takes ~10 sec and when it loads eventually, it plays at 144p instead of 1080p dash (default setting of the instance).

I got a 1Gpbs fiber at home so it definitely shouldn't be slow, the VM is using 500MB out of 2GB available and the CPU is <1% when playing a video. https://yewtu.be with dash enabled loads instantly and buffers the video very quickly. Did I miss-configure something or is google limiting me directly?

**Comment by SamantazFox** [comment]
Have you tried restarting the invidious service (on the sever)?

**Comment by unixfox** [comment]
If you aren't already doing it you should automatically restart invidious every 2 hours. This is due to the instability of Invidious.

**Comment by rderensy** [comment]
Restarting used to do the trick but now it doesn't solve anything.

**Comment by unixfox** [comment]
Could you try to set `enable_quic: false` in the config.yml?

**Comment by rderensy** [comment]
I'll try this, I'll let you know.

I'm starting to think I'm limited by google or my ISP at peak hours because right now at 10 AM CEST, I can play a video in 2160p flawlessly without any pause

**Comment by unixfox** [comment]
If you really want to know if your connection to Google is limited then you could try to download a big video using youtube-dl right now and at the time you think you are getting limited.

Look at the throughput/speed of the download and compare the two results. You may also do multiple tests in order to have better comparison.

**Comment by rderensy** [comment]
I'll try on the evening but for now, it seems very random.

This video via youtube-dl https://youtube.com/watch?v=1LaKH5etJoE and https://youtube.com/watch?v=eY9dXcjkVx8 downloads at ~15 or 25KB/s but https://youtube.com/watch?v=ILHEYblJ7uM and https://youtube.com/watch?v=bVT_yjB6lDg downloads at ~90MB/s

**Comment by unixfox** [comment]
This might be related to https://github.com/ytdl-org/youtube-dl/issues/29326

**Comment by rderensy** [comment]
This looks very similar indeed, they also say what's the problem/give the solution at the end of the thread, and it makes sense that Invidious is impacted and needs to be updated

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by TheFrenchGhosty** [comment]
Note: The youtube-dl solution is here: https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377

**Comment by unixfox** [comment]
@rderensy Would you mind testing this PR https://github.com/iv-org/invidious/pull/2220 if it solves the issue with YouTube throttling the bandwidth of the video?
You will need to patch Invidious in order to test it, if you don't know how to do it I can help with that.

**Comment by rderensy** [comment]
I think I managed to do it (and merging #2217 before), I clicked on tens of random videos from different 4 channels and they all load a 2160p without any buffering. Also, the video page takes slightly longer to load.

Though, clicking on as many video in a short lapse of time made the instance crash once but I'm not sure it's due to this fix.

**Comment by unixfox** [comment]
> I think I managed to do it (and merging #2217 before), I clicked on tens of random videos from different 4 channels and they all load at 2160p without any buffering. Also, the video page takes slightly longer to load.
> 
> Though, clicking on as many video in a short lapse of time made the instance crash once but I'm not sure it's due to this fix.

Could you test again the PR with the new code? I made a HUGE mistake of fetching twice the same data for no actual reason (I forgot to remove a duplicate code).
The latency when loading a video page should be much lower.

**Comment by rderensy** [comment]
It seems better indeed! As far as I can tell, this PR solves the issue, only time will tell if it's truly working or not

**Comment by SamantazFox** [comment]
I'm putting that here for reference, as I don't recall seeing it previously: https://github.com/pytube/pytube/pull/1037

**Comment by simoniz0r** [comment]
Is this fix included in version `2021.07.16-095c894`?  If so, it seems to not be working for me as I am frequently getting throttling and lower resolutions than what are actually available.

**Comment by rderensy** [comment]
No it's not, the PR https://github.com/iv-org/invidious/pull/2220 isn't merged yet

**Comment by rderensy** [comment]
@unixfox @SamantazFox what's the status on this? I've been using the PR https://github.com/iv-org/invidious/pull/2220 for more than a month (since June 29) and everything has been working so far. I updated my instance to https://github.com/iv-org/invidious/pull/2277 and it's not possible to merge #2220 anymore. Is a rebase the only thing that's needed?

**Comment by syeopite** [comment]
Yeah a rebase is all that needs to be done on #2220 for compatibility with Invidious on master.

**Comment by SamantazFox** [comment]
yup, this is planned
