### ISSUE TITLE
[Meta] New issue labels + Removing extra tags from issue title

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2200]
This is a discussion mainly for the organization members (@Perflyst @B0pol @cloudrac3r @hackerncoder @saltycrys @TheFrenchGhosty @syeopite @unixfox) but others are free to give their opinion:

I'd like to know what you think about adding the following labels for the issues/PRs:

* `type:a11y`, for all accessibility-related issues (UX, theme, problems with screen-readers, ...)
* `type:i18n`, for all internationalization/localization-related issues (translations, RTL support, ...)
* `type:player`, for issues that impact the video player itself (video formats, playback controls, captions, ...)

The main idea was automation of our to do list, available here: https://github.com/orgs/iv-org/projects/1, but as it turns out, this feature is extremely limited, so it will only be useful for issues filtering and manual sorting in the To Do list.

---

Also, in order to make issues more readable, I was thinking of removing the `[Bug]`, `[Enhancement]` and alike from issue titles, at it is redundant with labels.

That may also help with the common `[Bug] ` issue (empty title).

**Comment by TheFrenchGhosty** [comment]
>* `type:a11y`, for all accessibility-related issues (UX, theme, problems with screen-readers, ...)
>* `type:i18n`, for all internationalization/localization-related issues (translations, RTL support, ...)

It might be a good idea to use "words" ("accessibility" and "localization") instead of "a11y" and "i18n" or at least have both, I personally never heard of "a11y" before and I guess for "accessibility" sake it might be a good idea to have words instead of abbreviation (?).

However I agree, we need more "types" of issues.

>Also, in order to make issues more readable, I was thinking of removing the [Bug], [Enhancement] and alike from issue titles, at it is redundant with labels.

I personally think they make things a lot more readable when you aren't filtering by labels, I guess this should have its own discussion.

**Comment by SamantazFox** [comment]
> It might be a good idea to use "words" ("accessibility" and "localization") instead of "a11y" and "i18n" or at least have both, I personally never heard of "a11y" before and I guess for "accessibility" sake it might be a good idea to have words instead of abbreviation (?).

The idea is to have something that is short to maximize information density and avoid to clutter the visual space, while being understandable. We still have the label documentation to explain what it means (someone who don't know what "i18n" is have probably no clue about what "internationalization" is either).

If you have an issue with multiple labels, especially long ones, it may become longer than the issue's title (though that problem is less obvious now that we don't priority labels anymore).

for instance, without shortening labels:

`<enhancement>` `<internationalization>` `<acessibility>` `<bounty>` `<bounty:20$>` `<type:client-side>` `<good first issue>` `<help wanted>`

And with short labels (Okay, I went as far as even removing the duplicate bounty label and not adding `type:` on some labels):

`<enhancement>` `<i18n>` `<a11y>` `<bounty:20$>` `<client-side>` `<good first issue>` `<help wanted>`

> I personally think they make things a lot more readable when you aren't filtering by labels, I guess this should have its own discussion.

yeah, I should probably make a separate issue for that.

**Comment by TheFrenchGhosty** [comment]
> <good first issue> <help wanted>

FYI: we don't really use those.

The <bounty> label is personally useful to me since it include all the bounty-related discussion and all the bounties (of every "value")

**Comment by SamantazFox** [comment]
> FYI: we don't really use those.

I do use them, especially the `good first issue` one, as a kind of "reward" for issues that are clear, nicely documented and made by new-comers.

> The `<bounty>` label is personally useful to me since it include all the bounty-related discussion and all the bounties (of every "value")

Yeah, sure. That was only an example. Could have been `<bounty>` `<20$>`, too...

**Comment by SamantazFox** [comment]
So what should we do?

-> Short label names and let the label documentation explain what they mean
-> Long label names (and still label documentation)

**Comment by TheFrenchGhosty** [comment]
Middle-ground?

Basically the current size but maybe simplified a bit?

**Comment by SamantazFox** [comment]
@TheFrenchGhosty I was asking for the new "i18n / internationalization" and "a11y / accessibility" tab that I'd like ot add :)

**Comment by syeopite** [comment]
We should also remove the unfinished label since we've switched to using draft PRs to mark that.

**Comment by SamantazFox** [comment]
> We should also remove the unfinished label since we've switched to using draft PRs instead

That's a good idea :)
