### ISSUE TITLE
A few visual tweaks to make it more usable [Enhancement] 

### ISSUE THREAD

**Issue by TROMsite** [iv-org/invidious#2203]
I have played around with some CSS to make invidious be more usable. It is true that aesthetics are subjective, but some things are more handy in terms of design.

1. The youtube player's seekbar is so thin you can barely skim through  a video. I can rarely use it. Here's how it looks:
![image](https://user-images.githubusercontent.com/38043315/123420740-3b46dd80-d5bc-11eb-9a20-d96314ce47a9.png)
Here's how it looks with some simple CSS:
![image](https://user-images.githubusercontent.com/38043315/123420797-4dc11700-d5bc-11eb-9725-6d66081e7217.png)

The CSS:
```
.video-js.player-style-youtube .vjs-progress-control .vjs-progress-holder, .video-js.player-style-youtube .vjs-progress-control {height: 10px;
margin-bottom: 24px;}
```

2. The popular/trending and such pages. The menu is too close to the videos themselves and at times you may click teh top videos rather than the menu.
![image](https://user-images.githubusercontent.com/38043315/123421006-9678d000-d5bc-11eb-9aea-27e7c1da2f21.png)
With some simple CSS we can make it better:
```
.feed-menu {margin-bottom: 30px;
margin-top: 30px;}
```

I can add more such suggestions if you find them useful ;)

**Comment by unixfox** [comment]
I'm closing this issue because we already have a discussion about UI changes here: https://github.com/iv-org/invidious/issues/1950 and I would prefer that we keep it there.

And for the first, suggestion is tracked in https://github.com/iv-org/invidious/issues/2080. Please continue any discussion related to it on the specific issue.
