### ISSUE TITLE
[Bug] Channels are reported as nonexistent if URL parameters are added

### ISSUE THREAD

**Issue by Elaborendum** [iv-org/invidious#2206]
**Describe the bug**

If you add any URL parameter to the end of a channel URL, Invidious says that the channel does not exist and doesn't apply the setting the URL parameter was meant to toggle. 

**Steps to Reproduce**
1. Go to, for example, invidious.kavin.rocks/channel/UCSMOQeBJ2RAnuFungnQOxLg (the official Blender channel)
2. Add the URL parameter "&dark_mode=false" to the address
3. Reload the page

**Screenshots**

![image](https://user-images.githubusercontent.com/71190696/123476478-63393f80-d5c2-11eb-95db-dafc8e83d449.png)

**Additional context**
- Browser (if applicable): Firefox
- OS (if applicable): Windows 10

**Comment by SamantazFox** [comment]
The first URL parameter should be preceeded by a question mark (`?`), not an ampersand (`&`).

One parameter:  `https://your/url?param1=value1`
Two parameters: `https://your/url?param1=value1&param2=value2`
