### ISSUE TITLE
Don't clip URLs in video descriptions.

### ISSUE THREAD

**Issue by jtagcat** [iv-org/invidious#2218]
**Is your enhancement request related to a problem? Please describe.**
image from `/watch?v=ZFUU59BAILc`
![image](https://user-images.githubusercontent.com/38327267/123545943-32841200-d74a-11eb-8cfa-07104e7f31df.png)
Can't copy a whole section, the links are clipped, ending with '...'

**Describe the solution you'd like**
Show all links in full. They may be clipped in HTML so they don't overflow (yet can still be copied).

**Comment by MathiusD** [comment]
Following the discussions within the associated pull request (#2906), the possibility of don't clips links is not wanted and we advise you to turn to a user script (such as a browser extension that would display the target of the links or equivalent)

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/155603288-11b4b775-fb96-42f4-b06c-0456e30016e9.png)

Increasing it to fit a yt link without extra params would be great

**Comment by MathiusD** [comment]
> ![image](https://user-images.githubusercontent.com/38327267/155603288-11b4b775-fb96-42f4-b06c-0456e30016e9.png)
> 
> Increasing it to fit a yt link without extra params would be great

In this case as mentioned by @SamantazFox in the PR ([here](https://github.com/iv-org/invidious/pull/2906#issuecomment-1041813622)) we can see to increase the size of links displayed (I can submit new PR for this modification [I will keep you informed here as for the previous one])

**Comment by SamantazFox** [comment]
Yeah, we could increase the displayed characters count to 50, and strip the scheme (remove leading `http://` or `https://`)

**Comment by MathiusD** [comment]
I was going for a length that could be set from the instance configuration (since adding this kind of option in the user preferences was more likely to pollute the preferences, as mentioned [here](https://github.com/iv-org/invidious/pull/2906#issuecomment-1041813622)). Maybe it's not useful if you want fixed a constant value for everyone (like the 50 you mention bellow [And yeah, strip scheme is a good idea])

**Comment by SamantazFox** [comment]
I honnestly don't think that adding a config option for that is useful. That's adding way too much complexity to the code for no real benefit (If you need to copy/paste entire youtube descriptions on a daily basis, you can either go for a userscript or use the API).

**Comment by MathiusD** [comment]
I had proposed this to allow to launch some instances with full urls and therefore to allow any instance to set the size of the displayed url. But yes in the case the api is more adapted
