### ISSUE TITLE
[Bug] Search result pagination doesn't handle reserved characters correctly

### ISSUE THREAD

**Issue by foghawk** [iv-org/invidious#2229]
**Describe the bug**

Query parameters are URI-encoded correctly in the URL for the first page of search results, but not in the URL linked to by "Next Page". Reserved characters in the query appear to be interpreted as URI syntax, partially eating the affected search terms.

**Steps to Reproduce**

1. Search for a string containing an ampersand, such as "armstrong & miller show".
2. Click "Next Page".

Expected behavior: search box displaying "armstrong & miller show" and results related to _The Armstrong & Miller Show_ (similar to first page).

Actual behavior: search box displaying "armstrong " and results related to Louis and miscellaneous other Armstrongs.

Other reserved characters are similarly affected; the ampersand is just the most realistic case.

**Additional context**

Affects 2021.06.29-c7eea9b,  2021.06.29-fd313f0, 2021.06.27-67a18dc, 2021.06.25-135ae11, 2021.06.20-5a8825d (all the builds I have been able to test on).

**Comment by SamantazFox** [comment]
Thanks for reporting this issue :)
