### ISSUE TITLE
Order of Mix playlists are messed up

### ISSUE THREAD

**Issue by Discookie** [iv-org/invidious#223]
The order of videos in a Mix playlist changes on every video, and it eventually loops a few videos in.

Example: https://invidio.us/watch?v=HpPG_-hMwxM&list=RDHpPG_-hMwxM (loops 7 videos in)

**Comment by Discookie** [comment]
After playing around with mixes, an update on this:

The order of mix videos changes even on the playlist page. But usually the first ~7 videos stay consistent. The only way to guarantee video order would be to use some persistent state, instead of asking for the mix every time.

https://invidio.us/mix?list=RDH5KL5aqKOH8
The jumping around is more prominent around the 20-video mark.

**Comment by omarroth** [comment]
I don't think there is a very good solution for this. I would very much like to avoid any sort of tracking, which appears to be necessary in order to provide a consistent list of videos. Maybe the `/watch` page should keep track of a list of videos as query params? `&nextVideos=aaaa,bbbbbb,cccc,dddd...`

**Comment by Discookie** [comment]
I don't think it would be sensible to store the next videos in the query params - it would either be too long, or it wouldn't contain enough videos to solve the original problem.

I'd rather collect videos that we watched already in the query params - it would be shorter in most cases, and it would solve the problem of duplicates better.

The other option is to use the data that you do collect already - watch history.  
It would be pretty straightforward to take the start of the mix, and filter out all videos that were played after that one.
