### ISSUE TITLE
[Bug] RefreshChannelsJob: Could not extract JSON (Auto-generated channels)

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#2233]
**Describe the bug**
Auto generated channels are empty (tagged with `Auto-generated by YouTube` on youtube.com)

**Steps to Reproduce**

https://invidious.snopyta.org/channel/UClll_YYK6-qPGFwVHpchFYg
https://yewtu.be/channel/UCgXO9BFQg0nfgQkNDPRGCTQ
https://yewtu.be/channel/UCS82vMzswkB5CM__TfRC4hg

**Logs**
[error] RefreshChannelsJob: UClll_YYK6-qPGFwVHpchFYg : Could not extract JSON. Youtube API returned error 500 with message:<br>"Internal error encountered."
[error] RefreshChannelsJob: UClll_YYK6-qPGFwVHpchFYg fiber : backing off for 00:00:16s

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
