### ISSUE TITLE
playlist videos extra links aren't

### ISSUE THREAD

**Issue by ReNardier** [iv-org/invidious#2250]
see https://yewtu.be/search?q=syntwave+playlist
and then https://yewtu.be/playlist?list=PLEelxuGt2Io5jGNnA44S9lRhclhz7po1U
could you add the "watch on youtube", "audio mode" and "switch invidious instance" buttons on playlist page's videos?
thanks.

**Comment by unixfox** [comment]
for the playlist, there is already `View playlist on YouTube | Switch Invidious Instance`. What do you mean by "audio mode"? A search and a playlist are not a video, so it doesn't make sense to force to audio. You can force audio for every new video in the preferences with `Listen by default` though.

**Comment by ReNardier** [comment]
i meant the youtube(link to the video on youtube), headset(audio mode, aka the &listen=1) and airplane(switch instance) links that appears on regular searches and channels
![these 3](https://user-images.githubusercontent.com/52585505/125605761-a19dbbbe-3e5a-4df6-8df8-d3a4f2c41659.png)
but not on playlists
![aren't here](https://user-images.githubusercontent.com/52585505/125605953-0c1fd0fd-fb87-4649-a200-d5788307d85c.png)

**Comment by ReNardier** [comment]
and i guess i will request for them to be added to the recommended videos

**Comment by syeopite** [comment]
Those are tracked here in #1928

**Comment by ReNardier** [comment]
huh, good to know, hope both of our concerns get addressed pall
