### ISSUE TITLE
[Bug] Invisible watch history when using thin mode

### ISSUE THREAD

**Issue by TotalDarkness-NRF** [iv-org/invidious#2252]
**Is your enhancement request related to a problem? Please describe.**
When using thin mode accessing videos in watch history is not possible.

**Describe the solution you'd like**
Change how history is shown when using thin mode.
Im not 100% familiar with this code but based on my understanding this line causes it to skip rendering the thumbnails and ability to click when using thin mode.
https://github.com/iv-org/invidious/blob/edb37c95e1c9dbf1abf2647fcfcd1453c38124c1/src/invidious/views/history.ecr#L36
I would like to see that it changed to check if it is using thin mode and if it is use the title of the video instead of completly skipping.

**Describe alternatives you've considered**
#2122 
Rewrite of thinmode minus the suggestion to removing it

**Additional context**
Requires an invidious account to save watch history.
Requires at least one video in history.
Requires thin mode on.
Result:
![Screenshot_20210712_161913](https://user-images.githubusercontent.com/63280150/125350742-bba46700-e34e-11eb-8ada-cbc244b4147a.png)

**Comment by SamantazFox** [comment]
Yeah, thin mode definitely needs a rewrite, so does the whole UI...

**Comment by SamantazFox** [comment]
Related: #2122
