### ISSUE TITLE
Opening a link failed, invidious invite me to tell you... [Bug] 

### ISSUE THREAD

**Issue by zebulon-1st** [iv-org/invidious#2253]
**Describe the bug**
When opening a link that directly points to an invidious instance & video, I had an error message inviting me to tell you, instead.

**Steps to Reproduce**
1. Click on / Go to 'https://invidious.fdn.fr/watch?v=xsYXJc-owBE'

**Logs**
Title: `Could not check out a connection in 2.0 seconds (DB::PoolTimeout)`
Date: `2021-07-13T11:58:49Z`
Route: `/watch?v=xsYXJc-owBE`
Version: `2021.07.01-cf619f24 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 2.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:538:9 in 'checkout'
  from src/invidious/helpers/utils.cr:35:14 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Screenshots**
![](https://www.cjoint.com/doc/21_07/KGnmj6JbeTp_Capture-du-2021-07-13-14-09-42.png)

**Additional context**
 - Browser (if applicable): Firefox 89.0.2 (64 bits)
 - OS (if applicable): Debian 11 bullseye/sid (5.10.0-8-amd64 SMP 5.10.46-1 (2021-06-24) x86_64 GNU/Linux)

**Comment by unixfox** [comment]
Looks like that's an issue with the instance you're using! Please go ahead and visit https://redirect.invidious.io to select another one.
