### ISSUE TITLE
Build fails with crystal 1.1.0 (2021-07-14)

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [iv-org/invidious#2256]
```
user@host:~/gits/invidious$ crystal build src/invidious.cr --release
Showing last frame. Use --error-trace for full trace.

In /usr/share/crystal/src/socket/addrinfo.cr:192:7

 192 | resolve(domain, service, family, Type::STREAM, Protocol::TCP) { |addrinfo| yield addrinfo }
       ^------
Error: no overload matches 'Socket::Addrinfo.resolve' with types Int32, Socket::Family, Bool, Socket::Type, Socket::Protocol

Overloads are:
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil)
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil, &block)
 ```

**Comment by unixfox** [comment]
We don't support crystal 1.1.0 yet, you are advised to use crystal 1.0.0 until further notices.

**Comment by SamantazFox** [comment]
Looks like an issue with crystal itself (The error points to the code at `/usr/share/crystal/src/socket/addrinfo.cr:192:7` and [we don't use the `resolve()` function](https://github.com/iv-org/invidious/search?q=resolve)).

What distro are you using? Are you using the upstream binaries or your package maintainer's?

**Comment by tinglycraniumplacidly** [comment]
Hi @SamantazFox thanks for following up.

I'm using Ubuntu, and I followed the Manual setup as outlined here
https://crystal-lang.org/install/on_ubuntu/

I wasn't sure how to downgrade/get 1.0.0.

**Comment by syeopite** [comment]
It might not be an upstream issue. I just quickly ran an error trace which pointed to these extension methods for a potential culprit
 
https://github.com/iv-org/invidious/blob/0d57a887ea59b6111d9a19b1ea1cea619ad9f129/src/invidious/helpers/helpers.cr#L763-L773

**Comment by GauthierPLM** [comment]
Hello,

If you upgraded crystal to 1.1.0 and encounter issues, you can try to downgrade to 1.0.0 until a fix is done.
Unfortunately, the official Crystal repository does not contains the 1.0.0 version any more.

If you are lucky, the package could still be in `/var/cache/apt/archives/`.
You can install it using ` sudo apt install /var/cache/apt/archives/crystal_1.0.0-1+61.1_amd64.deb`.

To avoid upgrading the package, you can hold it so it does not upgrade: `sudo apt-mark hold crystal`. Don't forget to regularly upgrade the package when it's considered stable. [More information.](https://linoxide.com/exclude-specific-package-apt-get-upgrade/)

Hope this can help !

**Comment by markozajc** [comment]
[Here's](https://paste.debian.net/hidden/5a34ab7e/) the output with `--error-trace`, in case it's needed.

**Comment by SamantazFox** [comment]
> [Here's](https://paste.debian.net/hidden/5a34ab7e/) the output with `--error-trace`, in case it's needed.

What distro are you using? And what crystal release (from github, from repos)?

**Comment by markozajc** [comment]
@SamantazFox I am on Debian Bullseye/testing and I got the 1.1.0 release from the official repository on OBS (https://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Testing). Full version string is `1.1.0-1+2.1`.

**Comment by SamantazFox** [comment]
I'll try to update on our test instance when I'll have the time for that.

**Comment by nahdoubtit** [comment]
I got this same issue on Debian 10 buster & Crystal 1.1.0 [af095d72d]. I noticed tleydxdy has a PR to fix it, so I tried that before downgrading crystal and #2263 works. builds fine, and runs fine.

**Comment by SamantazFox** [comment]
> I got this same issue on Debian 10 buster & Crystal 1.1.0 [af095d72d]. I noticed tleydxdy has a PR to fix it, so I tried that before downgrading crystal and #2263 works. builds fine, and runs fine.

For now, we recommend to stay on `v1.0.*` of crystal. As discussed on matrix, while the modifications provided by @tleydxdy solve the compilation error, they doesn't fix the actual code, and the proxy feature (for bypass of region-restricted videos) is still broken.

**Comment by nahdoubtit** [comment]
> > I got this same issue on Debian 10 buster & Crystal 1.1.0 [af095d72d]. I noticed tleydxdy has a PR to fix it, so I tried that before downgrading crystal and #2263 works. builds fine, and runs fine.
> 
> For now, we recommend to stay on `v1.0.*` of crystal. As discussed on matrix, while the modifications provided by @tleydxdy solve the compilation error, they doesn't fix the actual code, and the proxy feature (for bypass of region-restricted videos) is still broken.

I was worried it'd be difficult to downgrade, i.e. compile it myself and have dependency issues, but it was easy as uninstalling crystal 1.1.0 and downloading the deb from this quote below, and manually installing it with dpkg.

> [Here's](https://paste.debian.net/hidden/5a34ab7e/) the output with `--error-trace`, in case it's needed.
> 
> You can also grab Crystal 1.0.0 from their [release page](https://github.com/crystal-lang/crystal/releases/tag/1.0.0) on GitHub.
