### ISSUE TITLE
[Enhancement] Change route classes to be modules

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#2273]
**Is your enhancement request related to a problem? Please describe.**

Currently, each of the route file uses a separate class as a namespace for storing different functions (routes). This is then initialized when building each route for kemal.

https://github.com/iv-org/invidious/blob/095c894548c2aaa884b8d2857dab01207c184345/src/invidious/routing.cr#L4

As of master, the route classes are initialized and allocated almost 40 times. 

**Describe the solution you'd like**

As expected, the current method is rather inefficient. So, I propose switching to the crystal object designed for namespaces: modules. Each of the route can then be a class method within their module.

**Describe alternatives you've considered**

Use structs instead  — and also with class methods.

**Additional context**

**Comment by SamantazFox** [comment]
Why is this even instancied? All the routing functions are "static" (in C terms) so they can be called directly without needing an object...

**Comment by syeopite** [comment]
Because the routing logic is really more of a temporarily solution that became permanent. Originally, the route classes were just intended as a stepping stone for migrating to other frameworks such as Lucky or Grip. See #1399. So it's really just a quick patch for making things more manageable.

And since we're not migrating away from kemal anytime soon, the routing logic should be improved upon.
