### ISSUE TITLE
[Bug] Typo in new option in preferences

### ISSUE THREAD

**Issue by Elaborendum** [iv-org/invidious#2289]
**Describe the bug**

There's a typo in the "Automatic Instance redirection" option in settings. It says "Automaticatic". Is it okay to report this as a bug?

**Steps to Reproduce**
1. Go to the Settings of any instance
2. Scroll down to "Miscellaneous preferences"
3. See typo

**Screenshots**

![imagen](https://user-images.githubusercontent.com/71190696/127439029-f1de8c5f-3284-47ed-8cfd-b25dac093fe2.png)

**Comment by syeopite** [comment]
Yep definitely a bug. Thanks for reporting the issue!

**Comment by SamantazFox** [comment]
Will be fixed next time a PR from weblate is merged.
