### ISSUE TITLE
[Bug]  isFamilyFriendly always returns false for channels

### ISSUE THREAD

**Issue by ChunkyProgrammer** [iv-org/invidious#2291]
**Describe the bug**
Invidious api always returns false for "isFamilyFriendly" even when it should be true

**Steps to Reproduce**
1. Go to /api/v1/channels/UCbCmjCuTUZos6Inko4u57UQ?fields=author,isFamilyFriendly&pretty=1
2. Notice that "isFamilyIsFriendly" is false when it should be true

**Screenshots**
![image](https://user-images.githubusercontent.com/78101139/127715548-fa25e27a-64d2-4d47-9387-a99f69ce4961.png)

**Additional context**
https://github.com/iv-org/invidious/blob/master/src/invidious/channels/about.cr#L103
I think this line would need to be changed to (have not tested, guessing based on how [FreeTube ](https://github.com/FreeTubeApp/yt-channel-info/blob/master/app/youtube-grabber.js#L129)does it)
`initdata["metadata"]["channelMetadataRenderer"]["isFamilySafe"].as_bool`

I am not sure if this line also needs to be changed
https://github.com/iv-org/invidious/blob/master/src/invidious/channels/about.cr#L80

**Comment by unixfox** [comment]
Can you check if this PR solve the issue: https://github.com/iv-org/invidious/pull/2255?

**Comment by ChunkyProgrammer** [comment]
> Can you check if this PR solve the issue: #2255?

It solves it. sorry, I didn't notice that PR when making this issue

**Comment by unixfox** [comment]
Reopening as the PR is not yet merged.
