### ISSUE TITLE
[Bug]  Could not check out a connection in 2.0 seconds (DB::PoolTimeout)

### ISSUE THREAD

**Issue by J4000** [iv-org/invidious#2292]
**Describe the bug**
A video reports an error message - I was advised to create a new issue on GitHub with the text of the error message, so here it is:

> Looks like you've found a bug in Invidious. Please open a new issue on GitHub and include the following text in your message:
````
Title: `Could not check out a connection in 2.0 seconds (DB::PoolTimeout)`
Date: `2021-07-30T23:42:45Z`
Route: `/watch?v=G-tCK-82FlI`
Version: `2021.07.27-36e18fe1 @ master`
<details>
<summary>Backtrace</summary>
<p>
```
Could not check out a connection in 2.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:538:9 in 'checkout'
  from src/invidious/helpers/utils.cr:35:14 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>
````

**Steps to Reproduce**
1. Go here: [https://ytprivate.com/watch?v=G-tCK-82FlI](https://ytprivate.com/watch?v=G-tCK-82FlI) (warning: the video in question may be offensive to some)
2. See the error message and be unable to watch and/or download the video

**Logs**
As above.

**Screenshots**
![region](https://user-images.githubusercontent.com/7039105/127721669-b4b099bb-dd1a-442b-9ca4-37222d7fb2a5.png)

**Additional context**
This only seems to happen on `ytprivate.com` - other invidio.us instances don't work either, but in a different way (clicking 'play' does nothing and the 'download' options dropdown is empty).

It could well be a slow database on this site's server or the site's timeout setting is set too low or something (2 seconds does seem a rather short time to wait before giving up), rather than any actual bug in Invidious; I am unsure but thought best to post this here as advised just in case.

**Comment by syeopite** [comment]
The `DB::PoolTimeout` is just an instance issue. As for the second, we're aware of it. YouTube has been making some changes to age-gated videos that is preventing them from being played. See #2189.

**Comment by J4000** [comment]
OK, cheers for advising!

**Comment by BakugoSimp123** [comment]
This issue has been happening to me a lot. (I mean the Could not check out a connection in 2.0 seconds thing) It happens on every video I watch and I can't fix it. This only happened after I went on a certain video. I forgot the exact video but after that nothing was working.

**Comment by unixfox** [comment]
> This issue has been happening to me a lot. (I mean the Could not check out a connection in 2.0 seconds thing) It happens on every video I watch and I can't fix it. This only happened after I went on a certain video. I forgot the exact video but after that nothing was working.

Use another instance from https://api.invidious.io
