### ISSUE TITLE
The Popular tab does not display any videos

### ISSUE THREAD

**Issue by tio-trom** [iv-org/invidious#2293]
The Popular is enabled 
`  popular_enabled: true `

But displays no videos:
https://ytb.trom.tf/feed/popular

**Comment by unixfox** [comment]
This isn't a bug, you have nobody registered on your instance (see usage.users.total from https://ytb.trom.tf/api/v1/stats) so Invidious can't generate a list of popular channel from registered users.
See this file for the actual implementation of the code of the popular page: https://github.com/iv-org/invidious/blob/master/src/invidious/jobs/pull_popular_videos_job.cr

**Comment by tio-trom** [comment]
Oh so the Popular tab is based on the users registered on out instance? That's interesting. Ok then. I get it now. Thanks!
