### ISSUE TITLE
Legal headsup about Facebook sending C&D letter to Barinsta (FLOSS 3rd party frontend)

### ISSUE THREAD

**Issue by Kreyren** [iv-org/invidious#2300]
Legal representatives of Facebook, Inc. and Instagram, Inc. sent a Cease and Desist letter to Barinsta developer[2] (Free and Open-Source Instagram frontend[1]) forcing them to stop the development after one year of work.[3]

I decided to inform you about it as it may mean legal issues for invidious and other 3rd party FLOSS frontends if the effort is successful.

References:
1. App in the f-droid:
https://f-droid.org/en/packages/me.austinhuang.instagrabber/
2. Copy of the letter:
https://firebot-prod-media.s3.amazonaws.com/email-attachments/9ceab4da-d016-4524-bffc-87519d5e2cce/Barinsta_-_C26D.pdf
3. Issue by the developer:
https://github.com/austinhuang0131/aushttps://github.com/austinhuang0131/austinhuang0131/issues/2

**Comment by SamantazFox** [comment]
Thanks for getting in touch! Though, we are already aware of that, and we've been discussing about what could/should be done in order to protect us, if such a thing would happen.

**Comment by Rjevski** [comment]
I think setting up a PGP key controlled by the core team would be a prudent idea, so that in the case of a GitHub takedown, development can restart elsewhere with the core team being able to prove who they are.
