### ISSUE TITLE
[Enhancement] Reinstate api-only branch via compile time flags

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#2301]
**Is your enhancement request related to a problem? Please describe.**

In the past Invidious had an [api-only branch](https://github.com/iv-org/invidious/tree/api-only). However, after the departure of Omarroth, that branch quickly became unmaintained. 

**Describe the solution you'd like**

Once #2271 is merged, it is now possible to bring back the api-only branch in a more maintainable way: compile-time flags. Instead of producing a new branch, I'll suggest we add a compile time flag that removes the routing logic for the UI entirely.

Something along the lines of this:
```crystal
{% skip_file unless flag?(:api_only) %}

class Invidious::Routes::PreferencesRoute < Invidious::Routes::BaseRoute
...
end
```  

and 

```crystal
{% unless flag?(:api_only) %}
  Invidious::Routing.get "/", Invidious::Routes::Misc, :home
  Invidious::Routing.get "/privacy", Invidious::Routes::Misc, :privacy
  ...
  Invidious::Routing.get "/toggle_theme", Invidious::Routes::PreferencesRoute, :toggle_theme
{% end %}

define_v1_api_routes()
```

**Describe alternatives you've considered**

**Additional context**

**Comment by SamantazFox** [comment]
That's a good idea! However, I have no idea on how compile flags are passed to Crystal ^^

Tho, we'd probably want at some point to move the big chunk of routes from `invidious.cr` to `routing.cr`, so we won't clutter the main file with a ton of conditionals.

**Comment by syeopite** [comment]
[Here's the documentation for them](https://crystal-lang.org/reference/syntax_and_semantics/compile_time_flags.html). It's about as simple as passing a `-D` parameter to the compiler. 

`crystal build src/invidious -Dapi_only`

> Tho, we'd probably want at some point to move the big chunk of routes from `invidious.cr` to `routing.cr`, so we won't clutter the main file with a ton of conditionals.

Yes, definitely.
