### ISSUE TITLE
[Enhancement] Show unavailable videos in playlists

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2303]
I saw that series of comments on NewPipe extractor side (See: https://github.com/TeamNewPipe/NewPipeExtractor/pull/604#discussion_r681909214), and though that it could be a good idea to restore the visibility of "unavailable" videos in playlists.

That would also fix inconsistencies in paging (e.g when requesting videos via the `browse` endpoint, youtube will always provide 100 entries no matter what. So if one of them was unavailable, say `#98`, it will provide `#1` to `#97` (97 videos), then `#99` to `#101` (3 videos). When showing page 2, we will request `#101` to `#200`, making `#101` redundant across pages).

That feature was present on youtube, before they removed it.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
