### ISSUE TITLE
[Bug] Controllers get created every single time the endpoint is requested

### ISSUE THREAD

**Issue by grkek** [iv-org/invidious#2304]
Doesn't this create a new controller every single time the endpoint is hit?

https://github.com/iv-org/invidious/blob/master/src/invidious/routing.cr#L4

**Comment by syeopite** [comment]
Not exactly. those macros are only executed on startup. 

https://github.com/iv-org/invidious/blob/1321c9092092a946d66b053f1dc3b71f922053ab/src/invidious.cr#L308-L317

However, yes. A new controller instance shouldn't be created when defining paths. See #2273 and #2298
