### ISSUE TITLE
[Discussion] Preferences overhaul

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2307]
I'm currently working on a complete refactor of the code handling the server config, the user preferences, and the override of the latter with URL parameters.

What config options can/should be removed?

<details>
<summary>Current options available:</summary>
<br/>

**Server:**
https://github.com/iv-org/invidious/blob/7ddab5b8cda8d673b2f4b5a482185fbf295c456d/src/invidious/helpers/helpers.cr#L71-L110

**User:**
https://github.com/iv-org/invidious/blob/7ddab5b8cda8d673b2f4b5a482185fbf295c456d/src/invidious/users.cr#L36-L85

<hr>
</details>

I plan to remove the following options:

* server
  - ~~`database_url` (redundant with the multi-part DB config)~~
  - `admins` (could be done via DB directly, imo).
  - `check_tables` (will be replaced with something else when the DB code is refactored)
  - `channel_threads`/`feed_threads` (??, crystal is single-threaded, this only sets the amount of fibers)

* user
  - `annotations_subscribed` (not sure if useful?)
  - `continue_autoplay`  => redundant with `continue` and `autoplay`)
  - `max_results` (this is limited by the youtube API anyway)
  - `quality_dash` (will be merged with `quality`)

<br/>

and replace/rename those:

* server
  - `dmca_content` (replace with `enable_download`)

* user
  - `comments` (will be replaced with booleans for yt/reddit)
  - `dark_mode` => replace with `theme`
  - `local` => rename to `proxy`, maybe?
  - `default_home` => rename to `homepage`
  - `unseen_only` => rename to something more explicit?

**Comment by Rjevski** [comment]
I would prefer if you kept the "database URL" parameter as-is. It's very common in web apps to configure backing services such as DB, cache, etc through URLs rather than discrete parameters, and a lot of PaaS such as Heroku (and self-hosted equivalents) export `DATABASE_URL` environment variables out of the box which would require extra parsing work (not easy to do in the shell) to turn into separate user/password/host/db name parameters.

**Comment by SamantazFox** [comment]
@Rjevski What about mergin the two under a common `database` setting, that can accept both discrete parameters and a URI string?

**Comment by Rjevski** [comment]
That could be possible, but I still don't see the point. Assembling a DATABASE_URL from discrete parameters is trivial enough in shell:

DATABASE_URL="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME" ./invidious

Given this I don't see the point of explicitly supporting it in the application itself.

**Comment by SamantazFox** [comment]
> That could be possible, but I still don't see the point. Assembling a DATABASE_URL from discrete parameters is trivial enough in shell: DATABASE_URL="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME" ./invidious Given this I don't see the point of explicitly supporting it in the application itself.
> […](#)
> On 9 Aug 2021, at 17:37, Samantaz Fox ***@***.***> wrote: @Rjevski What about mergin the two under a common database setting, that can accept both discrete parameters and a URI string? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

That won't work if your password contains any reserved characters (like `@./:`)

**Comment by Rjevski** [comment]
True - I feel like it's a major edge-case though, considering you can just make the password alphanumeric (without special chars) and add extra length to make up for the reduced character set?

**Comment by SamantazFox** [comment]
> True - I feel like it's a major edge-case though, considering you can just make the password alphanumeric (without special chars) and add extra length to make up for the reduced character set?

Afaik, a proper URI should be %-encoded (i.e any `/` in the password should be replaced with `%2F`)

**Comment by Rjevski** [comment]
Yes, I understand your point, but I was just saying that you can typically avoid it by just making a password that doesn't have special characters such as / (and increase the length to compensate) *if* assembling the DB URL out of discrete parameters is actually a requirement.

Environment variables is a standard way of configuring web applications from my experience, and DATABASE_URL is a common thing to see. Personally in my career I haven't had a use-case for keeping DB settings as discrete parameters. Instead the DB URL comes as a single value from whatever secrets store you use (Hashicorp Vault, AWS Parameter Store, etc).
