### ISSUE TITLE
[Enhancement] Support for custom channel emoji/emoticons

### ISSUE THREAD

**Issue by mc-fugger** [iv-org/invidious#2308]
I've searched for "emoji", "emoticon" and "smiley", both didn't return anything useful

**Is your enhancement request related to a problem? Please describe.**

Depends on the definition of "problem"
"I'm always frustrated when I click on a video and custom emoticons are displayed as text"

**Describe the solution you'd like**

When browsing comments, I'd like to have support for the custom emoticons some channels use, right now they're displayed as a text fallback

**Describe alternatives you've considered**

I tried imagining the emoticons without success

**Additional context**

![grafik](https://user-images.githubusercontent.com/81241301/128553483-eab87945-8fc3-41a4-929e-b67d69d8323a.png)
This is an example of how invidious displays the emoticon
![grafik](https://user-images.githubusercontent.com/81241301/128553537-87eceaa2-6436-4923-a763-ce274ab629e4.png)
and this is how it's supposed to be

Thank you for your consideration

**Comment by SamantazFox** [comment]
Hello! Can you please provide a few examples of places where this kind of emojis are used? (comment permalinks or video/playlist URL if that's also present in descriptions)

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898
