### ISSUE TITLE
[Bug] Crystal reports missing method HTTP::Cookies.from_client_headers(headers)

### ISSUE THREAD

**Issue by Quix0r** [iv-org/invidious#2314]
The reported error message in #2175 is still valid with latest invidious code:

I'm on commit id 81e77693b291db9d3b1aa18f330984fd284f7acf (master) and crystal:
````
$ crystal --version
Crystal 0.36.1 [c3a3c1823] (2021-02-02)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
$
````
If I try to build the usual way:
````
$ crystal build  src/invidious.cr --release --verbose --progress
Showing last frame. Use --error-trace for full trace.

In src/invidious/jobs/bypass_captcha_job.cr:119:37

 119 | cookies = HTTP::Cookies.from_client_headers(headers)
                               ^------------------
Error: undefined method 'from_client_headers' for HTTP::Cookies.class
$
````
I have installed crystal over the described way: https://crystal-lang.org/install/on_debian/ Now invidious runs on an older version (so I can still use it). :-)

**Comment by SamantazFox** [comment]
Invidious requires at least v1.0.0 of Crystal, so you'll have to update :) (current latest is 1.1.1)

**Comment by Quix0r** [comment]
So I better wait for an official Debian package. :-)

**Comment by SamantazFox** [comment]
> So I better wait for an official Debian package. :-)

There are already new packages for the latest versions of Crystal.

Upstream changed repositories (from bintray to open build service) when they passed to 1.0.0, so you'll probably need to clean any old Crystal PGP keys/sources.list from `/etc/apt`, get a fresh `install.sh` script, and run it again :)

**Comment by Quix0r** [comment]
I had to apply some fixes to `install.sh` as when I run it with `bash -x install.sh` I get some strange output:
````
+ _install_apt
++ command -v wget
+ [[ -z '' ]]
+ [[ -f /etc/apt/sources.list.d/crystal.list ]]
+ aptitude update
````
This is only an excerpt. The debug lines are NOT the strange output here. ;-) But the empty string in `[[ -z '' ]]` is. I found out that your script does this here:
````
if [[ -z "$(command -v wget &> /dev/null)" ]] || [[ -z "$(command -v gpg &> /dev/null)" ]]; then
````
While it has to be:
````
if [[ -z "$(command -v wget 2> /dev/null)" ]] || [[ -z "$(command -v gpg 2> /dev/null)" ]]; then
````
to suppress any error output. Maybe a typo? Maybe you also want to centralize `$(command -v foo)` in a function like `detect_binary()` and `$1` is the binary to look for?

**Comment by unixfox** [comment]
@Quix0r I created another issue as you are getting offtopic here: https://github.com/iv-org/invidious/issues/2425
