### ISSUE TITLE
[Bug] Cannot display replies to comments

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#2318]
**Describe the bug**

When I try to load the replies to a comment in a video, they are not shown. It tries to load them but then nothing is shown.

**Steps to Reproduce**
1. Go to https://invidious.fdn.fr/watch?v=YPjJNGeKmf8 
2. Click on any of the view replies links.

**Comment by hynet-mel** [comment]
I noticed this too on my own instance and also on NewPipe too. I suspect YouTube got something changed

**Comment by SamantazFox** [comment]
We're working on that: #2217 !

**Comment by unixfox** [comment]
Fixed by #2217
