### ISSUE TITLE
[Bug] Unexpected char 'C' at line 1 - Youtube is now serving csv file instead of json file when exporting the subscriptions

### ISSUE THREAD

**Issue by dhuschde** [iv-org/invidious#2319]
TEMPORARY SOLUTION: https://github.com/iv-org/invidious/issues/2319#issuecomment-900358678

-------

YouTube gives a csv file instead of a json file when exporting the subscriptions.

------

**Describe the bug**
I sadly can't import my YT Subs to Invie

**Steps to Reproduce**
Import your YT Subs to Invidious while having Google on German

**Logs**
Title: `Unexpected char 'K' at line 1, column 1 (JSON::ParseException)`
Date: `2021-08-10T16:16:31Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.07.27-5c76cdaa @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'K' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

[Also available on Snopyta PasteBin](https://bin.snopyta.org/?91bc88c04e266e77#3vdCruV713Xvm8KXYCuhjVZDvgMgGnDVkMj7iDdsdFd7)
Browser Link: https://yt.alt.s.dhusch.de/data_control?referer=%2Ffeed%2Fpopular

**Additional context**
I'm using YunoHost to host it

**Comment by ChunkyProgrammer** [comment]
I don't believe that Invidious supports importing csv files at all yet

**Comment by dhuschde** [comment]
But I can't change the file type on YT...

ChunkyProgrammer ***@***.***> schrieb am Mi., 11. Aug. 2021,
14:35:

**Comment by SamantazFox** [comment]
This is a known issue. It has been discussed here -> https://github.com/iv-org/documentation/pull/55#issuecomment-891196604

If you can provide some anonymized data, that would be really useful!

**Comment by dhuschde** [comment]
I send the CSV and the stuff I already provided here in the thread.

**Comment by unixfox** [comment]
Meanwhile you can use one of these tools for converting a CSV file to a json newpipe format which invidious can understand:
- https://tbjgolden.github.io/newpipe-csv-json-fixer/
- https://github.com/JCGdev/Newpipe-CSV-Fixer

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by martadinata666** [comment]
Credits to this man, https://github.com/JCGdev/Newpipe-CSV-Fixer by creating google csv to newpipe json format.

**Comment by acoolstraw** [comment]
I love how the Invidious codebase is so shit that no one has replaced the JSON parser with a CSV parser yet

**Comment by TheFrenchGhosty** [comment]
@acoolstraw You know that instead of throwing garbage tier trolling to a project that is made by unpaid volunteer in their free time you can also contribute, right?

No one in (or outside of) the team has to do anything for you, or anyone, people contribute what they want, if they don't care about fixing this and prefer to work in something else it's perfectly fine. You want a fix? You can contribute.

Next time we receive this kind of message from you, you get a ban.

**Comment by acoolstraw** [comment]
@TheFrenchGhosty cope and seethe
