### ISSUE TITLE
Samsung smart tv [Enhancement] 

### ISSUE THREAD

**Issue by d4rk-n0153** [iv-org/invidious#2334]
Hi
My Samsung tv browser videos don't play and stick in 00:00!

**Comment by unixfox** [comment]
What's the model of the smart tv?

**Comment by d4rk-n0153** [comment]
Model name:
UA43M6960AW

**Comment by d4rk-n0153** [comment]
> What's the model of the smart tv?

Model name:
UA43M6960AW

**Comment by unixfox** [comment]
Did you try enabling proxy mode and playing a video with it enabled? Also, did you try enabling dash and playing a video with it enabled?

Which Invidious instance are you using? Is it a public instance or a private one that you installed yourself?

**Comment by d4rk-n0153** [comment]
> Did you try enabling proxy mode in the preferences page and playing a video with it enabled? Also, did you try enabling dash in the preferences page and playing a video with it enabled?
> 
> Which Invidious instance are you using? Is it a public instance or a private one that you installed yourself?
I did nothing.
Youtube is censored in our country so, I use this url:
www.yewtu.be
For watch youtube  in my tv,
it's work last month but now it's did not.

**Comment by unixfox** [comment]
What do you mean it worked last month? It worked last month on your TV?

And you didn't reply on my two first questions:

> Did you try enabling proxy mode in the preferences page and playing a video with it enabled? Also, did you try enabling dash in the preferences page and playing a video with it enabled?

**Comment by d4rk-n0153** [comment]
> What do you mean it worked last month? It worked last month on your TV?
> 
> And you didn't reply on my two first questions:
> 
> > Did you try enabling proxy mode in the preferences page and playing a video with it enabled? Also, did you try enabling dash in the preferences page and playing a video with it enabled?

Yes, it worked well until a month ago, but now it is down.  In the case of the other two questions, it is not possible to activate the proxy on the TV, and it is only possible to enter the site address in the browser and view the sites.

**Comment by unixfox** [comment]
> > What do you mean it worked last month? It worked last month on your TV?
> > And you didn't reply on my two first questions:
> > > Did you try enabling proxy mode in the preferences page and playing a video with it enabled? Also, did you try enabling dash in the preferences page and playing a video with it enabled?
> 
> Yes, it worked well until a month ago, but now it is down. In the case of the other two questions, it is not possible to activate the proxy on the TV, and it is only possible to enter the site address in the browser and view the sites.

You didn't understand correctly what I said. When I meant proxy mode is from this page: https://yewtu.be/preferences and for dash too. Please test.

**Comment by d4rk-n0153** [comment]
> You didn't understand correctly what I said. When I meant proxy mode (proxy videos) is from this page: https://yewtu.be/preferences and for dash too. Please test.


On another site, the problem was fixed with these settings

site : www.ytb.trom.tf
