### ISSUE TITLE
[Bug] Could not fetch comments

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#2340]
**Describe the bug**
We don't handle the case where the comments are deactivated.

**Steps to Reproduce**
Affected video: https://redirect.invidious.io/watch?v=lrR93-Dee2I

**Logs**
Could not fetch comments

**Screenshots**

**Additional context**
Self reporting so that I can try to fix the issue later.

**Comment by TheFrenchGhosty** [comment]
@unixfox Comments work on the video you linked.

Is that a general issue on any video with disabled comments?

**Comment by unixfox** [comment]
> Is that a general issue on any video with disabled comments?

Yes it is.

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/1092

**Comment by unixfox** [comment]
@TheFrenchGhosty maybe you can move the bounty on https://github.com/iv-org/invidious/issues/1092

**Comment by TheFrenchGhosty** [comment]
@unixfox done
