### ISSUE TITLE
[Bug] Using shortlink redirects to channel instead of video

### ISSUE THREAD

**Issue by austinhuang0131** [iv-org/invidious#2347]
**Describe the bug**
Generally speaking `/<video_id>` redirects `/watch?v=<video_id>`.

However, somehow, `/<video_id>` was fetched as a channel URL instead in this case.

This affects Privacy Redirect's ability to redirect `youtu.be` links

**Steps to Reproduce**
1. https://redirect.invidious.io/watch?v=dQw4w9WgXcQ redirects to the rickroll video, right?
2. https://redirect.invidious.io/dQw4w9WgXcQ redirects to a channel called "SubToMe" whose [custom channel URL](https://www.youtube.com/c/dQw4w9WgXcQ) is `dQw4w9WgXcQ`

**Comment by syeopite** [comment]
Hmm this is strange. *Technically* Invidious's behavior is right. YouTube returns the first of those links as a `urlEndpoint` while the rest are given as a `watchEndpoint`.

As a result on YouTube the links traverse to:

* https://youtu.be/3EsuRXSv2U
* https://www.youtube.com/watch?v=YZPdI5Y2zCI&t=0s
* https://www.youtube.com/watch?v=o6vQEmMNT3E&t=0s
* https://www.youtube.com/watch?v=Xya6zsX3Hps&t=0s
* https://www.youtube.com/watch?v=gGv2rLBp01c&t=0s

And this is *technically* the behavior seen on Invidious. Just not the one you'd typically expect. Anyhow, #2365 should fix it.

**Comment by syeopite** [comment]
https://github.com/iv-org/invidious/issues/2347#issuecomment-907391702

Closing as this has been fixed by #2365
