### ISSUE TITLE
[Bug] When importing (previously exported) subscription file

### ISSUE THREAD

**Issue by Surgams** [iv-org/invidious#2349]
Title: `Expected Hash for #[](key : String), not String (Exception)`
Date: `2021-08-25T07:23:46Z`
Route: `/data_control?referer=%2Ffeed%2Fsubscriptions`
Version: `2021.08.21-0db23f92 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Expected Hash for #[](key : String), not String (Exception)
  from /usr/share/crystal/src/json/any.cr:104:7 in '[]'
  from src/invidious.cr:813:22 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
![snapshot-2021-08-25-17_28_47-1020x719](https://user-images.githubusercontent.com/26637441/130746115-7c6c03c3-2275-4be6-b577-5cf2ce48f88b.jpg)

</details>

**Steps to Reproduce**
1. Go to: subscriptions -> Manage subscriptions -> export (json or opml)
2.  Go to: subscriptions -> Manage subscriptions -> import file from 1 (json or opml)

**Logs**

**Screenshots**

![snapshot-2021-08-25-17_28_47-1020x719](https://user-images.githubusercontent.com/26637441/130746429-552b5192-827f-4a3a-95f6-1af1dd2aae3a.jpg)

**Additional context**

 - Browser (if applicable): Firefox 91.0.1
 - OS (if applicable): FreeBSD 13

**Comment by Surgams** [comment]
Thanks @SamantazFox, you are correct. Sorry for this

**Comment by SamantazFox** [comment]
> Thanks @SamantazFox, you are correct. Sorry for this

No problem :) That happens to everyone ^^
