### ISSUE TITLE
Galaxy S6 crashes

### ISSUE THREAD

**Issue by beefeater7** [iv-org/invidious#235]
I worship your altar for giving us the listen functionality. Anyway, problem is my Chrome tab always freezes while playing a clip in the background. I need to shut it down and open the site anew. I don't get this on other sites with audio playback.

**Comment by omarroth** [comment]
I unfortunately don't have a device to test this on, but see if e6bc5bb fixes it for you.

**Comment by Perflyst** [comment]
I have also Galaxy S6 and tested with LineageOS 14.1 and 15.1
Cannot reproduce this, I tried with Chrome, Chromium and Firefox. Seems to be a local problem only with his device.

**Comment by omarroth** [comment]
I can reproduce a similar issue when using Chrome with `&listen=1` on desktop, but there don't appear to be any bugs opened in Chromium. The issue may be using an audio-only source inside a `<video>` tag.
