### ISSUE TITLE
[Bug] Livestreams do not load - CSP Violation

### ISSUE THREAD

**Issue by hugoamvieira** [iv-org/invidious#2352]
**Describe the bug**
I've tried loading many livestreams on my private Invidious instance and I cannot seem to view any live video on Firefox or Edge, however it works on Safari (both mobile and desktop).

Normal content works just fine everywhere.

The Edge browser I tried this on had no extensions at all. As for the Firefox browser, I tried both with my extensions on, as well as in Firefox's troubleshoot mode (all extensions off) - No dice either way.

The problem with live video seems to come from a CSP violation, and the browser rejects loading the content.
My instance is behind a reverse proxy, however I also see the same behaviour when accessing it directly.

Firstly, there's a call to the Invidious instance on `http://my-invidious-instance/api/manifest/hls_playlist/.../index.m3u8?local=true`, followed by the failing call to Youtube. This happens repeatedly, seemingly forever.

On Safari desktop, the stream loads and safari seems to not have a problem with CSP. In fact, the call to `http://my-invidious-instance/api/manifest/hls_playlist/.../index.m3u8?local=true` doesn't seem to return a CSP header where as it does on the other browsers. I am very unfamiliar with Safari dev tools so I might be missing it, though.

I tried playing with my config (changing `disable_proxy` settings, as well as adding `external_port` and `domain`, but that didn't do anything.

**Steps to Reproduce**
1. Open any livestream content on Firefox or Edge.
2. Observe network call
2.1. Call to Invidious API - `index.m3u8`
2.2. Failed call to Youtube - `seg.ts`

**Logs**
`Content Security Policy: The page's settings blocked the loading of a resource at https://rr4---sn-aigzrne7.c.youtube.com/videoplayback/id/<id>/itag/300/source/yt_live_broadcast/.../file/seg.ts ("connect-src").`

The CSP Policy (as received by the browser from invidious API on the `index.m3u8` calls): 
`Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; manifest-src 'self'; media-src 'self' blob: https://*.googlevideo.com:443 https://*.youtube.com:443; child-src 'self' blob:; frame-src 'self'; frame-ancestors 'none'`

**Screenshots**
![image](https://user-images.githubusercontent.com/10965479/130866657-3c5cf3b3-5cde-4a24-aacc-3160213b8ddb.png)

**Additional context**
Invidious Version: `2021.08.24-5c74196 @ master`
Browser: Failing on Firefox 91.0.2 and Edge 92.0.902.78. Working on Safari (both mobile and desktop).
OS: Windows 10, macOS, and iOS.

The violation seems to come, at least as reported by Firefox, from the `connect-src` policy, which is set to `self`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

**Comment by hugoamvieira** [comment]
Hey there, I've just updated my Invidious instance to sort out the [comments replies situation](https://github.com/iv-org/invidious/issues/2381) and I think there's been a regression here as loading livestreams is presenting the described behaviour again.

Currently running `2021.09.06-8d5a867 @ master`

Thanks! 🙏

**Comment by unixfox** [comment]
It's probably a Youtube change instead of a real regression from our part, I'm going to investigate tonight if I've some free time. We changed nothing related to how livestream works so I'm pretty sure it's due to a change from Youtube.

**Comment by unixfox** [comment]
Reopening in order to making me remember to check that.

**Comment by WaywardHeart** [comment]
Hi, it looks like the regression was caused by #2271 not incorporating the new regex.

**Comment by syeopite** [comment]
Yep looks like it.

https://github.com/iv-org/invidious/blob/d97e128dc04a8e244f4cf577c9680dac736a18ee/src/invidious/routes/api/manifest.cr#L163

Thanks @WaywardHeart  🎉
