### ISSUE TITLE
[Meta] About YouTube's Rolling Cypher "DRM"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2354]
This is a discussion mainly for the organization members (@Perflyst @SamantazFox @syeopite @unixfox) but others are free to give their opinion.

This is a follow up to a discussion we had in the Matrix room.

---

Currently some videos can't be played because of the Rolling Cypher "DRM" (see https://github.com/iv-org/invidious/issues/602#issuecomment-864428423 ).

My idea was to wait for us to have legal protection before trying to do anything with it because there was no precedent.

However I remembered that youtube-dl received a DMCA because of this, and the EFF proven (albeit, not in court) that this wasn't an actual DRM and that it was perfectly legal to bypass/decrypt it.

--- 
Quote from the EFF letter: ( https://raw.githubusercontent.com/github/dmca/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf )

>We presume that this “signature” code is what RIAA refers to as a “rolling cipher,”
although YouTube’s JavaScript code does not contain this phrase. Regardless of what this
mechanism is called, youtube-dl does not “circumvent” it as that term is defined in Section
1201(a) of the Digital Millennium Copyright Act, because YouTube provides the means
of accessing these video streams to anyone who requests them. As federal appeals court
recently ruled, one does not “circumvent” an access control by using a publicly available
password. Digital Drilling Data Systems, L.L.C. v. Petrolink Services, 965 F.3d 365, 372
(5th Cir. 2020). Circumvention is limited to actions that “descramble, decrypt, avoid,
bypass, remove, deactivate or impair a technological measure,” without the authority of the
copyright owner. “What is missing from this statutory definition is any reference to ‘use’
of a technological measure without the authority of the copyright owner.” Egilman v.
Keller & Heckman, LLP., 401 F. Supp. 2d 105, 113 (D.D.C. 2005). Because youtube-dl
simply uses the “signature” code provided by YouTube in the same manner as any browser,
rather than bypassing or avoiding it, it does not circumvent, and any alleged lack of
authorization from YouTube or the RIAA is irrelevant.

>Similarly, youtube-dl does not violate section 1201(b) of the DMCA because the
“signature” code does not “prevent[], restrict[], or otherwise limit[] the exercise of a right
of a copyright owner”—in other words, the code does not prevent copying of video data.
Any program capable of running JavaScript programs can run YouTube’s “signature”
code, regardless of whether it can also save a copy of the video streams it receives. The
YouTube code is entirely different from the CSS encryption used on DVD discs and
described in Universal City Studios, Inc. v. Corley, 273 F. 3d 429 (2d Cir. 2001), or from
the Widevine DRM owned and used by YouTube’s parent company Google. Although I
express no opinion here about how the DMCA might apply to these technologies, I note
that both CSS and Widevine require licensed players containing secret keys, which are
distributed only to technology vendors who agree to limit their use and maintain secrecy.
In contrast, the YouTube “signature” code, is distributed to all comers and contains no
secrets. YouTube does not require Web browser vendors to accept a license or a
commitment to secrecy in order to use the “signature” code, as it does with Widevine.

---

This *theoretically* (again, it wasn't proven in court) mean that the project, because it's hosted on Github (and is therefore subject to US law) is protected.

The problem is that most (all?) of the team is from Europe, where there's no legal precedent, meaning that even if the project doesn't get "in trouble" the team members might.

This is where this discussion comes in: should we wait to be able to defend ourselves legally, project and team members, or should we go ahead and look into decrypting/bypassing it now because it's important and the project is *technically* protected.

**Comment by unixfox** [comment]
As strange as this might sounds, we don't decrypt anything anymore because when we request the video data using an ANDROID client the given video data is already unencrypted by Youtube servers (see https://github.com/TeamNewPipe/NewPipeExtractor/issues/562). All the videos not geo-restricted and linked in https://github.com/iv-org/invidious/issues/602#issuecomment-864428423 work perfectly.

But an external code reviewer, that could work for the company RIAA, could misinterpret the fact that we don't decrypt anything anymore because we still have some remaining code that was used to decrypt the DRM protected videos back in the days when we weren't using the innertube API.

Moreover, last time I tried the old decrypt code is broken if we would only be using the WEB client when requesting the video data from the innertube API.

So if you are worried about legal things, we could remove all the decryption code from Invidious and this would also remove some wasted CPU & memory consumption because by default we have some code related to that running in the background every 1 minute.

**Comment by TheFrenchGhosty** [comment]
@unixfox Thank you for this detailed explanation, this is really good to know.

>So if you are worried about legal things, we could remove all the decryption code from Invidious and this would also remove some wasted CPU & memory consumption because by default we have some code related to that running in the background every 1 minute.

This is definitely the way to go in my opinion.

**Comment by unixfox** [comment]
> @unixfox Thank you for this detailed explanation, this is really good to know.
> 
> > So if you are worried about legal things, we could remove all the decryption code from Invidious and this would also remove some wasted CPU & memory consumption because by default we have some code related to that running in the background every 1 minute.
> 
> This is definitely the way to go in my opinion.

Well after investigating more about it, for the moment Invidious can't bypass videos protected by DRM-protected (level 2) like this video: https://redirect.invidious.io/watch?v=ebXbLfLACGM. I'll open an issue for tracking this problem.

**Comment by unixfox** [comment]
Question answered.
