### ISSUE TITLE
[Bug] Edge case: 3GP streams don't get hidden on Chromium-based browser

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2359]
**Describe the bug**

**This is maybe a VideoJS issue, and this has maybe been already fixed in a version that came out after the one Invidious is using.**

On Chromium based browsers the 3GP stream isn't hidden, this leads to 2 issues:

- There are 2 "small" quality selectors.
- One of them is audio only because videojs doesn't support 3GP videos ( https://videojs.com/html5-video-support/ )

**Steps to Reproduce**

https://redirect.invidious.io/watch?v=h4OtyO74kJI

**Logs**

N/A

**Screenshots**

Firefox:
![ff](https://user-images.githubusercontent.com/47571719/131182104-3e8109a5-e564-4250-88db-7ba28e88f1c1.png)

Chrome-based (tested on ungoogled-chromium and Chrome Android):
![chrome](https://user-images.githubusercontent.com/47571719/131182138-fb126081-7202-4e67-8ef9-28121847cee6.png)

**Additional context**

@TiA4f8R Research:

```
I may found why it's buggy:
The video is 240p at max res
And on the Android client, there are two normal streams:
A 3GPP stream and a MP4 stream are returned on the Android client, used by Invidious:
The 3GPP stream has the following properties:

        "mimeType": "video/3gpp; codecs=\"mp4v.20.3, mp4a.40.2\"",
        "bitrate": 82901,
        "width": 176,
        "height": 144,
        "lastModified": "1394112427035754",
        "contentLength": "3081179",
        "quality": "small",
        "fps": 12,
        "qualityLabel": "144p",
        "projectionType": "RECTANGULAR",
        "averageBitrate": 82856,
        "audioQuality": "AUDIO_QUALITY_LOW",
        "approxDurationMs": "297494",
        "audioSampleRate": "22050",
        "audioChannels": 1

Where the MPEG-4 video stream has:

        "mimeType": "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\"",
        "bitrate": 350145,
        "width": 320,
        "height": 240,
        "lastModified": "1394112418893423",
        "contentLength": "13004663",
        "quality": "small",
        "fps": 15,
        "qualityLabel": "240p",
        "projectionType": "RECTANGULAR",
        "averageBitrate": 350067,
        "audioQuality": "AUDIO_QUALITY_LOW",
        "approxDurationMs": "297192",
        "audioSampleRate": "44100",
        "audioChannels": 2

On videos with higher resolutions, the MPEG-4 stream (itag 18) is a 360p video.
But the 3GPP stream (itag 17) is always using 144p.
This last one is only returned on mobile clients and is a low quality stream.

**Comment by unixfox** [comment]
Should we omit 3GP streams all together? This is causing some issue on https://github.com/iv-org/invidious/issues/2361 too.

We didn't have 3GP streams before https://github.com/iv-org/invidious/pull/2220 because 3GP is provided only for Android devices and previously we didn't fetch the video data like an Android device.

**Comment by TheFrenchGhosty** [comment]
@unixfox 

> Should we omit 3GP streams all together? This is causing some issue on #2361 too.

I think so, everything available as 3GP is available as AAC.
