### ISSUE TITLE
[Bug] Invidious starts playing audio instead of video without js on Chromium

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [iv-org/invidious#2361]
**Describe the bug**
Invidious instances start only playing audio instead of video when I'm blocking js. Unblocking js fixes this. Blocking js reintroduces the issue

**Steps to Reproduce**
1. Start using an invidious instance with js disabled.
2. At some point videos will start playing only audio. (waiting for this to happen can take weeks or a single day)

**Logs**
I get these errors, but these also appear on instances where video still works.

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
watch:40 GET https://ytprivate.com/js/video.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:41 GET https://ytprivate.com/js/videojs-mobile-ui.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:42 GET https://ytprivate.com/js/videojs-contrib-quality-levels.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:43 GET https://ytprivate.com/js/videojs-http-source-selector.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:44 GET https://ytprivate.com/js/videojs-markers.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:45 GET https://ytprivate.com/js/videojs-share.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:46 GET https://ytprivate.com/js/videojs-vtt-thumbnails.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:53 GET https://ytprivate.com/js/silvermine-videojs-quality-selector.min.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:58 GET https://ytprivate.com/js/videojs-vr.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:277 GET https://ytprivate.com/js/player.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:822 GET https://ytprivate.com/js/watch.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:852 GET https://ytprivate.com/js/handlers.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT
watch:853 GET https://ytprivate.com/js/themes.js?v=39f0f242 net::ERR_BLOCKED_BY_CLIENT

**Screenshots**
![image](https://user-images.githubusercontent.com/79863493/131246324-1d6344f3-c3e1-403d-9ba3-c150632bd53c.png)

**Additional context**
Browser: Brave
OS: Arch Linux

**Comment by unixfox** [comment]
Please post the video ID and please try with another invidious instance because ytprivate.com is outdated: https://api.invidious.io/

**Comment by MarcoPolo-PasTonMolo** [comment]
ytprivate is the instance that I'm using right now and that still works

Instances that started displaying this issue:
yewtu.be
vid.puffyan.us
invidious.snopyta.org
invidious.kavin.rocks
invidious-us.kavin.rocks
invidious-jp.kavin.rocks

Btw it's not only that video that has this problem, the problem appears on all videos.
Nevertheless this is the ID: 5DR1AIsyzZ0

**Comment by unixfox** [comment]
I'm indeed able to replicate this issue on a vanilla chromium but not on Firefox.

**Comment by unixfox** [comment]
Hi @MarcoPolo-PasTonMolo I think I fixed the issue in https://github.com/iv-org/invidious/pull/2376.

You can already try this pull request live on https://yewtu.be (it should take around 2 hours to have the new feature ready to be deployed).

**Comment by MarcoPolo-PasTonMolo** [comment]
Thanks, can confirm that now yewtu.be works
