### ISSUE TITLE
Concerns about YouTube striking down iv

### ISSUE THREAD

**Issue by aboutDavid** [iv-org/invidious#2369]
Hi! A bot called "groovy" on Discord was striked down with a C&D for giving a users to hear audio without music. iv allows people to download music without the video.

Sorry if I should have not made an issue about this or this is a duplicate.

**Comment by AR-Student824** [comment]
Agreed. I had this concern as well

**Comment by TheFrenchGhosty** [comment]
Hello, thank you for your concern, I'll try to detail my answer.

@aboutDavid 

>A bot called "groovy" on Discord was striked down with a C&D for giving a users to hear audio without music.

We are aware that the bot was C&D, however things are a bit more complicated than that. Groovy allowed users to hear audio from YouTube... which might have been fine... but they also made users pay for a premium to get better quality... which is surely the reason why it was C&D (the Rythm bot is doing the same thing, so if more C&D are planed, it's the next on the list).

Nothing about Invidious is behind a paywall, at most the project accept donations (that are currently only used for code bounties/project expenses), receiving donation is perfectly fine.

>iv allows people to download music without the video.

youtube-dl is made to download from YouTube and has been fine for ~15 years.

@AR-Student824 

>I don't think downloading should be an issue in specific, but the whole invidious in general

We already discussed it internally (and publicly in the Matrix room), if things were to happen chances are Invidious won't be the first to be taken down, also considering the fact that Invidious is open source (unlike commercial bots like Groovy) if something happen... people will just be able to fork the project and it will live on.

We have plans in the future to make it easier for us to handle any legal issue that might happen. It has been discussed on Matrix but nothing is official yet.


>People are also doing stuff with open sourced repos for copyright, so the devs should watch out, because youtube is becoming more of a pain in the ass by the second

If things were to happen to Invidious, it won't be the first. They have "bigger fish to fry" first.

**Comment by aboutDavid** [comment]
Thank you for the answer!

**Comment by TheFrenchGhosty** [comment]
@aboutDavid @AR-Student824 

As I was saying in my previous message: "the Rythm bot is doing the same thing, so if more C&D are planed, it's surely the next on the list", I was right, it was taken down today.

![rythm down](https://user-images.githubusercontent.com/47571719/133002549-8feb3233-64ad-4f76-8955-6c39d8b5ae5f.png)
