### ISSUE TITLE
Add youtube embedd fallback

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#237]
while i highly prefer the invidious player but some videos wont play like geoblocked videos, livestreams or 360° videos and sometimes i want to see the annotations. it would be nice to have a fallback embed for those and other unforseen situations.

**Comment by Discookie** [comment]
Usually you can bypass geo-blocks with DASH videos, since they are proxied through invidious itself - see #34 for info on turning it on.

There are also plans to proxy other formats when not available as well, in #90 and #92.

**Comment by dimqua** [comment]
There's a livestream and annotations support atm too.

**Comment by elypter** [comment]
this is more valid than ever unfortunately. i frequently get videos that just wont play on an invidious instance or just general problems with relyability. i often have to click "watch on youtube". i would highly prefer an embedd fallback over this workaround.

**Comment by SamantazFox** [comment]
Both links to youtube and youtube embed are available, so I'm closing this issue.

As for embedding the youtube player itself in Invidious pages as a fallback to the invidious player, this won't be done. We have already discussed that on Matrix, this is against our goal of a privacy-friendly platform. Embedding Google scripts would be a huge privacy (and trust) breach.
