### ISSUE TITLE
[Bug] Invidious ignoring config from docker compose

### ISSUE THREAD

**Issue by HurricaneDancer** [iv-org/invidious#2389]
**Describe the bug**

Invidious seems to be ignoring the INVIDIOUS_CONFIG options with docker compose, or it is broken. I have noticed that on a lot of other instances, including mine, you are not able to sign up. Is this maybe an issue with the latest release? 

The only options it doesnt seem to be ignoring is the database config. When I change the password, it gives me a connection error messages which is expected. However, when I change options like default_home, it does not work. 

**Steps to Reproduce**

Visit literally any invidious instance, the signup button will be grayed out. The main thing I have changed from the documentations docker-compose file is that it is now using a custom network and the localhost version of postgres. Here is my INVIDIOUS_CONFIG: 

    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 2
        feed_threads: 2
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: 172.19.0.1
          port: 5432
        default_home: "Subscriptions" 
        login_enabled: true
        registration_enabled: true
        check_tables: true

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/44342932/132651076-114b0ce1-0566-48ab-9b36-90b9bf097573.png)

**Additional context**

Browser: Firefox
OS: Windows

Host OS: Ubuntu Linux 20.04

**Comment by HurricaneDancer** [comment]
never mind, im just dumb.

**Comment by unixfox** [comment]
> never mind, im just dumb. 

Could you explain how did you solve your issue :)? It may be useful for others.

**Comment by HurricaneDancer** [comment]
> 
> 
> > never mind, im just dumb.
> 
> Could you explain how did you solve your issue :)? It may be useful for others.

it wasn't really an issue. the register button doesnt seem to work as intended, but if you try to login normally with your details invidious will create your account.

**Comment by EsmailELBoBDev2** [comment]
hmm, it seems the case for me.

i disabled creating new accounts but still i can create one so any idea how to solve it? also i added a banner but it does not appear so clearly docker ignores my config.yml

**Comment by unixfox** [comment]
Don't edit the config.yml. Use the INVIDIOUS_CONFIG env on your docker-compose.yml

**Comment by EsmailELBoBDev2** [comment]
Well, it's my first time with docker and can you give me syntax example?

will it be like: 
```
        channel_threads: 1
	registration_enabled: false
        check_tables: true
        feed_threads: 1
```

**Comment by EsmailELBoBDev2** [comment]
UPDATED: you know what, i hate docker now...

I kept getting errors about mapping docker file and i kept wondering why? i kept looking on examples online to find how to edit it and my god i kept getting errors because of i used tabs instead of spaces, Really?

this helped me: https://stackoverflow.com/a/57361302

Thats why i asked you if my way was correct, Thanks for helping tho really helped me
