### ISSUE TITLE
[Bug] non-JS player

### ISSUE THREAD

**Issue by TechnicalSuwako** [iv-org/invidious#2405]
**Describe the bug**
If you disable JS, the player's right side will spill.

**Steps to Reproduce**
If you disable JS, you'll know.

**Screenshots**
with JS
![with JS](https://some.very.questionable.website/Screenshot_20210915_200248.png)

no JS not yet fix
![no JS not yet fix](https://some.very.questionable.website/Screenshot_20210915_200232.png)

no JS with fix
![no JS with fix](https://some.very.questionable.website/Screenshot_20210915_200545.png)

**Comment by TechnicalSuwako** [comment]
You can see an example in my instance.　→　https://youtube.076.ne.jp/watch?v=ybpDr25fwns

**Comment by syeopite** [comment]
Closed by #2405
