### ISSUE TITLE
[Feature request] Optionally track watch time

### ISSUE THREAD

**Issue by HurricaneDancer** [iv-org/invidious#2408]
**Is your feature request related to a problem? Please describe.**

Sometimes I do not finish watching a video in one sitting, but I would like to watch it later. However, Invidious does not remember your watch time. 

**Describe the solution you'd like**

A new preference option that can be enabled and disabled, that tracks a users watch time per video. 

**Describe alternatives you've considered**

Writing down the watch time on a note, but this is not a very good user experience.

**Comment by syeopite** [comment]
Related: #2024

**Comment by unixfox** [comment]
Is https://github.com/iv-org/invidious/issues/2024 exactly what you are asking? If so then please close this issue :)
