### ISSUE TITLE
Could not check out a connection in 2.0 seconds (DB::PoolTimeout)

### ISSUE THREAD

**Issue by jhdohrmann** [iv-org/invidious#2411]
Title: `Could not check out a connection in 2.0 seconds (DB::PoolTimeout)`
Date: `2021-09-17T05:29:29Z`
Route: `/watch?v=gHhUAO8lqt8&iv_load_policy=1`
Version: `2021.08.31-b23f5feb @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 2.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:538:9 in 'checkout'
  from src/invidious/helpers/utils.cr:35:14 in '_post_json'
  from src/invidious/helpers/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:966:10 in 'fetch_video'
  from src/invidious/videos.cr:948:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment]
Looks like the instance you're using is having database issues. Please select another one from https://redirect.invidious.io. For more information, [please refer to the FAQ.](https://github.com/iv-org/documentation/blob/master/FAQ.md#q-could-not-check-out-a-connection-in-20-seconds-dbpooltimeout)

**Comment by jhdohrmann** [comment]
I'd kindly ask to make this an enhancement request. If the condition is undesired but considered a sort of "everyday" condition and not an error of the invidious code, it should give users a user-friendly message, instead of a apparently technical error message, a stack-trace and the request to open a GitHub Issue ...

**Comment by unixfox** [comment]
> I'd kindly ask to make this an enhancement request. If the condition is undesired but considered a sort of "everyday" condition and not an error of the invidious code, it should give users a user-friendly message, instead of an apparently technical error message, a stack-trace and the request to open a GitHub Issue ... 
> 

We are already tracking this bug here: https://github.com/iv-org/invidious/issues/1582

Which instance were you using that you got an error?

**Comment by jhdohrmann** [comment]
Hello unixfox, 

thank you for your quick reply. I'm sorry, but I were using several instances at that time and couldn't say which one it was, for sure. 

Best regards
