### ISSUE TITLE
[Enhancement] Disable indexing in robots.txt

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2418]
**Is your enhancement request related to a problem? Please describe.**

Invidious instances are getting indexed, this cause various issues, including the fact some instances that are considered untrustworthy appear before the project itself (Github, or website).

**Describe the solution you'd like**

We either disallow everything, or just allow the homepage to be indexed.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by unixfox** [comment]
You can't really completely remove the root path (`/`) of a website from Google, once google found out about the domain, then it will index it. Maybe not the other pages, but at least the root path it will be indexed.

If you want to get the invidious.io domain at the very top then you must properly implement the SEO, that's what I did with a lot of my domains and I never had such issues.
