### ISSUE TITLE
I had to apply some fixes to `install.sh`

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#2425]
I had to apply some fixes to `install.sh` as when I run it with `bash -x install.sh` I get some strange output:
````
+ _install_apt
++ command -v wget
+ [[ -z '' ]]
+ [[ -f /etc/apt/sources.list.d/crystal.list ]]
+ aptitude update
````
This is only an excerpt. The debug lines are NOT the strange output here. ;-) But the empty string in `[[ -z '' ]]` is. I found out that your script does this here:
````
if [[ -z "$(command -v wget &> /dev/null)" ]] || [[ -z "$(command -v gpg &> /dev/null)" ]]; then
````
While it has to be:
````
if [[ -z "$(command -v wget 2> /dev/null)" ]] || [[ -z "$(command -v gpg 2> /dev/null)" ]]; then
````
to suppress any error output. Maybe a typo? Maybe you also want to centralize `$(command -v foo)` in a function like `detect_binary()` and `$1` is the executable command to look for?

_Originally posted by @Quix0r in https://github.com/iv-org/invidious/issues/2314#issuecomment-925390257_

**Comment by syeopite** [comment]
Isn't this an upstream issue? This should've been transferred to crystal-lang/distribution-scripts

**Comment by unixfox** [comment]
Closing as it's an upstream issue, @Quix0r please open an issue on https://github.com/crystal-lang/distribution-scripts
