### ISSUE TITLE
Related videos within the video player interface.

### ISSUE THREAD

**Issue by accessiblepixel** [iv-org/invidious#2431]
Good day folks,

I've been trying out Invidious as a replacement to YouTube's AI and I really like it. I am very appreciative of the time it has taken to write, however I am having a problem which is that the related videos don't appear at the end within the player (either when it's still in the page, or when it's full screen).

I know that some people would prefer the less distraction of not having the related videos appear within the video frame, but it causes me a bit of an issue.

Sometimes when I can't really move in bed due to my health, I'd like to be able to keep the video player full screen and then click through to the next or a related video without having to come out of full screen, click a related video, then go back to full screen.

My friend said it might be doable with some CSS trickery, but I wouldn't know where to start in adding this feature myself. It just makes using an invidious instance a bit more difficult for me, especially when I'm wiped out and have little energy.

Apologies if I have posted this in the wrong place. If it's in the wrong place, please move it to where is more appropriate.

Thanks for reading and I look forward to any replies.

Kind regards,
Jessica

**Comment by accessiblepixel** [comment]
It looks like it's mentioned in #2395 as a feature. I tried searching through open issues first, but since it wasn't in the title, I couldn't find it. It would be great if this could be added! :)

~ Jessica

**Comment by unixfox** [comment]
If it was mentionned as an issue in #2395, can we close your issue?

**Comment by accessiblepixel** [comment]
Hi @unixfox,

If that's how it's tracked, sure. I just saw in the original thread that it was kind of a "master thread" that linked to others that actually tracked each one that was listed, so I figured having a thread that could be linked to so track the issue specifically was the right way around.

It also looked like they weren't sure if anyone needed or wanted the feature. I'm also not great at GitHub, so I'm sorry if I've done this wrong. Please do whatever is most appropriate for the project!

Kind regards,
Jessica

**Comment by unixfox** [comment]
I've added your github issue as an idea for the task "Related videos in full screen?"

I'll close your issue as it is tracked in #2395.
