### ISSUE TITLE
[Bug] Searching for videos on a channel by oldest upload loops the first page.

### ISSUE THREAD

**Issue by SkMyPP** [iv-org/invidious#2436]
Go to any channel on any instance, sort the videos by oldest, go to the bottom of the page and click "Next page".

Instead of going to the next page, it will loop the first page of results no matter how many times you click "Next page" when sorting by oldest uploads.

**Comment by SamantazFox** [comment]
Thanks for reporting this issue :)

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898
