### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by Lukas2112** [iv-org/invidious#2445]
Would a Mastodon account for this project be possible?

**Comment by unixfox** [comment]
Why would we run a mastodon account? For publishing the news about Invidious?

**Comment by Lukas2112** [comment]
> Why would we run a mastodon account? For publishing the news about Invidious?

That would be my main idea.

**Comment by Lukas2112** [comment]
> Why would we run a mastodon account? For publishing the news about Invidious?

It could also serve as an exchange with the community?

**Comment by SamantazFox** [comment]
I think @TheFrenchGhosty wanted some more social media presence. We'll see if he wants to :)

**Comment by TheFrenchGhosty** [comment]
It's planned yes. I just haven't took the time to do it.

**Comment by leethax666** [comment]
Yeah I'd love to follow the project on Mastodon, ActivityPub video comments might be cool but that's a whole different issue

**Comment by Lukas2112** [comment]
> It's planned yes. I just haven't took the time to do it.

If it is desired, I am happy to support? :)

**Comment by TheFrenchGhosty** [comment]
@Lukas2112 @leethax666 @gnu1dea @peepopoggers

I just created an account: 

@invidious@social.tchncs.de 

https://social.tchncs.de/@invidious
