### ISSUE TITLE
[Enhancement] Make duration search filters more like YouTube

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#2464]
**Is your enhancement request related to a problem? Please describe.**

Sometime during 2020, YouTube renamed the search duration filters from:

`Short (< 4 minutes)`
`Long (> 20 minutes)`

to:

`Under 4 minutes`
`Over 20 minutes`

and added the additional `4 - 20 minutes` option.

**Describe the solution you'd like**

Invidious should follow through with this naming change, and add the `4 - 20 minutes` option.

**Describe alternatives you've considered**

Don't follow suit.

**Additional context**

**Comment by SamantazFox** [comment]
Fixed by #2956
