### ISSUE TITLE
[Enhancement] docker-compose.yml: suggestion to change Network setting

### ISSUE THREAD

**Issue by bashforever** [iv-org/invidious#2486]
I am no docker expert at all, but the current ports setting in docker-compose.yml (in the installation instructions) seems to restrict usage to the local machine where the stack is running:
- "127.0.0.1:3000:3000" 

Maybe this should be replaced with
- 3000:3000/tcp

This change made my private invidious instance reachable within my LAN,
Thanks!

**Comment by unixfox** [comment]
We are restricting Invidious to localhost by default because most people just need Invidious for themself.

You can just change the ports yourself.

**Comment by bashforever** [comment]
I totally understand - thanks for the fast answer.
