### ISSUE TITLE
[Bug] Unable to sign in

### ISSUE THREAD

**Issue by lzap** [iv-org/invidious#2509]
**Describe the bug**
I am unable to sign in (create an account). After I enter a username and a password, I am taken back to the popular page. No errors, no messages, nothing. I still see the "Login" link in the top-right corner like if nothing happened.

**Logs**
```
[production] Invidious is ready to lead at http://0.0.0.0:9080
2021-10-14 18:07:05 UTC [debug] RefreshChannelsJob: Refreshing all channels
2021-10-14 18:07:05 UTC [debug] RefreshChannelsJob: Done, sleeping for one minute
2021-10-14 18:07:08 UTC [info] 302 GET / 224.86µs
2021-10-14 18:07:08 UTC [info] 200 GET /feed/popular 551.85µs
2021-10-14 18:07:10 UTC [info] 200 GET /login?referer=%2Ffeed%2Fpopular 539.1µs
2021-10-14 18:07:14 UTC [info] 302 POST /login?referer=%2Ffeed%2Fpopular&type=invidious 68.01ms
2021-10-14 18:07:14 UTC [info] 200 GET /feed/popular 163.6µs
```

Config:

```
admins: ["user"]
captcha_enabled: false
channel_threads: 1
database_url: postgres://x:x@localhost:5432/invidious
domain: 192.168.1.2
feed_threads: 1
full_refresh: false
hsts: false
https_only: false
log_level: All
login_enabled: true
port: 9080
registration_enabled: true
```

**Additional context**

My instance is running internally on my LAN, the system has no DNS so I am accessing it by IP.

I also disabled captcha as I do not need it. I tought that is untested scenario so I also tried with captcha enabled, but no change - it still gets me back to the page.

I am on 39c27f0c66b82f04a190a0d8dc4e5a7023f066cc (latest commit).

Thanks.

**Comment by TheFrenchGhosty** [comment]
No news for 2 weeks, this is assumed to be a miss-configuration.

**Comment by lzap** [comment]
Hey, wow 2 weeks that is strict, I like this attitude. With over 300 notifications and 135 opened PRs it is definitely challenge for me, sorry for not showing up earlier.

So I changed the domain name to `nuc.home.lan` which is my servers hostname and DNS name. No change, I am getting the very same result.

I am on `master` from today, rebuilt on Crystal 1.2.2.

**Comment by lzap** [comment]
I deleted all my users from the DB, now I am getting:

```
Title: `relation "subscriptions_94c752494c2c9dcfca3edd2f4522fa1e5c9f67e81132f32a8" already exists (PQ::PQError)`
Date: `2021-12-14T09:30:42Z`
Route: `/login?referer=%2Ffeed%2Fpopular&type=invidious`
Version: `2021.12.12-7f3ef122 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
relation "subscriptions_94c752494c2c9dcfca3edd2f4522fa1e5c9f67e81132f32a8" already exists (PQ::PQError)
  from lib/pg/src/pq/connection.cr:203:7 in 'handle_error'
  from lib/pg/src/pq/connection.cr:186:7 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'read'
  from lib/pg/src/pq/connection.cr:414:31 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:413:5 in 'expect_frame'
  from lib/pg/src/pg/result_set.cr:40:15 in 'move_next'
  from lib/db/src/db/result_set.cr:39:13 in 'perform_exec'
  from lib/db/src/db/statement.cr:85:9 in 'perform_exec_and_release'
  from lib/db/src/db/statement.cr:70:7 in 'exec:args'
  from lib/db/src/db/pool_statement.cr:19:30 in 'exec:args'
  from lib/db/src/db/query_methods.cr:275:7 in 'exec'
  from src/invidious/routes/login.cr:463:12 in 'login'
  from src/invidious.cr:317:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>
```

**Comment by lzap** [comment]
I dropped all tables, recreated them from scratch, the same problem :-(

All I can get is redirect to `/feeds/popular` as a unlogged user.

**Comment by unixfox** [comment]
Which postgresql version do you have?

**Comment by SamantazFox** [comment]
> Hey, wow 2 weeks that is strict, I like this attitude. With over 300 notifications and 135 opened PRs it is definitely challenge for me, sorry for not showing up earlier.

Sorry for that :/

> So I changed the domain name to `nuc.home.lan` which is my servers hostname and DNS name. No change, I am getting the very same result.

Okay, thanks for trying!

> I deleted all my users from the DB, now I am getting:
> 
> Title: `relation "subscriptions_94c752494c2c9dcfca3edd2f4522fa1e5c9f67e81132f32a8" already exists (PQ::PQError)` Date: `2021-12-14T09:30:42Z` Route: `/login?referer=%2Ffeed%2Fpopular&type=invidious` Version: `2021.12.12-7f3ef122 @ master`
> Backtrace
> [SNIP]

Can you try the following?
```sql
DROP MATERIALIZED VIEW subscriptions_94c752494c2c9dcfca3edd2f4522fa1e5c9f67e81132f32a8
```

We use "materialized views" to make personalized feeds, but it often causes issues (We have a PR to remove that). Bu removing it, it will very probably "unlock" the user creation process.

**Comment by lzap** [comment]
I am on Fedora 35:

```
$ rpm -q postgresql
postgresql-13.4-2.fc35.x86_64
```

Dropped the view and I am in! Superb! This is weird, I dropped the db completely and recreated from scratch.

Now when I go to my subscriptions (there should be none it is a fresh account) I do get: Title: `relation "subscriptions_94c752494c2c9dcfca3edd2f4522fa1e5c9f67e81132f32a8" does not exist (PQ::PQError)`

It is the one that I removed. So not sure what to do now :-)

**Comment by unixfox** [comment]
For future visitors, I recommend trying to reinstall postgresql from scratch if possible.

**Comment by lzap** [comment]
For the record: it was the domain, then it somehow corrupted my database. I was accessing via IP address. Thanks! Closing.

**Comment by alejandrogallo** [comment]
> Could you try to remove `domain` from your configuration?
> 
> This option is intended to tell invidious about the domain name (`example.com`) under which it is hosted, so in your case, where the instance is being directly accessed from a local address, this may interfere with the session cookie.

Just wanted to give my 2 cents, this option worked for me, I could not log in from a reverse proxy with let's encrypt
certificates, and I was having as a domain on the computer where invidious runs `domain = 0.0.0.0` which was
the problem!
