### ISSUE TITLE
[Bug] Unable to launch Invidious

### ISSUE THREAD

**Issue by balasratran** [iv-org/invidious#2516]
I used `Invidious-Updater` to install Invidious (regular install). Everything installs successfully but I cannot launch localhost:3000. I check `sudo netstat -tunlp` and it doesn't see invidious running and listening.

![screenshot_1634188169](https://user-images.githubusercontent.com/26430195/137491870-8f8ccdb7-8e30-4256-8e0e-4cbd3f4ad102.png)
![screenshot_1634188189](https://user-images.githubusercontent.com/26430195/137491878-00cc31d8-b0fc-4943-b820-8e14513825c0.png)

**Comment by unixfox** [comment]
Closing as it's an issue for Invidious-Updater: https://github.com/tmiland/Invidious-Updater/issues/73.
