### ISSUE TITLE
[Bug] Invidious sometimes(quite often really) crashes with a SIGSEV error on chromium.

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#2520]
**Tested On**
1. yewtu.be
2. invidious.pussthecat.org

With same settings on both sites.

**The bug**
When playing some videos, invidious will crash on chromium with a SIGSEV error.  Could be related but weirdly enough if I hold down my "Fn" key for sometime it seems to crash although I'm not too sure that is the problem, it certainly might help. Sometimes not going fullscreen seems to help but it's really iffy as to when exactly it will fail working. 

NOTE that: I have enabled proxying the video as well as set auto vid quality to dash and dash quality to 480p.

It either looks like - 

![image](https://user-images.githubusercontent.com/85624218/137593076-6407e914-c41e-486b-9f23-796ec230ccf9.png)

OR

![image](https://user-images.githubusercontent.com/85624218/137593106-b14a2627-ea9d-4107-8a75-497b79199c4e.png)

**Invidious Settings**

![image](https://user-images.githubusercontent.com/85624218/137593180-31500ac2-9f11-4ebd-89d9-fcf8be2545cb.png)

![image](https://user-images.githubusercontent.com/85624218/137593188-1a632cce-8859-4e6d-a21b-1aec2543f55e.png)

**Steps to Reproduce**
1. Go to invidious
2. Open up video
3. Hit play and full screen
4. Wait
5. Sometimes it crashes sometimes it doesn't.

**System Information**
OS - Arch Linux 64 bit
Kernel - 5.14.11-arch1-1
Browser - Chromium Version 94.0.4606.81 (Official Build) Arch Linux (64-bit)
WM - i3 running on Xorg
Audio Implementation - Pipewire only(no pulseaudio, I use pipewire-pulse)
Laptop - HP Probook 400 G2 (no battery attached, running on wall supply)

**Installed Browser Extensions**
![image](https://user-images.githubusercontent.com/85624218/137593201-7857ef07-057c-462b-a28c-2cf824f7f898.png)

**Comment by syeopite** [comment]
> video append of 43690b failed for segment #0 in playlist 0-placeholder-uri

I've experienced this error before but it's with an upgraded videojs version and never with the version Invidious uses. Maybe YouTube has been rolling out some changes?

**Comment by kibybyte** [comment]
> I think it's probably a browser issue on your side because I never had any browser crash before on invidious.

It doesn't happen on any other site.

**Comment by 11Tuvork28** [comment]
I mean you don't have to test every instance, just test one or two.
Did this issue occur after a recent system update? and if so was a browser update involved?

**Comment by kibybyte** [comment]
>Did this issue occur after a recent system update? and if so was a browser update involved?

I am not entirely sure on this but I don't really think so, I think the issue popped up out of the blue even before the last time I updated. I am updating my system rn and there is a linux update but no chromium update, maybe this update will make the issue go away or something? idk let's see what happens.

**Comment by 11Tuvork28** [comment]
Yeah well seems like this is a problem with your system configuration. Maybe try disabling all extensions if that doesn't help stick to another browser at least that is what I would be doing, anyways I hope I could help you a little bit :)

**Comment by kibybyte** [comment]
UPDATE: I disabled the option to proxy videos and the issue still persists :(

**Comment by kibybyte** [comment]
@SamantazFox exactly what I am suspecting since it works well in firefox.

**Comment by SamantazFox** [comment]
Closing this issue, as OP has deleted their account, and we've updated VideoJS, which might have fixed the problem (but we won't know if it's the case).
