### ISSUE TITLE
[Bug] Where is the 1080p ?

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2521]
**Describe the bug**
I'd like to play videos in 1080p, but it seems not possible anymore. I have the choice between "720p" and "medium" and that's all. And all videos i tested have a 1080p version.

**Steps to Reproduce**

1. Go to any video

**Screenshots**
![Screenshot_20211017_165828](https://user-images.githubusercontent.com/22192600/137633093-966930e1-47d8-473f-ac98-705334c2729e.png)

![Screenshot_20211017_170049](https://user-images.githubusercontent.com/22192600/137633098-b52adeb6-0a59-4493-929e-ad4a4fd6448e.png)

**Additional context**

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/187
