### ISSUE TITLE
video controls covering parts of the video

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#254]
Since YouTube switched from putting the video controls below the video to into the video frame this has become a de-facto standard. However i always found this irritating and it becomes a problem if you want to read subtitles or make a screenshot. there was never really a reason for this trend other than copying the big player. It's neccessary for fullscreen and it looks nice but video controls do not have to look ugly either. But even if you dont want to waste the space(of which todays websites waste plenty for far less useful stuff) or dont like the looks you could still make the controls extend to below the video instead of covering up the image.

so my suggestion is to leave it just like it currently is except let it slide downwards if video.js and html allow for this.

**Comment by BaconCatBug** [comment]
No chance this can be a thing? :( Even if it's an option to force the playback to always be visible below the video.

**Comment by elypter** [comment]
wow, thanks. works great. i hope this gets merged into invidio.us
