### ISSUE TITLE
[Bug] Page subscriptions in error if empty

### ISSUE THREAD

**Issue by clecle226** [iv-org/invidious#2548]
**Describe the bug**
The subscription page comes out with an error when trying to display it, while there is no channel subscription. 
*Original:
La page de souscription sort une erreur lorsqu'elle on essaye de l'afficher, alors que il n'y a aucun abonnement de chaine.*

**Steps to Reproduce**
1. Create a new user 
2. Go to /feed/subscriptions

**Logs**

Title: `la vue matérialisée « subscriptions_c4735ba2c3ef7b42ccfd087fa446473c93007193688b8a858 » n'a pas été peuplée (PQ::PQError)`
Date: `2021-10-30T09:18:23Z`
Route: `/feed/subscriptions`
Version: `2021.10.26-6f19a3a2 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
la vue matérialisée « subscriptions_c4735ba2c3ef7b42ccfd087fa446473c93007193688b8a858 » n'a pas été peuplée (PQ::PQError)
  from /usr/share/crystal/src/primitives.cr:266:3 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'query_all:as'
  from /usr/share/crystal/src/reference.cr:28:3 in 'get_subscription_feed'
  from src/invidious/routes/feeds.cr:96:29 in 'subscriptions'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

I tried to put a condition in the file "src / invidious / routes / feeds.cr", but I could not find a place that returned a simple message to the user like "You have not subscribed to no chain. " 
*Original:
J'ai cherché à mettre une condition dans le fichier "src/invidious/routes/feeds.cr", mais je n'ai pas trouvé d'endrois que renvoyé un message simple à l'utilisateur genre "Vous n'avez souscrits à aucne chaîne."*

**Comment by SamantazFox** [comment]
Hello! Your problem is likely caused by a bad database migration or a corrupted database.
Is that a fresh install? Also, are you the only user?

If you're the only user, you probalby want to drop the `users` and `session_ids` tables, and recreate them.
If you're not alone on that instance, delete the entries in `users` and `session_ids` where `email = your_username`

Also remove the materialized view that was created for your account:
`DROP MATERIALIZED VIEW subscriptions_c4735ba2c3ef7b42ccfd087fa446473c93007193688b8a858`

**Comment by clecle226** [comment]
Hello,

It was a very fresh installation, and I was the only user.
(I don't know what happened.)
I dropped the materialized view, and after 1 hour, he managed to recreate the view all by himself ....
Well, I don't know what happened, but it works, thanks for helping me. ^^ 

*Original:
C'était bien un installation toutes fraiche, et j'étais bien le seul utilisateur.
(Je sais pas ce qu'il c'est passé.)
J'ai drop la vue matarialisé, et après 1h, il à réussi à recréer tout seul la vue....
Bon ba je sais pas ce qu'il c'est passé, mais ça marche, merci de m'avoir aidée. ^^*
