### ISSUE TITLE
[Enhancement] Dark Scrollbars

### ISSUE THREAD

**Issue by TheAresjej** [iv-org/invidious#2550]
It would be a nice improvement if changing the colour of the page would also adjust the colour of the scroll bar.

**stackoverflow:**
https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does

**Comment by unixfox** [comment]
Would you consider contributing in order to add this new feature? We can help you in contributing.

**Comment by SamantazFox** [comment]
This is currently not supported by all browsers, and furthermore, this hasn't been standardized yet, so it may change in the future. https://caniuse.com/css-scrollbar

Better wait for this to be standard before doing anything.
