### ISSUE TITLE
Still shows reddit comment button while YouTube is set to default comment

### ISSUE THREAD

**Issue by hellojaccc** [iv-org/invidious#2551]
![Screenshot_20211031_172304](https://user-images.githubusercontent.com/71537512/139574375-f64983fc-d85e-4eb8-bfff-e4f2b9ecc069.png)
^ Only YouTube is selected in default comment
![Screenshot_20211031_172425](https://user-images.githubusercontent.com/71537512/139574392-f1f4fbdd-804b-4947-aed5-0527b0d1b125.png)
^ It still shows 'show reddit comment' button

**Comment by SamantazFox** [comment]
Hello! Thanks for reporting this issue :) Could you please give more details about this issue, like the instance URL and/or version (this can be found in the footer of the webpage)?

**Comment by hellojaccc** [comment]
Hi, thanks for looking.

`invidious.osi.kr`
`2021.10.26-2b81a82 @ master`

It also happens on English language.

**Comment by SamantazFox** [comment]
Ok, so I checked the source code, and it's a deliberate design made by @omarroth:
* When you select youtube comments, it will show a "view reddit comments" link
* and vice-versa, when you select reddit comments, it will show the link to get the youtube ones.

**Comment by hellojaccc** [comment]
Lots of video i watch doesn't have reddit comment, so it's not useful for me.

I think not selecting `reddit comments` in settings should show no `reddit comments` button
