### ISSUE TITLE
Allow other websites to use invidious as a video proxy (CORS headers)

### ISSUE THREAD

**Issue by Objectful** [iv-org/invidious#2554]
I'm trying to make an invidious based youtube frontend and the old YouTube player JS requires CORS on video stream urls. Because this currently doesn't exist in the code, I get spammed with such errors: 
![image](https://user-images.githubusercontent.com/73402079/139741094-37e743a5-9599-4933-84a5-13005b3cd624.png)
Will this be added? Thanks.

**Comment by SamantazFox** [comment]
Hello! By default, CORS don't allow another website to use videos streams. This is because it's kinda heavy on bandwitdth, and it's preferrable to run your own video proxy. See with the instance owner if they accept that you use their instance as a video proxy.

**Comment by unixfox** [comment]
Closing as it's not an issue introduced by us, but a default protection used by browsers when no CORS headers are specified by the HTTP server. Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information.

If you want to use a specific instance as a proxy, then please contact the owner of the Invidious instance.
