### ISSUE TITLE
Can you request replies in invidious without using continuations?

### ISSUE THREAD

**Issue by Objectful** [iv-org/invidious#2559]
I'm trying to make it so that in the comments, 2 replies will be automatically shown with the comment and the rest will be shown after clicking show more. If this doesn't explain it, I will attach a screenshot: 
![image](https://user-images.githubusercontent.com/73402079/140171163-94c46c31-ca0b-469b-89eb-21f05b312532.png)
I am doing this in PHP. Thanks.

**Comment by unixfox** [comment]
Are you using the invidious API?

**Comment by Objectful** [comment]
> Are you using the invidious API?

Yes.

**Comment by unixfox** [comment]
You can't retrieve the replies of a comment without using the continuation token, that's how youtube works unfortunately.
