### ISSUE TITLE
Video controls not available after play has been clicked

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#256]
Browser: Icecat  based on Firefox ESR

Video: https://invidio.us/watch?v=FwuPXchH2rA

![Wait till this gif loads...](https://my.mixtape.moe/yapgjl.gif)

After I click play the video starts playing and player controls disappears.

**Comment by omarroth** [comment]
I'm having trouble reproducing this in Icecat, do you have any of `autoplay`, `volume`, or other player preferences enabled? Are devtools showing any errors?

**Comment by Avizini** [comment]
### Player Preferences

- Autoplay/ Always loop/ Autoplay next video, Listen by default: Disabled
- Preferred video quality: medium
- Default comments: reddit (fallback youtube)
- Volume:  100
- Show related video: Disabled

> Are devtools showing any errors?

I don't know what that is, console shows this.

```
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
video.min.js:1:30651
Specified “type” attribute of “video/mp4; codecs="avc1.64001F, mp4a.40.2"” is not supported. Load of media resource https://r3---sn-ab5l6n67.googlevideo.com/videoplayback?ei=FuYHXJK6Lcms8wSY7aPoDQ&expire=1544043126&c=WEB&source=youtube&mime=video%2Fmp4&key=yt6&initcwndbps=215000&fvip=3&requiressl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&txp=4535432&mn=sn-ab5l6n67%2Csn-ab5szne7&ipbits=0&ratebypass=yes&ip=2604%3Aa880%3A400%3Ad1%3A%3A7b1%3A7001&mm=31%2C29&itag=22&ms=au%2Crdu&mt=1544021355&signature=E09C044CC76143810D3FEC9AC6568C1D32E276F9.E270CB09AE7275F0DCCFD4BFFA91813F482BD992&mv=m&id=o-AKwm8srC6bLvesNhDhQ0I1FcHvExhcWlmcXeZQ_5wOlt&dur=271.673&lmt=1543432584971035&pl=48 failed.
watch
passive_improve_css.js
```

**Comment by omarroth** [comment]
Everything appears to be working fine. Are there any extensions installed that might be causing problems?
