### ISSUE TITLE
[Enhancement] Switch to innertube for the captions - captions do not work on public instances

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#2567]
**Is your enhancement request related to a problem? Please describe.**
The current way of retrieving the captions is rate limited by google and captions doesn't work on popular instances.

**Describe the solution you'd like**
We should switch to the innertube for retrieving the captions because on innertube there is no rate limit (for the moment).

**Describe alternatives you've considered**

Install and use Invidious locally or switch to a less popular instances from https://instances.invidious.io

**Additional context**
Related to https://github.com/iv-org/invidious/pull/2519 and https://github.com/iv-org/invidious/issues/2565

**Comment by syeopite** [comment]
Possible solution #2564

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898

**Comment by rottenstonks** [comment]
I can personally offer $80 worth of XMR on top of the $20 worth of BTC from the Invidious project, to be claimed by whoever opens a PR switching to innertube.

Please ping me here, or via Matrix should there be any news or comments; will try to keep an eye open regardless.

**Comment by unixfox** [comment]
About https://github.com/iv-org/invidious/blob/master/src/invidious/routes/api/v1/videos.cr#L34

timedtext API does now provide links for auto-generated captions. Could this replace the current implement of getting the captions?

**Comment by tuxayo** [comment]
How does newpipe does it? Is it because it does it directly so it's not rate limited at the expense of a risk of user tracking?

Due to the elapsed time, is this less work-demanding solution worth considering as an alternative? : if proxy is disabled, then do the request for subtitles directly from user's browser.

**Comment by tuxayo** [comment]
request: rename the issue "Captions don't work on popular instances" or something like that so people can more simply find it. And it's not an enhancement, it's a bug.

**Comment by unixfox** [comment]
> How does newpipe does it? Is it because it does it directly so it's not rate limited at the expense of a risk of user tracking?

Whatever how newpipe does it, newpipe send the request from the IP address of the user so there no rate limit applied as a single user will never do as many requests as a Invidious instance.

**Comment by TheHolyTachanka** [comment]
Any updates on this?

**Comment by unixfox** [comment]
> Any updates on this?

No nobody had the time to work on it yet.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/4001 in testing on https://yewtu.be

**Comment by RadoslavL** [comment]
@rottenwheel syeopite seems to have solved the issue. They created a PR that is now merged.

**Comment by syeopite** [comment]
The fix still needs to be documented though as instances will have to enable `use_innertube_for_captions` within the configs to bring back caption capabilities.
