### ISSUE TITLE
[Enhancement] Redirect/resolve `/channel/brand_name`

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2570]
**Is your enhancement request related to a problem? Please describe.**
Going to `/channel/linustechtips` gives an error saying that the channel info can't be extracted.

I've discovered that I have many bookmarks in the `/channel/brand_name` form, and those doesn't work anymore.

**Describe the solution you'd like**
Either redirect to `/c/channel_name` or resolve the channel's name directly.

**Describe alternatives you've considered**
None.

**Comment by unixfox** [comment]
We can use the resolve_url endpoint of youtube innertube API for that :).

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898

**Comment by syeopite** [comment]
I don't think Invidious should've ever supported `/channel/<brand>` considering the `/channel` endpoint was always meant to be used with only a UUID. It's more of a bug that's now been patched on Invidious' end. 

We should just be a frontend to YouTube that replicates its functionality and nothing more. I personally vote for the bounty to be revoked and this issue to be closed.

**Comment by TheFrenchGhosty** [comment]
>I don't think Invidious should've ever supported /channel/<brand> considering the /channel endpoint was always meant to be used with only a UUID.

It's legacy, it's how youtube used to do it: brands and ID on the same endpoint. We should definitely support it.

**Comment by syeopite** [comment]
I don't think that has ever been implemented in YouTube considering they don't ever seem to remove legacy channel endpoints. `/user` has been deprecated for years and yet `/user/pewdiepie` works.

Assuming `/channel/<brand name>` was a valid endpoint, and YouTube's deprecation cycle is larger than even the life cycle of even `/user`, `/channel/<brand name>` would be such an ancient endpoint that supporting it is useless. 

Plus, if you look at data on archive.org, usage of `/channel/<brand name>` is almost nonexistent and always returns a missing channel.

---

Either way, do you have a `/channel/<brand name>` URL that's either on archive.org or got indexed by Google? I need to look more into this, but from what I can see `/channel/<brand name>` was never an endpoint on YouTube.

**Comment by kubo6472** [comment]
Some [official info](https://outline.com/95m6zt).
