### ISSUE TITLE
[Bug] Translation function is missing on the footer

### ISSUE THREAD

**Issue by Midou36O** [iv-org/invidious#2572]
**Describe the bug**
It seems like translated text doesn't correctly output so it only show the function of that text

**Steps to Reproduce**
Scroll down to the bottom

**Logs**
No need.

**Screenshots**
![image](https://user-images.githubusercontent.com/45198486/140814559-535a185d-c255-4ae6-954f-1e0a498a9a69.png)

**Comment by SamantazFox** [comment]
Thanks for reporting this :)
