### ISSUE TITLE
[Bug] Custom playlist does'nt autoplay

### ISSUE THREAD

**Issue by filt3rek** [iv-org/invidious#2574]
Hi all !

First of all, thanks for your work.

I have a strange behaviour, a custom playlist does'nt play next movie.

When I create a custom playlist, then I add movies to it, starts the first one, then it doesn't go to the next.
All is activated in my preferences, and when I select a movie from the search, it does play right the next suggested movie.

How to do please ? 

The browser here is Brave, but I tried also on Firefox and it does the same.

Thanks for your answer !

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898

**Comment by CatalinCsnMaster** [comment]
Hello!

Can I take this one? 🧰

**Comment by unixfox** [comment]
> Hello!
> 
> Can I take this one? 🧰

Hello, we welcome all the contribution! You are free to take this one :).
