### ISSUE TITLE
Does Invidious keep a record of videos users watch?

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#259]
`Only show unwatched`

Invidious preferences has this option.

**Comment by omarroth** [comment]
Yep. Same as YouTube, you can view (limited) info about watch historyat [/feed/history](https://invidio.us/feed/history). Also see #182.

**Comment by dimqua** [comment]
@omarroth from the first day of their registration? Is the history log rotation implemented?

**Comment by omarroth** [comment]
Correct, I think I'll probably open a new issue to disable tracking watch history. Could you describe what you mean by history log rotation?

**Comment by dimqua** [comment]
Watched videos older than few months should be probably removed from history logs or archived (not displayed at `/feed/history`).

**Comment by Discookie** [comment]
I think that should be an option, because I prefer to look up very old Watched videos of mine.  
Maybe there should be an option like `Store watch history of:` with a dropdown of None / 1 week / 1 month / 1 year / All time.
