### ISSUE TITLE
Cannot load any video,channel or search request.

### ISSUE THREAD

**Issue by Pyran1** [iv-org/invidious#2592]
**Describe the bug**
Invidious cannot load any page because YouTube front-end and back-end has changed(removed dislikes).

**Steps to Reproduce**
1. Go to main page
2. Do any search request or open any video.
3. See error.

**Logs**
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:540:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:14 in '_post_json'
  from src/invidious/search.cr:36:11 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

**Comment by unixfox** [comment]
Please read https://github.com/iv-org/invidious/issues/2577
