### ISSUE TITLE
[Bug] Videos don't play on iOS and iPadOS Safari

### ISSUE THREAD

**Issue by TheNamelessWonderer** [iv-org/invidious#2596]
**Describe the bug**

Videos don't play at all and an error is displayed. This happens with all videos on mobile Safari. Desktop firefox works fine.

**Steps to Reproduce**
1. Open Mobile Safari
2. Go to invidious
3. Click on any video.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/141509173-3abb28e4-ebe3-4e01-9b71-d03c4d057adb.png)

**Additional context**
 - Browser (if applicable): Safari
 - OS (if applicable): iOS 14.8.1 and iPadOS 15.1

**Comment by unixfox** [comment]
Strange I can't reproduce your issue on my iphone SE 2020 with safari too.

Did you try a non music video like this one: https://yewtu.be/watch?v=jNQXAC9IVRw?

**Comment by TheNamelessWonderer** [comment]
That one doesn't play for me either.

**Comment by yungsmoke9** [comment]
Try switching your link, also I find this to be caused by it being blocked by your Wi-Fi

**Comment by TheNamelessWonderer** [comment]
Yep I have. It doesn't load on mobile data either. The PC on the same network as my iPhone plays videos just fine.

**Comment by unixfox** [comment]
Can you reproduce this issue on other instances from this list : https://instances.invidious.io?

**Comment by TheNamelessWonderer** [comment]
I've found out that it plays fine if I'm logged out but as soon as I log in it fails.

**Comment by unixfox** [comment]
> I've found out that it plays fine if I'm logged out but as soon as I log in it fails.

Do you have dash enabled?

**Comment by TheNamelessWonderer** [comment]
nope I'm on hd 720.

**Comment by unixfox** [comment]
> nope I'm on hd 720 with proxy off.

Try with hd720 proxy on

**Comment by TheNamelessWonderer** [comment]
yep that fixes it.

**Comment by unixfox** [comment]
Nice can I close the issue? Btw that's why proxy is on by default on yewtu.be

**Comment by TheNamelessWonderer** [comment]
Sure. Thanks for that. Shouldn't it work without it though?

**Comment by unixfox** [comment]
> Sure. Thanks for that. Shouldn't it work without it though?

Well safari on iOS is weird, so it might send something that google servers don't like and thus return an error.
