### ISSUE TITLE
[Bug] Long usernames overlap into Search bar

### ISSUE THREAD

**Issue by TheNamelessWonderer** [iv-org/invidious#2597]
**Describe the bug**

If your username is very long and the screen is small such as an iPad, it overlaps into the search bar making it hard to see what you are searching for

**Steps to Reproduce**
1. Login with a long username
2. See issue

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/141509764-9acc70c8-7b6c-40ed-845a-8b22d6acfd48.png)

**Additional context**
 - Browser (if applicable): Any
 - OS (if applicable): Any

**Comment by SamantazFox** [comment]
Thanks for reporting this issue! As a temporary workaround, you can uncheck "show nickname on top" in the preferences, effectively hiding the username.

**Comment by TheFrenchGhosty** [comment]
A 5$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 5$ (in BTC) from the Invidious project.

More details: #1898

**Comment by 11Tuvork28** [comment]
I kind of have a fix for that live on my instance but its not pretty. I just added `style="max-height: 16.5px;overflow: hidden;"` but thats neither nice nor worth the bounty but I just wanted to share it anyways.
The oddly specific px number comes from the height of the icons.
