### ISSUE TITLE
Invidious as youtube cache

### ISSUE THREAD

**Issue by theScrabi** [iv-org/invidious#260]
Hei there, I really love invidious :D.

I am living in a student dorm in germany, and we have a really bad internet connection there. This is why we had to limit the data access for everyone who tries to connect to outside of our network. 
I was wondering if Invidious could utilize for example youtube-dl to cache (or precache if subscibed) videos, so if a video gets watched more than once invidious will deliver the locally stored version.

regs Schabi

**Comment by omarroth** [comment]
Not currently.

Invidious does cache video info though, so I could see that being a possible route. An external script would:
- Connect to the Invidious DB and pull list of `ids`
- Use youtube-dl or another tool to download streams, and provide local URLs for them
- Update the `info` field to point to local streams
- Change the `updated` field to far future so Invidious won't overwrite it

I expect that could work very well, and I would be more than happy to help you if you would like to pursue it.
Invidious uses PostgreSQL, and the video schema is [here](https://github.com/omarroth/invidious/blob/master/config/sql/videos.sql).

If you have any questions or issues feel free to contact me on the [FreeTube Matrix Server](https://riot.im/app/#/room/#freetube:matrix.org).

**Comment by elypter** [comment]
if you got access to a faster network you could also cache it locally to watch later. kinda like megaupload works i assume. there are tools to save websites for offline tools but invidious could do this internally as well. there are several mothods to save data locally in the browser aside from cookies. i think localStorage is the one for a purpose like this.

**Comment by omarroth** [comment]
Since there hasn't been any discussion on this issue for several months I'm going to close this, however I would very much like to see something like this exist.

There is now a [Matrix Server](https://riot.im/app/#/room/#invidious:matrix.org) for Invidious if you would like any help writing a script to do something like this. Please feel free to get in touch.

**Comment by traderp** [comment]
I'm interesting in working on this if other developers want to join. My recommendation would be to use IPFS or libp2p. There are viable ways to run node in the browser. End users would maintain their own video cache while Invidious is active. On the server, archive nodes could increase content availability and serve pinned video (and circumvent YouTube censorship).

**Comment by leonklingele** [comment]
@theScrabi you could set up nginx as a reverse proxy for invidious and configure a `proxy_cache`: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache

Untested and unoptimized, but something like this should work:

```nginx
# Outside server-block
# Use a maximum of 100GB for the cache which will be valid for 31 days.
proxy_cache_path /path/to/nginx/cache levels=1:2 use_temp_path=off keys_zone=invidious_cache:10m inactive=31d max_size=100g;
proxy_cache_key "$scheme$request_method$host$request_uri";

server {
# ...
	location ^~ /videoplayback {
		proxy_pass http://invidious_hostname:3000;
		proxy_http_version 1.1;
		proxy_set_header Connection "";

		proxy_cache invidious_cache;
		proxy_cache_valid 200 31d;
	}
# ...
}
```

**Comment by leonklingele** [comment]
I have updated my comment above, caching of videos with nginx works fine now.
