### ISSUE TITLE
[Bug] Unexpected char '<' at line 1, column 1 (JSON::ParseException)

### ISSUE THREAD

**Issue by skelish** [iv-org/invidious#2606]
Title: `Unexpected char '<' at line 1, column 1 (JSON::ParseException)`
Date: `2021-11-13T09:32:21Z`
Route: `/data_control?referer=%2Ffeed%2Fhistory`
Version: `2021.11.12-d214a0b3 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:331:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:213:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment]
Did you try to import a csv file?

**Comment by skelish** [comment]
> Did you try to import a csv file?

no opml flle

**Comment by shnappi-kk** [comment]
Same here. This error appears on search pages, channels or videos. Reloading the page fixes the problem, but after 5-10 minutes of inactivity it appears again.
I am using my private instance.

Title: `Unexpected char '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-11-13T14:07:56Z`
Route: `/search?q=do+som+search+pls`
Version: `2021.11.12-d214a0b3 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '' at line 1, column 1 (JSON::ParseException)
  from /usr/lib/crystal/json/lexer.cr:331:7 in 'raise'
  from /usr/lib/crystal/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/lib/crystal/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/lib/crystal/json/lexer/string_based.cr:63:8 in 'next_token'
  from /usr/lib/crystal/json/parser.cr:13:12 in '_post_json'
  from src/invidious/search.cr:36:11 in 'search'
  from src/invidious/search.cr:232:20 in 'search'
  from /usr/lib/crystal/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:171:14 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by shnappi-kk** [comment]
Little update. That error never appears on main page, /popular, /subscription, /playlists, /subscription_manager, /history and /settings. Only on trending, search, channel, community, etc.
The details in the backtrace remain the same.

**Comment by unixfox** [comment]
> Little update. That error never appears on main page, /popular, /subscription, /playlists, /subscription_manager, /history and /settings. Only on trending, search, channel, community, etc. The details in the backtrace remain the same.

Are you using a public instance? If so which one?

**Comment by shnappi-kk** [comment]
I use my private instance, deployed on Arch using a Invidious-Updater 1.5.9, w/o docker.

**Comment by unixfox** [comment]
> I use my private instance, deployed on Arch using a Invidious-Updater 1.5.9, w/o docker.

Do you have `use_quic` to true in your config file?

**Comment by shnappi-kk** [comment]
False, with true content-related pages not loading.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898

**Comment by matthewmcgarvey** [comment]
So I think shnappi-kk's error is unrelated tot eh OP's. The error as I understand it currently is that users are in `/data_control` and attempting to import OPML files from Invidious instances into the "Import Invidious Data" option and it's failing.

If that is the case then I believe that the error isn't in the backend (at least primarily) but in the naming of the options.
It's the "Import Youtube subscriptions" option that can handle those OPML files and the "Import Invidious Data" is only for the resulting JSON file when clicking "Export data as JSON".

So we could update the wording of these options to better clarify what they can handle or will give, and we could also update the endpoints to fail in a more descriptive way for the users.
