### ISSUE TITLE
[Feature request] podman support

### ISSUE THREAD

**Issue by 706f6f7079646f6f646f6f** [iv-org/invidious#2628]
**Is your feature request related to a problem? Please describe.**

podman not work by default.

**Describe the solution you'd like**

podman work by default.

**Describe alternatives you've considered**

edit file on disk.

**Additional context**

default registry bad idea https://github.com/iv-org/invidious/pull/2626

**Comment by unixfox** [comment]
Closing as I prefer to continue the discussion about podman in this PR: https://github.com/iv-org/invidious/pull/2626

**Comment by 706f6f7079646f6f646f6f** [comment]
> Closing as I prefer to continue the discussion about podman in this PR: #2626

very silly, feature request is valid if pr is merged or not
