### ISSUE TITLE
[Bug] Video description is not escaped in <meta> elements

### ISSUE THREAD

**Issue by babababag** [iv-org/invidious#2629]
On `/watch` the video description is not escaped in the `<meta>` `og:description` and `twitter:description` elements in the html head, see screenshot.

![description not escaped](https://user-images.githubusercontent.com/94438705/142191082-ae5162a3-d9c4-4f9c-bac4-0e144a87fb6a.png)

A description with quotation marks or `>` in it might mess up the page's markup (although firefox is coping here).

Not really sure how this could be used maliciously, CSP thankfully blocks a lot here. This probably can't comment out the rest of the page's markup because there's currently a comment right after the `<title>` tag (the string `-->` would end the inserted comment). An inserted comment could stop the stylesheets and videojs being loaded and change the page title. Just what I could think of though.

<details>
<summary>In the CSP `style-src` allows inline styles and `img-src` allows data URLs so something like this is definitely possible.</summary>
<img src="https://user-images.githubusercontent.com/94438705/142196140-6712754f-8fe4-41ea-9078-c55808d3adee.png" alt="Invidious video page but with a repeating image of a big rat as the background.">
</details>

**Comment by SamantazFox** [comment]
poke @TheFrenchGhosty (for a bounty?)

**Comment by TheFrenchGhosty** [comment]
@babababag Thank you a lot for reporting this problem!

For reporting (and fixing) this security issue (technically already reported in #2193 but forgotten) I and most of the organization members would like to reward you with 10$ (in BTC) If you want to receive your reward feel free to send me your BTC address or post it directly in the PR.

Every payment will be, as usual, reflected in the [transparency repository](https://github.com/iv-org/transparency), in our monthly financial reports.

**Comment by babababag** [comment]
@TheFrenchGhosty cool, i think this should work `bc1q4sxhymh3amtgjl36zpu4w2frd55d7g4pp8zs64`

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been rewarded to @babababag for this report.

Transaction (459de3822c3b26024ec7e9db2b51a2f5d4d47336de9e69654242d8ee7ce74521):

Amount sent: 0.0001725 BTC (~8.86€ or ~10$)

Mining fees (10 sat/byte): 0.00000705 BTC (~0.36€)
