### ISSUE TITLE
[Bug] Crystal build fails

### ISSUE THREAD

**Issue by Northernside** [iv-org/invidious#2665]
**Describe the bug**

While running `crystal build src/invidious.cr --release --error-trace` it fails with the following error:
```sh
invidious@raspberrypi:~/invidious $ crystal build src/invidious.cr --release --error-trace
In src/invidious.cr:23:1
 23 | require "pg"
      ^
Error: while requiring "pg"

In lib/pg/src/pg.cr:1:1
 1 | require "db"
     ^
Error: while requiring "db"

In lib/db/src/db.cr:2:1
 2 | require "log"
     ^
Error: can't find file 'log'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

Yes, I already executed `shards install` and I'm in the same directory as the `shard.yml`.

**Steps to Reproduce**

Just install Invidious on a Raspberry Pi 4B 8GB (using http://public.portalier.com/raspbian/ for crystal-lang).

**Logs**

No browser log bc yk it isn't running yet haha
**Screenshots**

![image](https://user-images.githubusercontent.com/60970791/143565826-5b15f36f-e1b5-4bc5-bd76-03cfa773437c.png)

**Additional context**

I'm trying to install Invidious on a **Raspberry Pi 4B** running on **Rasbian** via a 256GB SSD.

**Comment by unixfox** [comment]
Please post your crystal version: `crystal --version`

**Comment by Northernside** [comment]
`crystal --version` output:
```sh
Crystal 0.33.0 (2020-03-02)

LLVM: 5.0.1
Default target: arm-unknown-linux-gnueabihf
```

**Comment by unixfox** [comment]
Please use at least crystal 1.1.0. We don't support older versions.

That's why you are having issues compiling invidious.

**Comment by Northernside** [comment]
That's the thing. The only working method to use crystal on a Raspberry Pi was http://public.portalier.com/raspbian/. But it seems like it's outdated. Do you know any other alternative to use on a Raspberry Pi?

**Comment by unixfox** [comment]
Depending on your raspberry pi version, for example if you have a raspberry pi 3 or 4 then you may consider using our docker image available for ARM64/armv8: https://github.com/iv-org/invidious/issues/361#issuecomment-881047911. You will need a ARM64/ARMv8 operating system though, raspbian support ARM64: https://old.reddit.com/r/raspberry_pi/comments/gs6omd/raspberry_pi_os_for_arm64_finally_released/ or you can use ubuntu core or archlinux arm.

**Comment by SamantazFox** [comment]
@Northernside ARM has no official releases, so you'll either have to use docker, as recommended by unixfox, or follow the instructions to install crystal from source: https://crystal-lang.org/install/from_sources/

**Comment by Northernside** [comment]
> @Northernside ARM has no official releases, so you'll either have to use docker, as recommended by unixfox, or follow the instructions to install crystal from source: https://crystal-lang.org/install/from_sources/ (NB: this requires cross-compilation at some poinf from a x86 or x86_64 host).

I tried the Docker variant now but the terminal is spammen with `standard_init_linux.go:219: exec user process caused: exec format error`. What should I do?

**Comment by unixfox** [comment]
> > @Northernside ARM has no official releases, so you'll either have to use docker, as recommended by unixfox, or follow the instructions to install crystal from source: [crystal-lang.org/install/from_sources](https://crystal-lang.org/install/from_sources/) (NB: this requires cross-compilation at some poinf from a x86 or x86_64 host).
> 
> I tried the Docker variant now but the terminal is spammen with `standard_init_linux.go:219: exec user process caused: exec format error`. What should I do?

You aren't using a ARMv8/ARM64 operating system but a ARMv7 operating system. Please install one of these operating system on your Raspberry Pi:
- https://old.reddit.com/r/raspberry_pi/comments/gs6omd/raspberry_pi_os_for_arm64_finally_released/
- https://ubuntu.com/download/raspberry-pi (**64 bits**)
- https://archlinuxarm.org/

**Comment by Northernside** [comment]
> > > @Northernside ARM has no official releases, so you'll either have to use docker, as recommended by unixfox, or follow the instructions to install crystal from source: [crystal-lang.org/install/from_sources](https://crystal-lang.org/install/from_sources/) (NB: this requires cross-compilation at some poinf from a x86 or x86_64 host).
> > 
> > 
> > I tried the Docker variant now but the terminal is spammen with `standard_init_linux.go:219: exec user process caused: exec format error`. What should I do?
> 
> You aren't using a ARMv8/ARM64 operating system but a ARMv7 operating system. Please install one of these operating system on your Raspberry Pi:
> 
> * Raspbian ARM64: https://old.reddit.com/r/raspberry_pi/comments/gs6omd/raspberry_pi_os_for_arm64_finally_released/
> * Ubuntu ARM64: https://ubuntu.com/download/raspberry-pi (**64 bits**)
> * ArchLinux ARM64: https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3
> 
> And make sure to use the correct docker image: `quay.io/invidious/invidious:latest-arm64`

Sadly, the Raspberry Pi can't boot any other OS than the armv7 Raspbian from an external SSD without a micro SDCard. So I have to wait until tomorrow when my micro SDCards arrive. I'll update you tomorrow.

**Comment by Northernside** [comment]
So,
update for today: My Pi is now running on ARM64 Raspbian. Docker itself is working but Invidious makes some problems under Docker.

[Log](https://paste.laby.net/xopajopimo.makefile).

Does somebody know what to do now?

**Comment by unixfox** [comment]
Not sure how you installed docker, but your docker seems broken. Did you install docker using this script: https://get.docker.com/?
And you forgot to use the correct docker image, it's this one: `quay.io/invidious/invidious:latest-arm64`

**Comment by Northernside** [comment]
Oh yeah, now I reinstalled Docker and used the correct image. No errors while deploying with Docker. Invidious and PostgresSQL are running but if I try to access my Pi's ip address, nothing happens.
![image](https://user-images.githubusercontent.com/60970791/143694552-d09e08f5-5648-4245-ac04-0952f039d7b6.png)

**Comment by Northernside** [comment]
Yeah sorry about that. I installed Docker now correctly and used the correct Docker image. No errors so far ![image](https://user-images.githubusercontent.com/60970791/143718864-775efc6a-6309-48b0-8743-e150d2fdb7cf.png) but if I open the website via mypi'saddress:3000 nothing happens. Do you know why?

**Comment by unixfox** [comment]
You should try to remove all the docker volumes and containers with `docker system prune -a` and try again. Make sure to turn off invidious completely with `docker-compose down` twice before that.

I think I've seen this weird blank page bug before but I don't remember how the user fixed the issue.

@SamantazFox any ideas?

**Comment by Northernside** [comment]
![image](https://user-images.githubusercontent.com/60970791/143719700-2ab636e4-b238-42ca-b9ed-65e900ef16d3.png)
Didn't help sadly (pruning everything).

**Comment by unixfox** [comment]
Oh that's this page that you are talking about. Invidious listen by default only on localhost and not on the public IP so you will have to change:
```yaml
ports:
      - "127.0.0.1:3000:3000"
```
to:
```yaml
ports:
      - "3000:3000"
```

**Comment by Northernside** [comment]
Ohh haha, yeah thanks! Imma try that as soon as Windows finished the update haha. I'll update you. Could take some times yk Windows is slow asf

**Comment by Northernside** [comment]
I'm sorry for the late answer but GitHub had (and having it now) a major outage.
![image](https://user-images.githubusercontent.com/60970791/143722014-b6c59bdf-78fa-4339-bc13-a5a7aefabfba.png)
Thanks, it's working! Any way to make the Trending page as the starting page?

**Comment by Northernside** [comment]
Oh, and how do I change the port? I wan't Invidious to be run under the default HTTP port (80) but it isn't working when I change `3000:3000` to `80:80`.
