### ISSUE TITLE
[Bug] Unable to log in invidious

### ISSUE THREAD

**Issue by rlelchev** [iv-org/invidious#2668]
**Describe the bug**

When i try to log in, it just sends me to the main page.
**Steps to Reproduce**

Click "Log in"
Type your credentials
Click "Sign in or register"
**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
Which instance are you using?

**Comment by rlelchev** [comment]
Like a browser? Or a webpage? I am using qutebrowser on this onion url - http://w6ijuptxiku4xpnnaetxvnkc5vqcdu7mgns2u77qefoixi63vbvnpnqd.onion

**Comment by unixfox** [comment]
I can't replicate your issue, I'm able to log in successfully on this instance but I used the tor browser. Maybe it's related to your "qutebrowser".

https://user-images.githubusercontent.com/4016501/143691919-9ca7cf35-e02d-4cbf-9cf9-0ddc807d9726.mp4

Is your browser accepting cookies?

**Comment by rlelchev** [comment]
Of cource! I use it as my primary browser and can sign in at all websites except this one. The only problem, that i seem to notice is that it is based on chromium, but lacks many features chromium has. Unable to share screen in google meet and more. It has no proprietary codec support unless you compile it from source or install it from the official ubuntu repositories, but i don't have access to them. But cookies are one of the few things making qutebrowser different from netsurf and other low end browsers. It has great support for them. And can display any javascript contents too. I use it with tor using the ":set content.proxy" command, aka i am changing the proxy to tor's proxy. It also has an option to disable javascript accesseble through the ":set content.javascript.enable" command.

**Comment by unixfox** [comment]
Are you able to run invidious locally on your machine and try to login on it? Or could you try reproducing the issue on other invidious instances (instances = website that host invidious)?

You may try some invidious instances that are available on the clear net: https://api.invidious.io

**Comment by rlelchev** [comment]
Well the yewtu.be instance is working fine, but i want to use an instance in the onion network. I tried some of them, but as it seems any of the onion network instances are not working... The first clear net instances did work with my login information and i was successfully logged in. Does the login prompt require javascript? I have that disabled, because it's putting my computer at risk.

**Comment by unixfox** [comment]
It's your browser that is not storing cookies for onion sites. I'm sorry but you will have to investigate that on your side, logging in works fine on tor browser so it's definitively not an invidious bug.

**Comment by rlelchev** [comment]
I can log in Dread and other sites like that. I was able to log in the clear net instance of invidious in the same browser using the tor proxy. It works fine with other onion sites.

**Comment by unixfox** [comment]
Did you try other onion services on the instance list: https://api.invidious.io/? Not just the one that you sent on your second message.

**Comment by rlelchev** [comment]
Yes i tried all of them. It didn't work for any of them.

**Comment by unixfox** [comment]
How did you configure your browser with tor, like this: https://tonisagrista.com/blog/2020/tor-qutebrowser/?

I'll try to replicate the issue myself with your browser.

**Comment by rlelchev** [comment]
Yes, just like that. To save time editing the config files, you can just open the browser and type ":set content.proxy socks://localhost:9050/"

**Comment by SamantazFox** [comment]
I've also tried to register and login on a TOR instance, using TOR browser, and that works fine, so the issue is very likely due to how your browser handles cookies, rather than invidious itself.

**Comment by Toni-Vide** [comment]
Hey all, I had the same issue. I had to comment (remove):

domain: localhost 

in my yml to make it work. Hopefully this will help someone in the future.
