### ISSUE TITLE
[Bug] Failure to open all videos with NilAssertionError since 28-11-2021

### ISSUE THREAD

**Issue by BrightCandle** [iv-org/invidious#2675]
**Describe the bug**
When selecting a video page from the list of subscriptions or from popular then page will fail to load and crash with an exception trace.

**Steps to Reproduce**
1. Go to the popular page.
2. Click on any video.
3. See the error page.

Also the failure can be seen by going to the trending page, clicking on that will produce a similar failure.

**Logs**
Log entry is simply:

2021-11-28 13:45:26 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 93.27ms

Entire trace on the page is
Title: `HTTP::Client::Response#body_io cannot be nil (NilAssertionError)`
Date: `2021-11-28T13:44:46Z`
Route: `/watch?v=C33qjpP3siM`
Version: `2021.11.28-82f3eda @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
HTTP::Client::Response#body_io cannot be nil (NilAssertionError)
  from /usr/share/crystal/src/string.cr:5056:13 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:978:10 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Additional context**
Running in a docker image, started on the 28th and watchtower shows an update occurred over night so it does appear to be a newly introduced problem, this was working correctly yesterday.

Docker image: quay.io/invidious/invidious:latest@sha256:c1b56b3c5d7353a55f2b86fae8f438c420268e929817d02e8c20b9876c808271

The autoheal appears to be failing its healthcheck if I try to get its logs and the database instance is spewing out log entries of
2021-11-28 13:52:42.335 UTC [155138] LOG:  could not receive data from client: Connection reset by peer

Something has got broken with the latest update.

**Comment by unixfox** [comment]
Please update your docker image, this was fixed 5 hours ago.
