### ISSUE TITLE
Is that possible to provide an api for jitsi-meet?

### ISSUE THREAD

**Issue by OrionRandD** [iv-org/invidious#2676]
Is that possible to provide an api for jitsi-meet?
I asked in jitsi-meet about the possibility of playing
videos from invidious instances inside jitsi,

Do you think that is is possible to work with them for this to be possible?

See the thread here, if possible, please...

https://github.com/jitsi/jitsi-meet/issues/10470#issuecomment-980835094

 OrionRandD commented 14 hours ago

"I'd like to share videos in jitsi through invidious instances and not direct YT videos.
https://github.com/iv-org/invidious
I have tried it, but jitsi complains, telling me to correct the URL
e.g.
https://yewtu.be/watch?v=3Iwiwq7eofE
It does not open because it uses an invidious instance.
:(
@OrionRandD OrionRandD added the feature-request label 14 hours ago
@saghul
Member
saghul commented 12 hours ago

We don't support that, sorry. YT provides an API we interact with, which this system would need to provide."

**Comment by SamantazFox** [comment]
Hello! I'm not sure what API they're talking about: after a quick look at their code, they just seem to embed the Youtube player.

Given that Jitsi-meet is a browser application, you can use an extension like [privacy-redirect](https://github.com/SimonBrazell/privacy-redirect#get) that will replace the embedded youtube player by the invidious player from the instance of your choice.

**Comment by OrionRandD** [comment]
> Hello! I'm not sure what API they're talking about: after a quick look at their code, they just seem to embed the Youtube player.
> 
> Given that Jitsi-meet is a browser application, you can use an extension like [privacy-redirect](https://github.com/SimonBrazell/privacy-redirect#get) that will replace the embedded youtube player by the invidious player from the instance of your choice.

Yes, it is a browser appl, but many people install it as a local server in their machines. 
In my case, I do not have the jitsi server in my machine, I just access any free available server somewhere...
and that is why I asked the core devs to add the feature of enabling invidious instances to the application itself...
if you access this free server here and try to share a invidious video, you will see the message telling you to write a proper YT video link...

https://meet.jit.si/ 

Perhaps, if you can, you can clarify to them what you just told me about the possibility of having invidious instances working in jitsi.
It would really be a great add to that appl.

**Comment by unixfox** [comment]
Can you send us a screenshot of the error? When sending the URL that you gave I can't replicate the issue, I see no errors:
![image](https://user-images.githubusercontent.com/4016501/143786012-d0be1daa-4f63-46b5-bf3e-dd2b3b1710e8.png)

**Comment by unixfox** [comment]
We already have an API for interacting with invidious, it's well documented there: https://docs.invidious.io/API.md

**Comment by OrionRandD** [comment]
> We already have an API for interacting with invidious, it's well documented there: https://docs.invidious.io/API.md

https://imgur.com/n4FYvAm.png

:(

**Comment by unixfox** [comment]
> > We already have an API for interacting with invidious, it's well documented there: [docs.invidious.io/API.md](https://docs.invidious.io/API.md)
> 
> [imgur.com/n4FYvAm.png](https://imgur.com/n4FYvAm.png)
> 
> :(

Just because we provide the API doesn't mean that jitsi implemented it...

You have to tell them to implement it, we can't do anything else on our side.

**Comment by OrionRandD** [comment]
Right. Thx.
Do you know any public jitsi server supporting invidious?

**Comment by unixfox** [comment]
Sorry no I don't, like I said on my previous comment it's the responsibility of jitsi to implement that.

We already provide the API needed for them to implement an integration with invidious.
