### ISSUE TITLE
[Bug] Error adding video to playlist with disabled JS: hidden token required field not send

### ISSUE THREAD

**Issue by benyaminl** [iv-org/invidious#2686]
**Describe the bug**
Error when adding video to playlist when JS is disabled on IV
![image](https://user-images.githubusercontent.com/2817332/144176505-182eb56f-5b62-4b13-a6f2-906b21d64a7a.png)

**Steps to Reproduce**
1. Disable JS
2. Create Playlist
3. Browse Video
4. Add video to playlist
5. Error Token Missing

**Logs**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/2817332/144176607-9ae095cc-8a7a-43b1-ab28-7fe72c4fe051.png)
![image](https://user-images.githubusercontent.com/2817332/144176692-41a6afa5-6f36-498a-a28a-6c4f2a977367.png)

**Additional context**
On Disabled JS on any instance.

**Comment by unixfox** [comment]
I'm not even sure if this was supposed to work without JS 🤔.

@SamantazFox Any ideas?

**Comment by benyaminl** [comment]
If you manually add via PlayList the plus button does work but without any
success message, only via each detail video it doesn't work. Hopefully it
will be same.

Thank you.




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by unixfox** [comment]
What's the + button you are talking about? Could you please post a screenshot about it?

**Comment by benyaminl** [comment]
> What's the + button you are talking about? Could you please post a screenshot about it?

![image](https://user-images.githubusercontent.com/2817332/144206345-5632d49e-ce9a-48b6-a4ca-5b6b1372be56.png)
It's working even with JS Disabled, as the button type is submit, and it's inside form, btw I think because this form and page doesn't require token to accept the insert. 

The Link https://yewtu.be/add_playlist_items?q=Live+BBC&list=IVPLv3uKBoGl4smk0ywaoe5xSV9aLcKwTXO 

You can test as it's public yewtu.be link (your server I suppose)

**Comment by SamantazFox** [comment]
> I'm not even sure if this was supposed to work without JS 🤔. There is even an hint which is "ajax" is related to JS.
> 
> My understanding is that it's in JS so that the user doesn't have to leave the video page in order to add a video to a playlist.
> 
> @SamantazFox Any ideas?

Yeah, it should work without JS. With JS, it should be done with AJAX, but without JS it should be a form that sends the request when "add" is pressed (and it should open in a new tab/window to not disrupt playback).
