### ISSUE TITLE
[Bug] Buffering stops suddenly without reason

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2689]
**Describe the bug**
Sometimes, when i'm watching a video, the buffering stops suddenly and not a single byte of video is transferred anymore.

**Steps to Reproduce**

1. Watch a video
2. Sometimes it works fine, sometime it doesn't

**Logs**

**Additional context**
-  Browser: Firefox
 - OS (if applicable):

**Comment by unixfox** [comment]
Which instance are you using?

**Comment by stemy2** [comment]
It can happen on any instance.

**Comment by unixfox** [comment]
You didn't reply to my second question: do you have dash enabled or not?

**Comment by stemy2** [comment]
no

**Comment by TheFrenchGhosty** [comment]
Related/duplicate I think.
This sounds like youtube throttling: 
https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-982965623

**Comment by unixfox** [comment]
Could you please let your web tools opened with the network tab opened? You can access that with F12. And make a screenshot of the network tab once your encounter the issue.

**Comment by unixfox** [comment]
Probably duplicate of https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-982965623.

I can't reproduce the issue while I have been watching 300+ videos last month.
