### ISSUE TITLE
Why did you bring back this issue again...

### ISSUE THREAD

**Issue by MrBrastavaya** [iv-org/invidious#2699]
Ignore whatever tf I was watching [EDIT: ONLY HAPPENS ON INSTANCE ITERONI.COM]
**Describe the bug**
Can't play adult videos again, please fix this.

**Steps to Reproduce**
1. Go to any instance
2. Click on adult video
3. Scroll down to play button

**Screenshots**
![image](https://user-images.githubusercontent.com/88563252/144970317-3612793c-5c87-4bc5-8b06-cb411c540353.png)

**Additional context**

**Comment by MrBrastavaya** [comment]
This is just #2189 but now it's back.

**Comment by unixfox** [comment]
We have no control over the instance ITERONI.COM. Please use another instance from this list: https://instances.invidious.io
