### ISSUE TITLE
I translated Croatian, Dutch, German, and fixed the Serbian Translations.

### ISSUE THREAD

**Issue by SecularSteve** [iv-org/invidious#2700]
Just so you know...

**Comment by unixfox** [comment]
Thank you. We are periodically aware of every new translations that are being added.
Weblate, the tool that you probably used, is almost every week pushing the translation modifications to our code.

**Comment by SamantazFox** [comment]
@SecularSteve yeah, I saw that on weblate ^^ Thanks for your contribution!

**Comment by SamantazFox** [comment]
PR is here, btw: https://github.com/iv-org/invidious/pull/2692
(because you made large modifications, I have to make some manual checks before merging)
