### ISSUE TITLE
[Bug] Invidious doesn't honor captions off in Safari

### ISSUE THREAD

**Issue by alangrafu** [iv-org/invidious#2710]
**Describe the bug**
In Safari captions are shown even when the settings specify they should be off. You can turn the captions off on each video specifically, but the general settings are not honored.

**Steps to Reproduce**
1. Go to Preferences
2. Select default captions "none", "none" and "none"
3. Go to any video with spoken voices
4. See captions nonetheless

**Screenshots**
<img width="1462" alt="Screen Shot 2021-12-08 at 7 52 38 PM" src="https://user-images.githubusercontent.com/259102/145331601-5ee4ebe1-a6e9-411f-9891-f87f3e62e00c.png">

**Comment by unixfox** [comment]
I can't replicate your issue on my safari, please post the video ID that you used.

**Comment by alangrafu** [comment]
This happens to any video. I recorded the interaction here (the IDs of the videos are sw0VfmXKq54 and Q38556KTTR0)

https://user-images.githubusercontent.com/259102/145514626-9a94c57c-3881-4594-b121-8bf0505f5b68.mov

**Comment by SamantazFox** [comment]
Hello! The option in the preferences is only here to select your favorite captions, so they're place first in the list (in the event where many caption languages are available). You have to click on the [CC] icon at the bottom right of the player to disable captions completely!

**Comment by alangrafu** [comment]
So if you don't want captions you are forced to disable on every single video I watch it? This doesn't occur on Firefox, that's why I'm reporting it as a bug for Safari.

**Comment by SamantazFox** [comment]
> So if you don't want captions you are forced to disable on every single video I watch it? This doesn't occur on Firefox, that's why I'm reporting it as a bug for Safari.

Afaik, captions are natively managed by browsers. So safari should remember that you selected "captions: off" on a video and do that on all future videos, until you re-enable them.

**Comment by alangrafu** [comment]
Thanks @SamantazFox that's exactly the issue: Whatever mechanism Invidious is using to make the captions off, is not kept in Safari. I've been looking at the console and not even an error or warning is reported :-/

**Comment by haorenxu** [comment]
I've been testing these days on different VPS that all run in docker and Ubuntu 22.04, but get the same results—captions always show up. Until today I create a VPS on Amazon Lightsail that runs Ubuntu 20.04, and the captions are not show up, as it should be. I don't if it is related to the OS.

**Comment by SamantazFox** [comment]
@haorenxu Thanks for the investigation! On that Amazon Lightsail VPS, can you enable the captions at all? Could you also provide some logs?

Asking this to make sure that the captions endpoint isn't being restricted on youtube's side.

**Comment by haorenxu** [comment]
> @haorenxu Thanks for the investigation! On that Amazon Lightsail VPS, can you enable the captions at all? Could you also provide some logs?

The captions are disabled by default, and I can enable them. And after upgrading Ubuntu to 22.04, I haven't seen any problem. Other VPS providers I used were Linode, Vultr, and GCP (Ubuntu 22.04 installed by default), they all had the caption problem. Maybe I can test these VPS using 20.04, and see what happens.

**Comment by haorenxu** [comment]
@SamantazFox I think I found where the problem is. In macOS, under System Preferences > Accessibility > Captions, there is an option can let you enable/disable closed captions. When this is enabled, the captions in Invidious are forced to enabled too, no matter what your settings in Invidious are. The problem is, this option in macOS is disabled by default, but Invidious sees it as enabled or something else. Anyway, you have to _manually_ disable it—it means you have to enable it first—then Invidious just functions properly.

<img width="780" alt="Screen Shot 2022-09-23 at 7 46 11 PM" src="https://user-images.githubusercontent.com/33184148/191953749-7c8449de-7ec7-44fa-ab3b-d182f6f5a86e.png">

**Comment by SamantazFox** [comment]
Thanks for searcing! So in the end, it's aither a bug with VideoJS (the player we use) or Safari itself!
