### ISSUE TITLE
[Bug] While scanning the time with the mouse, the preview doesn't show up

### ISSUE THREAD

**Issue by AlexMiniReal** [iv-org/invidious#2717]
**Describe the bug**
In YouTube, when you are searching for a specific point in time in a video, the previews shows up. In this instance it is glitched and shows a transparent background.

**Steps to Reproduce**

**Screenshots**
YouTube
![Screenshot_2](https://user-images.githubusercontent.com/76444133/145687116-c378ec38-4ae0-495a-a052-1034818545bb.jpg)
invidious.mutahar.rocks
![Screenshot_1](https://user-images.githubusercontent.com/76444133/145687115-aa3223b0-f35c-4903-8c51-9a6c502a284b.jpg)
invidious.snopyta.org
![Screenshot_3](https://user-images.githubusercontent.com/76444133/145687198-88453a66-a598-493d-b0eb-b73693cec793.jpg)

**Comment by SamantazFox** [comment]
Hello! Have you tried switching instances? The thumnails are using the invidious API to work, and it's likely that the instance's owner is blocking the API to protect themselves from bots (the API is often being abused).

**Comment by AlexMiniReal** [comment]
Yes, as you can see from the screenshots, on the instance invidious.snopyta.org the preview shows correctly, but on invidious.mutahar.rocks it doesn't work. Could you tell me on your opinion which instance is the best?

**Comment by unixfox** [comment]
there is no best instance for everyone, you should find the one that suit to you by looking at this list: https://instances.invidious.io

Closing as it's an instance specific issue.
