### ISSUE TITLE
[Bug]  Index out of bounds (IndexError)

### ISSUE THREAD

**Issue by EliasNP** [iv-org/invidious#2735]
Title: `Index out of bounds (IndexError)`
Date: `2021-12-22T15:09:14Z`
Route: `/watch?v=xUqz9Rbp6nc&continue=1&nojs=1&player_style=invidious&quality=small&subtitles=es%2C%2C`
Version: `2021.12.22-fc2b903 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/indexable.cr:902:5 in 'fetch_reddit_comments'
  from src/invidious/comments.cr:266:1 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment]
Which instance did you use?

**Comment by EliasNP** [comment]
This those ones
invidious.namazso.eu
vid.mint.lgbt

―――――――――――――۞ Ƹɭïąᶊ Ɲïҽⱱą ۞――――――――――――
BASH,Where there is a Shell, there is a way
―――――――――――――――――――――――――――――――――
Ingeniero de Sistemas
eliasnieva{at}gnulinux4all.com
+34 673 559 25{dos}
[GnuLinux4All.com](https://eliasnp.github.io/)

―――― CONTACTO - REDES SOCIALES ―――――

- GitHub: https://github.com/eliasnp/

- Mastodon: [https://mastodon.social/@***@***.***/)Eliasnieva
- Telegram: https://t.me/EliasNieva/

- Reddit: https://www.reddit.com/user/EliasNieva/

―――――――――――――――――――――――――――――――――

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SamantazFox** [comment]
Ok, I guess that Reddit made changes to their API...
We'll have to dig further into this.

**Comment by matthewmcgarvey** [comment]
The problem wasn't that Reddit made changes, we didn't handle when there were no threads found
