### ISSUE TITLE
[Bug] 'Save the current video time' and 'Play next by default' settings conflict when trying to rewatch a video

### ISSUE THREAD

**Issue by omar-elnaggar** [iv-org/invidious#2736]
**Describe the bug**

'Save the current video time' and 'Play next by default' settings conflict when trying to rewatch a video. Once finishing viewing a video play next by default will bring the user to the next video as expected. When the user goes back to the previous page the video jumps to the end and plays the next video causing a minor annoyance to the user.

**Steps to Reproduce**

1. Go to any updated Invidious instance
2. Go to your preferences and enable both 'Save the current video time' and 'Play next by default'
3. Navigate to a short video
4. When the next video plays navigate back to the previous video
5. See bug occur as you are navigated to the next video

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

 - Workaround: User disables either setting or must catch the video quickly before the next video is played.

**Comment by SamantazFox** [comment]
Thanks for reporting the issue!

**Comment by 11Tuvork28** [comment]
I fixed this on my instance by adding this check to the player.js
`if (lastUpdated !== time && raw <= video_data.length_seconds - 15)`
This check prevents the saved time to be at the end of the video and the user therefore has a minimal time from 15sec to pause or do other stuff.

**Comment by SamantazFox** [comment]
> I fixed this on my instance by adding this check to the player.js `if (lastUpdated !== time && raw <= video_data.length_seconds - 15)` This check prevents the saved time to be at the end of the video and the user therefore has a minimal time from 15sec to pause or do other stuff.

Nice! Do you mind opening a PR for that?

**Comment by 11Tuvork28** [comment]
[Done ](https://github.com/iv-org/invidious/pull/2750):)
