### ISSUE TITLE
[Enhancement] Please have an option to disable the trending page

### ISSUE THREAD

**Issue by avdb13** [iv-org/invidious#2752]
**Is your enhancement request related to a problem? Please describe.**

Most people using Invidious are either doing it to protect their privacy or just because they dislike the Youtube homepage which suggests sexually incentive thumbnails. In my case the latter applies.
I also wasn't really satisfied with the homepage on most popular invidious instances since they contain misleading thumbnails (also called soy faces in meme culture) so I decided to spin up my own with registrations locked.
Everything was fine but it still sort of annoyed me that it's still possible to access the trending page on my instance.

**Describe the solution you'd like**

Please have a configuration option which allows us to disable the trending page completely. It's probably not harder than putting a few lines of HTML (and CSS) between an if-else statement.

**Describe alternatives you've considered**

There is no alternative.

**Additional context**

I will try to see if I can do something about this issue myself.

**Comment by avdb13** [comment]
This feature already exists, my excuses.

**Comment by badrow** [comment]
Hi, where is this feature ? I can't find it..
