### ISSUE TITLE
Edit the HTML Style like: https://youtube.076.ne.jp/feed/popular

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#2756]
> Ah, thank you. I really like the player and would be happy if I can use it someday, can you tell me where the path of the files is to edit the HTML in the Docker installation?

> No i mean i want to edit the HTML Style like: https://youtube.076.ne.jp/feed/popular

_Originally posted by @MaximilianGT500 in https://github.com/iv-org/invidious/issues/2755#issuecomment-1003750914_

**Comment by unixfox** [comment]
Opening another issue because you were getting offtopic in the previous issue.

**Comment by MaximilianGT500** [comment]
Okay, thanks.

**Comment by unixfox** [comment]
All the CSS and JS ressources are located here: https://github.com/iv-org/invidious/tree/master/assets
And the HTML pages are compiled from these .ecr files: https://github.com/iv-org/invidious/tree/master/src/invidious/views

**Comment by MaximilianGT500** [comment]
Hello, i use docker how can i find this there i use Ubuntu 20.04

**Comment by unixfox** [comment]
Git clone the repo then make your modifications then docker-compose up -d

**Comment by MaximilianGT500** [comment]
Ah, ok thanks
