### ISSUE TITLE
[Bug] Bad audio quality when a fast playback speed is selected

### ISSUE THREAD

**Issue by Transistor4aCPU** [iv-org/invidious#2759]
**Describe the bug**
The audio quality is bad if a higher speed is selected

**Steps to Reproduce**
1. Play a video
2. Set video speed to 2x
3. Bad audio

**Additional context**
Safari; iPadOS 15.2

**Comment by unixfox** [comment]
What is actually bad audio for you? Obviously changing the video speed will result in a different audio compared to the original audio

**Comment by Transistor4aCPU** [comment]
> What is actually bad audio for you? Obviously changing the video speed will result in a different audio compared to the original audio 

The audio quality should stay the same,
like it does with Youtube at 2x or freetube.

**Comment by unixfox** [comment]
What do you define audio quality? The bitrate becomes lower?

**Comment by Transistor4aCPU** [comment]
> What do you define audio quality? The bitrate becomes lower?
I don't think that it is the Bitrate.
The audio just sound extremely different, like the speaker is in a can.

**Comment by Transistor4aCPU** [comment]
I noticed it is an iPadOS related issue, not a problem of invidious
