### ISSUE TITLE
[Bug] Search query using api with fields returns strange (or empty) results

### ISSUE THREAD

**Issue by dimchee** [iv-org/invidious#2768]
I am using fields API in search query, and i noticed that results are not relevant, and sometimes they are empty.

**Steps to Reproduce**
Try one of these:
- https://vid.puffyan.us/api/v1/search/?q=dodirni+me?fields=title,videoId
- https://invidious.snopyta.org/api/v1/search/?q=dodirni+me?fields=title,videoId
- https://inv.riverside.rocks/api/v1/search/?q=dodirni+me?fields=title,videoId

**Comment by unixfox** [comment]
Can you reproduce this issue locally (on a locally installed invidious)?

**Comment by unixfox** [comment]
You malformed your URL, it should be like this:
`/api/v1/search/?q=dodirni+me&fields=title,videoId`
and not like this:
`/api/v1/search/?q=dodirni+me?fields=title,videoId`
