### ISSUE TITLE
[Bug] Title: `cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)`

### ISSUE THREAD

**Issue by LeTrollface** [iv-org/invidious#2773]
**Describe the bug**
After trying to export my subscriptions file (used https://juandarr.github.io/json-youtube-export/) i get the following error ''cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)''

**Steps to Reproduce**
1. Go to 'https://invidious.kavin.rocks/data_control?referer=%2Ffeed%2Fsubscriptions'
2. Click on 'export subscriptions from YouTube'
3. Click on 'Import'

**Logs**
cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:228:5 in 'as_a'
  from src/invidious.cr:826:33 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

**Screenshots**

![image](https://user-images.githubusercontent.com/93146593/148405246-a75a6836-2bea-4798-b962-ceb6d789ac9a.png)

**Additional context**
 - Vivaldi 5.0.2497.32 - W10

**Comment by unixfox** [comment]
Please try another tool listed here: https://github.com/iv-org/invidious/issues/2319#issuecomment-900358678

**Comment by LeTrollface** [comment]
> Please try another tool listed here: [#2319 (comment)](https://github.com/iv-org/invidious/issues/2319#issuecomment-900358678)

actually i have tested both of them, and they still give me error messages

**Comment by unixfox** [comment]
So you exported your youtube subscriptions to CSV then you used both of the tool for exporting to JSON then your tried to import the file using the `Import YouTube subscriptions` section on invidious?

**Comment by LeTrollface** [comment]
> So you exported your youtube subscriptions to CSV then you used both of the tool for exporting to JSON then you tried to import the file using the `Import YouTube subscriptions` section on invidious?

yes i have, i actually got 3 files with different sizes from these tools
![image](https://user-images.githubusercontent.com/93146593/148410383-592d837f-dac6-4ffb-9bab-37bf5fe7faf0.png)

**Comment by unixfox** [comment]
And all of these 3 files return the same error when importing them on `Import YouTube subscriptions` section?
<img width="177" alt="image" src="https://user-images.githubusercontent.com/4016501/148410764-cbba522b-cdc4-442d-85f5-512b99728541.png">

**Comment by LeTrollface** [comment]
![3-2400x800](https://user-images.githubusercontent.com/93146593/148411582-9c8893e9-7543-45ed-bef4-32d534f8f36a.png)

**Comment by LeTrollface** [comment]
> ![3-2400x800](https://user-images.githubusercontent.com/93146593/148411582-9c8893e9-7543-45ed-bef4-32d534f8f36a.png)

the first error

> **Describe the bug** After trying to export my subscriptions file (used https://juandarr.github.io/json-youtube-export/) i get the following error ''cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)''
> 
> **Steps to Reproduce**
> 
> 1. Go to 'https://invidious.kavin.rocks/data_control?referer=%2Ffeed%2Fsubscriptions'
> 2. Click on 'export subscriptions from YouTube'
> 3. Click on 'Import'
> 4. See error
> 
> **Logs** cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError) from /usr/share/crystal/src/json/any.cr:228:5 in 'as_a' from src/invidious.cr:826:33 in '->' from lib/kemal/src/kemal/route.cr:12:9 in '->' from /usr/share/crystal/src/primitives.cr:266:3 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from src/invidious/helpers/static_file_handler.cr:112:11 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call' from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process' from /usr/share/crystal/src/http/server.cr:500:5 in '->' from /usr/share/crystal/src/primitives.cr:266:3 in 'run' from ???
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/93146593/148405246-a75a6836-2bea-4798-b962-ceb6d789ac9a.png)
> 
> **Additional context**
> 
> * Vivaldi 5.0.2497.32 - W10

The first error is from subscriptions.json

**Comment by SamantazFox** [comment]
@LeTrollface do you mind sharing an extract of the files that you're trying to import?

**Comment by TheFrenchGhosty** [comment]
> @LeTrollface do you mind sharing an extract of the files that you're trying to import?

To add to that, if you don't want to share it publicly you can email it at: `contact [at] invidious [dot] io` and only the team members will receive it.

**Comment by unixfox** [comment]
We recently merged the ability to import CSV files, could you try (with an up to date version of invidious)?

**Comment by SamantazFox** [comment]
@LeTrollface Bump! We made some changes to the import system, can you please try again?

**Comment by unixfox** [comment]
Closing this issue, you can reopen it if you still encounter the issue.

**Comment by sternstaub** [comment]
I am getting the same issue when trying to open 

https://yt.artemislena.eu/channel/UCnyOwrZI72pKKroCtKYQHjg 
or https://invidious.namazso.eu/channel/UCnyOwrZI72pKKroCtKYQHjg

, so it goes for different instances. Tried on LibreWolf and Brave Browser. Problem persists. 

**Error message is:** 

Title: `cast from Hash(String, JSON::Any) to String failed, at /usr/share/crystal/src/json/any.cr:216:5:216 (TypeCastError)`
Date: `2023-01-31T11:01:27Z`
Route: `/channel/UCnyOwrZI72pKKroCtKYQHjg`
Version: `2023.01.26-3b8e6c6 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
cast from Hash(String, JSON::Any) to String failed, at /usr/share/crystal/src/json/any.cr:216:5:216 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:216:5 in 'as_s'
  from /usr/share/crystal/src/html.cr:24:17 in 'get_about_info'
  from src/invidious/routes/channels.cr:272:17 in 'fetch_basic_information'
  from src/invidious/routes/channels.cr:9:12 in 'videos'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment]
@sternstaub Hello! Can you please open a new issue? While the error looks similar, they're not related at all!
