### ISSUE TITLE
[Enhancement] Distraction Free Invidious Instance

### ISSUE THREAD

**Issue by MintMain21** [iv-org/invidious#2790]
**Is your enhancement request related to a problem? Please describe.**
Inividious has developed well to provide a "distraction free" experience for those willing to toggle the website settings and use cookies, but for others who either refuse to save cookies or are using (for example) a Private Browser Session, the only way to block distractions on Invidious (Comment Section, Homepage Feed etc) is with something like the uBlock Origin Element Picker. The latter works fine for Comments, but when attempting to block the sidebar of recommended videos, it will block alongside it either all video thumbnails across the site (including from search inquires), the other sidebar with important video info (including the YouTube link), or both. The only workaround without rewriting the site is to create an Invidious Instance where all these distractions are disabled by default, no cookies and setting toggling required. 

**Describe the solution you'd like**
I have two proposals. One: Invidious Developers can rewrite Invidious so that Sidebar Recommended Videos (and the homepage feed) are a different uBlock Origin filter than all video thumbnails etc, and can therefore be blocked by uBlock without breaking the site, or someone can make an invidious instance that has distractions (Homepage Feed, Comments, Recommended Videos etc) all disabled by default.

**Describe alternatives you've considered**
Cloudtube can be configured with uBlock Filters, no cookies required, but it's search capabilities are not nearly as advanced as Invidious (I can't filter by channel, for example, nor can I search playlists). Piped, on the other hand, does allow blocking of both Comments and Recommended feeds, similar to what I want out of Invidious. 

**Additional context**
Realistically, it's not the responsibility of this Github Repo to create individual Invidious Instances, let alone ones that is "distraction free" by default. I suggest this here moreso for the Invidious Community than Invidious Developers specifically.

**Comment by markozajc** [comment]
I believe you can use querystring (`?param=value`) parameters to tune Invidious to your liking without having to set cookies (not sure if you can have browsers insert them by default, but there's probably a way to do that with userscripts). An alternative to having an instance specifically dedicated to that could also be a "preset" querystring parameter to toggle distraction-free mode without having to specify all other parameters.

**Comment by MintMain21** [comment]
I have set up Redirector for all my Invidious Redirects instead of Privacy Redirect etc, and it uses Distraction Free URL Parameters. 

I am happy.
