### ISSUE TITLE
Search -> Unexpected char '' at line 1, column 1 (JSON::ParseException)

### ISSUE THREAD

**Issue by jedie** [iv-org/invidious#2792]
Seems that there is some whitespace that should be removed in a search?!?
```
Title: `Unexpected char '' at line 1, column 1 (JSON::ParseException)`
Date: `2022-01-09T14:35:55Z`
Route: `/search?q=ccc`
Version: `2021.12.12-7f3ef122 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:331:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:213:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '_post_json'
  from src/invidious/search.cr:36:11 in 'search'
  from src/invidious/search.cr:232:20 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>
```

**Comment by markozajc** [comment]
This works on the latest version (67cb8b7107682e451fa86c574c691f707e902e8c), please update your instance, or ask the instance's administrator to do so.

**Comment by unixfox** [comment]
Closing as the invidious version is out of date. We recommend updating it.

**Comment by stemy2** [comment]
Just happened on an instance with the version `2021.12.29-3aa98ae8 @ master`

**Comment by unixfox** [comment]
> Just happened on an instance with the version `2021.12.29-3aa98ae8 @ master`

Switch to another instance up to date from this list: https://api.invidious.io
