### ISSUE TITLE
Download button is missing

### ISSUE THREAD

**Issue by artenaki** [iv-org/invidious#2794]
I recently noticed that Download button on yewtu.be is gone. I don't use it, but I'm surprised. It's no secret that google has been actively fighting against downloading (and other) for a long time. Including secret conspiracy (youtube-dl author's). But I wonder if they explained to you the reason for complaint (removal)? Or did they just threaten you?

**Comment by unixfox** [comment]
Hi, the download button was disable on yewtu.be for saving some bandwidth, nothing related to google.
