### ISSUE TITLE
[Bug] Crash when channel: is put in search bar

### ISSUE THREAD

**Issue by raffaem** [iv-org/invidious#2812]
**Describe the bug**
Crash when `channel:` is put in search bar

**Steps to Reproduce**
1. Go to [https://invidious.kavin.rocks/channel/UC7YOGHUfC1Tb6E4pudI9STA](https://invidious.kavin.rocks/channel/UC7YOGHUfC1Tb6E4pudI9STA)
2. Type `channel:metal` in the search bar
3. Press Enter

**Logs**
```
Title: `Missing hash key: "header" (KeyError)`
Date: `2022-01-13T13:37:15Z`
Route: `/search?q=channel%3Ametal`
Version: `2022.01.11-e7394fe @ master`
<details>
<summary>Backtrace</summary>
<p>
   
Missing hash key: "header" (KeyError)
  from /usr/share/crystal/src/hash.cr:1034:9 in '[]'
  from src/invidious/search.cr:8:12 in 'channel_search'
  from src/invidious/search.cr:213:20 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

</p>
</details>
```

**Screenshots**

**Additional context**
Browser: Firefox 95.0.2

**Comment by unixfox** [comment]
I think instead of a crash, we should say that the channel doesn't exist.

**Comment by SamantazFox** [comment]
The `channel:` search filter has to be followed by the channel ID (a.k.a UCID), not the channel name.
For instance, to search LTT's channel, use `channel:UCXuqSBlHAE6Xw-yeJA0Tunw`.

**Comment by raffaem** [comment]
> The `channel:` search filter has to be followed by the channel ID (a.k.a UCID), not the channel name. For instance, to search LTT's channel, use `channel:UCXuqSBlHAE6Xw-yeJA0Tunw`.

Yeah I figured that out.

But what @unixfox says makes sense

**Comment by matthewmcgarvey** [comment]
I'm going to try to solve this one. Just a curiosity I noticed... that stack trace is incorrect. `search.cr:213` is actually `process_search_query` and `search` is the function name of the route file which is never mentions. Weird stuff 🤷
