### ISSUE TITLE
[Bug] Playlist set to public not visible to the public

### ISSUE THREAD

**Issue by poltrian** [iv-org/invidious#2818]
**Describe the bug**
I created 2 playlists and made them public. These are neither visible to unregistered users nor to registered users 

**Steps to Reproduce**

1. Create a Palylist set them to public
2. Use a second  Browser and do to your Instance, no playlist is shown
3. Login with an existing (test) account (not your own) and also no playlist is shown
4

**Comment by unixfox** [comment]
Which instance are you using? I can't replicate the issue.

**Comment by poltrian** [comment]
https://invidious.bachgau.social

Maybe I misunderstand the function. I thought that if I create a public list, it will be visible to everyone, whether they have an account or not

**Comment by unixfox** [comment]
Public playlist set to the public that I just created: https://invidious.bachgau.social/playlist?list=IVPLojsKFKDCcpZumEk1y9Ak41ZuOvr4LmI

I don't understand why it is not working on you side? Can you record your screen while creating the playlist and post it here?

**Comment by poltrian** [comment]
But shouldn't there be a "public playlist" link that any visitor can see without me having to share a link?
Your playlist is also not visible in my account, only via the sent link

**Comment by poltrian** [comment]
Quick and dirty

https://user-images.githubusercontent.com/50879520/149731742-979e647e-8986-4cf1-974c-da175054fee5.mp4

**Comment by unixfox** [comment]
Thanks for the video, can you share the URL to the playlist?

**Comment by poltrian** [comment]
https://invidious.bachgau.social/playlist?list=IVPL1laEI52Nqh2rAUWdOr6nXBo0Z6NdPy6

I thought a public playlist would show up under Popular along with the other videos seen by users.

**Comment by unixfox** [comment]
> [invidious.bachgau.social/playlist?list=IVPL1laEI52Nqh2rAUWdOr6nXBo0Z6NdPy6](https://invidious.bachgau.social/playlist?list=IVPL1laEI52Nqh2rAUWdOr6nXBo0Z6NdPy6)
> 
> I thought a public playlist would show up under Popular along with the other videos seen by users.

Oh, no these public playlists are not really integrated with the "YouTube" ecosystem as Invidious is just another way to view the YouTube ecosystem, it's not an ecosystem on its own.

**Comment by SamantazFox** [comment]
> https://invidious.bachgau.social/playlist?list=IVPL1laEI52Nqh2rAUWdOr6nXBo0Z6NdPy6
> 
> I thought a public playlist would show up under Popular along with the other videos seen by users.

The "popular" feed only shows the latest videos from the channels that your users subscribed to. It doesn't display playlists.

This could be a feature request, though. That will also make the "unlisted" visibility option meaningful (currently it's the same as "public").
