### ISSUE TITLE
[Bug] Sort by upload date filter incorrect order when certain queries/additional parameters contains colon character (eg: channel:)

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#2824]
**Describe the bug**
For normal search term query only searches the sort by upload date filter works as expected but if `channel:<channelID>` (edit: or certain other strings with colons in them) is added to the query the results are no longer ordered by upload date and seem to be arbitrarily ordered.

**Steps to Reproduce**
1. Search for a term + a channel parameter with the sort by upload date filter enabled, eg: `channel:UCmjNQjjxPOP9jMTQAqaP1PQ e-mount sort:date`
2. Notice the dates of the videos aren't ordered by date.
3. Now remove the `channel:<channelID>` part of the query and notice results are correctly ordered by date uploaded.

**Additional context**
Tested on both invidious.snopyta.org and kavin.rocks instances:
- https://invidious.snopyta.org/search?q=channel:UCmjNQjjxPOP9jMTQAqaP1PQ+e-mount+sort:date&page=1
- https://invidious.kavin.rocks/search?q=channel:UCmjNQjjxPOP9jMTQAqaP1PQ+e-mount+sort:date&page=1

**Comment by chocmake** [comment]
Update: I think I've now identified the root cause of this is. It's not `channel:` specifically but *any* query that has a colon in it, beside the `sort:date` parameter.

So a query such as `4:2:2 10-bit sort:date` also causes the ordering by date to fail, while `422 10-bit sort:date` doesn't.

**Comment by SamantazFox** [comment]
This will be addressed with #2544 :)

**Comment by SamantazFox** [comment]
Can you please confirm that it's fixed now?

**Comment by chocmake** [comment]
> Can you please confirm that it's fixed now?

So when trying the Snopyta instance (dated 2022-06-05) if searching for `4:2:2 10-bit` and sorting by date using the new filter menu it's now the correct date ordering.

However searching channels using the `channel:<id>` parameter + a string and clicking sort by date now strips the `channel:<id>` part of the URL entirely. I suppose this may be related to the recent #3148 issue I also reported.

Try for example the channel and search term from the first link then filter by *Sort by>Upload date*:

- https://invidious.snopyta.org/search?q=channel:UCmjNQjjxPOP9jMTQAqaP1PQ+e-mount

**Comment by SamantazFox** [comment]
> However searching channels using the `channel:<id>` parameter + a string and clicking sort by date now strips the `channel:<id>` part of the URL entirely. I suppose this may be related to the recent #3148 issue I also reported.

Yes, that's normal. In order to simplify many parts of the code, what we call "legacy" filters (`duration:`, `sort:`, etc.) have been reworked to be URL parameters, with a proper HTML form on the search page. They are still supported for backward compatibility, but are automatically converted to URL parameters when used.

Regarding the `channel:` filter, this is working in a special fashion. Similarly to other search filters, it's converted to a URL parameter. But it's not like a regular search. Search filters don't work (you'll see that on Youtube, you can't filter channel search results).

While there is no visual feedback atm (we haven't implemented the UI elements that show that a channel search is being done), it is working (if it doesn't, that's a bug). PR #2215 will add a dedicated "channel search" box on the channel page, like on Youtube.

**Comment by chocmake** [comment]
I suppose in that case, if no filters were intended to work for `channel:` searches or for the future dedicated channel search box, it might be a helpful clue if the Filter UI element was greyed out (with say a tooltip on it indicating filters not available for channel searches).

Closing since it seems the bug regarding colons was addressed while the channel filtering aspect is unintended.

**Comment by SamantazFox** [comment]
> I suppose in that case, if no filters were intended to work for `channel:` searches or for the future dedicated channel search box, it might be a helpful clue if the Filter UI element was greyed out (with say a tooltip on it indicating filters not available for channel searches, or a note in the expandable area when clicked).

Yes, that's a good idea! I'll see what can be done to make that more user friendly ^^
