### ISSUE TITLE
[Bug] "0 views" on all related videos

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2830]
**Describe the bug**
On the "watch" page, all related videos (right column) display 0 views

**Steps to Reproduce**
1. Enable related videos column
2. Got to any video
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/52980486/150558552-ff7e6477-72a2-4f7d-82a0-d5cc0999f730.png)

**Comment by hellojaccc** [comment]
Also listen, youtube, instance select button is gone

**Comment by SamantazFox** [comment]
> Also listen, youtube, instance select button is gone

I think thy never were there in the first place?
