### ISSUE TITLE
[Bug] Channel refresh job could be creating database bloat

### ISSUE THREAD

**Issue by matthewmcgarvey** [iv-org/invidious#2835]
**NOTE** This is only a theory as of right now.

## Theory

The `RefreshChannelsJob` calls `fetch_channel` for every channel in the database every 30 minutes. [link](https://github.com/iv-org/invidious/blob/8b0ed8b110752327b98565e4ecc4faf437c0bb3b/src/invidious/jobs/refresh_channels_job.cr#L33)

The `fetch_channel` code parses all videos from the channel's feed and tries to insert them into the database. [link](https://github.com/iv-org/invidious/blob/8b0ed8b110752327b98565e4ecc4faf437c0bb3b/src/invidious/channels/channels.cr#L237)

The database insertion uses `ON CONFLICT` to update the row if the id already exists. [link](https://github.com/iv-org/invidious/blob/8b0ed8b110752327b98565e4ecc4faf437c0bb3b/src/invidious/database/channels.cr#L92-L109)

All of this put together means that it's likely that almost every single channel video is updated every 30 minutes. That creates a dead tuple in postgres which means that the database table increase by `SELECT COUNT(*) FROM channel_videos` rows every 30 minutes. This does not mean that the detectable number of rows grows by that much, but that a large amount of rows are left for postgres to clean up at some point in time.

## Why is it just now a problem?

My theory doesn't make sense unless either (1) it has always bloated the database and no one has really noticed or (2) the job always failed before and no one noticed.

**Comment by matthewmcgarvey** [comment]
Thinking through this some more, this might be a good reason to look into using an ORM like https://github.com/imdrasil/jennifer.cr

Specifically, an ORM gives us the ability to not update the database unless something about the row changed.

In this scenario, we would load all channel videos for the channel we're refreshing. Then fetch all the data from YT. Cycling through each of the YT videos, we'd look through our channel video list for a matching one. If we find one we update all the fields and call save. It will save if a row changed, otherwise nothing will happen. And if we don't find a matching channel video, we create it.

It's also not like we have to switch over all the models at the same time as well. We should be able to get away with just converting `ChannelVideo` at first if we wanted to. Then we'd update the repository functions to the new ORM model.

**Comment by SamantazFox** [comment]
I like that `jennifer.cr` shard. It's a good candidate for #2620 !
