### ISSUE TITLE
[Bug] Pressing any numpad number skips to the end of the video

### ISSUE THREAD

**Issue by PORTB** [iv-org/invidious#2839]
**Describe the bug**

Pressing a number on the numpad skips to the end of the video, unlike normal buttons

**Steps to Reproduce**

1. go to a video
2. start playing it
3. press any numpad number
4. video skips to end

**Comment by SamantazFox** [comment]
It seems that it was initially implemented as a feature to quickly jump to some percentage of the video (0 would jump to the start, 1 to 10%, 2 to 20%, and so on), but something broke a long time ago:
https://github.com/iv-org/invidious/blob/0ca333715b06689f3120c136dfeab493f30bf867/assets/js/player.js#L605-L617

I think we should remove that feature, as nobody seems to use it (nobody complained that it's broken).

**Comment by PORTB** [comment]
I don't think it's worth removing, because it works fine with the normal number row. The numpad buttons start 96 instead of 48, so it tries to skip to beyond 100% of the video, hence why it skips to the end

**Comment by SamantazFox** [comment]
> I don't think it's worth removing, because it works fine with the normal number row. The numpad buttons start 96 instead of 48, so it tries to skip to beyond 100% of the video, hence why it skips to the end

Ah, that's interesting! Thanks for your research :)
