### ISSUE TITLE
[Bug] OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by NephtonLabs** [iv-org/invidious#2843]
Setting up invidious on Rocky Linux (RHEL) 8
Got it running, but in the CLI it throws the following error:

> [error] UpdateDecryptFunctionJob : SSL_connect: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

in the web interface if I enter a search I get the following error:

> Title: `SSL_connect: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (OpenSSL::SSL::Error)`
> Date: `2022-01-25T18:18:55Z`
> Route: `/search?q=video`
> Version: `2022.01.19-8b0ed8b1 @ master`
> <details>
> <summary>Backtrace</summary>
> <p>
>    
> ```
> SSL_connect: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (OpenSSL::SSL::Error)
>   from lib/lsquic/src/lsquic/patch.cr:174:11 in 'new:context:sync_close:hostname'
>   from src/invidious/helpers/crystal_class_overrides.cr:34:5 in 'io'
>   from /usr/share/crystal/src/http/client.cr:671:5 in 'send_request'
>   from /usr/share/crystal/src/http/client.cr:651:20 in '_post_json'
>   from src/invidious/search.cr:36:11 in 'search'
>   from src/invidious/search.cr:232:20 in 'search'
>   from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
>   from /usr/share/crystal/src/http/server.cr:500:5 in '->'
>   from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
>   from ???
> ```
> </p>
> </details>

Not sure what's going on. I was writing out a build guide as I ran through the setup:
![image](https://user-images.githubusercontent.com/51098774/151036053-6694840e-69ac-484a-ae84-fe4499f4421e.png)

I'm hoping somebody has an idea because I am stumped.

**Comment by NephtonLabs** [comment]
Thank you! I don't know why I failed to find that bug. Sorry.

**Comment by SamantazFox** [comment]
No problem, that can happen :)

**Comment by NephtonLabs** [comment]
Just as a final note on this incase anybody finds this and tries following the steps listed; substituting 

> crystal build src/invidious.cr --release

with 

> crystal build src/invidious.cr -Ddisable_quic -release

does work in that the search function now operates, but the calls to YouTube are crushingly slow, and thumbnails time out and fail to load most of the time.
