### ISSUE TITLE
Login does't work when page is loaded through a pro̷xy

### ISSUE THREAD

**Issue by TylerHobanDotCom** [iv-org/invidious#286]
When loading the page through a pro̷xy the page works with everything like the player but the login functionality doesn't. When logging in if pw/captcha is wrong the login is denied and the reason is displayed properly but when the login details are entered successfully it just goes to an Internal Server Error page. Same effect on multiple pro̷xies.

**Comment by omarroth** [comment]
I'm having trouble reproducing this. Are you using a proxying website or are you specifically using a proxy in your network settings? The issue may be that the proxy doesn't allow POST requests, which would be quite strange, but I'm having trouble thinking of anything that might be causing an issue.

**Comment by TylerHobanDotCom** [comment]
While going through the logs I determined that the POST was timing out. This is not a problem on the proxy side as POST functionality is not impacted on any other site.

This is the log if it helps you. I've removed some things from the log like the proxy host but that shouldn't matter.

`Jan 16 09:45:19pm info at=info method=GET path="https://invidio.us/login?referer=%2F"  fwd="51.254.208.245" dyno=web.1 connect=1ms service=1620ms status=200 bytes=33110 protocol=https

Jan 16 09:45:20pm info at=info method=GET path="https://invidio.us/"  fwd="51.254.208.245" dyno=web.1 connect=1ms service=31ms status=404 bytes=394 protocol=https

Jan 16 09:45:20pm info at=info method=GET path="https://invidio.us/favicon-32x32.png"  fwd="51.254.208.245" dyno=web.1 connect=0ms service=34ms status=200 bytes=1614 protocol=https

Jan 16 09:45:20pm info at=info method=GET path="https://invidio.us/favicon-32x32.png"  fwd="51.254.208.245" dyno=web.1 connect=0ms service=45ms status=200 bytes=1614 protocol=https

Jan 16 09:46:18pm error at=error code=H12 desc="Request timeout" method=POST path="https://invidio.us/login?referer=%2F&type=invidious" fwd="51.254.208.245" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
`

**Comment by omarroth** [comment]
The issue may then be with your account rather than the proxy you are using. Would you mind contacting me privately at omarroth@protonmail.com with your user ID?

**Comment by omarroth** [comment]
Appears to be an issue with the login page. I've done some work speeding up login, so it should be possible to login. Could you verify?

**Comment by TylerHobanDotCom** [comment]
Fixed, but now there is another issue where after logging in the page simply redirects to / and not https://invidio.us/ this means that instead of redirecting to invidious's home page it instead redirects to the proxy's home page. Other than that the issues with proxied logins are fixed. Thank you.

Note: after manually returning to invidious's home page the login is completed.
