### ISSUE TITLE
[Bug] Edge case: a video that "crash" the page if proxy is enabled

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2865]
**Describe the bug**
https://redirect.invidious.io/watch?v=HX-Cmi1MkPc will not load if the instance has proxy enabled. 

eg: https://yewtu.be/watch?v=HX-Cmi1MkPc https://invidious-us.kavin.rocks/watch?v=HX-Cmi1MkPc https://invidious.kavin.rocks/watch?v=HX-Cmi1MkPc

This is the first time I'm seeing that, it doesn't make any sense.

There is no stack-trace displayed on the page either.

**Steps to Reproduce**

N/A

**Logs**

```
[error] get_video: HX-Cmi1MkPc : 
[warn] i18n: Missing translation key ""
[info] 500 GET /watch?v=HX-Cmi1MkPc 60.39ms
```

**Screenshots**

N/A

**Additional context**

N/A

**Comment by SamantazFox** [comment]
weird... I'll try to investigate that.

**Comment by sertraline** [comment]
It happens for all age-restricted videos, e.g `lOMVmPPVgi4`.

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/2863

**Comment by TheFrenchGhosty** [comment]
@unixfox I don't think it's related, this one doesn't have any stacktrace.

**Comment by unixfox** [comment]
> @unixfox I don't think it's related, this one doesn't have any stacktrace.

Neither does the linked issue on some instances.
