### ISSUE TITLE
Jitsi dev is asking you a question for him to add invidious feature into that....

### ISSUE THREAD

**Issue by OrionRandD** [iv-org/invidious#2866]
Jitsi dev is asking you a question for him to add invidious feature into that....
See the thread here, with its link.
Could you answer him, and, perhaps, make jitsi even a better tool with invidious feature in that by default?
Thx for you two great opensource tools...

" OrionRandD commented Feb 5, 2022 •

Hi,
Jitsi is a great tool, but I have had problems on sharing videos with my students because it only accepts Youtube Videos or mainstream platform videos.
Since, jitsi-meet is opensource, could you, by default (meaning that we do not need to contact every jitsi free provider to add this feature), the capacity for us to circumvent Youtube and share their videos through Invidious, which is also an opensource project?
https://github.com/iv-org/invidious
Invidious can share Youtube videos through many ports we call Instances.
Thx a lot.
@saghul
Member
saghul commented Feb 5, 2022

Does that support the YT iframe API? Because that's what we use to display them. If it does, then it should be attainable to do. "

https://github.com/jitsi/handbook/issues/278#issuecomment-1030687133

**Comment by unixfox** [comment]
Closing in order to continue the discussion in https://github.com/jitsi/handbook/issues/278
