### ISSUE TITLE
[Bug] missing dependency in embed video: player.overlay is not a function (video-overlay.min.js)

### ISSUE THREAD

**Issue by VinnyVynce** [iv-org/invidious#2873]
**Describe the bug**
Hi a feature was added to add a button to link back to the instance from a embed indivious frame (see #1995)
However this feature doesn't seem to work anymore, I've looked on other instances to see if I was the only one having the issue but it doesn't seems like it.
If I'm going in on an embed link I get the following error under firefox 96: player.overlay is not a function.
I've tried copying the content of "videojs-overlay.min.js" inside player.js and it fixed the issue right away so it really seems like a missing dependency.

Thanks!

**Steps to Reproduce**
1- Go to any embed link (ex: https://yewtu.be/embed/0gct28UEKws)
2- Invidious should show up next to the seek bar but it's not
3- CTRL+SHIFT+P or F12 then console show the error mentioned above.

**Comment by SamantazFox** [comment]
Ah, nice catch ^^

This is a typo in a recent PR: https://github.com/iv-org/invidious/pull/2397/files#diff-63965ca57785af495cdc29d792cc0dfe671815e92c7f1a34d8fe5f89949e36cbR10
