### ISSUE TITLE
[Bug] Most issue pages broken since February 3rd

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2876]
**Describe the bug**

Originally discussed on Matrix.

Most (if not all?) error page are broken  since a PR from February 3rd

**Steps to Reproduce**

Broken: https://yt.artemislena.eu/watch?v=plHrNpNd9zk (dated February 3rd)

Works: https://inv.cthd.icu/watch?v=plHrNpNd9zk (dated February 2nd)

example from https://github.com/iv-org/invidious/issues/2863

**Logs**

N/A

**Screenshots**

![broken](https://user-images.githubusercontent.com/47571719/153095803-0473deba-53d5-4104-9e37-f2a420e72329.png)

**Additional context**

N/A

**Comment by SamantazFox** [comment]
As I expected, it's a small mistake. There was two problems:
- Inherited the wrong class (`InfoException` instead of `Exception`) => backtrace wasn't shown
- `inititalize` function that doesn't set the error message => no single-line error message displayed either
