### ISSUE TITLE
[Bug] Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [iv-org/invidious#2877]
**Describe the bug**
The video with ID 7IpVsQVyok8 cannot be loaded in Invidious.

**Steps to Reproduce**
1. Go to /watch?v=7IpVsQVyok8
2. Note that it has not worked

**Logs**
Title: `Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)`
Date: `2022-02-09T02:29:47Z`
Route: `/watch?v=7IpVsQVyok8`
Version: `2022.02.09-4272ee7 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element &quot;twoColumnWatchNextResults&quot; (BrokenTubeException)
  from /usr/lib/crystal/core/json/any.cr:102:10 in &#39;extract_video_info:video_id&#39;
  from /usr/lib/crystal/core/hash.cr:1139:13 in &#39;get_video:region&#39;
  from src/invidious/routes/watch.cr:63:15 in &#39;handle&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/invidious/helpers/static_file_handler.cr:167:15 in &#39;call&#39;
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/lib/crystal/core/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;run&#39;
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in &#39;??&#39;
```
</p>
</details>

**Comment by matthewmcgarvey** [comment]
Seeing this error in https://github.com/iv-org/invidious/issues/602 as well (id of `ccq8ctJ4PKY` is an example)

For the video `7IpVsQVyok8` it is because it is age restricted.

I think the key element we don't have yet and should add is checking the "playability status" that's in the json response


`player_response.dig("playabilityStatus", "status")` (would be added right above [this line](https://github.com/iv-org/invidious/blob/e2fc64296dacf6ce8a406183c1bb6388dce6d117/src/invidious/videos.cr#L926))

Example statuses:
`7IpVsQVyok8` (age restricted): LOGIN_REQUIRED
`ccq8ctJ4PKY` (geoblocked in the US): UNPLAYABLE
`eHciRT5B3CI` (normal video that works): OK

<details>
<summary>Full playabilityStatus JSON for `7IpVsQVyok8`</summary>
<br>

```json
{
  "playabilityStatus": {
    "status": "LOGIN_REQUIRED",
    "reason": "Sign in to confirm your age",
    "errorScreen": {
      "playerErrorMessageRenderer": {
        "subreason": {
          "runs": [
            { "text": "This video may be inappropriate for some users." }
          ]
        },
        "reason": { "simpleText": "Sign in to confirm your age" },
        "proceedButton": {
          "buttonRenderer": {
            "style": "STYLE_OVERLAY",
            "size": "SIZE_DEFAULT",
            "isDisabled": false,
            "text": { "simpleText": "Sign in" },
            "navigationEndpoint": {
              "clickTrackingParams": "CAQQ8FsiEwjAnNuBu_T1AhUSY5gKHfA_BgI=",
              "commandMetadata": {
                "webCommandMetadata": {
                  "url": "https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den&hl=en",
                  "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
                  "rootVe": 83769
                }
              },
              "signInEndpoint": {
                "nextEndpoint": {
                  "clickTrackingParams": "CAQQ8FsiEwjAnNuBu_T1AhUSY5gKHfA_BgI=",
                  "urlEndpoint": { "url": "" }
                }
              }
            },
            "trackingParams": "CAQQ8FsiEwjAnNuBu_T1AhUSY5gKHfA_BgI="
          }
        },
        "thumbnail": {
          "thumbnails": [
            {
              "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
              "width": 140,
              "height": 100
            }
          ]
        },
        "icon": { "iconType": "ERROR_OUTLINE" }
      }
    },
    "desktopLegacyAgeGateReason": 1,
    "contextParams": "Q0FFU0FnZ0M="
  }
}
```

</details>

**Comment by SamantazFox** [comment]
> `player_response.dig("playabilityStatus", "status")` (would be added right above [this line](https://github.com/iv-org/invidious/blob/e2fc64296dacf6ce8a406183c1bb6388dce6d117/src/invidious/videos.cr#L926))

There is already a check for that a bit above:
https://github.com/iv-org/invidious/blob/e2fc64296dacf6ce8a406183c1bb6388dce6d117/src/invidious/videos.cr#L884-L889

**Comment by matthewmcgarvey** [comment]
Maybe someone has an idea about what the desired output in these scenarios are? That method is very complicated so I don't want to throw a change at it without knowing what we should be showing people in these cases.

**Comment by SamantazFox** [comment]
@matthewmcgarvey I think that for now we shouldn't raise an exception if `"twoColumnWatchNextResults` is missing. That way, the frontend will diplay the `"reason"` below the video (ideally, this "reason" should be parsed, mapped to different cases (enum?), so the proper error message (translated) could be shown to the user, eventually above/in place of the player.

**Comment by TheFrenchGhosty** [comment]
Found this issue on a private ended livestream

**Comment by unixfox** [comment]
> Found this issue on a private ended livestream

Probably because youtube flagged the livestream as age restricted. Just look at the error given for the video on the real www.youtube.com...

**Comment by TheFrenchGhosty** [comment]
@unixfox 



> > Found this issue on a private ended livestream
> 
> Probably because youtube flagged the livestream as age restricted. Just look at the error given for the video on the real [www.youtube.com](http://www.youtube.com)...

I did, and there's nothing than: 

![s](https://user-images.githubusercontent.com/47571719/153499317-bfce4ebc-ef6f-4a21-80ad-57766ad621e0.png)

**Comment by SamantazFox** [comment]
@TheFrenchGhosty do you mind sharing the video ID? (In DM on matrix, if you prefer)

**Comment by TheFrenchGhosty** [comment]
@SamantazFox Sent on Matrix.
