### ISSUE TITLE
Bug in flixify or smt

### ISSUE THREAD

**Issue by asdfiapjdf** [iv-org/invidious#2898]
![Screenshot 2022-02-13 3 35 00 PM](https://user-images.githubusercontent.com/92223560/153776054-83af6a4d-0e51-4599-8a11-e11eb18ea7cc.png)

**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/92223560/153776057-72555510-4180-415a-89c9-a7a6fc0ec901.png)

**Comment by asdfiapjdf** [comment]
someone help?

**Comment by unixfox** [comment]
Are you using a public instance? If so which one? Or did you install Invidious locally?

Please give more context, we can't guess everything...

**Comment by asdfiapjdf** [comment]
I didn't install Invidious so i'm probably using a public instance

**Comment by asdfiapjdf** [comment]
Oh nevermind it is working again

**Comment by unixfox** [comment]
Ok if you are having some issues please try to use another instance from this list: https://instances.invidious.io

We have no controls over the public instances so we can't fix them.

**Comment by asdfiapjdf** [comment]
Alright thank you.

**Comment by TheFrenchGhosty** [comment]
@asdfiapjdf This instance is violating the AGPL. Do not use it.
