### ISSUE TITLE
[Suggestion/Enhancement] Accept privacy pass instead of annoying captchas.

### ISSUE THREAD

**Issue by TylerHobanDotCom** [iv-org/invidious#290]
Privacy Pass is an extension where you can bypass captchas on some sites by solving one captcha to get points. It's widely accepted as a bypass for captchas by many. Since there is no other captcha options available right now this would be good.

Link to extension: https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/
GitHub: https://github.com/privacypass/challenge-bypass-extension

**Comment by omarroth** [comment]
Sorry for the delay in response. I've been spending some time trying to understand how it works, so I haven't had a chance to provide any proper thoughts. 

It appears to me that Invidious would have to implement functionality described [here](https://github.com/privacypass/challenge-bypass-server). I could very likely be misunderstanding what would have to be implemented, but it appears to require special cryptographic primitives among other things, which makes implementation in another language difficult.

If there are any other resources that you think might help, such as a tutorial for implementing, or an implementation by another open-source project then I would be very grateful. Currently though, I expect it to be a while before this is implemented.
