### ISSUE TITLE
[Bug] Permission denied for tables

### ISSUE THREAD

**Issue by tperocks** [iv-org/invidious#2902]
**Describe the bug**

I was following the installing instruction from [here](https://ubunlog.com/en/invidious-alternate-front-end-youtube/) which I believe is identical to the instructions [here](https://docs.invidious.io/Installation.md).

Everything went well except that it shows the following 'permission denied' error in all video pages, and some other 'permission denied' error in cli.

I followed [this](https://github.com/iv-org/invidious/issues/881#issuecomment-554304946) and changed everything into trust but didn't work.

It seems to deny permission on all tables. What should I do to let it get access to the tables?

Please tell me if any there's any further info that I should provide to better discuss this situation.

Thank you in advance!

**Logs**

In Video Pages:

Title: `permission denied for table videos (PQ::PQError)`
Date: `2022-02-14T12:41:59Z`
Route: `/watch?v=CxuiFNYnEr4`
Version: `2022.02.14-8af202e8 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
permission denied for table videos (PQ::PQError)
  from /usr/share/crystal/src/primitives.cr:266:3 in &#39;handle_error&#39;
  from lib/pg/src/pq/connection.cr:184:9 in &#39;handle_async_frames&#39;
  from lib/pg/src/pq/connection.cr:162:7 in &#39;read&#39;
  from lib/pg/src/pq/connection.cr:157:7 in &#39;perform_query&#39;
  from lib/db/src/db/statement.cr:93:9 in &#39;query:args&#39;
  from lib/db/src/db/query_methods.cr:61:12 in &#39;select&#39;
  from src/invidious/videos.cr:1076:7 in &#39;get_video:region&#39;
  from src/invidious/routes/watch.cr:63:15 in &#39;handle&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from /usr/share/crystal/src/primitives.cr:266:3 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/invidious/helpers/static_file_handler.cr:167:15 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/share/crystal/src/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/share/crystal/src/primitives.cr:266:3 in &#39;run&#39;
  from ???
```
</p>
</details>

In CLI:

```
Unhandled exception in spawn: permission denied for table channels (PQ::PQError)
  from /usr/share/crystal/src/primitives.cr:266:3 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'begin'
  from src/invidious/jobs.cr:10:15 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
Unhandled exception in spawn: permission denied for table users (PQ::PQError)
  from /usr/share/crystal/src/primitives.cr:266:3 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'begin'
  from src/invidious/jobs.cr:10:15 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
Unhandled exception in spawn: permission denied for table channel_videos (PQ::PQError)
  from /usr/share/crystal/src/primitives.cr:266:3 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_all:as'
  from src/invidious/database/channels.cr:156:5 in 'begin'
  from src/invidious/jobs.cr:10:15 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

```

**Comment by unixfox** [comment]
Only the official document is supported, when using external documentation you are on your own.

You most likely have forgotten to add the correct postgresql permissions to the user invidious.

If you are novice in linux we recommend using docker which will setup everything for you automatically: https://docs.invidious.io/Installation.md

**Comment by SamantazFox** [comment]
@tperocks note that there is a subtle difference between our official installation documentation and the docs you were following: https://docs.invidious.io/Installation.md#set-up-postgressql

I recommend to run the following and follow the DB instructions from our official docs:
```
sudo -i -u postgres
dropdb invidious
dropuser kemal
exit
```

**Comment by tperocks** [comment]
> @tperocks note that there is a subtle difference between our official installation documentation and the docs you were following: https://docs.invidious.io/Installation.md#set-up-postgressql
> 
> I recommend to run the following and then follow the instructions from our official docs (see link above):
> 
> ```
> sudo -i -u postgres
> dropdb invidious
> dropuser kemal
> exit
> ```

Worked like a charm! Thank you!

I've noticed, after reading your reply, that there's a "sudo systemctl start postgresql" command in the docs I was following.

Do you mind telling me why could it made such a difference? Since I'm new to this, there's still a lot for me to learn.

Thank you!

**Comment by SamantazFox** [comment]
> Worked like a charm! Thank you!

You're welcome :)

> I've noticed, after reading your reply, that there's a "sudo systemctl start postgresql" command in the docs I was following.
> 
> Do you mind telling me why could it made such a difference? Since I'm new to this, there's still a lot for me to learn.

That command simply starts the PostgreSQL service (a.k.a "daemon"). Many linux distributions (like debian, ubuntu) will automatically start Postgres when you install it, and set it to autostart on boot. Doing so manually is generally not required.

If you wonder why we don't include that in our documentation, this is because they're a guide for the specificities of invidious, aimed at both new and experienced users.

The documentation expects that the reader knows (or to be able to search on internet) about some linux basics, like using the terminal, starting/stopping system services and knowing what software is already installed/running.
