### ISSUE TITLE
[Bug] Age restriction bypass isn't working consistently

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2905]
**Describe the bug**

The age restriction bypass isn't working consistently, it will only properly work after ~5 requests (just refreshing the page on the instance works). When it works once, it will work consistently everytime (because of caching I'm guessing).

**Steps to Reproduce**

- Load an age restricted video
- Get the error page (see screenshot) 
- Refresh the page
- After ~5 requests it will work

**Logs**

N/A

**Screenshots**

![error](https://user-images.githubusercontent.com/47571719/154084411-a6e3e59a-864e-4d89-98ce-a323c46380a9.png)

**Additional context**

I can provide some examples videos IDs at request.

On a related note: the age restricted videos, don't have descriptions.

**Comment by unixfox** [comment]
Might be better to continue the discussion in https://github.com/iv-org/invidious/issues/2189 instead.

**Comment by TheFrenchGhosty** [comment]
@unixfox 

> Might be better to continue the discussion in #2189 instead.

This is different, #2189 is an edge case (that seems to be an issue on our end), this issue is for a youtube change breaking every single age restricted videos.

**Comment by TheFrenchGhosty** [comment]
> It's literally the same issue as #2905, it focuses on all the age-restricted videos. Youtube also broke our way of fetching the age-restricted videos back in the days in [#2189 (comment)](https://github.com/iv-org/invidious/issues/2189#issuecomment-887253427)

But it used to work, this is something "new" that broke all of them.

**Comment by unixfox** [comment]
Like I said in https://github.com/iv-org/invidious/issues/2905#issuecomment-1040378223, we also had youtube breaking our bypass and we didn't create a new issue.

IMO it's better to continue the discussion in https://github.com/iv-org/invidious/issues/2189 as it is way more popular than in #2905

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/2189
