### ISSUE TITLE
Find a way to filter out shady parts of Youtube kids.

### ISSUE THREAD

**Issue by LinuxBeaver** [iv-org/invidious#2908]
Long story short, there are sketchy poorly moderated corners of Youtube where little girls film themselves playing and doing gymnastics and dance activities ect.... this shit appeals to pedophiles and could lead to scenarios where invidious moderators run into trouble with law enforcement.  This could be prevented If Invidious filtered out parts of Youtube kids relating to problematic keywords, such as things relating to children dancing and doing  gymnastics.  Invidious users will still be able to listen to music, a kids show,  or cartoon on the Youtube kids side but they will not be able to find content of little girls doing gymnastics or any other weird stuff.

Please take this seriously.

**Comment by unixfox** [comment]
Invidious is just a platform that proxy existing content, and we don't plan to censor videos.

@TheFrenchGhosty @SamantazFox your take on this?

**Comment by TheFrenchGhosty** [comment]
Completely out of scope. We're a YouTube frontend, it's YouTube/the police role to solve this, not ours.

>this shit appeals to pedophiles and could lead to scenarios where invidious moderators run into trouble with law enforcement

Instance don't host the content + see the laws about platforms not being responsible of the content posted by their users.

**Comment by SamantazFox** [comment]
> [this] could lead to scenarios where invidious moderators run into trouble with law enforcement.

There is no such thing as invidious moderator.
We don't host content, we simply proxy stuff from Google.

Google are the ones with billions of dollars and AI to filter that.
Not our problem if their moderation is crap.
