### ISSUE TITLE
Same bug as #2918 but i have Crystal 1.2 already

### ISSUE THREAD

**Issue by solisinvictum** [iv-org/invidious#2927]
Like the Title says, i have the same Error like in #2918 

The funny part is, im on 1.2.2 already since 20.01.2022 (https://github.com/iv-org/invidious/issues/2783#issuecomment-1017063626) 

```
Crystal 1.2.2 [6529d725a] (2021-11-10)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

```
[...]
Checking player dependencies...
Player dependencies are satisfied
Showing last frame. Use --error-trace for full trace.

In src/invidious/routes/playlists.cr:227:23

 227 | if !plid || !plid.starts_with?("IV")
                         ^-----------
Error: undefined method 'starts_with?' for Array(String) (compile-time type is (Array(String) | Bool | Float64 | Int32 | Int64 | Invidious::User | Preferences | String))
```

**Comment by TheFrenchGhosty** [comment]
@solisinvictum Hello, see the solution: https://github.com/iv-org/invidious/issues/2918#issuecomment-1048146335

We updated the documentation to reflect this change.

**Comment by solisinvictum** [comment]
Still the same Error.

**Comment by TheFrenchGhosty** [comment]
@solisinvictum Are you sure your shards.lock is the one from the repo and not one updated by a previous `shards update`?

(you can check with `git status`)

**Comment by solisinvictum** [comment]
Deleted whole VM. Reinstalled completly. Fails everytime at the same error. 

I try again with Arch's AUR package (until now it was a debian vm).

**Comment by solisinvictum** [comment]
Roflmao.

Im stupid af.

i reversed the usage of shards install --production everytime, because after that i started the Updater Script because of lazyness. 

I edited the Updater Script from @tmiland and started a PR: https://github.com/tmiland/Invidious-Updater/pull/81

**Comment by TheFrenchGhosty** [comment]
@solisinvictum 

All good, glad it's working.

Thanks for sending the PR
