### ISSUE TITLE
[Bug] Infinite loading due to lack of timeouts

### ISSUE THREAD

**Issue by joe27g** [iv-org/invidious#2931]
**Describe the bug**

The `/videoplayback` endpoint doesn't seem to have any timeout. The underlying slowness (as seen below) is most likely due to YouTube throttling, since speeds/latency to other sites are fine. Also, I run the instance behind a VPN, so its IPs are probably frequently used for invidious and/or youtube-dl.
![image](https://user-images.githubusercontent.com/20873239/155389500-42bbf5c8-6f96-44e2-8c94-8167ce4a1cb0.png)
However, it doesn't make sense that the client never times out and never retries fetching missing chunks.
At first, it may seem like this is a duplicate of #1447, but I think there should be a timeout on both the server side and client side. Doing so would make it impossible for an "infinite loading" state caused by a request being lost, as seen in the logs below. Note that I let it sit for over 15 minutes to see if anything would happen, and the request never failed.

**Steps to Reproduce**
1. Start an instance with DASH enabled, highest default quality
2. Enable video playback proxy
3. Put the instance behind a VPN (or something else to artificially increase latency/reduce speed/cause YouTube throttling)
4. With the server having a sufficiently bad/throttled connection, it should be possible to get this infinite loading state.

(Although this is an intermittent issue, when it does happen, it does so on nearly every video until reconnecting the server to the VPN. Hence I believe it would be possible to reproduce by throttling the speed or enabling a firewall to block requests during playback.)

**Logs**

![image](https://user-images.githubusercontent.com/20873239/155385954-1c7683b5-7971-4ef5-bcee-8dbee5c62230.png)

**Comment by SamantazFox** [comment]
> The `/videoplayback` endpoint doesn't seem to have any timeout.
> [SNIP]
> However, it doesn't make sense that the client never times out and never retries fetching missing chunks.

There is actually a timeout of ~11s between invidious and google servers. The entries that took around 11'000ms are exactly that. But because the video is transferred by chunks (~8 to 30kB) , there is always data coming from the server. Invidious never stops responding. It's only being extremely slow.

A practical example: If the browser requests a range of bytes (say from 100'000 to 250'000, which is a block of 150 kilobytes), and that the server sends a chunk of 10 kB every second, once the 11s timeout has been reached, invidious will drop the connection with the google video server. 110 kB have been transferred to the client (your browser), which will request the next block of data starting from where it left (i.e another block of 150kB, from 210'000 to 360'000). And so on.

That's why requests never fail.

> Note that I let it sit for over 15 minutes to see if anything would happen, and the request never failed.

It doesn't fail because the server returns the expected data, but extremely slowly.
I've plans to implement throttling bypass, but for the moment, there isn't much we can do about it.

**Comment by joe27g** [comment]
Thank you for pointing out how the upstream fetching works, it helped me a lot to understand what the backend is doing when being throttled like this. However, when you say that after the timeout, the fetched part is returned to the client (in the example, the 110kB out of the requested 150kB), it seems like that tends to fail occasionally, causing the "stuck" issue. One thing I did try to mitigate this was adding a timeout to the videojs requests to [assets/js/player.js](https://github.com/iv-org/invidious/blob/master/assets/js/player.js#L43-L48):
```js
videojs.Vhs.xhr.beforeRequest = function(options) {
    if (options.uri.indexOf('videoplayback') === -1 && options.uri.indexOf('local=true') === -1) {
        options.uri = options.uri + '?local=true';
    }
    options.timeout = 30000; // << Added code
    return options;
};
```
Although it didn't exactly fix it, it made the player re-cache chunks after seeking back a bit, whereas trying to seek back without that change, it would just play back that part and get stuck again (thus forcing you to refresh the page to continue watching.) I'm not sure why though, since the browser logs didn't show any timeouts happening. Still, I think this small addition could be useful for servers/users with slow connections.

However, as I was writing this comment, I realized my invidious version was out of date. Since f013a6b switches the player to something entirely different, this issue likely won't be relevant anymore. (I say likely because there are several other problems with that change preventing this problem from showing up.) Hopefully this timeout won't be needed, but I figured it was worth commenting in case it is in the future.

**Comment by joe27g** [comment]
Unfortunately it seems like this issue didn't completely go away. The original problem of a request never finishing and the client getting stuck seems much more rare, but still exists. Perhaps that's just because I enabled a reverse proxy with HTTP/2. Strangely, there is a similar new way it gets stuck - sometimes, due to the aforementioned ~11s timeout and slow response times in general, it will stop loading when the last chunk it received was <500KB or so.

![image](https://user-images.githubusercontent.com/20873239/158735310-9468764f-7f00-4220-a83f-a4e3dc1bc86b.png)

However, unlike the previous version of the player, the timeout is not necessary to make the player start loading chunks again after seeking back, as I mentioned before:

> trying to seek back without that change, it would just play back that part and get stuck again (thus forcing you to refresh the page to continue watching.)

So, because it's only a slight inconvenience at this point, I'm not going to reopen the issue. Just leaving this here as a reference for other people having the same problem.
