### ISSUE TITLE
[Bug] database files are incompatible with server

### ISSUE THREAD

**Issue by JackHewson** [iv-org/invidious#2933]
From @unixfox: 
We don't recommend using the `docker-compose.yml` straight from the repository because it is not for production but just for development. You should use the docker-compose from the documentation: https://docs.invidious.io/Installation.md

Do note that you will need to switch from `docker.io/library/postgres:14` to `docker.io/library/postgres:10`.

-----

**Describe the bug**
```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 14.2 (Debian 14.2-1.pgdg110+1).
```

**Steps to Reproduce**
1. Use an existing invidious instance for several days
2. Git update to the last commit of Feb 23, 2022.
3. Run the docker compose file

**Comment by rachmadaniHaryono** [comment]
i run invidious from repo, so i just reset to 5d1a1fef

**Comment by rachmadaniHaryono** [comment]
i can confirm above suggestion working

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index cd1df4ff..af4f3ed4 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -39,7 +39,7 @@ services:
       - invidious-db

   invidious-db:
-    image: docker.io/library/postgres:14
+    image: docker.io/library/postgres:10
     restart: unless-stopped
     volumes:
       - postgresdata:/var/lib/postgresql/data
```

**Comment by unixfox** [comment]
We don't recommend using the `docker-compose.yml` straight from the repository because it is not for production but just for development. You should use the docker-compose from the documentation: https://docs.invidious.io/Installation.md

Do note that you will need to switch from `docker.io/library/postgres:14` to `docker.io/library/postgres:10`.

**Comment by TheFrenchGhosty** [comment]
I'll be working on a migration guide soon-ish, we definitely need to have people move away from 10 since it EOL in 10 months.

**Comment by Mario-Hofstaetter** [comment]
> We don't recommend using the `docker-compose.yml` straight from the repository because it is not for production but just for development. You should use the docker-compose from the documentation: [docs.invidious.io/Installation.md](https://docs.invidious.io/Installation.md)
> 
> Do note that you will need to switch from `docker.io/library/postgres:14` to `docker.io/library/postgres:10`.

I followed the docs at https://docs.invidious.io/installation/#docker-compose-method-production which uses postgres 14 an still got the issue...
