### ISSUE TITLE
[Bug] Can't see subtitles

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2940]
**Describe the bug**
Even when activated, subtitles are not appearing.

**Steps to Reproduce**

1. Go to 'CC'
2. Select a language
3. No subtitles

**Screenshots**

**Additional context**
- Browser (if applicable): Firefox

**Comment by unixfox** [comment]
Are you using a public instance? If so your issue is a duplicate of https://github.com/iv-org/invidious/issues/2567
