### ISSUE TITLE
[Bug] No timestamp when hovering the progress bar

### ISSUE THREAD

**Issue by hl2guide** [iv-org/invidious#2941]
**Is your enhancement request related to a problem? Please describe.**
The video player does not show the timestamp for the point on the trackbar (when am I jumping to?)

**Describe the solution you'd like**
Please add a timestamp to the trackbar hover thumbnail in the video player.

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by unixfox** [comment]
Fixed in https://github.com/iv-org/invidious/pull/3011

Not intentional, I just happened to see that it got fixed in a newer videojs version.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/4016501/163730315-c2c4369c-dd41-40c5-a291-3e52978ee832.png">
