### ISSUE TITLE
[Bug] Rotating pauses video

### ISSUE THREAD

**Issue by IronMaltese** [iv-org/invidious#2942]
**Describe the bug**

When rotating from landscape to vertical on iOS, the video leaves fullscreen and pauses
**Steps to Reproduce**

**Screenshots**

https://user-images.githubusercontent.com/89056889/155855110-dc6e7454-c399-4d73-8ddd-0022ac3d87c0.MOV

**Additional context**

**Comment by IronMaltese** [comment]
Rotating doesn’t work on either YouTube or Invidious player styles

**Comment by unixfox** [comment]
Do you experience the issue on the demo page of videojs too: https://videojs.com/advanced?video=disneys-oceans?

**Comment by IronMaltese** [comment]
The issue doesn’t appear on that website

**Comment by IronMaltese** [comment]
This issue seems to be very inconsistent, since sometimes the video pauses when I rotate my phone but other times it does not, so as long as it doesn’t pause, this behavior should be good

**Comment by BlipRanger** [comment]
I can confirm that I have encountered this issue on iOS as well. It's not very consistent, but it is annoying. I wonder if it was a change with iOS.
