### ISSUE TITLE
[Bug] Can not stream download link in latest version

### ISSUE THREAD

**Issue by mdpe-ir** [iv-org/invidious#2943]
**Describe the bug**

YouTube links are restricted in my country, so I used invidious download links to stream YouTube videos in my app.

 for example : 

**GOLANG CODE TO GET DOWNLOAD LINK:**
```go

getDownloadLinkBody := url.Values{}
getDownloadLinkBody.Add("id", videoDownloader.Id)
getDownloadLinkBody.Add("title", videoDownloader.Title)
getDownloadLinkBody.Add("download_widget", "{\"itag\":"+videoDownloader.Itag+",\"ext\":\"mp4\"}")

req, err := http.NewRequest("POST", "http://127.0.0.1:3000/download", strings.NewReader(getDownloadLinkBody.Encode()))
req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
if err != nil {
	panic(err)
}
client := new(http.Client)
client.CheckRedirect = func(req *http.Request, via []*http.Request) error {
	return errors.New("Redirect")
}

response, err := client.Do(req)

urlFinal := "http://serverIP:3000" + response.Header.Get("Location")

return c.Redirect(urlFinal)
```

In the latest invidious version, I can download videos very well. but I can not play the link on video player 

**Logs**

Sample link result : 
`http://serverIP:3000/videoplayback?expire=1646076009&ei=CcwcYsPyHoWA6dsPqbOa-AM&ip=XX.XX.XX.XX&id=o-ANVX932YJllaDFDSeqtozK7E6-P8GOMBCl1-proYyv2v&itag=22&source=youtube&requiressl=yes&mh=iO&mm=31%2C26&mn=sn-4g5e6nsz%2Csn-f5f7lne6&ms=au%2Conr&mv=u&mvi=5&pl=24&gcr=de&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=488.756&lmt=1645992525929688&mt=1646053645&fvip=5&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgCGXWCXiYSJ9jLvzLocRp4gLcir1afwA1PGsg3vk_BM0CIQCzZdr8V0ECHJ-rp5uGaq7McJgna7A5hx3Kc27tcLuSBQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLqefRNVC74wlNncn-LiYA-COxN82RehHdbTrxsRbRE4CIQCbyzF5UOOeoJFyyDGzBZsSbyNp0FhrWKqaSuyayOZaPQ%3D%3D&host=rr5---sn-4g5e6nsz.googlevideo.com&title=e9BIS442PM8-McMaster%20says%20Putin%20%22got%20a%20lot%20more%20than%20he%20bargained%20for%22%20with%20Ukraine%20invasion.mp4`

**Screenshots**
![image](https://user-images.githubusercontent.com/57597379/155994231-e83d0543-c067-4280-99fc-ead3e5dcac1a.png)

**Comment by unixfox** [comment]
Have you tried with vlc?

**Comment by mdpe-ir** [comment]
> Have you tried with vlc?

yes. Also with kmplayer
Even if the link is downloaded with the download manager, it loses the pause feature.

**Comment by unixfox** [comment]
Is the video blocked in your country? Are you using a locally installed invidious instance?

Did you try with another basic video like this one: https://www.youtube.com/watch?v=jNQXAC9IVRw

**Comment by mdpe-ir** [comment]
> Did you try with another basic video like this

i downgrade invidious  to
```
 {
  "name": "invidious",
  "version": "2021.12.28-a779cdd4",
  "branch": "master"
}

```

version 
and 
Get video from 

`/latest_version?download_widget={%22id%22:%22e9BIS442PM8%22,%22itag%22:%2218%22,%22title%22:%22McMaster%20says%20Putin%20\%22got%20a%20lot%20more%20than%20he%20bargained%20for\%22%20with%20Ukraine%20invasion.mp4%22}`

And everything works fine again

**Comment by unixfox** [comment]
You didn't reply to my questions.

**Comment by mdpe-ir** [comment]
> Is the video blocked in your country? 

YouTube is completely restricted in my country, but I installed invidious on a server in Germany and I use the invidious  download section to access the videos in my  application 
Everything worked fine on the version I mentioned in the previous comment

>Did you try with another basic video like this one: https://www.youtube.com/watch?v=jNQXAC9IVRw

Yes, I tried many videos

**Comment by SamantazFox** [comment]
Hello! I'm not sure why you want a download link to play the video?

If you want to download it, directly paste the link in your browser, and you'll get a mp4 or webm file.
If you only want to play the video (in VLC, or anything else), use:
`/latest_version?id=<video_id>&itag=<itag>&local=true`

**Comment by mdpe-ir** [comment]
> Hello! I'm not sure why you want a download link to play the video?
> 
> If you want to download it, directly paste the link in your browser, and you'll get a mp4 or webm file. If you only want to play the video (in VLC, or anything else), use: `serverIP:3000/latest_version?id=<video_id>&itag=<itag>&local=true`

oh thanks a million 💯  it's solved my problem
