### ISSUE TITLE
[Bug] Subscriptions list is not up to date

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2945]
**Describe the bug**
In "subscriptions" page, some channels i subscribed don't really show the last video published by the said channels. For example, i subscribed to watchmojo and according the said page, their last video has been published 2 month ago whereas their latest video had been published 2 hours ago.

**Steps to Reproduce**
1. Go to Invidious
2. Log-in
3. Go to "subscriptions"

**Screenshots**
Latest WM video according to subscriptions manager (1 month)
![Screenshot_20220301_203841](https://user-images.githubusercontent.com/22192600/156237243-500a1e50-6d24-42e4-a0e5-71ecd1d3fd9d.png)

Latest WM video according to WM channel page (2 hours)
![Screenshot_20220301_204007](https://user-images.githubusercontent.com/22192600/156237486-8c743f02-3caa-4f08-91eb-b0c2a0ad59a5.png)

Screenshots have been taken at few seconds intervals.

**Comment by SamantazFox** [comment]
Hello! Is that your instance? If yes, could you share your config file (make sure to redact the passwords/tokens)? If no, is that a public instance?

**Comment by stemy2** [comment]
This is the flagship instance.

**Comment by unixfox** [comment]
Can you give the URL of the instance please.

**Comment by stemy2** [comment]
invidious.snopyta.org

**Comment by unixfox** [comment]
Please use other instances: https://instances.invidious.io.
The owner of that instance has probably deactivated something related to the refresh of the subscriptions because he doesn't want people to register to the instance anymore.
