### ISSUE TITLE
[Bug] DASH Rapidly Dropping Quality With No Cause

### ISSUE THREAD

**Issue by BlipRanger** [iv-org/invidious#2948]
**Describe the bug**
While using DASH streaming on a self-hosted instance, quality drops substantially without any changes in network stability/congestion. This has only begun to occur in the last month really. Running the latest version of Invidious via docker. 

**Steps to Reproduce**
1. Host Invidious Via Docker
2. Watch video via DASH
3. A minute or so in, quality auto drops from 1080p -> 240p
4. If you change quality back to 1080p, the video stops loading entirely, buffers indefinitely. 
5. If you try to move to a different point in the video, also stops/buffers indefinitely. 

**Logs**
No changes in logs, no errors. 

**Screenshots**
N/A

**Additional context**
 - Browser (if applicable): Firefox/Chrome
 - OS (if applicable): Windows, Hosted on Debian

**Comment by SamantazFox** [comment]
Probably due to #2407

**Comment by BlipRanger** [comment]
> Probably due to #2407

Ah yep, you're probably right. Does proxying help that any or is it just pretty much going to happen regardless?

**Comment by SamantazFox** [comment]
> Ah yep, you're probably right. Does proxying help that any or is it just pretty much going to happen regardless?

DASH already forces proxying (because of technical reasons) so no, that won't change anything ^^
Try using a public instance.
