### ISSUE TITLE
[Bug] Subscriptions are hella bugged

### ISSUE THREAD

**Issue by Relms12345** [iv-org/invidious#2953]
**Describe the bug**
I don't really know the best say to describe this bug but basically the subscriptions feature has been rly bugged for me. Like one second the notifications would show I have 0 notifications and on the next refresh it will show some arbitrary number like "10494" for example. Then I would click it and it go to the subscriptions/feed page and show either "0" notifications or it will show notifications from videos posted like hours or even days ago when I already got them. And a lot of times the feed does not update properly and show new videos posted at all. I have tried restarting the instance many times, done a fresh install and wiped the DB and deleted and recreated the account to no avail. I do not know crystal so I am unsure what is going on. The instance is https://yt.relms.dev and it is on the latest version from quay.io.

**Logs**
The logs does not show me anything out of the ordinary.

**Screenshots**
These screenshots are taken mere seconds from each other
![image](https://user-images.githubusercontent.com/57138119/156943481-f921752d-aadd-4dc5-9c01-3279e82eccf6.png)
![image](https://user-images.githubusercontent.com/57138119/156943501-beba4178-6b99-4d2e-97e7-fc3045855d71.png)

**Config**
Here is my config env var that I set in docker-compose.yml
![image](https://user-images.githubusercontent.com/57138119/156943598-86885c28-128f-4d67-ab79-e5ca2c2df2b0.png)

**Additional context**
The database is Postgres 14.0. The issue started when I upgraded to 14.2 so I figured I would downgrade the DB version to see if it would fix it somehow but to no avail.
The OS that the server is on is Ubuntu 21.10
I am on the latest docker and docker-compose version

**Comment by unixfox** [comment]
Are you the only user on your instance? If so could you try with postgresql 10 if that fixes the issue?

**Comment by Relms12345** [comment]
I am the only user on my instance so I can try that and get back to you

**Comment by Relms12345** [comment]
@unixfox nope same issue

**Comment by SamantazFox** [comment]
@Relms12345 In addition to what I said in https://github.com/iv-org/invidious/issues/2954#issuecomment-1060242192, could you please try to run this:
https://samantaz.fr/files/invidious/psql_disk_usage.sh

**Comment by Relms12345** [comment]
@SamantazFox Yep the advise you gave in #2954 seemed to help and the sizes seems to be back down to what they should be. And as for this bug, it seems to be not affecting me anymore after I turned off Full Refresh. Thanks everyone for the help.

**Comment by unixfox** [comment]
The issue is that you won't get the new videos in your subscription feed unless you are have pubsub enabled.

**Comment by Relms12345** [comment]
ah ok thanks for the heads up. i went ahead and enabled it.
