### ISSUE TITLE
[Bug] extremely high disk writing to postgres 10

### ISSUE THREAD

**Issue by Relms12345** [iv-org/invidious#2954]
While I was being helped in #2953, the guy told me to try Postgres 10 instead of 14. And I did that route (which still didnt fix #2953) and left it running for a couple hours. and after a while i realized that my server was being extremely slow for some reason. so i did some digging around and I saw this...
![image](https://user-images.githubusercontent.com/57138119/156949796-3270987c-40a3-4871-9aa7-bf12c8db907d.png)
So i ran 'iotop' and it said the postgres instance was having extremely high io activity. so i checked the database and saw this with du.
![image](https://user-images.githubusercontent.com/57138119/156949837-f63a0399-39d0-415b-9d93-9e5f31bd2a2e.png)
not sure why that happened when i went to postgres 14 to 10 but it wrote 32gb of data in seemingly 2 hours or so. The postgres version im running is version 10.20 on docker and this is the corresponding docker-compose.yml file. the postgres config is stock with what comes with 10.20.
![image](https://user-images.githubusercontent.com/57138119/156949968-c53a1ac0-d665-410b-890a-59aee104e6d4.png)

**Comment by Relms12345** [comment]
also i had to delete the database files because i was extremely low on disk space so ill see if i can replicate it on my local computer and look through the database files to see what was being written

**Comment by martadinata666** [comment]
#2042

**Comment by SamantazFox** [comment]
You should set `full_refresh` to `false` !
Full refresh will fetch **all** the videos from **every** subscribed channels. So if you're subscribed to even a few large channels, that will be downloading metadata from thousands of videos! Add to that the fact that your refresh happens every 5 minutes (`channel_refresh_interval`) and that makes a lot of read/writes per second ^^

**Comment by Relms12345** [comment]
yea that would make sense haha. I forgot I had even set that. And as for the VACUUM, on my regular production DB I do have that set. This was just a test DB I setup for #2953 and figured it might be a bug with Invidious. But I can just follow the instructions in link you sent and monitor the disk IO. And I'll reopen this if it still happens. Thanks!

**Comment by Relms12345** [comment]
Yep everything seems to be in order now. Thanks for the help!
