### ISSUE TITLE
[Bug] Download of subtitle files fails.

### ISSUE THREAD

**Issue by Lukas2112** [iv-org/invidious#2977]
**Describe the bug**
When downloading subtitle files, I noticed that this process always fails.

**Steps to Reproduce**
1. Go to a video you like.
2. Try to download a subtitle file.
5. See error

**Logs**
Title: `Missing hash key: "id" (KeyError)`
Date: `2022-03-18T07:40:23Z`
Route: `/download`
Version: `2022.03.15-5b82370b @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: &quot;id&quot; (KeyError)
  from /usr/share/crystal/src/hash.cr:1034:28 in &#39;captions&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from /usr/share/crystal/src/primitives.cr:266:3 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/invidious/helpers/static_file_handler.cr:112:11 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/share/crystal/src/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/share/crystal/src/primitives.cr:266:3 in &#39;run&#39;
  from ???
```
</p>
</details>

**Screenshots**
![bug-invidious](https://user-images.githubusercontent.com/47597136/158959007-50101d0b-500a-4c58-bcd8-225701187be9.png)

**Additional context**
- Mozilla Firefox 98.0
- Linux (Ubuntu 20.04.3 LTS)

**Comment by unixfox** [comment]
Which instance are you using?

**Comment by Lukas2112** [comment]
> Which instance are you using?

I have tried it on the following Invidious instances: 

- invidious.snopyta.org/ 
- https://invidious.namazso.eu/ 
- https://invidious.kavin.rocks
- https://invidious.osi.kr

**Comment by SamantazFox** [comment]
Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.

**Comment by Lukas2112** [comment]
> Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.

In the context of this, I also noticed that the subtitles cannot be displayed - would this then also be fixed?

**Comment by unixfox** [comment]
> > Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.
> 
> In the context of this, I also noticed that the subtitles cannot be displayed - would this then also be fixed?
> 

On public instances the subtitles retrieval may be blocked by google due to the high number of people requesting it.

**Comment by Lukas2112** [comment]
> > > Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.
> > 
> > 
> > In the context of this, I also noticed that the subtitles cannot be displayed - would this then also be fixed?
> 
> On public instances the subtitles retrieval may be blocked by google due to the high number of people requesting it.

So the same problem that happens with public bibliogram instances? 

Mhm, here the big, profit-oriented platforms demonstrate how they can dictate to others through their monopoly position. :/

**Comment by julianfairfax** [comment]
> > > Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.
> > 
> > 
> > In the context of this, I also noticed that the subtitles cannot be displayed - would this then also be fixed?
> 
> On public instances the subtitles retrieval may be blocked by google due to the high number of people requesting it.

Is there anything we can do about this?

**Comment by unixfox** [comment]
> > > > Ah, yep, I can reproduce! It is caused by #2922. I'll try to fix that today.
> > > 
> > > 
> > > In the context of this, I also noticed that the subtitles cannot be displayed - would this then also be fixed?
> > 
> > On public instances the subtitles retrieval may be blocked by google due to the high number of people requesting it.
> 
> Is there anything we can do about this?

https://github.com/iv-org/invidious/issues/2567

**Comment by TheFrenchGhosty** [comment]
@SamantazFox 

>Ah, yep, I can reproduce! It is caused by https://github.com/iv-org/invidious/pull/2922. I'll try to fix that today.

You forgot I think

**Comment by DrDustwolf** [comment]
I can reproduce the issue on:
https://invidious.snopyta.org/
https://invidious-us.kavin.rocks/
