### ISSUE TITLE
[Bug] Problem with closed captions

### ISSUE THREAD

**Issue by MaybeAnonymous** [iv-org/invidious#2985]
**Describe the bug**

I like watching videos with closed captions as it helps me understand what is going on better, but Invidious' closed captions do not seem to show up

**Steps to Reproduce**

1. Go to a video that has closed captions
2. Click on the closed captions buttons and choose a language
3. The captions do not show up, even if you let the video play for a while

**Screenshots**

**Youtube Site**
![image](https://user-images.githubusercontent.com/89218161/159806588-c71a0b6a-ba46-43b4-b447-6cdcbfb27b08.png)
**Invidious**
![image](https://user-images.githubusercontent.com/89218161/159806655-0af09d19-d830-4f8c-bfa0-af0530941b81.png)

**Additional context**

 - Browser (if applicable): ungoogled-chromium from Artix's universe/ repository
 - OS (if applicable): Artix Linux x86_64, Kernel: 5.16.14-artix1-1
 - Instance of Invidious: inv.riverside.rocks

**Comment by unixfox** [comment]
What's closed captions? Is it like different to normal captions?

**Comment by MaybeAnonymous** [comment]
> What's closed captions? Is it like different to normal captions?

It is the same, CC stands for Closed Captions

**Comment by unixfox** [comment]
Ok then please see https://github.com/iv-org/invidious/issues/2565#issuecomment-962516905
