### ISSUE TITLE
[Feature request] Channel groups

### ISSUE THREAD

**Issue by GasparVardanyan** [iv-org/invidious#2998]
First of all thank you for this great project!

It'll be nice to be able to group channels in separate feeds. For example, I want to have a separet feed, where I'll group tech related channels, separate feeds for different music genres, etc...

Again and again thank you for this amazing project!

**Comment by unixfox** [comment]
Is this feature similar to this one: https://github.com/iv-org/invidious/issues/2150?

**Comment by GasparVardanyan** [comment]
@unixfox  yes ))
