### ISSUE TITLE
Ability to add comments

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#300]
Is it possible to add a possibility to write comments (replies) to a video using your own google or reddit accounts?

**Comment by Perflyst** [comment]
I dont think this is possible without using the youtube api.

**Comment by omarroth** [comment]
It should be possible to emulate a browser to implement this functionality, similar to other parts of the site that use Google accounts.

it's quite a bit of work to implement. Maybe #312 will help with this, but I would not expect full integration to come quickly.
