### ISSUE TITLE
[Bug] Unable to retrieve RSS feed when url uses `user=` instead of `channel_id=`

### ISSUE THREAD

**Issue by aflyingpumpkin** [iv-org/invidious#3004]
**Steps to Reproduce**
1. Go to https://www.youtube.com/feeds/videos.xml?user=aragusea (notice how an RSS feed exists)
1. Go to https://redirect.invidious.io/feeds/videos.xml?user=aragusea (notice how an RSS feed does not exist)

**Comment by subatomic-honda-civic** [comment]
IIRC, Invidious uses a different format for RSS feeds:

https://[Instance]/feed/channel/<Channel ID>

Oh I don't think you can use "Channel Aliases" (`aragusea`), you'll have to use the ID (`UCuAXFkgsw1L7xaCfnd5JJOw`)

**Comment by SamantazFox** [comment]
Oh, sorry for not replying earlier!

Well, that's a bug. The `user` argument is parsed and indeed used, but it's actually never "resolved" to a channel ID (a.k.a "UCID"), so in the end the request fails.

Thanks for reporting it :)

**Comment by subatomic-honda-civic** [comment]
> Well, that's a bug. The `user` argument is parsed and indeed used, but it's actually never "resolved" to a channel ID (a.k.a "UCID"), so in the end the request fails.

Hmm, maybe I was doing it improperly in my RSS reader.

**Comment by aflyingpumpkin** [comment]
@subatomic-honda-civic From what I have seen YouTube has two different formats for fetching RSS feeds, and invidious only supports one (being `/channel/`.) You are doing things properly and in the only way that works. I ended up having to use some bash scripting to convert some of my old YouTube RSS feeds to use channelIDs.

**Comment by aflyingpumpkin** [comment]
If this doesn't get fixed any time soon for anyone in the future this is the bash script I used to convert `/user/` to `/channel/`:
```sh
#!/bin/sh

prefferedInstance="yewtu.be"
curl -Ls "https://$prefferedInstance/user/$1" | grep \/channel\/ | head -n 1 | sed 's/.*\/channel\/\(.*\)".*/\1/g'
```
