### ISSUE TITLE
[Bug] Video is unplayable by any instance

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#3006]
**Describe the bug**
Sometimes, i want to watch a video, but no matter wich instance i'm using, i get the same error message: "The media could not be loaded, either because the server or network failed or because the format is not supported".

**Steps to Reproduce**

1. Open a video with a random instance
2. Do the same with all others instances availables

**Comment by unixfox** [comment]
Please post the video ID.

**Comment by stemy2** [comment]
My most recent example: https://youtu.be/4wmylAORCx8

The solutions you mentioned didn't fixed anything.

**Comment by unixfox** [comment]
The video works fine with dash enabled.

**Comment by stemy2** [comment]
Nope ! Even in dash mode, the problem stills happens sometimes.
