### ISSUE TITLE
[Bug] Subscriptions feed doesn't update

### ISSUE THREAD

**Issue by laurikuparinen1987** [iv-org/invidious#3008]
I registered an account in Invidious a while back and yesterday I subscribed to 20 channels. However, the subscription feed page (/feed/subscriptions) doesn't update at all and shows me a blank page with a message: "0 unseen notifications". I checked from YouTube that my subs have added dozens of videos since yesterday and none of them appeared in Invidious subscription feed. I can see the videos in Invidious if I click on "Manage Subscriptions" and then click on the channels name, but it's really inconvenient way to check if my subscriptions have new content. What should I do to resolve the issue?

My OS: (Linux) Pop OS 20.04 LTS
Browser: Firefox 98.0.2

**Comment by unixfox** [comment]
Please post the instance used.

**Comment by laurikuparinen1987** [comment]
Ah yes, it's:  https://invidious.snopyta.org

**Comment by unixfox** [comment]
> Ah yes, it's:  https://invidious.snopyta.org

Please switch to another instance from this list: https://instances.invidious.io

Snopyta instance is broken for the subscriptions.
