### ISSUE TITLE
Allow to use proxies (HTTP(s) & socks)

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#301]
This could be useful for those having a self-hosted instance. The idea is about adding an option to specify a proxy server (e.g. tor socks proxy), which can be used when a server are going to make a request to YouTube to fetch the data.

**Comment by Perflyst** [comment]
Maybe it is also possible to proxy the youtube media through the server itself so that the users ip address is hidden to google. If this will be done, maybe also add the option to enable/disable this feature, because some hosters have traffic limit on their servers.

**Comment by Nutomic** [comment]
I honestly thought this is what invidious does. I was a bit surprised that it still connects me directly to youtube. This should definitely be possible, at least with self-hosting.

**Comment by omarroth** [comment]
To be clear, the instance itself proxies requests, and then uses a proxy in another region as necessary to circumvent geo-restrictions (see #92). See my comment [here](https://github.com/omarroth/invidious/issues/453#issuecomment-477574597) for some clarification on what Invidious does.

There appears to be a [socks](https://github.com/wontruefree/socks) shard that should make this possible, I'll have to look more into it to ensure it can be used here.

**Comment by leonklingele** [comment]
Running the invidious binary with `torsocks` should proxy requests through Tor.

**Comment by rakamanja** [comment]
I wish I could have replied to this earlier but our microsoft overlords decided they don't like my ISP.

`torsocks` overwrites calls to `libc` functions. Therefore it only works if your software is using libc. I believe the crystal network library is not implemented on top if `libc`, but I haven't tested nor do I know crystal. Source on that information (second and third paragraphs): https://gitweb.torproject.org/torsocks.git/tree/README.md

If this information is correct, the best way to tunnel the requests of your local instance through tor would be to either:
1. Run it on a VM an route all the VM's traffic through tor;
2. Run invidious under a dedicated user and use iptables to redirect every package from that user through a transparent proxy. In that case you have to make sure that your system is not using your ISP's DNS servers.

**Comment by kVxQeXZbQAufBnQqA** [comment]
It seems this issue has not received much attention. I would like to explore using the [sox](https://github.com/wontruefree/sox) shard, previously called "socks". My main worry with implementing this is that Google generally does not like IP addresses of Tor exit nodes and will either completely block these addresses or result in an endless Captcha loop.

**Comment by alexw1982** [comment]
as a private self-hoster of an instance I would love to run the requests to youtube/google also via a socks proxy. Would be awesome!

**Comment by JuniorJPDJ** [comment]
Bump, it's very cool idea and would make configuring VPN to access youtube on server-side easy to do.

**Comment by pickinanameainteasy** [comment]
Is it possible to proxy requests to YouTube by connecting to tor,  then connect to privoxy?

Maybe using this container (https://hub.docker.com/r/dockage/tor-privoxy#!) And having the invidious container depend on this one

**Comment by unixfox** [comment]
Candidate libraries:

## socks
- https://github.com/636f7374/socks.cr (latest update 2022 - under construction - seems unmaintained)
- https://github.com/636f7374/herbal.cr (latest update 2021 - seems unmaintained)
- https://github.com/jkthorne/sox (latest update 2020 - seems unmaintained)

## http
- https://github.com/mamantoha/http_proxy (latest update 3 weeks ago - seems maintained)
- https://github.com/spider-gazelle/connect-proxy (latest update 2022 - seems unmaintained)
- https://github.com/636f7374/connect.cr (latest update 2022 - seems unmaintained)
- https://github.com/636f7374/carton.cr (latest update 2021 - seems unmaintained)

@SamantazFox I think in the lights of #3822, this issue should be our main priority to more easily bypass YouTube restrictions.

**Comment by syeopite** [comment]
Still a work in progress but here's HTTP proxy support through the `http_proxy` shard:

https://github.com/syeopite/invidious/tree/http-proxy

It works although InnerTube requests aren't proxied for some reason but `/videoplayback` and related endpoints are. Still, this should allow us to bypass YouTube's blockage more easily seeing as they're mostly restricting access to the streaming urls.  

To use just set at least the `host` and `port` configuration here.

```yml
##
## Configuration for using a HTTP proxy
##
## If unset, then no HTTP proxy will be used.
## 
http_proxy:
  user:
  password:
  host:
  port:
```

I haven't tested every edge case but it seems to be stable.

**Comment by unixfox** [comment]
@syeopite very good, I think that was a big missing piece in the puzzle for trying to solve the geo-restrictions: https://github.com/iv-org/invidious/issues/92

**Comment by mk-pmb** [comment]
Can we make it so it uses the `https_proxy` env var passed to the docker image?

**Comment by mooleshacat** [comment]
I am compiling to test myself now, assuming this works, it should be merged into iv-org/invidious. Great work 👍

**Comment by unixfox** [comment]
Closing as https://github.com/iv-org/invidious/pull/4270 was merged.

**Comment by johnwmail** [comment]
I still see the error message shown as below, how to use http_proxy with today (2024-11-12) source code
![image](https://github.com/user-attachments/assets/4216f940-e278-448c-b087-f9cb78919669)

And http_proxy config in docker-compose.yml
![image](https://github.com/user-attachments/assets/86073d14-34b7-42c0-985b-8911653fe4a1)

**Comment by unixfox** [comment]
@johnwmail did you try to specify the protocol? With "http://"

**Comment by mk-pmb** [comment]
Since it's a YAML parsing error, it might be about nuances not visible in a screenshot, like tabs vs. spaces. It might be useful to post your entire YAML file as a gist. Also there are YAML linters online which you could try to find and fix potential syntax errors.

**Comment by unixfox** [comment]
@johnwmail  You can discuss this on matrix: https://matrix.to/#/#invidious:matrix.org
Thank you

**Comment by johnwmail** [comment]
Yes, tried with "http://", but same result.
Attached docker-compose.yml for reference, thanks.
[docker-compose.yml.txt](https://github.com/user-attachments/files/17729873/docker-compose.yml.txt)

**Comment by unixfox** [comment]
Because I don't want to clutter this issue with YAML basic issues, I'm going to lock this issue since this bug has been solved. Please continue the discussion on matrix or IRC thank you: https://matrix.to/#/#invidious:matrix.org or https://web.libera.chat/?channel=#invidious

**Comment by unixfox** [comment]
Invidious companion support socks proxies: https://github.com/iv-org/invidious/pull/4985

**Comment by unixfox** [comment]
Socks proxies now supported in Invidious itself: https://github.com/iv-org/invidious/pull/5865
