### ISSUE TITLE
[Enhancement] Allow to watch videos from playlists with the playlist to the side of the video

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3019]
**Is your enhancement request related to a problem? Please describe.**
I want to watch a playlist in order, but there's no button to play them all one after each other. I can click each video, but they don't click back to the playlist. At the bottom of each video, there's a link to the next video, but there's no button to autoplay that one.

**Describe the solution you'd like**
A layout similar to Youtube --- have the playlist on the right side of the video

**Describe alternatives you've considered**
An option to autoplay only playlists will be also OK.

**Additional context**

**Comment by TheFrenchGhosty** [comment]
"Autoplay next video" is already a thing, along with automatically loading the next video.

**Comment by unixfox** [comment]
> "Autoplay next video" is already a thing, along with automatically loading the next video.

Can you check if that solves your issue @DUOLabs333? If so can you close the issue if it's what you wanted?

**Comment by DUOLabs333** [comment]
It exists, but it's not per video. However, looking at previous issues, it seems like playlist already autopay as a special case.
