### ISSUE TITLE
Similar Icons

### ISSUE THREAD

**Issue by DNDEBUG** [iv-org/invidious#3037]
Zlibrary icon 
![image](https://user-images.githubusercontent.com/98880063/163718548-849c91bc-1f0e-405b-a8d6-8f233dece315.png)
Invidious icon 
![image](https://user-images.githubusercontent.com/98880063/163718563-0310f4ef-e5a6-4ee6-8434-60305dcb31ce.png)

**Comment by unixfox** [comment]
And? What's the issue?

**Comment by DNDEBUG** [comment]
Me like
![image](https://user-images.githubusercontent.com/98880063/163719929-d5b8ae8b-c64e-40fc-9b9f-3a700dcd5fb0.png)
