### ISSUE TITLE
[Bug] Regression - "https://" removed from all links in description/comments

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#3040]
**Describe the bug**

Surely related to #3038

Since a recent PR (maybe https://github.com/iv-org/invidious/pull/2936), all URLs in description/comments lost their `https://` (and I'm guessing `http://`), this isn't just a display issue, they're all interpreted as `http://`

**Steps to Reproduce**

N/A

**Logs**

N/A

**Screenshots**

![bug](https://user-images.githubusercontent.com/47571719/163723136-67c90c57-a8bf-4a28-bf3d-c7e5fcc282d8.png)

**Additional context**

Example used in the screenshot: https://redirect.invidious.io/watch?v=_cMxraX_5RE

**Comment by SamantazFox** [comment]
It's not a bug. It's made to display more URL than previously. The link redirect to either `http://` or `https://` expected.

**Comment by TheFrenchGhosty** [comment]
> this isn't just a display issue, they're all interpreted as http://

I indeed was wrong, since some URLs are also interpreted as https://, my bad.
