### ISSUE TITLE
[Bug] Regression - 0:00 time-code replaced with the video URL

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#3043]
**Describe the bug**

Surely related to https://github.com/iv-org/invidious/issues/3038

Since a recent PR (maybe https://github.com/iv-org/invidious/pull/2936), all time-code of "0:00" are replaced with the URL of the video on Invidious (shown with in text under youtube.com, ie: [youtube.com](https://invidious.io)) (in both the description AND the comments)

**Steps to Reproduce**

Find any video with time-codes in the description, 0:00 will be replaced by the video URL

**Logs**

N/A

**Screenshots**

Invidious:

![invidious](https://user-images.githubusercontent.com/47571719/163836679-0782d874-820f-490c-815e-cd5ca047e0dc.png)

YouTube:

![youtube](https://user-images.githubusercontent.com/47571719/163836702-a47a5eb9-9029-4212-9142-f003a4465918.png)

**Additional context**

Example used in the screenshots: https://redirect.invidious.io/watch?v=TEygSwHWhfA

Note: there was a bug before (I'm not sure it was ever reported) that made the page reload when clicking on 0:00

**Comment by MathiusD** [comment]
Ah, maybe it's related to my PR, I'm looking at this right now

**Comment by MathiusD** [comment]
Damn I forgot to add the 'Fix #XXX' in my PR, logically it should resolve current issue
