### ISSUE TITLE
[Bug] Invidious no longer seems capable of bypassing age restrictions for content (403 Forbidden)

### ISSUE THREAD

**Issue by 154pinkchairs** [iv-org/invidious#3053]
**Describe the bug**
One of the reasons I'm using Invidious is that I don't want to share my CC or ID with Google just to watch certain videos. So far I had no problems accessing them via any Invidious instance, but now regardless of the instance I use I find myself unable to do so. Instead I am getting this message:
_The media could not be loaded, either because the server or network failed or because the format is not supported._ 
Trying to download the video fails as well, displaying a blank page.

**Steps to Reproduce**

1. Go to an age restricted video, for example [this one.](https://invidio.xamh.de/watch?v=SF6P_Hs5kjY)
2. Error message is displayed at the top of the video. Below it an X symbol.
3. Repeatedly clicking the video, refreshing the page, switching the instances, trying on a different browser or trying to download seem not to change anything
4. When the same video is opened on YouTube, user is prompted to sign in to watch age restricted content.

**Logs**
`GET
	https://rr2---sn-5oxmp55u-8pxe.googlevideo.com/videoplayback?expire=1650766688&ei=AF9kYuPIF8-j8gPPyYv4Ag&ip=45.83.107.127&id=o-AMmRdn4S3NHa_2yJSKwRRl732R7mYO1DnLX-VMX1cjTE&itag=18&source=youtube&requiressl=yes&mh=Ky&mm=31,29&mn=sn-5oxmp55u-8pxe,sn-4g5lzney&ms=au,rdu&mv=m&mvi=2&pl=23&initcwndbps=226250&vprv=1&mime=video/mp4&ns=0IO8A-YrzkaaevrZPOlb4WAG&gir=yes&clen=13891415&ratebypass=yes&dur=162.075&lmt=1393832437719874&mt=1650744784&fvip=3&fexp=24001373,24007246&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER&n=V8GFCLhld_7XTyuhI6J7X&sparams=expire,ei,ip,id,itag,source,requiressl,vprv,mime,ns,gir,clen,ratebypass,dur,lmt&lsparams=mh,mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AG3C_xAwRQIgCvMG_dfV1Dg0ffJG2jfF-rx9SNw4LUV0GrGhAfNlygsCIQDQw5AcgVmDXsmx-FuPE5JW3MQpoMVPnPGS76IYkfk-7A==&sig=33==A1cU-Zsl3fIGjnc=TvQBMLyJiDTPka3wV5vOd2uASx2BiA5P86X2P9p3DZN-tfQ37qq9thT2SaalOerxe6ZVRFr4PAhIQRw8J8&host=rr2---sn-5oxmp55u-8pxe.googlevideo.com
Status
403 Forbidden

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
[video.js:84:49](https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f)
    LogByTypeFactory https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f:84
    error https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f:272
    error https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f:27355
    handleTechError_ https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f:25525
    dispatcher https://invidio.xamh.de/videojs/video.js/video.js?v=1e30f36f:1915
HTTP load failed with status 403. Load of media resource https://invidio.xamh.de/latest_version?id=SF6P_Hs5kjY&itag=18 failed. watch
An error occurred in the player, reloading...
`

**Additional context**

 - Browser: LibreWolf 99.0.1 (also tried on Brave Browser 100.1.37.116)
 - OS: Linux 5.17.1-3-MANJARO x86_64

**Comment by unixfox** [comment]
Please keep all the age-restricted issues here: https://github.com/iv-org/invidious/issues/2189
