### ISSUE TITLE
[Bug] Specific video not playing

### ISSUE THREAD

**Issue by Flavori** [iv-org/invidious#3055]
**Describe the bug**
This very specific video: https://invidious.snopyta.org/watch?v=F0CUI38JlOI cannot load and will always fail with "The media could not be loaded, either because the server or network failed or because the format is not supported."

I've tried:
- Switching instances (I tried on yewtu.be, snopyta.org, y.com.sb, invidious.mutahar.rocks, invidious.weblibre.org, vid.puffyan.us, invidious.kavin.rocks)
- Changing settings (setting quality to DASH, activating video proxy)
- Downloading the video from many instances (First attempt at downloading downloads 211kb, waits a bit, and fails; retrying fetched the first 800 or so kb's and then marks the download as complete)
- Changing browser (Tried on Firefox, Chromium, and Tor)
- Changing OS (Ubuntu 20.04, Android 4.4.4 (with Firefox))

I tried a few other videos, they all work well.

**Steps to Reproduce**
Open [the video](https://invidious.snopyta.org/watch?v=F0CUI38JlOI) in any instance.

**Comment by Flavori** [comment]
Additional info: I managed download the video using `yt-dlp` from Ubuntu 20.04's package manager (without difficulty or any particular setting).

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/3025
