### ISSUE TITLE
[bug] Video API returns empty `formats`/`adaptiveFormats` for livestreams

### ISSUE THREAD

**Issue by litetex** [iv-org/invidious#3057]
**Is your enhancement request related to a problem? Please describe.**
I'm currently implementing Invidious support into NewPipe (https://github.com/TeamNewPipe/NewPipe/pull/8220) and noticed that no livestreams are playable because ``formats`` and ``adaptiveFormats`` return no stream.

**Describe the solution you'd like**
Extract and return the streams inside  ``formats`` and ``adaptiveFormats``.

**Describe alternatives you've considered**
Currently you have to play livestreams using the NewPipe-native YT extraction.

**Additional context**

N/A

**Comment by SamantazFox** [comment]
That's not supposed to happen xD

**Comment by unixfox** [comment]
Invidious use HLS for livestreams, so you have to use the hlsUrl.

**Comment by SamantazFox** [comment]
Haha, found the culprit:
https://github.com/iv-org/invidious/blob/master/src/invidious/videos.cr#L634-L639

**Comment by SamantazFox** [comment]
@litetex I've made a quick fix, available on our test instance: https://test.invidious.io/api/v1/videos/oXQoDlOpr_M

I've also added a few other things, like audio properties (as \@TiA4f8R asked on Matrix), color infos and support for MP4 Timed Text tracks (`text/mp4`) that are available on livestreams.

**Comment by litetex** [comment]
@SamantazFox 
Looks good now:
<img src="https://user-images.githubusercontent.com/40789489/165359920-f6dd1420-7468-4b3c-94d4-30b56c96e13c.png" height=300 />

Thank you for the quick fix.

However I found a few other problems on the test instance:
* Livestreams have no views when searching for them and the date looks incorrect:
   <img src="https://user-images.githubusercontent.com/40789489/165358410-8682ae8a-ce97-48e0-a7a7-4b829721c878.png" height=300 />
* and the comments can't be extracted:
https://test.invidious.io/api/v1/comments/K-ktrninq7A returns ``{"error":"Could not fetch comments"}``
```org.schabi.newpipe.extractor.exceptions.ExtractionException: Could not get page https://test.invidious.io/api/v1/comments/461dBTJmpd8 [code=500,message=]```

I guess I should create new issues for these problems or?

**Comment by SamantazFox** [comment]
> @SamantazFox Looks good now
> Thank you for the quick fix.

Nice! I'll do a PR then :)

>     * Livestreams have no views when searching for them and the date looks incorrect:

No views is because we don't parse the `runs` under `viewCountText`, and we don't have a differenciation between the different kind of videos (live, short, regular) (it's kind of a mess atm :X).

As for the date, we don't handle that either... :facepalms:

>     * and the comments can't be extracted:
>       https://test.invidious.io/api/v1/comments/K-ktrninq7A returns `{"error":"Could not fetch comments"}`
>       `org.schabi.newpipe.extractor.exceptions.ExtractionException: Could not get page https://test.invidious.io/api/v1/comments/461dBTJmpd8 [code=500,message=]`

As for that part, it's weird. I don't have any issues requesting that from the API. Maybe there was an issue on Youtube's side? The error you got points to both `onResponseReceivedEndpoints` and `continuationContents` missing from the Youtube response.

> I guess I should create new issues for these problems or?

Yep, please open a new one for the livestream start time/view count. Seem like nobody reported that before.
