### ISSUE TITLE
[Bug] Regression - "#something" shown as "/hashtag/something' (and lead to the instance homepage)

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#3062]
**Describe the bug**

Surely related to #3038 and #3043 

Since a recent PR (surely https://github.com/iv-org/invidious/pull/2936), all hashtags in the video description/comments (#something) are displayed as `/hashtag/something`.

They also now all lead to the instance homepage

**Steps to Reproduce**

N/A

**Logs**

N/A

**Screenshots**

YouTube:

![youtube](https://user-images.githubusercontent.com/47571719/165821891-124f5d03-9110-4aca-b924-f33c9bfed19d.png)

Invidious:

![invidious](https://user-images.githubusercontent.com/47571719/165821904-abddb245-b729-42ff-822a-ec85cfd6a5bf.png)

**Additional context**

N/A

Example: https://redirect.invidious.io/watch?v=6stlCkUDG_s (video was chosen because it's creative common)

**Comment by SamantazFox** [comment]
Ok, I think that we'll revert that change... It broke too many things and it's making the code much more complex for nothing.

**Comment by TheFrenchGhosty** [comment]
@SamantazFox Yeah... I mean, I like the feature, but so much stuff broke with it.
