### ISSUE TITLE
[Feature request] Support Invidious on Cloudron 

### ISSUE THREAD

**Issue by yeehi** [iv-org/invidious#3071]
**Is your feature request related to a problem? Please describe.**
For many people, deploying invidious is too complex. This means, among other things, that there are fewer instances of invidious and the burden these few instances carry is great. 

**Describe the solution you'd like**
One click deployment of an Invidious instance would be possible on Cloudron.

**Describe alternatives you've considered**
People might use Piped instead:
https://github.com/TeamPiped/Piped
or possibly PeerTube:
https://joinpeertube.org/

**Additional context**

The bulk of the work necessary to make this happen is creating an Invidious Docker image. 

You are invited to participate in the discussion on the Cloudron forum here:  

https://forum.cloudron.io/topic/2674/invidious-an-alternative-front-end-to-youtube?_=1651395800020

**Comment by unixfox** [comment]
We already have a docker image for invidious: https://docs.invidious.io/installation/#docker

**Comment by yeehi** [comment]
@unixfox, that is great news, but there is still quite a large amount of technical know-how necessary for an ordinary person to make a Docker image provide a service that is available on the World Wide Web. 

If somebody is skilled with packaging, please make Invidious even easier to install by completing the necessary steps, which are explained here:

https://forum.cloudron.io/topic/2843/read-first-before-starting-to-package-an-app

You can see how easy it is to deploy an application with a quick look at the Cloudron demo here (username: cloudron password: cloudron):
https://www.cloudron.io/

**Comment by unixfox** [comment]
We unfortunately don't have enough free time in the team for doing that.

But you can try to package invidious for cloudron and we can help you if are running into some issues.
