### ISSUE TITLE
[Feature request] Add Playlists Link to Feed Menu

### ISSUE THREAD

**Issue by arjpar** [iv-org/invidious#3078]
**Is your feature request related to a problem? Please describe.**

When a end user of Invidious wants to view their created playlists, they have to go to the preferences page scroll down and click "View all playlists". If a user has a lot of playlists and/or frequently accesses them it would be helpful to provide a quicker method to access playlists.

**Describe the solution you'd like**
As discussed on IRC/Element, I believe a satisfactory solution would be to add a "Playlists" link to the feed menu. This "Playlists" link would point to `/feed/playlists`.

**Describe alternatives you've considered**
One alternative could be to just keep the playlist page open in a separate tab, but this may not be desirable for some.

The only question is whether to keep or remove the "View all playlists" link in the preferences page if this feature request is implemented.

**Additional context**
![image](https://user-images.githubusercontent.com/41452613/166191979-31d9cbb7-0e7b-4bff-a9da-b0e70fdee878.png)
As discussed in the solution section, a "Playlists" link would be added next to the "Trending" link in the feed menu. I think the solution I proposed will also be relatively trivial to implement.

If this is a "good first issue" for newcomers, I'm willing to submit a PR.

**Comment by SamantazFox** [comment]
Closing, as the feature already exists. Sorry for making you open an issue :/
