### ISSUE TITLE
[Bug] API ``/api/v1/search`` returns incorrect data for livestreams

### ISSUE THREAD

**Issue by litetex** [iv-org/invidious#3086]
**Describe the bug**
From https://github.com/iv-org/invidious/issues/3057#issuecomment-1110078281:
> * Livestreams have no views when searching for them and the date looks incorrect:
>   <img src="https://user-images.githubusercontent.com/40789489/165358410-8682ae8a-ce97-48e0-a7a7-4b829721c878.png" height=300 />

**Steps to Reproduce**
1. Search for live streams via the API, e.g. https://test.invidious.io/api/v1/search?q=live
2. Notice that livestreams
   * have a ``published``-field that is equals to the current time, which is incorrect
   * have a ``viewCount`` of ``0`` which is also incorrect

Example:
Result of the API:
https://test.invidious.io/api/v1/search?q=live
```
[
    {
        "type": "video",
        "title": "Russia-Ukraine Conflict Live News Updates: G7 to hold virtual meet with President Zelensky | WION",
        "videoId": "yjJ3Ygc0u2Q",
        "author": "WION",
        "authorId": "UC_gUM8rL-Lrg6O3adPW9K1g",
        "authorUrl": "/channel/UC_gUM8rL-Lrg6O3adPW9K1g",
        "videoThumbnails": [
            {
                "quality": "maxres",
                "url": "https://test.invidious.io/vi/yjJ3Ygc0u2Q/maxres.jpg",
                "width": 1280,
                "height": 720
            },
            ...
        ],
        "description": "",
        "descriptionHtml": "",
        "viewCount": 0,
        "published": 1651925674,
        "publishedText": "vor 0 Sekunden",
        "lengthSeconds": 0,
        "liveNow": true,
        "premium": false,
        "isUpcoming": false
    },
    ...
]
```

Actual YouTube information regarding that livestream:
![grafik](https://user-images.githubusercontent.com/40789489/167254225-0f3c7fa7-36b8-4be9-9881-1e4824a88bed.png)

**Comment by iBicha** [comment]
I'm seeing `"liveNow": false`, is returned on live videos
