### ISSUE TITLE
[Bug] iOS: Playback speed does not reset to default

### ISSUE THREAD

**Issue by k-sareen** [iv-org/invidious#3104]
**Describe the bug**

Playback speed does not reset to default after changing it on iOS.

**Steps to Reproduce**

1. Open an invidious instance (such as https://invidious.snopyta.org) on an iOS device.
2. Change playback speed for any video (let's say we changed it to 2x).
3. Open another video and play it (or even refresh the current video). Its playback speed will still be 2x instead of the default.

**Additional context**

I'm using iOS 15.4.1 with Firefox 100.1 (I've also tested with Safari). Now I'm unsure if this is an iOS video player issue, iOS browser issue, or an invidious issue, so I apologize for the noise if it is not an invidious issue. I've checked if this is reproducible with my desktop browser (Firefox 100 on Fedora Linux) and it seems to work correctly, i.e. playback speed resets to default for different videos.

**Comment by SamantazFox** [comment]
Saving volume and playback speed across videos was a feature added in #2895.

**Comment by k-sareen** [comment]
Ah right. Thank you for the context! The system is a bit counterintuitive to me, so if possible is it agreeable add a config setting that controls this (with default being on as it currently is)? If not, then I'm not too fussed about it -- I can workaround it myself.

Thank you
