### ISSUE TITLE
[Bug] Global playback speed, volume settings update based on per-video changes instead of remaining as-is

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#3105]
**Describe the bug**
In the global Invidious preferences if one sets the playback speed ('Default speed') to say 1.5x and the player volume to say 50% it persists until the user adjusts either the speed/volume of any single video, whereupon the global settings become updated to the value of that single video.

IIRC this didn't used to be the behavior as of a few weeks ago (if the bug label is incorrect, apologies). Normally I have the global playback speed as 1.5x and only want 1x in rare instances. Similarly I have the global volume between 25-50% since some videos are too loud and some too soft and it provides a consistent baseline for headroom so I'm not caught by surprise volume shifts (also one can't tell what the prior volume is otherwise without playing a video first).

Since both settings now change globally after adjusting just one video's settings it means there isn't the consistent, expected speed and volume I'd manually set in the global settings.

**Steps to Reproduce**
1. Go to an instance and change the *Default speed* and *Player volume* preferences to something non-default (eg: `1.5` and `50%`, respectively).
2. Open any video and observe the global settings respected.
3. Now adjust the playback speed and volume for just that single video.
4. Open a different video and observe the settings adjusted of the prior video persist instead of respecting the previously customized global values in the preferences.

**Additional context**
Tested on both invidious.snopyta.org and invidious.kavin.rocks instances.

**Comment by k-sareen** [comment]
I think it's probably related to https://github.com/iv-org/invidious/pull/2895 as mentioned in my issue here: https://github.com/iv-org/invidious/issues/3104#issuecomment-1133956440.

**Comment by chocmake** [comment]
Just to add as an adjacent outcome of this, the playback speed for live videos is always auto set to 1x and with the current behavior any subsequent video(s) will also change to become 1x even if the video prior to viewing the livestream was set to some other speed.

**Comment by chocmake** [comment]
Just commenting re the stale the bot, since it would still be useful to have the ability to preserve a global speed setting default independent of any per-video adjustment (like other settings do), given also the way it affects subsequent videos played after a livestream, as mentioned.
