### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by MaximilianGT500** [iv-org/invidious#3114]
Hello, how can i transfer my database to my new Server?
I used to run invidious: docker-compose.

Thanks,
Max

**Comment by unixfox** [comment]
Just copy entire data of the volume postgresdata to the new server.

Just search for `docker copy volume to another host` on your favorite search engine. Or you can follow this article that I found when searching for the same keywords: https://medium.com/@bmihelac/copy-docker-container-data-volume-to-another-host-931568bda7fa
