### ISSUE TITLE
[Bug] Document is empty (XML::Error) when viewing YouTube kids comments without JavaScript

### ISSUE THREAD

**Issue by DoodlesEpic** [iv-org/invidious#3115]
**Describe the bug**
Trying to look for comments on a YouTube kids video with JavaScript disabled on your browser will give you a document is empty error if you are logged in with an account that has Reddit comments enabled, which I feel should be caught and have a proper error message such as "No comments". I've provided a cringe YouTube kids video as an example below.
This could be related to the following issue, although it appears they only have a similar error that appears on a different page:
https://github.com/iv-org/invidious/issues/1725

**Steps to Reproduce**
1. Disable JavaScript on your browser 
2. Log in to your Invidious instance of choice
3. Enable Reddit comments on the settings
4. Go to https://yewtu.be/watch?v=bV8P8GWz48c or any other YouTube kids video on a Invidious instance
5. Press "[Hi! Looks like you have JavaScript turned off. Click here to view comments, keep in mind they may take a bit longer to load.](https://yewtu.be/watch?v=bV8P8GWz48c&nojs=1)" to load the nojs version of the page
6. Error

**Logs**
```
Title: `Document is empty (XML::Error)`
Date: `2022-05-24T20:23:41Z`
Route: `/watch?v=bV8P8GWz48c&nojs=1`
Version: `2022.05.24-34caf95 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
Document is empty (XML::Error)
  from /usr/lib/crystal/core/xml.cr:99:21 in 'fill_links'
  from src/invidious/routes/watch.cr:104:30 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
</p>
</details>
```

**Screenshots**
![Screenshot from 2022-05-24 17-29-22](https://user-images.githubusercontent.com/37254797/170126424-d7f7033c-4f26-43ea-914d-862c1b755ef2.png)

**Additional context**
 - Browser: Brave Browser Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
 - OS: Fedora Linux 36 (Workstation Edition)

**Comment by SamantazFox** [comment]
Hmm, that's weird, I can't reproduce, even on the instance you mentioned....

**Comment by DoodlesEpic** [comment]
Oh ok I tried again in a clean environment and it seems like this bug only happens if you are logged into the Invidious instance, is this the step that's missing?

**Comment by SamantazFox** [comment]
@DoodlesEpic I'll try that, hold on!

**Comment by DoodlesEpic** [comment]
@SamantazFox 
Well that's really weird. What browser are you using and how have you disabled JavaScript? Are there any extensions? I'm going to make some more tests to find if I can reliably identify reproduction steps

**Comment by SamantazFox** [comment]
I managed to reproduce. You need to have Reddit comments enabled.

**Comment by DoodlesEpic** [comment]
@SamantazFox 
That's exactly it! Thank you so much, gonna update the op again

**Comment by SamantazFox** [comment]
Talk about an edge case, rofl
