### ISSUE TITLE
[Bug] Player uses `/api/v1` for storyboards

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3117]
**Describe the bug**
When fetching storyboards, the player uses `/api/v1/storyboards/sb/` instead of `/sb`.

**Steps to Reproduce**
I'm not sure what causes it.

**Logs**

**Screenshots**

**Additional context**

**Comment by DUOLabs333** [comment]
After compiling a new version, do I have to update my DB somehow?

**Comment by unixfox** [comment]
> After compiling a new version, do I have to update my DB somehow?

No you dont

**Comment by DUOLabs333** [comment]
What file controls what endpoint is used? Is it done by the `invidious` binary itself, or by a file in `assets`?

**Comment by DUOLabs333** [comment]
> I don't see where this happens. Do you have a specific video Id?
> 
> ![image](https://user-images.githubusercontent.com/52980486/170304372-fbeeff2f-b46a-4db0-b9dc-666038e2c1f9.png)

Interestingly, video.js calls it from line 1382, not in the 2000 range.

**Comment by SamantazFox** [comment]
Looks like the VTT-thumbnail plug-in doesn't properly handle the case where the path doesn not contain a domain name:

![image](https://user-images.githubusercontent.com/52980486/170393444-dfc104fa-2e34-4269-984d-491d9218d54c.png)

Compared to a public instance:
![image](https://user-images.githubusercontent.com/52980486/170393253-91c37442-6f80-43ba-83f0-11362e90c3ba.png)


@DUOLabs333 do you have a domain name for your instance? If yes, have you set the `domain` config?

**Comment by DUOLabs333** [comment]
After a while, @SamantazFox and I found that you needed `domain`, `external_port` and `https_only` enabled for it to work.

**Comment by SamantazFox** [comment]
Related:
 - #1231
 - https://github.com/chrisboustead/videojs-vtt-thumbnails/issues/31

**Comment by DUOLabs333** [comment]
This is still an issue.

**Comment by syeopite** [comment]
#4040 introduces a workaround for this problem. Does it fix it for you?

Interestingly `/api/v1/storyboards/sb` isn't called for me. Rather it's just `/v1/storyboards/sb`

**Comment by DUOLabs333** [comment]
This hasn't been a problem for me I'm a while.
