### ISSUE TITLE
[Enhancement] Some strings have not been translated

### ISSUE THREAD

**Issue by AHOHNMYC** [iv-org/invidious#3120]
**Describe the bug**
Some strings have not been translated

**Steps to Reproduce**
Find all patterns like `translate(locale, "blahblah` and compare them with strings from `locales/en-US.json`:
```sh
#!/bin/bash
in_source=`rgrep -hoP "(?<=translate\(locale, \")[^\"]+" | sort | uniq`
in_translation=`grep -oP '(?<=: ")(\\\"|[^"])+' locales/en-US.json | sort | uniq`
non_translated=`diff <(echo "$in_source") <(echo "$in_translation") | grep "^<" | grep -v "^< [a-z_{}]\+" | sed 's/< //'`
echo "$non_translated"
echo -e "\nFalse positive:\n"
echo "$non_translated" | xargs -d'\n' -Istr grep "str" locales/en-US.json
```

Non translated strings are:
```
%a %B %-d %T %Y UTC
Add to playlist
Add to playlist: 
Answer
Download is disabled.
Popular enabled: 
Search for videos
The Popular feed has been disabled by the administrator.
```

**Comment by maboroshin** [comment]
For the above strings 1.5 year ago, current status. "Popular enabled:" has been implemented. "Add to playlist" is not yet available. I don't know about the others.

* %a %B %-d %T %Y UTC
* [ ] Add to playlist
* [ ] Add to playlist: 
* Answer
* Download is disabled.
* [x] Popular enabled: 
* Search for videos
* The Popular feed has been disabled by the administrator.

----

"Add to playlist" is a bit long horizontally (this button is the one without semicolon). So it would be best to change to "Add playlist".

![image](https://github.com/iv-org/invidious/assets/41102508/45ab61f2-21ea-4fb9-966c-17b917edcf11)
