### ISSUE TITLE
[Bug] Not (fully) logged in when visiting invidious instance via hyperlink

### ISSUE THREAD

**Issue by ndsvw** [iv-org/invidious#3132]
**Describe the bug**
This is a bit bizarre... I'm not fully logged in anymore when I visit invidious via clicking on a hyperlink. When I open the site via entering the domain in the URL bar, it works fine...

**Steps to Reproduce**

What works:
1. Visit an invidious instance and log in. (maybe use yewtu.be for this)
2. Close the invidious tab
3. Enter the invidous instance URL (e.g. the one of yewtu.be) in the address/URL bar of your browser and press Enter
=> You are logged in.

What does not work:
1. Visit an invidious instance and log in. (maybe use yewtu.be for this)
2. Close the invidious tab
3. Click a hyperlink to the invidious instance (e.g. https://yewtu.be)
=> You are not logged in for some reason. You can click "Login" and are logged in immediately then (without entering credentials).

**Screenshots**
When following the "What works" steps:
<img width="313" alt="Screenshot 2022-05-29 at 17 54 36" src="https://user-images.githubusercontent.com/21332313/171137766-5df968e4-2eda-45b0-af71-9358e15a0a02.png">

When following the "What does not work" steps:
<img width="283" alt="Screenshot 2022-05-31 at 11 09 43" src="https://user-images.githubusercontent.com/21332313/171137707-f2005be4-786c-4f3f-aa13-8430af4c7f7f.png">

**Additional context**
 - Browser (if applicable): Firefox on MacOs, Safari on MacOS and Firefox on Windows
 - OS (if applicable): Windows and MacOs (that's where I reproduced it)

**Comment by unixfox** [comment]
I really can't reproduce the issue:
https://user-images.githubusercontent.com/4016501/171380393-bd9d9aa7-6c35-46dd-9afa-6029b91cf128.mov

Please record the issue and post it here.

**Comment by ndsvw** [comment]
I've just recorded this in my Safari browser: A browser that I pretty much never use, and it has no extensions installed:
![repro](https://user-images.githubusercontent.com/21332313/171445870-0f07d64d-a1a9-4121-bd05-8f706bc3d3a7.gif)

**Comment by ndsvw** [comment]
And this is a gif of the "instant login" (without credentials) when visiting the site via clicking on a hyperlink:
![output4](https://user-images.githubusercontent.com/21332313/171447420-349b75b4-ecc4-414b-9d7d-7d50557d57e8.gif)

**Comment by ndsvw** [comment]
One more bizarre fact in the Safari browser:
* If you click the hyperlink normally (without holding CMD or similar), **you are not fully logged in.** (That's what I did in the 2 gifs)
* If you hold CMD and click the hyperlink, it opens a new tab, and **you are fully logged in.**

**Comment by unixfox** [comment]
And does this bug also occurs on Firefox and chrome?

**Comment by ndsvw** [comment]
I've just found a way to overcome this problem locally.
This is maybe not the fix for this issue, but...

When I manipulate the SID cookie and remove the "." in front of the domain attribute of the cookie (".yewtu.be" => "yewtu.be"), it works.

> but not on my account where I logged in like more than 6 months ago.

@unixfox Is this possibly the difference? No dot?

---

It looks like there was an [RFC 2109](https://www.rfc-editor.org/rfc/rfc2109.txt) about "State management" that was obsoleted by [RFC 2965](https://www.rfc-editor.org/info/rfc2965) which was again obsoleted by [RFC 6265](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.2.3).

From the oldest one (1997):

> The Domain attribute specifies the domain for which the
      cookie is valid.  An explicitly specified domain must always start
      with a dot.

From the latest one (2011):

> The Domain attribute specifies those hosts to which the cookie will
   be sent.  For example, if the value of the Domain attribute is
   "example.com", the user agent will include the cookie in the Cookie
   header when making HTTP requests to example.com, www.example.com, and
   www.corp.example.com.  (Note that a leading %x2E ("."), if present,
   is ignored even though that character is not permitted, but a
   trailing %x2E ("."), if present, will cause the user agent to ignore
   the attribute.)  If the server omits the Domain attribute, the user
   agent will return the cookie only to the origin server.

That sounds like removing the "." won't cause problems for me locally...

But to be honest: Most of the websites I've just visited prepend a dot in front of the domain attribute.

**Comment by unixfox** [comment]
> @unixfox Is this possibly the difference? No dot?

I do I've a dot too in my cookies on my old session so I don't think it's the issue: 
![image](https://user-images.githubusercontent.com/4016501/171996086-1d8638af-1f2f-410f-a265-63c3c43210bd.png)

**Comment by xofe** [comment]
I've noticed this too recently, preferences stored in cookies being ignored when coming from another site. 

Looks like things were changed in #2895 to set the [cookie samesite setting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) to 'strict' which would cause exactly this (cookies not being sent except on requests originating from the site itself). I can't test it myself right now, but using 'lax' instead would probably fix this.

**Comment by DUOLabs333** [comment]
For me, this still happens --- if I click a link there, I'm not signed in, but if I enter the address myself into the address bar, I'm signed in.

**Comment by SamantazFox** [comment]
@DUOLabs333 Can you please provide some more details? (Browser, instance, etc...)

**Comment by DUOLabs333** [comment]
This is on Firefox 89 on my own instance (2022.08.25-a7d9df5 @ master)

**Comment by ndsvw** [comment]
How old are your cookies? Have you tried deleting the cookies and logging in again?

I've experienced the problem of this issue once again a few hours ago (with the latest version 2022.09.19-00cb670 on yewtu.be), but as soon as I deleted the months old cookies, it worked again.
