### ISSUE TITLE
[Bug] Audio Append Failed For Segment Error

### ISSUE THREAD

**Issue by Abystus** [iv-org/invidious#3139]
**Describe the bug**

When loading certain videos, the audio will fail to append and the video will fail to play. This cannot be resolved by refreshing the page.

**Errors Displayed**

`audio append of 60231b failed for segment #0 in playlist 0-placeholder-uri-AUDIO-audio-main`
`audio append of 60390b failed for segment #0 in playlist 0-placeholder-uri-AUDIO-audio-main`

**Steps to Reproduce 1**

1. Log in to the site
2. Search for "MK4 Glitches"
3. Click on video titled "MK4/Gold Readout Glitch"
4. Observe error as video attempts to load

**Steps to Reproduce 2**

1. Log in to the site
2. Search for "Mortal Kombat 4 Missing Cheats"
3. Click on video titled "Mortal Kombat 4 Missing Cheats"
4. Observe error as video attempts to load

**Screenshots**

![image](https://user-images.githubusercontent.com/1529049/172062862-c1c12024-6440-4e3a-a52e-bc23443be0e6.png)
![image](https://user-images.githubusercontent.com/1529049/172063089-b3a1df4a-c38a-4b9e-ba7a-59bfd330bed7.png)

**Comment by Zero3K** [comment]
It also happens with the video ID of CrlLxq_ISYg.

**Comment by ydididodat** [comment]
Happened for me too with a few videos from the same channel, but not with all the videos from that channel. I don't want to say the name of the channel though for privacy reasons. But I don't think it's necessary because others here have already shared videos that have this error.
