### ISSUE TITLE
[Bug] Regression - Local storage key for dark mode changed

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#3146]
**Describe the bug**

Not technically a massive issue, but one of the recent PR (I'm guessing #3084 - @AHOHNMYC ) changed the value for the key used by the dark theme local storage entry. It went from `dark_mode: true"` to `dark_mode:"%22dark%22"`

**Steps to Reproduce**

Click the theme switcher button at the top right, and look at the key's value in the browser local storage.

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by AHOHNMYC** [comment]
Oh, yes. Format has been changed. I hope, this is not critical.

But what about `%22` it is not a bug, it is a feature :) `helpers.storage` allows to save JS objects and restore them as is. In this case dark is a string, so it wrapped with `"` which after `encodeURIComponent` turns into `%22`.

This looks like mess in case of just one string, but when you'll start storing arrays or other complex objects, you'll see all benefits of this approach.

https://github.com/iv-org/invidious/blob/b5c54b4e410709d93423ca019aaf30579cb53ace/assets/js/_helpers.js#L212

**Comment by AHOHNMYC** [comment]
@AHOHNMYC yeeah, I would have thought so by myself if I hadn't been the cause of this behavior :D

Yes, this issue may be closed.

Code doesn't rely on previous stored value and just overrides it with value got from HTML, so nothing is broken (I hope :)

https://github.com/iv-org/invidious/blob/b5c54b4e410709d93423ca019aaf30579cb53ace/assets/js/themes.js#L39-L43

**Comment by jodizzle** [comment]
Not sure if you would consider this a regression exactly, but this change did break my default preferences.  I had `dark_mode` set to `true` in `default_user_preferences` so that the dark theme would always be activated.  That stopped working after my latest upgrade.

Changing `dark_mode` to be `"dark"` by default works, though, so easy enough to fix.

**Comment by TheFrenchGhosty** [comment]
@jodizzle So that's the problem, I was wondering why it was acting weird on my instance!

@AHOHNMYC @SamantazFox how should we handle that? Should we just edit the example config? Maybe rename `dark_mode` to `theme`?

**Comment by SamantazFox** [comment]
@TheFrenchGhosty renaming `dark_mode` to `theme` is planned. I have many PRs on standby that should work on the user preferences (like #2377 and #3020), but I haven't been able to work on them recently (I'm trying to consolidate our tests and make invidious more resistant to breakages).
