### ISSUE TITLE
[Bug] Searching by channel, when an additional search string present, then clicking Next page returns non-channel results

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#3148]
**Describe the bug**
Using the `channel:` search parameter in the URL, along with a search term, if one clicks 'Next page' at the bottom of results it will strip the `channel` parameter from the results.

**Steps to Reproduce**
1. Use eg: `https://invidious.snopyta.org/search?q=channel:<channelID>%20<search term>`, such as `https://invidious.snopyta.org/search?q=channel:UC2DjFE7Xf11URZqWBigcVOQ%20multimeter`
2. Go to bottom of page and click 'Next page'
3. Observe the results for the string query no longer limited to the channel.

Compare the following URL for what the correct next page URL should be:
`https://invidious.snopyta.org/search?q=channel:UC2DjFE7Xf11URZqWBigcVOQ multimeter&page=2`
Instead it's:
`https://invidious.snopyta.org/search?q=multimeter&&page=2`

**Additional context**
Tried on invidious.snopyta.org instance.

(Also sorry about the numerous title changes, I accidentally originally submitted the issue without any text and tried to rapidly add the rest)

**Comment by SamantazFox** [comment]
Ah, thanks for reporting this!

**Comment by chocmake** [comment]
Can confirm with kavin.rocks instance this fix resolves this issue. Thanks!
