### ISSUE TITLE
My instance is slow and I'm not sure why

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [iv-org/invidious#3149]
I host http://invidious.esmailelbob.xyz/ and I noticed when I open multiple tabs invidious start to lag in videos. I checked my nginx and server block for invidious but still same problem and I'm unsure why. Server block is same across all sites but for some reason only invidious hang and lag

**Comment by unixfox** [comment]
Do you have an auto restart of invidious? If so how often?

Do you run multiple processes of invidious and loadbalanced behind a reverse proxy?

**Comment by EsmailELBoBDev2** [comment]
Damn, I understand nothing.

No I do not restart invidious unless docker itself is down, I do not run multiple processes and I do not use loadbalancer

**Comment by unixfox** [comment]
You should restart invidious every hour. It's a requirement for public instances.

**Comment by EsmailELBoBDev2** [comment]
oh, restart like docker-composer restart or restart like docker-compose down && docker-compose up -d ?

**Comment by unixfox** [comment]
Please restart your instance every hour it's literally recommended here: https://docs.invidious.io/installation/#post-install-configuration. This will greatly help in the slowdowns.
Use whatever method you like.

**Comment by EsmailELBoBDev2** [comment]
Thanks, Also known fact, most people (incl me) do not read docs unless they are stuck in something...

**Comment by EsmailELBoBDev2** [comment]
Nope, restarted and still lags :)

**Comment by suymur** [comment]
I needed to add the following to my docker-compose.yaml:
```
    dns: 
      - 1.1.1.1 
```

i just put that under:
```
    depends_on:
      - invidious-db
```

**Comment by EsmailELBoBDev2** [comment]
I'm not good at docker so it's like this?:
```
    depends_on:
      - invidious-db
    dns: 
      - 1.1.1.1 
```

**Comment by EsmailELBoBDev2** [comment]
Okay I tried to stress test it and it works but I will use it casually and see

**Comment by EsmailELBoBDev2** [comment]
Nope, still lags

**Comment by EsmailELBoBDev2** [comment]
Okay I noticed something 

my instance is faster on firefox, on firefox it does not lag as much as on chromium

**Comment by EsmailELBoBDev2** [comment]
@TheFrenchGhosty why did you close it? it still lags??

**Comment by TheFrenchGhosty** [comment]
@EsmailELBoBDev2 Because it's obviously an issue on your end.

**Comment by EsmailELBoBDev2** [comment]
@TheFrenchGhosty obv I know that and I asked you on mastodon, said ask here??

**Comment by TheFrenchGhosty** [comment]
@EsmailELBoBDev2 

>my instance is faster on firefox, on firefox it does not lag as much as on chromium

This is an issue on your client side. Also, as @unixfox said, setup autorestart (and basically follow the installation document correctly).

**Comment by EsmailELBoBDev2** [comment]
> setup autorestart

already done this
___
but tested on both mobile and PC ?
