### ISSUE TITLE
[Bug] Youtube comments don't show up anymore

### ISSUE THREAD

**Issue by spitemim** [iv-org/invidious#3150]
**Describe the bug**

On every instance I've tried (https://yewtu.be/, https://iteroni.com/, https://invidious.snopyta.org/), the comment section contains no comments, and the heading reads "View 0 comments". This started happening to me just minutes ago.

**Steps to Reproduce**

1. Click on any video
2. Scroll down to the comments section
3. There are no comments

**Additional context**

I'm running Firefox on Linux Mint 20, but I don't think that's the issue. I think Youtube introduced a change that broke whatever method Invidious uses to scrape comments.

**Comment by spitemim** [comment]
It seems to be working again now, at least on https://iteroni.com/. Closing this now.

**Comment by unixfox** [comment]
That was a temporary issue on youtube side: https://nitter.pussthecat.org/TeamYouTube/status/1536780222720253952#m
