### ISSUE TITLE
[Bug] Missing hash key: "selected" (KeyError)

### ISSUE THREAD

**Issue by markozajc** [iv-org/invidious#3152]
**Describe the bug**

Opening a `* - Topic` channel page results in an error. This seems to occur with any topic channel page (below error log is generated for Led Zeppelin's).

**Steps to Reproduce**
1. Open a music video generated on a topic page of an artist, such as `?v=X791IzOwt3Q`
2. Click on the topic channel link above the 'Subscribe' button
3. See error

NB: channel links on the search page seem to lead to the ordinary and not the topic channel, so they will not produce this error.

**Logs**
Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-06-16T20:07:56Z`
Route: `/channel/UCYtap7ujIPaxTS2iCDoMi3g`
Version: `2022.06.09-b5c54b4e @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from /opt/invidious/invidious in '??'
  from ???
```
</p>
</details>

**Additional context**
 - OS: Debian 11/bullseye (on the machine running Invidious)
 ```
$ crystal -v
Crystal 1.4.1 [b7377c041] (2022-04-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by SamantazFox** [comment]
Heck... This is probably due to geo restrictions.

Works on those instances:
 * https://invidious.snopyta.org/channel/UCYtap7ujIPaxTS2iCDoMi3g
 * https://invidious.esmailelbob.xyz/channel/UCYtap7ujIPaxTS2iCDoMi3g
 * https://invidious.osi.kr/channel/UCYtap7ujIPaxTS2iCDoMi3g
 * https://vid.puffyan.us/channel/UCYtap7ujIPaxTS2iCDoMi3g

Doesn't work on those:
 * https://invidious.kavin.rocks/channel/UCYtap7ujIPaxTS2iCDoMi3g
 * https://invidious.lunar.icu/channel/UCYtap7ujIPaxTS2iCDoMi3g

**Comment by markozajc** [comment]
Huh, it also seems to work on my instance now. It probably is A/B testing then.

**Comment by TheFrenchGhosty** [comment]
More information in #3154
