### ISSUE TITLE
Livestream premiere page for (some?) videos doesn't display any info besides countdown

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#3155]
**Describe the bug**
I noticed when visiting [this video](https://www.youtube.com/watch?v=0L-VW-7dJds)'s page on Invidious it only displays the text 'This live event will begin in \<n\> hours'. No video title/thumbnail/other text is present. It also shows the same thing on embedded Invidious version (`/embed/<videoid>`).

Thing is, I don't recall this issue on non-livestream premiere videos in the past (which would show the full video page IIRC). Also can't find another yet-to-premiere livestream video to compare if the same thing happens for all such videos, which is why I tentatively used 'some?' in the issue title.

**Steps to Reproduce**
1. Visit [this video](https://www.youtube.com/watch?v=0L-VW-7dJds) on an Invidious instance (tested on [Snopyta.org](https://invidious.snopyta.org/watch?v=0L-VW-7dJds) and [Kavin.rocks](https://invidious.kavin.rocks/watch?v=0L-VW-7dJds) instances).
2. Observe the missing video information.

**Screenshots**
Youtube:
![Screenshots - Youtube regular - Crop](https://user-images.githubusercontent.com/34178938/174654158-1ef8edb1-b689-4390-884c-ec7297f91246.png)

Invidious (the `/embed/` version also displays this instead of its normal embed UI):
![Screenshots - Invidious - Crop](https://user-images.githubusercontent.com/34178938/174654187-ce40a1bd-ac64-4c11-8b49-b1dbdfed65e1.png)

**Comment by unixfox** [comment]
It's not a bug, youtube is returning us a reason that the video can't be played, so we show the reason to the user. Simple.

What you are asking here is to implement a case where if it's a pre-livestream video then we show more than just the reason why the user can't play the video.

**Comment by chocmake** [comment]
For some context I should probably also mention that I wasn't actually aware what the video was until visiting the youtube.com version. Someone had embedded it with no accompanying comment and since I use the Privacy Redirect addon all my Youtube embeds are automatically made into Invidious embeds.

Neither from the embed (which for this video shows the regular website UI as seen in the screenshot instead of the normal embed UI) nor the page could I tell what the video was since all I saw was what is pictured above.

I'm guessing from the comment above the expectation is a user has clicked it via an Invidious search result or channel and would already know what the video title/context was.
