### ISSUE TITLE
OAuth/OpenID accounts

### ISSUE THREAD

**Issue by choelzl** [iv-org/invidious#3159]
Add support for external sourced accounts via OAuth/OpenID (or LDAP or SAML could also be considered but seem less practical to implement).

**Comment by unixfox** [comment]
Already requested in https://github.com/iv-org/invidious/issues/705

**Comment by choelzl** [comment]
@unixfox OAuth/OpenID is not the same as LDAP but #705 can be adjusted to also mention OAuth support (since it doesn't currently). OAuth might be easier/faster to implement thanks to google-auth being already supported. I believe the code base is already partly present and just requires adjustment to support other backends.
