### ISSUE TITLE
[Bug] Unexpected char 'ش' at line 1, column 1 (JSON::ParseException)

### ISSUE THREAD

**Issue by HadiDkb** [iv-org/invidious#3166]
Title: `Unexpected char 'ش' at line 1, column 1 (JSON::ParseException)` Date: `2022-06-28T16:11:47Z` Route: `/data_control?referer=%2Ffeed%2Fsubscriptions` Version: `2022.06.28-3044f0b @ master` <details> <summary>Backtrace</summary> <p> ``` Unexpected char 'ش' at line 1, column 1 (JSON::ParseException) from /usr/lib/crystal/core/json/lexer.cr:211 in 'raise' from /usr/lib/crystal/core/json/lexer.cr:330 in 'unexpected_char' from /usr/lib/crystal/core/json/lexer.cr:326 in 'unexpected_char' from /usr/lib/crystal/core/json/lexer/string_based.cr:63:8 in 'next_token' from /usr/lib/crystal/core/json/parser.cr:13:12 in 'update_data_control' from lib/kemal/src/kemal/route.cr:12:9 in '->' from lib/kemal/src/kemal/config.cr:92:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from src/ext/kemal_static_file_handler.cr:112:11 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process' from /usr/lib/crystal/core/http/server.cr:500:5 in '->' from /usr/lib/crystal/core/fiber.cr:146:11 in 'run' from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??' ``` </p> </details>

**Comment by SamantazFox** [comment]
Did you select "CSV" to import your subscription file?

**Comment by SamantazFox** [comment]
Closing due to lack of replies.
