### ISSUE TITLE
[Bug] PostgreSQL is stuck on "ImagePullBackOff" when installing via helm chart

### ISSUE THREAD

**Issue by atropos112** [iv-org/invidious#3167]
**Describe the bug**
Trying to run invidious on Kubernetes as instructed and fail by getting a permanent 
`ImagePullBackOff` on `invidious-postgresql-0` pod (and `Init:0/1` on the `invidious-invidious` pod).

logs on the postgres pod give the following

```
Error from server (BadRequest): container "postgresql" in pod "invidious-postgresql-0" is waiting to start: image can't be pulled
```

**Steps to Reproduce**
Run the commands as instructed (helm dep build, kubectl... , helm install invidious ./)

**Logs**
```
Error from server (BadRequest): container "postgresql" in pod "invidious-postgresql-0" is waiting to start: image can't be pulled
```

**Comment by unixfox** [comment]
Please check in the events of the pod what's going on that the image can't be pulled. The chart is working fine for me, closing the issue.

**Comment by atropos112** [comment]
Have had another look at it, now that I have been playing with this stuff for more couple months rather than couple days. The reason it wasn't working for me was because 
```
  image:
    registry: quay.io
```
I had no authorization, hence could not pull... I am guessing @unixfox has the auth so didn't see the issue being there. Sorry for necro-bumping, felt it might be useful for the next guy.

**Comment by unixfox** [comment]
Idk what you did but the image is publicly available: https://quay.io/invidious/invidious
https://github.com/iv-org/invidious/blob/master/kubernetes/values.yaml#L4
