### ISSUE TITLE
Add ability to disable watch history in account preferences

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#317]
At the moment you cannot disable your watch history. This is possible on YouTube but not on Invidious yet.

**Comment by trymeouteh** [comment]
I would like this too. I use my browser watch history as my watch history and would like this so less data is stored on invidious servers. This will make a good privacy option for many people.

**Comment by tdeeb** [comment]
Any updates on this? I'd love this feature as well!

**Comment by 4yx** [comment]
this would be great to have, it's annoying having to clear it all the time

**Comment by unixfox** [comment]
In my opinion, watch history should be disabled by default and offering the ability for people to enable it if needed in the preferences.

**Comment by unixfox** [comment]
[0001-Make-the-history-recording-optional.zip](https://github.com/iv-org/invidious/files/8084212/0001-Make-the-history-recording-optional.zip)

Patch with the feature by "Le Jester" on matrix.
