### ISSUE TITLE
[Bug] DASH does not work for old videos

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3177]
**Describe the bug**

**Steps to Reproduce**
1. Select `DASH` in settings
2. Go to https://redirect.invidious.io/watch?v=IImlNwI5rEA
3. See how it says "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/49244768/176942330-83911e4d-ab55-454d-b681-ebffd0e92132.png)

**Additional context**

Selecting HD720 makes it work.

**Comment by DUOLabs333** [comment]
Seems to be a duplicate of #3136.

**Comment by unixfox** [comment]
> Seems to be a duplicate of #3136.

No DASH exist but the stream data given by youtube seems corrupted for some unknown reason.

**Comment by SamantazFox** [comment]
that's likely due to their content ID or whatever "protection"...

**Comment by DUOLabs333** [comment]
The video in question no longer has a 720p option, and works now with the other quality options.
