### ISSUE TITLE
[Bug] invidious.snopyta.org's instances video doesn't load completly

### ISSUE THREAD

**Issue by agnusiesu** [iv-org/invidious#3185]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by agnusiesu** [comment]
i saw this error only on [invidious.snopyta.org](https://invidious.snopyta.org/) instances

**Comment by unixfox** [comment]
We have no control over the invidious.snopyta.org instance, please reach out to the maintainer.

@Perflyst pinging

**Comment by Perflyst** [comment]
Works for me, maybe was a temporary issue. I restarted invidious just in case anyways
