### ISSUE TITLE
[Bug] Missing hash key when trying to view channel playlists

### ISSUE THREAD

**Issue by Alexey104** [iv-org/invidious#3188]
**Steps:**
Open any channel and go to `Playlists`.

**Expected results:**
Channel playlists should be shown.

**Actual results:**
<details>
  <summary>The following message shows up on any instance:</summary>
<br/>
It looks like you found a bug in Invidious!

Before reporting a bug, make sure that you have:

tried to [refresh the page](https://invidious.snopyta.org/channel/UCMlGfpWw-RUdWX_JbLCukXg/playlists)
tried to [use another instance](https://redirect.invidious.io/channel/UCMlGfpWw-RUdWX_JbLCukXg/playlists)
read the [Frequently Asked Questions (FAQ)](https://github.com/iv-org/documentation/blob/master/docs/faq.md)
searched for [existing issues on GitHub](https://github.com/iv-org/invidious/issues)

If none of the above helped, please [open a new issue on GitHub](https://github.com/iv-org/invidious/issues/new?labels=bug&template=bug_report.md&title=%5BBug%5D+Missing+hash+key%3A+%22selected%22+%28KeyError%29) (preferably in English) and include the following text in your message (do NOT translate that text):

Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-07-05T12:46:28Z`
Route: `/channel/UCMlGfpWw-RUdWX_JbLCukXg/playlists`
Version: `2022.06.13-6c73614a @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/share/crystal/src/hash.cr:1034:9 in '[]'
  from src/invidious/yt_backend/extractors_utils.cr:87:70 in 'process'
  from src/invidious/yt_backend/extractors.cr:640:8 in 'extract_items'
  from src/invidious/channels/playlists.cr:33:13 in 'fetch_channel_playlists'
  from src/invidious/routes/channels.cr:59:27 in 'playlists'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>
  
    
</details>

**Comment by unixfox** [comment]
This issue has been fixed in https://github.com/iv-org/invidious/pull/3183

The instance that you are using is outdated. Please use an instance that is up-to-date on https://instances.invidious.io

**Comment by Alexey104** [comment]
Ok, thank you!
I've tried multiple instances, and they all have the same problem, but I've finally found a working one.
