### ISSUE TITLE
[Q] Why is there a 55 char limit on passwords?

### ISSUE THREAD

**Issue by txtsd** [iv-org/invidious#3191]
Passwords are/should be stored as salted (and peppered) hashes, so it doesn't make sense to limit them.

Is there perhaps another technical limitation? Or is it an arbitrary limit?

**Comment by unixfox** [comment]
The explanation: https://security.stackexchange.com/a/39851

Found in https://github.com/iv-org/invidious/blob/master/src/invidious/routes/login.cr#L351

**Comment by txtsd** [comment]
Ah a `bcrypt` idiosyncrasy.
