### ISSUE TITLE
Comments don't load [Bug]

### ISSUE THREAD

**Issue by urgellx** [iv-org/invidious#3193]
**Describe the bug**
The comments don't load at all.

1: Go on video.urgelle.fr
2: Click on any video that you might want to watch.
3: Comments don't load.

**Logs**
Invidious log : 
`2022-07-11 15:57:53 UTC [info] 206 GET /videoplayback?expire=165...`

Example  Firefox error :
 
`Uncaught ReferenceError: helpers is not defined
get_youtube_comments https://video.urgelle.fr/js/watch.js?v=2ea98632:226
    <anonymous> https://video.urgelle.fr/js/watch.js?v=2ea98632:339`

**Screenshots**
![image](https://user-images.githubusercontent.com/109094729/178305689-4573dd2e-3be2-4f85-b607-1ad840fcd6e9.png)

**Additional context**
 - Browser (if applicable): Firefox
 - OS (if applicable): Linux (Arch-based) (don't know if that matters)

**Comment by SamantazFox** [comment]
Instance is outdated. Ask the maintainer to update, or switch instance!
