### ISSUE TITLE
Add feedback to the updates to avoid confusion [Enhancement] 

### ISSUE THREAD

**Issue by urgellx** [iv-org/invidious#3194]
**Is your enhancement request related to a problem? Please describe.**
When I updated my Invidious instance, i thought multiple times that there was a problem (i reinstalled Crystal to see if that fixed it) since it gives no feedback after
checking the video dependencies.

**Describe the solution you'd like**
Please, add a description of what the update program does as the update progresses, it shows nothing even after adding the verbose option.

**Comment by unixfox** [comment]
```
checking the video dependencies.
```
Is just a message saying that it fetches the library dependencies only once and that's it. If it gets stuck then something is wrong on your internet.

No real need to add a progress bar.

**Comment by urgellx** [comment]
> ```
> checking the video dependencies.
> ```
> 
> Is just a message saying that it fetches the library dependencies only once and that's it. If it gets stuck then something is wrong on your internet.
> 
> No real need to add a progress bar.

Sorry, maybe i didn't explain it properly but i'm talking about what happens after the message "Player dependencies are satisfied" appears, it takes quite a little bit of time to execute the command on my vps (compiling i think ?). So i was wondering if it was possible to add a way to know what progress was being made, to avoid waiting without seeing what it does for 20 minutes (maybe more maybe less, just left it running and did something else).

**Comment by unixfox** [comment]
No `checking the video dependencies.` is done after launching Invidious. Once this process is done, Invidious is launched.

We don't want to add a progress bar, just wait and that's it. I'll edit the message saying that it can take a while.
