### ISSUE TITLE
[Enhancement] Alert proxy user if instance has proxy disabled

### ISSUE THREAD

**Issue by umbralOptimatum** [iv-org/invidious#3196]
I prefer watching videos via proxy, but when using an extension like LibRedirect to automatically connect to a random instance, it's not obvious whether it has proxying enabled. When trying to watch a video with local=true set (whether via cookies or URL) on an instance with proxy disabled, the player should display an appropriate error message rather than silently connecting to Youtube's servers.

**Comment by SamantazFox** [comment]
That's a good idea :D

**Comment by unixfox** [comment]
Proxy will soon be required since we want to move to DASH by default: https://github.com/iv-org/invidious/issues/4847
