### ISSUE TITLE
[Question] Using invidious icon in a Firefox add-on

### ISSUE THREAD

**Issue by aminecmi** [iv-org/invidious#3206]
Hello,

I just create a Firefox add-on to redirect every YouTube link to an Invidious instance. 

I want to publish it on the Mozzila Addons website, and I wanted to know if I could use the Invidious icon/logo inside the app, and as a logo for the add-on.

Thanks for the answer.

**Comment by TheFrenchGhosty** [comment]
@aminecmi You can use the logo when you mention Invidious (fair-use like), but do not reuse it for your software as if it was "yours".

**Comment by aminecmi** [comment]
Thanks. 

I used the svg file and did my own icon. If you would like to "review" it, it's [here](https://github.com/aminecmi/youtube-to-invidious/blob/main/icons/Frame%201.png)
