### ISSUE TITLE
[Feature request] this is not a PWA? No installable?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [iv-org/invidious#3208]
Looks like not a progressive web app, or I miss something?

**Comment by unixfox** [comment]
There is no plan to make invidious a PWA because that would need to rely a lot on javascript and we try to not do that.

But you can install invidious as a classic PWA because nowadays it's possible do it on any website. I even have "add to home screen" on chrome and firefox on android.

**Comment by vitaly-zdanevich** [comment]
Tried to add to home screen on Firefox, Android - not added :(

**Comment by vitaly-zdanevich** [comment]
Maybe with PWA in iOS we will have a full full screen.

**Comment by unixfox** [comment]
> Tried to add to home screen on Firefox, Android - not added :(

Something is probably wrong on your browser because I do see the install button on my firefox on android.

You should probably try to reset firefox if that fixes the issue.
