### ISSUE TITLE
[Enhancement] Test crystal 1.5

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#3211]
**Is your enhancement request related to a problem? Please describe.**

The new crystal 1.5 has been released.

**Describe the solution you'd like**

Test crystal 1.5.

**Describe alternatives you've considered**

**Additional context**

**Comment by SamantazFox** [comment]
I'm using it on the test instance. Works great so far, except with release mode.
I don't know what causes this, I need to investigate.

**Comment by SamantazFox** [comment]
This can be closed, because of 0c64a86ebec8844a3aadbe44265776767d810aae
