### ISSUE TITLE
[Bug] Error: error executing command: git rev-list HEAD --max-count=1 --abbrev-commit, got exit status 128

### ISSUE THREAD

**Issue by jaroslavmraz** [iv-org/invidious#3222]
Problem with auto isntall

1. Download 
`curl -s https://api.github.com/repos/tmiland/Invidious-Updater/releases/latest \
| grep "browser_download_url.*sh" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -`

2. run with advanced and without advanced cfg

Error with db

`Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
➜ Creating user kemal with password 6pwABZjJAIb0lXkzjkeJ6aTU7tuV60Yg
CREATE ROLE
➜ Creating database invidious with owner kemal
CREATE DATABASE
➜ Grant all on database invidious to user kemal
GRANT
➜ Running /home/invidious/invidious/config/sql/annotations.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/channel_videos.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/channels.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/nonces.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/playlist_videos.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/playlists.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/session_ids.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/users.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
➜ Running /home/invidious/invidious/config/sql/videos.sql
psql: error: FATAL:  Peer authentication failed for user "kemal"
✔ Finished Database section
➜ Updating config.yml with new info...`

End with error GIT

`Done checking player dependencies, now compiling Invidious...
fatal: detected dubious ownership in repository at '/home/invidious/invidious'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/invidious/invidious
fatal: detected dubious ownership in repository at '/home/invidious/invidious'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/invidious/invidious
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:68:25

 68 | CURRENT_COMMIT  = {{ "#{`git rev-list HEAD --max-count=1 --abbrev-commit`.strip}" }}
                              ^
Error: error executing command: git rev-list HEAD --max-count=1 --abbrev-commit, got exit status 128

✗ [ERROR] Build Process Failed!

 This is most likely an issue with Invidious, not this script!

➜ Report issue: https://github.com/iv-org/invidious/issues`

Tested on Clean Ubuntu 20.04LTS and 22 LTS in virtualbox.

**Comment by unixfox** [comment]
Please open an issue on the correct repository: https://github.com/tmiland/Invidious-Updater/issues
