### ISSUE TITLE
[Bug] relation "videos" does not exist (PQ::PQError)

### ISSUE THREAD

**Issue by kubo6472** [iv-org/invidious#3225]
**Describe the bug**
Invidious instance won't play any videos

**Steps to Reproduce**

**Logs**
2022-07-29 18:22:55.672 UTC [83] STATEMENT:    SELECT DISTINCT ON (ucid) *
invidious_db_1    |       FROM channel_videos
invidious_db_1    |       WHERE ucid IN (SELECT channel FROM (SELECT UNNEST(subscriptions) AS channel FROM users) AS d
invidious_db_1    |       GROUP BY channel ORDER BY COUNT(channel) DESC LIMIT 40)
invidious_db_1    |       ORDER BY ucid, published DESC
invidious_db_1    | 2022-07-29 18:47:29.116 UTC [83] ERROR:  relation "videos" does not exist at character 17
invidious_db_1    | 2022-07-29 18:47:29.116 UTC [83] STATEMENT:    SELECT * FROM videos
invidious_db_1    |       WHERE id = $1

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
Try to reset everything from invidious and do all the steps from https://docs.invidious.io/installation/#docker-compose-method-production

**Comment by kubo6472** [comment]
Worked, thanks. It was almost right.
