### ISSUE TITLE
Not able to embed videos on external sites

### ISSUE THREAD

**Issue by C161** [iv-org/invidious#3229]
I want to embed a video on a site using Invidious. While the original embed from YouTube works, the one from Invidious does not. I am able to paste the link manually in my browser however, and it plays just fine.
Youtube iframe: 
`<iframe width="560" height="315" src="https://www.youtube.com/embed/znpLJdvRZNk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

Invidious iframe: 
`<iframe width="560" height="315" src="https://inv.vern.cc/embed/znpLJdvRZNk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

The Privacy Redirect add-on does not work either. If I have it toggled on, the YouTube iframe stops to work, too.
The test was done [here](https://c161.github.io/art/the%20fog/the-fog.html).

![Screenshot from 2022-07-30 15-08-30](https://user-images.githubusercontent.com/108121550/181915836-8ba003e8-8739-4f95-a13b-dafe4a0132f2.png)

![Screenshot from 2022-07-30 15-08-40](https://user-images.githubusercontent.com/108121550/181915842-6b5b7154-9601-4ae9-99b0-8b95f31be923.png)

 - Browser: Brave and Firefox
 - OS: LMDE 5

**Comment by unixfox** [comment]
Please write the URL of the invidious instance used.

**Comment by C161** [comment]
yt.artemislena.eu
inv.bp.projectsegfau.lt
yewtu.be

They all don't work and give me the "Domain XY refused to connect." error.

![Screenshot from 2022-07-30 15-55-50](https://user-images.githubusercontent.com/108121550/181917662-b8c2c75b-3839-473b-b027-6de82fa1a6c3.png)
![Screenshot from 2022-07-30 15-56-53](https://user-images.githubusercontent.com/108121550/181917675-4cb64a61-3566-4752-b26e-e2b2e67a8348.png)

**Comment by unixfox** [comment]
Does the embed work on this website: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe?

**Comment by C161** [comment]
Yes, both the YouTube and the Invidious embed work (even different instances)

**Comment by unixfox** [comment]
Then it's a CSP issue, your webpage need to configure the correct CSP in order to allow iframes.

Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

Closing the issue as it's not a problem directly related to invidious. If you want additional help you may join our matrix or IRC channel:
- matrix: https://matrix.to/#/#invidious:matrix.org
- IRC: https://web.libera.chat/?channel=#invidious
