### ISSUE TITLE
[Meta/Question] api-only

### ISSUE THREAD

**Issue by kubo6472** [iv-org/invidious#3236]
Has anyone recently tried to run invidious without any frontend just for e.g. FreeTube integration? There used to be the API-only branch, but it is no longer working.

**Comment by unixfox** [comment]
You can build the API only with `crystal build -Dapi_only src/invidious.io`.

Do note that this remove a bunch of endpoints in invidious and some may be required for freetube to work properly with invidious.

**Comment by kubo6472** [comment]
Thanks
