### ISSUE TITLE
[Bug] dash with low resolution at the start of playing

### ISSUE THREAD

**Issue by rezad1393** [iv-org/invidious#3241]
when I set the quality to dash and set resolution to high (like 720) when I have low internet speed the start of video (like the first 7 second) is show as low resolution. low at 240 or 128p

is this intended behavior?
can this be "fixed"?

**Comment by unixfox** [comment]
I think it's probably because the force quality plugin kicks in only after a few seconds, but videojs built-in auto selection of the best quality has already started, so it tries to load a low resolution segment in order to detect the best quality based on your internet connection.

But then the force quality plugin step in and force the quality to 720p. Which result in a small delay in order to have the a 720p stream.

We can't do anything about it unfortunately, it's an issue present in the video.js player: https://github.com/videojs/video.js

**Comment by rezad1393** [comment]
> I think it's probably because the force quality plugin kicks in only after a few seconds, but videojs built-in auto selection of the best quality has already started, so it tries to load a low resolution segment in order to detect the best quality based on your internet connection.
> 
> But then the force quality plugin step in and force the quality to 720p. Which result in a small delay in order to have a 720p stream.
> 
> We can't do anything about it unfortunately, it's an issue present in the video.js player: https://github.com/videojs/video.js

is there any plan to maybe migrate to another video player, or maybe create one?
I see some bug that are all videojs. like this bug here.
or no support for vp9.
is that too much work?
any other video player that can somewhat replace videojs?

**Comment by unixfox** [comment]
creating a video player is a full time job, we are just volunteers. so it's not a no go.

I evaluated the other video players a month ago, shaka was a good candidate but it is made by google: https://github.com/shaka-project/shaka-player
Expect that player, there is no player that offer the same level of functionalities as video.js

**Comment by rezad1393** [comment]
thank you for taking the time to respond to my post.
I understand the part about creating a video player.
the issue I have is that videojs has some bugs that are too weird.
like the bug here or it not supporting vp9. I have no idea why a html video player would not support a coded. am I missing something?

about that shakra player, I browsed its github page and it has a good feature summery, though I am not an expert.
is that a problem that google created that? it is open source and can be at the last resort forked right? that way the whole "create a video player is a full time job" is not that important, right? and that is in the even that google doesn't support that project anymore.

any place that I can track, maybe a test for shakra with invidious or is it just a suggestion right now?

**Comment by unixfox** [comment]
can we continue the discussion on matrix : https://matrix.to/#/#invidious:matrix.org or IRC: https://web.libera.chat/?channel=#invidious

I don't like discussing "off-topic" things on a github issue.
