### ISSUE TITLE
[Bug] Index out of bound - video doesn't exist in the playlist

### ISSUE THREAD

**Issue by tunnckoCore** [iv-org/invidious#3242]
**Describe the bug**

 It's a mirror of popular Bulgarian torrent site for 2 decades. I don't know which instance it tries to get the embed cuz I have the Privacy Redirects Firefox extension which automatically redirects youtube links.

**Steps to Reproduce**

1. Go to https://zamunda.ch/index.php
2. It has usually a youtube embed.

**Logs**

Title: `Index out of bounds (IndexError)`
Date: `2022-08-05T10:30:09Z`
Route: `/embed/?listType=playlist&list=PLLjHNPsiPC3f9jTm0HhH3OckS6MOSfxGv&index=11&local=true&dark_mode=true`
Version: `2022.08.03-4ab54f2 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/string.cr:5288:5 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Screenshots**

It says to report it and as Open Sourcerer i'm reporting it.

![image](https://user-images.githubusercontent.com/5038030/183059970-1291636f-32df-4f19-9080-9571198a51ce.png)

**Additional context**

 - Browser (if applicable): Firefox (LibreWolf) latest
 - OS (if applicable): ArchLinux

**Comment by unixfox** [comment]
The bug is related to the parameter `index=11`. Can reproduce on all the instances.

**Comment by tunnckoCore** [comment]
Oh, yea thanks. Didn't thought about that.

**Comment by unixfox** [comment]
There are 10 videos in the playlist, invidious can't magically find a 11th one.
