### ISSUE TITLE
[Bug] When redirecting from youtube.com to $INSTANCE, it signs you out

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3247]
**Describe the bug**
If you set up Redirector to redirect you from youtube.com to $INSTANCE, it will sign you out, until you click "LOG IN".

**Steps to Reproduce**
1. Install Redirector Add-on (I've only tested this on Firefox, it might also happen in Chrome).
2. Add a Redirect like this:
```
 Redirect:

^https://(www.|)youtube.com/(.*)$
to:

https://youtube.test/$2
Example:

https://www.youtube.com/watch?v=L0BxpbisQBg → https://youtube.test/watch?v=L0BxpbisQBg
Applies to:

Main window (address bar)
```
Replace `youtube.test` with your instance's URL.
3. Sign in to your instance
4. Go to youtube.com, and get redirected
5. See error

**Logs**

**Screenshots**

**Additional context**
It may be some issue with cookies. Since there seems to be no corresponding issue(s) for Libredirect, this seems to be unique to the Redirector addon.

**Comment by unixfox** [comment]
Can you confirm it's pretty much the same issue as this one: https://github.com/iv-org/invidious/issues/3132?

**Comment by DUOLabs333** [comment]
It doesn't seem to be --- If I go to a link like https://youtube.test/watch?v=$ID, I'm logged in.

**Comment by unixfox** [comment]
I'm closing this issue because I do think the cookie issue is the same as https://github.com/iv-org/invidious/issues/3132.
