### ISSUE TITLE
[Enhancement] Rework the headers and parameters sent

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#3256]
We should rework the headers and parameters that we send in https://github.com/iv-org/invidious/blob/master/src/invidious/yt_backend/connection_pool.cr#L9 because these were applicable to the old way for communicating with youtube servers.

Here are the parameters sent by newpipe and yt-dlp: https://gist.github.com/coletdjnz/cc0cbce42067b77c628d68c7b10a96c5

**Comment by unixfox** [comment]
Like found in https://github.com/iv-org/invidious/issues/3230#issuecomment-1226887639, we should send the correct user-agent or youtube will send us an error `Content not available in this app. upgrade to latest version of youtube.`.

**Comment by unixfox** [comment]
Technically done in https://github.com/iv-org/invidious/pull/3290 but @SamantazFox wants to do improve it: https://github.com/SamantazFox/invidious/tree/yt-api-improvements

**Comment by unixfox** [comment]
Closing as the videos streams retrieval will be moved to invidious companion.

**Comment by syeopite** [comment]
Isn't this still applicable for the data that will be fetched by Invidious? Eg channel videos
