### ISSUE TITLE
[Bug] Invidious Docker Container log errors

### ISSUE THREAD

**Issue by computertherapist** [iv-org/invidious#3265]
**Describe the bug**
Pulling the latest docker container results in an error in the docker logs for the container and a 502 bad gateway from nginx

**Steps to Reproduce**
I ran a docker-compose pull to update my containers, followed by a docker-compose down and docker-compose up -d. Invidious is stuck in a restart loop

**Logs**
(from the Invidious docker container)
Unhandled exception: Route declaration get "/" needs to start with '/', should be get "//" (Kemal::Exceptions::InvalidPathStartException)
  from src/invidious/routing.cr:19:5 in 'register_all'
  from /usr/share/crystal/src/gc/boehm.cr:129:5 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'

**Comment by griffinht** [comment]
I am also having this issue after https://github.com/containrrr/watchtower updated invidious for me, probably caused by https://github.com/iv-org/invidious/pull/3261

**Comment by SamantazFox** [comment]
I'm deeply sorry for the bug. I let a typo pass through in the PR you mentioned :/
