### ISSUE TITLE
Random Videos in other tabs starting unexpectedly 

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#327]
i am using firefox 64 on windows 10. it now happened the 4 or 5th time that a video from a completely unrelated tab start playing. as far as i remember it is triggered by loading a new tab or starting to play another invidio.us video

**Comment by omarroth** [comment]
You may have `autoplay` enabled, otherwise there's not much else I could suggest, since I'm having trouble reproducing.

**Comment by elypter** [comment]
i dont have it enabled and i never had. its a weird bug becase it affects other tabs. maybe it was a firefox bug. i report if it keeps happening.

**Comment by elypter** [comment]
it has been quite a while since the last time this happened so i assume whatever caused it is now fixed.

**Comment by Zero3K** [comment]
Its not fixed for me.

**Comment by Zero3K** [comment]
Its still happening.

**Comment by elypter** [comment]
its very rare but probably not solved yet. last time it happened about 2 months ago.

**Comment by elypter** [comment]
it happened many times yesterday and today so it definitely is still a problem

**Comment by Zero3K** [comment]
Bump

**Comment by unixfox** [comment]
> Bump

Still happening?

**Comment by unixfox** [comment]
Closing due to a lack of replies.

Might be fixed because a lot of code changed since almost more than 1 year.
