### ISSUE TITLE
[Bug] Loading a specific channel throws "Index out of bounds" error

### ISSUE THREAD

**Issue by ryspace** [iv-org/invidious#3270]
**Describe the bug**
Trying to load a channel on multiple instances gives an index error: Index out of bounds.

**Steps to Reproduce**
1. Open an invidious instance
2. Attempt to visit channel ID `UChlBQwYK2Z7zj-Lclj0375w`
3. See Error:

**Logs**

Title: `Index out of bounds (IndexError)`
Date: `2022-08-15T23:28:51Z`
Route: `/channel/UChlBQwYK2Z7zj-Lclj0375w`
Version: `2022.08.13-9e58bc19 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/hash.cr:907:13 in 'text_to_parsed_content'
  from src/invidious/channels/about.cr:92:26 in 'get_about_info'
  from src/invidious/routes/channels.cr:200:17 in 'fetch_basic_information'
  from src/invidious/routes/channels.cr:9:12 in 'videos'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

</p>
</details>

**Additional context**
Other channels seem to load just fine, so there just seems to be something about this channel's ID that invidious doesn't like.

Tried on snopyta, flokinet, yewtube, and 076.ne.jp

**Comment by Jon-guy30** [comment]
I'm getting it too on my end. Two different instances.

![channel error](https://user-images.githubusercontent.com/10241225/185441352-a3830d5e-f73a-44e9-acb2-259e3e57efc4.PNG)

**Comment by unixfox** [comment]
Please don't put a screenshot but instead copy paste the text.
