### ISSUE TITLE
Youtube embed feature works inconsitently

### ISSUE THREAD

**Issue by Jon-guy30** [iv-org/invidious#3274]
Hi all! So I'm having a problem with the youtube embed feature...

**Describe the bug**
The Watch on YouTube (embed) button works works inconsistently.

**Steps to Reproduce**
1. Go to any video.
2. Click on "Watch on YouTube" (embed).
3. Watch it redirect to YouTube itself, not loading the embedded player. I just tried it with Edge, it loaded once, subsequent attempts failed.

**Additional context**
 - Browser (if applicable): Google Chrome 104.0.5112.102 only with uBlock origin and remove Youtube suggestions and I don't care about cookies. Tried with Edge latest stable channel with the same extensions, same effect. I only watch videos on chromium browsers, haven't tried Firefox.
 - OS (if applicable): Windows 8.1 (Version 6.3 build 9600) x64

The embed link which gives me an embedded invidious video works fine, this is about the YouTube embed.

**Comment by unixfox** [comment]
It's an issue related to YouTube, when you click on the link `Watch on YouTube **(Embed)**` you exit the software `invidious`. We have no control over what's going on after that.

Please open a bug at Google instead.

**Comment by Jon-guy30** [comment]
Ah ok, I didn't realize. Thanks for letting me know! Explains why the invidious embed works fine.
