### ISSUE TITLE
Feature Request: Alternative source and or p2p source

### ISSUE THREAD

**Issue by twodollarblake** [iv-org/invidious#328]
In the age of google restricting free speech, it's essential to move away from youtube. I propose that you Implement at least one alternative source. This will make it convenient for consumers to protect their privacy while watching videos from youtubers that they know and love, while allowing these youtubers to migrate their content from youtube to another source to protect their content.

Options to implement include [Bitchute](https://www.bitchute.com/) and one of the [Peertube Instances](https://joinpeertube.org/en/#instances-list). Since Peertube is p2p, it's a smart choice for bypassing censorship. If you decided to make your own instance (the graphics are already there, and the p2p code is already there, you just have to marry the two), the p2p-ness prevent putting a load on invidious servers.

**Comment by ealgase** [comment]
How would p2p take a load off invidious?  Invidious isn't serving any of the content (which is like 99.9% of used bandwidth).

**Comment by elypter** [comment]
i dont know if invidio is currently proxying some of the videos that didnt work until recently. if so it could actuallly reduce traffic.

moreover it could serve as a backup for videos that are deleted on youtube.

**Comment by Perflyst** [comment]
Mirrors can create a lot of issues (because of copyright)
Also need a lot of space, this is a bad idea

**Comment by omarroth** [comment]
> the p2p code is already there

I'm not quite sure what you're referring to here. Is this something that I've already implemented, or are you referring to what Peertube has? I would like to allow users to watch videos without enabling Javascript (as is currently the case with YouTube), is it possible to watch Peertube videos in this way?

I think adding support for different platforms would be a very nice thing to have. There's been some mention of adding support for SoundCloud, similar to NewPipe, although there doesn't appear to be an open issue here.

There is a cost associated with adding support for multiple services. Search needs to be able to merge results from multiple services, as would subscriptions and playlists, see #114. Again, I'm not opposed to this at all, just making clear what would need to change to support this.

**Comment by blaketeastman** [comment]
@omarroth This is not something you've implemented. When I said the p2p code was already there, I was talking about the code that peertube has published on GitHub [(https://github.com/Chocobozzz/PeerTube).](https://github.com/Chocobozzz/PeerTube). Unfortunately, peertube is written in typescript, which is described as "a superset of javascript".

I'm glad you're open to adding new sources, but I'm not a fan of soundcloud as an option. There's no video, and if your goal is to be an alternative to youtube in the long term, you need to provide video.

**Comment by elypter** [comment]
doesnt the player already need javascript? i tried to use it with umatrix disabling scripts and it played but with an error message overlayed and the second attempt it only showed the error message so the first might have been a fluke. the error is about unsupported format and mime type

**Comment by blaketeastman** [comment]
@elypter I don't think so... I disabled scripts and it works just fine.

**Comment by elypter** [comment]
https://invidio.us/watch?v=8QSpDfGHmtw

this gives me an error message and this one doesnt play the video

https://invidio.us/watch?v=jvTO4OvOKuk

both work when js is enabled

**Comment by blaketeastman** [comment]
@elypter I'm on fedora with brave browser, using brave shields to block the scripts, and they both work fine.

**Comment by omarroth** [comment]
> They do say they are working on a script-less version, but that doesn't helps us now.

Please do leave an update when this is available.

> I'm glad you're open to adding new sources, but I'm not a fan of soundcloud as an option.

This was mostly referencing NewPipe as precedent, since they've also taken steps to integrate multiple services. I personally think SoundCloud would be a reasonable addition since music is almost paradoxically quite a large part of YouTube, you can look at #302 or the [list of most-viewed YouTube videos](https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos) to get a better sense of that.

There's also Vimeo and DailyMotion that could be considered reasonable additions.

Because of the amount of work required to support this I wouldn't expect it to be added soon, but I will look into it and provide an update when I've started work on it.

**Comment by exilexi** [comment]
+1 to Peertube! And thanks for all your work!

**Comment by wuniversales** [comment]
You can use this to add p2p to the videos.
https://github.com/Novage/p2p-media-loader
I hope the feature is added.

**Comment by vincenthawke** [comment]
I hope Bitchute gets added soon. I would love to combine Bitchute and Youtube videos in 1 place to not need to log into both platforms to get videos I am subscribed to.

**Comment by snakyjake1** [comment]
YouTube has been removing/censoring videos and channels that I follow.  A lot of the channels are now moving to Bitchute and Rumble.

**Comment by syeopite** [comment]
Invidious is a Youtube frontend and nothing more. This is out of scope
