### ISSUE TITLE
[Bug] Video titles are unreadable when video is paused

### ISSUE THREAD

**Issue by Victor239** [iv-org/invidious#3293]
**Describe the bug**
Due to the colours chosen, reading the video's title is very difficult.

**Steps to Reproduce**
1. Go to any video
2. Click play, then pause it

**Screenshots**
![](https://i.imgur.com/7OnWfj0.png)

**Comment by SamantazFox** [comment]
Could you please explain where this happens? Afaik, the video title isn't displayed over the video player.

**Comment by Victor239** [comment]
It displays the video title when videos are embedded e.g. using the [LibRedirect](https://addons.mozilla.org/en-GB/firefox/addon/libredirect) browser extension to replace embedded YouTube videos with Invidious ones. 

[Video ID/URL](https://yewtu.be/watch?v=I_VLPN8PD2Y)
Current version: 2022.09.02-5460d12 @ master
Firefox 104.0.1
[Example webpage](https://summit.news/2022/09/01/its-a-scam/) with embedded YouTube video if trying to test the extension

**Comment by SamantazFox** [comment]
Thanks for the details. I've made a PR to fix it :)
