### ISSUE TITLE
[Bug] Seeing somebody else's email login account on puffyan instance

### ISSUE THREAD

**Issue by Pentaphon** [iv-org/invidious#3297]
I'm logged into the https://vid.puffyan.us/ instance with a very long random password but every time I go to the site I see this. 

![puffyan](https://user-images.githubusercontent.com/49374058/188025060-1141048a-82d8-4240-8eaf-fd89c4754b86.png)

This is not my email. It's somebody else's. I have a randomized username because I never gave invidious any email since it doesn't require an email address. Anybody else seeing this? 

When I refresh the page, my username comes back. Is this a puffyan instance bug or an invidious bug?

**Comment by SamantazFox** [comment]
@ItsSt0ne You're the owner of that instance, right?

**Comment by Pentaphon** [comment]
Update: it's stopped showing me somebody else's email as the username but now I have to press the login button to see my username whenever I go to the site while I'm logged in.

**Comment by ItsSt0ne** [comment]
This was an instance issue, and should be resolved now.

**Comment by Pentaphon** [comment]
> This was an instance issue, and should be resolved now.

Anything users should worry about?

**Comment by ItsSt0ne** [comment]
> Anything users should worry about?

I don't think there were any additional issues related to this, no one would have had access to user accounts or other data.
