### ISSUE TITLE
[Enhancement] [Search] Open video pasting YouTube URL

### ISSUE THREAD

**Issue by valerio-bozzolan** [iv-org/invidious#3300]
## Proposal

Improve the search field, in order to accept a YouTube URL instead of a generic search term. Example: you can paste this:

https://www.youtube.com/watch?v=5mgYnwhM4eg

To be redirected there:

https://yewtu.be/watch?v=5mgYnwhM4eg

Some interesting related documents:

* https://stackoverflow.com/questions/6903823/regex-for-youtube-id

Pro:

* you don't need a rewrite extension
    * useful when you are on another computer, or from a smartphone, or from a TV
    * useful to help iOS users in migrating from YouTube (they usually cannot use extensions)
* you don't need to manually rewrite the URL
    * usually longer than copy-paste
    * allows to avoid typo/mistakes

Example use case:

Somebody sends a YouTube URL in a chat. You have an Invidio.us tab already opened (or you have a bookmark to it). You could just copy that, paste in the search bar, and see the video.

**Comment by unixfox** [comment]
Mmh I think you can get the same result with a web extension like [privacy redirect](https://github.com/SimonBrazell/privacy-redirect) or [libredirect](https://github.com/libredirect/libredirect) or any other redirector extension.

On top of that, you can just swap the domain `youtube.com` to `yewtu.be` and you will get the same result.

Not sure if it's really useful to implement this feature.

**Comment by valerio-bozzolan** [comment]
Yep. Sorry, I've added now some "Pro" notes as general context.

**Comment by OkyDooky** [comment]
Also, as far as I know, iOS cannot support browser extensions. So, this is a good use case for a lot of users.

**Comment by valerio-bozzolan** [comment]
Moreover, I don't know how much you love the Fediverse, but lot of PeerTube users love to paste URLs from domain1 in search bar of domain2 resulting in a transparent integration.

Example: visit this URL (video.linux.it) and see what I searched, and look what I've found (the video from peertube.uno):

https://video.linux.it/search?search=https:%2F%2Fpeertube.uno%2Fw%2Fff69b2fb-63d4-4eea-9684-eca165fa500d&searchTarget=local

And trust me, pasting an URL in the search bar can be intuitive and a-m-a-z-i-n-g-l-y quick and monkey-approved.

**Comment by SamantazFox** [comment]
Yup, I completely agree that this is a very cool feature to have!
I'll see what I can do to implement it, but I can't promise it will be done soon.
