### ISSUE TITLE
Sound becomes erratic after coming back from sleep.

### ISSUE THREAD

**Issue by jminer-kraft** [iv-org/invidious#3305]
Whenever I leave invidious open for a while and my computer goes to sleep for maybe 20 minutes, when I bring my computer back up and try to play whatever video I was watching beforehand, the sound kind of cuts in and out. This happens no matter which video it is and the only way to fix the sound is to close out of invidious and open a new tab, not even refreshing the page works. I run Firefox 104.0.1 on Pop!OS 22.04 LTS. The hardware is a Dell Latitude E5470 if that helps any.

**Comment by unixfox** [comment]
Does it happen on other websites too?

**Comment by jminer-kraft** [comment]
No, just invidious

**Comment by unixfox** [comment]
can you reproduce this issue on other browsers like chromium?

**Comment by jminer-kraft** [comment]
I don't use chromium. It isn't installed. I can install it and see.

**Comment by jminer-kraft** [comment]
Oh, and the instance is http://inv.riverside.rocks/

**Comment by jminer-kraft** [comment]
oops its https://inv.riverside.rocks/

**Comment by jminer-kraft** [comment]
It does indeed happen on chromium. Just tested it.

**Comment by unixfox** [comment]
Do you have DASH enabled or you didn't touch the invidious settings?

Also can you reproduce this issue on the demo page of video.js: https://videojs.com/advanced/?video=sintel? Video.js is the player used by invidious.

**Comment by jminer-kraft** [comment]
Dash is enabled by default on the instance I am using, and I did not change that setting. I did change the screen resolution to a lower one to save bandwidth. I cannot duplicate the issue on the demo page.

**Comment by jminer-kraft** [comment]
So now its just doing it whenever I open multiple videos in sequence (one after another) in the same tab. Like, I finish a video then open another in the same tab and it does the same thing as letting the computer go to sleep. It seems that opening the second video in a new tab fixes the issue.

**Comment by unixfox** [comment]
Can you reproduce this issue when DASH is not enabled?

**Comment by jminer-kraft** [comment]
The videos won't even load if DASH is disabled.

**Comment by unixfox** [comment]
That's not true almost all videos load without dash.

Check your browser extension or something that is blocking the requests

**Comment by jminer-kraft** [comment]
I have a few privacy extensions, but invidious is allowed through all of them.

**Comment by jminer-kraft** [comment]
I have tried removing the extensions, but no luck.

**Comment by jminer-kraft** [comment]
I think it was just the instance I was using, because it went offline for a good while and when it came back up it worked again, as long as I don't use dash.
