### ISSUE TITLE
[Bug] could not access status of transaction 0 (PQ::PQError)

### ISSUE THREAD

**Issue by Hereforonething** [iv-org/invidious#3307]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
On which invidious instance did you get this issue?

**Comment by SamantazFox** [comment]
Could you provide more details, please? There should have been an error message with some useful details.

**Comment by unixfox** [comment]
@Hereforonething  Closing due to lack of replies, please reopen with an answer.
