### ISSUE TITLE
Empty RSS for particular YT channel [Bug] 

### ISSUE THREAD

**Issue by mateuszjablonski** [iv-org/invidious#3310]
**Describe the bug**

For a particular channel "Śmiem Wątpić" the RSS feed is empty. It has title, description, author and image, but no items - even though there are videos on the channel as recent as 1 week ago.

**Steps to Reproduce**

1. Go to https://invidious.snopyta.org/channel/UC-Q7kWPVNqMsCyy4ZgGE6MA
2. Click on RSS icon in upper right corner
3. Inspect opened/downloaded subscription file
4. It has no items - only the basic feed structure

**Logs**

none

**Screenshots**

<img width="785" alt="Zrzut ekranu 2022-09-15 o 15 20 37" src="https://user-images.githubusercontent.com/7666514/190414445-618ffcde-2924-4e3e-9ae4-48f543fa7c53.png">

**Additional context**

Regular Youtube RSS returns items as expected:
https://www.youtube.com/feeds/videos.xml?channel_id=UC-Q7kWPVNqMsCyy4ZgGE6MA

**Comment by s104346** [comment]
The empty RSS feed bug does not only occur for one particular channel, but basically for all channels I've tested and/or on /feed/popular listings.

Three empty example feeds from channels that posted in the last 24h:
- https://invidious.rhyshl.live/feed/channel/UCm9K6rby98W8JigLoZOh6FQ
- https://yewtu.be/feed/channel/UC7YOGHUfC1Tb6E4pudI9STA
- https://invidious.sethforprivacy.com/feed/channel/UCg6gPGh8HU2U01vaFCAsvmQ

**Comment by SamantazFox** [comment]
What did youtube change this time...

**Comment by Sommerwiesel** [comment]
Hello, I don't know if this is related but my public instance (invidious.nerdvpn.de) has stopped refreshing all feeds as of today.

RefreshChannelsJob: UCvDUaH2fbXP_Yc5Lc9UXfqA : Deleted or invalid channel

**Comment by s104346** [comment]
It's working again for some reason ...

**Comment by mateuszjablonski** [comment]
It is indeed. Let's hope it was an incident. Closing the issue.

**Comment by unixfox** [comment]
It would have been great to save the XML file given directly by youtube servers in order to introduce some fix for the future.

**Comment by SamantazFox** [comment]
@unixfox I tried to, but unfortunately this bug didn't impact me. Either this was limited to some region, or they fixed it before I was able to save the XML.
