### ISSUE TITLE
[Bug] Hashtag search - pagination not correct

### ISSUE THREAD

**Issue by allendema** [iv-org/invidious#3311]
**Describe the bug**

When searching for a hashtag or simply clicking on a hashtag from the description will redirect to instance.tld/hashtag/something,   
then if you click on ```next page``` the same videos will appear.

**Steps to Reproduce**

See 
https://invidious.tiekoetter.com/hashtag/livecomedy?page=1
https://invidious.tiekoetter.com/hashtag/livecomedy?page=11

They will contain the same videos.

**Logs**

N/A

**Screenshots**

N/A
**Additional context**

N/A

**Comment by SamantazFox** [comment]
Fixed by #3803
