### ISSUE TITLE
[Bug] Outdated docker-compose file in the repository

### ISSUE THREAD

**Issue by tiyn** [iv-org/invidious#3326]
When setting up invidious with docker i ran into a few problems.
I cloned the repository and made slight changes to the `docker-compose.yml` file.
After that setup the version number of the invidious instance showed a date `2021.04.13-edb37c9 @ master`.
that does not match the current version.

**Steps to Reproduce**

- Clone the repository (`git clone https://github.com/iv-org/invidious`)
- Open the directory (`cd invidious`)
- adapt the `docker-compose.yml` file (`vim docker-compose.yml`)
- run the docker-compose file (`docker-compose up`)

**Probable solution**
I then searched in the documentation of invidious.
It appears that the [docker-compose file of the repository](https://github.com/iv-org/invidious/blob/master/docker-compose.yml)
and [that of the documentation](https://docs.invidious.io/installation/] are not the same, with the documentation being the 
more current version of the docker-compose file.
After using the docker-compose file of the documentation the set up worked flawlessly without problems 
and with the current version number.

The docker-compose version works correctly with the following steps:

- Clone the repository (`git clone https://github.com/iv-org/invidious`)
- Open the directory (`cd invidious`)
- Navigate to [https://docs.invidious.io/installation]
- Copy the `docker-compose`-file in the `Docker-compose method (production)` section
- Change the dockercompose file (`vim docker-compose.yml`) by pasting the suggestion of the previous step (remove all other lines)
- run the docker-compose file (`docker-compose up`)

Additionally it has to be noted, that the docker-compose file of the documentation uses postgres:14 and the repos version uses postgres:13.
The only other difference seems to be that the repository version builds invidious from the repository and the documentation version using a quay.io image of invidious, which in my case seems to be working way better.

**Comment by unixfox** [comment]
Please post the commands used.

**Comment by unixfox** [comment]
Thanks.

Closing this issue as the docker-compose.yml should only be used for development purpose.

So you indeed used the right docker-compose.yml from the documentation.
