### ISSUE TITLE
[Question] Full HD 1080p streaming over 720p ?

### ISSUE THREAD

**Issue by FrostBlade5** [iv-org/invidious#3327]
Any plans to provide 1080p in invidious for example with yewtu.be ?
720 is not bad but the quality is not really good either.

**Comment by unixfox** [comment]
Enable dash in the preferences and you will get 1080p stream.

**Comment by FrostBlade5** [comment]
> Enable dash in the preferences and you will get 1080p stream.

How / where are the perferences to enable dash? Is that a browser setting or an invidious setting?

**Comment by FrostBlade5** [comment]
When i klick the settings icon in invidious/yewtu.be it only shows 720p and 360p

**Comment by unixfox** [comment]
https://yewtu.be/preferences

**Comment by FrostBlade5** [comment]
> https://yewtu.be/preferences Preferred video quality: Dash

Thank you.
So basically i will have to load the perfernces site and manually enable dash quality every single time i want to use yewtu.be in 1080p? Is there any way to automate this process?
Would you consider pushing 1080p to be the new standard? 720p looks a bit blury.

Anyways thanks for helping.

**Comment by SamantazFox** [comment]
> > https://yewtu.be/preferences Preferred video quality: Dash
> 
> So basically i will have to load the perfernces site and manually enable dash quality every single time i want to use yewtu.be in 1080p?

Yyou'll only need to do it once :)
It's saved in a browser cookie once you click "save preferences"!

**Comment by unixfox** [comment]
Or if you don't want to save the cookies then use an extension like:
- privacy redirect: https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/
- libredirect: https://libredirect.github.io/

**Comment by FrostBlade5** [comment]
> > > https://yewtu.be/preferences Preferred video quality: Dash
> > 
> > 
> > So basically i will have to load the perfernces site and manually enable dash quality every single time i want to use yewtu.be in 1080p?
> 
> Yyou'll only need to do it once :) It's saved in a browser cookie once you click "save preferences"!

I don't use cookies for privacy reasons... my browser is configured in about:config and in setting to delete all cookies when closed... this is not a solution for me and it shouldn't be for anyone.

**Comment by FrostBlade5** [comment]
> Or if you don't want to save the cookies then use an extension like:
> 
>     * privacy redirect: https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/
> 
>     * libredirect: https://libredirect.github.io/

I use only uBlockOrigin for a minimalistic setup, it's pretty damn good and in general it's better to avoid to many extensions.
I had a similar problem when i used duckduckgo search (which i don't anymore after tracking agreement with microsoft...), i liked to use darkmode with duckduckgo search but every time after restarting the browser it was using system default (white mode), because i delete cookies for privacy. Is there no other solution to this than enabling cookies to be safed or installing an extensions? Id rather add a little bit of automated code to librewolf to tell it how to handle yewtu.be, is there really no other way to instantly trigger 1080p streaming whenever yewtu.be is loaded?

**Comment by unixfox** [comment]
If you append `quality=dash` to the URL then it will use dash.
Example: https://yewtu.be/watch?v=WuCN8eiLDko&quality=dash

**Comment by FrostBlade5** [comment]
Thanks for that, working perfectly.
Just, i can't think of how i could use this as an automated process. manually writing &quality=dash seem even more work than changing the setting itself.

I can't resist to say this, the video you sent was the worst choice, didn't watch it but not going to either because this guys face with the wide open mouth looks so extremly disgusting and stupid makes me want to put a pistol in his mouth and pull the trigger, lol. Sorry, i really hate these people.

Let me mention, i use a batfile to instantly visit all youtube channels of interest.
So i tried adding &quality=dash to the end of the channel url but this sadly did not work...
example https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q&quality=dash

You think this could be added as a future update/improvement?
Would be really awesome if that can be added to a channel and not just a video.
If it would work with the channel then i imagine any video i would select will play in dash (1080p) this would be great.
Also darkmode in the parameters is interesting as i always use it (it's chilling for the eyes). How could i use darkmode and dashquality at the same time how do i write that to the urlbar correctly?

**Comment by unixfox** [comment]
> You think this could be added as a future update/improvement?

Please open a new feature request.

Meanwhile, we hugely recommend using an extension for that, this will make things way easier. If you want a simple extension that does the redirect then use this extension: https://addons.mozilla.org/en-US/firefox/addon/redirector/

Using an extension won't harm your privacy, it won't collect info about you. It is running locally only.

**Comment by FrostBlade5** [comment]
> Please open a new feature request.
> 
> Meanwhile, we hugely recommend using an extension for that, this will make things way easier. If you want a simple extension that does the redirect then use this extension: https://addons.mozilla.org/en-US/firefox/addon/redirector/
> 
> Using an extension won't harm your privacy, it won't collect info about you. It is running locally only.

I have seen a few videos claiming some extensions do indeed steal data and abuse the person installing them, unlikely to happen to me as i take care of whati install, i'm just saying it is possible that extensions can be harmful, or not?
![Capture2](https://user-images.githubusercontent.com/91756004/192577300-2a455450-f649-46b2-9365-dc898e5ed4ff.PNG)

I installed your recommendation (the addon redirector) i never used anything like that and it seems like i am to much of an idiot to get it working...
![Capture](https://user-images.githubusercontent.com/91756004/192577431-8ecabe0c-7f49-4ac7-a4ac-fce792f4585f.PNG)

**Comment by unixfox** [comment]
> I have seen a few videos claiming some extensions do indeed steal data and abuse the person installing them, unlikely to happen to me as i take care of whati install, i'm just saying it is possible that extensions can be harmful, or not? 

The same applies to programs that you run on your computer, some are harmful and some are harmless.

Mozilla takes the security of their web store for Firefox extension very seriously, so it's very unlikely that an extension that is 2 years old, like privacy redirect, will be harmful to your data.

Again I really recommend using it because it has dedicated features for invidious. If you want to be sure to run the correct source code you can always install it from the github repository: https://github.com/SimonBrazell/privacy-redirect#development
