### ISSUE TITLE
[Bug] Captions issue on some videos

### ISSUE THREAD

**Issue by llsc12** [iv-org/invidious#3330]
**Describe the bug**
Captions data returned on some videos seems to be garbled.

**Steps to Reproduce**

Go to [/api/v1/captions/Vd9QkWsd5p4?label=English](https://test.invidious.io/api/v1/captions/Vd9QkWsd5p4?label=English)

**Logs**

<details>
<summary>Garbled response</summary>
�����Xn7W07y!8>D#CNvv()˗HTKZ$X0i68nh߰;3LɯjX/j0=$IO{Gv iQ&g,)Ho!k^5"6jltS^}d/z7QQLy3uq�a;=kFͦ+TIoj|43L-6{0T9Bf1[
]2}뻭Һم=؅;QQIE?",L!;
k6-iXJyՆ쟏8[̬!b)Zt:j^WJ%rǍB*K�;=&@U,[hLZd
fb歫
\OA͓+fطJT
9e.>j8
3H-lu;e+0<2*Mr/MHh|ކm5VVʴ=١A(픨td0@;E^_pw\K{q6$l(i빰Æk2*^y
fP1"-Qlɋ14"4O#/2j<mp_<^ukŎyT+7P$w	[V$Mh<yaچ|;;1=Y]MN/ ɹ6/WWIJ=
8<,yg~Ԣvۃ?�(AiKv#fs$rr;SԌ1=^Ml&JK"wzgN)c/ywfLaDPR[)v͕`=DX""i֓>P=R3Y;W5
yenZHѨxg(
.Ƴ
ATI
 *xVxD1-k_
M`羭vQőJ^z�+܎|FUPK?�a`KY%*]fV)R*`(IJ*�(D3DvV'q@QA2@"*ƴ|Y)0zSf0y-%E4ȣ(
_ED
/:	?Ѭ
<-=
	/µ]a*`g2pۨDsl5
PMvֶc)Y:w{m~8'JȻ
M
nR#hncjAn	gvYM:1 ތ~%jX+!ӳFRCrTU`tGEcϖwm̢GPJ+kwHqJ~g{DPFųZ&Lښ0!uP8q63ʝFrzRPd
f()^*GNg6km")ⲑ,hG?
\"AWϴ#(WPC)øYw$"'y*6� ̀%*1`<2|IwJC%p$(\|r� 
^D0E'g@Qpx Q\g}r
C\<`(YO["E#)(Jy#'xS>yTx*;gzYoM<��
</details>

**Comment by llsc12** [comment]
what did youtube change? just curious

**Comment by SamantazFox** [comment]
> what did youtube change? just curious

I'm not sure, haven't got the time to investigate. My guess is that youtube is trying to get rid of the old VTT captions endpoints to prefer their innertube (JSON API) endpoint instead.

**Comment by llsc12** [comment]
How could I access the json endpoints for captions? Just curious and want to try it out.

**Comment by unixfox** [comment]
> How could I access the json endpoints for captions? Just curious and want to try it out.

https://github.com/iv-org/invidious/issues/2564
