### ISSUE TITLE
[Feature request] expose an MRSS feed for Roku consumption

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#3345]
**Is your feature request related to a problem? Please describe.**
The official Youtube App on a Roku TV is plagued with Ads. There might be a low-hanging fruit way to use Invidious.

**Describe the solution you'd like**
Roku support creating channels from just a feed.

[Feed format specifications](https://developer.roku.com/en-ca/docs/specs/direct-publisher-feed-specs/feed-spec.md)

- [Direct Publisher feed format (JSON)](https://developer.roku.com/en-ca/docs/specs/direct-publisher-feed-specs/json-dp-spec.md)
  - Roku provides a sample of this feed [here](https://devtools.web.roku.com/samples/roku-developers-feed-v1-rdp.json)
- [MRSS Feed Specification](https://developer.roku.com/en-ca/docs/specs/direct-publisher-feed-specs/mrss-dp-spec.md) which is based on 
  - [MRSS 1.5.1 specification](http://www.rssboard.org/media-rss)
  - [RSS 2.0 specification](http://www.rssboard.org/rss-specification)
 
Once a feed that complies with one of the two specs can be shipped, a Roku channel can be created out of it without any coding.

Since Invidious has some RSS capability (as far as I can tell) this looks like a good opportunity to provide an MRSS.

**Describe alternatives you've considered**

Writing an app for Roku, in BrightScript... which is not very appealing, and will require continuous maintenance.

**Additional context**
Creating a Roku channel is merely providing a feed url.

<img width="400" alt="Screen Shot 2022-10-14 at 1 06 43 PM" src="https://user-images.githubusercontent.com/17722782/195903002-afce5ec4-85e7-4bf8-80b1-4efc4b042bff.png">

**Comment by MintMain21** [comment]
This is a very interesting proposition. 

I've never heard of any Private Frotend/Client getting proper Roku support, but it's an exciting proposition all the same.

**Comment by iBicha** [comment]
This could be more complicated than what I described. Unpublished channels will need manual refresh from the feed (by clicking a button on the Roku Dev Dash) rendering this useless.

<img width="821" alt="Screen Shot 2022-10-22 at 12 21 54 AM" src="https://user-images.githubusercontent.com/17722782/197318884-3d278a7f-a0a2-47f3-b6f5-bd505fedb187.png">

If Invidious publishes a channel, it will probably be shutdown for ToS pretty quickly.

I guess the longer route is to build a BrightScript app, which would call the Invidious APIs, but that's a bit more effort.

**Comment by OkyDooky** [comment]
I bought a Raspberry Pi (cost more than a Roku, sadly) because it had a web browser. I could use Invidious for YT and other sites for streaming more premium content for free. The only thing that doesn't work, ironically, is The Roku Channel's website (claims it doesn't support Linux browsers).
It would be really cool to not need fully-separate DIY device to use YT privately. Plus, it could be recommended to existing owners of Roku devices. One major benefit is of course being able to use a remote for navigation instead of a Smartphone As A Mouse via KDE Connect.

**Comment by iBicha** [comment]
There's probably not a good way to create any direct publisher channel without it getting shutdown.
Closing for now.
