### ISSUE TITLE
[Bug] Missing hash key: "browseEndpoint" (KeyError)

### ISSUE THREAD

**Issue by DalekDave** [iv-org/invidious#3349]
**Additional context**
 - Browser (if applicable):  Chrome on Windows
 - OS (if applicable): Ubuntu 20.04

Title: `Missing hash key: "browseEndpoint" (KeyError)`
Date: `2022-10-18T05:36:46Z`
Route: `/watch?v=JcTWMP7j8vM`
Version: `2022.10.12-3b39b8c7 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "browseEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:102:10 in 'dig'
  from /usr/share/crystal/src/json/any.cr:215:3 in 'get_browse_id'
  from src/invidious/videos.cr:861:34 in 'parse_related_video'
  from src/invidious/videos.cr:1011:9 in 'parse_video_info'
  from src/invidious/videos.cr:926:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:1129:10 in 'fetch_video'
  from src/invidious/videos.cr:1109:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:36 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment]
On which instance did you get this error?

**Comment by DalekDave** [comment]
I got this error on https://media.dalek.zone but I had to stop the Invidious service and disable it temporarily because I have Mastodon and Peertube on the same server, and Invidious seems to need special attention during installation to avoid co-existence problems. I am going to visit the Invidious chat room on Matrix in the next few days to figure out how to troubleshoot the situation.

Sorry I posted this rather incomplete bug report. I was in a hurry for work when I did so, but wanted to "capture" the info. I'm attaching a couple of screenshots showing the full page output.

By the way, Invidious is REALLY cool, and I really like it. I will definitely figure out how to work around the current problems. Please post back any questions. I can recover logs, etc.

![invidious-bug-screenshot1](https://user-images.githubusercontent.com/64964084/196513939-364146a0-b0f3-485c-a9a3-f3f86a85ccb2.JPG)

![invidious-bug-screenshot2](https://user-images.githubusercontent.com/64964084/196513972-939c5d5c-3d05-42b1-aa11-36f4211e1fcb.JPG)

**Comment by DalekDave** [comment]
For your info, I installed Invidious using the installer script at: https://github.com/tmiland/invidious-installer

So I did not take any special action for Imagemagick (I saw some info about that, but the 'alternative' installation steps pertain to Ubuntu 18.04).

I also set a cronjob to restart Invidious every 60 minutes, as I saw that recommended in the nice documentation at https://docs.invidious.io/installation/

I'll be back to contribute more info to this bug report over the coming days.

**Comment by TheFrenchGhosty** [comment]
Another ID that does break on all instances (including yewtu.be): U6EqIzLCvZQ
