### ISSUE TITLE
[Enhancement] Support Handles (@username URLs)

### ISSUE THREAD

**Issue by Macic-Dev** [iv-org/invidious#3358]
YouTube is introducing [handles](https://blog.youtube/news-and-events/introducing-handles-a-new-way-to-identify-your-youtube-channel/). They will function similarly to [custom URLs](https://support.google.com/youtube/answer/2657968) and appear next to the channel's name in the comments, search results, etc. They are visible under the `customUrl` property in the YouTube API, meaning it should be possible to implement. Every channel will have a handle by November 14th and large channels have already claimed theirs. Since this is such a huge change, Invidious should implement it.

**Comment by SamantazFox** [comment]
E.g: https://youtube.com/@Toujours_Thomas
