### ISSUE TITLE
[Bug] Cannot watch videos on PS4 Browser

### ISSUE THREAD

**Issue by k2helix** [iv-org/invidious#3363]
**Describe the bug**
When using any instance of Invidious on the playstation browser to watch a video, it keeps loading and a dialog saying "The media could not be loaded, either because the server or network failed or because the format is not supported" appears. This is weird as in some instances I'm able to watch YouTube streams but not videos

**Steps to Reproduce**
1. Go to any instance
2. Click on any video
3. Attempt to play it
4. See the error

**Additional context**
 - Browser (if applicable): PS4 Browser
 - OS (if applicable): whatever the ps4 os is called

**Comment by unixfox** [comment]
Did you try with DASH enabled?

**Comment by k2helix** [comment]
Just tried witb DASH, same happens

**Comment by unixfox** [comment]
Which instances did you try? Which videos did you try?

**Comment by k2helix** [comment]
Happens on every instance on any video

**Comment by unixfox** [comment]
Please give the instances and the video ID tested. We cannot proceed further without them, we want to be able to reproduce the same issue that you had.

**Comment by k2helix** [comment]
Instances:
- https://invidious.snopyta.org/
- https://yewtu.be/
...and some more
Video:
https://www.youtube.com/watch?v=J7Ssyrr4HZU
Note that this specific video is age restricted, but it happens for every video I clicked on the main page too

**Comment by RadoslavL** [comment]
I can't replicate the issue on a webkit-based browser. If this issue currently still exists, it's likely a bug that Sony introduced in the PS4 browser.
