### ISSUE TITLE
[Question] Server Configuration not completely reflected in UI preferences

### ISSUE THREAD

**Issue by itguy327** [iv-org/invidious#3366]
**Describe the bug**
I've added config settings for quality and other behaviors in my docker-compose and when I clear my browser cache on multiple devices my expectation is that these settings are applied. I can't verify if they are actually applied except for the Popular tab being disabled. Also, is there a way to remove Popular/Trending server wide?

Thank you for this project, it is amazing!

      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        pool_size: 10000
        use_quic: false
        force_resolve: ipv4
        popular_enabled: false
        statistics_enabled: false
        captcha_enabled: false
        channel_threads: 5
        channel_refresh_interval: 300m
        dark_mode: true
        disable_proxy: false
        comments: ["youtube", ""]
        quality: dash
        quality_dash: best
        local: true
        feed_menu: ["Subscriptions", "Playlists", "", ""]
        default_home: "Subscriptions"
        banner: 
        domain:

**Comment by unixfox** [comment]
Make sure to remove cookies too. In order to be sure test your instance in incognito mode.

**Comment by itguy327** [comment]
> Make sure to remove cookies too. In order to be sure test your instance in incognito mode.

Thanks. I did that for sure. I tried on my desktop, mobile and android tv box. Is it possible that the preferences won't reflect those server configs.

Essentially I am looking to have everything controlled at the server level as defaults, which I'm pretty sure is the intent.

Thanks for adjusting my report.

**Comment by unixfox** [comment]
You didn't respect the indentation and look you missed to include `default_user_preferences`: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L507

Closing as it's an user error.

**Comment by itguy327** [comment]
> You didn't respect the indentation and look you missed to include `default_user_preferences`: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L507
> 
> Closing as it's an user error.

Thank you for the help. I'm still getting used to yaml :-)
