### ISSUE TITLE
Feature Request: Live Now notification from subscriptions

### ISSUE THREAD

**Issue by tmiland** [iv-org/invidious#337]
Hi,

would it be possible to add a feature, that if a video is live when the feed is updated/fetched, to show a notification of some sort?

Not sure how, but maybe distinguish the live videos, like placing them above the regular videos in "feed/subscriptions", and maybe light up the notification bell with a red colour (bg?) if not yet visited "feed/subscriptions"? 🤔

Just a thought. 😃

**Comment by dimqua** [comment]
For reference: #195.

**Comment by omarroth** [comment]
It seems to me that this is a duplicate of #195, unless different functionality is being requested. 

I just pushed 5bf3c284362905a02406a71fc0cbc396c782c426 which adds this indicator:
![image](https://user-images.githubusercontent.com/14208607/53199755-88c67080-35e5-11e9-8537-edcf88793dd1.png)

To search results, and I'm planning on adding the same to subscription feeds.

**Comment by omarroth** [comment]
Added with f0658bbd092af23e097ac52a1587688ec9ee17df.

**Comment by omarroth** [comment]
They appear to be missing from new uploads, so I'd like to investigate a little more before this is closed.
