### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FreeBornAngel** [iv-org/invidious#3379]
**Describe the bug**

Videos not being presented.

**Steps to Reproduce**

**Logs**

No errors in console.

**Screenshots**

![image](https://user-images.githubusercontent.com/18445737/199340781-813157d1-30c1-4692-8f83-a8f7d135d0f0.png)

![image](https://user-images.githubusercontent.com/18445737/199340855-cba5767d-179a-4e05-b61b-300d6c4b16f8.png)

**Additional context**
It just quit working.
I noticed it yesterday.
 - Browser (if applicable):  brave
 - OS (if applicable): linux mint
 - 
--> I'd don't want to go back to utub.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3371

**Comment by FreeBornAngel** [comment]
Thanks, I guess I missed that looking for it.
