### ISSUE TITLE
[Bug] Sorting by oldest or popular on channel pages returns same page as default

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#3386]
**Describe the bug**
Clicking the *oldest* or *popular* links on a channel page returns the same results as the default sort.

Was only about a couple months prior that I'd used that feature on Invidious so I know it was working relatively recently. However I'm not sure if the bug is some side effect of issue #3371 (since only the first page of channel results have been listed while that bug was active) or related to some Youtube removal of the feature (as I read some old resurfaced [news](https://old.reddit.com/r/youtube/comments/ymoyx3/youtube_confirms_that_it_has_removed_the_sort_by/) that Youtube removed the oldest sort feature from their site).

**Steps to Reproduce**
1. Go to any channel and on the right click the *oldest* or *popular* link to sort the channel.
2. Observe the same default results are returned.

**Additional context**
Tried on both snopyta (2022.11.02-09942dee) and yewtu.be (2022.11.11-af99630) instances.

**Comment by unixfox** [comment]
Bug due to https://github.com/iv-org/invidious/issues/3371, closing this issue.
