### ISSUE TITLE
[Question] Bash `channels.sql`: Permision denied

### ISSUE THREAD

**Issue by witheredwave** [iv-org/invidious#3391]
**Describe the bug**
`-bash: /home/invidious/invidious/config/sql/channels.sql: Permision denied`

**Steps to Reproduce**
1. Go to 'systemctl enable --now postgresql
sudo -i -u postgres
psql -c "CREATE USER kemal WITH PASSWORD 'kemal';" # Change 'kemal' here to a stronger password, and update `password` in config/config.yml
createdb -O kemal invidious'

psql invidious kemal < /home/invidious/invidious/config/sql/channels.sql

-bash: /home/invidious/invidious/config/sql/channels.sql: Permiso denegado

**Additional context**
 - Browser (if applicable): Librewolf
 - OS (if applicable): PopOS

**Comment by unixfox** [comment]
No actual info on what have been done in order to get this issue... Closing

**Comment by SamantazFox** [comment]
Reopening, the content was in the message, but OP forgot to remove HTML comments from template (`<!--` and `-->`)

**Comment by SamantazFox** [comment]
@witheredwave Try to use `./invidious --migrate` (from the invidious home folder, as the invidious use)
This deployment method doesn't require using the legacy .sql files.

**Comment by TheFrenchGhosty** [comment]
Documentation updated https://github.com/iv-org/documentation/pull/306
