### ISSUE TITLE
No "Next page" button in channel videos -- can only see last 30 published

### ISSUE THREAD

**Issue by salperinlea** [iv-org/invidious#3393]
Title more or less says it all. There is no "Next page" button on any channel's videos. I cannot scroll back beyond the 30 most recent videos. I can reach said videos just fine if I search the name of the channel and scroll through search results, but not from the page for the channel itself. 

This effects all instances and is not browser specific.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3371
