### ISSUE TITLE
Raspberry pi docker build failing

### ISSUE THREAD

**Issue by bigOconstant** [iv-org/invidious#3397]
**Describe the bug**

**Steps to Reproduce**
1. On a raspberry pi running raspbian 64 bit with docker installed 
2. Clone Invidious `git clone https://github.com/iv-org/invidious.git`
3. `cd invidious`
4. `docker build -f docker/Dockerfile.arm64 . `
5. See error, seems to change from time to time.

`Failed to clone https://github.com/crystal-lang/crystal-sqlite3.git` or

`Failed to clone https://github.com/will/crystal-pg.git`

**Comment by unixfox** [comment]
Please post the full logs.

**Comment by bigOconstant** [comment]
> Please post the full logs.

It fails on a different git clone everytime. I'm not sure whats going on. Some kinda arm specific alpine problem?

```
USERNAME@raspberrypi:~/temp/invidious $ docker build -f docker/Dockerfile.arm64 .
Sending build context to Docker daemon  29.58MB
Step 1/31 : FROM alpine:3.16 AS builder
 ---> 2b4661558fb8
Step 2/31 : RUN apk add --no-cache 'crystal=1.4.1-r0' shards sqlite-static yaml-static yaml-dev libxml2-dev zlib-static openssl-libs-static openssl-dev musl-dev
 ---> Using cache
 ---> fd6f62818f42
Step 3/31 : ARG release
 ---> Using cache
 ---> ddfa2527c242
Step 4/31 : ARG disable_quic
 ---> Using cache
 ---> b07462419c24
Step 5/31 : WORKDIR /invidious
 ---> Using cache
 ---> ca45fd3db10e
Step 6/31 : COPY ./shard.yml ./shard.yml
 ---> Using cache
 ---> e43cae87891a
Step 7/31 : COPY ./shard.lock ./shard.lock
 ---> Using cache
 ---> c2ac6273fc1b
Step 8/31 : RUN shards install --production
 ---> Running in fd4e963c29bd
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/iv-org/protodec.git
Fetching https://github.com/iv-org/lsquic.cr.git
Fetching https://github.com/athena-framework/negotiation.git
Failed to clone https://github.com/kemalcr/kemal.git
The command '/bin/sh -c shards install --production' returned a non-zero code: 1
USERNAME@raspberrypi:~/temp/invidious $ 

```

As soon as I get a minute i'll try to write a debian dockerfile. I'm just not that familiar with crystal and it's build tools.

**Comment by bigOconstant** [comment]
I'm getting the same thing in podman. So it must be a problem with alpine linux on arm.

**Comment by SamantazFox** [comment]
@bigOconstant could you try the following?

Here, use `alpine:edge`
https://github.com/iv-org/invidious/blob/516efd2df3f7d242c2d1df416053b4991a554116/docker/Dockerfile.arm64#L1

And here use `crystal=1.6.2-r0`
https://github.com/iv-org/invidious/blob/516efd2df3f7d242c2d1df416053b4991a554116/docker/Dockerfile.arm64#L2

**Comment by bigOconstant** [comment]
Hi @SamantazFox Thanks for getting back to me. I however get the same error. 

for now as a workaround I'm building and running invidious on my amd machine and connecting to my raspberry pi's postgres instance. 

Atleast I can access all my old subscriptions. 

I'm not sure why it's failing on a random github package. 

```
Step 8/31 : RUN shards install --production
 ---> Running in 2523c4af2b3c
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/iv-org/protodec.git
Fetching https://github.com/iv-org/lsquic.cr.git
Fetching https://github.com/athena-framework/negotiation.git
Failed to clone https://github.com/crystal-lang/crystal-sqlite3.git
The command '/bin/sh -c shards install --production' returned a non-zero code: 1
```
