### ISSUE TITLE
[Question] Any way to donate that isn't crypto currency?

### ISSUE THREAD

**Issue by accessiblepixel** [iv-org/invidious#3401]
Hi!

I realise that Invidious is a small team, and I tried to make a small donation through the sponsor link, but that took me to a page with crypto currency hashes and I don't have any crypto currencies so would find it a bit difficult to make a donation.

Is there another way to make a small contribution (other than trying to leave good bug reports when I can, of course!)

Thank you.

**Comment by SamantazFox** [comment]
Hello!

Sorry, we don't accept anything else than cryptos for legal reasons :/

To receive euro/dollars/etc.. donations, it would require us to register a non-profit organization (like an US "501(c) organization" or a french "association loi 1901") and to declare those donations. Alternatively, we could join a fiscal host like OpenCollective.

In either case, we don't have the time to do so.

**Comment by accessiblepixel** [comment]
Ahh, okay.

Thank you for taking the time out to reply! I can understand the "administrative burden" to make those registrations. I've been following the bug for the channel video listings and would have liked to have made a small contribution.

Do the invidious developers have a charitable organisation that they support that a donation may be made on your "behalf" so to speak? I know it's not the same as a direct contribution though.

Other than that, all I can offer is my heartfelt thanks for the continuing work that you all do on the project to give us all an alternative unencumbered YouTube UI... and attempting to leave good bug reports when I can, of course!

Hope you and yours and the team is doing well.

Kind regards,
Jessica

**Comment by k-sareen** [comment]
I would also love to donate but don't have crypto assets. I don't know if you've explored this option, but I've seen some devs use Buy Me a Coffee [1], Ko-Fi [2], and more recently GitHub Sponsors [3] to get donations. Do these bypass the registration requirement? Or is the issue with these that Invidious is an organization instead of a solo developer, and so which donations go where is a bit nebulous?

Thank you for all your work, specially with the new shenanigans from YT.

\[1]: https://www.buymeacoffee.com/
\[2]: https://ko-fi.com/
\[3]: https://github.com/sponsors

**Comment by SamantazFox** [comment]
@accessiblepixel

> Do the invidious developers have a charitable organisation that they support that a donation may be made on your "behalf" so to speak? I know it's not the same as a direct contribution though.

To be relevant with invidious' own goals, you can donate to an organization that fights for privacy and digital rights. For instance (non-exhaustive list, maybe adapt to what's local to you):
 - "La Quadrature du Net" (France)
 - "Open Rights Group" (U.K)
 - "Electronic Frontier Foundation" (U.S)
 
You can also donate to the people that host the public (or semi-public) instances too, as they're the ones with the most expenses! (The main 4 websites don't require that much power, so the current crypto donations are enough for that ^^).

As for myself, that'd be some local LGBT, Anti-abortion or other Human rights organization that you find relevant!

> Other than that, all I can offer is my heartfelt thanks for the continuing work that you all do on the project to give us all an alternative unencumbered YouTube UI... and attempting to leave good bug reports when I can, of course!

That's the intention that matters ^^
And mind that your kind messages are already paying me in happiness :D Thanks a lot!

---

@k-sareen 

> I would also love to donate but don't have crypto assets.

Yes, I completely understand that you don't want to deal with cryptocurrencies (I don't like them either personally).

> I've seen some devs use Buy Me a Coffee, Ko-Fi, and more recently GitHub Sponsors to get donations. Do these bypass the registration requirement? Or is the issue with these that Invidious is an organization instead of a solo developer, and so which donations go where is a bit nebulous?

Note that while we call "invidious" an organization, it has no legal ground (we're held together by the power of our our internet connections!). So while we can't receive donations in that name we can individually sign-up to the services you mentioned.

And yes, I've considered those, as well as liberapay, too. But that's still quite complex in terms of paperwork I'd have to do. In essence, I'd have to declare this income on my tax form, and I'd have to manage the potential issues. I don't have the time nor the willingness for that xD

> Thank you for all your work, specially with the new shenanigans from YT.

Thanks for your kind words <3

**Comment by Nehwu** [comment]
@accessiblepixel @k-sareen 
I would suggest using a cryptocurrency ATM. A lot of them can be founded here: https://coinatmradar.com/
It just means you would put into it cash and the address of Invidious'  cryptocurrency wallets. It's really simple to use, the only downside are the fees, which can be up to 10%. Still, I thought this might help to anybody wanting to donate to the project :)

**Comment by TheFrenchGhosty** [comment]
Hello, @accessiblepixel @k-sareen 

As explained by @SamantazFox Invidious by itself doesn't accept donation in anything other than cryptocurrencies for legal/administrative reason (this might change at a later date but not anytime soon).

However, as mentioned by Samantaz, most [team members](https://invidious.io/team/) accept donations directly. If you do donate this way do note that this won't necessarily be "for" Invidious (but more for the FOSS work of the person in general).

As for donating to an organization we support, it was agreed between Perflyst and me to donate everything the project has (in case Invidious ever dies) to PeerTube/Framasoft, so this is what we would recommend if you don't want to donate cryptocurrencies and/or donate to a specific team member: https://support.joinpeertube.org/en/
