### ISSUE TITLE
[Bug]I couldn't set video quality to 144p

### ISSUE THREAD

**Issue by UserChristie** [iv-org/invidious#3404]
Description:
I tried to set the video quality to 144p but the worst quality I could obtain through all the manipulations in the settings was 256p.

Ways approached and Observations:
> 01.(Preferred Video Quality = Small) + (Preferred DASH Video Quality = Worst)
Result = 'Medium' highlighted in blue

> 02.(Preferred Video Quality = Small) + (Preferred DASH Video Quality = 144p)
Result = 'Medium' not highlighted but shown as topmost option

> 03.(Preferred Video Quality = Small) + (Preferred DASH Video Quality = Auto)
Result = 'Medium' highlighted in blue

> 04.(Preferred Video Quality = DASH) + (Preferred DASH Video Quality = Worst)
Result = 'Auto' highlighted in white

> 05.(Preferred Video Quality = DASH) + (Preferred DASH Video Quality = 144p)
Result = 'Auto' highlighted in white and 256p highlighted in blue

> 06.(Preferred Video Quality = DASH) + (Preferred DASH Video Quality = 144p) + (Proxy Videos = Ticked)
Result =  256p highlighted in blue

User's Specifications:
Browser: Firefox
OS: Android
Instance: yewtu.be

**Comment by UserChristie** [comment]
Instance: yewtu.be

**Comment by unixfox** [comment]
is 144p even available for the video?

**Comment by UserChristie** [comment]
Invidious link:
https://yewtu.be/watch?v=u20D_nUhc-Q

Youtube link:
https://m.youtube.com/shorts/u20D_nUhc-Q

I think 144p for the above link was unavailable because the video belonged to 'Shorts' category (for which I now found that video quality is not mentioned on youtube) and I made mistake by applying the changes just for this particular video.

I tried the last setting to several other videos and found 144p was available.

Sorry for bothering and thanks for the response.

**Comment by unixfox** [comment]
> Similar problem here? https://yewtu.be/watch?v=TJiKnT7sy9Y only shows 1080p
> 
> YouTupe has 1440p https://www.youtube.com/watch?v=TJiKnT7sy9Y

Not the same issue, invidious doesn't support webm and for some videos only webm format will offer more than 1080p.
