### ISSUE TITLE
[Bug] Invalid Int32: "@bordersecurityaustralia5634" (ArgumentError)

### ISSUE THREAD

**Issue by RiversideRocks** [iv-org/invidious#3411]
**Describe the bug**
Upon searching "border security" on yewtu.be, this error appears.

Title: `Invalid Int32: "@bordersecurityaustralia5634" (ArgumentError)`
Date: `2022-11-19T18:27:46Z`
Route: `/search?q=border+security`
Version: `2022.11.17-e726eaf @ master`

<details>
<summary>Backtrace</summary>
<p>
   
Invalid Int32: "@bordersecurityaustralia5634" (ArgumentError)
  from /usr/lib/crystal/core/int.cr:957:11 in 'to_i32'
  from src/invidious/helpers/utils.cr:176:3 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:56:7 in 'search'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'

</p>
</details>

**Steps to Reproduce**
1. Use yewtu.be
2. Search border security

**Logs**

**Screenshots**

**Additional context**
Tor Browser
yewtu.be is using `2022.11.17-e726eaf`

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/3394
