### ISSUE TITLE
[Bug] Live-streams do not appear on subscription feed, only when manually going into the channel which you are already subscribed to.

### ISSUE THREAD

**Issue by emitho** [iv-org/invidious#3417]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by SamantazFox** [comment]
Closing as it's already been reported in #3371. We're working on a fix!

**Comment by emitho** [comment]
Thanks!Enviado desde mi iPhoneEl 20 nov 2022, a la(s) 19:58, Samantaz Fox ***@***.***> escribió:﻿
Closing as it's already been reported in #3371. We're working on a fix!
