### ISSUE TITLE
[Feature request] Search in Channel page, click to load more videos 

### ISSUE THREAD

**Issue by lothar-cell** [iv-org/invidious#3429]
**Is your feature request related to a problem? Please describe.**
There's no option to search for specific videos on a channel page, nor is there to load more videos.

**Describe the solution you'd like**
A search bar on the channel page and either auto load more videos or numbered hyperlinks (1 - 2 - 3, like on forums).

**Describe alternatives you've considered**
piped.video 

**Additional context**
<img width="1288" alt="Screenshot 2022-11-23 at 10 01 13" src="https://user-images.githubusercontent.com/2356354/203507178-bc566d8b-44a5-4e52-8291-54034b8abfc2.png">
<img width="1363" alt="Screenshot 2022-11-23 at 9 56 36" src="https://user-images.githubusercontent.com/2356354/203507212-40803797-af8d-4a91-a951-ad046dd4ad5a.png">

**Comment by unixfox** [comment]
First feature request: https://github.com/iv-org/invidious/issues/2344
Second feature request: https://github.com/iv-org/invidious/issues/3371

Closing due to duplicate
