### ISSUE TITLE
Resume playing

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#343]
Partially watched videos can be marked differently, and you should be able to continue watching them.

**Comment by elypter** [comment]
it would also be very helpful if it automatically asks you if you want to continue watching when reloading a video.

**Comment by dimqua** [comment]
NewPipe recently got this feature!

**Comment by elypter** [comment]
related #494

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/2024?

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/2024
