### ISSUE TITLE
[Feature request] Armv7 docker image

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#3433]
**Is your feature request related to a problem? Please describe.**
Armv7 docker image to run on Raspbian OS (RPI)

**Describe the solution you'd like**
Provide an a docker image for armv7, similar to 
- quay.io/invidious/invidious:latest
- quay.io/invidious/invidious:latest-arm64

This is to bring Invidious to Raspberry PI Raspbian OS.

**Describe alternatives you've considered**
N/A

**Additional context**
(in particular, to the [Tipi appstore](https://github.com/meienberger/runtipi-appstore/tree/master/apps/invidious))

**Comment by unixfox** [comment]
Please read this FAQ: https://github.com/iv-org/invidious/issues/361#issuecomment-881047911
