### ISSUE TITLE
[Bug] Wrong tiles in story board

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#3440]
**Describe the bug**
/videos/:id returns wrong storyboardHeight

**Steps to Reproduce**

1. `/api/v1/videos/UhbixyxgsiU`
2. returns 3 storyboards. The second storyboard returns 

```
         "url":"/api/v1/storyboards/UhbixyxgsiU?width=60&height=45",
         "templateUrl":"https://i.ytimg.com/sb/UhbixyxgsiU/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjBmdybBg%3D%3D&sigh=rs%24AOn4CLBujIIzxs6-nY318GTi_j8tt52HAw",
         "width":60,
         "height":45,
         "count":74,
         "interval":2000,
         "storyboardWidth":10,
         "storyboardHeight":10,
         "storyboardCount":1
```

The image is actually 10x8, not 10x10, making the storyboardHeight field wrong

**Logs**

**Screenshots**
<img width="599" alt="Screen Shot 2022-11-27 at 6 44 50 PM" src="https://user-images.githubusercontent.com/17722782/204166162-e9ed176d-07f3-4bda-ad8a-28080f3e93ee.png">

**Comment by iBicha** [comment]
I see many more cases of this. 10x5 reported as 10x10
```
         "url":"/api/v1/storyboards/Gb4ghMzz0a4?width=25&height=45",
         "templateUrl":"https://i.ytimg.com/sb/Gb4ghMzz0a4/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgicmuCbBg%3D%3D&sigh=rs%24AOn4CLA7AtTjMrWA77A6PaTdlV8QL6jxNg",
         "width":25,
         "height":45,
         "count":48,
         "interval":1000,
         "storyboardWidth":10,
         "storyboardHeight":10,
         "storyboardCount":1
```
<img width="253" alt="Screen Shot 2022-11-27 at 8 04 49 PM" src="https://user-images.githubusercontent.com/17722782/204170944-2658d288-a327-46a4-a1fa-2206dc6e8c5d.png">

**Comment by SamantazFox** [comment]
Oh, that's interesting! The code always assumed 10x10, but seems like things have changed (probably because of shorts and other newer formats?).

**Comment by SamantazFox** [comment]
Actually, it seems normal?

The `storyboardWidth` and `storyboardHeight` represent the maximum amount of storyboards you can get on each axis per image. But the last image in the set (or the only image, in case of short videos) may have less than that!

Here is the output for a long video (livestream):
```json
{
	"videoId": "etyCb38ag-s",
	"storyboards": [
		{
			"url": "/api/v1/storyboards/etyCb38ag-s?width=48&height=27",
			"templateUrl": "https://i.ytimg.com/sb/etyCb38ag-s/storyboard3_L0/M$M.jpg",
			"width": 48,
			"height": 27,
			"count": 100,
			"interval": 0,
			"storyboardWidth": 10,
			"storyboardHeight": 10,
			"storyboardCount": 1
		},
		{
			"url": "/api/v1/storyboards/etyCb38ag-s?width=80&height=45",
			"templateUrl": "https://i.ytimg.com/sb/etyCb38ag-s/storyboard3_L1/M$M.jpg",
			"width": 80,
			"height": 45,
			"count": 1414,
			"interval": 10000,
			"storyboardWidth": 10,
			"storyboardHeight": 10,
			"storyboardCount": 15
		},
		{
			"url": "/api/v1/storyboards/etyCb38ag-s?width=160&height=90",
			"templateUrl": "https://i.ytimg.com/sb/etyCb38ag-s/storyboard3_L2/M$M.jpg",
			"width": 160,
			"height": 90,
			"count": 1414,
			"interval": 10000,
			"storyboardWidth": 5,
			"storyboardHeight": 5,
			"storyboardCount": 57
		}
	],
}
```

**Comment by iBicha** [comment]
@SamantazFox your logic makes sense (I guess I was mislead with some of the 1 pagers)
So after all it's like you said, only shorts are affected

**Comment by iBicha** [comment]
So the format is technically correct? Thanks for clarifying I'll close the issue - please reopen if there's some edge case to it
