### ISSUE TITLE
Television Mode

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#345]
It would be great to have a mode that automatically plays videos from your subscription as an alternative to tv if you just want some entertainment without having to interact but dont want to watch stupid shit.

**Comment by omarroth** [comment]
Would it make sense to implement this as a playlist? So e.g. `/playlist?list=IVS${USER_TOKEN}` would show the same contents as your RSS feed.

**Comment by alexgleason** [comment]
I don't really understand #114, but I agree that viewing your subscriptions like a playlist would be a great feature!

Maybe something like: `/feed/subscriptions/play`

The rudimentary form would be just a reverse-chronological playlist of all videos in your subscriptions feed. You could slap a "Play" button on that page (in `/feed/subscriptions`). It would make sense in the UI.

In a more advanced version (down the line), it could be a configurable "smart" playlist where it does things like showing you unviewed videos first. Etc.

**Comment by elypter** [comment]
i think that would be a good way to implement this in the beginning. later it would be cool to be able to have a more random order, being able to show only new videos and allow to skip videos but save them for watching later.

**Comment by nathgit** [comment]
> I don't really understand #114, but I agree that viewing your subscriptions like a playlist would be a great feature!

I don't heat #114 either. What is that?
