### ISSUE TITLE
[Bug] Notifications: True

### ISSUE THREAD

**Issue by TernaryC** [iv-org/invidious#3452]
I've decided to submit my personal favorite inconsequential bug. This is low priority to be sure.

The notifications bell will occasionally show the number of notification as "TRUE" instead of any actual number. I have not managed to find a consistent reason as to why.
I can confirm this occurring on multiple instances (vid.puffyan.us and yewtu.be at the least).

![image](https://user-images.githubusercontent.com/36998960/204741234-38633684-cb59-46a7-989f-cd9d45f298ca.png)

Browser: Mozilla Firefox 107.0
OS: Linux Mint 20.3 Cinnamon

**Comment by unixfox** [comment]
Notifications are forcibly disabled on yewtu.be.

**Comment by SamantazFox** [comment]
Oh, right, thanks! I've already seen that bug occurring, but completely forgot to open an issue!

**Comment by Zero3K** [comment]
I have reproduced it by force closing the browser when it shows a number, running it, restoring the tabs, and viewing a restored tab that has an Invidious page in it.

**Comment by DanielRayson** [comment]
Not sure if this is the issue, but looking at the source code I see a function `function update_ticker_count()` that is setting a variable `const notification_count = helpers.storage.get(STORAGE_KEY_STREAM);` to the value of something that isn't the notification count...

I suspect the correct code would be something more like `let notification_count = helpers.storage.get(STORAGE_KEY_NOTIF_COUNT) || 0;`

**Comment by Zero3K** [comment]
Bump
