### ISSUE TITLE
Auto Fullscreen Option

### ISSUE THREAD

**Issue by Basti77** [iv-org/invidious#3461]
Would it be possible to add an option in the settings that automatically switches the video to fullscreen playback? 
that would be perfect for playback on the browser on the TV.

**Comment by unixfox** [comment]
not possible to do it automatically, see https://stackoverflow.com/a/19355528

**Comment by Basti77** [comment]
The article is about the fullscreen of the browser. 
the browser of the LG TV is smart enough to play the page in full screen. there is no Chrome running on the TV.
I mean the player's. You ALWAYS have to click in the bottom right corner and that's very awkward with a remote control.

**Comment by unixfox** [comment]
The different browsers probably work the same way.
