### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by ghaemaghaey** [iv-org/invidious#3465]
<hey guys si really thankful for you project its helped me alot 
but we need a feature 
a next page bottun in evey acount homepage 
i really thankfull 
have a nice one 
ghh35181

**Comment by ghaemaghaey** [comment]
add persian language to translate section

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3371

**Comment by SamantazFox** [comment]
> add persian language to translate section

Regarding persian, it's already available: https://hosted.weblate.org/projects/invidious/translations/fa/
