### ISSUE TITLE
[Bug] Auto generated captions not being shown

### ISSUE THREAD

**Issue by theodrim** [iv-org/invidious#3469]
**Describe the bug**
auto-generated does not get displayed

**Steps to Reproduce**
1. Open https://yt.funami.tech/api/v1/captions/OHKKcd3sx2c?label=English%20(auto-generated)

**Logs**
```
WEBVTT
Kind: captions
Language: en
```
**Additional context**
Inspecting same video via piped, captions requested being served as ttml as highlight by this issue - https://github.com/iv-org/invidious/issues/3455

**Comment by SamantazFox** [comment]
Yes, this is the same issue as #3455
