### ISSUE TITLE
what happened to kgg2m7yk5aybusll.onion?

### ISSUE THREAD

**Issue by bruceleerabbit** [iv-org/invidious#3483]
Does anyone know if there is an onion v3 host that replaces kgg2m7yk5aybusll.onion?

(yes, I’m aware that there are other onion invidious instances, but I’m interested in kgg2m7yk5aybusll.onion specifically).

**Comment by potatoesAreGod** [comment]
Doesn't seem like there's any replacement at all. I spent some time looking around on the web, however, I couldn't find anything. Unless you know who created it there's nothing to do.

I wouldn't care too much, onion domains tend to come and go. To be honest I don't think we will ever see it again.

**Comment by SamantazFox** [comment]
Sorry, we can't help here, especially given that it looks like this domain never was in the public list.
