### ISSUE TITLE
[Bug] Closed stream (IO::Error)

### ISSUE THREAD

**Issue by AzrailaOuO** [iv-org/invidious#3487]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Please help ;^;
The server of individious' server is down, please fix it as soon as possible, thank you

**Comment by AzrailaOuO** [comment]
Nevermimd

**Comment by AzrailaOuO** [comment]
Nevermind

**Comment by AzrailaOuO** [comment]
Title: `Closed stream (IO::Error)`
Date: `2022-12-11T22:58:48Z`
Route: `/search?q=fnf`
Version: `2022.12.07-abbe84cb @ (HEAD detached from origin/master)`

<details>
<summary>Backtrace</summary>
<p>
   
```
Closed stream (IO::Error)
  from /usr/share/crystal/src/openssl/ssl/socket.cr:144:5 in 'flush'
  from /usr/share/crystal/src/io/buffered.cr:227:5 in 'close'
  from src/invidious/yt_backend/connection_pool.cr:43:9 in '_post_json'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

Here's the bug

**Comment by unixfox** [comment]
What's the website that you used?

**Comment by AzrailaOuO** [comment]
> What's the website that you used?

I used individious fdn fr

**Comment by SamantazFox** [comment]
I'm reopening, because it's quite an important and legitimate issue.
The multiple PRs opened recently (#3489, #3490, #3491) is a sign, and I've also seen that problem multiple times by myslef.

**Comment by unixfox** [comment]
> I'm reopening, because it's quite an important and legitimate issue. The multiple PRs opened recently (#3489, #3490, #3491) is a sign, and I've also seen that problem multiple times by myslef.

What do you even want to do in order to fix this issue on our side? The server is literally overloaded, that's why it gives this error.
