### ISSUE TITLE
502 Bad Gateway on Large Invidious Data Import

### ISSUE THREAD

**Issue by C-Loftus** [iv-org/invidious#3500]
**Describe the bug**
Importing an Invidious json file with lots of data only gets partially read in. The json is correctly formatted and playlists/subscriptions appear. However, after around 25 seconds it stops reading in more playlists and throws a bad gateway error. 

**Steps to Reproduce**
Read in a large invidious json file (e.g. more than 200 videos from different playlists is enough to time out. I have sometimes been able to read in up to 400 but nothing more)

**Logs**
`504 Gateway Time-out
nginx` 

**Additional context**

 - Browser (if applicable): Firefox
 - Self hosted Invidious instance running ` 2022.11.02-09942dee @ master` 

Seems like this was discussed at 
https://github.com/iv-org/invidious/issues/505
and this commit increased the timeout.
https://github.com/iv-org/invidious/commit/f15b7cebac9d9383340a33f4f091badc5d07d2ca
However, this timeout doesn't seem to be long enough still. It would be awesome if this could be customized.

I am not very familiar with the codebase but it seems like it might be coming from this check in `invidious/src/invidious/helpers/helpers.cr` It would be awesome if this value could be customized.
```
begin
    # Send heartbeat
    loop do
      env.response.puts ":keepalive #{Time.utc.to_unix}"
      env.response.puts
      env.response.flush
      sleep (20 + rand(11)).seconds
    end
  rescue ex
  ensure
    connection_channel.send({false, connection})
  end
```

**Comment by C-Loftus** [comment]
Also my apologies if this is miscategorized. I wasn't sure if this is considered a bug or a feature enhancement.

**Comment by unixfox** [comment]
Have you increased the timeout on the nginx side too though?

**Comment by C-Loftus** [comment]
That seemed to be it, thank you!! Fixed by adding `proxy_read_timeout 10000s;` to my nginx conf for my Invidious site.
I see there is a playlist size limit of 500 but I will just get around this by splitting up a playlist into 'playlistname'1 & 'playlistname'2 etc

Thank you for all your work!
