### ISSUE TITLE
[Bug] Arithmetic overflow (OverflowError)

### ISSUE THREAD

**Issue by GWevroy** [iv-org/invidious#3504]
Title: `Arithmetic overflow (OverflowError)`
Date: `2022-12-18T09:29:18Z`
Route: `/search?q=8+bit+guy`
Version: `2022.11.22-5160d8b @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Arithmetic overflow (OverflowError)
  from src/invidious/yt_backend/extractors.cr:173:63 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

I tried refreshing several times, but does not help. I can see my subscriptions no hassle, but if I try to enter anything in the search bar, I get this. i will also point out that I have a VPN currently running, though that usually does not cause an issue with Invidious. I also tried logging out and back in again, but same fault occurs.

**Comment by GWevroy** [comment]
I tried refreshing several times, but does not help. I can see my subscriptions no hassle, but if I try to enter anything in the search bar, I get this. i will also point out that I have a VPN currently running, though that usually does not cause an issue with Invidious. I also tried logging out and back in again, but same fault occurs.

**Comment by unixfox** [comment]
Closes https://github.com/iv-org/invidious/issues/3451
