### ISSUE TITLE
Slow performance and other issues using "latest_version"

### ISSUE THREAD

**Issue by forthrin** [iv-org/invidious#3505]
#3503 was closed without possibility to comment or reopen, so opening a new issue.

The suggested technique works, but it is incredibly slow (about 4 seconds).

```
$ time ffmpeg -i 'https://invidious.weblibre.org/latest_version?id=GA7Kl7XWOmM&itag=22&local=true' -c copy -vframes 1 -y foo.mp4
0m3.890s
```

Also, the server seems to refuse scripted requests:

```
$ curl --head 'https://invidious.weblibre.org/latest_version?id=GA7Kl7XWOmM&itag=22&local=true'
HTTP/2 200 
content-length: 0
x-sso-wat: You've just been SSOed
```

By comparison, the same operation using the [technique](https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445) linked in the previous issue, takes a mere 0.1s(!)

How does one get a similarly lightning fast response to a playable video from Invidious using a script?

**Comment by unixfox** [comment]
You can still comment on the original issue... Please don't reopen new issues related to the same issue

![image](https://user-images.githubusercontent.com/4016501/208296321-44f7ef34-8ba6-4548-9e0e-2c95be911c98.png)

-----

The response time depends on the power/server resources of the invidious instance. The instance `invidious.weblibre.org` seems overloaded, the page take a lot of time to load.

If you want the fastest response time, then run your own invidious instance: https://docs.invidious.io/installation/

**Comment by forthrin** [comment]
Running own instance seems excessive.

Tried all public instances, and all are much slower than native YouTube, plus many fail. (Results below in milliseconds)

If there is no simple, public method that gets a valid video URL (or JSON data) as fast as a native fetch, this is useless.

I assume core users of this system are people whose need of privacy far outweighs other drawbacks like sluggishness.

Question: Why is the response so slow? Too many users and too few servers?

```
  809	invidious.namazso.eu
 1390	invidious.dhusch.de
 1625	yt.artemislena.eu
 1687	inv.odyssey346.dev
 1842	invidio.xamh.de
 2231	invidious.baczek.me
 2353	inv.bp.projectsegfau.lt
 2388	inv.riverside.rocks
 3157	invidious.nerdvpn.de
 3394	invidious.weblibre.org
 3719	vid.puffyan.us
 5005	y.com.sb
 6054	invidious.privacydev.net
11459	invidious.esmailelbob.xyz

https://invidious.snopyta.org/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 403 Forbidden (access denied)
https://yewtu.be/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
https://invidious.flokinet.to/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 5XX Server Error reply
[tcp @ 0x7fc67a905b80] Connection to tcp://invidious.sethforprivacy.com:443 failed: Connection refused
https://invidious.sethforprivacy.com/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Connection refused
https://invidious.tiekoetter.com/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 403 Forbidden (access denied)
https://inv.vern.cc/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 403 Forbidden (access denied)
https://invidious.slipfox.xyz/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 403 Forbidden (access denied)
https://invidious.rhyshl.live/latest_version?id=GA7Kl7XWOmM&itag=22&local=true: Server returned 5XX Server Error reply
```

**Comment by SamantazFox** [comment]
@forthrin as unixfox said, we don't have any control over the public instances.

While we do our best to make invidious fast, we can't guarantee anything.

It's important to note that video playback is very heavy on bandwidth, so as the number of users increase, the load on the servers increase exponentially. Each instance has different hardware, different ISP, and different budget. Some only have a single server, some can afford a dozen high power nodes.

While the instance owners are providing a free service, there are non-negligible infrastructure costs in the background. For that reason, we understand that some of them may have deployed solutions against abuse (like API access restriction, automated queries detection, etc..).

If you have specific needs, we strongly recommend you to run your own instance, in order to reduce the stress on the public ones.

**Comment by forthrin** [comment]
VPS and BW costs are obvious. My use is minuscle, just a few search queries per day. I guess I'll stay with my own setup, as instant response is paramount to me. Call it an occupational hazard of having worked with optimization too long.

I like the more accessible search parameters and simple response format, though I might have preferred the JSON paths identical to the original (and rather remove unnecessary keys), so that the same code could be reduced to parse the data.

Questions:

1. When you have gone through the trouble of indexing the entire video collection, why is searching for `duration` still restricted to `short` and `long` rather than a fine-grained range? Same for `date`, etc.

2. Is the core purpose and target user group (and non-purpose and edge use) of Invidious explained clearly anywhere? Couldn't see it in the FAQ. "What is Invidious?" and "Who is Invidious for?" seems treated as implicit knowledge.

**Comment by SamantazFox** [comment]
> I like the more accessible search parameters and simple response format, though I might have preferred the JSON paths identical to the original (and rather remove unnecessary keys), so that the same code could be reduced to parse the data.

The invidious API tries to stay as consistent as possible. Youtube's internal API is terrible at that.
So the idea is to extract the relevant data and provide only that in a simpler and consistent form.

> When you have gone through the trouble of indexing the entire video collection, why is searching for `duration` still restricted to `short` and `long` rather than a fine-grained range? Same for `date`, etc.

I have absolutely no idea. Try to ask an engineer working at Youtube?

> Is the core purpose and target user group (and non-purpose and edge use) of Invidious explained clearly anywhere? Couldn't see it in the FAQ. "What is Invidious?" and "Who is Invidious for?" seems treated as implicit knowledge.

is https://invidious.io/ what you're looking for?

**Comment by forthrin** [comment]
> The invidious API tries to stay as consistent as possible. Youtube's internal API is terrible at that. So the idea is to extract the relevant data and provide only that in a simpler and consistent form.

I agree.

> > When you have gone through the trouble of indexing the entire video collection, why is searching for `duration` still restricted to `short` and `long` rather than a fine-grained range? Same for `date`, etc.
> 
> I have absolutely no idea. Try to ask an engineer working at Youtube?

Since you index the entire collection, you have a database of all durations, all dates, etc. Why do you impose the same search restrictions on your API as the search engine of the original?

> > Is the core purpose and target user group (and non-purpose and edge use) of Invidious explained clearly anywhere? Couldn't see it in the FAQ. "What is Invidious?" and "Who is Invidious for?" seems treated as implicit knowledge.
> 
> is https://invidious.io/ what you're looking for?

Not bad. Nice illustrations, but a few paragraphs of text at the top of the FAQ would have been nice. But maybe people are already sold by word of mouth when they arrive there.

**Comment by forthrin** [comment]
> > Since you index the entire collection, you have a database of all durations, all dates, etc. Why do you impose the same search restrictions on your API as the search engine of the original?
> 
> We don't index anything. That task would require way too much disk space and servers... What we do is only forwarding the search query to youtube, then providing the returned results. Nothing more.

Oh, wow... I didn't realise that. So it's basically an adapter pattern as a service. Abstraction for the sake of simplicity and (well, some) privacy. Well, for non-tech web users it's fantastic to have a minimalistic frontend.

I thought you ran search queries to the source, built up a database of the responses that are then used as a cache for later queries, combined with new videos from the source as needed. Most metadata is static after all (except view count).

Well, thanks for sorting this out. This could also have been included in the FAQ or the front page. Or maybe it's just me.
