### ISSUE TITLE
[Bug] New videos don't show in subscriptions page

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#3507]
**Describe the bug**

If a subscribed channel releases new videos, it will not show up in the Subscriptions page
**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**
Version: 2022.11.22-5160d8b @ master

This problem is very recent --- it worked fine last week. I didn't change anything on the server or client side.

**Comment by unixfox** [comment]
Do you have pubsub enabled?

**Comment by DUOLabs333** [comment]
Restarting it does not solve the issue.

**Comment by DUOLabs333** [comment]
How would I get a HMAC key to pubsubhub?
