### ISSUE TITLE
[Bug] The number of videos and subscribers are reversed.

### ISSUE THREAD

**Issue by BlitDev** [iv-org/invidious#3514]
**Describe the bug**
Number of subscribers: 0
Number of videos: 341 (actual number of subscribers: 34k)

**Steps to Reproduce**
1. Search any channel.

**Logs**
No
**Screenshots**
![image](https://user-images.githubusercontent.com/79034202/209436520-1d2e6f7c-427d-4a5d-bc25-a6a6ffe6c6b5.png)
but
![image](https://user-images.githubusercontent.com/79034202/209436529-331b2533-49c2-4dbe-a7a1-f0365b613524.png)

**Additional context**

- Browser: Librewolf (Firefox fork)
- OS: Arch Linux

**Comment by SamantazFox** [comment]
Hello! Yes, we are aware of that, it's because of the new handle thing that's being rolled out by YT.
I'm hoping that youtube will stabilize it's output: https://github.com/iv-org/invidious/issues/3394#issuecomment-1321251986

**Comment by DUOLabs333** [comment]
Should be fixed by PR #3535.

**Comment by SamantazFox** [comment]
Yes, this was closed by #3535
