### ISSUE TITLE
[Question] how to change port

### ISSUE THREAD

**Issue by obito26m** [iv-org/invidious#3515]
**Is your enhancement request related to a problem? Please describe.**

sorry i didn't know where to write best i try to change the port because i already have something on port 3000 i set the port 3000 to 3005 in the compose dadtei but in the log file it still says that you have to go to localhost:3000 i think that in a config the port 3000 is still there but somehow i can't find it this is how my compose file looks i connected the folders 

version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3005/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - /volume1/docker/invidious/postgresdata:/var/lib/postgresql/data
      - /volume1/docker/invidious/config:/config/sql
      - /volume1/docker/invidious:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

but in the config folder is not ? iption of what the problem is.

**Comment by unixfox** [comment]
In your docker-compose file set

```
ports:
- "3005:3000"
```
