### ISSUE TITLE
[Feature request]  Are there any plugins to sort of remember my chosen settings if I change IV instances?

### ISSUE THREAD

**Issue by Jaladhjin** [iv-org/invidious#3516]
I've been very happy using IV & am very grateful to the people hosting public instances.

1 very small issue I've ran into as a simple end user is whenever I switch instances understandably all my preferred setting changes get wiped out.

Things like auto play video, the quality set, pretty much anything from default I change in user settings on the YT frontend page.

So the proposal is a userscript that maybe attempts to confirm your settings on any given instance, if they are not set sets them & reloads the page if necessary.

I'm no coder myself so I'm not sure if this is possible or even practical to attempt to do but it's the only very minor frustration I have as an IV end user.

Food for thought friends & a very merry holiday season to all where ever you may be!

**Comment by unixfox** [comment]
Stop creating duplicated issues I've already answered you in this issue: https://github.com/iv-org/invidious/issues/3509#issuecomment-1358983357
