### ISSUE TITLE
[Enhancement] Add support for carousel community posts

### ISSUE THREAD

**Issue by ChunkyProgrammer** [iv-org/invidious#3522]
**Is your enhancement request related to a problem? Please describe.**
Some community posts can contain multiple images. 
Ex: https://www.youtube.com/post/Ugkxt21IuGwAASZbIZjcev04GN4alJlYK3T5

In invidious api it will say "unknown attachment type"
https://redirect.invidious.io/api/v1/channels/UCnkp4xDOwqqJD7sSM3xdUiQ/community?pretty=1

**Describe the solution you'd like**
Add support for parsing posts with multiple images

**Describe alternatives you've considered**
None

**Comment by SamantazFox** [comment]
Partially implemented by #3599
This still requires a front-end implementation.

**Comment by ChunkyProgrammer** [comment]
Looks like this is an accessible carousel using only css and html:
codepen: https://codepen.io/jwjertzoch/pen/JjyGeRy 
article: https://levelup.gitconnected.com/how-to-make-a-fully-accessible-css-only-carousel-40e8bd62032b
