### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by ghtesting2020** [iv-org/invidious#3524]
When I am watching a video at random times it will stop and the message "The media could not be loaded, either because the server or network failed or because the format is not supported." other times that message appears on certain videos immediately. I cannot pin down why, there are no network issues on my end and the format not supported does not make sense to me.

Example clip that immediately displays that message: https://inv.vern.cc/watch?v=7ury3Wmg9PA which is from this search https://inv.vern.cc/search?q=crazy+frog the first 7-8 work fine and then that one does not. What makes that one special?

I am on Firefox flatpak

**Comment by unixfox** [comment]
See all of these info:
- https://github.com/iv-org/invidious/issues/2055
- https://docs.invidious.io/faq/#table-of-contents
- try to enable dash in the preferences

**Comment by itguy327** [comment]
I have dash enabled across my instance and get this message unless I select HD720

**Comment by pannal** [comment]
I can't play [this video at all](https://www.youtube.com/watch?v=RzfEmZrlSHY), regardless of what settings are used. Chrome, current stable.

**Comment by acoul** [comment]
> I can't play [this video at all](https://www.youtube.com/watch?v=RzfEmZrlSHY), regardless of what settings are used. Chrome, current stable.

same on [this video](https://www.youtube.com/watch?v=WuN9nyHFYI4) on arch linux firefox 120.0.1 (64-bit)
