### ISSUE TITLE
[Enhancement] Be able to see all videos in videos page

### ISSUE THREAD

**Issue by alx-alexpark** [iv-org/invidious#3534]
**Is your enhancement request related to a problem? Please describe.**

You can't see all the videos of a certain channel.

**Describe the solution you'd like**

Either continuous scrolling to be able to see all the videos of a channel, or pagination/load more button for users that have disabled javascript.

**Describe alternatives you've considered**

I cannot think of any other alternatives.

**Additional context**

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3371
