### ISSUE TITLE
[Bug] relation "videos" does not exist (PQ::PQError)

### ISSUE THREAD

**Issue by QT31416** [iv-org/invidious#3536]
**Describe the bug**
I try to search for a video. I click on the thumbnail to watch any video, then this error occurs.

**Steps to Reproduce**
1. Go to '<url>:3000' and search for any video
2. Click on any video

**Logs**
Title: `relation "videos" does not exist (PQ::PQError)`
Date: `2023-01-04T10:33:18Z`
Route: `/watch?v=_bkX5VkZg8U`
Version: `2023.01.01-865704d @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
relation "videos" does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'select'
  from src/invidious/videos.cr:337:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/26166095/210537685-b0808bc9-d210-4085-85ac-7c8cd5cc12ef.png)

**Additional context**
 - Browser (if applicable): Firefox on Windows, Chrome on Android
 - OS (if applicable): Windows 10 64-bit, Android 11, Android 12
 - Invidious is installed on Docker
 - Upon first boot a few hours ago, Invidious worked

**Comment by QT31416** [comment]
I tried deleting the:
1. containers on portainer
2. images on portainer
3. network on portainer
4. persistent volumes

Then I tried installing from scratch again, but it didn't work.

**Comment by unixfox** [comment]
We do not support portainer. Please install invidious the proper way using our documentation: https://docs.invidious.io/installation/#automated-installation

**Comment by QT31416** [comment]
Yeah, sorry about that. Works like a charm now. Thank you!
