### ISSUE TITLE
[Bug] Search API returns published as the time when the search was performed

### ISSUE THREAD

**Issue by manutdkid77** [iv-org/invidious#3543]
**Describe the bug**
Hello :)

I've been using the [search api](https://docs.invidious.io/api/#get-apiv1search) to note the published time for a video.

However I've noticed that the timestamp returned by the `published` property matches the time when I performed this search.

Is there something which I'm missing to check ?

**Steps to Reproduce**
1. This search query `https://inv.riverside.rocks/api/v1/search?q=mVy_As1xTNs&type=video&pretty=1` returns published as `1671424701` for the first item in the list.

2. If I [convert this](https://www.unixtimestamp.com/) its the same time (10:08 AM IST) when I performed the search.

**Screenshots**

![sc11](https://user-images.githubusercontent.com/14297705/211251144-e6cd1dcd-a464-4e18-b97b-8a6a5b913135.PNG)

![sc12](https://user-images.githubusercontent.com/14297705/211251255-5084557b-718a-43b8-80f3-b5f70a77b33c.PNG)

**Comment by ChunkyProgrammer** [comment]
I think this issue only happens with video premiers and live videos. Here's an id that still returns current time for testing purposes: O3cCYok_ukk for premiere and jfKfPfyJRdk for live video

**Comment by manutdkid77** [comment]
The video id **mVy_As1xTNs** which I have linked to in the first post is not a premiere/live video 🙂

Here's another normal video id **xlqcT4NSrZw** which returns the current time `https://inv.riverside.rocks/api/v1/search?q=xlqcT4NSrZw&type=video&pretty=1`
