### ISSUE TITLE
[Bug] Media could not be loaded - dash video quality set to 240p

### ISSUE THREAD

**Issue by gh-supersudo** [iv-org/invidious#3550]
**Describe the bug**

Here's the channel: /channel/UCERUmrDh9hmqEXBsnYFNTIA

I noticed that his videos that were published until June 01, 2017 0:00:00 UTC gives that error. I tried it on other instances and it shows the same error. I'm using an old device that's why my preferred video quality is only set to 240p/small. I added `&quality=dash` and dash video quality set to 240p but it plays 720p or higher for a few seconds causing my device to lag so I'm trying to avoid it.

Here's a sample of the subject's video that was published before the given date: /watch?v=rrrmOFtTqCM
Here's another video from another channel that was published before the given date but it works normal: /watch?v=_esd3FisTDU

Here's the instances I tried the videos with: `invidious.nerdvpn.de`, `inv.vern.cc`, `invidious.snopyta.org`, `vid.priv.au`

**Comment by unixfox** [comment]
You forgot to specify which instance did you use.

**Comment by gh-supersudo** [comment]
> You forgot to specify which instance did you use.

my bad, i just added it
