### ISSUE TITLE
[Bug] relation "subscriptions_" does not exist (PQ::PQError)

### ISSUE THREAD

**Issue by tempname1024** [iv-org/invidious#3566]
**Describe the bug**
A recent update/restart to [c012aac](https://github.com/iv-org/invidious/commit/c012aac997c6944fc0735800716b8304ab8c92cc) (unsure which commit specifically is implicated, hadn't updated for a few weeks) seems to have broken the subscriptions page.

Functionality when not logged in seems OK.

**Steps to Reproduce**
1. Update to [c012aac](https://github.com/iv-org/invidious/commit/c012aac997c6944fc0735800716b8304ab8c92cc).
2. Create an account, add subscriptions.
3. Navigate to subscriptions page.

**Logs**
Title: `relation "subscriptions_" does not exist (PQ::PQError)`
Date: `2023-01-15T16:12:18Z`
Route: `/feed/subscriptions`
Version: `2023.01.15-c012aac9 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
relation "subscriptions_" does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:220:65 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'query_all:as'
  from src/invidious/users.cr:183:18 in 'get_subscription_feed'
  from src/invidious/routes/feeds.cr:97:29 in 'subscriptions'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Additional context**
- Alpine Linux 3.17

**Comment by tempname1024** [comment]
Update: The issue may be the result of A/B testing, transient system-sensitive conditions, or ghosts; everything seems to be working OK now, I'll leave the issue's status up to maintainers in case it's reproducible.

**Comment by unixfox** [comment]
Please see: https://github.com/iv-org/invidious/issues/3344

Solution: https://github.com/iv-org/invidious/issues/3344#issuecomment-1278147276
