### ISSUE TITLE
[Bug] Captions dont work on any instance.

### ISSUE THREAD

**Issue by qxczji** [iv-org/invidious#3569]
**Describe the bug**
Hello, iv-org. There are is a bug to all public instances that run invidious. Whenever I enable captions, it refuses to show up. All instances that are public does that.

**Steps to Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/95053021/212560802-8ac1c537-28b6-4a53-858d-791d1ac7ac10.png)

**Additional context**

 - Browser: Microsoft Edge 109.0.1518.49 (64-bit)
 - OS (if applicable): Windows 10

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3455 and https://github.com/iv-org/invidious/issues/2567
