### ISSUE TITLE
Postgres Connection Refused > docker-compose with production image (Raspberry Pi)

### ISSUE THREAD

**Issue by teslakoil** [iv-org/invidious#3572]
**Deploying the docker-compose yml from the git repo always returns back a Connection Refused error on the DB**

**Steps to Reproduce**
1. Clone the git.
2. Edit YML to include the ARM image.
3. Check container logs

**Logs**
Unhandled exception:  (DB::ConnectionRefused)
  from lib/sqlite3/src/sqlite3/connection.cr:10:11 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Cannot establish connection (PQ::ConnectionError)
  from lib/pg/src/pq/connection.cr:23 in 'new'
  from lib/pg/src/pg/connection.cr:13:9 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Error connecting to 'invidious-db:5432': Connection refused (Socket::ConnectError)
  from /usr/lib/crystal/core/gc/boehm.cr:192:5 in 'new'
  from lib/pg/src/pg/connection.cr:13:9 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Unhandled exception:  (DB::ConnectionRefused)
  from lib/sqlite3/src/sqlite3/connection.cr:10:11 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Cannot establish connection (PQ::ConnectionError)
  from lib/pg/src/pq/connection.cr:23 in 'new'
  from lib/pg/src/pg/connection.cr:13:9 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Caused by: Error connecting to 'invidious-db:5432': Connection refused (Socket::ConnectError)
  from /usr/lib/crystal/core/gc/boehm.cr:192:5 in 'new'
  from lib/pg/src/pg/connection.cr:13:9 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from /usr/lib/crystal/core/int.cr:525:11 in 'build_database'
  from src/invidious.cr:61:15 in '__crystal_main'
  from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'

**Additional context**
 - Browser (if applicable):
 - OS dietpi

EDIT: The network by default is on bridge. The IPs and range getting created are in the 172.2x.0.0 range. Both containers are in the same network created. Tried with replacing invidious-db as the network with an ip address, produced the same problem.

**Comment by unixfox** [comment]
check if postgres is running: docker compose ps or docker-compose ps

**Comment by teslakoil** [comment]
It is:

![image](https://user-images.githubusercontent.com/49675220/212697180-0200cfd6-cc52-4b29-b09b-ee64bafb6ae4.png)

**Comment by teslakoil** [comment]
I've tried changing to PostgreSQL 13, in hopes that it would change something, but it doesn't. Same behavior with 14.

**Comment by unixfox** [comment]
Please give the result of the command that I've sent, not something else please.

**Comment by unixfox** [comment]
Invidious is running on port 3000, what's the issue here?

**Comment by teslakoil** [comment]
I seem to be too much of a newbie trying to configure the reverse proxy to point to 127.0.0.1. This is however no Invidious issue. I thought the DB not allowing the connection wasn't allowing the container to start. 

Thanks!
