### ISSUE TITLE
[Bug] Missing JSON element "videoDetails" (BrokenTubeException) - Annotations leading into private vids

### ISSUE THREAD

**Issue by d3nwah** [iv-org/invidious#3573]
**Describe the bug**
Invidious doesn't seem to know how to handle redirects from annotations to a private video and crashes instead. Reportedly YT privated a lot of unlisted videos in 2017 when they got rid of annotations.

**Steps to Reproduce**
1. Go to any YT video on an any Invidious instance that has annotations leading to a private video (e.g. any options in watch?v=hvkjP6dqpfY )
2. Click Show annotations button if not shown already
3. Click annotation

**Logs**

Title: `Missing JSON element "videoDetails" (BrokenTubeException)`
Date: `2023-01-16T13:50:12Z`
Route: `/watch?annotation_id=annotation_487862&ei=p4IqXK_NPM6UhwakvZDYDg&feature=iv&src_vid=hvkjP6dqpfY&v=YVs2JHXHA6s`
Version: `2023.01.10-05258d5 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "videoDetails" (BrokenTubeException)
  from /usr/share/crystal/src/array.cr:114:31 in 'parse_video_info'
  from src/invidious/videos/parser.cr:90:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:366:10 in 'fetch_video'
  from src/invidious/videos.cr:354:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Screenshots**

Not needed

**Additional context**

Chromium Linux, probably not needed info

**Comment by unixfox** [comment]
The instance that you are using is outdated by a few code changes because this bug has been fixed. Please wait for the instance to be updated or use an up-to-date instance: https://api.invidious.io/
