### ISSUE TITLE
Editting the config doesn't change anything on my own instance.

### ISSUE THREAD

**Issue by IrIougER** [iv-org/invidious#3579]
I've just started self hosting and run my own instance for personal use.  When I edit  config.example.yml nothing changed on my instance.  Tried again with a copied config.yml    Still no luck.

I want to disable any more registrations and tried to make a banner.

**Comment by unixfox** [comment]
You have not given any context as to how you did install invidious, what operating system you are using and more...

**Comment by IrIougER** [comment]
> You have not given any context as to how you did install invidious, what operating system you are using and more...

Used the official installation on https://docs.invidious.io/installation/    Using docker-compose on an  Ubuntu 22.04 VPS.   Reverse proxy is  NGINX Proxy Manager.

**Comment by unixfox** [comment]
You have to make the modifications in the environment variable `INVIDIOUS_CONFIG` located in the docker-compose.yml. Changing the `config.yml` won't do anything.
