### ISSUE TITLE
[Bug] Channel: parameter search returns no results

### ISSUE THREAD

**Issue by chocmake** [iv-org/invidious#3594]
**Describe the bug**
Using the `channel:` parameter for queries no longer returns results.

**Steps to Reproduce**
1. Visit a channel and copy its channel ID from the URL.
2. In the search box enter `channel:<channelID> <query>`
3. Observe no results found.

Example: [this channel](https://www.youtube.com/channel/UCHqwzhcFOsoFFh33Uy8rAgQ) is all about antennas. However querying `antenna` with such a channel search returns no results ([Snopyta example query](https://invidious.snopyta.org/search?q=channel:UCHqwzhcFOsoFFh33Uy8rAgQ%20antenna)).

According to my history the last time this parameter search worked was 2023-01-21 (unsure what Invidious version the instance I was using was on at that time though).

**Additional context**
Noticed on both Snopyta (2023.01.24-9a9f8231) and Yewtu.be (2023.01.28-71f980b) instances.

**Comment by ChunkyProgrammer** [comment]
It seems like you may need to have a space after the colon for it to work (not sure if this was always the case)

I also noticed that the link your provided did not properly encode the  ":" character which can also be part of the issue.
With the unencoded colon, it fails:
https://invidious.snopyta.org/search?q=channel:UCHqwzhcFOsoFFh33Uy8rAgQ%20antenna

And this should work (notice the `%3A`):
https://invidious.snopyta.org/search?q=channel%3A+UCHqwzhcFOsoFFh33Uy8rAgQ%20antenna

**Comment by chocmake** [comment]
> https://invidious.snopyta.org/search?q=channel%3A+UCHqwzhcFOsoFFh33Uy8rAgQ%20antenna

This doesn't return results from the specified channel though, just generic search results containing the raw channel ID and query included. Fwiw, the original syntax was non spaces, eg seen in an earlier bug report of mine (#3148).

If we use the colon escaped encoding (without the space, as per original syntax) it doesn't return results ([example](https://invidious.snopyta.org/search?q=channel%3AUCHqwzhcFOsoFFh33Uy8rAgQ+antenna)).

**Comment by ChunkyProgrammer** [comment]
Would like to add that this issue also affects the API

Ex:
https://yt.artemislena.eu/api/v1/channels/search/UCHqwzhcFOsoFFh33Uy8rAgQ?q=antenna

**Comment by SamantazFox** [comment]
That's possible that Youtube changed their channel search
