### ISSUE TITLE
[Question] how to remove a video from a playlist

### ISSUE THREAD

**Issue by ForceConstant** [iv-org/invidious#3598]
So I can obvoiusly see how to add a video to a watchlist, but shouldn't there be an equally as obvoius way to remove a video from a watchlist? I can't figure out how to do it. How am I supposed to do this?

**Comment by bzuruce** [comment]
Playlist > [Playlist name] > + > Editing Playlist "[Playlist Name]" > Trash Icon

**Comment by ForceConstant** [comment]
Thanks, well funny enough today I don't know if I missed it before, or it is new. I see in the playlist view, that each video has a trash icon in top right of video image to delete from playlist.
