### ISSUE TITLE
High CPU usage in listen mode

### ISSUE THREAD

**Issue by Self-Perfection** [iv-org/invidious#3602]
**Describe the bug**
Firefox uses about 5 times more CPU time for showing Ividious page in listen than direct playback of the same file.
Brave uses about 3x times more CPU time.

**Steps to Reproduce**
1. Start web browser with new profile
2. Open single tab with any YouTube music video. Example: https://yewtu.be/watch?v=qk1nnAHI1mI&listen=1
3. Start playback
4. Check CPU usage by web browser
5. Download audio track from test video (e.g. `yt-dlp -f ba $URL`)
6. Playback audio via dedicated audio player. I used mpv for instance.
7. Observe CPU usage 3-5 times lower than during playback via web browser

**Additional context**
I expected that playing just audio via Invidious would drastically decrease power consumption and therefore save battery. But in my case it just a little bit lower. Even embed Invidious link ( https://yewtu.be/embed/qk1nnAHI1mI?listen=1 ) consumes 5x times more CPU time than direct playback. Why is that?

**Comment by unixfox** [comment]
Can you reproduce the same issue if you turn off JavaScript? This will use the default browser player.

This way we can understand if it's videojs, the Invidious player that is causing some high CPU usage or not.

**Comment by Self-Perfection** [comment]
On my test system with `javascript.enabled=false` playback of https://yewtu.be/watch?v=qk1nnAHI1mI&listen=1 in Firefox uses 2 times less CPU time than with enabled JS. More precisely:
* About 15-20% CPU time without JS
* about 45-50% CPU time with JS

Apparently JS player adds substantial overhead.
