### ISSUE TITLE
[Bug] DASH plays with wrong audio language

### ISSUE THREAD

**Issue by samsapti** [iv-org/invidious#3610]
**Describe the bug**

When playing videos with DASH, the audio is in a different language than the original, which is English. For some instances, it's in one language, and another language for other instances.

**Steps to Reproduce**

1. Go to Invidious on any instance
2. Play a video that has alternative audio languages, it'll play in a random language
3. Play the same video on YouTube, it'll play in English

**Logs**

Not relevant.

**Screenshots**

Not relevant.

**Additional context**

- Browser: Brave
- OS: Linux

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
