### ISSUE TITLE
[Bug] Proxying is disabled entirely when only allowing downloads.

### ISSUE THREAD

**Issue by GoldDominik893** [iv-org/invidious#3619]
having set the 
```yaml
disable_proxy:
         - local
         - livestreams
         - dash
```
in the `docker-compose.yml` file causes dash streams and proxied video to be disabled but it also disables downloads.
The download button is there but upon clicking on it, it redirects to a page saying `Administrator has disabled this endpoint.`
![brave_vpfHSWgFQC](https://user-images.githubusercontent.com/68468388/216763484-36af3147-5013-4003-818d-f239c27268b4.png)
![brave_oUG9AfJy3V](https://user-images.githubusercontent.com/68468388/216763492-8c0dd5b4-9755-4d07-8e1a-43c2e5d4029a.png)

**Comment by SamantazFox** [comment]
That's because you're probably trying to download some DASH video.
Can you try to download e.g "medium" or "hd720" quality video?

**Comment by GoldDominik893** [comment]
Isn't 720p/hd720 and 360p/medium?

**Comment by GoldDominik893** [comment]
Or do you mean like right clicking on the video and clicking Save as?

**Comment by SamantazFox** [comment]
> Isn't 720p/hd720 and 360p/medium?

Oh, sorry, I forgot that those don't have the same name as on the player.

In the player, `hd720` and `medium` are regular HTTP audio+video streams, where as `144p`, `360p`, `480p`, `720p` and such are video-only DASH streams.

In the download drop down, here are the equivalents. Note how it says "video only":
![image](https://user-images.githubusercontent.com/52980486/219174922-8d00de46-3c82-41ce-b0b2-9c04c7084199.png)

So can you try to download one of the first two entries?

**Comment by GoldDominik893** [comment]
yea i was trying to download those two top ones before also you can check on here: https://invidious.epicsite.xyz/watch?v=h7mNA2L_6Z4.
