### ISSUE TITLE
[Feature request] Hide videos shorter than X seconds

### ISSUE THREAD

**Issue by rex4539** [iv-org/invidious#3621]
**Is your feature request related to a problem? Please describe.**

This is an attempt to solve the ultra annoying short videos issue.

**Describe the solution you'd like**

Add an option in Preferences "Hide videos shorter than" where user can enter any number in seconds, so any videos shorter than this number will be hidden from the UI.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2585
