### ISSUE TITLE
[Bug] Some videos are taking long to load on ios browsers

### ISSUE THREAD

**Issue by shokifrend007** [iv-org/invidious#3623]
**Describe the bug**

I have recently noticed that videos longer than ~15 min take a long time to load in listen mode.
However, the same videos load instantly in video mode.
Also, if i disable javascript in safari, the video doesn't load at all, but that is probably a different issue.

Slow loading video:
https://invidious.tiekoetter.com/watch?v=LBtEJ-iQbeg&listen=1

Really slow loading video:
https://invidious.tiekoetter.com/watch?v=ePGIebH-Wzw&listen=1

**Steps to Reproduce**

1. open safari
2. go to one of the links above
3. wait...
4. video loaded after up to 5min

**Screenshots**
![image](https://user-images.githubusercontent.com/63724336/217355979-ccc4cb19-8b45-4b92-b8ef-47989efc4059.png)

**Additional context**
Device: iPhone 7
ios version: 15.7.3
Browsers: Safari and Firefox
Instances: tiekoetter, yewtu.be, sethforprivacy

P.S.: Please don't judge my music choices

**Comment by whaler-ragweed** [comment]
Same issue here, listen mode is loading forever on Safari (both MacOS and iOS).

**Comment by SamantazFox** [comment]
I guess it's not browser specific. Youtube is throttling audio streams if the accompanying video stream is not fetched.

**Comment by unixfox** [comment]
> Would it be possible to fetch the video stream to the server that host my invidious instance, and then make only the audio stream flow to my client device?
> 
> This would be increased traffic for my server, but at least things would load..?

That would require to have a transcoder built-in in invidious, something we do not plan to implement.

**Comment by ManiMatter** [comment]
Any ingenious plan to get around the youtube throttling? ;)

**Comment by unixfox** [comment]
> Any ingenious plan to get around the youtube throttling? ;)

There is a related issue here: https://github.com/iv-org/invidious/issues/3941#issuecomment-1610136581

We are trying to find a fix. Some instances like https://yewtu.be have implemented one, you may try to see if that solves your issue.

Apart from that, if we don't post anything it's just that there hasn't been any progress towards that.

**Comment by ManiMatter** [comment]
Super, you guys rock! Fingers crossed we figure this one out, too :)
