### ISSUE TITLE
Support for Watch Later feature

### ISSUE THREAD

**Issue by RafiqAli** [iv-org/invidious#3629]
Hello,

I'm a user of invidious for some weeks now, I like it so far. I noticed that invidious allows the creation of playlists with the ability to add videos to them. On the other hand I didn't see any button or mechanism to save videos while one is scrolling through the front page. 

I suggest we add a button on every video on the feed page that automatically adds it to an already created playlist named 'Watch Later' or any other name.

Thank so much for your work & I'm here to help. 
Have a great day !

**Comment by unixfox** [comment]
Already requested in https://github.com/iv-org/invidious/issues/408

**Comment by WalsGit** [comment]
@RafiqAli I have created and just published a userscript that does exactly that. you can find it here https://github.com/WalsGit/Add2WL-for-Invidious
