### ISSUE TITLE
Alternative login options

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#364]
It's probably a good idea to add a support of an another login provider (except Google). Since people may do not want to create an account on the site (for various reasons) and may not have a Google account at the same time. 

IMHO, implementing OpenID standard support (for example) would be beneficial.

**Comment by KetchupEnthusiast** [comment]
Also #41 would be great too

**Comment by roipoussiere** [comment]
I totally agree.
My first motivation to use invidious is to move away from the Google influence and I delete my Google account last year.
It could be a key-feature to subscribe to channels without a Google account for me and many other people.

On my smartphone I use [NewPipe](https://newpipe.schabi.org/), on which I can subscribe to channels *locally* and see which new video has been published on these accounts.

My typical workflow is to check what video I would like to watch on my smartphone, then go to Youtube / Invidious to select this video to actually watch it on a bigger screen, which is not really practical.
