### ISSUE TITLE
[Bug] Missing warning / error message for broken captcha

### ISSUE THREAD

**Issue by PrivacyDevel** [iv-org/invidious#3647]
**Describe the bug**
When the rsvg-convert command can't be found (indicating that the librsvg2-bin package isn't installed in Debian's case), the registration captcha image fails to be loaded / generated without any kind of warning or error messages getting logged that tells the user what's wrong.

**Steps to Reproduce**
1. Install Invidious without installing the package that provides rsvg-convert
2. Enable registration
3. Create account
4. See broken clock captcha image with the source url "data:image/png;base64,"
5. Time to troubleshoot without errors or warnings

**Comment by SamantazFox** [comment]
The lack of error message is caused by the Crystal standard library not behaving as expected on POSIX systems.
See https://github.com/crystal-lang/crystal/issues/12873
