### ISSUE TITLE
[Enhancement] bump video watched, already in watch history

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#3649]
**Is your enhancement request related to a problem? Please describe.**

When a video is watched and it's already in watch history, it should be bumped to the beginning of the list.
If the video was watched long time ago (several pages into the watch history) it is perceived as if it was not added.
That's why it should be put into the beginning.

**Describe the solution you'd like**

As described 

**Describe alternatives you've considered**

**Additional context**

**Comment by unixfox** [comment]
Seems like a pretty easy fix though, like moving the video element to the first position in the array: https://github.com/iv-org/invidious/blob/master/src/invidious/database/users.cr#L52
