### ISSUE TITLE
[Bug] Slow loading time with DASH

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#3666]
**Describe the bug**
I recently noticed that DASH will always be showing the lowest quality. 
This looks consistent across instances and videos.
I thought it was my internet, but it's not.

**Steps to Reproduce**
1. Preferred video quality: DASH
2. Preferred DASH video quality: auto
3. Open any video
4. The quality will be lowest (like 144p) and does not improve

**More context**
Both Invidious player and [Playlet](https://github.com/iBicha/playlet) are seeing the same thing (low quality DASH)

**Comment by SamantazFox** [comment]
Yes, see https://github.com/yt-dlp/yt-dlp/issues/6369 for more details!

**Comment by iBicha** [comment]
Following up on this issue: DASH does not show the lowest quality feed (as described in the repro steps). It's been a while since it's working.
If there's an no ongoing underlying issue on top of this, then this can be closed.
