### ISSUE TITLE
Request: Redesign

### ISSUE THREAD

**Issue by itsarjuna** [iv-org/invidious#367]
I was wondering if in the long term there could be a redesign for the site. This issue is somewhat related to #4. I'm willing to create a few designs and implement it in CSS. These designs wouldn't be anything revolutionary - I'm thinking a generally lightweight design that doesn't change the overall structure of the existing design.

Do you think that bootstrap could be an option?

**Comment by proyb6** [comment]
If I wanted to build something, I won’t use  Bootstrap but functional CSS like Tachyons CSS

**Comment by omarroth** [comment]
I've received a couple other messages about this. There's some discussion on a similar feature in FreeTubeApp/FreeTube#38. My thoughts on this are similar to @PrestonN's.

Currently Invidious uses [purecss](https://purecss.io/), and some custom styling in `assets/css/default.css`, `assets/css/lighttheme.css`, and `assets/css/darktheme.css`. You'll probably want to look there for getting started. I would recommend creating a new `assets/css/themename.css` and opening a PR.

I'm not very familiar with Bootstrap, but if you want to use another CSS framework you'll want to make sure it's compatible with the AGPL. Most open-source licenses will generally be fine.

I think trying to switch to and use another framework would be quite a bit of work, so if you can, I'd recommend trying to modify the existing design using the method I described above.

**Comment by shortenjukebox** [comment]
I personally dig the current design’s minimalism, both aesthetically and in its use of resources. JavaScript being optional is a huge plus. It looks non-descript enough that it hopefully won’t draw too much attention from [The Company That Shall Not Be Named].

I suppose I’d prefer the navigation bar to be ~25 pixels shorter, so the whole video player fits above-the-fold on my tiny laptop screen.

**Comment by PopeRigby** [comment]
Would Google be able to shut down Invidious?

**Comment by Perflyst** [comment]
Sure, they can do it through the law more or less and also technical.

**Comment by PopeRigby** [comment]
So why haven't they? Makes me uneasy that they could shut this down at any second.

**Comment by omarroth** [comment]
In future please open a new issue rather than asking in an unrelated issue.

See #130. Invidious works similarly to youtube-dl and NewPipe, which also have information on this. Invidious is not, to my understanding, at risk of legal threats, since it does not use the official YouTube API.

**Comment by PopeRigby** [comment]
Alright. Sorry about that

**Comment by trymeouteh** [comment]
I think PureCSS would work well for a redesign but honestly the site does not look that bad.

**Comment by practik** [comment]
Overall I like the design as well, but I was already using YouTube in theater mode, so the layout of Invidious is quite similar to what I was used to. My only suggestions would be:
- In the related videos column, putting the thumbnails and descriptions side by side (i.e., the way YouTube does it) would save space (meaning you don't have to scroll as far) and make it clearer which description belongs to which thumbnail.
- For those of us who just want to tweak the layout with some custom CSS on our own browsers, it would help a lot if every element had an id and/or class. Currently a lot of the `p` elements don't have either (view count, video length, video title, etc.), so to target them you have to resort to stuff like `.pure-u-lg-1-5:first-of-type p:nth-of-type(2)`.

**Comment by elypter** [comment]
>In the related videos column, putting the thumbnails and descriptions side by side (i.e., the way YouTube does it) would save space (meaning you don't have to scroll as far) and make it clearer which description belongs to which thumbnail

This has the downside that the video description section will get squeezed to much on an non wide screen or smaller monitor. it could be part of a fluid adapting design though

**Comment by aparms** [comment]
So I now have the time to get working on this, but I'm not sure if this is a highly requested feature. If there is substantial interest then I could get to work on making some things a bit prettier, perhaps similar to the FreeTube layout although I haven't used FreeTube in a while.

**Comment by PopeRigby** [comment]
> 
> 
> So I now have the time to get working on this, but I'm not sure if this is a highly requested feature. If there is substantial interest then I could get to work on making some things a bit prettier, perhaps similar to the FreeTube layout although I haven't used FreeTube in a while.

I'd certainly be interested.

**Comment by Perflyst** [comment]
I am interested too!
Would like to see some screenshots in your future PR about your redesign.
