### ISSUE TITLE
Subtitles always showing

### ISSUE THREAD

**Issue by McMac** [iv-org/invidious#3681]
On my self-hosted invidious instance, subtitles are always showing despite them being turned off in settings. Already deleted all cookies. Where could this be stored? I never turned them on globally but may have used them on an individual video.

**Comment by unixfox** [comment]
Are you using safari? If so you might have this bug: https://github.com/iv-org/invidious/issues/2710

**Comment by unixfox** [comment]
Closing due to lack of replies.

**Comment by McMac** [comment]
> Are you using safari? If so you might have this bug: #2710

This wasn't like that a while ago. I'm using it on an iPad. But could be related to ios update. Can't make the connection with safari settings... 🤔

**Comment by McMac** [comment]
Re-read the instructions and this is also the solution on the iPad. Enable and the disable it again, then the captions aren't loaded.
