### ISSUE TITLE
[Bug] The alias of the commentators is sometimes shown instead of their nickname

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#3682]
I've been noticed that the alias of the commentators is sometimes shown instead of their nickname.
Fixed by reloading the page, after which the nicknames return to their place.
Instance where this behavior was observed: https://invidious.baczek.me/
Before the page is reloaded.
![unnamed](https://user-images.githubusercontent.com/126508037/224491432-096a1d4f-ed6c-4b57-8c80-732dd85a97b0.png)
After the page is reloaded.
![unnamed2](https://user-images.githubusercontent.com/126508037/224491439-ebd88894-f16f-4eff-ae33-7c39aa54fa37.png)

**Comment by absidue** [comment]
Unfortunately this is caused by YouTube, sometimes they return the names and other times the channel handles, when they return the channel handles the channel names aren't in the response at all, so Invidious can only show the handle in those cases.

**Comment by absidue** [comment]
@unnamed25 As mentioned in my comment above this is how it looks on YouTube too, Invidious can't magically make YouTube return information that it doesn't even return for it's own website.

This isn't an Invidious bug, Invidious is just showing you the information it gets from YouTube.

**Comment by absidue** [comment]
YouTube displays the channel handles too, you can see the full name if you click through to the channel.

Channel handles are only allowed to contain ASCII characters and have to be unique, channel names can contain any number of Unicode characters and don't have to be unique. I highly suspect that the switch to showing channel handles, is an attempt to reduce the number of scams and porn bots in comment sections, that pretend to be the channel they are commenting on.
