### ISSUE TITLE
[Bug] No thumbnails with mouseover on playbar

### ISSUE THREAD

**Issue by ZIOOIZ8** [iv-org/invidious#3703]
I have a selfhost variant in use, which also works so far quite well, but with a small problem, which I could not find a solution via Google. I installed it with a Portainer stack on a Proxmox LXC in an Intel NUC. My problem is that the little thumbnails that appear when you hover over the playbar just don't appear. I have also tried a manual install, with different install sources, with or without reverse proxy, with Docker and without, always the same error. I append a screenshot with the error. I have also seen this error on an official instance at https://redirect.invidious.io/, unfortunately I can't find the server anymore. As a browser I use the latest Firefox, also I had tested Edge, always the same error.
![Error](https://user-images.githubusercontent.com/87153886/227329854-9af0cb7a-2c34-4909-9463-6e795dddb4f4.png)

**Comment by alexanderstephan** [comment]
I also face the same issue. Interestingly, the network tab shows that the images are at least loaded into the client / browser, but somehow not displayed.

**Comment by SamantazFox** [comment]
I think that's caused by a bug in the videoJS plugin that we use for thumbnails. See: #3117

**Comment by ZIOOIZ8** [comment]
> Ich denke, das wird durch einen Fehler im VideoJS-Plugin verursacht, das wir für Thumbnails verwenden. Siehe: [ #3117 ](https://github.com/iv-org/invidious/issues/3117)

Thank you very much, this was the decisive info, the problem is solved. I changed this 3 lines in the portainer stack to:
external_port: 443
domain: domain.tld
https_only: true
