### ISSUE TITLE
[Bug] i18n: Missing translation key "Download is disabled."

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#3707]
**Describe the bug**
"Download is disabled." missing in default and fallback language https://github.com/iv-org/invidious/blob/master/locales/en-US.json

**Steps to Reproduce**
Disable downloads, open any video

**Comment by UnoYakshi** [comment]
Probably connected, too: `Error: non 200 status code. Youtube API returned status code 400`

Full message (in Docker):
```
invidious-1       | 2024-12-12 18:41:54 UTC [error] get_video: cYN9aniMhPs : Error: non 200 status code. Youtube API returned status code 400. See <a href="https://docs.invidious.io/youtube-errors-explained/"> https://docs.invidious.io/youtube-errors-explained/</a> for troubleshooting.
```
