### ISSUE TITLE
[Bug] Closed Captions are always showing for every video independent of language

### ISSUE THREAD

**Issue by McMac** [iv-org/invidious#3730]
For quite some time now every video I watch (self-hosted), I automatically get closed captioning despite not having configured any. The setting is being ignored.

**Comment by unixfox** [comment]
Are you using a safari? You might run into the same issue: https://github.com/iv-org/invidious/issues/2710

**Comment by unixfox** [comment]
Closing due to lack of replies and based on the username of the author it's possible that he is using safari.
