### ISSUE TITLE
[Bug] `Missing hash key: "lengthText" (KeyError)` when loading community tab

### ISSUE THREAD

**Issue by ahoge-enthusiast** [iv-org/invidious#3731]
**Describe the bug**
I get this error when loading https://yewtu.be/channel/UCJ46YTYBQVXsfsp8-HryoUA/community I tried some other channels but none of them have the same issue.

**Logs**
> Title: `Missing hash key: "lengthText" (KeyError)`
> Date: `2023-04-10T17:25:31Z`
> Route: `/channel/UCJ46YTYBQVXsfsp8-HryoUA/community`
> Version: `2023.04.10-5091648 @ master`
> 
> <details>
> <summary>Backtrace</summary>
> <p>
>    
> ```
> Missing hash key: "lengthText" (KeyError)
>   from /usr/lib/crystal/core/json/any.cr:100 in '[]'
>   from /usr/lib/crystal/core/json/any.cr:102:10 in 'fetch_channel_community'
>   from src/invidious/routes/channels.cr:136:26 in 'community'
>   from lib/kemal/src/kemal/route.cr:13:9 in '->'
>   from lib/kemal/src/kemal/config.cr:92:7 in 'call'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
>   from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
>   from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
>   from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
>   from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
> ```
> </p>
> </details>

**Comment by ChunkyProgrammer** [comment]
This seems to be caused by a shared video being live 
![Screenshots_2023-04-10-18-06-01](https://user-images.githubusercontent.com/78101139/231008287-46b05239-b1cb-46ee-8eb2-4e21078943ce.png)

**Comment by ahoge-enthusiast** [comment]
I found another channel where this is happening, there's no live video but there is an upcoming:

https://yewtu.be/channel/UC1V0A85U1AGi-zQCC8oE55A/community
