### ISSUE TITLE
[Bug] `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`

### ISSUE THREAD

**Issue by Kayley2009** [iv-org/invidious#3747]
Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)` Date: `2023-04-14T22:34:51Z` Route: `/search?q=trisha+paytas` Version: `2023.04.14-62c86b5 @ master` <details> <summary>Backtrace</summary> <p> ``` Could not check out a connection in 5.0 seconds (DB::PoolTimeout) from /usr/lib/crystal/core/mutex.cr:47:9 in 'checkout' from src/invidious/yt_backend/connection_pool.cr:39:7 in '_post_json' from src/invidious/search/processors.cr:12:18 in 'process' from src/invidious/routes/search.cr:56:7 in 'search' from lib/kemal/src/kemal/config.cr:92:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call' from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next' from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process' from /usr/lib/crystal/core/http/server.cr:500:5 in '->' from /usr/lib/crystal/core/fiber.cr:146:11 in 'run' from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??' ``` </p> </details>

**Comment by MikeGale** [comment]
I got that several times but only on "yewtu.be".  When I followed the other instances link and clicked on a link (2 tried) I saw the videos.
