### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by noah-frank** [iv-org/invidious#3754]
Would it be possible to include the sponsor block (https://addons.mozilla.org/de/firefox/addon/sponsorblock/) addon into this project?

**Comment by ggtylerr** [comment]
The extension already supports it. Options -> Misc. -> Add 3rd Party sites.
In case you mean integrating it into the site, this is a duplicate of...
* #1502
* #3130 
* #3519 
* #3604

**Comment by noah-frank** [comment]
Thank you for your quick reply. I tried the search but it seems that I failed. Anyway thank you I found the option in the addon settings and added my invidious instance. Works perfect :) Is the same possible with the return youtube dislike button addon?

**Comment by ggtylerr** [comment]
Refer to #2707

**Comment by noah-frank** [comment]
Thanks again 👍🏼
