### ISSUE TITLE
[Bug] DASH quality being selected results in some videos not playing

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#3756]
A URL of a video with this issue is at https://inv.zzls.xyz/watch?v=B-nluiQ1Hew. It still happens when having it not show annotations by default and with autoplay disabled. The error shown is "Playback cannot continue. No available working or supported playlists". At https://yewtu.be/watch?v=B-nluiQ1Hew, I get "The media could not be loaded, either because the server or network failed or because the format is not supported".

**Comment by Zero3K** [comment]
video.js?v=961cae2b:163 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. MediaError
(anonymous) @ video.js?v=961cae2b:163
watch:1 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.
video.js?v=961cae2b:163 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. MediaError
(anonymous) @ video.js?v=961cae2b:163
/api/v1/annotations/NbsNO7mEgso:1

1
    Failed to load resource: the server responded with a status of 500 ()

**Comment by unixfox** [comment]
Please try with another browser.

**Comment by Zero3K** [comment]
![image (8)](https://user-images.githubusercontent.com/6194332/232980511-66728e59-037e-4bfe-a5c5-54cc6fc4049e.png)

**Comment by Zero3K** [comment]
Edge doesn't have AV1 support built in while Chrome does.

**Comment by unixfox** [comment]
I think we should probably create a separate github issue for fixing this problem.
