### ISSUE TITLE
Add support for content filtering

### ISSUE THREAD

**Issue by lyndalopez544** [iv-org/invidious#376]
- Provide support for blocking certain keywords, channels or users from being totally accessed from the search results or through direct URL access.
- Provide support for family search.

**Comment by omarroth** [comment]
Likely duplicate of #344.

I'm not sure what you mean by "family search". Is this something available on YouTube or in a similar app?

**Comment by aurora-of-earth** [comment]
@omarroth Yes, I mean adult content filtering.
