### ISSUE TITLE
[Enhancement-Bug] Make it easier for invidious users to delete playlists by adding delete buttons next to links in the "view all playlists" feed.

### ISSUE THREAD

**Issue by AahanKotian** [iv-org/invidious#3762]
![image](https://user-images.githubusercontent.com/106942580/233255944-76b1366d-9d62-4f35-9c3a-e949e4e898ec.png)

I have this playlist saved on invidious but I am unable to delete it and when I attempt to click the link, go in and delete the individual playlist it displays the following: "Could not extract playlistSidebarRenderer." Possibly because the original playlist that was displayed on youtube had already been removed.

![image](https://user-images.githubusercontent.com/106942580/233258738-3bef0c18-3e05-4802-927e-8081031f17bd.png)

Please add a mechanism for us to be able to delete playlists from the feed in which delete buttons are displayed next to the links in the feed as opposed to solely within each individual playlist page like this:

![image](https://user-images.githubusercontent.com/106942580/233257102-9330480b-445f-4fe4-bdeb-d64d0038c002.png)

**Comment by unixfox** [comment]
Please post the invidious version (can be found at the bottom of the page).

**Comment by Akotian79** [comment]
![image](https://user-images.githubusercontent.com/106942580/233412893-c166e8c9-59b9-47e0-ba68-21edda08d43f.png)

it is yewtu.be

![image](https://user-images.githubusercontent.com/106942580/233413401-ecc0c9a3-8679-4053-9333-75f51afa3959.png)

**Comment by Akotian79** [comment]
If this was taken care of I would be more than happy.

**Comment by unixfox** [comment]
Do not bump issues, it doesn't help.
