### ISSUE TITLE
[Bug] Video description not showing up

### ISSUE THREAD

**Issue by ForceConstant** [iv-org/invidious#3765]
I swear I used to be able to see the video description, but now I don't see it. Am I crazy, or maybe a setting got toggled?

Current version: 2023.04.05-525e4bd @ master

**Comment by SamantazFox** [comment]
Please see: https://github.com/iv-org/invidious/issues/3660
Problem has been fixed on April 10th, so you'll have to update or wait for the instance to be updated.
