### ISSUE TITLE
[Question] Slow Streaming

### ISSUE THREAD

**Issue by Abyssgrowth** [iv-org/invidious#3771]
Since around two weeks i'm experiencing really poor connection to all the invidious instances.
I've been using yewtu.be for months, then when the issues started happening switched to vid.puffyan.us however while the connection was slightly more stable here it's still a complete mess, videos not loading, loading but randomly stop playing, have to reload the tab then it works again or doesn't, haven't changed anything on my end so i don't understand where this issues suddenly came from.
Anyone else is experiencing major connection issues? I don't want to switch back to youtube.com because google is evil, but what good is a service if i can't use it?

**Comment by unixfox** [comment]
Are you using DASH?

**Comment by Abyssgrowth** [comment]
> Are you using DASH?
> 
> If so you might running into this issue: #3666

Oh you must be talking about the dash video quality, yes i preffer this option in 1080p the videos have decent quality while 720p is looking bad/unclear.
But why does this issue happen just now since it worked normaly before?

![Capture](https://user-images.githubusercontent.com/125774114/234961395-2f0d2610-d14c-4769-ab4d-f4dc382c3b28.PNG)

**Comment by unixfox** [comment]
> > Are you using DASH?
> > 
> > If so you might running into this issue: #3666
> 
> Oh you must be talking about the dash video quality, yes i preffer this option in 1080p the videos have decent quality while 720p is looking bad/unclear.
> But why does this issue happen just now since it worked normaly before?
> 
> ![Capture](https://user-images.githubusercontent.com/125774114/234961395-2f0d2610-d14c-4769-ab4d-f4dc382c3b28.PNG)
> 

For yewtu.be that's a separate issue: https://github.com/unixfox/invidious-custom/issues/60

I'll close this issue as there is already an opened issue for the slow loading time that apply to all instances.
