### ISSUE TITLE
[Bug] Trending broken in 2023.04.30-eefc8bb

### ISSUE THREAD

**Issue by bbsixzz** [iv-org/invidious#3774]
Latest docker update 2023.04.30-eefc8bb breaks trending videos, all categories are empty.

**Comment by bbsixzz** [comment]
Also broken in version: 2023.04.30-97e3938

**Comment by adequacy1** [comment]
Also having this bug in my own instance (Arch linux, up-to-dated)

**Comment by SamantazFox** [comment]
Yeah, sorry, my bad, I merged my last PR hastily, without proper testing.
I'll try to fix that today.
