### ISSUE TITLE
[Question] Autoplay parameter for embed player ? 

### ISSUE THREAD

**Issue by stephane-r** [iv-org/invidious#3779]
Hi community,

Do you know if it's possible to use an `autoplay` parameter for embed URL ? For example : 

`https://invidious.snopyta.org/embed/vBytxZ6X3Rc?autoplay=1 // or true ?`

I'm surprised this isn't possible? Maybe it's another parameter ?

**Comment by unixfox** [comment]
Works fine for me, it's just that autoplay is disabled on the browser by default, so that's why if the user has never interacted with the website before the autoplay won't work.
