### ISSUE TITLE
Ability to manage playlists for Google accounts

### ISSUE THREAD

**Issue by spriteclad** [iv-org/invidious#378]
Might be related to #114?

Basically, have a link/button on every video page, allowing you to add said video to any of your playlists linked to your Google account if you're signed in.

Also, if possible, add the ability to rename playlists, move videos in playlists, and remove videos from playlists that the logged-in user has made within Invidious, if possible. It would save me a lot of time since I wouldn't have to go back and forth between YT and Invidious.

**Comment by omarroth** [comment]
The functionality requested here is very similar to requested in #114. For clarity, I'd probably recommend changing the title to something like "Manage playlists for Google accounts". Expect this to be added alongside #114.
