### ISSUE TITLE
[Bug] Cannot select OLDEST video

### ISSUE THREAD

**Issue by 99thim** [iv-org/invidious#3802]
BUG:--
Choosing to have the videos of a channel sorted by OLDEST option generates error message on all instances for Chrome/Firefox/Brave.

ERROR MESSAGE:--
Could not extract JSON. Youtube API returned error 500 with message:
"RET_CHECK failure (video/youtube/channels/frontend/shared/feed_filler/feed_filler.cc:200) failed_aggregates < aggregates.size() (1 vs. 1) All aggregates failed"

OS/Browser:--
MacOS Bigsur
Chrome/Firefox/Brave

**Comment by unixfox** [comment]
Closing as there is already an issue opened: https://github.com/iv-org/invidious/issues/3371

**Comment by SamantazFox** [comment]
Reopening because the other issue is different.
Sort by oldest was removed by youtube, but now they added it back!
