### ISSUE TITLE
[Bug] Maxxing out CPU and hanging on startup

### ISSUE THREAD

**Issue by termermc** [iv-org/invidious#3808]
**Describe the bug**
Today after updating, my instance started hanging infinitely with 100% CPU on startup. The server does not start, only hangs with 100% CPU usage. There are no logs being written to the log file.

After I discovered this, I updated and recompiled it again, but the issue still persisted. Right now I'm trying to find out possible reasons for it, but I have very little information to go off of. Hopefully someone else has also encountered this and knows more than me.

I've been using my instance for a couple of years and I have a local account and a fair bit of data in the DB. This could be part of it, but I don't know how that would affect it.

**Steps to Reproduce**
Try compiling the latest release (as of 2023/05/15). I'm not sure if it's just me or not.

**Logs**
No logs available.

**Screenshots**
No screenshots available.

**Additional context**
Invidious version: `commit 3a54e9556b0cd28fd224db5801f8141a68108c13 (HEAD -> master, origin/master, origin/HEAD)`

Server: Ubuntu Server 22.04 running Linux 5.4.0-137-generic

Crystal:
```
Crystal 1.8.2 [7aa5cdd86] (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

-----

I'm willing to help out as best as possible. I don't know Crystal but I can read its code fairly easily if that's of any help.

**Comment by unixfox** [comment]
Are you sure the DB version didn't change?

**Comment by termermc** [comment]
Part of my update script runs DB migrations, but just to make sure, I just ran them again. Nothing changed.

**Comment by unixfox** [comment]
I'm talking about the postgresql version, please post it here.

And if possible check if the version was upgraded or not.

**Comment by unixfox** [comment]
Also make sure you are not compiling invidious with QUIC, by default with the `make` command it disables it.

**Comment by termermc** [comment]
I'm running postgresql `12+214ubuntu0.1`.

Here's my build script that gets run everyday at 00:00 GMT:

```bash
#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

currentVersion=$(git rev-list --max-count=1 --abbrev-commit HEAD)
git stash
git pull
for i in `git rev-list --reverse --abbrev-commit $currentVersion..HEAD` ; do file=./config/migrate-scripts/migrate-db-$i.sh ; [ -f $file ] && $file ; done
shards install --production
echo "Compiling..."
crystal build src/invidious.cr --release
```

**Comment by unixfox** [comment]
See my comment above you are not compiling invidious the proper way: https://github.com/iv-org/invidious/issues/3808#issuecomment-1547247410

**Comment by termermc** [comment]
My script was the correct way it was compiled when I first set it up. I just compiled it with make and it worked properly. Thanks for the info.
