### ISSUE TITLE
Vevo music videos fail to load in Invidious via Yattee on iOS

### ISSUE THREAD

**Issue by 34candos** [iv-org/invidious#3810]
**Describe the bug**
Some videos (mostly music, and especially Vevo videos) fail to load in Yattee app using Invidious.

Note: this is not an app bug; all these music videos were working just fine with Yatte when connecting via Piped. I switched to Invidious to use an account I had, and that's when the videos stopped opening.

**Steps to Reproduce**
1. Go to Yattee app on iOS
2. Click on Vevo music videos
3. See error "cannot load"

**Comment by 34candos** [comment]
Once again, this does not seem like an app bug, but if you don't think that's worth looking into, ok.

**Comment by unixfox** [comment]
For the bug report to be valid you have to demonstrate that the error comes from the invidious software/backend and not only from yattee.

We unfortunately have no time to investigate into the issues of other applications that rely on invidious.

**Comment by ChunkyProgrammer** [comment]
Might be related to the livestream issue if yattee uses HLS?
