### ISSUE TITLE
[Bug] The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#3822]
### For everyone:

We are fully aware of this issue, please comment only if you have new info to bring on. Please refrain from opening new issues.
YouTube has recently started to care about alternative frontends like Invidious and is trying to block them.
This currently only affects some public Invidious instances, so if you have the resources we recommend installing Invidious on your own personal computer or server: https://docs.invidious.io/installation/

### For Invidious instance maintainers: 

Please read this comment for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

If you want to discuss or read for other solutions: https://github.com/iv-org/invidious/issues/3915

-------

BUG: `The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`

When trying to loading any video on the invidious.vpsburti.com instance, this error is shown:
```
Title: `The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`
Date: `2023-05-27T08:21:28Z`
Route: `/watch?v=Nx-ougrNm50&listen=1`
Version: `2023.05.14-3a54e95 @ master`

<details>
<summary>Backtrace</summary>
<p>

The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)
  from /usr/share/crystal/src/array.cr:114:31 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:377:10 in 'fetch_video'
  from src/invidious/videos.cr:365:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
</p>
</details>
```

**Comment by unixfox** [comment]
It appears that YouTube is doing some breaking changes in a rollout way, which means it doesn't affect all the instances.

I'm trying to find an affected IP address where I could debug the issue. For now it seems like people that are hosted at hetzner (invidious.nerdvpn.de & invidious.vpsburti.com) are affected.

**Comment by dellasorte** [comment]
I've got this as well

`Title: `The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`
Date: `2023-05-27T06:08:04Z`
Route: `/watch?v=QncYBP785uA`
Version: `2023.05.25-381a0e3 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)
  from /usr/share/crystal/src/array.cr:114:31 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:377:10 in 'fetch_video'
  from src/invidious/videos.cr:365:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>`

**Comment by unixfox** [comment]
@dellasorte which provider are you using? Or is it a public instance? Which one?

**Comment by unixfox** [comment]
For now it seems like IPv6 addresses may not be impacted.

As you are probably using IPv4 when you are running invidious in docker, you might want to look into enabling ipv6 in docker, there are multiple tutorials available here:
- https://gdevillele.github.io/engine/userguide/networking/default_network/ipv6/
- There is also the possibility of using this intermediate software: https://github.com/robbertkl/docker-ipv6nat

Try this only if your server supports IPv6 (most of the provider offer ipv6 nowadays. Try `curl -I -6 ipv6.google.com` and if you don't get any error you have ipv6.

**Comment by unixfox** [comment]
After a bit more dinging into the issue, I've found that even on the official www.youtube.com website you get the error:
![image](https://github.com/iv-org/invidious/assets/4016501/cc9e07eb-296f-4d76-b046-5ce27e987437)

I'm not sure if it's an error on their side or a way to "shadow ban" an IP address. For now I don't have a solution except from using another IP address like described above.

**Comment by lo-kiss** [comment]
Started noticing the same errors today as well at https://invidious.sethforprivacy.com

**Comment by unixfox** [comment]
> Not sure if this is related, but [yewtu.be](https://yewtu.be) started giving empty videos with "This content is not available", tested on multiple videos from different channels. ![2023-06-02 10_54_19-ORDER __ ULTRAKILL - Touhou Remix - Invidious – Mozilla Firefox](https://user-images.githubusercontent.com/51241486/242838147-630d053a-7271-478a-96d4-b137c8db4a6f.png) [y.com.sb](https://y.com.sb) and [inv.vern.cc](https://inv.vern.cc) seem affected from the original error.

Yes it's related.

I've temporarily fixed the issue on yewtu.be by applying the solution in https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621, but there is a big probability that the issue will arise again in a few hours.

**Comment by Ashirg-ch** [comment]
Could it be useful to have a script that automatically changes the IPv6 address and hook it up to a cronjob?

**Comment by unixfox** [comment]
> Could it be useful to have a script that automatically changes the IPv6 address and hook it up to a cronjob?

There is a script just for that :D: https://github.com/ycd/ipv6-rotator

But I did not test if changing the IP address in the same range fixes the issue or not.

**Comment by gamer191** [comment]
@unixfox over on yt-dlp discord, the one user who's getting the new "this content isn't available" [video](https://www.youtube.com/watch?v=M5t4UHllkUM) claims to still be able to access youtube in a browser. As such, next time yewtu.be breaks, can you please check whether it can still access youtube in a browser?

**Comment by Trit34** [comment]
[This video](https://www.youtube.com/watch?v=mQYL_88MOe0) is available on YT from my home’s computers, but not on my favorite Invidious instance ([FDN’s](https://invidious.fdn.fr/watch?v=mQYL_88MOe0)).

**Comment by Kreuger** [comment]
> @unixfox over on yt-dlp discord, the one user who's getting the new "this content isn't available" [video](https://www.youtube.com/watch?v=M5t4UHllkUM) claims to still be able to access youtube in a browser. As such, next time yewtu.be breaks, can you please check whether it can still access youtube in a browser?

I use Invidious in Edge on my Xbox. It is having the exact same problem. The odd instance will work  if you keep going through the list but thats a huge pain in the ass.

**Comment by unixfox** [comment]
> @unixfox over on yt-dlp discord, the one user who's getting the new "this content isn't available" [video](https://www.youtube.com/watch?v=M5t4UHllkUM) claims to still be able to access youtube in a browser. As such, next time yewtu.be breaks, can you please check whether it can still access youtube in a browser?

@gamer191 like in https://github.com/iv-org/invidious/issues/3822#issuecomment-1565457284I I'm getting the new video saying "content unavailable" on www.youtube.com.

**Comment by Daxy7** [comment]
Hmm, after refreshing the page on this bug 2-4 times the video n audio responds 
and playback works fine for whole duration.

<details>
<summary>Details</summary>
<p>
Title: `The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`

Date: `2023-06-09T12:36:14Z`

Route: `/watch?v=PQ_dmFUR2N8&nojs=1`

Version: `2023.06.04-c8b7bf2 @ master`

   
```
The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)
  from /usr/lib/crystal/core/json/any.cr:102:10 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:357:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by iambeingtracked** [comment]
> > Not sure if this is related, but [yewtu.be](https://yewtu.be) started giving empty videos with "This content is not available", tested on multiple videos from different channels. ![2023-06-02 10_54_19-ORDER __ ULTRAKILL - Touhou Remix - Invidious – Mozilla Firefox](https://user-images.githubusercontent.com/51241486/242838147-630d053a-7271-478a-96d4-b137c8db4a6f.png) [y.com.sb](https://y.com.sb) and [inv.vern.cc](https://inv.vern.cc) seem affected from the original error.
> 
> Yes it's related.
> 
> I've temporarily fixed the issue on yewtu.be by applying the solution in [#3822 (comment)](https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621), but there is a big probability that the issue will arise again in a few hours.

That seems to be the thing happening with Piped: https://github.com/TeamPiped/Piped/issues/2487

Google is doing something VERY sussy atm

**Comment by trentwiles** [comment]
This hit me hard. OVH only gives you a /128 block for the IPv6 space, so I could mitigate this for a while using that, but it would be pointless if I'm going to get IP blocked again on IPv6. :middle_finger: <---- that's for you Google

**Comment by trentwiles** [comment]
If there's some sort of way to set up invidious with a SOCKS5 proxy, I could probably rotate IPs on DigitalOcean/Vultr.

**Comment by ddvarpdd** [comment]
> This hit me hard. OVH only gives you a /128 block for the IPv6 space, so I could mitigate this for a while using that, but it would be pointless if I'm going to get IP blocked again on IPv6. 🖕 <---- that's for you Google

You could try getting a proper IPv6 range from tunnel broker such as [Hurricane Electric](https://tunnelbroker.net/).

**Comment by Daxy7** [comment]
Is this issue resolved? I live in the UK and today so far no errors

**Comment by ccuser44** [comment]
I'm getting this issue too and it's quite breaking, most instances just don't work, there are some that do.

Could this be related to the recent Youtube takedown thing?

**Comment by marcussacana** [comment]
> **[ccuser44](/ccuser44) ** commented

Basically, it appears that Google is implementing an IP ban on Invidious hosts, but it can be bypassed by using a random IPv6 address. I find it somewhat strange that IP bans are still being used nowadays; it's a technique reminiscent of a kid running a Minecraft server.

**Comment by Veeno** [comment]
Suggestion for your sanity: specialcase the Invidious page for this error so it links to this issue rather than to a new issue submission form (at least temporarily).

**Comment by tempname1024** [comment]
I've had success routing outbound invidious traffic over shared VPNs; blending traffic with 'legitimate' users and connecting from non-Hetzner/OVH/DO address space works well for now.

```
PostUp = ip route add default dev %i table 5280
PostUp = ip -6 route add default dev %i table 5280

PostUp = ip rule add from (wg v4 address) table 5280
PostUp = ip -6 rule add from (wg v6 address) table 5280
PostUp = ip -4 rule add uidrange 991-991 lookup 5280
PostUp = ip -6 rule add uidrange 991-991 lookup 5280

PostDown = ip rule del from (wg v4 address) lookup 5280
PostDown = ip -6 rule del from (wg v6 address) lookup 5280
PostDown = ip -4 rule del uidrange 991-991 lookup 5280
PostDown = ip -6 rule del uidrange 991-991 lookup 5280

Table = off
```

reCAPTCHA profiles addresses at the /64 so it probably won't be long until we see that on YT as well, if they aren't already.

**Comment by trentwiles** [comment]
I'm not smart when it comes to networking, where do you add these lines? Also, how do you authenticate with WG? You can't just connect to the IP without a private key right?

**Comment by tempname1024** [comment]
> I'm not smart when it comes to networking, where do you add these lines? Also, how do you authenticate with WG? You can't just connect to the IP without a private key right?

To keep wireguard from updating the system's default routing table we disable that functionality with `Table = off`, create our own table caled `5280`, add wiregurad's addresses, and create a rule to lookup table `5280` for traffic which originates from the user running invidious, in my case the user ID is 991. These lines are added to the `Interface` section.

**Comment by ccuser44** [comment]
> > If there's some sort of way to set up invidious with a SOCKS5 proxy, I could probably rotate IPs on DigitalOcean/Vultr.
> 
> Double that. You could also use a “residential IP” proxy service, or even one of the mobile proxy ones (which use mobile operators networks and usually change IPs every couple minutes for you). This might not work well with proxying video traffic though, and I'm afraid it also might be not too cheap nowadays.

Are you sure the video traffic has to be proxied at all?

**Comment by unixfox** [comment]
I have created a separate issue for freely discussing how to circumvent the current blockage: #3915.

This way people subscribed in this issue will not be "spammed" and we can keep this issue for tracking the new ways to really solve the original issue, not temporary workarounds.

Please refrain from talking about temporary workarounds here and use #3915 instead. Thank you

**Comment by Quix0r** [comment]
Videos can still be viewed on my instance, but what I have noticed is that `/feed/popular` is not being updated.

**Comment by Fish25op** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/3719

**Comment by unixfox** [comment]
Closing as youtube is now blocking projects based on it using other methods: https://github.com/iv-org/invidious/issues/4045

**Comment by kurukurukuru** [comment]
Seems like this is back. Happening on multiple instances, across multiple videos.
This started happening around 2AM EST today. Eventually if I switch instances enough there are a few which are not blocked. 

Instances which are blocked:
https://par1.iv.ggtyler.dev/
https://inv.us.projectsegfau.lt 
https://invidious.io.lol/
https://invidious.no-logs.com/
https://yt.cdaut.de
https://vid.priv.au
https://invidious.einfachzocken.eu/
https://onion.tube/
https://yt.oelrichsgarcia.de

Instances which work:
https://invidious.fdn.fr/
https://invidious.lunar.icu
https://invidious.nerdvpn.de

**Comment by AaronDaOne** [comment]
> Instances which are blocked: 

Also: https://yewtu.be/

**Comment by unixfox** [comment]
Oops I thought I did setup everything according to the guide that I wrote myself for bypassing youtube but I forgot a parameter lol.
It's fixed, yewtu.be is back.

**Comment by MXB2001** [comment]
invidious.private.coffee also blocked
invidious.drgns.space is not blocked

**Comment by Quix0r** [comment]
At least https://yt.cdaut.de seem to work again (only the popular feed is disabled, maybe due to privacy concerns).

**Comment by unixfox** [comment]
Yes there is an ongoing effort from me to alert the public instances.

https://github.com/iv-org/documentation/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc

Please only comment if you have something useful to say about the bug itself. Tracking all the working instances is not. We are planning to offer this functionality automatically: https://github.com/iv-org/instances-api/pull/44

**Comment by 253153** [comment]
Hello, I am the owner of invidious.io.lol, how do I fix this? Please !!

**Comment by unixfox** [comment]
> Hello, I am the owner of invidious.io.lol, how do I fix this? Please !!

Follow our tutorial: https://docs.invidious.io/ipv6-rotator

**Comment by theAkito** [comment]
Just FYI: I concur.

Some things work, like e.g. some playlists, but for example the videos in it don't. ☹️

**Comment by emcdarby** [comment]
> Oops I thought I did setup everything according to the guide that I wrote myself for bypassing youtube but I forgot a parameter lol. It's fixed, yewtu.be is back.

I was using yewtu.be and again it's not fixed as I'm getting the "Can’t load the video on this Invidious instance. YouTube is currently trying to block Invidious instances. [Click here for more info about the issue](https://github.com/iv-org/invidious/issues/3822)." error.

**Comment by CryptorClub** [comment]
Thank you for guide. Just enable ipv6 on my instance https://y0u.tube

How to enable ipv6 DigitalOcean guide 
https://docs.digitalocean.com/products/networking/ipv6/how-to/enable/

**Comment by johnpc** [comment]
This just started affecting my personal instance (I am the only user) within the last couple of days. I tried a handful of public instances as well facing the same issue, even with ipv6

**Comment by marcxm** [comment]
@johnpc same here ... since couple of days I am unable to watch videos via self-hosted instance of Invidious. Day or two ago it was possible to view videos by just refreshing web page couple of times, but now it's dead.

**Comment by pencilcheck** [comment]
Some instances aren't working now just FYI.

**Comment by theAkito** [comment]
This periodically happens now and it hits very hard. I basically cannot find any instance in my case, that works, when it is time again for it to not work...

**Comment by Kreuger** [comment]
> This periodically happens now and it hits very hard. I basically cannot find any instance in my case, that works, when it is time again for it to not work...

Theyre literally going after 3rd party ad blocking solutions. Its gonna be rough for the next while. The downside of an open source project such as this is that they can see how things are circumvented. And since youtube is closed, we cant see how they block it.

**Comment by iAmInActions** [comment]
I found a temporary (very hacky) fix to get around this. I dont recommend it but for me it seems to be working so far.
To put it simple, the API that returns the invalid value is the android api. You can force invidious to always use the fallback api (which will make it slower!) by commenting out some lines in `src/invidious/videos/parser.cr`.
More specifically, starting at
```
  if reason.nil?
    # Fetch the video streams using an Android client in order to get the
```
and ending at 
```
  # Last hope
```

**Comment by unixfox** [comment]
Locking this one because the discussion should happen here now: https://github.com/iv-org/invidious/issues/4045
