### ISSUE TITLE
[Bug] Playlist Pages have disappeared

### ISSUE THREAD

**Issue by NoxStellans** [iv-org/invidious#3848]
**Bug:** I have multiple playlists containing over 100 videos, and one has over 200 videos. Just yesterday, the second pages of all 100+ video playlists disappeared. Strangely, the 200+video playlist still has the third page, but all second pages are gone.

**Steps to Reproduce:**

1. Go to the homepage.
2. Click on playlists.
3. Click on any playlist with 100+ videos.

**Screenshots:**
![image](https://github.com/iv-org/invidious/assets/130122911/9ba85f7c-90bb-4862-aa9d-b14fbcc575c5)
![image](https://github.com/iv-org/invidious/assets/130122911/9bbfd9a5-5c52-4ba4-a9c2-7e5610627161)

**Browser:** Firefox
**OS:** Windows 10
**Instance:** kavin.rocks

**Comment by ChunkyProgrammer** [comment]
Likely a regression from #https://github.com/iv-org/invidious/pull/3807

**Comment by NoxStellans** [comment]
What would you suggest I do?

**Comment by ChunkyProgrammer** [comment]
> What would you suggest I do?

You'd need to wait for an update to invidious (your playlist data should be unaffected)

**Comment by NoxStellans** [comment]
Fair enough, thanks!

**Comment by NoxStellans** [comment]
I'm sorry, but this issue is still affecting me.

**Comment by ChunkyProgrammer** [comment]
Looks like kavin.rocks was last updated on 2023-07-05 so you'll have to wait for the instance to be updated for it to work (You can check this by looking at the Current Version in the footer)

**Comment by MrFlyingToasterman** [comment]
@ChunkyProgrammer Thank you for fixing the problem! ❤️
