### ISSUE TITLE
Configure Log level

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#385]
Add an option to set the log level. For example I do not want `GET` request logged.
Maybe following log levels:
Error, Warn, (Normal / Default), Debug

I do not know if there are already any debug logs which you may use somewhere for testing, if not just drop debug.

**Comment by Perflyst** [comment]
Dunno if possible but if the log only shows exception with error level it could also show a few lines before and after the exception of debug log.

**Comment by Perflyst** [comment]
It would be interesting here to have some default privacy policies for each log level.

**Comment by unixfox** [comment]
Still interested
