### ISSUE TITLE
[Announcement] hmac_key parameter in config.yml mandatory by July 1st

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#3854]
In the effort of fixing issues like in #3540, by the July 1st we are going to make the `hmac_key` mandatory in the `config.yml` file. After this date, Invidious will not start without this parameter configured.

As a reminder, `hmac_key` is a key that needs to be generated from random characters using the command `pwgen 20 1` or `openssl rand -hex 20`. This is explained in the documentation: https://docs.invidious.io/installation/#post-install-configuration

**Comment by SamantazFox** [comment]
Note: this can be set with the environment variable `INVIDIOUS_HMAC_KEY` too!
