### ISSUE TITLE
[Question] See my changes in localhost

### ISSUE THREAD

**Issue by broquemonsieur** [iv-org/invidious#3858]
I have experience with docker but not with Crystal (Ruby? yes)

What am I doing wrong?

1. Change the following line in `en-US.json` as a sanity check of proof:
``` "Watch on YouTube": "Watch on YouTube (I'm proof that my changes are live!)",```
2. `docker-compose up`
3. The termainl output says:
```invidious-invidious-1     | [development] Invidious is ready to lead at http://0.0.0.0:3000```
4. So I go to localhost > Trending page (so far so good) and choose a video
5. To my surprise I see that "Watch on YouTube" appears instead of my message

Additional info:
My FireFox Inspector shows this in the Network pane for my Request Headers: `Accept-Language en-US,en;q=0.5`

**Comment by unixfox** [comment]
See more here for more info that could help you: https://github.com/iv-org/invidious/issues/3800

**Comment by broquemonsieur** [comment]
Success, thanks!

**Comment by SamantazFox** [comment]
As a side note: you likely have an outdated repo.
The key (string on the left of the colon) `"Watch on YouTube"` was replaced by `"videoinfo_watch_on_youTube"`.

**Comment by broquemonsieur** [comment]
Gotcha thanks, will `git pull` from upstream any chance I get
