### ISSUE TITLE
Certain DASH videos fail to load on FF65

### ISSUE THREAD

**Issue by BlipRanger** [iv-org/invidious#386]
Some, but not all DASH videos fail to load on FF65 with the error:
`Specified “type” attribute of “application/dash+xml” is not supported. Load of media resource /api/manifest/dash/id/x5bnTPpKe4g?local=true failed.` 
This is on a self hosted instance (docker) running behind Traefik and there are no errors sever side. In fact, it seems to be serving the first portion of the DASH stream with no issues, however the browser is failing to begin playing. I have also found that `/api/manifest/dash/id/x5bnTPpKe4g` can actually be downloaded and played by VLC. There are some DASH videos that play just fine and I cannot tell what the difference is so far.

**Comment by omarroth** [comment]
Sorry for the late response.

If you're running behind something, you might take a look at #330 to see if the connection is somehow truncated. Are you able to play `/api/manifest/dash/id/x5bnTPpKe4g?local=true` in VLC in another browser, or are they all affected by this issue?
