### ISSUE TITLE
YouTube legal team contacted us

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#3872]
![image](https://github.com/iv-org/invidious/assets/47571719/362333a1-0de0-4b7e-b3b3-7559c26c11be)

![image](https://github.com/iv-org/invidious/assets/47571719/b66adf38-1f69-46c3-8cf6-bb2e997cc8e5)

![image](https://github.com/iv-org/invidious/assets/47571719/4e054fca-0630-4df6-b305-b2884b578f99)

They don't understand that we never agreed to any of their TOS/policies, they don't understand that we don't use their API.

**What now?**

Things will continue normally until they can't anymore.

Assume it's just the start.

Assume they'll ask GitHub to takedown the repos (if so go to our Gitea https://gitea.invidious.io/iv-org ).

Assume the team wont be able to work on Invidious.

You know what you have to do.

May Invidious live and prosper, with, or without us.

PS: We won't do anything unless we have to.

PS-2: If we are forced to quit, any funds remaining will go to Framasoft (and maybe some other organization working on FOSS/privacy)

---

**Edit:** Some people people asked me why I’m not stopping my work on Invidious, here’s the explanation: https://blog.thefrenchghosty.me/posts/im-not-invidious/

---

**Edit 2:**

**New websites and creators that talked about this (sorted by the order by which we discovered them):**

- TorrentFreak (news website): https://torrentfreak.com/youtube-orders-invidious-privacy-software-to-shut-down-in-7-days-230609/ (great coverage)
- AlternativeTo (news website): https://alternativeto.net/news/2023/6/youtube-legal-team-asked-invidious-developers-to-take-down-the-service-within-7-days/
- Lous Rossman (YouTube creator): https://redirect.invidious.io/watch?v=PTmZv7-eMrE (great coverage)
- gHacks (news website): https://www.ghacks.net/2023/06/10/google-is-threating-privacy-friendly-youtube-frontend-invidious/ (great coverage)
- Eli the Computer Guy (YouTube creator): https://redirect.invidious.io/watch?v=kMSqTAxptTI (great coverage - offtopic after 17:45)
- Vice (news website - the article was on the [homepage](https://github.com/iv-org/invidious/assets/47571719/c147d085-1298-4330-b82a-b056866edf3a)): https://www.vice.com/en/article/88xxex/youtube-tells-open-source-privacy-software-invidious-to-shut-down (great coverage - the reporter, Jules Roscoe, contacted us)
- Techlore (YouTube creator): https://redirect.invidious.io/watch?v=AxV8Q-iBIj0&t=748

**Comment by projjalm** [comment]
Reddit charging millions for their API calls, YouTube blocking ad-blockers, and now this. I see a pattern here, they're trying very hard to veer users out of their platforms to an user-respecting alternative. I sense a similar letter to Piped, NewPipe, or any of the more popular youtube clients.  
But as always, I hope the very best for Invidious. its what i daily-drive for watching videos. If the worst happens in this case, Invidious will go dark and I'll discontinue viewing youtube, at least on desktop, for good.  
Lots of love to you and the contributors for gifting us such a simple and lovely frontend. <3

**Comment by ahcheing** [comment]
> They don't understand that we never agreed to any of their TOS/policies

I dont know what their API terms are but I assume/suspect that youtube would argue that since you are accessing their service you are also consenting to their terms of service. The terms of service are the terms under which they make their content available in the first place, if you don't agree to the terms you are not supposed to be accessing their services. 

I am not saying I agree with that, but thats how they think. 

https://www.youtube.com/static?template=terms

> Permissions and Restrictions 
> You may access and use the Service as made available to you, **as long as you comply with this Agreement** and applicable law...
> The following restrictions apply to your use of the Service. You are not allowed to ...
> access, reproduce, download, distribute, transmit, broadcast, display, sell, license, alter, modify or otherwise use any part of the Service or any Content except: (a) as expressly authorized by the Service; or (b) with prior written permission from YouTube and, if applicable, the respective rights holders;

**Comment by yamilt351** [comment]
I can't believe it, I've been using Invidious for a while now as an excellent replacement for the crap that is YouTube, and I really want to congratulate you for bringing privacy and peace of mind to thousands of us who are aware of the garbage that Google and its 'services' represent. It's a shame that these things happen, I guess we'll have to wait and see what happens.

**Comment by pukkandan** [comment]
> I dont know what their API terms are but I assume/suspect that youtube would argue that since you are accessing their service you are also consenting to their terms of service. The terms of service are the terms under which they make their content available in the first place, if you don't agree to the terms you are not supposed to be accessing their services.

But the mail is specifically referring to developer API terms, not the website's terms

**Comment by Growebis** [comment]
YouTube doing what they are known for, making shitty decisions for no reason.

**Comment by jasons393** [comment]
Now I'm wondering what their reaction would be when they found out that we never used the API and agreed to the TOS.

**Comment by TheAssassin** [comment]
**Dear users, please stop posting speculation in this thread or otherwise post off-topic.** I'm sure the team appreciates your support, but there are better ways than bloating this thread. Feel free to show your :heart: the initial post!

As a member of Team NewPipe, I'd like to offer you folks to get in touch. We have closely monitored previous situations (e.g., youtube-dl) and can provide some (non-professional) feedback about the legal aspects. I do not see any imminent legal threat in this e-mail that would require immediate action. I further do not expect GitHub to permit any takedown requests, since this is clearly _not_ about copyright (i.e., DMCA does not play a part in this). I am interested in resolving this in the best possible way for Invidious. You can find me on IRC in NewPipe's channel or reach me or the team via e-mail (I also have PGP set up).

Finally, I kindly ask @TheFrenchGhosty and the team to lock this thread to make sure relevant updates can be found easily.

**Comment by selfisekai** [comment]
reytan dev here. laughing my ass at so many details here. they make a whole block of text accusing that you are using the API wrong, to at the very end say "*if* you are accessing or using YouTube API Services"...

I have even decided to look up these terms and how they define this shit.
>"API Client" means a website or software application (including a mobile application) developed by you that accesses or uses the YouTube API Services.

you might wonder what [the definition of API services](https://developers.google.com/youtube/terms/developer-policies#definition-youtube-api-services) is.
>"YouTube API Services" means (i) the YouTube API services [...]

the very definition of this is a fallacy. and the e-mail phrasing suggests that API services is when you get assigned your own keys (that is, not innertube). thanks for confirming, youtube legal team!

**Comment by bkw777** [comment]
> **Dear users, please stop posting speculation in this thread or otherwise post off-topic.** I'm sure the team appreciates your support, but there are better ways than bloating this thread. Feel free to show your ❤️ the initial post!
> 
...
> 
> Finally, I kindly ask @TheFrenchGhosty and the team to lock this thread"

"You know, after I get to say what I want I mean. But aside from me, everyone else shut up. Instead you can speak in this method I approve of. On this repo that isn't even mine."

Do you hear yourself?

**Comment by ggtylerr** [comment]
> "You know, after I get to say what I want I mean. But aside from me, everyone else shut up. Instead you can speak in this method I approve of. On this repo that isn't even mine."
> 
> Do you hear yourself?

They're asking to lock the thread to prevent off-topic posts. They are _not_ demanding it nor are they asking to be allowed to post afterwards.

**Comment by Darin755** [comment]
You need a lawyer

**Comment by SamantazFox** [comment]
> BTW, what was your reply? GitHub is not safe for code like this. Start taking it away to self host as well, probably.

@vdbhb59 
1) We didn't reply. We're waiting to see how it goes. As mentioned multiple times above, we don't use their official API, so they're accusing us of something that hasn't happened.
2) Our code is already mirrored on our gitea: https://gitea.invidious.io/iv-org/, and I already have registered my GPG keys there, just in case. If anything would hapen, we have a backup ;)

> Finally, I kindly ask @TheFrenchGhosty and the team to lock this thread to make sure relevant updates can be found easily.

@TheAssassin Yeah, that's a good idea! I don't want this issue to be clogged up with speculations either.

For all the others: we have a matrix/IRC (bridged) chat if you want to discuss some more, but we'll moderate the chat too if the topic gets too heated.

> the very definition of this is a fallacy. and the e-mail phrasing suggests that API services is when you get assigned your own keys (that is, not innertube). thanks for confirming, youtube legal team!

@selfisekai That's exactly what we though, hence why we are waiting to see where it goes.

**Comment by SamantazFox** [comment]
Hello everyone!

Quick update update on the subject: as we expected it, Youtube didn't proceed further with their legal action threat.

If anything new comes by, we'll keep you informed, no matter what.

Thanks a lot for all of the supportive messages we received, this means a lot to us!

**Comment by TheFrenchGhosty** [comment]
Nothing happened since.

Closing for hopefully forever.
