### ISSUE TITLE
[Feature request] IPFS mirror

### ISSUE THREAD

**Issue by Martinligabue** [iv-org/invidious#3888]
**Is your feature request related to a problem? Please describe.**

Since the recent announcement I think this would be a pretty easy way to make easy to make the repo resilient.

**Describe the solution you'd like**

It would be nice if you would put a link to IPFS too, so the repo can become decentralised, and easily shareable, like this: https://ipfs.io/ipfs/QmWJPutE8pzgbk4HrrZ3PK4DCtkSMnDrFuJYx9yajUYp5n
(if this goes offline, as for now I'm the only one hosting it, any node can copy the repo and hash it to ipfs to make the link work again)(this would become more resilient when more ipfs nodes (like from brave or ipfs desktop), cache this content, and become seeders too)

**Describe alternatives you've considered**

I don't think nft might be a good idea, and other decentralization methods I know are difficult to implement, this one should be easy to use for everyone

**Additional context**

**Comment by SamantazFox** [comment]
With the recent events (See #3872), many people are now hosting mirrors of our repo. In addition, we have our own self-hosted mirror at https://gitea.invidious.io, and some projects like software heritage are also archiving our code.

With all of this, and the already decentralized nature of git, I don't see a point in using IPFS. If you want to make sure that the code is the original one, all my commits are GPG-signed with my key: `A20312E544F7B9CC57922D40F42821059186176E`
