### ISSUE TITLE
[Discussion] Heavy Disk Usage

### ISSUE THREAD

**Issue by trentwiles** [iv-org/invidious#3890]
**Describe the bug**

![image](https://github.com/iv-org/invidious/assets/59586759/865653b9-9215-42cb-8180-24632c1bd1db)
Postgresql running via invididous is writing 17-20MB/s to the disk at all times. This sucks up all of my storage within a few hours.

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by SamantazFox** [comment]
Yeah, ok, I really need to work on merging https://github.com/iv-org/invidious/pull/2469

**Comment by unixfox** [comment]
I recommend turning off user notifications which play a big part of the disk usage: https://github.com/iv-org/invidious/issues/2042#issuecomment-1372914979

Related issue: https://github.com/iv-org/invidious/issues/2042
