### ISSUE TITLE
[Bug] Generated channels error with 'Missing hash key: "interactiveTabbedHeaderRenderer"'

### ISSUE THREAD

**Issue by SethFalco** [iv-org/invidious#3902]
**Describe the bug**

**Steps to Reproduce**

1. Go to https://y.com.sb/api/v1/channels/UC4R8DWoMoI7CAwX8_LjQHig
2. See error

**Logs**

```
Missing hash key: \"interactiveTabbedHeaderRenderer\" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '[]'
  from src/invidious/channels/about.cr:47:14 in 'get_about_info'
  from src/invidious/routes/api/v1/channels.cr:25:5 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:158:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

**Screenshots**

**Additional context**

I've seen others report similar issues in the past, but looks like they got stale and closed. :sob: 

Browser: Firefox 113
OS: Debian 11

I think this is caused by the generated channels on YouTube.

For example, the one that caused the error above is the Live section:
https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig

If we look at previous issues, it was also due to generated channels.

> Click on the channel 'Gaming' with this description: 'YouTube's gaming channel, featuring news, reviews, playthroughs, and more. This channel was generated automatically by YouTube ...'
> 
> — https://github.com/iv-org/invidious/issues/2137

---

Happy to look at this myself next week. :+1:

**Comment by unixfox** [comment]
Thank you

I reopened the previous issue for keeping more context to the issue: https://github.com/iv-org/invidious/issues/3902
