### ISSUE TITLE
[Bug]: URL in comment section not being displayed properly

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [iv-org/invidious#3916]
**Describe the bug**

URL not fully being displayed in comment section

**Steps to Reproduce**

1. Go to https://youtu.be/4OjoZZVyHgc
2. Load comments
3. See url in pinned comments cut off

**Logs**

None.

**Screenshots**

Screenshots taken within FT

With Invidious API
![Capture1](https://github.com/iv-org/invidious/assets/73130443/5dc43b08-9545-4e35-a588-295dd6d32a24)

Compared to our Local API
![Capture](https://github.com/iv-org/invidious/assets/73130443/f2c5192a-f278-47ef-902e-925247054d6b)

**Additional context**

Tested on https://invidious.protokolla.fi

**Comment by SamantazFox** [comment]
I should have tested https://github.com/iv-org/invidious/pull/3911 more thoroughly :/

**Comment by SamantazFox** [comment]
Hold on, this is working as expected! (I did "inspect source" on the instance you mentioned, video id `4OjoZZVyHgc`):
![image](https://github.com/iv-org/invidious/assets/52980486/e6f1c9b9-d663-489a-aeb4-e2437f681d0e)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If i click on the link it doesn't take me to the correct page on the site though

**Comment by SamantazFox** [comment]
The API returns the right HTML, so I guess that it's an issue with FreeTube

https://invidious.protokolla.fi/api/v1/comments/4OjoZZVyHgc
```
"Purchase Link: <a href=\"https://covertinstruments.com/collections/ssf-bypass-bible/products/covert-companion-1\">covertinstruments.com/collections/ssf-bypass-bible…</a>  (Covert Companion)<br><br><a href=\"https://covertinstruments.com/collections/ssf-bypass-bible/products/ssf-jiggler\">covertinstruments.com/collections/ssf-bypass-bible…</a> (SSF Jigglers)<br><br>Video created by @McnallyOfficial"
```

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You are right this is definitely an issue on our end. Sorry for not testing properly!
