### ISSUE TITLE
[Feature request] Add an option to remove youtube shorts.

### ISSUE THREAD

**Issue by amogusussy** [iv-org/invidious#3920]
**Is your feature request related to a problem? Please describe.**

Youtube shorts are usually just tiny clips of larger videos, and only serve to advertise said videos. It's also usually made to create as much attention as possible, so shouting is very common within them. This means that the subscriptions feed is usually clogged up with tons of annoying adverts, rather than the actual content you signed up for.

**Describe the solution you'd like**
An option in the settings where you can disable shorts.
You can check if the route of a video is /shorts in youtube in order to tell whether or not a video is a short.

**Describe alternatives you've considered**
I've used piped, since that has the ability to block shorts from appearing in the feed.
The one issue with that, however, is that it requires JavaScript, which isn't ideal.

**Additional context**

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2585
