### ISSUE TITLE
Attempt to use archive.org as a video source if the original video is down

### ISSUE THREAD

**Issue by ealgase** [iv-org/invidious#393]
Example: video with id (ZmKqDXCSKPw) is privated, however, you can access the stream by putting wayback-fakeurl.archive.org/yt/ZmKqDXCSKPw into archive.org.  (sorry about the language in the video, it was the easiest archived video I could find).

**Comment by samuncle** [comment]
IMHO we should make this in a more generic way (to open possibilities for #260 ).

We could have a way of adding an alternate source of videos (can be archive.org, can be your own server, whatever), and you can specify it in the configuration, something like

cdn.example.com/$video_id
