### ISSUE TITLE
Deploying on cPanel

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#3935]
Hi. Is it possible to deploy invidious on cPanel?
If you don't know about cPanel. cPanel is simply a shared hosting environment for deploying website. And as I'm looking through the Invidious documentation it looks that we need to have docker to run Invidious on the server. But cPanel is not root access and it does not even have docker. we simply have to upload Html/CSS/JSor other files of the project to the file manager and then the website works. cPanel also supports Python, Node JS and PHP. I'll appreciate it if you take a look at this case and help me with it 🙏❤

**Comment by unixfox** [comment]
no thats not possible, invidious is written in crystal not PHP.
