### ISSUE TITLE
Any way to disable custom player?

### ISSUE THREAD

**Issue by catfromplan9** [iv-org/invidious#3944]
I'd like to opt for using the browser's standard video player. Is this possible? Im willing to use a hacky fix to achieve this result if itll work. I just prefer something more minimal than custom players for my invidious instance.

**Comment by unixfox** [comment]
yes disable javascript on the website

**Comment by catfromplan9** [comment]
Removing player.js worked

**Comment by catfromplan9** [comment]
> Removing player.js prior to compilation worked

Maybe not, unsure. An nginx rule will work though

**Comment by catfromplan9** [comment]
> Removing player.js prior to compilation worked

Recompiling is unnecessary. I can just remove the player.js and restart invidious.
