### ISSUE TITLE
[Bug] "This content isn't available"

### ISSUE THREAD

**Issue by trentwiles** [iv-org/invidious#3950]
Looks like Youtube struck back again. Now, proxied videos (at least through yewtu.be) display a ~1:30 second video of a black screen with the text "this content isn't available".

**Describe the bug**

![image](https://github.com/iv-org/invidious/assets/59586759/4399130e-5d5d-4b00-9e8b-97046d715d20)

**Steps to Reproduce**
Proxy any video on Invidious.

**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3822
