### ISSUE TITLE
[question] installation issue - invidious.box has refused the connection.

### ISSUE THREAD

**Issue by shark0on** [iv-org/invidious#3960]
**Describe the bug:**
Out of nowhere the connection is rejected on the host itself and from 3. devices.

**Steps to Reproduce:**
"Steps to reproduce the behavior:"
1. Open browser
2. Navigate to http://localhost:3000 or http://invidious.box:3000/
3. See error: invidious.box has refused the connection.

**Logs:**
"If applicable, copy the log that appear in the browser page where the error is reported."
[chromewebdata.zip](https://github.com/iv-org/invidious/files/11929508/chromewebdata.zip)

**Screenshots:**
"If applicable, add screenshots to help explain your problem."
![2023-07-02 14_39_17-NVIDIA GeForce Overlay DT](https://github.com/iv-org/invidious/assets/50054917/61f94ce4-a683-4c6f-a8a8-3e74519b834f)

**Additional context:**
"Add any other context about the problem here."
 - Browser (if applicable): 1.52.129 Chromium: 114.0.5735.198 (Offizieller Build) (64-Bit) 
 - OS (if applicable): Microsoft Windows [Version 10.0.22621.1928]
 - Already reinstalled debian 12.0.0 and invidious
 - Update/Edit: Also pihole disabled for testing

**Comment by unixfox** [comment]
You have not explained how you installed invidious...

**Comment by shark0on** [comment]
> You have not explained how you installed invidious...

I'm sorry, just used the installer and let everything on default -> https://github.com/tmiland/invidious-installer

**Comment by unixfox** [comment]
Please open an issue there: https://github.com/tmiland/invidious-installer/issues

We do not manage this installer.
