### ISSUE TITLE
[Enhancement] Add ReturnYoutubeDislikes API to the Likes counter :)

### ISSUE THREAD

**Issue by xplshn** [iv-org/invidious#3963]
The Return Youtube Dislikes API is part of the extension Return Youtube Dislikes, its all FOSS and the API is free, it allows for apps to see the dislikes counter on Youtube and other alternatives like Piped to see them too, also, Newpipe X Sponsorblock has added that too.
Its a nice to have and for some it is a big deal.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/2781#issuecomment-1025263083
