### ISSUE TITLE
[FYI] Firefox nightly shows 'No available working or supported playlists'- works in Firefox 102

### ISSUE THREAD

**Issue by Yetangitu** [iv-org/invidious#3966]
In the continuing saga of _Playback cannot continue. No available working or supported playlists_ related errors I can add that this message has started to crop up in recent Firefox nightly versions on some videos. The same videos work without problems in Firefox 102 (ESR) as well as in Chromium. When coming upon a video which doesn't work in FF nightly - e.g. https://www.youtube.com/watch?v=XoJ0bAp4Eo8 (_Johnny Cash - The Mercy Seat_) - the following appears in the console:

```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. 
Object { code: 3, message: "Playback cannot continue. No available working or supported playlists." }
[video.js:163:49](https://invidious.example.org/videojs/video.js/video.js?v=45cc8356)
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. [video.js:24023:27](https://invidious.example.org/videojs/video.js/video.js?v=45cc8356)
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. 
Object { code: 3, message: "Playback cannot continue. No available working or supported playlists." }
```

...and the following in the _Network_ tab:
```
GET   invidious.example.org   https://invidious.example.org/videoplayback?expire=1688518885&ei=hWykZKiwG8C3mLAPvoSrgA0&ip=...   video.js:8080 (xhr)   mp4   NS_BINDING_ABORTED   498.78 kB
GET   invidious.example.org   https://invidious.example.org/videoplayback?expire=1688518885&ei=hWykZKiwG8C3mLAPvoSrgA0&ip=...   video.js:8080 (xhr)   mp4   NS_BINDING_ABORTED   1.57 MB
...
GET   invidious.example.org   https://invidious.example.org/videoplayback?expire=1688518885&ei=hWykZKiwG8C3mLAPvoSrgA0&ip=...   video.js:8080 (xhr)   mp4   NS_BINDING_ABORTED   105.56 kB
GET   invidious.example.org   https://invidious.example.org/videoplayback?expire=1688518885&ei=hWykZKiwG8C3mLAPvoSrgA0&ip=...   video.js:8080 (xhr)   mp4   NS_BINDING_ABORTED   1.03 MB
```

As said this works in Firefox 102, there are no similar NS_BINDING_ABORTED messages in the _Network_ tab and the console shows `VIDEOJS: loadmetadata event [video.js:163:49]` where the Nightly console produces those error messages. Both browsers are used with an identical profile, tested with a freshly compiled version of Invidious, built with Crystal 1.8.2 but the same error cropped up when I built it with earlier Crystal versions.

**Comment by unixfox** [comment]
can you reproduce the issue on public instance(**s**)?

are you using DASH or not DASH (default settings with hd720)?

what's the firefox version number?

**Comment by Yetangitu** [comment]
Using DASH, tested with medium as well, no difference.

Testresults with Firefox 102

__Not working__

yewtu.be, invidious.lunar.icu, vid.puffyan.us, yt.artemislena.eu, inv.zzls.xyz, ...: `The media could not be loaded, either because the server or network failed or because the format is not supported.` - not logged in, I only have an account on my own server, could be related? Proxy video enabled.

onion.tube, inv.tux.pizza, vid.priv.au, ...: `The media could not be loaded, either because the server or network failed or because the format is not supported.` - not logged in, proxy video disabled, can not be enabled (greyed out)

__Working__

invidious.projectsegfau.lt, inv.bp.projectsegfau.lt: works, tested at DASH 480p (maximum offered)


With Firefox Nightly (117) this video does not work with any instance

**Comment by unixfox** [comment]
What's the video codecs results on this website: https://html5test.com/?

**Comment by Yetangitu** [comment]
Firefox 107 running on Debian "Sid":

MP4 with H.264 support | Yes ✔
MP4 with H.265 support | No ✘
TS with H.264 support | No ✘
TS with H.265 support | No ✘
WebM with VP8 support | Yes ✔
WebM with VP9 support | Yes ✔

Firefox Nightly (117) running on same Debian "Sid":

MP4 with H.264 support | Yes ✔
MP4 with H.265 support | No ✘
TS with H.264 support | No ✘
TS with H.265 support | No ✘
WebM with VP8 support | No ✘
WebM with VP9 support | No ✘

Seems WebM is absent in the latter

**Comment by unixfox** [comment]
Related: https://github.com/iv-org/invidious/issues/3993
