### ISSUE TITLE
[Bug]  After latest update sefvice does not start

### ISSUE THREAD

**Issue by CarlBishop** [iv-org/invidious#3975]
**Describe the bug**
Deat team, sorry for this ticket, I tried everything my limited knoledge allow me to do.

After latest update the service does not start.

I also tried to reinstall (loosing all db) but nothing to do, it won't run anymore
This is the error:

```
* invidious.service - Invidious (An alternative YouTube front-end)
     Loaded: loaded (/lib/systemd/system/invidious.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-07-09 17:05:20 CEST; 3ms ago
    Process: 9289 ExecStart=/home/invidious/invidious/invidious -o invidious.log (code=exited, status=1/FAILURE)
   Main PID: 9289 (code=exited, status=1/FAILURE)
        CPU: 17ms

Jul 09 17:05:20 invidious systemd[1]: invidious.service: Main process exited, code=exited, status=1/FAILURE
Jul 09 17:05:20 invidious systemd[1]: invidious.service: Failed with result 'exit-code'.
```

**Steps to Reproduce**
1. Start the service
2. Get the error

**Logs**

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/12203647/2ff5b20a-5ad2-4858-8c74-f68d4f2ccb8c)

**Additional context**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
Ram 4gb
Manual installation

**Comment by unixfox** [comment]
Please check if hmac_key is set: https://github.com/iv-org/invidious/issues/3854
