### ISSUE TITLE
[Enhancement]  Disable or reset playback position for playlist and videos near end.

### ISSUE THREAD

**Issue by dertester** [iv-org/invidious#3976]
Hey,

is it already possible or would it be possible to disable the save_player_pos only for playlists?

Currently after hearing a playlist once it jumps to the last 10s of each video.

To keep the feature working with playlists i think a threshold would be useful.
Eg. Reset to beginning when saved playback position is 90% or more

thx

**Comment by resi23** [comment]
Any Update?

**Comment by unixfox** [comment]
May be fixed by https://github.com/iv-org/invidious/pull/4731
