### ISSUE TITLE
[Bug] Non Family Friendly videos buffer way more than Family Friendly videos

### ISSUE THREAD

**Issue by monkeyboy537** [iv-org/invidious#3984]
**Describe the bug**
Non Family Friendly videos buffer more than Family Friendly videos and the Non Family Friendly videos work okay under Youtube. This happens on both HD720 and DASH.

**Steps to Reproduce**
Go to a non family Friendly video like this one (https://www.youtube.com/watch?v=Yd8XgzSjLb4) or (https://www.youtube.com/watch?v=Sh3Fl_Rhcw4)

**Additional context**
I managed to recreate this issue on both my self-hosted instance and publicly hosted instances.
I used Firefox but I also recreated the same issue using a Third Party Tool called Yattee.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2189
