### ISSUE TITLE
[Bug] Sometimes unable to load videos with music.

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#3992]
It has been observed that sometimes, for unclear reasons, videos containing music unable to load.
If open the "Network" tab in the browser console, will notice that the video for unknown reason refuses to load due to a 403 error from the server side.
The problem is intermittent and is treated either by temporarily changing the instance, or by trying to load the video after a certain time, for example, tomorrow.
Examples of video that are currently not loading:
https://invidious.protokolla.fi/watch?v=y-l0tew3rP4
Also this video did not load a couple of hours ago, but now it loads without problems:
https://invidious.protokolla.fi/watch?v=7bOXKb7686Q

- Browser (if applicable): Pale Moon 32.3.0
- OS (if applicable): Windows 11

**Comment by Daxy7** [comment]
try loading without javascript on an instance other a `yewtu.be`

**Comment by unixfox** [comment]
Can you observe the same issue on other instances?

**Comment by cazwacki** [comment]
I ran into this issue on my local, private instance for songs in the Trending section.

**Comment by Daxy7** [comment]
edit: found one where it won't load on any method
```
https://yewtu.be/watch?v=vBkOTd_aYNQ
```
seems to be related to copyright control and not placed on the original uploader
