### ISSUE TITLE
[Bug] Letterboxed playlist thumbnails

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#4002]
**Describe the bug**

A recent commit seems to have caused letterboxing on playlist thumbnails. See screenshots below.

**Steps to Reproduce**

1. Go to a channel
2. Click on the playlists tab
3. See letterboxing on all playlist thumbnails 

**Logs**

**Screenshots**

Channel playlists tab:
![letterbox](https://github.com/iv-org/invidious/assets/70992037/8cfabcbf-47f6-4b9b-b664-ab833fa59187)

Search results:
![letterboxed playlists](https://github.com/iv-org/invidious/assets/70992037/8168e18b-d930-49bf-9eaa-70f7f1dabb40)

**Additional context**

**Comment by SamantazFox** [comment]
Probably caused by https://github.com/iv-org/invidious/pull/3763

**Comment by SamantazFox** [comment]
Uh, FF devtools shows that the image is indeed letterboxed. Did YT change something again?
![image](https://github.com/iv-org/invidious/assets/52980486/7a209aa6-4403-4e68-99c1-e678c94196da)
