### ISSUE TITLE
[Question] Not possible to install Invidious anymore on Debian and Arch.

### ISSUE THREAD

**Issue by solisinvictum** [iv-org/invidious#4012]
The Logs are the same like here: https://github.com/iv-org/invidious/issues/3985

i worked now days into this. with multiple reinstallation of the VM. Debian and Arch. 

None of the described Installationmethods here https://docs.invidious.io/installation/ works. Even Manual installation dont work (Debian and Arch).

Than, because i thought maybe the VM is the problem, i tried it out on a old hp notebook. First with @tmiland installer. Dont work. Than completly reinstalled Debian. Tried Docker. Dont work. Again complete reinstallation. Tried manual. Dont work.

Than i choosed Arch. Same behaviour. On Arch i tried the AUR Package too. Dont work too.

Im now lost and dont know further. On every variant, invidious crash (and restart) directly, because something with the DB Connection is wrong/not working.

**Comment by unixfox** [comment]
Maybe you can do a video capture of you doing the installation? This would allow us to see what you are executing exactly.

Either with a screenrecorder like simplescreenrecorder or your default screen recorder. There is also asciinema for an easy terminal recording: https://asciinema.org/

**Comment by solisinvictum** [comment]
Sure. 

Im currently at Work. As soon i can, i do it! :-)

**Comment by solisinvictum** [comment]
So, i tried again.

And got it working. 

The only Problem is, DASH Playback isnt possible because of "The media could not be loaded, either because the server or network failed or because the format is not supported."

Docker install method.

But, all other instances dont play DASH too. only yewtube.com works for me. (Firefox browser)

**Comment by unixfox** [comment]
DASH works for me for all the public instances.

That's probably a browser issue on your side.

Check for any errors in the devtools or the console.

**Comment by solisinvictum** [comment]
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

Is the Error shown in the dev-console.

**Comment by unixfox** [comment]
Check in the devtools too, in the Network tab for any errors.

Don't expect me to give all the answers.

Check the tutorials available online like this one: https://support.panopto.com/s/article/How-to-Capture-Network-Logs-from-Firefox-Web-Browser

**Comment by solisinvictum** [comment]
<img width="1159" alt="grafik" src="https://github.com/iv-org/invidious/assets/94938946/0305a889-df58-4024-9d86-580f63fbf7c4">

dont know if this helps.

sry, im not experience enough, to debug this 100% correctly.

**Comment by unixfox** [comment]
If you are running invidious behind a reverse proxy you probably forgot to follow these steps: https://docs.invidious.io/installation/#post-install-configuration

This CSP error is probably a misconfiguration with the actual domain used or something like that.

I'm going to close this issue as it's now a configuration error on your side. You are better off asking for help on matrix: https://matrix.to/#/#invidious:matrix.org or IRC: https://web.libera.chat/?channel=#invidious

**Comment by solisinvictum** [comment]
thanks. i give it a shot.
