### ISSUE TITLE
[Enhancement] Mandatory Login / No Search without Login

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4013]
Hi,

I want that every user must be logged in to be able to perform a search. 

Given I have turned of registrations for additional users, that essentially means that invidious can only be used by certain people that have access to my invidious page (which is desired behavior).

The desired behaviour would be that
1) User coming to invidious is asked to log in (default_home: Login - page)
2) Search bar is no showing (search_enabled: false)

Do you think that would be feasible?

**Comment by ManiMatter** [comment]
hi Unifox,

the duplicate 446 that you mentioned at the beginning is indeed pretty much the same request.
However, I think the solution there feels a bit "Patchy". What I propose here is literally a setting that can be set to turn-off the search, and a "default_home" setting which points to the login screen.

Having to deal with authelia etc feels to me like an overkill...
Wdyt?

**Comment by unixfox** [comment]
The original issue is also a feature request that's why I said it's a duplicated issue.

**Comment by ManiMatter** [comment]
Ok fair; the other ticket was closed without a feature being implemented.
Personally, I think the way via authentication is feasible, but cumbersome, and I'd rather vote for having the setting that can be set easily. 

I fear by this ticket being closed, and the other being closed, the feature will never see daylight ;)...
Is there a good way to request it, so that other people can "upvote" if they feel it's a beneficial thing?

**Comment by unixfox** [comment]
The other ticket is still opened???

**Comment by ManiMatter** [comment]
sorry, my bad :)
