### ISSUE TITLE
[Enhancement] Making auto-suggestions from Browser Optional / Showing Youtube Type-ahead suggestions instead

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4014]
Hi,

I find the autocomplete in the Search-field from the browser history rather annoying. 
It populates the search with completely unrelated stuff.
I understand that these were enabled by request in [https://github.com/iv-org/invidious/pull/3724](#3724 )

Two ideas for an enhancement:

1) Would it be possible to create an "allow autofill"-parameter that we can turn on/off via config.yml* so that for those users the browser history is considered when making suggestions (true) or not (false)?

2) What I believe would actually be helpful is to see the type-ahead suggestions of youtube.
From what I have read in other threads, I understand these cannot be personalized suggestions (since otherwise google could track that a user is using invidious and potentially lock the account). 
Would it be possible to at least the normal type-ahead suggestions be implemented (that everybody sees who is not logged in)?

What would be helpful: **Youtube type-ahead suggestions**
![Bildschirmfoto 2023-07-27 um 14 40 12](https://github.com/iv-org/invidious/assets/124743318/b6070022-747f-42cf-9c53-c3dc75d5c9f2)

What I would rather want to turn off (make optional via parameter): **Browser history auto-fill**
![Bildschirmfoto 2023-07-27 um 14 47 00](https://github.com/iv-org/invidious/assets/124743318/23955516-bcfe-4d67-83b2-1a4da2c529bc)

*with config.yml i refer to the settings that can be specified when launching invidious.
https://github.com/iv-org/invidious/blob/master/config/config.example.yml

**Comment by syeopite** [comment]
Duplicate of #541 

I'm going to be closing this issue in favor of reopening that one if you don't mind. The stale handler should not have eaten up that issue. 

----

Anyhow, about your suggestion. The API needed for this feature is fully available from the backend. It just needs to be integrated in the frontend through JS.

**Comment by syeopite** [comment]
For now though here's a quick git patch to make the browser-history autocomplete configurable

<details> 
<summary>Patch</summary>

```patch
From 7adb7439b3ffa3809ef8146e79117fb21e78bf72 Mon Sep 17 00:00:00 2001
From: syeopite <syeopite@syeopite.dev>
Date: Thu, 27 Jul 2023 13:49:23 -0700
Subject: [PATCH 1/1] Make browser-history autocomplete configurable

---
 config/config.example.yml                     | 8 ++++++++
 src/invidious/config.cr                       | 3 +++
 src/invidious/views/components/search_box.ecr | 2 +-
 3 files changed, 12 insertions(+), 1 deletion(-)

diff --git a/config/config.example.yml b/config/config.example.yml
index 34070fe5..003b3919 100644
--- a/config/config.example.yml
+++ b/config/config.example.yml
@@ -504,6 +504,14 @@ hmac_key: "CHANGE_ME!!"
 ##
 #playlist_length_limit: 500
 
+##
+## Enables/Disables Browser-history autocomplete for the searchbar
+##
+## Accepted values: true, false
+## Default: true
+##
+# browser_autocomplete: true
+
 #########################################
 #
 #  Default user preferences
diff --git a/src/invidious/config.cr b/src/invidious/config.cr
index e5f1e822..cea9a16a 100644
--- a/src/invidious/config.cr
+++ b/src/invidious/config.cr
@@ -140,6 +140,9 @@ class Config
   # Playlist length limit
   property playlist_length_limit : Int32 = 500
 
+  # Browser-history autocomplete for search bar
+  property browser_autocomplete : Bool = true
+
   def disabled?(option)
     case disabled = CONFIG.disable_proxy
     when Bool
diff --git a/src/invidious/views/components/search_box.ecr b/src/invidious/views/components/search_box.ecr
index a03785d1..9dba33bb 100644
--- a/src/invidious/views/components/search_box.ecr
+++ b/src/invidious/views/components/search_box.ecr
@@ -1,6 +1,6 @@
 <form class="pure-form" action="/search" method="get">
 	<fieldset>
-		<input type="search" id="searchbox" autocorrect="off"
+		<input type="search" id="searchbox" <%= "autocomplete=\"off\"" if !CONFIG.browser_autocomplete%> autocorrect="off"
 		autocapitalize="none" spellcheck="false" <% if autofocus %>autofocus<% end %>
 		name="q" placeholder="<%= translate(locale, "search") %>"
 		title="<%= translate(locale, "search") %>"
-- 
2.41.0

```
</details>

**Comment by ManiMatter** [comment]
Hi syeopite,

first of all, many thanks for creating the patch, super kind of you!

I am not sure, however, how I can use it.

In my setup, I use docker where I pull the docker image from here:
quay.io/invidious/invidious:latest-arm64

What is not clear to me is how the patch you have written finds its way into the image?
Is the process that you create a PR with your patch, somebody reviews/accepts it, and then it's within your git master.
And then once the folks of quay.io publish a new version of their image, they pull the latest git master from you?

Apologies if that's a naive question.

Thank you!

**Comment by unixfox** [comment]
for these kind of assistance, please discuss on matrix https://matrix.to/#/#invidious:matrix.org or IRC https://web.libera.chat/?channel=#invidious

It's annoying to discuss this inside a github issue which is not designed as a forum.
