### ISSUE TITLE
[Bug] On iPhone: When in "Listen" mode, when moving position slider >50% jumps to 100% ; Can't select anything between 50% and 100%

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4016]
On iPhone:
When you are listening to a video, and you want to use the slider to move forward, you can only do so for the first 50%.
The moment you drag the slider over the 50% mark, it jumps to 100% automatically.

It is not possible to select anything between 50% and 100%.

When watching the video (not in listen mode), the slider works fine.

When watching the video on listen mode on MacBook (not iPhone), slider works fine. 
Possibly related to https://github.com/iv-org/invidious/issues/4018

Tried this on separate networks (5G, 4G, Wifi), with 2 different devices (iPhone 13 Pro, iOS 16.5.1 / iPhone , iOS 16.5.1) with consistent same result (same bug).

**Comment by unixfox** [comment]
Can you reproduce the same issue on Firefox and chrome for iOS?

**Comment by ManiMatter** [comment]
I just downloaded both Firefox and Chrome for iOS and both show the same bug as Safari.
