### ISSUE TITLE
[Bug] On iPhone: Video Length & thumbnail incorrect in Listen-only mode 

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4018]
When opening videos in "Listen" mode on Iphone, two things seem broken
1) The duration is incorrect
2) The thumbnail is black

This is visible on below images.
When watching the following [video](https://www.youtube.com/watch?v=4oxd1iOoixk) as a real video on iPhone, the duration is 2:17. This is the correct duation.

When switching to listen-only mode, the thumbnail goes black, and the duration is suddenly shown as 4:34.
Interesting enough, when watching the same video on invidious through a computer browser, things work correctly (and in listen-only mode, a proper thumbnail is shown.

Tried this on separate networks (5G, 4G, Wifi), with 2 different devices (iPhone 13 Pro, iOS 16.5.1 / iPhone , iOS 16.5.1) with consistent same result (same bug).

**On Iphone, Watching as Video: (all correct)**
![Bildschirmfoto 2023-07-27 um 17 24 48](https://github.com/iv-org/invidious/assets/124743318/b30c0560-3a95-4c63-b9ce-cc24ad6f2605)

**On iPhone, watching as listen-only: (Thumbnail Broken, wrong Duration)**
![Bildschirmfoto 2023-07-27 um 17 29 28](https://github.com/iv-org/invidious/assets/124743318/81813ccc-9a38-4e43-af2b-1065a46283db)

**On regular browser, watching as listen only: (all correct)**
![Bildschirmfoto 2023-07-27 um 17 24 08](https://github.com/iv-org/invidious/assets/124743318/a3154791-f584-4a96-b8f3-5e9227d20f60)

**Comment by ManiMatter** [comment]
I just downloaded both Firefox and Chrome for iOS and both show the same bug as Safari.
The duration shown when in "Listen" mode is almost twice the actual length, and the thumbnail is black.

**Comment by SamantazFox** [comment]
Looks like https://github.com/iv-org/invidious/issues/913 is back
