### ISSUE TITLE
[Bug] update instance won't play livestreams

### ISSUE THREAD

**Issue by 2011** [iv-org/invidious#4031]
**Describe the bug**

I remember Inivdious instances having the ability to play livestreams in the past. But now, I have tried a few livestreams, and none of them offier the ability to play the stream.

As an example (you will have to find a new one after this one finishes):

https://yewtu.be/watch?v=UoLNoTDUDis

I suspect that something has changed on YouTube's end (yt-dlp now returns "No video formats found!" for livestreams).

**Comment by unixfox** [comment]
Duplicate https://github.com/iv-org/invidious/issues/3811

Yewtu.be has livestream disabled though, for the moment due to high bandwidth usage.

**Comment by 2011** [comment]
Okay. Two questions from that:

Could the instances somehow (maybe in the preferences) indicate that they don't support livestreams?

Forgive my ignorance on this, but doesn't video content (assuming "Proxy videos" remains unselected, as in this case) come directly from Google, and if so, why do livestreams cause "high bandwidth usage"?

**Comment by unixfox** [comment]
> Okay. Two questions from that:
> 
> Could the instances somehow (maybe in the preferences) indicate that they don't support livestreams?

Could create a separate issue where we inform to the user which functionalities are disabled?

> Forgive my ignorance on this, but doesn't video content (assuming "Proxy videos" remains unselected, as in this case) come directly from Google, and if so, why do livestreams cause "high bandwidth usage"?

Some livestream requires to have the video content going through the server that's why it comes with more bandwidth usage.
And if you use DASH it's automatically proxying as it's required.
