### ISSUE TITLE
[Question] how to configure ports web

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4049]
Hi. Is it possible to run Invidious on any other port like 443 or 80 through the Configutation file?
I tried 80:80 but didnt work.
Now I'm talking about the configuration file not any other reverse proxy thing.

**Comment by unixfox** [comment]
Invidious binds on port 3000 not 80. It's not recommended to run on port 80 but instead you should use a reverse proxy.

Closing as it's completely unrelated to invidious and is a problem only related to web server configuration
