### ISSUE TITLE
[Bug] Download is broken

### ISSUE THREAD

**Issue by ba06** [iv-org/invidious#4055]
Can't download any video for local playback.

1. Go to https://vid.puffyan.us/watch?v=Ux8bI98b08Q
2. Attempt to download via Download button (any format)
3. Get 403 error or empty response

Alternatively
1. Go to https://yewtu.be/watch?v=Ux8bI98b08Q
2. Copy /latest_version.* URL string from source code
3. Paste and go to that URL (https://yewtu.be/lastest_version.*)
4. Get same 403/empty response

It has been like this for several days now. I browse with JS off 80% of the time and often when JS is on, the inline videos will fail to load. If I'm browsing via Lynx (preferred) or Links2 or edbrowse, same issue. It's across all the instances I've tried, including invidious.io.lol and vid.priv.au and probably some others I don't remember.  It's the same in Vivaldi, too, with and without JS.

It used to be an issue on certain videos, but now it's seemingly on everything. The video, with JS off, almost always loads fine in the inline player (<video>).

Vivaldi Error (TUI browsers just load a blank screen):

Access to vid.puffyan.us was denied
You don't have authorization to view this page.
HTTP ERROR 403

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/4045
