### ISSUE TITLE
[HELP] How do i disable the Popular Tab on a Instance using docker-compose?

### ISSUE THREAD

**Issue by WreckingBANG** [iv-org/invidious#4058]
I just started hosting my own private Instance for me and my family and i dont want that there is a popular page. I just found the config.example.conf but no config options for docker-compose. Did i miss something or is it not a option?

**Comment by unixfox** [comment]
Just use the same parameter inside the INVIDIOUS_CONFIG environment variable.

**Comment by WreckingBANG** [comment]
Oh ok, i did not know that the config was also for the docker install. Thank you!
