### ISSUE TITLE
[Feature request] Torrent videos off YouTube

### ISSUE THREAD

**Issue by Right-BuggerOff** [iv-org/invidious#4061]
If you're on TOR or have really cheap Internet, downloading 360p can be very hard. OTOH I've had no trouble stealing movies. Please consider adding a .torrent file option for video AND audio.

**Comment by unixfox** [comment]
That's not possible, invidious doesn't host any video file.

**Comment by Right-BuggerOff** [comment]
Well maybe not a torrent, but is there a way to download a file by way of a proxy site piece by piece? Surely you don't HAVE to download it all at once.

And man, whose heav’n-erected face,
⁠The smiles of love adorn,
Man’s inhumanity to Man,
⁠Makes countless thousands mourn.
– Robert Burns

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by unixfox** [comment]
Not sure what you really want to achieve here, when downloading your are already downloading the file piece by piece.
