### ISSUE TITLE
[Bug] Language seems to change when DASH is enabled in settings

### ISSUE THREAD

**Issue by ozoned** [iv-org/invidious#4064]
**Describe the bug**
I'm on Fedora 38 and watching my invidious instance through Firefox.  When I attempted to watch a Mark Rober video, the "
Backyard Squirrelympics 3.0- The Summer Games" it was set to some audio that seemed to be something like Mandarin, though I only speak English so I'm not sure.  After troubleshooting multiple things this seems to be an issue with DASH adaptive quality.

**Steps to Reproduce**
1. Go to Settings -  Preferred video quality: - DASH (adaptive quality)
2. Go to "Backyard Squirrelympics 3.0- The Summer Games" video and it was in another language
3. Setting to HD720 resolves this issue

**Additional context**
Even opening Freetube and having it look at a completely separate Invidious instance, flipping between DASH and Legacy Format causes this issue.  So I really think this is an issue with DASH changing language audio in Invidious.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
