### ISSUE TITLE
[Question] Question about proxying videos.

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4067]
Hi. I have a question about proxying videos. I'm wondering how exactly does this feature works.
For example in my case. I have a VPS server and a domain that I'm running Invidious. so for example when I enable Proxying videos does that mean that my instance (server) will connect to a proxy server and use that to hide the ip address of the request sent to Googlevideos?

So are there some proxy servers that the invidious team has setted up for instances to use?
Did I get the idea right? My server connects to a proxy server and then use that to load the videos?

**Comment by unixfox** [comment]
https://docs.invidious.io/faq/#table-of-contents

section `Q: What data is shared with YouTube?`
