### ISSUE TITLE
Audio mode not working

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4077]
Hi. the caption says pretty much everything. for example i would like to play music videos as just as audio thing only . but i've noticed the feature audio mode is not working at all not in any video.

**Comment by syeopite** [comment]
Can you provide some example video urls?

**Comment by armin567ip** [comment]
> Can you provide some example video urls?

Oh wait. It looks the problem is from my instance. On another public instance it works just fine.![Screenshot_20230827-115038_Chrome.jpg](https://github.com/iv-org/invidious/assets/106415257/69c1fed1-e789-4918-a8dc-f4f30dda0a5e)

How can I fix mine

**Comment by armin567ip** [comment]
Additional information if needed:
I'm hosting on Ubuntu 20
And using caddy webserver.
However I either tried it with NGinx before. It's the same.
And the configuration file is the exact default . I just changed the key in it and the port to 3000:3000

**Comment by unixfox** [comment]
Try to enable "proxy" or "dash" in the preferences if that solves the issue.

**Comment by armin567ip** [comment]
> Try to enable "proxy" or "dash" in the preferences if that solves the issue.

Yeah proxy fixed it, Thanks 🙏❤
