### ISSUE TITLE
Consistent HTTP 429 from yewtu.be

### ISSUE THREAD

**Issue by forthrin** [iv-org/invidious#4082]
**Describe the bug**
Consistent HTTP 429 errors on yewtu.be when using mpv with yt-dl hook.

**Steps to Reproduce**
1. `mpv https://yewtu.be/watch?v=r6sGWTCMz2k`

**Logs**
```
[ffmpeg] https: HTTP error 429 Too Many Requests
Failed to open https://www.yewtu.be/watch?v=XUto8p6fzNc.
```

**Additional context**
- mpv logs unfortunately don't say which request they make, even at msg-level=all=debug
- Never happened until a few days ago.
- Does not happen with eg. invidious.protokolla.fi, but that server sadly responds much slower.
- While testing, noticed the server also has an erroneous redirect.

```
$ curl --head 'https://www.yewtu.be/watch?v=XUto8p6fzNc'
HTTP/1.1 301 Moved Permanently
Location: https://yewtu.be/watch?v=XUto8p6fzNc?v=XUto8p6fzNc
```

**Comment by unixfox** [comment]
Wrong repository: https://github.com/yewtudotbe/invidious-custom/issues

**Comment by forthrin** [comment]
@unixfox: Ah. I didn't know about that. Could you move/re-post there with privileges?

**Comment by unixfox** [comment]
> @unixfox: Ah. I didn't know about that. Could you move/re-post there with privileges?

We can only move from the same repository you need to repost the issue.
