### ISSUE TITLE
[Bug] Unexpected char '%' at line 1, column 1 (JSON::ParseException)

### ISSUE THREAD

**Issue by atiilla** [iv-org/invidious#4089]
**Describe the bug**

**Steps to Reproduce**

**Logs**

```
POST /download HTTP/2
Host: invidious.fdn.fr
Content-Length: 130
Cache-Control: max-age=0
Sec-Ch-Ua: 
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: ""
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.91 Safari/537.36
Origin: https://invidious.fdn.fr
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://invidious.fdn.fr/watch?v=y8CYSwHXVNE
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

id=y8CYSwHXVNE&title=5%2B+CSS+Features+That+Will+Change+How+You+Code&download_widget=%7B%22itag%22%3A18%2C%22ext%22%3A%22mp4%22%7D
```

**Screenshots**

Screenshot-1: https://prnt.sc/hvUYgOnY3kNA
Screenshot-2: https://prnt.sc/7QtV4ubQxhLr
Screenshot-3: https://prnt.sc/9trl5FB_J8mt

**Additional context**

**Comment by SamantazFox** [comment]
Can you please describe the bug you're getting?

**Comment by atiilla** [comment]
When I sent a POST request to /download via the Insomnia client tool, there was no problem. However, when I added an unexpected character to a value in the 'URL form encoded' payload, I received the following error



```
**It looks like you found a bug in Invidious!**

Title: `Unexpected char '%' at line 1, column 11 (JSON::ParseException)`
Date: `2023-09-09T20:50:56Z`
Route: `/download`
Version: `2023.08.27-2a86d7d0 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '%' at line 1, column 11 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:331:5 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer/io_based.cr:11:21 in 'consume_number'
  from /usr/share/crystal/src/json/lexer.cr:63:7 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:108:11 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from /usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>
```

**Comment by SamantazFox** [comment]
You're not supposed to manually send POST request to the `/download` endpoint.
If you need to automate video download, please use a tool like [yt-dlp](https://github.com/yt-dlp/yt-dlp).
