### ISSUE TITLE
[question] Strange warning

### ISSUE THREAD

**Issue by letruxux** [iv-org/invidious#4097]
![Screenshot_20230911_212044_com.brave.browser.jpg](https://github.com/iv-org/documentation/assets/102257756/9b8a89f9-dd81-456b-bd24-eb5267cce447)

I'm getting this warning when viewing limited videos, the thing is that it worked some time ago, is this an update or what?

**Comment by unixfox** [comment]
That's the error youtube servers are giving us so we return the same error to the client, in this case you.

That's it.
