### ISSUE TITLE
[Question] Search results show "0 videos", but the channel has more

### ISSUE THREAD

**Issue by wanniethecharacter** [iv-org/invidious#4105]
For example, if i search for “[Shabnam K](https://vid.priv.au/search?q=%22shabnam+k%22&page=1&date=none&type=channel&duration=none&sort=relevance)” and filter it by “channels”, it comprises channels displaying “0 videos” on the search page although some ([like this](https://vid.priv.au/channel/UCfuRKPBhp4vExkmHIuRLtTw)) display 1 or more videos/shorts when you go to the channel page.
This needs to be fixed!

**Comment by unixfox** [comment]
how this that a bug? you are filtering by type "channels" so invidious only show you channels not videos.

you want to have all the videos from a channel? I don't understand what's your end goal here.

**Comment by syeopite** [comment]
This is a valid issue. Channels shown on the search results are saying that they have zero videos when in reality they have more. 

![zero videos](https://github.com/iv-org/invidious/assets/70992037/d51aafe6-2009-4ef8-9876-cf768d686aee)

**Comment by absidue** [comment]
Pretty sure if you look on YouTube it doesn't display the video count anymore for those channels, instead it shows the channel handle,  which #3994 adds support for.

**Comment by SamantazFox** [comment]
Yep, youtube removed the info. There was a trasition time where some channels still had the video count, but now all seem to return their handle.

**Comment by syeopite** [comment]
Ah that makes sense. I didn't know that they had removed video count

**Comment by ChunkyProgrammer** [comment]
`- Topic` channels still have video counts 
![image](https://github.com/iv-org/invidious/assets/78101139/1ff2da15-0a10-45f2-a895-756fb4f81fe5)

**Comment by absidue** [comment]
Topic channels don't have a handle, so that's probably why.
