### ISSUE TITLE
[Feature request] Add config option like "Don't autoload video data"

### ISSUE THREAD

**Issue by Nerdmind** [iv-org/invidious#4110]
Hello.

I would also like to see a configuration option like ["Don't autoload video data"](https://github.com/iv-org/invidious/issues/798) so that video data only starts loading when the user explicitly hits the "Play" button.

This would be useful for people who are using a cellular connection for their home network and do not want to waste any mobile data volume when some tabs in Firefox with Invidious URLs are re-loading on browser restart, for example.

It is possible [to configure Firefox ](https://superuser.com/a/1344698)so that only a small portion of the video will be buffered. However, this still consumes a few Megabytes on page load when the first part of the video stream is buffered in the background.

Thank you!
– Thomas

**Comment by unixfox** [comment]
I think this will only be possible for DASH formats video because without DASH (hd720 exemple) it's the browser that control how the video is loaded so we can't do anything on that.

**Comment by Nerdmind** [comment]
Maybe I am wrong, but isn't the `preload` attribute of the HTML5 `<video>` element supposed to give the web developer control over [how the web browser will start loading a video](https://www.w3schools.com/TAgs/att_video_preload.asp)? I quote:

> The preload attribute specifies if and how the author thinks that the video should be loaded when the page loads.

When inspecting the DOM of an Invidious video URL (using the non-DASH version) in the Firefox developer console, I see that the `<video>` element has the `preload` attribute set to `auto`:

~~~html
<video style="[...]" playsinline="playsinline" poster="[...]"
	id="player_html5_api" class="vjs-tech" preload="auto" tabindex="-1"
	src="/latest_version?id=THE_VIDEO_ID&amp;itag=18&amp;local=true">
~~~

If this could be set to `none`, no HTTP request should be made to the `/latest_version`-URL until the user explicitly hits the play button. Here is a web page [with a a demonstration about the behaviour of the `preload` attribute](https://clubmate.fi/what-does-the-preload-attribute-in-the-video-element-do).

But maybe I am wrong and missing something.

**Comment by Nerdmind** [comment]
OK, I just looked into the Invidious source code to see if I can quickly fix this for myself and have made the following observations when loading a random Invidious video URL like `/watch?v=78uQL9RpcW4`.

When using the non-DASH player, there are immediately two requests fired each to `/latest_version` and `/videoplayback` (`/latest_version` just redirects to the final `/videoplayback` URL):

~~~
"GET /latest_version?id=78uQL9RpcW4&itag=18&local=true HTTP/2.0" 302 0
"GET /videoplayback?expire=1695599353... HTTP/2.0" 499 0
"GET /latest_version?id=78uQL9RpcW4&itag=18&local=true HTTP/2.0" 302 0
"GET /videoplayback?expire=1695599353... HTTP/2.0" 206 6564951
~~~

When using the DASH player, the following requests are fired immediately on page load:

~~~
"GET /latest_version?id=78uQL9RpcW4&itag=18&local=true HTTP/2.0" 302 0 
"GET /videoplayback?expire=1695603859... HTTP/2.0" 499 0        
"GET /videoplayback?expire=1695603859... HTTP/2.0" 200 302225                
"GET /videoplayback?expire=1695603859... HTTP/2.0" 206 740
"GET /videoplayback?ex[0/1864]5603859... HTTP/2.0" 200 367761
"GET /videoplayback?expire=1695603859... HTTP/2.0" 206 163692
"GET /videoplayback?expire=1695603859... HTTP/2.0" 206 632
"GET /videoplayback?expire=1695603859... HTTP/2.0" 206 162055
~~~

When disabling JavaScript (so neither the DASH nor the non-DASH player is used):

~~~
"GET /latest_version?id=78uQL9RpcW4&itag=18&local=true HTTP/2.0" 302 0
"GET /videoplayback?expire=1695599353... HTTP/2.0" 206 1256545
~~~

When searching for `preload` and `<video` in the Invidious source tree, I found the following files:

* `player.js` (`assets/js/player.js`)
* `player.ecr` (`src/invidious/views/components/player.ecr`)


### `player.js`
In `player.js` there is a setting like this:

~~~js
var options = {
    preload: 'auto',
    [...]
~~~

### `player.ecr`

The `player.ecr` is the file where the `<video` element is defined that one can see in the HTML source view:

~~~html
<video style="outline:none;width:100%;background-color:#000" playsinline poster="<%= thumbnail %>"
~~~

It has no `preload` attribute defined (which is equivalent to `auto`) and explains the two requests when JavaScript is disabled. Adding the `preload="none"` attribute to the `<video>` element and re-compiling Invidious results into not loading the video data anymore until the user explicitly hits the play button – at least if JavaScript is disabled.

For the JavaScript version of the player, one need to set `preload: 'none'` in the `player.js` additionally. This works for both the DASH and non-DASH player like expected, tested with Firefox and Chromium.

The result of these two changes is that video data will no longer be loaded until the user hits the play button.
