### ISSUE TITLE
[Bug] Clicking on the timecode redirects to the youtube page

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#4115]
**Describe the bug**
When i click on a clickable timecode, instead of going to the said timecode in the current page, it loads the YT page of the video.

**Steps to Reproduce**
1. Go to a video with a clickable timecode in the description
2. Click on the said timecode

**Logs**
Not applicable

**Screenshots**
Not applicable

**Additional context**

**Comment by unixfox** [comment]
please give the video ID and a screenshot of the comment.

**Comment by stemy2** [comment]
A screenshot containing all the infos you asked.
![Capture d’écran du 2023-09-22 00-11-56](https://github.com/iv-org/invidious/assets/22192600/429c2f78-b390-4172-b002-7901ead79985)

**Comment by SamantazFox** [comment]
Sounds like an issue with this specific instance, as I can't reproduce on others.
Is Youtube A/B testing stuff again?
