### ISSUE TITLE
[Bug] Skipping to timestamps does not work if in audio only mode

### ISSUE THREAD

**Issue by witchent** [iv-org/invidious#4124]
**Describe the bug**

If you load a video in audio mode in firefox (either clicking the button, or adding &listen=1 to the url), and try to skip to a certain point in the video (either seeking via arrow keys, mouse click, or clicking a timestamp in the description), the music stops, while the loading circle is displayed in the video frame

**Steps to Reproduce**

0. Create new firefox profile and open it
1. Go to https://invidious.projectsegfau.lt/watch?v=9ZqZ3is9tpk&t=268&listen=1
3. See loading circle in the video screen and nothing happens anymore

**Logs**

**Screenshots**

**Additional context**

Browser: Firefox v117. It seems to work fine using chromium.
OS: Linux x64 (don't know if this makes a difference)

**Comment by witchent** [comment]
Oh I just tried creating a new profile and in that profile it works, so it must be some firefox setting causing this problem. I will try to debug it further, and sorry for prematurely opening an issue.

**Comment by markozajc** [comment]
As far as I've seen seeking does actually work, but Invidious for some reason seeks in real time (eg. seeking 5 minutes from the start will take 5 minutes to load). I don't know if that's a limitation imposed by YouTube (possibly related to their throttling mechanisms) or just an Invidious thing.

**Comment by witchent** [comment]
I don't know when that happened, but the problem is fixed for me, so I close this for now

**Comment by lamadesbois** [comment]
Hi,
I am having the same problem with longer videos.
Waiting does not help.
Attached are 2 videos of the problem.
Thank you
https://drop.infini.fr/r/s4yrY1RJAc#1gq9Xv1K+ryp6NH7iuHx1Zka/ILUMIK6iHw/J63GROQ=
