### ISSUE TITLE
The media could not be loaded [Bug] 

### ISSUE THREAD

**Issue by Morasithil** [iv-org/invidious#4129]
**Describe the bug**

I'm regularly watching invidious on two instances those are https://yewtu.be and https://invidious.private.coffee
I've also tried other instances but the issue is the same everywhere, when i klick to play ANY video, an X appears in the center of the video and this error code:
**The media could not be loaded, either because the server or network failed or because the format is not supported.**
This is happening since i believe four days or so, not a single video works.

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
For yewtu.be please create an issue here: https://github.com/yewtudotbe/invidious-custom/issues

For the other instance contact the maintainer, we do not control the public instances.

**Comment by Morasithil** [comment]
Thanks for the reply, i'll do as you said if this relevant after this update.
I'm still having this issue on my main computer with all instances and have no idea why, it suddenly happened few days ago and since then refuses work again, i haven't changed any of my settings.
However a moment ago i visited yewtu.be in a virtual box windows 10 machine and the streaming worked as it used to work on the host os, so i tried again on the host os thinking it might have been solved, but no it still doesnt work.
Any ideas? Should i share some type of logs?
