### ISSUE TITLE
[Bug]  Videos cannot be loaded if proxy enabled

### ISSUE THREAD

**Issue by StartNoob** [iv-org/invidious#4132]
**Describe the bug**
Videos cannot be loaded if proxy enabled

**Steps to Reproduce**

1. Go to any instance
2. Click on any video with proxy enabled or &local=true
3. The media could not be loaded error

**Screenshots**

![a](https://github.com/iv-org/invidious/assets/145612162/15cf51eb-4fe7-4833-9b9a-52f6cafeca48)

**Comment by xbdmHQ** [comment]
> **Describe the bug** Videos cannot be loaded if proxy enabled
> 
> **Steps to Reproduce**
> 
> 1. Go to any instance
> 2. Click on any video with proxy enabled or &local=true
> 3. The media could not be loaded error
> 
> **Screenshots**
> 
> ![a](https://user-images.githubusercontent.com/145612162/271731391-15cf51eb-4fe7-4833-9b9a-52f6cafeca48.png)

Google is blocking the proxying ip instances, turn it off and use a vpn instead.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4045
