### ISSUE TITLE
issue with default audio language

### ISSUE THREAD

**Issue by umikali222** [iv-org/invidious#4134]
Hi, I've been using invidious for some time now, and I've been self-hosting it, but the problem is whenever a video has a few audio languages, invidious always seems to pick I think it's Spanish. How do I make it always pick English? Also I used the docker compose file that was in the main directory, so it runs on docker.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007

**Comment by umikali222** [comment]
I thought this could be set up in the docker compose file, not in the player, because the online invidious instances automatically play the English audio.
