### ISSUE TITLE
[Bug] Random DB::PoolRetryAttemptsExceeded random errors

### ISSUE THREAD

**Issue by tuxpizza** [iv-org/invidious#4135]
**Describe the bug**
Seem to keep running into this error every so often (~every hour). Invidious will stop working and pump out this error no matter what I click on, then after a little while it will go back to working again.

**Steps to Reproduce**
Using Invidious, clicking on a video

**Logs**

Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2023-10-01T18:06:41Z`
Route: `/`
Version: `2023.09.18-bb14f79 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_one?:as'
  from src/invidious/routes/before_all.cr:83:10 in 'handle'
  from lib/kemal/src/kemal/filter_handler.cr:82:62 in '->'
  from lib/kemal/src/kemal/filter_handler.cr:58:23 in 'call_block_for_path_type'
  from lib/kemal/src/kemal/filter_handler.cr:16:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>
```

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/84710786/cf9261c5-e5f1-416a-9687-e33de2aac30a)


**Additional context**
Seems to be more of an issue when logged into an account, but viewing videos can still cause errors even when not.

**Comment by unixfox** [comment]
Instance issue closing, we do not manage public instances. Ask the owner to fix the bug

**Comment by tuxpizza** [comment]
I am the owner. Could you at least elaborate? If I understand it correctly there are too many connection attempts to the database, and it has to wait for a cooloff? Not sure why this is happening though. I've tried to investigate but I am unfamiliar with this codebase or database setup

**Comment by unixfox** [comment]
That's correct, usually it's when too many people are using the instance or too many invidious processes using the database.
The best idea would be to put invidious behind a connection pooler like pgpool or pgbouncer.

**Comment by tuxpizza** [comment]
Thanks, I will look into that. Super weird why this is happening now though, I've had 1000+ members for a while and haven't ran into this issue until this week. Traffic also is historically about the same as its been for the past few months.

I did have an issue recently where one of the Invidious volumes grew to over 256GB and then it wouldn't start up anymore. Not exactly sure what that was (video information cache?) but I re-created my invidious instance, imported the users DB, and then that's when I think this issue started occurring.

**Comment by unixfox** [comment]
> did have an issue recently where one of the Invidious volumes grew to over 256GB and then it wouldn't start up anymore. Not exactly sure what that was (video information cache?) but I re-created my invidious instance, imported the users DB, and then that's when I think this issue started occurring

Very strange invidious should automatically clean the database.
