### ISSUE TITLE
[Bug] cannot execute UPDATE in a read-only transaction (PQ::PQError)

### ISSUE THREAD

**Issue by nontechnoob** [iv-org/invidious#4136]
**Describe the bug**
Whilst navigating between any page or opening a page or even at times attempting to Log in, the error can presented, effectively "bricking" the whole site. I have tried multiple instances with the same issue, specifically "invidious.flokinet.to", "invidious.projectsegfau.lt", "invidious.slipfox.xyz" and "invidious.privacydev.net". It does NOT seem to effect "yewtu.be", however Im sure you're aware, they have disabled accounts, rendering use on it massively restricted.

This specific log below occurred when attempting to save preferences, however it is widespread as stated above. I will add the error log thats displayed having clicked "feed/subscriptions" in the "additional context" section below. Many thanks for the time, energy and expertise which you invest here.

**Steps to Reproduce**
1. Attempting to log in or save preferences or navigate to any video or page BESIDES the preference page displays the error.

**Logs**
Title: `cannot execute UPDATE in a read-only transaction (PQ::PQError)`
Date: `2023-10-01T19:00:15Z`
Route: `/preferences?referer=%2Ffeed%2Fsubscriptions`
Version: `2023.09.18-bb14f79 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
cannot execute UPDATE in a read-only transaction (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'move_next'
  from lib/db/src/db/result_set.cr:39:13 in 'exec'
  from src/invidious/database/users.cr:174:5 in 'update_preferences'
  from src/invidious/routes/preferences.cr:183:7 in 'update'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Additional context**
Error log when attempting to access "feed/Subscriptions"

- Browser (if applicable): Firefox 118.0.1 
- OS (if applicable): Windows 10

**Comment by nontechnoob** [comment]
I entered all the fields and submitted but none of the information entered was submitted. I will close this and attempt again.

**Comment by SamantazFox** [comment]
It was because you left `<!--` and `-->` in you message, which are understood as HTML comments, and hence are not rendered by Github. I fixed it for you ^^

**Comment by SamantazFox** [comment]
We only have two choices, so "not planned" is used for invalid & duplicates:
![image](https://github.com/iv-org/invidious/assets/52980486/cfa21c65-cbd1-4ef5-aae3-cfedb1d1d58f)

**Comment by syeopite** [comment]
I feel like Invidious should probably have some custom error pages for these database problems. Ones that explains what these errors are, that they're an instance issue, and to tell the users to either contact the instance maintainer or to try another instance

**Comment by nontechnoob** [comment]
Oh good to know, thanks again.


________________________________

**Comment by unixfox** [comment]
@SamantazFox why was this reopened?

**Comment by SamantazFox** [comment]
@unixfox the issue is genuine. The author only had some issues with the formatting.
