### ISSUE TITLE
Feature suggestion: federation

### ISSUE THREAD

**Issue by ealgase** [iv-org/invidious#414]
This is a huge suggestion but I think it would be very useful.

Support Federation with the ActivityPub protocol.

Channel pages would be actors, all videos would be posts, etc.  This would make it very easy to interact with YouTube content directly on the Fediverse (e.g. Mastodon) and follow your favorite channels there.  There could also be a separate "Federated Comment Section" for comments by Invidious users and those accessing from other federated platforms.

**Comment by Perflyst** [comment]
If this will be implemented, please (!) disable it by default or provide an option to disable it completely.

**Comment by elypter** [comment]
related: https://github.com/omarroth/invidious/issues/264
