### ISSUE TITLE
[Bug] Error connecting to 'piped-backend:2000': Connection refused (Socket::ConnectError)

### ISSUE THREAD

**Issue by BlueberryFoxtrot** [iv-org/invidious#4154]
As best as I can tell, the following is only a TEMPORARY glitch, which I'm only reporting just in case it might be helpful and hint at a more persistent problem. 

If there are no further like reports, if nobody else is experiencing the same issue, and if the glitch does not recur or clue actual devs in to a real problem, then devs could very well just close this hypervigilant bug report.

Upon trying to visit this URL, https://invidious.privacydev.net/watch?v=dPpLf-0xyHI
I was greeted by the below error:

Title: `Error connecting to 'piped-backend:2000': Connection refused (Socket::ConnectError)`
Date: `2023-10-09T07:59:52Z`
Route: `/watch?v=dPpLf-0xyHI`
Version: `2023.08.26-ac0c0609 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Error connecting to 'piped-backend:2000': Connection refused (Socket::ConnectError)
  from /usr/share/crystal/src/socket/addrinfo.cr:66:15 in 'initialize'
  from src/invidious/helpers/crystal_class_overrides.cr:6:3 in 'new'
  from src/invidious/helpers/crystal_class_overrides.cr:29:10 in 'io'
  from /usr/share/crystal/src/http/client.cr:678:5 in 'send_request'
  from /usr/share/crystal/src/http/client.cr:610:37 in 'exec'
  from /usr/share/crystal/src/http/client.cr:721:5 in 'exec'
  from src/invidious/videos.cr:423:37 in 'fetch_video'
  from src/invidious/videos.cr:384:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

I think I saw the error survive one refresh of the same tab, but I'm not 100% sure. 
Upon visiting the same URL again in a different tab, the page loaded correctly, which is why I'm at pains to point out that depending on what other people see, this might only be a limited, temporary glitch. Again, I'm only reporting "just in case" it's more than that, which I alone cannot tell.

**Comment by unixfox** [comment]
We do not manage public instances. Please contact the owner or use another instance at https://instances.invidious.io
