### ISSUE TITLE
[Bug] Invalid HTML hides video titles from my "Copy links" addon

### ISSUE THREAD

**Issue by mk-pmb** [iv-org/invidious#4160]
**Describe the bug**
I selected part of a playlist and used an addon to copy the links of all the videos in the selection. All the link titles came up empty. While it is a bug in that addon to be so easily fooled, it's also a bug in invidious to use a `<p>` block element inside an `<a>` inline element. Use something like `<span>` instead, or hoist the `<p>` up until it's no longer inside an inline element.

**Steps to Reproduce**
1. Visit [the Summer of Math Exposition playlist](https://yewtu.be/playlist?list=PLnQX-jgAF5pQS2GUFCsatSyZkSH7e8UM8)
2. View DOM
3. Search for "bubbles"

**Logs**

**Screenshots**

**Additional context**

**Comment by Rjchauhan18** [comment]
Hello , @mk-pmb 

I would like to work on this issue.
Please assign this issue to me .

`Do you wanted to add link inside this <p> ?`

![image](https://github.com/iv-org/invidious/assets/113838908/60a2e227-fd1f-459d-afad-18e049d153e9)

**Comment by unixfox** [comment]
Hi @Rjchauhan18, we do not assign anyone to any issue.
Feel free to create a pull request for fixing the bug and we will review your code there.

**Comment by mk-pmb** [comment]
> Do you wanted to add link inside this `<p>`?

I'm not sure about the solution. The DOM tree probably shows the result after the browser has attempted automatic repair, so I doubt we can rely on that. Instead, try feeding the page to [The W3C Markup Validation Service](https://validator.w3.org/) and see if that can give advice. I'd try myself but I'm Cloudflare-blocked because nowadays W3 has very strange attitudes about who should be allowed to read information about internet technologies.

**Comment by Rjchauhan18** [comment]
Hey @mk-pmb 
I think nothing to worry about when i check everything is working fine but i found only one video which subtitles are not working but it is fine according to code. 
I have checked code and it is fine but If you want to check by yourself you can check [here](https://github.com/iv-org/invidious/blob/0e4d3d89fc96f808439a72e32a6d783d96f2c429/src/invidious/views/components/item.ecr#L29C20-L29C44)

**Comment by syeopite** [comment]
Is this really a bug? HTML5 allows you to nest a paragraph under an anchor element.

**Comment by mk-pmb** [comment]
If it's really allowed in HTML5, I may have missed that rules update. Unfortunately I'm still banned from the validator.

@Rjchauhan18
> I think nothing to worry about when i check everything is working fine

With "working fine", do you mean you tried the W3 validator and it found no complaints?

**Comment by syeopite** [comment]
> With "working fine", do you mean you tried the W3 validator and it found no complaints?

I just tried it and it found no complaints with this minimal example below. 

```html
<!DOCTYPE html>
<html lang="en">
<head><title>example</title></head>
<body>
  <a href="https://example.com">
    <p> Paragraph </p>
  </a>
</body>
</html>
```

Nesting block level elements under an anchor tag has been allowed for years in HTML5 and it is used in almost every major website.

**Comment by mk-pmb** [comment]
Thank you for checking and helping me learn. It's not a bug in iv then, after all.
