### ISSUE TITLE
[Enhancement] Personalized recommender system?

### ISSUE THREAD

**Issue by UlyssesZh** [iv-org/invidious#4169]
**Is your enhancement request related to a problem? Please describe.**
Currently, the "popular" page shows the popular videos of all accounts of an instance. Those are not necessarily videos I like.

**Describe the solution you'd like**
Have a personalized recommender system that recommends videos according to subscribes and watch histories.

**Describe alternatives you've considered**

**Additional context**

**Comment by unixfox** [comment]
Invidious is just a proxy, it doesn't have any recommendation algorithm like YouTube does. And that's not planned.
