### ISSUE TITLE
Please provide arm64 image

### ISSUE THREAD

**Issue by draeath** [iv-org/invidious#4177]
I was looking to set this up on a local server and was sad to receive this warning:

    WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })

[Please consider cross-compiling and publishing an arm64 image](https://docs.docker.com/build/building/multi-platform/).

This would also help those using hosting environments like AWS where ARM based images tend to be less expensive to run for the same relative performance.

**Comment by unixfox** [comment]
Funny that you went so far as to find the crystal issue about arm64, but you didn't find this: https://github.com/iv-org/invidious/issues/361#issuecomment-881047911 nor read the documentation: https://docs.invidious.io/installation/#docker :smiley:

**Comment by draeath** [comment]
I don't want to sound ungrateful, but what exactly was I missing from the documentation page? I just went through it again and I still don't see it.

I'm very happy to see #361 though! I have no idea how I failed to find that.

**Comment by unixfox** [comment]
![image](https://github.com/iv-org/invidious/assets/4016501/0e6a21ad-ad5e-4834-9ab5-ff8890db144a)

We can't make it obvious :smile:

**Comment by draeath** [comment]
I don't know what to say, lol

Thanks heh
