### ISSUE TITLE
[Enhancement] Fallback to "medium" when "hd720" is not available

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#4180]
**Is your enhancement request related to a problem? Please describe.**
Could you have `<instance>/watch?v=VWEmsUiQELU&raw=1&quality=hd720&local=true` automatically redirect to `<instance>/latest_version?id=VWEmsUiQELU&itag=18&local=true` instead of it redirecting to the significantly inferior 3gpp video, as it currently does?

**Describe the solution you'd like**
Basically, in the absence of `itag=22`, `&quality=hd720` should try `itag=18` first before falling back to the lower quality versions. The user shouldn't have to explicitly specify `&quality=medium` to have invidious get the `itag=18` version.

**Additional context**
Reported by "margeauxleblanc" on Matrix

**Comment by unixfox** [comment]
Related https://github.com/yt-dlp/yt-dlp/issues/3372

**Comment by unixfox** [comment]
hd720 is gone: https://github.com/iv-org/invidious/issues/4759
