### ISSUE TITLE
[Enhancement] Please add the mpd_version path or query parameter to the DASH manifest URLs you get from YouTube

### ISSUE THREAD

**Issue by absidue** [iv-org/invidious#4186]
**Is your enhancement request related to a problem? Please describe.**
For live streams and post-live-DVR videos, Invidious returns the manifest from YouTube. Unfortunately by default those manifests are very verbose, so verbose that the live ones never load in shaka-player. This is caused by YouTube listing the URLs for all 5 second segments going back 4 hours for every stream in the manifest, that means that for each stream, there are over 2k elements.

Adding the `mpd_version` parameter with the value set to `5`, makes YouTube return a manifest that uses templates instead of that gigantic list, so the player can generate the list of segments based on the template instead of having to parse all the elements in the segment lists.

The difference is even noticable by looking at the file size, for the lofi girl live stream, the default one is 2.08MB, whereas the v5 one is only 30.4KB.

**Describe the solution you'd like**
When Invidous fetches the manifest from YouTube, I would like it to add the `mpd_version` parameter with the value of `5` to the URL.

YouTube supports two ways of providing parameters, in the path or the query.

This pseudo code handles both cases:

```js
if (dashManifestUrl.includes('?')) {
    dashManifestUrl += '&mpd_version=5'
} else {
    dashManifestUrl += `${dashManifestUrl.endsWith('/') ? '' : '/'}mpd_version/5`
}
```

As Invidous can't use those manifests itself (YouTube uses self-initialising segments for their live and post-live-dvr videos, which video.js doesn't support), this change won't make any difference to Invidious, but 3rd party players interacting with the Invidous API would benefit from it a lot.

**Describe alternatives you've considered**
Currently I'm just using the HLS manifest instead, which doesn't provide any seeking (the live DASH manifests give you 4 hours) but at least you can watch the live stream.

**Comment by SamantazFox** [comment]
Wow, that's stupid! It goes from 2M+ characters (~43200 lines) down to 50k characters (~185 lines). Thanks for the tip!
