### ISSUE TITLE
[Bug] Index out of bounds (IndexError)

### ISSUE THREAD

**Issue by cnstudios** [iv-org/invidious#4188]
**Describe the bug**
Receiving an index out of bounds error when importing Youtube playlist

**Steps to Reproduce**
1. Export playlists through youtube takeout
2. Unzip takeout file
3. Go to Settings -> Import/Export data
4. Select Youtube playlist file and click "Import"

**Logs**
> Title: `Index out of bounds (IndexError)`
> Date: `2023-10-20T10:38:07Z`
> Route: `/data_control?referer=%2Fsubscription_manager`
> Version: `2023.10.20-0e4d3d8 @ master`
> 
> <details>
> <summary>Backtrace</summary>
> <p>
>    
> ```
> Index out of bounds (IndexError)
>   from /usr/share/crystal/src/json/any.cr:237:3 in 'update_data_control'
>   from lib/kemal/src/kemal/route.cr:12:9 in '->'
>   from src/invidious/helpers/handlers.cr:30:37 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
>   from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
>   from src/invidious/helpers/handlers.cr:94:12 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
>   from src/invidious/helpers/handlers.cr:151:29 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
>   from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
>   from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
>   from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
>   from ???
> ```
> </p>
> </details>

**Additional context**
 - Invidious selfhosted on Synology NAS through Docker

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4069
