### ISSUE TITLE
[Bug] Unable to Switch Language on Multilingual YouTube Videos

### ISSUE THREAD

**Issue by LilToaster69** [iv-org/invidious#4194]
**Describe the bug**
When attempting to view multilingual content on Invidious, I encounter difficulties with language switching. Despite content creators translating their videos into other languages on YouTube, I cannot switch to the desired language on Invidious.

**Steps to Reproduce**
- Visit the Invidious.
- Search for a YouTube video that has been translated into multiple languages.
- Click on the video to play it.

**Additional context**
 - Browser (if applicable): Mozilla Firefox 118.0.2
 - OS (if applicable): Arch Linux on my PC and Ubuntu 22.04 LTS on the Server that runs Invidous

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
