### ISSUE TITLE
Bug in the audio-only mode

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4202]
Hi. Since Audio-only mode requires proxy videos to be active, I suggest it would be a fix that when the user clicks audio-only on a video. it plays it with proxy videos active so there wont be any error.
You may be saying what am I talking about, Well I've mentioned this in some previous issues that "Audio-only" mode has a bug on some instances that it requires the proxy option to be active unless it will display an error.
![Capture](https://github.com/iv-org/invidious/assets/106415257/0a6b9fda-10a4-4925-afa4-5e75d919c399)

And this is my idea for fixing this error: To activate proxy option automatically for "Audio-Only" mode. (Only for that tab and video, not the whole account).

**Comment by unixfox** [comment]
> Since Audio-only mode requires proxy videos to be active

Absolutely not true, audio mode only works without proxy enabled.

Closing as there is already a built-in logic that try to load the audio in proxy if it didn't work without proxy.
