### ISSUE TITLE
[Bug] Thumbnails appear as blank with dotted lines.

### ISSUE THREAD

**Issue by ImagineGamesTech** [iv-org/invidious#4207]
All thumbnails on yewtu.be are blank with dotted outlines.
![IMG_4495](https://github.com/iv-org/invidious/assets/136746250/91f0a224-dbfc-44aa-b992-5982b2b0638b)

This happens on every page of the site that contains videos.

OS: Windows 10
Browser: Chrome 118

**Comment by unixfox** [comment]
Please create a bug report on the repository of the instance: https://github.com/yewtudotbe/invidious-custom/issues
