### ISSUE TITLE
Bind instead of volumes

### ISSUE THREAD

**Issue by shandshellin** [iv-org/invidious#4210]
I have tried to tu use bind ont he compose file with little success. Would you have any idea what format it needs to be for bind mounts to work?

**Comment by unixfox** [comment]
Closing as this is a basic docker compose issue and this bug tracker is for issues related directly to invidious.

Please use dedicated forums like https://forums.docker.com/

**Comment by shandshellin** [comment]
Sigh, this is why i asked for manual service creation steps rather than a yml. Could you provide old documentation from before it was a yml that i could extrapilate from. I check compose v3 and i'm using the syntax properly just not working with the provided yml.

**Comment by unixfox** [comment]
For such questions we also have a place to ask for help where there will probably be one or more people that will find the time to help you.

Either on matrix: https://matrix.to/#/#invidious:matrix.org or IRC: https://web.libera.chat/?channel=#invidious

On this bug tracker there is mainly only the maintainers that read it so we do not have the time to help for custom setups outside of what we officially support.
