### ISSUE TITLE
[Enhancement] Option --restrict-filenames should de-zalgo.

### ISSUE THREAD

**Issue by mk-pmb** [iv-org/invidious#4212]
**Is your enhancement request related to a problem? Please describe.**

I had to manually fix the output filename for a video whose title contains lots of character decorations ([Zalgo](https://en.wikipedia.org/wiki/Zalgo_text)):

```text
$ ytdl-rg3 --format=18 --get-title -- i41M0no6ff4
Film Theory: There Is Only DAD DaD ͈͘DAd ̒̇͞d̻̈́̚aD dAD

$ ytdl-rg3 --format=18 --output='%(title)s' --get-filename -- i41M0no6ff4
Film_Theory_-_There_Is_Only_DAD_D_a_D_DA_d_d_a_D_d_A_D
```

(Why I need `--format=` to read the title can be left for another day.)

**Describe the solution you'd like**

Let's automatically dezalgo the input before restricting filename. On PyPI I found [zalgolib](https://pypi.org/project/zalgolib/) but it may be easier to just regexp-replace the unicode ranges mentioned there.

**Describe alternatives you've considered**

```text
$ ytdl-rg3 --format=18 --get-title i41M0no6ff4 | tr -cd 'A-Za-z \n' | tr ' ' _
Film_Theory_There_Is_Only_DAD_DaD_DAd_daD_dAD
```

… was a good enough work-around for this specific video.

**Additional context**

**Comment by unixfox** [comment]
Wrong github repository. Closing...

**Comment by mk-pmb** [comment]
Whoops. Sorry for causing you needless effort!
