### ISSUE TITLE
[Feature request] Search within a channel

### ISSUE THREAD

**Issue by Olejja** [iv-org/invidious#4217]
If you go to any channel on YouTube, you will see a special icon for searching within the channel. I would like to see the same feature in invidious.

**Comment by unixfox** [comment]
That's already possible. Go to the channel that you want to search within then you just have to type the query word after the channel ID.

Example:

![image](https://github.com/iv-org/invidious/assets/4016501/f21bc100-468e-4f47-8e5c-d981f67c6664)
