### ISSUE TITLE
[Question] DASH not functional unless on mobile browser

### ISSUE THREAD

**Issue by gil-roboute** [iv-org/invidious#4234]
DASH quality is all of a sudden unusable across all devices on my local network with the exception of my smartphone - it appears to be a CSP issue. 

Content-Security-Policy: The page’s settings blocked the loading of a resource at "video url" (“connect-src”).

Screenshots attached for error reference.

> Content-Security-Policy: The page’s settings blocked the loading of a resource at _**![Issues](https://github.com/iv-org/invidious/assets/145676840/cac245d9-c2cc-4c50-aff1-a0d485f87c85)**_ (“connect-src”). video.js:8080:8

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by unixfox** [comment]
please explain how you installed invidious.......

**Comment by gil-roboute** [comment]
My instance is currently deployed on a DigitalOcean Ubuntu 22.04 LTS droplet that is reverse proxied to a domain that I own.Thanks    ---- On Tue, 07 Nov 2023 22:04:55 +1000  Émilien ***@***.***> wrote ----  
please explain how you installed invidious.......

**Comment by unixfox** [comment]
you have only explained where you installed invidious, I'm asking the how

**Comment by gil-roboute** [comment]
Apologies - it was a manual install - I’m not a docker fan.    ---- On Tue, 07 Nov 2023 22:23:33 +1000  Émilien ***@***.***> wrote ----  
you have only explained where you installed invidious, I'm asking the how

**Comment by unixfox** [comment]
This sounds like a configuration issue on your issue.

I think it's much better if you ask on matrix or IRC for any issue like this: https://github.com/iv-org/invidious#chat-with-us

Because GitHub is really not designed for a continuous discussion like your problem.
