### ISSUE TITLE
[Enhancement] Sort Playlist Videos

### ISSUE THREAD

**Issue by kenderbard** [iv-org/invidious#4236]
**Is your enhancement request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Would love to be able to sort the videos in my playlists. Suggested options: Length, Date Released, Alphabetically, Publisher, Views

**Describe alternatives you've considered**
I haven't really seen any way of doing this manually in a way that makes sense so if anyone has any suggestions, I would appreciate it. I suppose you could export the list, reorder it however you want in the CSV, and then reupload it?

**Additional context**
Was inspired by this website, which lets you sort YT playlists: https://ytplaylistsorter.carterrj.co.uk/index.php

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/1870
