### ISSUE TITLE
[enhancement] Dead link in README

### ISSUE THREAD

**Issue by GoldDominik893** [iv-org/invidious#4237]
**Describe the bug**
The link for Watchtube in the README.md file leads to a 404 page.

**Screenshots**

![brave_3elZ2ffvsn](https://github.com/iv-org/invidious/assets/68468388/b952a82a-8210-43d6-8524-49f92bf982f9)
![brave_uHp1JMQfaw](https://github.com/iv-org/invidious/assets/68468388/2ff288a2-e193-4d84-bd8f-ea88667868ae)

**Comment by unixfox** [comment]
Feel free to submit a change it is not that difficult.

**Comment by syeopite** [comment]
Should be fixed by #3853
