### ISSUE TITLE
[Bug] Random API-side 500s on /channel/ - Could not get channel info. 

### ISSUE THREAD

**Issue by markozajc** [iv-org/invidious#4238]
**Describe the bug**
YouTube seems to randomly return 500 on the channel browse route. Invidious simply displays "Could not get channel info." when that happens.
**Steps to Reproduce**
1. Go to a channel page (any seems to work, I used `/channel/UCSMOQeBJ2RAnuFungnQOxLg`)
2. Refresh a few times
3. See error

**Logs**
```
[debug] YoutubeAPI: Using endpoint: "/youtubei/v1/browse"
[trace] YoutubeAPI: ClientConfig: YoutubeAPI::ClientConfig(@client_type=YoutubeAPI::ClientType::Web, @region="US", @proxy_region=nil)
[trace] YoutubeAPI: POST data: {"browseId" => "UCSMOQeBJ2RAnuFungnQOxLg", "context" => {"client" => {"hl" => "en", "gl" => "US", "clientName" => "WEB", "clientVersion" => "2.20230602.01.00", "clientScreen" => "WATCH_FULL_SCREEN", "osName" => "Windows", "osVersion" => "10.0", "platform" => "DESKTOP"}}, "params" => "EgVhYm91dA=="}
[error] YoutubeAPI: Got error 500 when requesting /youtubei/v1/browse
[error] YoutubeAPI: Internal error encountered.
[info] YoutubeAPI: POST data was: {"browseId" => "UCSMOQeBJ2RAnuFungnQOxLg", "context" => {"client" => {"hl" => "en", "gl" => "US", "clientName" => "WEB", "clientVersion" => "2.20230602.01.00", "clientScreen" => "WATCH_FULL_SCREEN", "osName" => "Windows", "osVersion" => "10.0", "platform" => "DESKTOP"}}, "params" => "EgVhYm91dA=="}
[info] 500 GET /channel/UCSMOQeBJ2RAnuFungnQOxLg 60.02ms
```

**Additional context**
Invidious version: 2414e7db
I used my selfhosted instance, but this behaviour is observable on public instances too (I tried vid.puffyan.us).
This started happening roughly a week ago.

**Comment by Phantop** [comment]
Yeah I've been seeing this constantly in recent days—it's really affecting my usage of RSS feeds where out of 85 channels over half are constantly getting the error across numerous public instances.

**Comment by syeopite** [comment]
This seems to occur even on local instances. I wonder if this is a problem on YouTube's side or are they just trying to introduce another method to block us

**Comment by syeopite** [comment]
YouTube is currently in the process of removing the channel's about tag for which Invidious uses to fetch basic channel information

**Comment by syeopite** [comment]
https://github.com/iv-org/invidious/blob/438467f69a20007cace4f300d03138b7d2d7e79a/src/invidious/channels/about.cr#L22

Changing the protobuf param here to the latest `EgVhYm91dPIGBAoCEgA=` seems to significantly reduce the chances of this happening.

**Comment by iBicha** [comment]
It started random, but now no calls succeed at all

**Comment by NolonQ** [comment]
I can confirm this issue is happening right now, it started maybe two weeks back? But as of today every channel on all instances returns "Could not get channel info" error.

**Comment by thesreal** [comment]
same with me. every single instance gives the issue

**Comment by dommangetnicolas** [comment]
I am getting the same behaviour on my instance

**Comment by MintMain21** [comment]
I see I'm not the only person to notice this.

Hello Bug Report thread! Looking forward to getting any updates.

**Comment by iBicha** [comment]
> YouTube is currently in the process of removing the channel's about tab for which Invidious uses to fetch basic channel information

Speaking of, before this started happening, I was noticing something: for certain channels, calling `api/v1/channels/ucid` did not always return the same tabs. Sometimes the related channels is missing, sometimes it is there. Refresh and get new results again. The tabs definitely are being tinkered with.

**Comment by syeopite** [comment]
Should be fixed by #4241

**Comment by iBicha** [comment]
> Howdy! I apologize if this sounds stupid but I am still receiving status code 500 attempting to view channels even after following the [update procedure for Docker installation written here](https://docs.invidious.io/installation/#updating-a-docker-install).
> 
> ```
> [error] YoutubeAPI: Got error 500 when requesting /youtubei/v1/browse
> [error] YoutubeAPI: Internal error encountered.
> [info] YoutubeAPI: POST data was: {"browseId" => "UCSMOQeBJ2RAnuFungnQOxLg", "context" => {"client" => {"hl" => "en", "gl" => "US", "clientName" => "WEB", "clientVersion" => "2.20230602.01.00", "clientScreen" => "WATCH_FULL_SCREEN", "osName" => "Windows", "osVersion" => "10.0", "platform" => "DESKTOP"}}, "params" => "EgVhYm91dA=="}
> [info] 500 GET /channel/UCSMOQeBJ2RAnuFungnQOxLg 66.33ms
> ```

Make sure you're on the latest version (it should say `Current version: 2023.11.08-c5b87e3 @ master` at the bottom of the page)

**Comment by MintMain21** [comment]
Wait a minute. 

Wasn't there another issue with loading channels on a video that was resolved with a redirect script to a playlist with the most recently uploaded videos?
