### ISSUE TITLE
[Enhancement] Gitlab Repository

### ISSUE THREAD

**Issue by MintMain21** [iv-org/invidious#4248]
**Is your enhancement request related to a problem? Please describe.**
Github has become too comfortable with AI for my taste. I have moved all my Userscripts to Gitlab and I encourage as many open source projects that I care about to do the same.

**Describe the solution you'd like**
An Invidious Repository on Gitlab, either as a clone or a replacement for the Github repository.

**Describe alternatives you've considered**
As far as I know, Gitlab is the most popular Github alternative and makes it easy to migrate. It seems in turn to be the most logical alternative. 

**Additional context**

**Comment by syeopite** [comment]
We do currently have a gitea mirror here https://gitea.invidious.io/iv-org/invidious
