### ISSUE TITLE
Dash as fallback

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#425]
There are some videos that only play with dash but that has playback issues on some occasions. it would be nice to be able to control the priority of video qualities precisely. people on mobile might prefer the lowest quality while others prefer the highest and some want dash as the primary and no fallbacks for anonymity. i think this could be done with a drag'n'drop list with javascript and a set of dropdown menus without.

**Comment by dimqua** [comment]
Yes, just like multiple subtitle variants are handled. I think it's a good idea, since dash quality is not always stable in my case. 

BTW, you don't need to use dash for avoid google connections anymore.

**Comment by omarroth** [comment]
This was mentioned recently in the Matrix server, copied here for convenience:

> @omarroth:
> The plugin I'm using to provide dash currently gives me very little control over playback. I can set the default bitrate, but that doesn't seem very useful, and the user has no control for selecting the quality they want.

> As mentioned in #34, I'd rather wait until [this project](https://github.com/videojs/http-streaming) is mature enough to be used in Invidious, since it's much smaller, supports hls+dash, and provides proper options for changing quality

The plugin that's currently being used also has issues with playback as you mentioned (see #193).

I would rather not handle that myself and there is an excellent project [videojs-http-source-selector](https://github.com/jfujita/videojs-http-source-selector) that provides the requested functionality out of the box.

Expect this to be added as part of #34.

Which videos are you only able to play with dash?

**Comment by elypter** [comment]
streams in general but also some others which i havent inspected further yet.

**Comment by johnwmail** [comment]
HI, I meet this problem on android/firefox, can not play with 720/360, only can play dash.
What is disadvantage set dash as default?
Thanks.

**Comment by omarroth** [comment]
Dash currently has some minor issues with playback (see #193) and is more bandwidth intensive for the site. Both of these issues are being worked on, but I currently don't consider it stable enough to have enabled by default or as fallback.
