### ISSUE TITLE
[Question] Non logged in users see videos suggestions from the logged in user subscribtions

### ISSUE THREAD

**Issue by ahmadyusuf** [iv-org/invidious#4258]
**Describe the bug**
I am using Invidious as a docker container with only one user, the user imported subscription information from YouTube. When someone opens Invidious without logging in, even on a different browser or Incognito mode, the popular videos they can see as suggestions actually belong to the channels subscribed by the only user, which is a privacy issue.

**Steps to Reproduce**
1. Create an Invidious container using docker-compose
2. Create a new user
3. Import subscription history from YouTube
4. Navigate to Invidious self-hosted URL from another device/browser
5. You will see video suggestions from the channel import in step 3

**Comment by unixfox** [comment]
Just disable the popular feed then. Obviously on a small scale of users some popular videos may be from channels that the users subscribed to.

That's the entire point of the popular feed.

https://docs.invidious.io/faq/

**Comment by ahmadyusuf** [comment]
Got it, thanks for your prompt response
