### ISSUE TITLE
[Bug] Channel videos pagination through API not working

### ISSUE THREAD

**Issue by Garakusi** [iv-org/invidious#4261]
**Describe the bug**

All page numbers return first page in the `/api/v1/channels/videos/UCID?page=` endpoint.

**Steps to Reproduce**

1. Request page 1: `https://some.invidious.instance/api/v1/channels/videos/UCID?page=1`
2. Request page any other page: `https://some.invidious.instance/api/v1/channels/videos/UCID?page=?`
3. Compare requests
4. Both return the same data

**Comment by RadoslavL** [comment]
That's because the channel API routes don't use numeric pages, but rather continuation-based pages. So if you need to switch to the second page, you need to get the next continuation from the API, and add it to the URL instead of the `page` parameter.

**Comment by Garakusi** [comment]
Thanks for clarifying. Because the playlists endpoint use numeric pages I assumed the channel videos would be the same.
