### ISSUE TITLE
[Enhancement] Have a `Default` language selection option in the settings which uses the browsers locale

### ISSUE THREAD

**Issue by ccuser44** [iv-org/invidious#4263]
**Is your enhancement request related to a problem? Please describe.**

- Sometimes you don't get translations for the menu.

**Describe the solution you'd like**

- Have a `Default` language selection option in the settings which uses the browsers reported locale. If the browsers reported locale is not available it uses english.

**Describe alternatives you've considered**

- Set the setting to the browsers locale. There may be numerous reasons  relating to settings why this doesn't work as well.

**Comment by unixfox** [comment]
Can you post a screenshot of this?

I think that's the current behavior to default to English.

**Comment by ccuser44** [comment]
> I think that's the current behavior to default to English.

Right, but I think there should be a seperate option called Default which makes the server always use the translation from the clients locale headers

**Comment by unixfox** [comment]
That's already the case, the server default to the language sent by the browser.

If the browser do not send any language then it's default to English.
