### ISSUE TITLE
[Feature request] DuckDuckGo-like ability to open first search result, using !

### ISSUE THREAD

**Issue by leoheitmannruiz** [iv-org/invidious#4268]
**Is your feature request related to a problem? Please describe.**
Often, searching for a video, the first search result is the video I was searching. I then have to select that first search result, which is annoying.

**Describe the solution you'd like**
I want to be able to decide, while entering the search query, to directly open the first result. Just like DuckDuckGo offers the ability to prepend or append an exclamation mark (!) to directly open the first search result.

**Comment by Magikh42** [comment]
Exclamation marks are used for bangs
First result shortcut is '\' (backslash)
Also, I already asked it in #3356

**Comment by leoheitmannruiz** [comment]
Thanks!
