### ISSUE TITLE
[Feature request] a distributed database among instances to cache where most requested videos can actually be streamed from

### ISSUE THREAD

**Issue by pezcurrel** [iv-org/invidious#4269]
One of the main problems why so many users, despite knowing of the existence of invidious, prefer to use youtube directly or link directly to videos from yotube in their social posts, etc., lies in the fact that it often happens that from an invidious instance a certain video cannot be streamed, so then the user would have to use the page that is accessible from the "switch invidious instance" link to search for the video on other instances until they find one that can stream it.

I think this problem could be mitigated, perhaps quite a bit, if it could be made that each invidious instance contributes to update a distributed database among all instances when a video is requested, with the status of "available" or not relative to that instance, and a timestamp of the check. Thus the distributed, constantly updating database would give each instance a way to know, with respect to the most requested videos, on which instances they are possibly available. At that point, when a user were to search, from any instance, for a certain video, if the video turned out to be available on the one on which he or she is searching, it would be streamed through that one; if it did not turn out to be available on that one, but turned out to be available on other instances that had checked it up to X amount of time before, a redirect would take place to the instance that had checked it as available most recently ("X" perhaps could be a constant, such as 1 day, or perhaps it could be evaluated according to more complex criteria); if it was not available on the initial instance and was not available on any others that had checked it up to X time before, or if no other instance had ever checked it before, it would work as it does now, i.e., the user would have to go to the page with the list of other instances accessible from the "switch invidious instance" link, and hope to find one where it is available (but the list could exclude those instances on which at the last possible check the video was found to be unavailable, if the last check had been done up to X time before).

I know little about distributed databases, however openpgp keyservers instances used to synchronize with each other (and some still do) a considerable amount of openpgp public keys, so perhaps it would be feasible.

**Comment by pezcurrel** [comment]
Also, the "switch invidious instance" page could query other instances with the same query the user made on the first, and return only those that can stream it; or, maybe even better, the query would be done on the other instances as soon as the user sends it to the instance (s)he is using.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/879
