### ISSUE TITLE
[feature request] Add API for subscriptions and account registration

### ISSUE THREAD

**Issue by lnjX** [iv-org/invidious#427]
I'm currently working on a convergent Invidious app for [KDE Plasma Mobile](https://plasma-mobile.org) & desktop. I'm using the Invidious API and I'd like to "sync" subscriptions across devices and get the latest subscriptions as on the website. It'd be great if you could also add an API for:
* registering new accounts
* logging in
* getting latest videos from subscriptions
* (un)subscribing from channels

**Comment by omarroth** [comment]
Very nice! Mind hopping on the [Matrix server](https://riot.im/app/#/room/#invidious:matrix.org) to discuss implementation details? I'm sure quite a few other people there would be very interested in this, and I've been looking into a way to provide similar functionality for #114.

**Comment by omarroth** [comment]
See both #469 and #473 for handling the last two items on your list.
