### ISSUE TITLE
[Feature request] Support changing audio stream / dub (similar to how subtitle caption choices work)

### ISSUE THREAD

**Issue by accessiblepixel** [iv-org/invidious#4309]
I was watching Tom Scott's latest video on Subtitling and Dubbing, and noticed that there was no option within Invidous to change the stream to one of the alternative dubs (as there is in the youtube UI) and I was presented with playback that was not my native language.

This would be something great to support if it were possible. :)

Link to his video: https://www.youtube.com/watch?v=pU9sHwNKc2c

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A similar way to select the audio stream akin to how you can select subtitle languages.

Thank you for reading!

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007

**Comment by accessiblepixel** [comment]
Thanks @unixfox - tried looking for an existing issue before posting but didn't come across one. Thanks for pointing that out, will track that for updates!
