### ISSUE TITLE
[Bug] default_home not working

### ISSUE THREAD

**Issue by techcow2** [iv-org/invidious#4316]
**Describe the bug**
I'm having a hard time getting "default_home: Trending" to work. I was able to disable the Popular feed using 'popular_enabled: false' and it shows disabled on the instance page. However, I have 'default_home' set to 'default_home: Trending" and when you open my instance it goes straight to the Popular feed.

**Here is my docker-compose file:**

> version: "3"
> services:
> 
>   invidious:
>     image: quay.io/invidious/invidious:latest
>     # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
>     restart: unless-stopped
>     ports:
>       - "3468:3000"
>     environment:
>       # Please read the following file for a comprehensive list of all available
>       # configuration options and their associated syntax:
>       # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
>       INVIDIOUS_CONFIG: |
>         db:
>           dbname: invidious
>           user: kemal
>           password: kemal
>           host: invidious-db
>           port: 5432
>         check_tables: true
>         # external_port:
>         domain: _REDACTED_
>         login_enabled: false
>         default_home: Trending
>         popular_enabled: false
>         # https_only: false
>         # statistics_enabled: false
>         hmac_key: _"REDACTED"_
>     healthcheck:
>       test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
>       interval: 30s
>       timeout: 5s
>       retries: 2
>     logging:
>       options:
>         max-size: "1G"
>         max-file: "4"
>     depends_on:
>       - invidious-db
> 
>   invidious-db:
>     image: docker.io/library/postgres:14
>     restart: unless-stopped
>     volumes:
>       - postgresdata:/var/lib/postgresql/data
>       - ./config/sql:/config/sql
>       - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
>     environment:
>       POSTGRES_DB: invidious
>       POSTGRES_USER: kemal
>       POSTGRES_PASSWORD: kemal
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
> 
> volumes:
>   postgresdata:

**Comment by unixfox** [comment]
Default home is after the "user:" section in yaml.

**Comment by syeopite** [comment]
If I'm not mistaken the `default_home` parameter is actually placed under the `default_user_preferences` section
