### ISSUE TITLE
[Bug] I'm unable to change to watch videos in 'Dash' quality on my own instance, but I'm able to on other instances - "The media could not be loaded, either because the server or network failed or because the format is not supported."

### ISSUE THREAD

**Issue by techcow2** [iv-org/invidious#4317]
**Issue:**

If I switch to Dash quality in the preferences, I receive the following error: 

> The media could not be loaded, either because the server or network failed or because the format is not supported.

This only happens on my instance. When I use a public instance, I have no problem. I am new to self-hosting, so It's probably something I did wrong. Any help would be appreciated. Thanks!

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.

**Comment by pihomeserver** [comment]
@techcow2 in case you have the solution it would be great to share it as i also have the same issue even after following the configuration guide

**Comment by tarbib** [comment]
same here @pihomeserver

**Comment by techcow2** [comment]
> same here @pihomeserver

I'm not sure where the comment went, but I uninstalled this after I was told that they were too busy to help me with this issue and to go somewhere else.
