### ISSUE TITLE
[Bug] Subtitles aren't rendered at all

### ISSUE THREAD

**Issue by bicolino34** [iv-org/invidious#4324]
**Describe the bug**
When I turn on subtitles in videos, there is always no text appearing. It happens for both auto-generated and manually created subtitles on Youtube in both Invidious and Youtube style players. Changing appearance setting doesn't help.
In settings I set subtitles main languages to Japanese, Ukrainian and then Japanese (auto-gen).

**Steps to Reproduce**
1. Go to any video with subtitles
2. Turn on subtitles
3. See subtitles not being rendered

**Logs**

**Screenshots**
Same video in the same moment
Youtube
![зображення](https://github.com/iv-org/invidious/assets/58372007/e467fc37-86db-4bd6-ae89-362caf510d8b)

Invidious
![зображення](https://github.com/iv-org/invidious/assets/58372007/a5a4ebf5-0e11-4e2d-84c1-f614331fddae)

**Additional context**
 - Browser (if applicable): Mozilla Firefox 117.0.1
 - OS (if applicable): Linux Mint
- Invidious version: 2023.12.06-72478ba @ master
- Instance I use is https://onion.tube/watch?v=Ng5sHevRX3w

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2567#issuecomment-1727928996
