### ISSUE TITLE
Issue with paused videos

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#433]
After a few minutes, they start to play on their own. It is happening in the latest Pale Moon.

**Comment by omarroth** [comment]
I'm having trouble reproducing in 28.4.0. Could you check the console to see if it is reporting any errors before it starts playing?

**Comment by CSDUMMI** [comment]
Could this issue be related?
https://github.com/omarroth/invidious/issues/327

**Comment by omarroth** [comment]
Yes, from a quick glance it appears this is likely a duplicate of #327.
