### ISSUE TITLE
[Bug] shorts tab 2nd page is empty

### ISSUE THREAD

**Issue by umikali222** [iv-org/invidious#4330]
**Describe the bug**
when you go to a channel's shorts tab, and go to the 2nd page it's empty

**Steps to Reproduce**
1. go to any invidious instance
2. go to any channel with many short videos eg. [Daily Dose Of Internet](https://invidious.io.lol/channel/UCdC0An4ZPNr_YiFiYoVbwaw/shorts)
3. go to the 2nd page

**Additional context**
I first found this on my self-hosted instance, and when I tried it on invidious.io.lol the same thing hapenned

**Comment by SamantazFox** [comment]
Duplicate of #4029
