### ISSUE TITLE
Lemmy comments on Invidious [Enhancement] 

### ISSUE THREAD

**Issue by slrgt** [iv-org/invidious#4331]
**Is your enhancement request related to a problem? Please describe.**

Invidious already supports Reddit comments but as the API for reddit was ruined a lot of people moved to Lemmy which is an open source federated alternative to reddit.

**Describe the solution you'd like**
It would be great to have Lemmy comments appear on videos similar to how the reddit comments appear. There is already a firefox\chrome extension that makes this possible and maybe the source code of that extension could help invidious devs implement Lemmy comments on Invidious https://github.com/Xyl-AU/Reddit-Comments-for-YouTube

**Comment by unixfox** [comment]
Would you be willing to contribute to this feature? It's not that difficult if you already know a little bit about programming and we can help you for sure.

**Comment by slrgt** [comment]
> Would you be willing to contribute to this feature? It's not that difficult if you already know a little bit about programming and we can help you for sure.

I would love to contribute the feature but other than very beginner python I don't know any programming :/ I'm not sure if I would be able to understand enough of the code to be able to contribute something like this.

Although the extension was updated to now be able to display Reddit and Lemmy comments on _any_ website. If I understand correctly this will only work for invidious links that have been submitted to Lemmy and not the youtube links that corresponds to the invidious link though. Which would also be different depending on what invidious instance you're on :/

**Comment by Fa-zz** [comment]
> Would you be willing to contribute to this feature? It's not that difficult if you already know a little bit about programming and we can help you for sure.

Hey, I'm interested in contributing, but I would need some help to get started as I'm not entirely sure how to

**Comment by unixfox** [comment]
Feel free to join our matrix: https://matrix.to/#/#invidious:matrix.org or IRC: https://web.libera.chat/?channel=#invidious to discuss more about it.

**Comment by syeopite** [comment]
Related: #264, #1278
