### ISSUE TITLE
The site keeps being down every few minutes

### ISSUE THREAD

**Issue by TommyTonka** [iv-org/invidious#4332]
For no reason, the site keeps being down a few minutes, either if it's 
503 backend fetch or Google Chrome's "took too long to respond" error, cn you guys please fix that

**Comment by syeopite** [comment]
Which instance are you using? Invidious does not have an official instance of Invidious so we cannot control when an instance goes down.

There is an website, https://invidious.io, but that's just a landing page about Invidious itself. 

Your best bet is to use another instance here over at https://instances.invidious.io
