### ISSUE TITLE
[Bug] What... WAT?!?!?!

### ISSUE THREAD

**Issue by TommyTonka** [iv-org/invidious#4337]
Every time I go to a video, I keep getting THIS:
![waa](https://github.com/iv-org/invidious/assets/110128256/8e9488fe-a330-4f92-9fcc-b0a9669970e5)

What am I supposed to do, go to YouTube?! I can't deal with "Includes paid promotion", the information panels, Premieres ("Show chat replay"), "Comments are turned off", "Most replayed"! I hate those things!!

**Comment by iam-py-test** [comment]
Try clicking "Switch Invidious Instance".
Also might be helpful for the maintainers to know:
- What video you are trying to play
- What instance you are using
- Browser version (probably irrelevant)

Thanks
