### ISSUE TITLE
[Bug] MrBeast videos do not play in English audio

### ISSUE THREAD

**Issue by Bubba8291** [iv-org/invidious#4340]
**Describe the bug**

When I play any MrBeast video, the audio is not in English and there is no way to fix it.

**Steps to Reproduce**

1. Search MrBeast
2. Click on one of his videos
3. Click play
4. Hear the audio not in English

**Logs**

**Screenshots**

**Additional context**

I am using a self hosted instance.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
