### ISSUE TITLE
[Bug] Dash formats use audio tracks from different languages

### ISSUE THREAD

**Issue by PixieCat-dev** [iv-org/invidious#4350]
when using this iv.datura.network/latest_version?id=6acSH-EXoU0&local=true

it plays with the english audio track but when using this

iv.datura.network/latest_version?id=6acSH-EXoU0&local=true&itag=140

it plays the hispanic audio track the video has 2 audio tracks: english and hispanic

**Comment by absidue** [comment]
Duplicate of #2007
