### ISSUE TITLE
[Feature request] Make it easier to configure a custom npm registry base URL.

### ISSUE THREAD

**Issue by mk-pmb** [iv-org/invidious#4360]
**Is your feature request related to a problem? Please describe.**
In my network setup, the docker container cannot directly download from https://registry.npmjs.org/ , so I'd like to configure my own npm registry URL pointing to a local mirror.

**Describe the solution you'd like**
Maybe a docker build arg or something.

**Describe alternatives you've considered**
Changing the hard-coded URL in [fetch-player-dependencies.cr line 86](https://github.com/iv-org/invidious/blob/97c4165f55c4574efb554c9dae8d919d08da1cdd/scripts/fetch-player-dependencies.cr#L86)

**Additional context**

**Comment by mk-pmb** [comment]
Actually, I have an even better idea. I'll leave this around closed to help other people find it who had the same initial approach.

**Comment by unixfox** [comment]
Feel free to submit a PR for being able to configure the npm registry URL.

There is an example here for using crystal flags: https://github.com/iv-org/invidious/blob/97c4165f55c4574efb554c9dae8d919d08da1cdd/src/invidious/routes/misc.cr#L1
