### ISSUE TITLE
[Bug]  Error opening file with mode 'r': 'locales/ar.json': No such file or directory (File::NotFoundError)

### ISSUE THREAD

**Issue by rocket2021** [iv-org/invidious#4363]
Unhandled exception: Error opening file with mode 'r': 'locales/ar.json': No such file or directory (File::NotFoundError)
  from /usr/share/crystal/src/crystal/system/unix/file.cr:11:7 in 'read'
  from /home/invidious/invidious/src/invidious/helpers/i18n.cr:75:32 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from /home/invidious/invidious/invidious in '_start'
  from ???

Crystal Version : 1.8

**Comment by miranda** [comment]
Why is this closed with no explanation?  "not planned"?  I'm getting this same error trying to set up the invidious server on Arch Linux and I don't know what to do.  I tried both the normal package and invidious-git from the AUR.

**Comment by miranda** [comment]
Nevermind, I needed to be inside the directory:

/usr/lib/invidious# ./invidious --migrate
