### ISSUE TITLE
[Bug] Certain videos don't show up in search, when directly accessed display "This video is not available"

### ISSUE THREAD

**Issue by retropele** [iv-org/invidious#4368]
**Describe the bug**
I've previously watched this channel of Iron Chef videos on Invidious, but now find they can't be searched or display in it and just say "This video is not available". This is even on instances that aren't showing the Youtube blocking invidious instances message. I'm sorry if this has been reported before, but I couldn't find it.

1. Is this an unavoidable effect because of Youtube reading Invidious as "embedding" the video?
2. Is this a new blocking attempt by Youtube? Will it be fixed if so?
3. If this is an embedding problem that can't be avoided, can there be a more helpful error message so people have an idea of what's wrong? (If this is the case then feel free to change the label to "enhancement")

**Steps to Reproduce**
1. Try to access [this video](https://invidious.nerdvpn.de/watch?v=6PCiaStrnPc) (or any videos from the FilmRise channel of Iron Chef episodes)
2. Video can't be accessed
3. When clicking "switch instance", it is still not available on any Invidious instance (that I've found)
4. When searching within Invidious they are also absent

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/123419913/02b9804b-eaf1-4903-aef7-46e4eb2d2e6f)

**Additional context**
Browser: Librewolf aarch64
Region: UK (if this is a copyright issue)

**Comment by CatPlanet** [comment]
I watched 1 video of Spookston guy on yewtu.be, I clicked [next one](https://yewtu.be/watch?v=EEvexS67PSs) (14:23 in length) and I got this:
![](https://i.imgur.com/DI7Kd1S.png)
it's 1:33 video of "This content isn't available"; thumbnail and preview on seek bar still works

I'm not sure it's related issue but the timing is interesting for sure.

**Comment by unixfox** [comment]
Closing as it's what youtube returns to invidious so we show you the error message given by youtube.

![image](https://github.com/iv-org/invidious/assets/4016501/75744f22-390e-4a8d-8d12-92403cd95719)

If I access the video from www.youtube.com I also get "This video is not available". Probably due to a georestriction but that's another issue https://github.com/iv-org/invidious/issues/92
