### ISSUE TITLE
The search for project Segfault does not return a result. 

### ISSUE THREAD

**Issue by ShakeSphereStuff** [iv-org/invidious#4381]
When using a chromebook, I could not search, as it would return an error

OS: Chromebook
Distro: Project Segfault

**Comment by ShakeSphereStuff** [comment]
Works now for some reason?

**Comment by unixfox** [comment]
we don't manage public instances. contact the maintainer of the instance or use another one at https://instances.invidious.io

**Comment by thansk** [comment]
@unixfox this seems to happen with other instances too but not for all search terms

https://yewtu.be/search?q=test works

https://yewtu.be/search?q=andy+compton - `Missing hash key: "navigationEndpoint" (KeyError)`

**Comment by syeopite** [comment]
Duplicate of #2530 then
