### ISSUE TITLE
[Bug] Podcast playlists return error 400

### ISSUE THREAD

**Issue by avidseeker** [iv-org/invidious#4382]
Example: https://yewtu.be/playlist?list=PLfx0NKbQXfNBc5n8LOXYRTMzvTofAY8d6?list=PLfx0NKbQXfNBc5n8LOXYRTMzvTofAY8d6

Returns: Could not extract JSON. Youtube API returned error 400 with message: "Request contains an invalid argument." 

Compare with the original: https://www.youtube.com/playlist?list=PLfx0NKbQXfNBc5n8LOXYRTMzvTofAY8d6

Version: Current version: 2023.12.16-4065b0b @ master

**Comment by unixfox** [comment]
Not sure why you are sending twice the `?list` parameter but it works for me like this:
https://yewtu.be/playlist?list=PLfx0NKbQXfNBc5n8LOXYRTMzvTofAY8d6

**Comment by avidseeker** [comment]
What I did was that I started with the original Youtube URL, then replaced "youtube.com" with "yewtu.be". It seems that Invidious is the one that redirected to the URL with doubled `?list` parameter.
