### ISSUE TITLE
[Enhancement] Passively Synchronize while switching instances

### ISSUE THREAD

**Issue by GitHubington** [iv-org/invidious#4389]
_Passively Synchronize while switching instances_

**Is your enhancement request related to a problem? Please describe.**

Currently, switching instances can be tedious because the user has to manually import User Data for each individual instance, and User Data can easily go out of sync between instances.

**Describe the solution you'd like**

Instances could instead:

- synchronize User Data using Browser Storage.
- share access to Browser Storage with other instances.
- use synchronization standards (e.i. timestamps, hashes) to determine which User Data version is up to date, between browser and instance.

**Additional context**

Improvement of user experience

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/879
