### ISSUE TITLE
how can i apply changes made to the config/config.yml file?

### ISSUE THREAD

**Issue by antonioraminhos** [iv-org/invidious#4395]
how can i apply changes made to the `config/config.yml` file? after i do some changes, i write ./invidious --migrate but it just says that there are no migrations to make... i also wrote this command systemctl restart invidious.service and changes were not applied, im on debian 12 and did the manual instalation

**Comment by antonioraminhos** [comment]
my instance is working perfectly fine, i just cant apply the new changes made on the the config file

**Comment by unixfox** [comment]
Closing as it's an issue on your end, and we do not have the time to help you with that.

But you can seek for help on our matrix room (https://matrix.to/#/#invidious:matrix.org) or IRC channel (https://web.libera.chat/?channel=#invidious).

People from the community will probably be able to help you.
