### ISSUE TITLE
Login feature for API

### ISSUE THREAD

**Issue by spiderbit** [iv-org/invidious#4397]
I am the author of https://melpa.org/#/ytdious and when I wrote that 3 years ago I tried to use the login feature over Json from inside my client, to as example get the list of subscriptions and seen / unseen videos.

Back then I found some docu but I couldn't get it to run, now I don't see any login related things in the API, is that dead or planed or just not good documented?

**Comment by spiderbit** [comment]
Yes I meant that, does that work, now? :D

**Comment by unixfox** [comment]
This documentation has existed for years.

I haven't tested. Feel free to try.

**Comment by unixfox** [comment]
Closing as the question has been answered.
