### ISSUE TITLE
[Bug] Instance broken due to insanely slow loads/timeouts.

### ISSUE THREAD

**Issue by voronind-com** [iv-org/invidious#4410]
**Describe the bug**
Instance is basically broken since the last update (after 3 mo since the prev update). Logs are all fine, except that every GET request takes 30-50 seconds. My sub page looks like on a screenshot bellow. If I try to open a video, I get 504 gateway timeout.

**Steps to Reproduce**
Youtube itself works great on all devices, even yt-dlp loads all great, so shouldn't be limited.

Docker instance ae354a5d026c, version 2024.01.10-1c0b420

My config:
```text
db:    
  dbname: ???
  user: ???                                                                                         
  password: ???                                                                                     
host: 10.1.0.3                                                                                          
port: 5432                                                                                              
check_tables: true                                                                                        
https_only: true                                                                                          
domain: ???                                                                                   
port: 443    
external_port: 443    
registration_enabled: false    
captcha_enabled: false    
hmac_key: ee09c90353866964690776179a5135bbe69f31c1    
admins: ["root"]
```

**Logs**
[log.txt](https://github.com/iv-org/invidious/files/14078338/log.txt)

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/22127600/dd45795f-669d-4bd0-9611-7cbf13f65454)

**Additional context**

**Comment by unixfox** [comment]
Sounds a lot like
https://github.com/iv-org/invidious/issues/4142

**Comment by unixfox** [comment]
I would prefer that you ask for help on our matrix (https://matrix.to/#/#invidious:matrix.org) or IRC (https://web.libera.chat/?channel=#invidious) because we, invidious developers, do not have the time to diagnose the misconfigurations of the users.
