### ISSUE TITLE
[Bug] RSS appears to be dead at the moment.

### ISSUE THREAD

**Issue by barkoder** [iv-org/invidious#4411]
**Describe the bug**
Invidious RSS appears to be dead. Currently youtube's own RSS is dead as well.

**Steps to Reproduce**
1. Go to https://INSTANCE/feed/channel/UC_ADhkBQFudvyhdpsBJJvYw
2. And I don't get the list of recent uploads.
3. Go to https://www.youtube.com/feeds/videos.xml?channel_id=UC_ADhkBQFudvyhdpsBJJvYw
4. And you get
    <p><b>404.</b> <ins>That’s an error.</ins>
    <p>The requested URL <code>/feeds/videos.xml?channel_id=UC80UDR9O8vDvUVossfppxHg</code> was not found on this server.  <ins>That’s all we know.</ins>

Please fix.

Thanks.

**Comment by sereinity** [comment]
Looks like a regression from youtube, https://news.ycombinator.com/item?id=39179446.

Also your link also lead to a 404. Maybe the behavior is different when we are logged in.

**Comment by unixfox** [comment]
It's back. That was a temporary issue on youtube side.
