### ISSUE TITLE
Question: RSS and account creation

### ISSUE THREAD

**Issue by lamyergeier** [iv-org/invidious#4426]
Do we need to create account for each instance of invidious to save our preferences or we need to create it only once? 

Since some public instances are down sometimes, which RSS feed URL to use? Is it instance independent?

**Comment by unixfox** [comment]
You can save preferences without an account. It will just be saved into the cookies.

So if you remove the cookies your preferences are lost. Hence why an account is interesting because it's saved on the instance.

**Comment by lamyergeier** [comment]
@unixfox

Since some public instances are down sometimes, which RSS feed URL to use? Is it instance independent?

**Comment by unixfox** [comment]
Indeed it depends on the instance.
