### ISSUE TITLE
Connecting to a server behind Authentik

### ISSUE THREAD

**Issue by mike-lloyd03** [iv-org/invidious#4427]
**Is your feature request related to a problem? Please describe.**
My server is sitting behind [authentik](https://goauthentik.io) (using the proxy provider) to enable a more robust layer of authentication. So when I navigate to my server, I have to authenticate with authentik first before I'm redirected to Invidious. Clipious cannot connect to my server as a result of this configuration. When attempting to add the server, I get an error:

```
FormatException: Unexpected character (at line 4, character 1)
<!DOCTYPE html>
^
```

I'm assuming Clipious is expecting a JSON response from the API but is instead being redirected to authentik and gets an HTML response instead.

**Describe the solution you'd like**
Some method to tell Clipious to expect a redirect to an identity provider before making any requests to the Invidious API

**Describe alternatives you've considered**
I've tried disabling authentik and adding the server. Then re-enbling authentik and using token authentication with invidious. This properly handles the redirect to authentik and allows me to log in to Invidious, but afterwards, no videos will load.

**Comment by syeopite** [comment]
This seems more like an issue that should be resolved on Clipious' side

**Comment by mike-lloyd03** [comment]
I'm sorry I posted this in the wrong tab. Closing.
