### ISSUE TITLE
[Bug] Incoherent video submission date in Portuguese language

### ISSUE THREAD

**Issue by Steven79203** [iv-org/invidious#4434]
**Describe the bug**

When setting the Invidious interface to Português the videos submission date shows incoherent dates on any page (trendings, popular, subscriptions). 

**Steps to Reproduce**

1 . Open the Invidious setting
2 . Set the language to 'Português' (not Português Brasileiro or Português de Portugal) 

**Screenshots**
These are the submission dates for the same video.

Set as Português language. It translates to 'Shared 17 months ago'
![screenshot_14-02-2024_13-51-27](https://github.com/iv-org/invidious/assets/75397801/593d30c0-943f-45bc-a552-9c61cdb03514)

Set as Português Brasileiro. Translates to 'Shared 41 minutes ago'
![screenshot_14-02-2024_14-13-26](https://github.com/iv-org/invidious/assets/75397801/80b2e29b-bbf0-4458-bf57-a6c5b55316ad)

Set as English
![screenshot_14-02-2024_13-52-41](https://github.com/iv-org/invidious/assets/75397801/7d252d1a-2bd0-4975-89fd-ccdc2089eea2)

**Additional Information**
This doesn't affect both _Português de Portugal_ or _Português Brasileiro_ languages.

**Comment by SamantazFox** [comment]
For the record, this is a problem with the translations on Weblate. It's fixed in #4164
