### ISSUE TITLE
[Bug] Error when trying to import playlist from csv file.

### ISSUE THREAD

**Issue by jolo2486** [iv-org/invidious#4435]
**Describe the bug**
After creating an account at https://iv.nboeck.de and clicking 'playlists' and then 'import/export' -> 'Import YouTube playlist (.csv) - browse' and picking a playlist csv file as downloaded from takeout.google.com, I get a page saying "It looks like you found a bug in Invidious!" with the following error:

**Logs**
Title: `Index out of bounds (IndexError)`
Date: `2024-02-16T12:12:49Z`
Route: `/data_control?referer=%2Ffeed%2Fplaylists`
Version: `2024.02.12-5c0b6d8 @ master`
  
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/json/any.cr:237:3 in 'update_data_control'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

I have tried several different mirrors, such as invidious.flokinet.to, and invidious.protokolla.fi, and also refreshing and trying again. I have also tried different playlists. Example of what they look like:
```
Video-id,Timestamp  
AAJB9l-HAZs,2017-11-07T21:27:59+00:00
6EIWRg-6ftQ,2017-11-07T21:31:20+00:00
V49i_LM8B0E,2017-11-07T21:32:15+00:00
bDKmewuwJjQ,2017-11-07T21:34:15+00:00
zcvsyL7GtH4,2017-11-07T21:42:05+00:00
hcRZadc5KpI,2017-11-07T21:43:05+00:00
nddefUNMEys,2017-11-07T22:04:20+00:00
TpnXBhaTERA,2017-11-07T22:21:31+00:00
```

**Additional context**
 - Browser: Firefox 122.0.1 (64-bit), also tried in Chromium Version 121.0.6167.160 (Official Build) snap (64-bit)
 - OS: Ubuntu 22.04

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4069
