### ISSUE TITLE
[Bug] Explicit videos have no watch next videos

### ISSUE THREAD

**Issue by iBicha** [iv-org/invidious#4443]
**Describe the bug**
Explicit videos (age restricted, requires login) do not have`recommendedVideos`.
I guess this is because the video info from `TvHtml5ScreenEmbed`, but we're not getting the related videos from it.

**Steps to Reproduce**
Open `/watch?v=B3eAMGXFw1o` on any instance, notice no related videos.
You can also try `/api/v1/videos/B3eAMGXFw1o` and notice an empty array for `recommendedVideos`.

**Comment by absidue** [comment]
That is expected, as attempting to request the `/next` response for a video from YouTube with that client returns an error, presumably because whichever embed that YouTube has that uses that client, probably never makes that request.

**Comment by iBicha** [comment]
That does make sense. I didn't try to call /next on that client. Good enough for me

**Comment by Daxy7** [comment]
In other cases comments and next feed are disabled such as on this video: `https://yewtu.be/watch?v=xd8xt07oQkc` but is viewable and searchable through addresses that use Google's API  like `https://ytcomment.kmcat.uk/`
