### ISSUE TITLE
[Bug] DASH does not work.

### ISSUE THREAD

**Issue by FreeBornAngel** [iv-org/invidious#4445]
**Describe the bug**

The page loads the thumbnail and then nothing.

**Steps to Reproduce**

Open video

**Screenshots**

![image](https://github.com/iv-org/invidious/assets/18445737/bf60dffa-369c-4360-9c70-64e01e59371b)

**Additional context**

It's been a couple days of this.

 - Browser (if applicable): brave
 - OS (if applicable): linux mint
-->

**Comment by unixfox** [comment]
Instance issue. Closing.
