### ISSUE TITLE
[Enhancement] Allow to pause by tapping on the player screen on touch screen in Windows

### ISSUE THREAD

**Issue by tomasz1986** [iv-org/invidious#4447]
**Is your enhancement request related to a problem? Please describe.**

Among other devices, I use Invidious on a touch screen 8" Windows tablet. The play/pause button is very small, and as such it's difficult to press it with a finger.

**Describe the solution you'd like**

The player would be much easier to navigate with a finger if it was possible to play and pause videos simply by pressing on the screen at any place.

**Describe alternatives you've considered**

YouTube itself brings up its video controls on one screen press, and on the second press it pauses or unpauses the video. Because of this, it's easier to use the official YouTube video player on touch screen Windows devices than Invidious.

**Additional context**

The video controls themselves are very small and difficult to press on touch screen devices.

**Comment by tomasz1986** [comment]
I've just realised that you can actually use a mouse to click on the screen to play and pause videos. However, tapping doesn't work the same way, i.e. only the play/pause button on the bottom bar responds to touches. I didn't realise that before, because I never use this particular device with a mouse.

I've also changed the title to be about Windows only, as I can't verify what actually happens under different OSs.

**Comment by unixfox** [comment]
I don't understand, if you click anywhere on the player box the video pause???

https://github.com/iv-org/invidious/assets/4016501/be7d4e2b-caeb-4aa6-85c5-7956505e103c

**Comment by tomasz1986** [comment]
If you click, yes, but not if you tap with a finger… Of course, you do need a Windows touch screen device to reproduce.

**Comment by unixfox** [comment]
Ha interesting, that's probably a bug in video.js. Our video player.

Could you please try if it works better on the new video.js 8 by testing this PR: https://github.com/iv-org/invidious/pull/4439?

**Comment by tomasz1986** [comment]
No difference, unfortunately. The only thing that I can add is that if the video is already playing, then pressing on the screen does bring up the control bar (both in the current and the new video.js). However, still the only way to interact is to press on the play/pause button directly.

**Comment by unixfox** [comment]
does it works on the demo video.js players: https://videojs.com/?

**Comment by tomasz1986** [comment]
No, it's the exact same behaviour there.

**Comment by unixfox** [comment]
OK then you should create a bug report on video.js repository instead: https://github.com/videojs/video.js/issues

**Comment by tomasz1986** [comment]
Reported at https://github.com/videojs/video.js/issues/8608.
