### ISSUE TITLE
How does Invidious quickly get data from Youtube?

### ISSUE THREAD

**Issue by LeNub64** [iv-org/invidious#4456]
Hello! i was curious as to how Invidious is getting data quickly from youtube, like maybe 1.5 seconds, as when i do it myself, it takes 4. Im trying to work on my own app and was using Invidious as a placeholder, and now im trying to use one i made myself.

if possible, id also like to know how comments and comment reply's are gotten as well.

**Comment by unixfox** [comment]
invidious uses innertube, a non-documented API used by the www.youtube.com, android application.

we are mostly get only what we want, it's structured in JSON not HTML.

everything is readable in the source code: https://github.com/iv-org/invidious/tree/master/src/invidious and the youtube api handler is here: https://github.com/iv-org/invidious/blob/master/src/invidious/yt_backend/youtube_api.cr
