### ISSUE TITLE
[Feature request]  Toggle to hide shorts from feeds

### ISSUE THREAD

**Issue by aut-mn** [iv-org/invidious#4457]
As I'm sure many of you know, YouTube has had a shorts feature for a few years now. They're well.. Short & in portrait mode

I personally enjoy long-form content and _never_ watch shorts. It's a hassle having to click "Already watched" for every short on my subscriptions feed to see the actual long-form content I prefer

That's why I think it'd be nice to have a toggle that hides those shorts from your feed so there's only long-form content on there :)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2585
