### ISSUE TITLE
Invidious freezes on loading videos

### ISSUE THREAD

**Issue by chiaraepoi** [iv-org/invidious#4468]
When I load a video that I never When I open a video that I have never watched invidious remains in a waiting state indefinitely and the only solution is to reload the video itself several times until it works.

Debian GNU/Linux 11 (bullseye)
Invidious: 2024.02.19-e8a36985 @ master
Postgresql: 13.14
Nginx 1.18.0

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our matrix channel or IRC.

Closing as it's a configuration issue on your side.
