### ISSUE TITLE
[Bug] 【Chinese Mainland】The video cannot be played

### ISSUE THREAD

**Issue by zaiyi269** [iv-org/invidious#4471]
Server Region: Hong Kong
Network bandwidth: 1G

All images/comments/apis are normal, only the video playback prompts "The media could not be loaded, either because the server or network failed or because the format is not supported"

How to solve the problem that the video cannot be played normally in Chinese Mainland? We look forward to the engineer's answer

**Comment by syeopite** [comment]
As long as the video isn't also geoblocked in Hong Kong, the video should play when you enable video proxy or DASH within the preferences age

**Comment by unixfox** [comment]
Are you using a public instance? If so which one?

**Comment by zaiyi269** [comment]
> Are you using a public instance? If so which one?

2024.02.19-e8a36985 @ master

**Comment by zaiyi269** [comment]
> As long as the video isn't also geoblocked in Hong Kong, the video should play when you enable video proxy or DASH within the preferences age

config.example.yml   SET

  # -----------------------------
  #  Miscellaneous
  # -----------------------------

  ##
  ## Proxy videos through instance by default.
  ##
  ## Warning: As most users won't change this setting in their
  ## preferences, defaulting  to true will significantly
  ## increase the instance's network usage, so make sure that
  ## your server's connection can handle it.
  ##
  ## Accepted values: true, false
  ## Default: false
  ##
  #local: true

The video cannot be played correctly in Chinese Mainland

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.
