### ISSUE TITLE
[Bug] "Unhandled exception: (DB::ConnectionRefused) when starting Invidious

### ISSUE THREAD

**Issue by TheHelmet22** [iv-org/invidious#4472]
**Describe the bug**
Trying to start Invidious through `./invidious` results in a bunch of garble that I don't really understand and a lot of errors including something to do with not being able to establish a connection to a server.

**Steps to Reproduce**
i. Log into your server and find where your Invidious files are located.
ii. Start Invidious using the `./invidious` command.
iii. The error message will appear.

**Logs**
This is the error message that appears when attempting to run Invidious: 
$ ./invidious
Unhandled exception:  (DB::ConnectionRefused)
  from lib/pg/src/pg/connection.cr:16:9 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:16 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from lib/db/src/db/pool.cr:47:34 in 'initialize'
  from lib/db/src/db/pool.cr:40:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:7 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:155:5 in 'build_database'
  from lib/db/src/db.cr:119:5 in 'open'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from ./invidious in '_start'
  from ???
Caused by: Cannot establish connection (PQ::ConnectionError)
  from lib/pg/src/pq/connection.cr:38:7 in 'initialize'
  from lib/pg/src/pq/connection.cr:19:5 in 'new'
  from lib/pg/src/pg/connection.cr:13:23 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:16 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from lib/db/src/db/pool.cr:47:34 in 'initialize'
  from lib/db/src/db/pool.cr:40:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:7 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:155:5 in 'build_database'
  from lib/db/src/db.cr:119:5 in 'open'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from ./invidious in '_start'
  from ???
Caused by: Error connecting to 'localhost:6968': Connection refused (Socket::ConnectError)
  from /usr/share/crystal/src/socket/addrinfo.cr:67:17 in 'initialize'
  from src/invidious/helpers/crystal_class_overrides.cr:6:3 in 'initialize'
  from src/invidious/helpers/crystal_class_overrides.cr:6:3 in 'new'
  from lib/pg/src/pq/connection.cr:30:17 in 'initialize'
  from lib/pg/src/pq/connection.cr:19:5 in 'new'
  from lib/pg/src/pg/connection.cr:13:23 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:16 in '->'
  from lib/db/src/db/pool.cr:214:7 in 'build_resource'
  from lib/db/src/db/pool.cr:47:34 in 'initialize'
  from lib/db/src/db/pool.cr:40:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:7 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:155:5 in 'build_database'
  from lib/db/src/db.cr:119:5 in 'open'
  from src/invidious.cr:63:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from ./invidious in '_start'
  from ???
$ sh: turning off NDELAY mode
^C

**Screenshots**
Not applicable.

**Additional context**
OS: Windows 11 Pro 23H2 22631.2861 running Ubuntu 22.04 Server through WSL

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.
