### ISSUE TITLE
[Bug]  (DB::PoolRetryAttemptsExceeded)

### ISSUE THREAD

**Issue by Mbuni21** [iv-org/invidious#4474]
**Describe the bug**
I cannot log on, no matter what instance...

**Steps to Reproduce**

**Logs**

**Screenshots**

![image](https://github.com/iv-org/invidious/assets/133012667/a3f7201e-cd2d-416b-9145-f274acca5656)

**Additional context**

**Comment by unixfox** [comment]
Hello, this sounds like an issue with a specific instance.
Please try to use another instance: https://instances.invidious.io/

The invidious maintainers do not manage the public instances. Please report the issues to the maintainer of the public instance.
