### ISSUE TITLE
[Feature request] Add startup checks for correct postgres version

### ISSUE THREAD

**Issue by Sommerwiesel** [iv-org/invidious#4479]
Following the problems (currently at least one) instance owner has with running invidious with an older version of postgres, there should be a startup check in invidious, checking for the correct version and preventing it from starting, with a clear error in the log.

**Comment by unixfox** [comment]
Invidious is compatible with all recent postgresql versions.

In the past there was an issue with postgresql 14 but I think this one is fixed when we removed lsquic from the code: https://github.com/iv-org/invidious/issues/2938
