### ISSUE TITLE
[Enhancement] The hmac_key when using docker-compose file should be populated automatically

### ISSUE THREAD

**Issue by HolgiB** [iv-org/invidious#4482]
**Is your enhancement request related to a problem? Please describe.**
The hmac_key inside either the docker-compose file or the generic config used to build the invidious Container image.

**Describe the solution you'd like**
The most straight forward approach might be using the Dockerfile itself plus pwgen and some sed replace magic to generated a unique hmac_key for every Invidious instance generated on a Docker host.

**Comment by unixfox** [comment]
That's not possible, the config.yml is not persistent in a docker environment.

**Comment by HolgiB** [comment]
Ok, but persisting the config subdirectory in a volume is not a considerable option ?
So I guess the hmac_key from the Docker Compose file is injected to the Invidious container as environment variable ?
One thing that does not go into my head right now: If I build an invidious image localy with preconfigured hmac_key, the container spawned from this image would have a constant hmac_key, win win ?

**Comment by unixfox** [comment]
Based on the fact that inserting a hmac_key parameter is trivial, just inserting it into the env `INVIDIOUS_CONFIG` and you are done. I don't think we are going to change anything.

**Comment by HolgiB** [comment]
Valid point. Thanks for the quick response.
