### ISSUE TITLE
[Bug] The Direct Link generated by the share button does not route correctly

### ISSUE THREAD

**Issue by syildizz** [iv-org/invidious#4487]
**Describe the bug**
The URL that is displayed on the "Direct Link:" textbox when clicking the share button of the video does not link to the video. Instead, when following the link the server returns a HTTP 302 status response code and redirects to the "https://yewtu.be/" URL.

**Steps to Reproduce**
1. Go to https://yewtu.be/watch?v=C0DPdy98e4c&t=3
2. Click on share button
3. Click on copy button under "Direct Link:"
4. Go to that URL

**Logs**
```
HTTP/2 302 
date: Sat, 16 Mar 2024 14:39:20 GMT
content-type: text/html
content-length: 20
content-encoding: gzip
x-frame-options: sameorigin
location: /
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-robots-tag: 'noindex, nofollow, nosnippet, noarchive'
alt-svc: h2="ingress.yewtu.be:443"; ma=86400
X-Firefox-Spdy: h2
```

**Screenshots**
![share_button_page](https://github.com/yewtudotbe/invidious-custom/assets/118059676/591ed9bb-f7d2-4107-bb0b-b103763f00ec)

**Additional context**

|||
-------------------------|--------------------------------------------------|
The URL generated by the share button: |  https://yewtu.be/C0DPdy98e4c?t=3 |
The URL that actually redirects to the video at the time stamp: | https://yewtu.be/watch?v=C0DPdy98e4c&t=3

This could be fixed by either:
- Changing the generated URL to the working one.
- Routing the generated URL correctly.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3933
