### ISSUE TITLE
Compiling [Bug] 

### ISSUE THREAD

**Issue by blade10101** [iv-org/invidious#4490]
.88     Unhandled exception: Hostname lookup for registry.npmjs.org failed: Try again (Socket::Addrinfo::Error)

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.
