### ISSUE TITLE
[Feature request]  Detailed metadata about a video stream.

### ISSUE THREAD

**Issue by Guvanchhojamov** [iv-org/invidious#4493]
Hi, 
It would be better if we add detailed metadata for video.
Like this: 
[Video Streams detailed metadata API](https://developers.google.com/youtube/v3/docs/videos#fileDetails.videoStreams[]) 
Often we have to use, aspectRatio or rotation information about video.  But in invidious, we don't have this information. 
Thanks!

**Comment by absidue** [comment]
Invidious gets it's data in the same way that YouTube's website does and YouTube's website doesn't have the information, so Invidious has no way to get it. If you require that information, you should probably change to using the API that you linked instead of using Invidious.
