### ISSUE TITLE
[Question]  - Not parsing email address in registration

### ISSUE THREAD

**Issue by chiaraepoi** [iv-org/invidious#4495]
**Describe the bug**
During a normal process of checking the users registered on my instance (https://i.redsnake.io/) I found that many users are registered without a complete email address (i.e. user instead of [user@domain.tld](mailto:user@domain.tld)). It seems that the email address is not parsed allowing anyone to register

**Steps to Reproduce**
1 . Try to register using a broken email address

**Comment by unixfox** [comment]
It's not required to use a provide an email address that's it.
