### ISSUE TITLE
[Bug] The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)

### ISSUE THREAD

**Issue by an00bo** [iv-org/invidious#4498]
### The Invidious team is aware of the issue. Please only comment if you have new things to add to the subject.

This post will be updated with relevant infos as needed.

----

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-03-28T20:32:59Z`
Route: `/watch?v=SoHyj8i8Ywo&list=PLfGibfZATlGonwDMXhmHWWchf4_QN5chy&index=1`
Version: `2024.03.28-3749a34 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from /usr/lib/crystal/core/hash.cr:1080:49 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:112:10 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by UltraBlackLinux** [comment]
Can reproduce, just pulled the latest docker build too. It's been happening for the last maybe three days and it's been driving me crazy. It's not a big deal since you can just refresh the page and it'll usually load but it's very annoying to see it popping up regularly

**Comment by cutiness** [comment]
I can confirm that this happens regularly on my private instance as well.

**Comment by tusharhero** [comment]
I can confirm that it happens in multiple instances: https://invidious.nerdvpn.de/ https://invidious.lunar.icu/

**Comment by d4g** [comment]
Same for me.

**Comment by Delikt** [comment]
same for me with version  2024.03.08-99a5e9cb @ master

**Comment by JacenBoy** [comment]
I've also been getting this fairly frequently

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-03-28T23:17:41Z`
Route: `/watch?v=jcs1YRz0qgM&list=PL28_eRFIuaoKYPeXwrPTzyjXftBC2G-Ui&index=54`
Version: `2024.02.19-e8a36985 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from src/invidious/videos/parser.cr:157:9 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:111:5 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:391:3 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video'
  from src/invidious/videos.cr:361:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from src/invidious/routing.cr:159:19 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:157:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:146:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:521:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:451:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Comment by net00-1** [comment]
I'm also seeing this in my private instance, running the latest version. Refreshing the page fixes it, then videos play as expected. 

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-03-28T23:36:08Z`
Route: `/watch?v=n1xJs-FwffQ`
Version: `2024.03.08-99a5e9c @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from /usr/share/crystal/src/hash.cr:1080:49 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:112:10 in 'extract_video_info:video_id'
  from /usr/share/crystal/src/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:371:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by lyczak** [comment]
I'm also seeing the same issue with the latest docker build.

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-03-29T00:00:47Z`
Route: `/watch?v=uH7e9wumYWg`
Version: `2024.03.08-99a5e9c @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from /usr/lib/crystal/core/hash.cr:1080:49 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:112:10 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment]
As noted in the matrix channel this is probably caused by the fact that YouTube changed their integrity check again which Invidious currently does not meet.

**Comment by monkeyboy537** [comment]
My private instance also has this problem

**Comment by xprnio** [comment]
For me it seems to happen quite randomly on various videos. Sometimes a single page refresh solves it, sometimes it requires multiple page refreshes, but so far it has eventually loaded the video properly.

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-03-29T00:55:38Z`
Route: `/watch?v=HquFpnjkenE`
Version: `2024.02.19-e8a36985 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from src/invidious/videos/parser.cr:157:9 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:111:5 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:391:3 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video'
  from src/invidious/videos.cr:361:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from src/invidious/routing.cr:159:19 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:157:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:146:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:517:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:470:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment]
Please do not create duplicated comments.

**Comment by tl87** [comment]
👀

**Comment by UltraBlackLinux** [comment]
> changing your server's public ip

I live in germany meaning my public IP changes daily. If this whole IP thing is related to the "shadow banning" of clients, then I think that solution does just not apply. As I said previously, you can just reload the page and it will load the video after 1-5 tries.

**Comment by stonerl** [comment]
I have to second @UltraBlackLinux' assessment. Reloading solved that, so the solution to changing the IP and setting up rotating IPs doesn't hold water.

**Comment by krim404** [comment]
If you use an older modified youtube app, then you see the same result - youtube replaces the video with a fake video displaying that this app is not supported anymore. 

This started the same day as invidious started this issue. So i assume, that this has something to do with it

**Comment by sonnysighedup** [comment]
On my own instance, I've noticed that on my laptop sometimes reloading the video doesn't work. 

Curiously, the problem **doesn't** extend to watching Invidious on mobile devices. On the same instance, trying to watch the same videos, I have no problem on either of my mobile devices - one an Android, the other running e/OS.

**Comment by xprnio** [comment]
@sonnysighedup that's weird as I do run into the same problem on my mobile device, although I am using iOS

**Comment by unixfox** [comment]
This is not related to the device that you are using. It affects the invidious software as a whole regardless of the device.

**Comment by sonnysighedup** [comment]
@unifox - does the "...(Android client)..." in the error title have any significance?

**Comment by WizardOfWor1969** [comment]
I switched my VPN to go through Mexico and it worked for a couple of hours, then broke again. Not sure if that is helpful.

**Comment by unixfox** [comment]
> @unifox - does the "...(Android client)..." in the error title have any significance?

This is just related to the fact that invidious emulate the android app for YouTube in order to go the data from YouTube.

**Comment by tl87** [comment]
If it is not a change, that was added by the invidious team, then this could also just be "the video service provider", that is doing something, to try and block requests from invidious instances..

**Comment by ashley0143** [comment]
it seems like its on every instance now

**Comment by ashley0143** [comment]
we cant use the android client anymore without gms apperently

**Comment by gptlang** [comment]
Yup. Was just refreshing a few thousand times but within the past few minutes it stopped working entirely. 

> Android client

Is there anything preventing us from using the IOS or web client instead?

**Comment by jimmygle** [comment]
Looks like YouTube is potentially implementing some countermeasures, or some bug/feature that's been rolling out through their server fleet today. It slowly got worse throughout the day, and now I can't watch any videos.

**Comment by Delikt** [comment]
FYI - If this affects all unlicensed Third Party Frontends/Clients . NewPipe on Android is still functional and works.

**Comment by accessiblepixel** [comment]
It seems like a change was implemented youtube side, and over the past couple of days they've been deploying it slowly to ramp up. It went from 1-5 refreshes and it'd get it, to now every instance I've tried has the issue (my own, and numerous that are listed on the redirector).

It looks like it's sending back the wrong video like they were doing last year before the integrity check was added to invidious ( #3230 ) which is when this error message was added to detect if it started happening again.

As others have said yt-dlp still can download videos, but it also looks like it's having issues with it's use of the android client too... for eg.
```
[youtube] eUIMOTrMh-g: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] eUIMOTrMh-g: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
```

**Comment by krim404** [comment]
As far as i can see, YoutTube enforced the verification of PoToken. In the past it would deliver videos even when the token was empty.

**Comment by UltraBlackLinux** [comment]
>  NewPipe on Android is still functional and works.

I'm surprised that newpipe and invidious even use diverging systems to pull the videos. In my experience newpipe was always blazingly fast and pretty much never had any issues. Is there any reason why invidious uses a different system at all? It does seem to be a tad bit slower overall

**Comment by Rikj000** [comment]
> we cant use the android client anymore without gms apperently

If that's true,   
perhaps [MicroG](https://microg.org/) could be of use,   
as a FOSS privacy respecting implementation of GMS.

However,   
I doubt that this is the case.   
Since I did not give [Tubular](https://github.com/polymorphicshade/Tubular) (the NewPipe fork I use) access to MicroG's GMS implementation on my device,   
and it still works correctly.

**Comment by unixfox** [comment]
> >  NewPipe on Android is still functional and works.
> 
> I'm surprised that newpipe and invidious even use diverging systems to pull the videos. In my experience newpipe was always blazingly fast and pretty much never had any issues. Is there any reason why invidious uses a different system at all? It does seem to be a tad bit slower overall

Please don't go offtopic please.

Software have different implementation which may introduce some differences.

Also invidious is a centralized service that serve multiple users at the same time. Whereas newpipe is an android app for a single user. So the performance will obviously be different.

**Comment by hed47** [comment]
how do I fix it?

**Comment by Trit34** [comment]
yt-dlp seems to have some problems, too, and shows a tentative to redirect to https://www.youtube.com/watch?v=aQvGIIdgFDM.

**Comment by TheodorSmall** [comment]
I don't know if this is related. Reloading the onion service of vid.puffyan.us gets me the already known error, but one out of maybe 10-20 reloads, I keep getting the default error message without any further information.

URL: http://grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad.onion/watch?v=WRmKC2SaP5o
Error: "Can't load the video on this Invidious instance. YouTube is currently trying to block Invidious instances. [Click here for more info about the issue.](https://github.com/iv-org/invidious/issues/3822) \n After which you should try to", followed by the buttons "refresh", "switch invidious instance" and "go to youtube".

This only occurs rarely, usually the "normal" bug as described in this issue is displayed.

**Comment by Muhommetmratkakajanow** [comment]
сб, 30 мар. 2024 г., 16:35 TheodorSmall ***@***.***>:

**Comment by diogo098** [comment]
Idk but im playing fine the videos on FreeTube App using invidious back end, but not in the browser

**Comment by TheodorSmall** [comment]
> Idk but im playing fine the videos on FreeTube App using invidious back end, but not in the browser

@diogo098 Which instance are you using, and does FreeTube App work with any instance or just that one?

**Comment by Jvernon0202706** [comment]
i can't use yewtu.be

**Comment by sunlightspectre** [comment]
Although different frontends absolutely use different methods of authentication, both Piped and Invidious are completely inaccessible at this time. Putting aside how I feel on this matter, it appears that youtube is going to take a twitter approach on authentication integrity. That should be factored into any efforts - permanent, or temporary - to evade the problem.

For now... Pretty sure what I thought was a separate issue [here](https://github.com/yewtudotbe/invidious-custom/issues/96#issue-2177340972) was just being hit with this issue earlier than most, as I continued to get sporadic instances of the errors until today, at which point _all_ instances of invidious using _any_ combinations of settings refuse access.

**Comment by DustyAttemborough** [comment]
> Although different frontends absolutely use different methods of authentication, both Piped and Invidious are completely inaccessible at this time. Putting aside how I feel on this matter, it appears that youtube is going to take a twitter approach on authentication integrity. That should be factored into any efforts - permanent, or temporary - to evade the problem.

It may be worth noting that I'm able to access Piped without issues.

**Comment by Jerroder** [comment]
> it appears that youtube is going to take a twitter approach on authentication integrity. That should be factored into any efforts - permanent, or temporary - to evade the problem.

FWIW nitter is trying to implement "guest accounts" where you create an account every x hours in order to get a pool of account and use one of them to get the feed.

**Comment by Seeings** [comment]
> > it appears that youtube is going to take a twitter approach on authentication integrity. That should be factored into any efforts - permanent, or temporary - to evade the problem.
> 
> FWIW nitter is trying to implement "guest accounts" where you create an account every x hours in order to get a pool of account and use one of them to get the feed.

Unfortunately nitter is pretty much dead now, since twitter fixed that workaround

**Comment by sunlightspectre** [comment]
> It may be worth noting that I'm able to access Piped without issues.

Hopefully it stays that way, but if you do lose access, any discrepancies between what we've got so far'd be great to have on hand.  
I don't want to clutter the thread, but something to keep an eye on if you can.

**Comment by DustyAttemborough** [comment]
> > It may be worth noting that I'm able to access Piped without issues.
> 
> Hopefully it stays that way, but if you do lose access, any discrepancies between what we've got so far'd be great to have on hand. I don't want to clutter the thread, but something to keep an eye on if you can.

Sadly, my technical knowledge isn't likely up to snuff, so my contribution won't likely be useful; that said, I can say that livestreams seem to be an issue, as do _some_ videos.  If it'd be helpful, I could send links to what works for me and what does not.

**Comment by RubberDuck01** [comment]
I too experience this error. These are the instances I use daily (I switch between them every so often):

![image](https://github.com/iv-org/invidious/assets/72613604/6524ddb2-a671-410f-b00f-f8c100a53902)

Yesterday, every video I attempted to watch had 50/50 chance of throwing the error. Today, I couldn't watch a single video on Invidious.

**Comment by gripped** [comment]
Using mpv to play the invidious links still works for me.
I've long had a tampermonkey script which changes a couple of the links on the video page from https:// to mpv:// and then a helper script in firefox to turn the link back to https:// and open it with mpv.
I just commented the check for the correct video in/src/invidious/videos/parser.cr
So that I get access to the links rather than the error page. And they still work. One is direct to youtube so no surprise there. But the other is through my invidious instance and I was surprised when that still worked.

Hadn't seen this mentioned.

**Comment by techmetx11** [comment]
I didn't know this was an issue, I made a workaround PR that makes invidious use the HTML5 client if the Android client fails #4549

**Comment by CommandLord** [comment]
> It may be worth noting that I'm able to access Piped without issues.

Now it dose not. I can't get any video to load on piped. Here is their issue, in case it helps: https://github.com/TeamPiped/Piped/issues/2915

**Comment by AceDenghar** [comment]
It's wasn't working for my instance too since 2 days but for now it's working again...

**Comment by ThaDaVos** [comment]
Quick question, anyone else having issues playing videos now on certain older devices after the fix? 
My Nvidia Shield Tablet, using Clipious, doesn't play the videos any longer, just stays black

**Comment by ashley0143** [comment]
> Quick question, anyone else having issues playing videos now on certain older devices after the fix? 
> My Nvidia Shield Tablet, using Clipious on Android 7, doesn't play the videos any longer, just stays black

tried on a Lenovo k5 that runs android 7 it works on my device

**Comment by doc75** [comment]
> Quick question, anyone else having issues playing videos now on certain older devices after the fix? My Nvidia Shield Tablet, using Clipious on Android 7, doesn't play the videos any longer, just stays black

With a docker based install, I remove the healthcheck which is failing every ~10 minutes. Otherwise it is working fine again with the latest version published yesterday.

**Comment by ThaDaVos** [comment]
It's working on my Phone which is Android 13, but for some reason my Tablet with Android 7 does, I think the webclient works, but Clipious does not after the fix made for this

**Comment by a7maadf** [comment]
Hi, I'm trying to update my instance through `sudo docker-compose pull` but for some reason it keeps saying the the pulled image is the latest available version. I would really appreciate it if someone could help me updating it. 

Thanks

**Comment by Ex0danify** [comment]
> Hi, I'm trying to update my instance through `sudo docker-compose pull` but for some reason it keeps saying the the pulled image is the latest available version. I would really appreciate it if someone could help me updating it.
> 
> Thanks

Pull latest master Form repo via git pull. Then rebuild the docker image with docker-compose build. After that you should have the latest version, fire it up as usual with docker-compose up.

**Comment by a7maadf** [comment]
Thank you so much!

**Comment by shrapnelnet** [comment]
`sudo docker compose pull` seems to be working for me as of now without extra build steps

**Comment by unixfox** [comment]
Locking the issue for now because some people are getting offtopic and the issue has been solved in the latest version.
