### ISSUE TITLE
Refresh subscriptions without full restart? (Docker)

### ISSUE THREAD

**Issue by McMac** [iv-org/invidious#4502]
Is there a way to run some part of invidious explicitly to refresh the subscriptions without impacting playback? Currently I am restarting the docker image but rather do some cron job to manually trigger the refresh part?! Is that possible?
Still don't understand why inv stops after certain times and seemingly were using the wrong search terms to find the right issue tickets for more details.

Thanks for any enlightenment! :)

**Comment by unixfox** [comment]
You need to have pubsub enabled.

**Comment by McMac** [comment]
Thank you for **not reading my question** @unixfox! I know about the restarts!

My question was, can I **restart** part of Invidious **while** I am **watching a video**!? 
Will hardly work if I am restarting the entire docker container.

Why are the responses here always so rude?
