### ISSUE TITLE
[Bug] "The video returned by YouTube isn't the requested one." is still returned after applying patch.

### ISSUE THREAD

**Issue by sahinakkaya** [iv-org/invidious#4558]
I am getting exact same error as #4498. I've applied the patch by pulling the latest changes but the problem is not fixed. Do I need to do anything else? Here is what I've done:

```
cd invidious
git pull
docker compose down
docker compose up -d
```

**Comment by sahinakkaya** [comment]
```
docker pull quay.io/invidious/invidious:latest
docker compose down
docker compose up -d
```

**Comment by unixfox** [comment]
Please follow the official documentation: https://docs.invidious.io/installation/#docker-compose-method-production

**Comment by sahinakkaya** [comment]
@unixfox yeah I also just answered my own question :D Thanks!
