### ISSUE TITLE
[Bug] Comments won't load on all videos

### ISSUE THREAD

**Issue by DestinyofYeet** [iv-org/invidious#4566]
**Describe the bug**

Comments won't load on some videos

**Steps to Reproduce**

1. Open video with video ID q0zCZpyv8HI
2. Scroll down to the comments
3. Be greeted by an infinite loading circle instead of the comment section

**Logs**

The GET request to `api/v1/comments/VIDEOID?format=html&hl=en-US&thin_mode=false` fails with a 500 error code.

```json
{
	"error": "Missing hash key: \"commentRenderer\"",
	"errorBacktrace": "Missing hash key: \"commentRenderer\" (KeyError)\n  from /usr/share/crystal/src/hash.cr:1191:11 in '[]'\n  from /usr/share/crystal/src/json/any.cr:115:7 in '[]'\n  from src/invidious/comments/youtube.cr:137:34 in 'parse_youtube'\n  from src/invidious/comments/youtube.cr:60:3 in 'parse_youtube'\n  from src/invidious/comments/youtube.cr:16:12 in 'fetch_youtube'\n  from src/invidious/routes/api/v1/videos.cr:325:20 in 'comments'\n  from src/invidious/routing.cr:229:5 in '->'\n  from lib/kemal/src/kemal/route.cr:12:26 in '->'\n  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:157:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:146:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:17:35 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'\n  from /usr/share/crystal/src/http/server.cr:521:5 in 'handle_client'\n  from /usr/share/crystal/src/http/server.cr:451:5 in '->'\n  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'\n  from /usr/share/crystal/src/fiber.cr:98:34 in '->'\n  from ???\n"
}
```

**Screenshots**

**Additional context**

Browser: Firefox 124.0
OS: Arch linux

**Comment by DestinyofYeet** [comment]
Refreshing the page with Ctrl+F5 did bring back the comments, so I'm just gonna close this issue.

**Comment by nyanpasu64** [comment]
The bug still appears on various videos (and sometimes the 500 error doesn't even go away with multiple full refreshes), I don't think it's "fixed".

**Comment by YeapGuy** [comment]
It's still broken. My healthcheck keeps failing because of this.

**Comment by DestinyofYeet** [comment]
Indeed. I didn't investigate it further yesterday but I can confirm this is the case.

**Comment by ashley0143** [comment]
youtube is a/b testing a new comments response iirc

**Comment by limbuscode** [comment]
Yes, the response is different now, the comments are in another property "frameworkUpdates.entityBatchUpdate.mutations".

I wonder if it is a permanent update...

**Comment by ashley0143** [comment]
it seems like its on all videos now

**Comment by limbuscode** [comment]
> it seems like its on all videos now

It seems you are right, I think the author of the issue should update its title to "[Bug] Comments won't load on **ALL videos**".

@DestinyofYeet

**Comment by RundownRhino** [comment]
YCD seems to already have a fix for it: https://github.com/egbertbouman/youtube-comment-downloader/commit/9850cf47dad950ad241919284117fd2e93672c88
so this can be ported to invidious.

**Comment by limbuscode** [comment]
Is there any public instance with this fixed?

**Comment by limbuscode** [comment]
I've noted that sometimes (bare rarely) the instances output the comments correctly but most of the time it doesn't, it seems not a permanent update to the response just yet.

**Comment by RundownRhino** [comment]
That's worrying if so, because if this is still in A/B testing, then moving to the new format will make it fail to parse the responses whenever youtube sends them in the old format.

**Comment by ChunkyProgrammer** [comment]
My PR doesnt remove parsing of the old format, it just adds code for parsing the new format 🙂 @limbuscode @RundownRhino

**Comment by Yetangitu** [comment]
FYI: Just built current master with @ChunkyProgrammer 's PR and tested with a number of video's, comments loaded on every attempt.

**Comment by roryyamm** [comment]
I eagerly await a sense of closure for the pull request and this issue.

**Comment by incrediblyimpressiveusername** [comment]
> Comments won't load on some videos

Not on some videos, on ANY video, on any instance, on any browser, on any device, and for weeks and weeks already

**Comment by wanniethecharacter** [comment]
> > Comments won't load on some videos
> 
> Not on some videos, on ANY video, on any instance, on any browser, on any device, and for weeks and weeks already

WHEN IS THIS GONNA BE FIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXED!??!!?!?!?!?!?!?!??!?!?!??
