### ISSUE TITLE
[Bug] INstall Phase 4 Error

### ISSUE THREAD

**Issue by scooter2214** [iv-org/invidious#4567]
If i want to install INvidious this shows up .. 

▣▣▣▣ Phase 4 of 4: Setup Invidious
Updating config                                                         [ OK! ]
Setting folder permissions                                              [ OK! ]
Running shards install                                                  [ OK! ]
Running crystal build                                                   [----<]
[ERROR]
[ERROR] Something went wrong with the previous command. Exiting.
Installing Invidious Service                                            [==>--]
Ubuntu 23.04 invidious pts/1

**Comment by unixfox** [comment]
You are probably installing invidious through unsupported means.

Please follow the official documentation: https://docs.invidious.io/installation/
