### ISSUE TITLE
[Feature request] New way to watch content you just want to listen to instead of watching and listening

### ISSUE THREAD

**Issue by marcelinhoshow** [iv-org/invidious#4568]
Allowing you to just listen to music videos or playlists without playing the video, saving internet bandwidth that would otherwise be used unnecessarily.

![image](https://github.com/iv-org/invidious/assets/44094119/38d75a9a-f56e-488e-b45c-f48c6ef18f4c)

Something that is assimilated, while playing music, or content that it is desirable to just listen to the audio

**Comment by syeopite** [comment]
This already exist! If you click on the headphone icon next to the title of a video, or enable "Listen by default" in the settings then only the audio will play
