### ISSUE TITLE
add more description when signing in with google account

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#457]
IMO `login with google` should show more information regarding how it works. It should clearly state that user's password is sent to invidious and the server can misuse it and that the user should decide whether he/she trust the server admin or not.

**Comment by omarroth** [comment]
As mentioned in #227, an `/about` page was suggested that would be an excellent place for something like this, and providing a link on the login page. A common question I've been asked is why Invidious triggers a Google alert, so providing an answer on said page and any other info would be quite useful I think.
