### ISSUE TITLE
Add inv.benrogo.net to the list of public Invidious instances

### ISSUE THREAD

**Issue by BenRogozinski** [iv-org/invidious#4574]
**Describe the solution you'd like**
I host an Invidious instance that has a high bandwidth capacity and I would it to be added to the list of public instances

**Additional context**
My server has very high availability with a proxmox HA setup, it's locally managed with battery backups on everything and proxied through cloudflare for security

**Comment by syeopite** [comment]
Please open an issue here with the template 

https://github.com/iv-org/documentation/issues/new/choose
