### ISSUE TITLE
URL download links [Question] 

### ISSUE THREAD

**Issue by dejalavidavolar** [iv-org/invidious#4575]
Hi! I'm trying to "embed" invidious videos trought HTML, because I don't want to include JS on my website, but video download links always changes.

For example: 

```
<video width="640" height="360" controls>
        <source src="https://inv.nadeko.net/videoplayback?expire=1712621347&ei=wzIUZuHBGejd1sQP88-BMA&ip=186.105.185.25&id=o-APN5Ys2owjXXQ_yejPiGJaJ-d09Kuf9PIWNaT_rd90mD&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=4S&mm=31%2C29&mn=sn-uxgg5-njaes%2Csn-uxgg5-njar&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=19&initcwndbps=1096250&spc=UWF9f43wTQzQhhuB9yyXu9_nirOR7HHbYQ0p7uE&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=8.777&lmt=1712427287173821&mt=1712599267&fvip=3&fexp=51141542&c=ANDROID&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAKUVWiZcwAChS1TBGGNSgEffzP52rYfCBv_oND5tDbg3AiBxwr6YPT-vBX553KLYCQ6Ca9UPNsES6rfM_R4zXn-34A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRgIhAOeuTVdgocPl5GoMABlTYMjJfMz_x5Lm8zPUAfCFpFqBAiEAoSbBt236AiMsmsUS8ZlQosEDGni_XT9avQ7Xa1Sa8E8%3D&host=rr1---sn-uxgg5-njaes.googlevideo.com&title=Extreme%20Side%20Eye-vnr_sfN4M_M.mp4" type="video/mp4">
    </video>
```
**It would be possible to convert automatically video download links into a fixed one?** 

For example, with previous video:

```
<video width="640" height="360" controls>
        <source src="https://inv.nadeko.net/watch?v=vnr_sfN4M_M-720.mp4" type="video/mp4">
    </video>
```

Or something like that. 

Best Greetings!

**Comment by unixfox** [comment]
Yes use the API of invidious for giving the correct videoplayback URL through your back end.

https://docs.invidious.io/api/

**Comment by dejalavidavolar** [comment]
HI! Does that mean I have to have access to the instance administration? Because, I don't have it. I was reading API docs, but it is difficult for me to understand it.

**Comment by unixfox** [comment]
No just the API. The instance need to allow access to the API though.

**Comment by dejalavidavolar** [comment]
Thanks @unixfox !!

**Comment by SamantazFox** [comment]
> Hi! I'm trying to "embed" invidious videos trought HTML, because I don't want to include JS on my website, but video download links always changes.

For your information, these links are only valid for 6 hours (thank google for that).
As unixfox said, you'll need to use the API to get a valid link each time.

Alternatively, you can embed invidious directly:
```
<iframe src='https://inv.nadeko.net/embed/your_video_id' frameborder='0' allowfullscreen></iframe>
```
