### ISSUE TITLE
video player doesn't work well for small displays

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#458]
I have a phone that has `240x<redacted>` screen and the video player's controls overflows from the screen. I have to go right and then click on full screen, viewing without full screen is not that good on that device and I cannot see captions properly when not in full screen mode.

**Comment by omarroth** [comment]
See #310. You should be able to scroll to view player controls. If that's not the case, would you mind providing a screenshot of the player?

**Comment by elypter** [comment]
in addition to that: the title of the video should be displayed in a smaller font if the screen/window is very small.

**Comment by cyaniventer** [comment]
I am able to go full screen and yes the title of the video should be displayed in a smaller font, it takes half of my screen.

Can that player display overflowed buttons on next line instead?

**Comment by omarroth** [comment]
I would probably open oversized elements as a new issue. 

> Can that player display overflowed buttons on next line instead?

I'm unfortunately not familiar enough with Video.js to add something like that and generally I'm wary of making those sorts of changes since it's difficult to make it work properly on multiple devices/screen sizes. PRs are always welcome.

**Comment by tleydxdy** [comment]
on my tor browser (firefox) I can't even scroll to the right
