### ISSUE TITLE
[Bug] invidious.io down, all invidious instances return error

### ISSUE THREAD

**Issue by incrediblyimpressiveusername** [iv-org/invidious#4594]
**Describe the bug**
invidious.io is down, and according to isitdownrightnow.com has been down for everyone for almost 10 hours now.
The instances themselves aren't down but all give the error message `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`, except for invidious.perennialte.ch which has a different error message: `(500) The server encountered an unexpected condition that prevented it from fulfilling the request`

**Steps to Reproduce**
Try to use invidious normally.

**Additional context**
Verified on Firefox, Librewolf, Brave, Mullvad, Falkon, Badwolf and Tor.
Verified on Windows 10, Windows 11, Ubuntu and Devuan

**Comment by incrediblyimpressiveusername** [comment]
Please do not remove have of the bug report.

**Comment by unixfox** [comment]
https://social.tchncs.de/@invidious/112311313404497392

**Comment by unixfox** [comment]
https://social.tchncs.de/@invidious/112311313404497392

And for the other half of the bug... https://github.com/iv-org/invidious/issues/4584
