### ISSUE TITLE
[Bug] The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException) 

### ISSUE THREAD

**Issue by 101112010625** [iv-org/invidious#4617]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

タイトル: 「YouTube から返されたビデオは、要求されたものではありません。」 (Android クライアント) (VideoNotAvailableException)` 日付: `2024-04-26T03:29:00Z` ルート: `/watch?v=RyBD5FLDnyg` バージョン: `2024.04.10-b673695 @ master`  <詳細> <summary>バックトレース</summary> <p>     「」 YouTube から返されたビデオはリクエストされたものではありません。 (Android クライアント) (VideoNotAvailableException)   「try_fetch_streaming_data」の /usr/share/crystal/src/hash.cr:1080:49 から   「extract_video_info:video_id」の src/invidious/videos/parser.cr:112:10 から   「fetch_video」の /usr/share/crystal/src/hash.cr:1185:13 から   「get_video:region」の src/invidious/videos.cr:379:13 から   「ハンドル」の src/invidious/routes/watch.cr:55:15 から   lib/kemal/src/kemal/route.cr:13:9 から '->'   「呼び出し」の src/invidious/helpers/handlers.cr:30:37 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call_next」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の lib/kemal/src/kemal/filter_handler.cr:21:7 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call_next」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の src/invidious/helpers/handlers.cr:94:12 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call_next」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の src/ext/kemal_static_file_handler.cr:106:14 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   「call」の /usr/share/crystal/src/http/server/handler.cr:30:7 から   /usr/share/crystal/src/http/server/request_processor.cr:51:11 から「handle_client」   「実行」の /usr/share/crystal/src/fiber.cr:146:11 から   から ？？？ 「」 </p> </詳細>

**Comment by PhilPhonic** [comment]
dupes #4584
