### ISSUE TITLE
javascript:void constantly displayed

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#465]
javascript:void is often kept constantly displayed at the bottom left of the browser like if something was still loading.
I noticed it in dash quality but it might also happens when using other qualities.

The problem is that it stays on the screen even in fullscreen (in front of the video).

**Comment by omarroth** [comment]
Mind providing which browser you're using?

**Comment by TheFrenchGhosty** [comment]
Icecat, I don't think it's related to the browser since I only have that problem and invidious.

It's not always though

**Comment by leonklingele** [comment]
I noticed this as well. `href="javascript:void(0);"` should not be used on `a`-tags, prefer to use `button` elements instead.

**Comment by 2secslater** [comment]
I get something similar, but it's "Transferring data from <instance domain>".

**Comment by TheFrenchGhosty** [comment]
I finally found where this problem come from.

When clicking "Show replies" it will display "javascript:void" but if it fail (with "Pulling comments failed" in the console) it will still be displayed after.

**Comment by TheFrenchGhosty** [comment]
This problem is actually not related to "Show replies" it sometimes happen without interacting with the comments.

**Comment by TheFrenchGhosty** [comment]
Seems to be solved since the JS refactoring #3084
