### ISSUE TITLE
[Bug] Unable to subscribe to any channels 

### ISSUE THREAD

**Issue by nansan1** [iv-org/invidious#4657]
**Describe the bug**
I am unable to subscribe to any channels via Invidious at this time. I was able to subscribe to one account before, but I am unable to recreate it for some reason. I will click the button and then it will unsubscribe me almost instantly. 

**Steps to Reproduce**
1. Go to an Invidious instance. 
2. Click on an instance (I used iv.ggtyler.dev and vid.puffyan.us). 
3. Log in 
4. Attempt to subscribe.
5. See error
-->

**Additional context**
I attempted to subscribe on my phone with safari, on my laptop and via Yattee. None of them work. 
-->

**Comment by unixfox** [comment]
Maybe tell us more details like the instance used (public or private)?

**Comment by gptlang** [comment]
>  Deleted or invalid channel

https://github.com/iv-org/invidious/blob/eda7444ca46dbc3941205316baba8030fe0b2989/src/invidious/channels/channels.cr#L158-L176

`http://www.youtube.com/feeds/videos.xml?channel_id=UC--0QCjDPscI45t2EV0SuKA` -> 
![image](https://github.com/iv-org/invidious/assets/121417512/caec7a88-ba1a-4ca8-89ff-5f4b4dce7f3a)

But it was present in the wayback machine:
https://web.archive.org/web/20221017182100/http://www.youtube.com/feeds/videos.xml?channel_id=UC--0QCjDPscI45t2EV0SuKA

**Comment by gptlang** [comment]
I see references to it being removed from a few months back: https://news.ycombinator.com/item?id=39179446

Why is this issue only popping up now?

**Comment by nansan1** [comment]
> Maybe tell us more details like the instance used (public or private)?

Updated

**Comment by nansan1** [comment]
It looks like it was restored somehow. I will close this now.

**Comment by FineTralfazz** [comment]
I'm running into this again on my instance. Sample RSS URL, though I've tried with a few and they all have the same issue: https://www.youtube.com/feeds/videos.xml?channel_id=UCy0tKL1T7wFoYcxCe0xjN6Q

**Comment by kbowlerthedragon2002** [comment]
I'm getting this problem too! 
the instance i'm on is nerdvpn
https://invidious.nerdvpn.de/feed/channel/UCFsUWElXNBZ6mpPAFydOoTw

**Comment by Fijxu** [comment]
> I'm getting this problem too! the instance i'm on is nerdvpn https://invidious.nerdvpn.de/feed/channel/UCFsUWElXNBZ6mpPAFydOoTw

Do not bump old closed issues, contact the instance administrator about that problem instead if you are not hosting your own instance of Invidious. cc @Sommerwiesel
