### ISSUE TITLE
[Support] Load time is too long using self-hosted Invidious instance

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [iv-org/invidious#4658]
I apologize in advance if Github Issues is not the right place to ask for support.

I am self-hosting private Invidious instance using docker. The problems I am facing are the following:

- It takes quite a long time (or end up failed) loading search results and video streams
- Thumbnails are missing. 
 
This does not seem like a bug, I confirmed public instances do not suffer from this issue. The problems started since mid 2023. I don't know exactly but I suspect Youtube is blocking my IP as describe in [Rotate your IPv6 address for escaping YouTube blocking](https://docs.invidious.io/ipv6-rotator/). 

Is this really caused by Youtube blocking my IP?

Edit: Here's my [docker-compose.yml](https://pastebin.com/SKh0QYNa)

**Comment by absidue** [comment]
Did you correctly follow the post-installation steps, such as setting up the frequent restart of Invidious?

> Because of various issues Invidious **must** be restarted often, at least once a day, ideally every hour.

https://docs.invidious.io/installation/#post-install-configuration

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.
