### ISSUE TITLE
[Bug] Using DASH on Linux Firefox leads to laggy playback

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#4665]
**Describe the bug**
The unique combination of using Invidious, DASH, Linux, and Firefox leads to laggy playback --- changing any of these parameters (using Youtube, using HD720, or using Chromium), leads to smooth playback.

**Steps to Reproduce**
1. Have an environment mentioned above (for reference, I am using Arch Linux ARM)
2. Play any video
3. See issue

**Logs**

**Screenshots**

**Additional context**
I originally that it had something to do with my GPU, but I couldn't replicate the issue with other sites (even those that use video.js).

**Comment by unixfox** [comment]
Probably has to do with either video codec not supported by your device or firefox being not performant enough on ARM.

Closing as video.js hasn't really changed for years and is fast enough.

You may test this PR if it's better with the latest version of video.js 8 though: https://github.com/iv-org/invidious/pull/4439

**Comment by DUOLabs333** [comment]
I think you're right --- I tested av1 playback on third-party sites (ie, neither Invidious or Youtube. Specifically, the problem was the most apparent here: https://av1comparison.vindral.com/), and it has the same lagging problems, while H.264 playback was smooth. Was the switch to av1 recent?

**Comment by unixfox** [comment]
> Was the switch to av1 recent?

Actually no but youtube only provide this codec when using DASH.

**Comment by DUOLabs333** [comment]
I think I may have been too hasty --- I can only get the slowdown with `watch?v=DSgFu4rDxgc` --- other videos work fine.

**Comment by unixfox** [comment]
Some video are AV1 only and some not. Mostly new video only have av1.

**Comment by DUOLabs333** [comment]
Only that video lags -- even videos that were published today plays as expected. I'm not sure what's the criteria for what codec gets returned.

**Comment by DUOLabs333** [comment]
Interestingly, after I recently updated mesa, the playback is still laggier, but much less than before.

**Comment by DUOLabs333** [comment]
I no longer have this issue --- it was probably fixed after one update or another.
