### ISSUE TITLE
[Enhancement] Docker multi-platform image

### ISSUE THREAD

**Issue by tomtom5152** [iv-org/invidious#4669]
**Is your enhancement request related to a problem? Please describe.**
Currently invidious provides images for `amd64` and `arm64` on different tags (`latest` and `latest-arm64` respectively). This works great with simple docker/docker-compose setups but does not scale well to a cluster orchestrator such as k8s running on mixed architecture.

**Describe the solution you'd like**
For invidious to provide a [multi-platform image](https://docs.docker.com/build/building/multi-platform/) for all platforms on the same tag such that an orchestrator can automatically download the correct image.

**Describe alternatives you've considered**
Manually assigning a specific image to a specific arch in the orchestrator. Works, but isn't ideal given it significantly hinders the ability of the orchestrator to schedule the pods across the whole cluster.

**Additional context**
Related #361

Would prevent issues such as #4177, #3609 with confusion about the `latest`/`latest-arm64` tags

**Comment by unixfox** [comment]
We hear the issue but it's explained here why this is not possible: https://github.com/iv-org/invidious/issues/361#issuecomment-881047911

We are investigating the cross compilation in this issue: https://github.com/iv-org/invidious/issues/2648 though.

Closing as I prefer to keep issue #2648 dedicated for finding how to cross compile for ARM then we can think about the multi platform.
