### ISSUE TITLE
[Feature request] personal channel notes

### ISSUE THREAD

**Issue by ulmemxpoc** [iv-org/invidious#4671]
**Is your feature request related to a problem? Please describe.**

My friends name their channel with random words. For example `@optimumtable81`. I can't remember whose channel it is. Looking at the content only reveals Minecraft videos and does not hint at who it is.

**Describe the solution you'd like**

Somewhere to write down and view persistent and private channel notes. Each of these notes should be attached to a channel.

**Describe alternatives you've considered**

Writing down such notes on a separate text file outside of Invidious. This is not user friendly.

**Additional context**

It would be better if even admins of the hosted Invidious can't read these private notes (encrypted) because it moght contain private information (name).

**Comment by unixfox** [comment]
That's out of scope of this project sorry.
