### ISSUE TITLE
[Bug] Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)

### ISSUE THREAD

**Issue by Tintin232** [iv-org/invidious#4673]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by Fijxu** [comment]
@Tintin232 any logs? Invidious always shows the logs/backtrace of the bug.

**Comment by Tintin232** [comment]
So sorry, I'm a beginner to these things, didn't know to record it 😞

**Comment by Tintin232** [comment]
Ok

**Comment by syeopite** [comment]
Likely a duplicate of #2137
