### ISSUE TITLE
[Bug] Channel banner sometimes doesn't load

### ISSUE THREAD

**Issue by oifj34f34f** [iv-org/invidious#4681]
**Describe the bug**
The channel banner sometimes doesn't load the first time, but loads on page refresh. Subscriber count is also missing
The bug also appears on yewtu.be (I haven't tested other instances except invidious.protokolla.fi), before testing I disabled all extensions in my browser

**Steps to Reproduce**
1. Go to any channel with a banner
2. See the absence of a banner

**Screenshots**
| ![desktop screenshot](https://github.com/iv-org/invidious/assets/128177553/d1f7d51d-cc3c-4236-8b6b-a6f7643cad8e) | ![mobile screenshot](https://github.com/iv-org/invidious/assets/128177553/05b11569-2f69-4502-9080-dc98cbdd2203) | 
|:--:|:--:| 
| *GNU/Linux, invidious.protokolla.fi* | *Android, yewtu.be* |

**Comment by An0n-00** [comment]
Hey there
It works for me:
![image](https://github.com/iv-org/invidious/assets/142223573/02c1472a-bbf3-483c-a1d5-8275f8e55956)

Could it be that something in your network might have blocked the pictures to load?

**Comment by unixfox** [comment]
Closing as it's either the server is overloaded or a network connection on your side that has issues.

**Comment by oifj34f34f** [comment]
The bug seems to have disappeared by itself, at least on https://invidious.protokolla.fi/.

**Comment by oifj34f34f** [comment]
Can we reopen this issue? Currently, this bug is seen on all instances, including my self-hosted instance.
FYI, yt-dlp has fixed this: https://github.com/yt-dlp/yt-dlp/commit/a0d9967f6822fc279e86bce33464194985148727

**Comment by unixfox** [comment]
please create a new issue @oifj34f34f
