### ISSUE TITLE
[Bug] Comments won't load on all videos

### ISSUE THREAD

**Issue by incrediblyimpressiveusername** [iv-org/invidious#4687]
You very conveniently closed issue #4566 as completed, but it has not been fixed, as can easily be verified by clicking "View [X] replies" and not having them load. You do an awful lot of this closing of issues without addressing them, editing bug reports to remove the bugs mentioned, and hiding comments by marking them as abuse. When will you start taking the project seriously again?

**Comment by unixfox** [comment]
![image](https://github.com/iv-org/invidious/assets/4016501/4f65ae7d-28e6-472b-b8dc-4b99c8386c1b)

can't reproduce, works on latest version... please update
