### ISSUE TITLE
[Bug] Can't change theme to auto in preferences

### ISSUE THREAD

**Issue by mattfbacon** [iv-org/invidious#4689]
**Describe the bug**
Whenever I try to set the theme to auto in the preferences it doesn't save properly. All other preferences work normally.

**Steps to Reproduce**
1. Go to preferences
2. Set theme to auto, and change another setting as well
3. Save
4. Go back to preferences and see that theme has not changed, but the other preference has

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
- Browser: Firefox

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.

**Comment by mattfbacon** [comment]
It's not my instance and I have reproduced this on every invidious instance I've tried.

**Comment by unixfox** [comment]
auto is the default theme so I don't know what you are talking about.

**Comment by mattfbacon** [comment]
The administrators have changed the default.
