### ISSUE TITLE
[Feature request] User profiles

### ISSUE THREAD

**Issue by cortsf** [iv-org/invidious#4690]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**

freetube style user profiles are very handy, would love to have them in invidious. Even more if they could be url-accesible so it would be possible to have multiple profiles open at the same time in multiple tabs. 

**Describe alternatives you've considered**
Allowing to login by setting a token in the url instead of user and password in the login page. So instead of having multiple profiles per user we could have multiple users which don't require filling any form to login.

**Comment by unixfox** [comment]
Are you referring to like an URL for saving preferences? This way you don't have to rely on cookies?

Similar to the preferences url in searx/searxng? https://searxng.site/searxng/preferences (then cookies section)

**Comment by cortsf** [comment]
More than preferences it's about having sets of subscriptions which can be switched from the address bar (using bookmarks, search engine alias/keywords, etc) without having to fill any login form. If implementing this with profiles (one user account, many profiles, similar to freetube) then all preferences would be the same for all profiles. If done by allowing some sort of access token in the urls (to avoid having to login manually) then each account will have its own preferences of course. I guess the second one only makes sense in locally run instances of invidious.

I guess this is also out of scope, I'm dropping the idea just in case.

**Comment by unixfox** [comment]
That is not possible, we could do something for preferences but apart from that, there is a technical limitation where it's not possible to do what you asked (subscriptions).

Should I keep the scope of this feature request only for preferences?

**Comment by cortsf** [comment]
Ahh sad. I personally don't care about preferences, feel free to keep it open for that reason of course.

Thanks!

**Comment by unixfox** [comment]
Ok I'm closing this one then. The free time has been lacking for quite some time, so I don't want to give hopes to implement this.

**Comment by maboroshin** [comment]
Piped implements this as channel groups. This idea seems easier than user profiles.

**Comment by cortsf** [comment]
There is also [this other solution](https://github.com/iv-org/invidious/issues/4745#issuecomment-2212606327). It has been working very well for me.
