### ISSUE TITLE
[Bug] Suggestions from subscribed channels not updating

### ISSUE THREAD

**Issue by zen85** [iv-org/invidious#4697]
Hello Community!

The Suggested Videos in the "Popular" and also the "Subscriptions" Tab ar often not updating for days. My newest Suggestion is from 4 days ago and can only be be updated by updating the whole docker-container. When i look at the channels i see a lot of new viedeos. they just dont appear in these two tabs. I went through the setttings but could not find any mistakes there. 
Does anybody have an idea where i am going wrong?

PS: I really love this project and the idea of it :)

**Comment by unixfox** [comment]
Do you daily restart invidious like explained in https://docs.invidious.io/installation/#post-install-configuration?

**Comment by zen85** [comment]
oh i see. that indeed "solves" it :)

made an hourly cronjob restarting the container
