### ISSUE TITLE
[Enhancement] Instance links in stats

### ISSUE THREAD

**Issue by shaedrich** [iv-org/invidious#4699]
**Is your enhancement request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be neat if the `/api/v1/stats` JSON result would look something like this:
```jsonc
{
  "version": "2.0",
  "software": {
    "name": "invidious",
    "version": "2024.04.27-eda7444",
    "branch": "master"
  },
  "openRegistrations": true,
  "usage": {
    "users": {
      "total": 804,
      "activeHalfyear": 645,
      "activeMonth": 156
    }
  },
  "metadata": {
    "updatedAt": 1715706242,
    "lastChannelRefreshedAt": 1715705442
  },
  "playback": {},
  "instanceLinks": { /* NEW */
    "contact": "/contact",
    "donation": "/donate",
    "modifiedSourceCode": "/modifications.txt",
    "statusPage": "https://perennial.statuspage.io/",
    "onion": "http://iv.daturab6drmkhyeia4ch5gvfc2f3wgo6bhjrv3pz6n7kxmvoznlkq4yd.onion/"
  }
}
```

**Describe alternatives you've considered**

```jsonc
{
  "version": "2.0",
  "software": {
    "name": "invidious",
    "version": "2024.04.27-eda7444",
    "branch": "master"
  },
  "openRegistrations": true,
  "usage": {
    "users": {
      "total": 804,
      "activeHalfyear": 645,
      "activeMonth": 156
    }
  },
  "metadata": {
    "updatedAt": 1715706242,
    "lastChannelRefreshedAt": 1715705442
  },
  "playback": {},
  "features": { /* NEW (other parent key) */
    "contact": true, /* booleans instead of strings */
    "donation": true,
    "download:" false
  }
}
```
This option has the downside, that not all instances have, for example, the donation information at `/contact`.

**Additional context**
Or is there any other way to programmatically get these information?

**Comment by unixfox** [comment]
But why?
Donation link is always the same, it's /donation

And there is no "contact" configuration for the moment.

**Comment by shaedrich** [comment]
> Donation link is always the same, it's https://invidious.io/donate/

Nope, it's not. I'm talking about instance specific links. Hence the key. For example: https://einfachzocken.eu/donate or https://invidious.nerdvpn.de links to https://ko-fi.com/weidenwiesel

> And there is no "contact" configuration for the moment.

Well, on some instances, there's a contact page: https://einfachzocken.eu/contact

**Comment by unixfox** [comment]
They all have modified code for dealing with that. It's not official.

**Comment by shaedrich** [comment]
I know. But I hoped, this could be easily added via a config file. So, there's no way of knowing, unless the instance also modifies the API 🤷🏻‍♂️
