### ISSUE TITLE
Select all on mobile

### ISSUE THREAD

**Issue by Jtasiu** [iv-org/invidious#471]
Whenever I watch a video on mobile there is an annoying thing where if you on the player a bit to long like when you change the position of the video a 'Select All' option pops up and won't go away without some extra useless steps. 

I don't know if there is a way to change this on invidious' end so that these kind of options don't pop up when click on the player...is there some CSS or way to stop it from popping up?

**Comment by omarroth** [comment]
I'm having trouble reproducing this on iOS, what device are you encountering this on?

**Comment by Jtasiu** [comment]
I get this issue on Android Oreo device

**Comment by Perflyst** [comment]
I tried to reproduce this, didnt worked either. I can get a "Select All" popup but I can easily click outside the video and this popup hides again.

Can you please provide a screenshot or something?

**Comment by Jtasiu** [comment]
@Perflyst

That "Select All" popup is what I'm talking about. It's annoying to close it whenever the popup comes up blocking part of the video when you're in fullscreen and you need to exit the video, click outside the video and go back into fullscreen...especially when it becomes a regular occurrence. I face this popup quite frequently whenever dragging or moving the video position in the progress bar...maybe I do this more than other people so I notice it regularly.

**Comment by Perflyst** [comment]
I have never done this before. I only get such a popup if I click longer on the video timeline.
I can get multiple different "Select All" popups, I would still ask for a screenshot from you.

**Comment by Jtasiu** [comment]
Couldn't take screenshot in fullscreen but below is after exiting from fullscreen

![screenshot](https://user-images.githubusercontent.com/43510369/56123869-bb269580-5fb8-11e9-988b-93f31585fced.png)

**Comment by Perflyst** [comment]
Thanks. Okay, than I can reproduce this. But it doesnt happen for me in daily usage, just if I want it.
