### ISSUE TITLE
[Question] Recognize URLs with si query parameter in search

### ISSUE THREAD

**Issue by shaedrich** [iv-org/invidious#4710]
**Describe the bug**

When YouTube links have an `si` URL parameter appended, Invidious search can't find the video. I'm not familiar with Invidious' algorithm to extract the video ID, but I would assume, this is only a minor adjustment to be made.

**Steps to Reproduce**
1. Go to the start page of an instance of your choice
2. Paste 'https://youtube.com/shorts/LlkXltZaD_w?si=zgUmpZh0aXnI4aUh' into the search field
3. Press enter
4. See "No results found."

**Logs**

**Screenshots**

![grafik](https://github.com/iv-org/invidious/assets/11225821/e3cfc7ab-9399-42a6-85eb-ddba4e5fba53)

**Additional context**

**Comment by unixfox** [comment]
The search function is passed along to youtube servers.

If this search is not supported by the youtube servers itself, it won't work on invidious too.

Based on my testing, searching with the parameter "si" on www.youtube.com doesn't work either.

**Comment by SamantazFox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/3300
