### ISSUE TITLE
[Bug] ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by roifgroup** [iv-org/invidious#4718]
**Describe the bug**
Some videos do not seem to be able to load properly for example:
1. https://www.youtube.com/watch?v=j5Zsa_eOXeY (works)
2. https://invidious.lunar.icu/watch?v=j5Zsa_eOXeY (Does not work)

**Steps to Reproduce**
1. Click on URL number 2 above. 

**Logs**
Getting "Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial content)" in Chrome developer tools.
No additional logs in the container.

On Firefox I got a little banner: "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Screenshots**
![Screenshot from 2024-05-31 06-24-35](https://github.com/iv-org/invidious/assets/62592047/dfc107ff-f72f-454d-a882-4299d1397cd0)

**Additional context**
 - Browser (if applicable): Tested on Chrome / Firefox

Tried to get the curl command and test on the terminal got:
```
curl --trace-ascii output.txt --tlsv1.2 'https://rr3---sn-nhpax-ua8r.googlevideo.com/videoplayback?expire=1717136950&ei=1hlZZtKVHOWuhcIPivu2gAM&ip=102.110.52.11&id=o-ACVhzNeU0FShRc0iDPijy3lOHMlSpJGkpHJ-S1K8KyBT&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=7d&mm=31%2C29&mn=sn-nhpax-ua8r%2Csn-ua87zn7l&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=991250&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&cnr=14&ratebypass=yes&dur=8298.022&lmt=1709368201718765&mt=1717114617&fvip=5&c=ANDROID_TESTSUITE&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgF20XArG4uZDpf5r6DPnq0Uy9I4oX4e1J_AUloOrkjO0CIGL7qPhSC32YgAsvM8qNkecRUP1OJiu0JZIXXqrJr5-j&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIgJveFkyH0bHkUlmg9Ha2pFqzbKXkAaA6dWeM60l24n44CIQCZLgGfC3UJGdIdLnhM4B48s14EfSuX2dhyLl2JQhnU7A%3D%3D&host=rr3---sn-nhpax-ua8r.googlevideo.com' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Range: bytes=4030464-' \
  -H 'Sec-Fetch-Dest: video' \
  -H 'Sec-Fetch-Mode: no-cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' \
  -H 'X-Client-Data: CIW2yQEIorbJAQipncoBCJzqygEIlKHLAQj7mM0BCIegzQE=' \
  -H 'sec-ch-ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"'
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
```

Trying to download the video I found that some of the video only download button work, while the combined does not. Which makes me believe this is a not supported format of sorts.

**Comment by unixfox** [comment]
Can you reproduce the error on other instances: https://api.invidious.io/?

**Comment by roifgroup** [comment]
Very interesting:
https://invidious.fdn.fr/watch?v=j5Zsa_eOXeY (Works)
https://vid.puffyan.us/watch?v=j5Zsa_eOXeY (Does not work)
https://invidious.nerdvpn.de/watch?v=j5Zsa_eOXeY (Does not work)
https://invidious.lunar.icu/watch?v=j5Zsa_eOXeY (Does not work)
https://inv.tux.pizza/watch?v=j5Zsa_eOXeY (Does not work)
https://inv.nadeko.net/watch?v=j5Zsa_eOXeY (Does not work)

On the one that works: 
![Screenshot from 2024-05-31 14-34-59](https://github.com/iv-org/invidious/assets/62592047/acac7f22-7fab-45fd-863c-2692157ae561)


On the onces that do not:
![Screenshot from 2024-05-31 14-35-38](https://github.com/iv-org/invidious/assets/62592047/c42e8002-2f2d-435b-b9df-89d3cd0e17b7)

**Comment by unixfox** [comment]
Probably due to https://github.com/iv-org/invidious/issues/4734, closing.
