### ISSUE TITLE
Loop on mobile

### ISSUE THREAD

**Issue by Jtasiu** [iv-org/invidious#472]
Is there a way to loop a video without using the parameter on mobile? On desktop there is a option to right-click and click loop but on mobile both mobile and desktop versions don't give this option. Any way to add it?

**Comment by omarroth** [comment]
You can set `Always loop` in your preferences, which will loop all videos. There doesn't appear to be any native option in Safari or other mobile browsers for allowing a user to loop a video.

It would probably be necessary to add something like a `Loop` button, similar to the listen option, but if it's only necessary on mobile this seems wasteful.

**Comment by Jtasiu** [comment]
I think Loop button is not needed either. A tap and hold the click menu option to do this like on desktop would be best because I don't want to loop every video but it's ok if it's not possible. Close issue if you want.

**Comment by omarroth** [comment]
Unfortunately this does not appear to be possible. Mobile browsers don't provide any API for modifying the menu option. The official YouTube player uses a custom menu on desktop, but this does not appear to be possible on mobile devices.

Other events (double tab etc.) are consumed by the device for other purposes, so as mentioned I don't know of any way this could be implemented without using the `Loop` button I mentioned above.

**Comment by Jtasiu** [comment]
@omarroth

I find myself manually looping more recently which makes me think a button for loop may be worthwhile. Do you think it's worth to add a loop button next to the listen button? It would be very useful and easy click to loop for tablet and mobile users in my opinion (also another way for desktop users to easily loop a video too I guess).

**Comment by omarroth** [comment]
Sure. In that case it would probably make sense to move both `Loop` and `Audio mode` to the bottom left, see @Booteille's comment in [#491](https://github.com/omarroth/invidious/issues/491#issuecomment-483384141).

**Comment by Jtasiu** [comment]
@omarroth 
Agree, makes sense
