### ISSUE TITLE
[Question] I cant log in my account

### ISSUE THREAD

**Issue by Yumega** [iv-org/invidious#4722]
install invidious by docker, I can login my account at Local area network.
Reverse proxy it to my own domain, I can play the videos,but I can't login my account or creat an account.

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing as it's a configuration issue on your side.
