### ISSUE TITLE
[Bug] Missing hash key: "videoDetails" (KeyError)

### ISSUE THREAD

**Issue by anonas1** [iv-org/invidious#4723]
Title: `Missing hash key: "videoDetails" (KeyError)`
Date: `2024-06-02T13:47:51Z`
Route: `/watch?v=27Z4fur1lEg`
Version: `2024.05.26-bbd550a @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "videoDetails" (KeyError)
  from src/invidious/helpers/helpers.cr:188 in 'dig'
  from /usr/lib/crystal/core/json/any.cr:342:3 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:111:27 in 'extract_video_info'
  from /usr/lib/crystal/core/hash.cr:1280:13 in 'fetch_video'
  from src/invidious/videos.cr:383:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from /usr/lib/crystal/core/string.cr:3075:20 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>

**Comment by C-Loftus** [comment]
Also getting this same bug for all videos. I am deploying via docker compose on Ubuntu 22.04 for what it is worth. (No configuration on my end)

**Comment by ast9501** [comment]
I ran into same problem. Update to newer version works for me:
2024.05.27-1ae14cc2 @ master

**Comment by C-Loftus** [comment]
> I ran into similar problem. Update to newer version works for me: `2024.05.27-1ae14cc2 @ master`

I have git cloned the repo on the most recent commit and it says the version is `Version: `2023.08.26-ac0c0609 @ master`, at least when I build with docker-compose. Could you specify what the right way to get a more recent version would be? Wasn't sure if I can't use docker for that.

**Comment by C-Loftus** [comment]
> Maybe check your current commit is at latest commit ([1ae14cc](https://github.com/iv-org/invidious/commit/1ae14cc22468ce6e0eb794752b113604b1d5582d))? It seams like you are in older commit on master branch. I built with docker-compose too.
> 
> > > I ran into similar problem. Update to newer version works for me: `2024.05.27-1ae14cc2 @ master`
> > 
> > 
> > I have git cloned the repo on the most recent commit and it says the version is `Version: 2023.08.26-ac0c0609 @ master`, at least when I build with docker-compose. Could you specify what the right way to get a more recent version would be? Wasn't sure if I can't use docker for that.

Ah that's it, I needed to rebuild the cached version, thanks! `docker-compose up -d --no-deps --build`.

**Comment by Fijxu** [comment]
I see no problems on my instance (https://inv.nadeko.net/watch?v=27Z4fur1lEg). Probably youtube is changing the way they display the videoDetails or they are simply blocking some requests made by the instance you are using.

**Comment by ZenIsFluffy** [comment]
Receiving the same error on my instance as well. I am on `2024.04.10-b673695a @ master` and deploying over docker-compose. 

Title: `Missing hash key: "videoDetails" (KeyError)`
Date: `2024-06-16T15:59:31Z`
Route: `/watch?v=EnDCumOfgWg`
Version: `2024.04.10-b673695a @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "videoDetails" (KeyError)
  from /usr/share/crystal/src/hash.cr:1077:11 in '[]'
  from /usr/share/crystal/src/hash.cr:1128:17 in 'dig'
  from src/invidious/videos/parser.cr:152:12 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:111:5 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:391:3 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video'
  from src/invidious/videos.cr:361:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from src/invidious/routing.cr:159:19 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:157:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:146:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:517:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:470:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Comment by Happyfeet01** [comment]
Same problem here.

Title: `Missing hash key: "videoDetails" (KeyError)`
Date: `2024-06-22T07:17:07Z`
Route: `/watch?v=F6shQa0yZuE`
Version: `2024.04.10-b673695 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "videoDetails" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in 'dig'
  from /usr/share/crystal/src/json/any.cr:330:3 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:112:10 in 'extract_video_info:video_id'
  from /usr/share/crystal/src/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment]
This is because sometimes the client ANDROID_TESTSUITE does not work anymore.

It seems like youtube is A/B testing the removal of this client.

**Comment by K33k0** [comment]
Fixed for me with the latest docker image
quay.io/invidious/invidious:latest image (07ceda5d18d4)
Current version: 2024.04.27-eda7444 @ master

**Comment by ZenIsFluffy** [comment]
I feel kinda silly. I had been running `docker-compose pull` but didn't think to run `git pull`. Anyway, after that I ran `docker-compose up -d --no-deps --build` as mentioned above. Brought my version from `2024.04.10-b673695a @ master` to `2024.05.27-1ae14cc2 @ master` and now its working!

**Comment by Happyfeet01** [comment]
> I feel kinda silly. I had been running `docker-compose pull` but didn't think to run `git pull`. Anyway, after that I ran `docker-compose up -d --no-deps --build` as mentioned above. Brought my version from `2024.04.10-b673695a @ master` to `2024.05.27-1ae14cc2 @ master` and now its working!

I do the same but still on 2024.04.10-b673695 @ master

**Comment by Fijxu** [comment]
> > I feel kinda silly. I had been running `docker-compose pull` but didn't think to run `git pull`. Anyway, after that I ran `docker-compose up -d --no-deps --build` as mentioned above. Brought my version from `2024.04.10-b673695a @ master` to `2024.05.27-1ae14cc2 @ master` and now its working!
> 
> I do the same but still on 2024.04.10-b673695 @ master

Do `git pull` first, then build the image.

**Comment by unixfox** [comment]
Don't use the docker-compose.yml please. Use the production docker-compose: https://docs.invidious.io/installation/

**Comment by Happyfeet01** [comment]
I forgot the docker-compose pull after the git pull.
Now it works ;-)

**Comment by ImTheSadra** [comment]
![image](https://github.com/user-attachments/assets/0ff475a2-7acb-469f-b8e4-64eda657937d)
i got this error in this [instance](https://invidious.privacyredirect.com)
and no video can be played

**Comment by hgw77** [comment]
I have the same issue with the latest release v2.20240825.2, I also tested latest from master. My invidious is running in a k3s cluster and was running before without problems

I can see in the logs:

````
2024-09-30 09:40:29 UTC [error] get_video: qnX6sPFjXnA : Missing hash key: "videoDetails"
2024-09-30 09:40:29 UTC [info] 500 GET /watch?v=qnX6sPFjXnA 634.04ms
````

**Comment by spitfire** [comment]
This helped me: https://social.tchncs.de/@invidious/113209915579753655
