### ISSUE TITLE
[Bug] 2160p quality option missing on some videos

### ISSUE THREAD

**Issue by fuomag9** [iv-org/invidious#4724]
**Describe the bug**
4K video is missing on https://www.youtube.com/watch?v=TWc48iVC8u8 when opened on invidious, even with dash enabled. Videos such as https://www.youtube.com/watch?v=nH9bobxSfvA have 4K 

**Steps to Reproduce**
1. Enable DASH
1. Open https://www.youtube.com/watch?v=TWc48iVC8u8 on invidious
2. There will be no 2160p option available
3. Open https://www.youtube.com/watch?v=nH9bobxSfvA on invidious
4. There will be a 2160p option avabilable

**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3677
