### ISSUE TITLE
[Bug] Video wont load. Watch on the latest version of YouTube. 

### ISSUE THREAD

**Issue by ParadoxLeon** [iv-org/invidious#4725]
**Describe the bug**
Video wont load

**Steps to Reproduce**
On my instance vid.selbsthilfegruppe.wtf click on any video

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/67509460/f3e37766-c434-4b1d-b9b2-c4946709ba34)

**Additional context**
even after I removed the security headers the error persists

**Comment by unixfox** [comment]
Is https://docs.invidious.io/ipv6-rotator/ correctly setup?

**Comment by sunlightspectre** [comment]
Can confirm this happens on yewtu.be as well.  
Fairly consistently. And of course, the rotator should be set up right there.

**Comment by ParadoxLeon** [comment]
> Is https://docs.invidious.io/ipv6-rotator/ correctly setup?

I haven't set this up since I'm having some trouble with my ipv6 set up but I'm working on it.
so it could be youtube blocking the instance?

**Comment by ParadoxLeon** [comment]
just noticed invidious.yourdevice.ch has the same problem.
![image](https://github.com/iv-org/invidious/assets/67509460/e152f38d-0d89-4240-a84d-61c2a4e1d134)

**Comment by unixfox** [comment]
> > Is [docs.invidious.io/ipv6-rotator](https://docs.invidious.io/ipv6-rotator/) correctly setup?
> 
> I haven't set this up since I'm having some trouble with my ipv6 set up but I'm working on it. so it could be youtube blocking the instance?

It's literally written in the form when adding a new instance to set it up.

It's mandatory, otherwise your instance will stop functioning after a few days.

**Comment by ParadoxLeon** [comment]
It's not mandatory it's just

> [...] highly recommended to follow these tutorials because it will allow the instance to stay stable and performant [...] 

maybe change the wording

**Comment by ParadoxLeon** [comment]
after having a mental breakdown setting up ipv6 on my server, the ipv6-rotator is up and running.

Instance is working for now

**Comment by unixfox** [comment]
Closing in favor of the new bug: https://github.com/iv-org/invidious/issues/4734
