### ISSUE TITLE
[Help] Allow remote connection to PostGRE SQL database. 

### ISSUE THREAD

**Issue by nirvgorilla** [iv-org/invidious#4735]
Hello - 
I apologize for posting this here but I'm not sure where else to post; and please bear with me as I'm fairly new to Linux.

My friend forgot his password on his account, so I used the standard method to change it using the documentation, but when I went to log into it to make sure it changed, it said "registration is disabled." Confused, I quickly enabled registration, restarted the server, and logged in with the credentials. His playlist was gone and all settings - it was a new account.
So I logged into the database (this is a standard installation debian server, no GUI), and was able to see that there were two identical account names in the database.
Not being comfortable with navigating databases in a terminal, I typed netstat -ntpl to see if postgre was open to remote connection; it wasn't. 
So I changed the config file for postgre in /etc/ to 0.0.0.0/0 md5, but of course invidious doesn't seem to use a normal version of postgre and does it a different way. That's where I'm lost.

I wanted to open the db for remote connection so I can use HeidiSQL in Windows or some GUI so I don't accidentally delete my friend's account and instead delete the duplicate one. But of course I'm not smart enough to even know the credentials required to connect to the invidious db. I saw the config.yml and I can see host: localhost and the db URL, but I don't know what to change it to in order to open it up for remote connection, and I don't know what credentials I would need.
I couldn't find anybody else anywhere who wanted to do this with invidious, so this is my last resort.

**Comment by unixfox** [comment]
Hello, 

As maintainers, we do not have a lot of free time, so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Closing.
