### ISSUE TITLE
[Feature request] SponserBlock

### ISSUE THREAD

**Issue by mosajjal** [iv-org/invidious#4748]
Hi, 

There is a freely available Database for all the sponsored blocks of YouTube videos. The extension is [here](https://github.com/ajayyy/SponsorBlock) and the server code is [here](https://github.com/ajayyy/SponsorBlockServer). Any appetite to integrate this with the native player as an option? Since invidious already has a Postgres database, a scheduled job to sync up the table to the local db should be doable, which only leaves the player tweaks to skip the seconds provided for each video.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3519
