### ISSUE TITLE
[Bug] Player menus hiding when moving the cursor

### ISSUE THREAD

**Issue by giacomocerquone** [iv-org/invidious#4749]
**Describe the bug**

When opening whatever menu available on the player, such as video quality, playback speed etc., if you don't move the cursor fast enough, the menu gets closed, and I'm not able to select any option from the menu. This one is pretty annoying for me.

**Steps to Reproduce**

1. Open whatever video
2. Try to change its quality for example, or the playback speed
3. You'll notice that if you're not fast enough to move the cursor up, the menu gets closed.

**Logs**

This is not a problem where logs are related.

**Screenshots**

Here is a video of the bug I'm talking about: https://www.loom.com/share/10504723e7ca452481eefb2193979bd2

**Additional context**

**Comment by unixfox** [comment]
You are supposed to click on the menu option for keeping it active.

**Comment by giacomocerquone** [comment]
> You are supposed to click on the menu option for keeping it active.

Didn't know this, and I don't find it that intuitive, you know? I guess mine can be considered as an enhancement, then. But if you feel like you don't want this, let's close it!

Thanks

**Comment by unixfox** [comment]
It's the default behavior of video.js, a video player library.

It would be interesting if you can still reproduce your bug in the newer video.js 8: https://github.com/iv-org/invidious/pull/4439
