### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TSN4444** [iv-org/invidious#4756]
Images:
Reference 1- https://github.com/iv-org/invidious/assets/165482704/be6bd01a-64ee-463f-ba01-653ae14d69f1
Reference 2- https://github.com/iv-org/invidious/assets/165482704/c97408cb-4f76-4365-9a8b-1de05e937bb9

taken from console (These lines of code loop):

VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
(anonymous) @ video.js?v=eda7444:163
video.js?v=eda7444:163 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError
(anonymous) @ video.js?v=eda7444:163
/videoplayback?expire=1718696140&ei=bORwZtGuLsWBkucPu4yP6AU&ip=2603%3A3005%3A6cf6%3A8100%3Aa526%3Ad029%3Aebd4%3Ae605&id=o-AGcn1kkGjpyw-9EoSCD8twrm5iytiuJDgWKohlNgJpgh&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=FS&mm=31%2C29&mn=sn-jvhj5nu-cvnd%2Csn-p5qlsn7s&ms=au%2Crdu&mv=m&mvi=3&pl=40&initcwndbps=716250&bui=AbKP-1OyCkZzydTFWP_7WjOM5UhaxAWwo4iLq-NgRwLqQCjR9hJ7cJuaWZo1dlHyspEkHA2BmLsOE_W9&vprv=1&svpuc=1&mime=video%2Fmp4&ns=kdhQ5z_e9aEaOG6sQX93DGsQ&rqh=1&gir=yes&clen=61372491&ratebypass=yes&dur=1115.834&lmt=1718435349666537&mt=1718674142&fvip=5&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER&sefc=1&txp=5538434&n=vmznd0gSzg8M4FcW&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgRqh5Agbo6ZT3t9n7C4JeYIAHwpRlmUEiAaO3nw40NYACIFmGMtJrnTP5dCIDfwNLW6XmttbpmiFqJNW7BxzBgSXy&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgRiZF34yfhNJazaN8DRrEBiDNJkoVDW3GE1OhNJw6WokCIQDHCNXIhdutpczzLiE6i-HJ_voKzSTVaKq4mrOQVGE1ng%3D%3D&host=rr3---sn-jvhj5nu-cvnd.googlevideo.com:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
video.js?v=eda7444:163 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError
(anonymous) @ video.js?v=eda7444:163
player.js?v=eda7444:75 An error occurred in the player, reloading...

OS: Windows
Browser: Brave

Context: for certain channels, videos will not play and will keep giving the error seen in "Reference 1", and when I attempt to download the video to watch videos from these specific channels an error says that I'm not allowed to see them (Reference 2). I have also tried downloading the videos from other places such as YTMP3 and still get a similar error.

**Comment by syeopite** [comment]
Looks like the instance was blocked by YouTube. If it's an instance you host you should try setting up the IPv6 rotator and if not you should use another public instance.

**Comment by TSN4444** [comment]
I've tried with other instances but it doesn't work still, It's only specific channels like Second Thought that don't seem to work, this has been happening across all instances

**Comment by syeopite** [comment]
Ah I see.

I went to check on the specific video you mentioned and it looks like the video has been age-gated.

Invidious is able to bypass some age restricted videos but not all of them. And in this case the Second Thought video is unable to be accessed. 

See #2189

**Comment by TSN4444** [comment]
any ways I can fix this?

**Comment by unixfox** [comment]
There is no fix.

**Comment by TSN4444** [comment]
alright, thanks for the info, it helps a lot
