### ISSUE TITLE
[Bug] HD720 only shows medium quality on multiple instances

### ISSUE THREAD

**Issue by AnimatorTao** [iv-org/invidious#4759]
**Describe the bug**

HD720 only shows the medium quality option and not the other one (high) on multiple instances

**Steps to Reproduce**
1. Open video
2. Click on the gear icon
3. See the missing option

**Additional context**

 - Browser (if applicable): Brave

**Comment by ashley0143** [comment]
can confirm - itag 22 doesnt work - itag 18 does

**Comment by unixfox** [comment]
It seems like youtube removed itag22 on all their clients.

We will see if there is a way to fix that or not.

**Comment by ashley0143** [comment]
> It seems like youtube removed itag22 on all their clients.
> 
> We will see if there is a way to fix that or not.

cant we just combine 720p video and medium audio server-side? and call that itag 22 on the code ?

**Comment by unixfox** [comment]
> > It seems like youtube removed itag22 on all their clients.
> > 
> > We will see if there is a way to fix that or not.
> 
> cant we just combine 720p video and medium audio server-side? and call that itag 22 on the code ? like, hard code it.

No that would be too computationally expensive.

Just use DASH instead.

**Comment by felifluid** [comment]
DASH also seems to be broken. At least on my instance I'm getting the error message "The media could not be loaded, either because the server or network failed or because the format is not supported." 🤔

**Comment by altercat10n** [comment]
> DASH also seems to be broken. At least on my instance I'm getting the error message "The media could not be loaded, either because the server or network failed or because the format is not supported." 🤔

I am not sure that comment is off-topic. As DASH [was recommended](https://github.com/iv-org/invidious/issues/4759#issuecomment-2184072002) as a solution for this thread’s problem. But *in my experience, DASH videos very often do not work*, which was the reason I initially had chosen HD720 in my settings as default. (Which does not give acceptable video quality recently, as mentioned by the thread starter.)

**Comment by unixfox** [comment]
Because it's a separate issue. Let's keep on topic about HD720 and not about DASH issues.

DASH could very well be affected by the latest YouTube issues from https://github.com/iv-org/invidious/issues/4734. The only way to know what's going on is to look at the requests from the network tab in the devtools (F12).

**Comment by unixfox** [comment]
Closing as hd720 is gone. There is no way to recover it.

This is where Invidious will maybe need to switch to DASH by default.

**Comment by Berkopl** [comment]
> Because it's a separate issue. Let's keep on topic about HD720 and not about DASH issues.
> 
> DASH could very well be affected by the latest YouTube issues from #4734. The only way to know what's going on is to look at the requests from the network tab in the devtools (F12).

Whee is the issue for video that not working with DASH setting?

**Comment by PricacyPro0** [comment]
DASH should be set as default. 
If I enable DASH, Videos are all in a very good quality. 
I almost stopped using Invidious, because the Video quality only was 360p or lower. 
720p is the minimum quality for videos to be watchable

Thanks for the idea with DASH
It resolves the issue, but most people don't know. That's why it should be standard.
