### ISSUE TITLE
[Feature request] autotorrent

### ISSUE THREAD

**Issue by SoniEx2** [iv-org/invidious#4761]
**Is your feature request related to a problem? Please describe.**

in addition to watching via invidious it should also be possible to watch via torrent, which works independently of the invidious instance

**Describe the solution you'd like**

when proxying is enabled, also generate torrents

**Describe alternatives you've considered**

N/A

**Additional context**

bonus points if generating torrent rss feeds

**Comment by unixfox** [comment]
That's not possible.

For torrent to work you need the entire video file to exist in the filesystem of the server that host invidious.

But invidious only proxy, it doesn't store any file.

**Comment by SoniEx2** [comment]
no you don't, you just need the hash to stay the same

**Comment by unixfox** [comment]
Whatever that's out of the scope of the kind of features we implement in invidious.

**Comment by SoniEx2** [comment]
but why?

**Comment by syeopite** [comment]
Invidious is merely an alternative frontend for YouTube. We provide a UI where users can browse and watch for videos, and an API for applications to do the same. That's it.

Anything else is out of scope for a project like Invidious. We do no processing on our end and instead just proxies content from YouTube to the end user. 

A torrent feature will require a computationally intensive process to convert YouTube's video streams to one that can be sent via torrent.
