### ISSUE TITLE
Add Custom RSS Feeds as A Subscription

### ISSUE THREAD

**Issue by jhlee2222** [iv-org/invidious#4767]
**Is your feature request related to a problem? Please describe.**
Subscription management isn't as robust as I'd like, but I don't really need it to be, as another solution could curate that for me with this feature. 

**Describe the solution you'd like**
Add the ability to subscribe to a custom RSS feed containing YouTube videos.

**Describe alternatives you've considered**
I'm not sure where to begin, but I've wondered if there was a way to "hack in" a subscription, maybe via the import functionality, to have it refer to a custom RSS feed. Just messing around, I've not found a way to do this. The front end likewise does not appear to allow for it either.

**Additional context**
I'd like the ability to manage subscriptions via my feed reader, subscribing to a YouTube channel's RSS feed, then using my feed reader to fashion a custom feed for my Invidious instance to pick up and display as though it's a channel's feed. My feed reader configuration could filter out things from subscriptions I don't care for, or could even provide a feed of videos I've tagged within the feed reader to mark to watch later. From Invidious's standpoint, I'd have one or more subscriptions that are coming from a custom RSS feed, not a channel feed directly from Youtube.

**Comment by unixfox** [comment]
I'm sorry this is out of scope.
