### ISSUE TITLE
[Bug] Media playback was aborted

### ISSUE THREAD

**Issue by UltraBlackLinux** [iv-org/invidious#4769]
**Describe the bug**

As of maybe 12 hours ago videos stopped playing on my private instance entirely, always showing the same error message, mentioned below.

Any idea what's going on? I've restarted my entire system (in case that might fix it once again) and ran a `docker compose pull` , but no dice still.

**Steps to Reproduce**

Try to play any video.

**Logs**
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Object { code: 3, message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." }
​
code: 3
​
message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
​
<prototype>: Object { code: 0, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, … }
video.js:163:49
```
and
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 468008b failed for segment #0 in playlist 2-placeholder-uri-2 
Object { code: 3, message: "video append of 468008b failed for segment #0 in playlist 2-placeholder-uri-2" }
video.js:163:49
```

**Additional context**
 - Browser (if applicable): Floorp (Firefox derivative)
 - OS (if applicable): Arch Linux - both server and client

**Comment by unixfox** [comment]
Check the devtools and see what is shown in the "network" tab.

**Comment by UltraBlackLinux** [comment]
hmm. I'm getting a lot of
![image](https://github.com/iv-org/invidious/assets/62404294/d4780b89-d7f0-4881-8a30-2e00f3621c2b)
(Blocked) stuff. No idea why that is. It's definitely new. I'm unsure why that would happen all of a sudden. I've changed no configs anywhere

**Comment by unixfox** [comment]
Click on the a request and check the response code.

**Comment by UltraBlackLinux** [comment]
well it's `206 Partial Content`

**Comment by unixfox** [comment]
Closing as most probably related to the latest youtube breakages: https://github.com/iv-org/invidious/issues/4734
