### ISSUE TITLE
[Bug] Stuck on not being able to play on mobile network.

### ISSUE THREAD

**Issue by thickmelon** [iv-org/invidious#4773]
**Describe the bug**

Stuck on not being able to play on mobile network. Works fine only on wifi.

**Steps to Reproduce**

1. Go to Yattee
2. Click on any video
3. Stuck on loading

**Logs**

**Screenshots**

![image](https://github.com/iv-org/invidious/assets/50360240/cdf31bf2-365b-411f-862c-4fadb6a3584a)

![image](https://github.com/iv-org/invidious/assets/50360240/d84484c1-1b10-465f-8a4f-b7eb6ac41ec4)

**Additional context**

 - Browser (if applicable): 
 - OS (if applicable): iOS 17.5.1 on iPhone 15

**Comment by unixfox** [comment]
Please open a bug issue on yattee instead. This repo is about invidious.

**Comment by thickmelon** [comment]
It's the same on Invidious web version

2024년 7월월 4일 (목) 3:03 오후, Émilien ***@***.***(mailto:2024년 7월월 4일 (목) 3:03 오후, Émilien <<a href=)> 작성됨:
