### ISSUE TITLE
[Enhancement] docker compose for arm64/v8 (Raspberry Pi 5)

### ISSUE THREAD

**Issue by fgerent** [iv-org/invidious#4786]
I followed the docker install instructions (both prod and dev) for a Raspberry Pi 5 host, but was initially getting exec format errors.

I was able to solve that by adding "platform: linux/arm64/v8" to my docker compose file, maybe that could be added as an optional (commented out) entry to the example docker files, similar to how there's an option for the arm64 image?

**Comment by unixfox** [comment]
follow the docs: https://docs.invidious.io/installation/#docker

**Comment by fgerent** [comment]
Sorry, I must be missing something. That's the documentation I was following, I just searched that page and I don't see any references to "platform" there. Where is that information located?

**Comment by unixfox** [comment]
search for "ARM64"

**Comment by fgerent** [comment]
I can see the arm64 image option (as I had mentioned on my original message), but even when using that image I was getting exec format errors. That was only fixed when I specifically added "**platform: linux/arm64/v8**", and I don't see that option mentioned anywhere in the documentation.
