### ISSUE TITLE
[Bug] Unused method definitions in `Invidious::LogHandler`

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#4791]
I noticed that the following methods in `Invidious::LogHandler` aren't actually being used whatsoever, neither in Invidious itself nor anywhere in Kemal.

`#puts`
https://github.com/iv-org/invidious/blob/bad92093bff66bfb0281e5276fa0e136a61ba330/src/invidious/helpers/logger.cr#L37-L40

`#set_log_level`
https://github.com/iv-org/invidious/blob/bad92093bff66bfb0281e5276fa0e136a61ba330/src/invidious/helpers/logger.cr#L47-L53

As such these methods can be safely removed.

I'm opening this issue as to make sure these methods aren't being purposelessly kept

**Comment by SamantazFox** [comment]
These can safely be removed!
