### ISSUE TITLE
[Bug] Non Englisch Video descriptions (and sometimes comments) glitch up

### ISSUE THREAD

**Issue by Vamp898** [iv-org/invidious#4802]
**Describe the bug**
With English, everything seems to look fine, but looking at german and japanese videos, the result is something like this
![image](https://github.com/user-attachments/assets/9446885e-ca73-4b0c-9847-4aeafd7f931b)
![image](https://github.com/user-attachments/assets/ebbb78c4-b4c0-44c3-a1ee-19f8dd81af6e)
![image](https://github.com/user-attachments/assets/e418bef6-be5c-41c6-904e-5e997797236a)

**Steps to Reproduce**
1. Go to watch?v=_mg0fNxFtE8
2. Check the Video description
3. Check comments

**Additional context**
 - Browser (if applicable): Firefox 128.0.1
 - OS (if applicable): Archlinux

**Comment by unixfox** [comment]
Related: https://github.com/iv-org/invidious/issues/4256

**Comment by SamantazFox** [comment]
It works well on a few public instances:
* https://invidious.fdn.fr/watch?v=_mg0fNxFtE8
* https://invidious.incogniweb.net/watch?v=_mg0fNxFtE8
* https://invidious.privacyredirect.com/watch?v=_mg0fNxFtE8
* https://invidious.flokinet.to/watch?v=_mg0fNxFtE8

Is this happening on your instance?
If yes, check that your web server (e.g nginx) is properly configured!

**Comment by Vamp898** [comment]
Hi there, thanks for the reply.

Its my own instance, its running on localhost and i directly access it on port 3000, there is no webserver in between.

It worked fine until the update ~2weeks ago. I am building directly from source.

If you need any other informations, feel free to ask

**Comment by syeopite** [comment]
Which Crystal version are you using to build Invidious? There was a similar problem in the RSS feeds as seen in #4256 but it was due to an upstream problem that was fixed in [Crystal 1.10.0](https://github.com/crystal-lang/crystal/releases/tag/1.10.0)

**Comment by Vamp898** [comment]
Crystall 1.13. I just tried a make clean and rebuild, but the result is the same.

**Comment by Vamp898** [comment]
This issues is fixed since 2024.08.26 Update =)
