### ISSUE TITLE
[Bug] Stuck on not being able to play on mobile network.

### ISSUE THREAD

**Issue by thickmelon** [iv-org/invidious#4803]
**Describe the bug**

Stuck on not being able to play on mobile network. Works fine only on wifi.

**Steps to Reproduce**

1. Use a web browser and access invidious
2. Click on any video
3. Stuck on loading

**Logs**

**Screenshots**

![image](https://github.com/user-attachments/assets/48274b1d-1a8e-4d10-9cf5-6d51be3c957e)

![image](https://github.com/user-attachments/assets/134f1b56-0c2f-4399-9802-4cdfb6895c2e)

**Additional context**

 - Browser (if applicable): safari, chrome, anything on mobile. Even on supported app.
 - OS (if applicable): iOS 17.5.1 on iPhone 15

**Comment by unixfox** [comment]
No idea, could be that the instance is somewhat broken.

Would suggest to try on an instance from the official instances list: https://instances.invidious.io

**Comment by thickmelon** [comment]
Alr. Thx anyways.

**Comment by unixfox** [comment]
Or try with proxy enabled in the preferences.

**Comment by thickmelon** [comment]
I don’t understand why, but this worked lol thank you

2024년 7월월 26일 (금) 5:00 오후, Émilien ***@***.***(mailto:2024년 7월월 26일 (금) 5:00 오후, Émilien <<a href=)> 작성됨:

**Comment by unixfox** [comment]
could be that something on your mobile network is blocking access to google servers. because without proxy enabled, you are directly connected to google servers when you are loading the video stream.
