### ISSUE TITLE
[Bug] after creating a user logon its not helping

### ISSUE THREAD

**Issue by Berkopl** [iv-org/invidious#4804]
**Describe the bug**

after I create a user, I provide the user and password, the system accepts it, but the user is not logged in, logging in again also means that they cannot log in without any error, there is simply no login, system show still “login”

my version 2024.04.27-eda7444 installed 2 days ago.

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Or you may consult these probably related issues for finding a fix:
- https://github.com/iv-org/invidious/issues/2668
- https://github.com/iv-org/invidious/issues/3132
- https://github.com/iv-org/invidious/issues/2509

Closing as it's a configuration issue on your side.

**Comment by Berkopl** [comment]
@unixfox Thank you, your right, this was error on me configuration, alias in domain was not needed. 
yea make my day.✌🏻
