### ISSUE TITLE
[Bug] Can’t change video quality, video quality always poor.

### ISSUE THREAD

**Issue by Berkopl** [iv-org/invidious#4809]
**Describe the bug**

[Bug] Can’t change video quality in the player windows, only “medium” quality are available.
Also changing the video quality in the settings change to any quality don’t make a difference, video is always poor like “medium”.
Also why there is only 720P to setup in the setting, not more like 1080p (see screenshot)
Thx.
**Screenshots**
screenshots to help explain your problem.

**Additional context**
 - Browser (if applicable):Safari
 - OS (if applicable):iPadOs 17.5.1
 - Current version: 2024.04.27-eda7444 
![IMG_1504](https://github.com/user-attachments/assets/5148b627-00bb-424d-913e-f00839930566)

[
![IMG_1506](https://github.com/user-attachments/assets/7e095d84-6830-4c6d-b23c-c44461ff30e7)
](url)

If I change to DASH QUALITY video won’t play:
![IMG_1507](https://github.com/user-attachments/assets/2c12bb04-0c9d-4c65-ba71-2b1bcca18dbf)

-->

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4759
