### ISSUE TITLE
[Feature request] Subtitles with auto generated translate

### ISSUE THREAD

**Issue by Berkopl** [iv-org/invidious#4810]
description

[Future request] Subtitles with auto generated translate, like in YouTube, machine translate to any language.
Like this example in YouTube website player: 
![IMG_1509](https://github.com/user-attachments/assets/f1f5288e-22e0-42c7-8b54-f7ada65ef6b5)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2567
https://github.com/iv-org/invidious/issues/4432

https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L174

**Comment by Berkopl** [comment]
> #2567 #4432
> 
> https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L174

Hi Fox,
thanks for the quick reply, but can you please tell me how I can cover these links more specifically, or is there a bare solution there?
Thx

**Comment by syeopite** [comment]
This is more #2187
