### ISSUE TITLE
[Feature request] Options to setup up Autoskip of, intros, self promotion etc. and visibility of this on timelime by color coding. Like on viewtube.io

### ISSUE THREAD

**Issue by Berkopl** [iv-org/invidious#4817]
[Feature request] Options to setup up Autoskip of, intros, self promotion etc. and visibility of this on timelime by color coding. Like on viewtube.io
Screenshot from viewtube.io as an example for the solution idea.

![IMG_1525](https://github.com/user-attachments/assets/9642f23e-bb13-417f-8002-939cdc52a4da)
![IMG_1526](https://github.com/user-attachments/assets/8de51466-33f9-4fb0-8a97-65312ae9a8d2)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3519
