### ISSUE TITLE
[Feature request] Allow download to override stream

### ISSUE THREAD

**Issue by nintendoeats** [iv-org/invidious#4820]
**Is your feature request related to a problem? Please describe.**
Streaming can be flaky, and inconsistent, either dropping down quality or stopping altogether. I personally also want to maintain an archive of my favourite videos. 

The download feature, and other youtube downloading clients offer a solution but then you lose the youtube frontend (it's just a bunch of files in folders). It's ok, but not perfect.

**Describe the solution you'd like**
I would like it if I could specify a server-side "download" folder, and have the option to tell Invidious to download a video to the server. Then I would like to be able to play the downloaded video from the server, directly from Invidious as though it were streaming from Youtube.

**Describe alternatives you've considered**
AFAIK the main alternative is downloading to folders, possibly writing a new frontend to present that nicely. 

**Additional context**
My thought is that this feature is exclusively for local instances, and any public instance would turn it off (holy bandiwdth batman!).

**Comment by unixfox** [comment]
Out of scope. Use youtube-dl or yt-dlp for that.
