### ISSUE TITLE
[Bug] Home and End keys not working

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#4828]
**Describe the bug**

The Home and End keys to go to the beginning and end of a video do not work. Instead, they scroll the page.

**Steps to Reproduce**
1. Open a video
2. Try to use the Home/End key
3. The page scrolls to the beginning or the end instead of the video.

**Logs**

**Screenshots**

**Additional context**

**Comment by SamantazFox** [comment]
That's expected. If you want to jump around in the video, the keys 0 to 9 on the numpad jump to 0% to 90% of the video, respectively.
