### ISSUE TITLE
[Bug] Very long videos slow down Firefox and make Invidious unuseable

### ISSUE THREAD

**Issue by Vertux** [iv-org/invidious#4830]
**Describe the bug**
Very long videos massivly slow down Firefox and the Invidious user interface become unuseable.

**Steps to Reproduce**
1. Search and open [this huge video 81hrs(!) (AWS Certified Developer Associate (DVA-C02) Certification Course – Prepare For and Pass the Exam)](https://youtu.be/TTcyhhH2FWE) in Invidious (do not play it!)
2. Almost immediately Firefox become unresponsive and shows a warning (here in german):
<img width="658" alt="Bildschirmfoto 2024-08-12 um 21 24 04" src="https://github.com/user-attachments/assets/9a1f8216-a179-47b1-b65e-23d515f632d7">

3. If you try to add the video to a playlist, it does not work.
4. Refreshing the page does not help either.

**Additional context**
 - Browser (if applicable): Firefox v129.0, 64bit
 - OS (if applicable): MacOS Sonoma 14.6.1 (23G93), Apple Silicon
 - Invidious Current version: 2024.04.27-eda7444 @ master (Docker image, which runs in a Debian 12.5 VM, XCP-NG)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/3220
