### ISSUE TITLE
[Bug] 私たちのコミュニティを保護するのに役立ちます

### ISSUE THREAD

**Issue by kou123a** [iv-org/invidious#4833]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by kou123a** [comment]
どういうことですか？これをそうていがいにしゅうりょうしましたとは

**Comment by kou123a** [comment]
すみませんわかりました。ありがとうございます

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734
