### ISSUE TITLE
[Bug] Can't (watch or) download any videos; "access denied" 

### ISSUE THREAD

**Issue by Tintin232** [iv-org/invidious#4856]
**Describe the bug**
When I try downloading any video I get this message:
![Screenshot_20240817_101459_Chrome](https://github.com/user-attachments/assets/5e786f70-31d5-4225-8b14-30a059cd47fb)

**Additional context**
I can't either watch any video due to the following error message, 
![Screenshot_20240817_102202_Chrome](https://github.com/user-attachments/assets/04b508d0-4c99-4fab-8516-dcfa1d215558)
but that's not what I'm trying to do right now so I won't focus on that.

 - Browser: Chrome 127.0.6533.103
 - OS: Android 14

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734

**Comment by Tintin232** [comment]
It's actually working now, thanks whoever 🫠.
