### ISSUE TITLE
[Bug] Video downloads keep auto-pausing

### ISSUE THREAD

**Issue by Tintin232** [iv-org/invidious#4864]
**Describe the bug**
When downloading any video from Invidious, the download keeps on auto-pausing, saying "waiting for network", and I I have to pause and resume the download every time.

**Screenshots**

![Screenshot_20240820_065446_Chrome](https://github.com/user-attachments/assets/04b149c7-e25c-4e28-b7ae-4f3c127fdde4)

**Additional context**
This seems to be an Invidious-related issue, as other downloads from the same browser work just fine.
 - Browser: Chrome (v 127.0.6533.103)
 - OS: Android 14

**Comment by unixfox** [comment]
Is this a private or public instance?

**Comment by Tintin232** [comment]
It's a public instance. 
https://invidious.reallyaweso.me/, to be exact.

**Comment by unixfox** [comment]
Then it's an instance issue. Contact the owner.
