### ISSUE TITLE
[Enhancement] Provide YT Music `authorUrl` Instead of YT `authorUrl` for YTM streams in `recommendedVideos`

### ISSUE THREAD

**Issue by n-ce** [iv-org/invidious#4866]
**Is your enhancement request related to a problem? Please describe.**

Basically users expect channels of ytm streams take them to their ytm channel and not the yt channel which kinda comes of as odd.

**Describe the solution you'd like**

Point to ytm channel instead. I know Invidious does not support yt music yet but the stream which points to the yt channel already does not exist on it.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by absidue** [comment]
Invidious shows the information it gets from YouTube, so those channels should exist, I doubt YouTube would return a link to a non-existent channel.

Please provide an example of what you are talking about.

**Comment by n-ce** [comment]
> Invidious shows the information it gets from YouTube, so those channels should exist, I doubt YouTube would return a link to a non-existent channel.
Not talking about the channel but the stream itself. You won't find the stream on the channel that it links to.

**Comment by absidue** [comment]
On YouTube those channels list the singles and albums and the videos are inside those playlists.

The main problem with your proposal then becomes how Invidious can identify those videos in the recommended videos list **without making any extra requests**. In YouTube's response they have the same data structure as every other video, there is not magic "is this originally from youtube music" property.

**Comment by n-ce** [comment]
> In YouTube's response they have the same data structure as every other video, there is no magic "is this originally from youtube music" property.

In the Piped API's `relatedStreams` the `author` contains ' - Topic' and the `authorUrl` is of YTM. Therefore in the case of Invidious, I would have to assume this is some sort of extraction side logic to keep the YT data fields.

**Comment by SamantazFox** [comment]
Could you provide an example? I'm not sure to understand how the two differ!

**Comment by n-ce** [comment]
> Could you provide an example? I'm not sure to understand how the two differ!

I'm extremely sorry! I just checked and It seems either there have been a mistake on my side or that the API behaviour has changed. It now stands that The Piped response is not any different from the Invidious response.
I'm very sorry for wasting the valuable time!
