### ISSUE TITLE
Can't get rid of "This helps protect our community. Learn more"

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4874]
Hi, I've followed [this installation guide ](https://github.com/iv-org/documentation/blob/sig_helper_po_token/docs/installation.md)for setting up my personal instance on a VPS server.

I did everything correctly but it's still showing that error.
Here is my yml file, Is anything wrong?
`version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: "CgtrUVY3NUM5QjNkSSjxiaa2BjIKCgJJUhIEGgAgMA%3D%3D"
        po_token: "IjjWiNaLsEFSepXvovqD3o-7mN2bvYfimOOF27zwv-m3upTin8OV75zCg-CfzZHvl--byfO7kq3lzA=="
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "Cchangedbro2933hh"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:`
  
  I added the two visitor_data and po_token between double quotes and i also tested without double quotes but it's still the same.
  
  Some things to note:
  I get my vps server from Hetzner which allows me to have ipv6 on my server along with ipv4.
  Which one is recommended?
  Though I tried with both ipv6&ipv4 and also ipv4-only and the problem didn't fixed.
  
  What am I doing wrong?
  Also which type of IP and networking is recommended for Invidious?

**Comment by unixfox** [comment]
You should be using master not latest branch.
