### ISSUE TITLE
[Question] "media could not be loaded" - "Parse MP4 metadata failed"

### ISSUE THREAD

**Issue by evilantishad0w** [iv-org/invidious#4889]
**Describe the bug**
Playing at least one video results in "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Steps to Reproduce**
Play stream ID epWABkgM1_I on an invidious instance.  (Private and several public instances tested.)
Playing on Youtube works normally.

**Logs**
Media resource http://192.168.89.191:3000/latest_version?id=epWABkgM1_I&itag=18&local=true could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)

Details: virtual RefPtr<MP4Demuxer::InitPromise> mozilla::MP4Demuxer::Init(): Parse MP4 metadata failed
An error occurred in the player, reloading... player.js:75:21
...
Media resource http://192.168.89.191:3000/latest_version?id=epWABkgM1_I&itag=18&local=true could not be decoded.
...
Source map error: Error: NetworkError when attempting to fetch resource.
...
Resource URL: http://192.168.89.191:3000/js/silvermine-videojs-quality-selector.min.js?v=4782a67
Source Map URL: silvermine-videojs-quality-selector.min.js.map

**Comment by evilantishad0w** [comment]
Discovered video plays properly when the flags "&quality=dash&quality_dash=auto" to the URL.  Does not work if the invidious container settings are switched to this.

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

**Comment by evilantishad0w** [comment]
As I said, this video does not play on other, public invidious instances, like yewtube.

**Comment by krim404** [comment]
@unixfox i can confirm this, i have a lot of videos now which are unplayable on neither invidious instance.

**Comment by weikib** [comment]
I've looked at other instances and it happens here too, so it's not just something from my instance.

**Comment by swoop124** [comment]
hello guys,

i have the same problem with newer videos. I discovered one public invidios instance where it is working correctly.
https://inv.nadeko.net/watch?v=09EXdXwrDhg&quality=dash&quality_dash=auto
The version of this invidious instance is  2024.09.19-7ded745 

My selfhosted instance is on version:  2024.08.26-4782a67

maybe the newer version is working correctly, so pleas make the docker container with the new version publicly avalable.

thanks
