### ISSUE TITLE
[Question] How people are opening new issues while  #4734 is still not fixed?

### ISSUE THREAD

**Issue by sahinakkaya** [iv-org/invidious#4891]
Since  #4734, invidious doesn't work for me at all. I can't watch any video. Yet, people are still opening new issues and new commits are still pushed. Is there a workaround that I am not aware of? Are you able to use invidious?

**Comment by syeopite** [comment]
Yes, https://github.com/iv-org/invidious/issues/4734#issuecomment-2290075097

**Comment by syeopite** [comment]
You can find the guide on setting those up in this PR https://github.com/iv-org/documentation/pull/581
