### ISSUE TITLE
Like/Dislike option

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [iv-org/invidious#490]
I think it would be nice if we have the option to like or dislike a vídeo. I think this is important, cause it's a way author sees feedback about his/her videos.

**Comment by Perflyst** [comment]
Is this even possible without being logged into youtube? I mean you somehow need a google account to like something, otherwise google cant count the likes.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
impossible. wontfix please close.

**Comment by omarroth** [comment]
It's possible if logged in with Google. Invidious can sync subscriptions/etc. with YouTube so could do the same with likes. Otherwise, for Invidious accounts, it would likely have a separate counter (see #253).

Similar thoughts in #300.

**Comment by BurnyBoi** [comment]
>Otherwise, for Invidious accounts, it would likely have a separate counter (see #253).

Adding a separate like/dislike system for Invidious accounts seems like overkill and out of scope. It also doesn't give the author any feedback like how the actual YouTube system does, which is the main concern DevAspirer brought up. It's unlikely that a YouTube author is going to go around to public Invidious instances to see how people are reacting to it.

**Comment by omarroth** [comment]
My understanding is that YouTube provides a list of liked/disliked videos as a separate playlist, similar to watch later and favorites, so something like this would probably be added as part of #114. Similar to #253 it would be an extension of something already implemented (subscriptions for #253, and playlists for this). Likes would be determined from the number of users with the video ID in their respective `Liked videos` playlist, and similarly for disliked videos.

Invidious already provides separate users, subscriptions, and playlists are planned, so I wouldn't consider it out of scope if that's what's being requested here. If that is the case then I'd consider it a fairly simple extension to something that's already planned and wouldn't have a problem adding it.

**Comment by elypter** [comment]
youtube uses algorithms to skew those numbers und invidio.us also has a differen user pool. i would consider likes and dislikes to be valuable information for users to dicern if a video is watchworthy

**Comment by BlauerHunger** [comment]
I'd like to have the option to attach my google account to my invidious account so that the instance adds a like/dislike to the video on youtube using the google account when I press the corresponding button

**Comment by KlausDevWalker** [comment]
> I'd like to have the option to attach my google account to my invidious account so that the instance adds a like/dislike to the video on youtube using the google account when I press the corresponding button

That would be awesome.

**Comment by syeopite** [comment]
This is an valid feature request that really shouldn't be closed.

**Comment by unixfox** [comment]
Impossible to implement, you can't like a youtube video without a google account, and we prefer to keep invidious as a simple "proxy".

**Comment by Zero3K** [comment]
What about having someone make a userscript?
