### ISSUE TITLE
[Enhancement]  Set a cap on max resolution for auto dash

### ISSUE THREAD

**Issue by RNavarro3000** [iv-org/invidious#4900]
I have a private instance of Invidious, which I use via desktop/phone/tablet.

Video quality is set to dash and quality_dash is set to auto
Whenever I have playback stutter/buffer issues its usually related to the player grabbing a 2160p stream... as soon as I manually set to 1080p, playback is fine.

Could a parameter be added to limit auto dash to a max resolution set by user, such as 1080p or 1440p?
Current version: 2024.08.26-4782a67 @ master

**Comment by unixfox** [comment]
Already exist its literally called "Preferred DASH video quality" in the preferences.
