### ISSUE TITLE
[Bug] `formatStreams` only has 360p stream for non-dash players

### ISSUE THREAD

**Issue by ThaDaVos** [iv-org/invidious#4907]
**Describe the bug**

Somewhere along the period of the past few months something changed causing the `formatStreams` to only return a single stream for 360p quality, see for example: https://inv.nadeko.net/api/v1/videos/SurUidVDQf4

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by absidue** [comment]
The change was on YouTube's side, they stopped providing the 720p combined audio+video stream, there is nothing Invidious or any other project can do about it.
