### ISSUE TITLE
[Feature request] Integrate Return YouTube Dislikes API

### ISSUE THREAD

**Issue by Bubba8291** [iv-org/invidious#4913]
**Is your feature request related to a problem? Please describe.**

Dislikes as we know have been gone for a while.

**Describe the solution you'd like**

Integrate the return YouTube Dislikes API https://returnyoutubedislike.com/docs/

**Describe alternatives you've considered**

An Invidious Dislike API

**Additional context**

Return YouTube Dislikes currently has an open source Chromium and Firefox extension. [Anarios/return-youtube-dislike
](https://github.com/Anarios/return-youtube-dislike)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/2781#issuecomment-1025263083
