### ISSUE TITLE
[Bug] This content isn’t available.

### ISSUE THREAD

**Issue by KPniX** [iv-org/invidious#4916]
**Describe the bug**

If I can't open YouTube clip on some Invidious instance. Displays a info about unavaible content or "Protect Community".

**Steps to Reproduce**

1. Try open any video by Invidious
2. Error was display

**Logs**
None

**Screenshots**

![picture](https://github.com/user-attachments/assets/caee6e57-e14d-42b6-9141-58ddf73ef1fd)

**Comment by syeopite** [comment]
Duplicate of #4734

But this is interesting... I believe the "This content isn't available" error is new.

**Comment by akasaka99** [comment]
Hi, I have the same issue even with servers using version as late as 2024.09.17-cec3cfb.

**Comment by epman100** [comment]
I'm getting the same problem this October but with Invidious instance sites invidious.jing.rocks & yt.drgnz.club with any youtube videos and these videos all work with youtube
