### ISSUE TITLE
[Bug] This helps protect our community. Learn more

### ISSUE THREAD

**Issue by Panja0** [iv-org/invidious#4919]
I'm running: 2024.08.26-4782a67 @ (HEAD detached at v2.20240825.2)

I'm using the signhelper + potoken as per [manual](https://github.com/iv-org/youtube-trusted-session-generator)
Still getting the error: `This helps protect our community. Learn more` 

It worked before with the signhelper and potoken but since today (maybe yesterday) it stopped working again.
Created a new potoken and created the docker stack again without luck.

[docker-compose.yml](https://pastebin.com/5D1TmKXL)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734

**Comment by Panja0** [comment]
Thanks for the reply.
But did you check my docker-compose and my problem description?

I already using visitor data and po-token. 

Could you point me to what I am doing wrong?
Instead of just linking to a thread I already followed and implemented?

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734#issuecomment-2349782180

**Comment by W9JYD** [comment]
Stop being a jerk @unixfox ! Jesus Christ foss devs are jerks.
