### ISSUE TITLE
Windows installation via docker

### ISSUE THREAD

**Issue by K0-RR** [iv-org/invidious#4927]
The guide mentions it's possible to install on Windows via docker. Since I only want to use invidious locally, I went the development route.
```
... \invidious> docker-compose up
time="2024-09-19T17:27:54+02:00" level=warning msg="C:\\Users\\Roman\\invidious\\docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.46/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dinvidious%22%3Atrue%7D%7D": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
```

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

**Comment by K0-RR** [comment]
I understand and I will ask there, but I want to mention there was no configuration needed to be done.
According to the [guide](https://docs.invidious.io/installation/#docker-compose-method-development) all I have to do is:
```
git clone https://github.com/iv-org/invidious.git
cd invidious
docker-compose up
```
