### ISSUE TITLE
[Bug] Same video published date for all videos

### ISSUE THREAD

**Issue by boher** [iv-org/invidious#4932]
**Describe the bug**
As of 20 September 2024, all videos on invidious instances are taking the current date as the upload published date, instead of the actual date. Observing this on working instances [yewtu.be](https://yewtu.be) and [invidious.privacyredirect.com](https://invidious.privacyredirect.com/)

**Steps to Reproduce**
1. Go to any video uploaded at least a day ago
2. Click on another video that is also uploaded at least a day ago
3. See that the date indicated below the channel name are the same
4. Repeat step 2 to view the same results
-->

**Screenshots**
On working invidious instances:
![image](https://github.com/user-attachments/assets/47ece7bb-c375-496a-a781-ce323bd7404a)

On youtube:
![image](https://github.com/user-attachments/assets/d9743213-7713-4372-b86d-48348b469e26)

**Comment by absidue** [comment]
The issue just before yours explains why, the place Invidious was reading the published date from before, no longer exists with the new workaround to get videos to play. There is probably somewhere else Invidious could get that information from, but understandably the maintainers decided that getting videos to play was higher priority and that fixing the metadata could be done later.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4929
