### ISSUE TITLE
[Enhancement] Suggestions or ideas to battle google blocks

### ISSUE THREAD

**Issue by nyakojiru** [iv-org/invidious#4936]
**Is your enhancement request related to a problem? Please describe.**
About recent google ultimate block. Trying to help, giving some suggestions or ideas.

**Describe the solution you'd like**

I suggest a solution to be able to create instances from within tor. It would be slow, but impossible to block. Or from any other network that don’t rely on single IP access to YouTube . Or, make a mesh of collaborative home instances. Google can’t block millions of home IPs. Or use any mesh collaborative network capable of it. Collaborative on requests of videos streams only, that would load balance to not overload single home instances.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/879
