### ISSUE TITLE
[Enhancement] Instances could work like nostr relays

### ISSUE THREAD

**Issue by MrDraxs** [iv-org/invidious#4938]
Instead of manually trying each instance to see with one is on or not, instances can work kinda like nostr relays, the client will have the option of a configuration in the settings where we will be able to put instances that we chose there and when we load the site it will automatically try to load each instance in order if the instance that it try to load failed it will load the next one in line.

EXAMPLE:

MAIN SITE(CLIENT)
configuration:
instances list:
[inv.nadeko.net]
[invidious.nerdvpn.de]
[invidious.jing.rocks]
[invidious.privacyredirect.com]

entering main site(CLIENT)

day 1
[inv.nadeko.net]✅
[invidious.nerdvpn.de]🟩
[invidious.jing.rocks]🟩
[invidious.privacyredirect.com]🟥

day 2
[inv.nadeko.net]❌
[invidious.nerdvpn.de]✅
[invidious.jing.rocks]🟩
[invidious.privacyredirect.com]🟩

day 3
[inv.nadeko.net]❌
[invidious.nerdvpn.de]❌
[invidious.jing.rocks]❌
[invidious.privacyredirect.com]✅

✅ and 🟩 are online instances.

❌ and 🟥 are offline instances.

✅ succeed to load.

❌ failed to load.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/879
