### ISSUE TITLE
[Feature request] Easy Installer

### ISSUE THREAD

**Issue by valenhas** [iv-org/invidious#4939]
Because of https://github.com/iv-org/invidious/issues/4734, I installed Invidious on macOS, which went fairly well.
There is nothing comparable to Invidious, all the other Youtube frontends lack in design and UI simplicity.

So I propose to create easy to use installers that place premade executables and register them to run at login. 
Everyone could run their own private instance, drawing little attention from Youtube.

For macOS, it could even be a Homebrew package.

**Comment by valenhas** [comment]
Working around blocks looks pretty doomed to me, now that Invidious has major Youtube attention. I think a focus on installers, while dropping the work on blocks, would reduce workload a lot.

**Comment by unixfox** [comment]
There is no plan to stop supporting public instances. We will continue to investigate solutions.

The reason why we are not investigating into some "installer" is that we have no real knowledge about that and the "Docker" installation is easy enough for most of the people. We can't fulfill everyone needs, Invidious wasn't initially meant to installed by everyone, it just so happens that Docker lower the bar of entry.

There is no plan to officially having an installation as simple as installing Freetube or Newpipe.

If someone from the community have the time to create an installer, it's great we will list their software on our documentation page but the maintainers of Invidious have no plan to maintain this kind of software.

**Comment by WardPearce** [comment]
> We don't have time to maintain something else than what's already being proposed on the installation page: https://docs.invidious.io/installation/
> 
> There are some automated scripts like this one but it's non-official: https://github.com/tmiland/invidious-updater
> 
> And then I have heard that @WardPearce want to create a desktop app of a fork called Materialious. Maybe he can explain what will be this project.

Yea not sure if Materialious is super applicable to this issue. But if someone wants a modern frontend for Invidious, Materialious is a option.

If someone is facing issues with a public instance they use is being blocked by Google, Materialious has automatic fallback support using YouTube.js & handles all the po token & visitor data generation locally on Android & Desktop.

https://github.com/Materialious/Materialious
