### ISSUE TITLE
[Feature request] skip shorts / shorts on demand per channel

### ISSUE THREAD

**Issue by VnkCCENcXH0c3AhnijQ0y7SBeZx27** [iv-org/invidious#4941]
## feature request: 

requesting functionality which would ignore certain shorts from a feed per individual channel. 

## background: 

there are 3 types of youtubers: 

1. those that do not make shorts
2. those that make shorts that are original 
3. those that butcher their perfectly fine regular video into 20 ten-seconds shorts and release them before or after the main video spamming the feed with worthless recap junk mining for clicks

## execution:

under **https://inv.url/subscription_manager** add one more column with checkboxes per each line/channel effectively forcing (if checked) to skip shorts entering the cue at **https://inv.url/feed/subscriptions**

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2585
