### ISSUE TITLE
[Bug] Cannot open videos and always get 403 errors

### ISSUE THREAD

**Issue by RobertoBiundo** [iv-org/invidious#4952]
**Describe the bug**

Any video that I load in my private invidious instance fails to load with the error message 
"The media could not be loaded, either because the server or network failed or because the format is not supported."

Since im running invidious using dockers a docker-compose logs -f shows that all calls to /videoplayback reutrn GET 403.
I have tried removing the entire DB, stopping and restarting the dockers, setting DASH on/off, changing resolution from 720p to medium to small. 

The server used to be fine for about a month and I watched videos every morning (1-2 videos). But since a week ago I cannot play anything.

**Steps to Reproduce**

**Logs**

2024-09-26 17:39:37 UTC [info] 200 GET /watch?v=1s188WNEiqw 22.26ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 302 GET /latest_version?id=1s188WNEiqw&itag=18 73.94ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 302 GET /latest_version?id=1s188WNEiqw&itag=18 15.35ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 200 GET /api/v1/storyboards/1s188WNEiqw?height=90 17.95ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 302 GET /latest_version?id=1s188WNEiqw&itag=18&local=true 1.88ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 200 GET /vi/fmILGS4C9Ro/mqdefault.jpg 192.97ms
invidious-invidious-1     | 2024-09-26 17:39:38 UTC [info] 403 GET /videoplayback?expire=1727393408&ei=H5r1ZradO-rL6dsP4cTLgAY&ip=143.178.4.57&id=o-AKJWoC9tevoRHtmQd-fsVurS6Lt_HUW3KXdg57Rb9ZG1&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=ue&mm=31%2C29&mn=sn-uhvcpaxoa-guhe%2Csn-5hne6nz6&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=2923750&bui=AXLXGFTHZtK1CA4692f5i5iOcGpgFgqtW2HZoqUUQdjMiZTuAkIigAGd-IeykK3gB7-OhHwNQk2Taarw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=dhZWEtY4Ef05d5xWNQ5YfjMQ&rqh=1&gir=yes&clen=21702826&ratebypass=yes&dur=373.934&lmt=1727260637986055&mt=1727371505&fvip=4&fexp=51299152%2C51300761&c=TVHTML5_SIMPLY_EMBEDDED_PLAYER&sefc=1&txp=4438434&n=hNAKFR1ctabapFEeC&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAKPYxcXzsmpdbhc0tV6ENWlyBT4Cs2DGJ9-Aoy0ih0quAiEAh5UnKC_f97mvbhSd_Uor_ZnxkUO9EiYsU6AyjfL15K4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRgIhAOlDqkIFhEy2hjQKdNXd7-31BqOXFGVpr76BWbkzOZriAiEAhI8nF3j4xQNAB2fxfxvfGD-bODTEH2QUEUOQsw6VFH4%3D&host=rr2---sn-uhvcpaxoa-guhe.googlevideo.com 103.31ms

**Screenshots**

![Screenshot 2024-09-26 194131](https://github.com/user-attachments/assets/1f5a1e26-3e25-4489-898c-688d4da5f6ef)
![Screenshot 2024-09-26 194150](https://github.com/user-attachments/assets/61eb2af7-253a-4d6d-b5ea-40e2e5dc69e7)

**Additional context**

**Comment by msinfo32github** [comment]
See https://github.com/iv-org/invidious/issues/4947 & a potential fix at https://github.com/iv-org/invidious/issues/4947#issuecomment-2373119622
