### ISSUE TITLE
[Bug] All videos randomly stop working ! format is not supported.

### ISSUE THREAD

**Issue by Berkopl** [iv-org/invidious#4956]
<!--error by any setting and video.
  window.The media could not be loaded, either because the server or network failed or because the format is not supported.
--
My version: Current version: 2024.04.27-eda7444 @

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. --
![IMG_1602](https://github.com/user-attachments/assets/a3f185ec-3c0c-4095-bdaa-f3c1ba8567bf)
![IMG_1601](https://github.com/user-attachments/assets/8f9222a3-4ef4-4cdc-94f1-fc714120e5c0)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4947
