### ISSUE TITLE
[Bug] The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by Lucky-Lobo** [iv-org/invidious#4957]
**Describe the bug**

The media could not be loaded, either because the server or network failed or because the format is not supported.

Appears on any video when i swtich to DASH in the options, no video is loading - once I'll switch back to HD720 every video loads.

Tried differennt combinations (proxy on/off, config external domain etc.)

**Steps to Reproduce**

1. Go to 'Preferences'
2. Click on 'Preferred video quality'
3. Scroll down to 'DASH (adaptive quality'
4. Go back to video and see error

**Logs**

![2024-09-28_14-01](https://github.com/user-attachments/assets/3148fb96-6f7c-4e89-9a0c-8b964459d657)

**Screenshots**

![2024-09-28_14-05](https://github.com/user-attachments/assets/99c38ca8-825a-4505-af82-7d091a7c121d)

**Additional context**

 - Browser (if applicable): Firefox, Chromium
 - OS (if applicable): Debian Client, Server Ubuntu 24.04

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4947
