### ISSUE TITLE
[Enhancement] please enable h2 (http2) on official instances

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [iv-org/invidious#496]
please enable h2 (http2) on official instances. only http1.1 atm.
would result in better streaming latency and benefit at all and in all scenarios. 
please consider it also for the onion virtual hosts! but they have no tls enabled at all yet. which is required for h2. h2c would be fine too but its not supported by many browser without tls.

**Comment by Perflyst** [comment]
> please consider it also for the onion virtual hosts! but they have no tls enabled at all yet

TLS on onion is useless and not needed

**Comment by omarroth** [comment]
As mentioned in crystal-lang/crystal#2125, should be possible with [this shard](https://github.com/ysbaddaden/http2). I would have to do more testing before this is added.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> > please consider it also for the onion virtual hosts! but they have no tls enabled at all yet
> 
> TLS on onion is useless and not needed

i agree with you, that the transport is already encrypted and so it is not needed for this case. _(well there are other benefits i do not want to describe here)_ but it is an **requirement** to **enable h2**.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
think this issue is still relevant and applicable

**Comment by unixfox** [comment]
There is official instances anymore and a lot of instances support HTTP2.

Closing this issue.
