### ISSUE TITLE
[Bug] "This helps protect our community."

### ISSUE THREAD

**Issue by Ihate-g-i-t-hub** [iv-org/invidious#4968]
Hello,
Since this morning my self hosted Invidious instance has been having an issue where I continue to receive an error 500 with the message "Please Sign In". I am signed in, and I am unable to watch any videos. I am running the new inv_sig_helper as well. The error I'm receiving is happening as soon as I try to access any video, before the video is displayed. 

I am hosting my instance in a LXC container and is built from source. The only information I could find on this issue are old. I have included the logs from my service. I can provide more information on this issue as well. Thanks, and sorry if this is a known bug or issue.

**Describe the bug**
Since today when I try to watch anything on Invidious I am receiving an error asking me to sign in. I am already signed into Invidious.

**Steps to Reproduce**
Try and watch any video. The message on Invidious is "Please Sign In", however the server is returning an error 500. Looking at the Invidious logs I see that Youtube is returning a Please sign in request. I also see a warning about missing a translation key.

**Logs**
Oct 01 17:29:40 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:40 UTC [info] jobs: running ClearExpiredItems job
Oct 01 17:29:41 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:41 UTC [info] jobs: ClearExpiredItems done.
Oct 01 17:29:41 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:41 UTC [info] 200 GET /api/v1/auth/subscriptions 14.59ms
Oct 01 17:29:52 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:52 UTC [error] get_video: 0cRu98XSap0 : Please sign in
Oct 01 17:29:52 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:52 UTC [warn] i18n: Missing translation key "Please sign in"
Oct 01 17:29:52 Invidious-LXC invidious[2114680]: 2024-10-02 00:29:52 UTC [info] 500 GET /watch?v=0cRu98XSap0 282.32ms

**Screenshots**

**Additional context**
I have tried in Firefox and Chromium. I am running Linux as my OS.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734
