### ISSUE TITLE
[Bug] Google blocking videos again (please sign in)

### ISSUE THREAD

**Issue by mooleshacat** [iv-org/invidious#4972]
**Describe the bug**

It appears that it is possible YT stepped up it's game. Just now every video I click on shows the "please sign in" message. It was just working all day up until seconds ago.

Either that, or they've blanket blocked VPN services. My instance uses a VPN because otherwise they'd just ban my naked IP.

Update: it must be the VPN block because after switching around getting blocked still , eventually I hit a VPN IP in the US that works. Maybe the signature helper or po-token stuff needs to be looked at again, somehow I am being detected and blocked.

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Using invidious over VPN

**Comment by mooleshacat** [comment]
problem solved I guess

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/4734

**Comment by retrocaster** [comment]
@mooleshacat It's not a VPN block. The same thing happened to me starting today on my locally hosted private instance which is on a residential IP address from Xfinity.
