### ISSUE TITLE
[Bug] Please sign in. After which you should try to: Refresh, Switch Invidious Instance, Go to YouTube

### ISSUE THREAD

**Issue by Bubba8291** [iv-org/invidious#4976]
**Describe the bug**

At frequent occurrences, Invidious will give the error: `Please sign in. After which you should try to: Refresh, Switch Invidious Instance, Go to YouTube`

**Steps to Reproduce**

1. Click a video
2. See error

**Logs**

N/A

**Screenshots**

<img width="317" alt="Screenshot 2024-10-03 at 7 26 30 AM" src="https://github.com/user-attachments/assets/c08a41f4-7b97-4255-bcef-77e076447963">

**Additional context**

Self hosted instance

**Comment by Kirk1984** [comment]
I had the same issue. Renewing `visitor_data` and  `po_token` fixed it on my self hosted instance.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734

**Comment by fuckgfw00** [comment]
It was latest WEB_CREATOR merge casuse the issue.
