### ISSUE TITLE
[Feature request] Standalone lite mode/subproject

### ISSUE THREAD

**Issue by mrx23dot** [iv-org/invidious#4998]
I like this project, since Youtube ads are getting more aggressive by the day.
But finding Invidious instances is mandating, they get blocked, needs rotating, different UIs etc.

So my idea would be to break out the smallest viable player and be able to run it locally, 
like a single page webplayer playing only one url with basic controls.

Not sure what's the secret sauce in this repo to be able to to show. 

Or is there an alternative project that does this and still work?

Also don't really want to maintain/update an OS app like FreeTube.

**Comment by unixfox** [comment]
That's completely out of scope. You can enable `Thin mode` though in the preferences for having the lightest experience.

**Comment by Caian** [comment]
> I like this project, since Youtube ads are getting more aggressive by the day. But finding Invidious instances is mandating, they get blocked, needs rotating, different UIs etc.
> 
> So my idea would be to break out the smallest viable player and be able to run it locally, like a single page webplayer playing only one url with basic controls.
> 
> Not sure what's the secret sauce in this repo to be able to to show.
> 
> Or is there an alternative project that does this and still work?
> 
> Also don't really want to maintain/update an OS app like FreeTube.

You can do this with yt-dlp and vlc:

`yt-dlp --get-url -f b "https://www.youtube.com/watch?v=$1" | vlc -`
