### ISSUE TITLE
[Bug] Can't play Invidious VEVO music videos in Tor Browser, Firefox VEVO and non-VEVO Tor works fine

### ISSUE THREAD

**Issue by neelchauhan** [iv-org/invidious#5008]
Open this link (Chappell Roan "Hot to Go" VEVO video) in Firefox: https://inv.nadeko.net/watch?v=xaPNR-_Cfn0

The video plays as usual.

Try the above link or this onion link in Tor Browser: http://inv.nadekonw7plitnjuawu6ytjsl7jlglk2t6pyq6eftptmiv3dvqndwvyd.onion/watch?v=xaPNR-_Cfn0

It doesn't work. It gets stuck on an "The media could not be loaded, either because the server or network failed or because the format is not supported." error.

In comparison, this video works in Tor Browser: http://inv.nadekonw7plitnjuawu6ytjsl7jlglk2t6pyq6eftptmiv3dvqndwvyd.onion/watch?v=2RmUMmUj3u8

~~I'm not sure if this is a Tor issue or an Invidious one. Sadly, YouTube is now blocking Tor clients unless you sign in so Invidious is the only way to anonymously watch videos on Tor. I know a family member who's joining Google but I doubt she can help since I don't know her department.~~ It seems regular YouTube is unblocked on Tor, it was just some DoS attack via Tor relays earlier.

I'm on macOS 15 (Sequoia) on a MacBook Pro M3 14 36GB.

**Comment by neelchauhan** [comment]
This bug is also posted on the Tor GitLab here: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/43216

**Comment by unixfox** [comment]
Hello, this sounds like a codec issue. People have experienced codec issues with Microsoft Edge for example.

https://github.com/iv-org/invidious/issues/3966
https://github.com/iv-org/invidious/issues/4713#issuecomment-2135457950
