### ISSUE TITLE
Including Peertube and odysee search results

### ISSUE THREAD

**Issue by profdc9** [iv-org/invidious#5018]
The feature is to include Peertube and Odysee/lbry results to searches in invidious.  This way there are additional options when Youtube videos do not work, or at least would promote alternatives to Youtube.

**Is your feature request related to a problem? Please describe.**
The problem is the ongoing attempts of Google to prevent invidious from presenting Youtube content.

**Describe the solution you'd like**
Allow (perhaps optional) inclusion of Peertube/Odysee search results.

**Describe alternatives you've considered**
One can search these sources separately, but promoting these all in one place would pressure Google into being more open about their content.

**Comment by unixfox** [comment]
hello, unfortunately we don't have the time for such feature and invidious prefer to stay focused as being a proxy for YouTube only.
