### ISSUE TITLE
[Bug] Video specific caption fail

### ISSUE THREAD

**Issue by AresUII** [iv-org/invidious#5022]
To replicate:

1. Go to https://pol1.iv.ggtyler.dev/watch?v=nhxMvsHAqfw [or any other instance that plays the video].
2. Select English or German subs [others not tested].

The subtitles will not appear at all, and cannot be downloaded as a VTT file either.
The problem may occur with other videos [not verified]. Keep this in mind as the video will be gone in two weeks.

**Comment by unixfox** [comment]
Instance is probably missing the option https://github.com/iv-org/invidious/pull/4001
