### ISSUE TITLE
[Bug] Importing NewPipe exported zip, "Uploaded file is too large"

### ISSUE THREAD

**Issue by createchange** [iv-org/invidious#5023]
**Describe the bug**
I have exported my NewPipe data, and am trying to import to a self-hosted, Docker compose installed instance which is exposed only to my Tailscale network.

I was able to successfully import my subscriptions, but would like to import my playlists as I have built out a decent catalog of items. The exported zip file from NewPipe is 4.4MB. When attempting to upload into the Invidious importer, I receive the following log in the docker logs, as well as a corresponding one in the UI:

```
2024-10-25 03:36:00 UTC [warn] i18n: Missing translation key "Uploaded file is too large"
```

I don't know if the system resources I have provided to the Invidious instance would be relevant, but it should have plenty, since I had plenty to spare. It has 4 cores, 8GB RAM, and 50GB of storage.

**Steps to Reproduce**
1. Export modestly sized NewPipe zip
2. Attempt to import into Invidious

**Logs**
```
2024-10-25 03:36:00 UTC [warn] i18n: Missing translation key "Uploaded file is too large"
```

**Screenshots**
<img width="543" alt="image" src="https://github.com/user-attachments/assets/d70f1ce5-6f75-4ec7-9abe-fe749c1b2363">

**Additional context**
 - Browser (if applicable): Firefox
 - OS (if applicable): MacOS client, Debian host
 - NewPipe zip is 4.4MB

**Comment by ChunkyProgrammer** [comment]
There is a limit of 4mb files being uploaded. I'm guessing this is to prevent abuse (zip bombs?)

https://github.com/iv-org/invidious/blob/d8b893e9ad456598a3e127cec578dd3355141578/src/invidious/user/imports.cr#L298

It also doesn't look like there's any way to import playlists from NewPipe (yet) and invidious can only import watch history and subscriptions from NewPipe.

**Comment by createchange** [comment]
Ah thanks for finding that. It would be nice to have that be a configurable option, as I am the only one with access to my instance and I don't on zip bombing myself. I suppose I could just modify the source and build myself, as well. Regardless, it's a non-issue at this point, since importing playlists is not possible at present any way!
