### ISSUE TITLE
[Feature request] Tesla Webbrowser Compatible Audio Mode

### ISSUE THREAD

**Issue by Basti77** [iv-org/invidious#5041]
**Is your feature request related to a problem? Please describe.**
I want to use Invidious in my Tesla car. While it works well when the car is stationary, there's a cosmetic issue with the player lacking control icons for pause and restart. Additionally, for safety reasons, videos can only be watched when the car is not in motion, which I understand. However, the Audio Only mode is immediately interrupted when the car enters a driving mode, preventing continuous audio playback during the drive.

**Describe the solution you'd like**
I would like the Audio Only mode to be designed to function like a "real" Audio stream. This means that audio playback should continue uninterrupted even when the car is in driving mode, similar to how audio-only content from news sites like Tagesschau.de can be listened to while driving.

**Describe alternatives you've considered**
Currently, using the standard Audio Only mode stops playback when driving mode is engaged. As an alternative, accessing news websites that support audio-only playback allows for listening during drives, but integrating this seamless audio experience directly into Invidious would be more convenient and efficient.

**Additional context**
The issue is consistently reproducible on a Tesla with the current firmware version 2024.8.2. My Invidious instance is running version 2024.08.26-4782a67.
```

**Comment by unixfox** [comment]
That's probably a limitation of video.js. We provide the audio file to the browser and it play it. We don't do anything else.

Sorry we don't have the time to work on your feature request. Feel free to investigate and create a PR if you find something!
