### ISSUE TITLE
[Feature request] Stop promoting and discourage the use of public instances

### ISSUE THREAD

**Issue by pimlie** [iv-org/invidious#5047]
**Is your feature request related to a problem? Please describe.**

All the efforts that YT has started to put into blocking users using alternative front-ends the past year, might be for some part motivated because projects like invidious promote a list of public instances. This list of public instances are too easy to use and are direct competition with the YT website itself and therefore directly hurts YT income model as any person can publicly use a frontend that doesn't generate income for YT.

**Describe the solution you'd like**

- invidious should stop publishing a list public instances and just promote itself as a privacy focused frontend **for personal use**. That doesn't mean that it couldn't be used publicly, but the project itself should discourage it and when possible maybe even make it difficult and for certain shouldn't facilitate it.
- any features related to public instances (like switching to another public instance from a pre-populated list) should be removed. It should probably be ok for a user to specify a list of instances themselves they can switch between, but the invidious project shouldn't publish such a list and shouldn't allow such lists being shared on websites they control.
- moderators/contributors/members should actively discourage use of invidious as a public interface in github issues, matrix chat etc

**Describe alternatives you've considered**

n.a.

**Additional context**

Regardless of what anyone here thinks about YT and/or Google, we have to respect that they are a business, that running YT costs them a lot of money but that they are also mainly in it for their shareholder revenue. And especially a project like invidious that actively promotes public use as a custom frontend is a direct threat to that shareholder revenue. So that also makes it much easier for YT to justify allocating resources to blocking services like invidious.

Just making this issue as we have to realize that an increase in popularity of invidious (and other alternative frontends for that matter) due to the shitification of YT itself is a double edged sword. The more popular alternative frontends becomes, the more it hurts YT revenue so the more resources they will try to throw against it to prevent that loss of revenue.

**Comment by unixfox** [comment]
Invidious has always promoted both options, you have two buttons on https://invidious.io

Use or host invidious. Use gives you the public instance list and host gives you the installation guide.

I don't think we can't do much more clear.
