### ISSUE TITLE
[Question] New user about video clarity

### ISSUE THREAD

**Issue by beautygirl1998** [iv-org/invidious#5049]
First of all, thank you developers, this software is great. This is my first time using your service. When I browse youtube videos, there are no ads and the speed is very fast.

Today I built invidious according to the tutorial. I used the first recommended method, using docker to build it. Finally, the video can be played normally.

The problem I encountered is that although I have set DASH to be enabled by default and automatic in the configuration file, when I access invidious with a browser, the default video resolution is only medium. I have to reset the video resolution in the settings of invidious on the web page, and then there will be multiple video resolutions when returning to the video playback page, such as 1080, 1440p, etc. I think if other people use my invidious, they have to take a few more steps to set it up, which is not very convenient. If the configuration file can take effect, and other people including me can have multiple video resolutions when visiting invidious, I believe this will be a good user experience.

I don’t know if this problem is an official restriction of youtube, so I raised this question. Thank you again.

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

DASH only works with javascript enabled, make sure to have it enabled.
