### ISSUE TITLE
[Bug] "Request contains an invalid argument." when going to channels

### ISSUE THREAD

**Issue by LeNub64** [iv-org/invidious#5054]
a similar bug to this, but it effects all channel tabs im guessing.
https://github.com/iv-org/invidious/issues/5021

go to: https://yewtu.be/channel/UCkRfArvrzheW2E7b6SVT7vQ
and you should get 
"Could not extract JSON. Youtube API returned error 400 with message:
"Request contains an invalid argument."

screenshot:
<img width="568" alt="Screenshot 2024-11-06 at 5 46 19 PM" src="https://github.com/user-attachments/assets/845aac7c-5f5d-42b1-be91-8dd1c4387e0f">

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/5021
