### ISSUE TITLE
[Bug] i18n: Missing translation key "Please sign in"

### ISSUE THREAD

**Issue by Lyrics0811** [iv-org/invidious#5062]
When running Invidious in docker with the 'master' image I don't receive this error message, but receive a different one that was fixed in the 'latest' build.  When running the 'latest' build, I'm getting an error message about a "Please Sign in" for every video I try to watch.  I ran the helper and pasted the visitor_data and po_token in the docker-compose file but I'm still getting the error.  I've wiped my database, images and volumes but still am receiving it.  It's only me that uses it on a residential IP.

It looks like the fix for this may had been deployed here:

https://github.com/iv-org/invidious/issues/4734#issuecomment-2362314357

I was wondering if this was also applied in the 'latest' image, as I'm seeing it there but not in the master.

Logs
2024-11-08 19:58:31 UTC [error] get_video: FZzZatxb9KQ : Please sign in
2024-11-08 19:58:31 UTC [warn] i18n: Missing translation key "Please sign in"
2024-11-08 19:58:31 UTC [info] 500 GET /watch?v=FZzZatxb9KQ 73.72ms
2024-11-08 19:58:31 UTC [info] 200 GET /api/v1/trending 400.13ms

Current version: 2024.11.07-792d0d5 @ master

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990

**Comment by etbusch** [comment]
@unixfox This seems to only affect the master container version. If I rollback to latest, videos play normally again.
