### ISSUE TITLE
[Bug] "Please sign in"

### ISSUE THREAD

**Issue by zxcv05** [iv-org/invidious#5068]
**Describe the bug**

When trying to watch any video, the error "Please sign in" appears.

**Steps to Reproduce**

1. Click on any video
2. See error

**Logs**

No browser logs
journalctl: `2024-11-09 16:05:21 UTC [error] get_video: FYR5MIGI3f8 : Please sign in`

**Screenshots**

**Additional context**

I'm using firefox on linux
I'm using invidious version `2024.11.08-b173d4a @ master` (self hosted instance)
I have `po_token` and `visitor_data` set correctly

**Comment by zxcv05** [comment]
Im using the master docker image aswell if that helps

**Comment by unixfox** [comment]
Duplicate of https://github.com/iv-org/invidious/issues/4734
