### ISSUE TITLE
Watch on hooktube

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#507]
It would be nice to have a setting that let's you change the "Watch on youtube" link to "Watch on Hooktube" and direct to that website.

**Comment by omarroth** [comment]
Would you mind providing some rationale for preferring HookTube over Invidious, [CloudTube](https://cadence.gq/cloudtube/search), or YouTube itself?

My understanding is that HookTube uses the [standard YouTube embed](https://hooktube.com/changelog), uses the YouTube API, and is not fully open-source, so it doesn't appear to provide any advantages over the alternatives mentioned above.

See also FreeTubeApp/FreeTube#136.

**Comment by elypter** [comment]
oh, i dont prefer hooktube over invidio.us, i just prefer it over youtube as a fallback. i didnt know about couldtube which looks rather nice as well.

i thought about having other options. hooktube is a middle ground between invidio.us and youtube because of the embed. that's why i thought about it. btw cloudtube gives the user the choice between "watch on youtube" and "watch on invidio.us" i just find it a bit clunky that those buttons take up rather much space

**Comment by cloudrac3r** [comment]
Or a custom input field in preferences where you can list alternate sites like `https://youtube.com/watch?v=%id` where `%id` would be replaced by the server with the URL of the current video.

**Comment by PrestonN** [comment]
I feel like the reasoning of wanting to go to HookTube could be solved by simply providing the YouTube embedded player as was requested from #237.  URLs could provide a `?embed=true` to show the player.

**Comment by sergeevabc** [comment]
A powder room is still a toilet, let bygones be bygones.

**Comment by elypter** [comment]
there are things that invidio.us cannot provide in the near or mediate future. i want to use it as often as i can but in some occasions i still need a function that invidio.us cannot provide but an embedded player can. in that case a youtube embed is still better than visiting youtube. but even if invidio.us had a youtube embed there are still reasons to try out other sites.

**Comment by ealgase** [comment]
Which functions?

**Comment by jeroen7s** [comment]
@ealgase playback on Vevo video's: https://invidio.us/watch?v=Tztc73r8348

**Comment by ealgase** [comment]
Works for me.
