### ISSUE TITLE
[Bug] The media could not be loaded, 403 on arch linux only

### ISSUE THREAD

**Issue by fsoc** [iv-org/invidious#5091]
**Describe the bug**
I get the usual "The media could not be loaded, either because the server or network failed or because the format is not supported." in the GUI when I try to use a self-hosted docker container image on arch linux. 

It works well on ubuntu though, but not on 2 different machines running arch linux

**Steps to Reproduce**
From https://docs.invidious.io/installation/
1. Run docker run quay.io/invidious/youtube-trusted-session-generator
2. Paste in the values
3. Run docker compose
4. Try to view any video on the first page

**Logs**
```
403 GET /videoplayback?expire=1732480988&ei=fDtDZ_60OMWD0u8Pu7Ou-Q8&ip= ... VscnEbNEzquTktLwQPEG77rlTieTCKfjdz3mglOdYpBeML9g%3D%3D 161.94ms
```

**Additional context**

# Does not work, pc1
Docker version 27.3.1, build ce1223035a
running directly to localhost:3000

git repo hash: 98926047
    Release v2.20241110.0
Arch linux 6.12.1-arch1-1

# Does not work, pc2:
Docker version 27.3.1, build ce1223035a
running via nginx reverse proxy
git repo hash: 98926047
    Release v2.20241110.0
Arch linux 6.11.9-arch1-1

# Does work, pc3:
running via nginx reverse proxy

ubuntu 24.10
 
96c2999ef648   quay.io/invidious/invidious:latest
initiated from git repo @ v2.20241110.0, current
HEAD:98926047586154269bb269d01e3e52e60e044035

nginx config:
$cat /etc/hosts
127.0.0.1 foo

$cat /etc/nginx/sites-enabled/default
```
        server_name foo;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                proxy_pass http://localhost:3000;
        }
```
http://foo and http://localhost:3000 works well, I can watch videos!

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).
