### ISSUE TITLE
[Feature request] Increase avaiability by letting each client be an opt-in server

### ISSUE THREAD

**Issue by gustavonmartins** [iv-org/invidious#5093]
**Is your feature request related to a problem? Please describe.**
Since some monthes, most of invidious instance returns an error saying they are blocked or something similar. I access them via farside.link

**Describe the solution you'd like**
I understod this happens because youtube doesnt allow cloud-ips to download anymore.

I think an alternative is if each client could opt-in to be a small server in the network, instead of relying on invidious central servers, which often gets blocked by youtube.

Thus, I would propose that each person who would like to help would be able of logging in to youtube in a way which is not blocked, and while the person downloads the video, automatically the person becomes a supplier of the video, probably in a torrent-like, magnet links or some other P2P way.

In this way, invidious servers are not overloaded providing the videos, and everyone can serve the network even if they dont have a big server at home.

**Describe alternatives you've considered**
People could have their own servers at home, but its too much of a burden. Better would be if each client is also a small server, maybe a torrent server/seed.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/879
