### ISSUE TITLE
Is Youtube trolling Invidious users by playing a different Audio track?

### ISSUE THREAD

**Issue by kladderadeng** [iv-org/invidious#5096]
When I [play this Video](https://www.youtube.com/watch?v=2nYJiVQqhk0&t=12s) in my Invidious instance, that guy is talking Spanish / Portuguese or something like that and not English. On Youtube I get the original Audio track in English. Other videos in his channel are fine. This is the first time I see (hear) this and I wonder if this is just some very weird bug or if YT starts to troll Users not using the YT Web interface by mixing Audio / Video from different sources?
I do run Version 2024.11.10-5d2dd40 in Docker which works flawless for everything usually... but this is really odd.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
