### ISSUE TITLE
[Bug] Self-hosted instance: videos only load via http, not https via Nginx Proxy manager

### ISSUE THREAD

**Issue by pflavio** [iv-org/invidious#5100]
**Describe the bug**
When trying to watch videos on my self-hosted Invidous instance, I have to access it via IP:Port and cannot use a custom URL set via Nginx Proxy manager. When I do that, I receive the error "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Steps to Reproduce**
1. Go to 'http://myinvidiousinstanceip:3000' and watch any video -> works as expected
2. Go to 'http://myinvidiousinstance.myprivatedomain.com' and watch any video -> video won't load with error "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Logs**
I'm happy to provide any logs neccesarry, just tell me which ones.

**Screenshots**

**Additional context**

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).
