### ISSUE TITLE
[Bug] Missing hash key: "label" (KeyError)

### ISSUE THREAD

**Issue by ththt007** [iv-org/invidious#5103]
Title:Missing hash key: "label" (KeyError)Date:2024-11-27T12:51:24ZRoute:/search?q=interVersion:2024.11.10-5d2dd40 @ (HEAD detached at v2.20241110.0)`

**Comment by ththt007** [comment]
Title:Missing hash key: "label" (KeyError)Date:2024-11-27T12:51:24ZRoute:/search?q=interVersion:2024.11.10-5d2dd40 @ (HEAD detached at v2.20241110.0)`

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/5095
