### ISSUE TITLE
[Bug] Build failed: NilAssertionError compiling Invidious

### ISSUE THREAD

**Issue by pbreh** [iv-org/invidious#5104]
creation of a new VM with 20GB containing Debian 12
**sudo apt update
sudo apt upgrade
sudo apt install docker.io docker-compose
sudo systemctl start docker
sudo systemctl enable docker 
sudo docker run hello-world
git clone https://github.com/iv-org/invidious.git
cd invidious
sudo docker-compose up -d**
…
Checking player dependencies, this may take more than 20 minutes... If it is stuck, check your internet connection.
Resolving player dependencies
Fetched videojs-mobile-ui
Fetched videojs-http-source-selector
Fetched videojs-contrib-quality-levels
Fetched videojs-overlay
Fetched videojs-vtt-thumbnails
Fetched videojs-vr
Fetched videojs-markers
Fetched videojs-share
Fetched video.js

Done checking player dependencies, now compiling Invidious...
Unhandled exception in spawn: Nil assertion failed (NilAssertionError)
The command '/bin/sh -c if [[ "${release}" == 1 ]] ; then         crystal build ./src/invidious.cr         --release         --static --warnings all         --link-flags "-lxml2 -llzma";     else         crystal build ./src/invidious.cr         --static --warnings all         --link-flags "-lxml2 -llzma";     fi' returned a non-zero code: 137
ERROR: Service 'invidious' failed to build : Build failed

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).
