### ISSUE TITLE
[Bug] Videos playing with wrong default audio track

### ISSUE THREAD

**Issue by georgek** [iv-org/invidious#5105]
**Describe the bug**

Many videos I watch now seem to have an audio track dubbed into a language I can't understand. I don't even know what the language is, but oddly it often sounds like the same dude on the track. These are sometimes small channels I wouldn't expect to get translations, it's odd.

A few recent examples: zkRxfmECWSM, 9-Jl0dxWQs8, 3E5ZjfZAn6Y

No setting in Invidious seems to allow me to get the original English audio for these videos.

**Additional context**

Firefox/Linux

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007
