### ISSUE TITLE
[Bug] Degraded performance and "The media could not be loaded" error for all play attempts

### ISSUE THREAD

**Issue by retrocaster** [iv-org/invidious#5110]
Starting today, my private instance at my residential ip address running 2024.11.10-9892604 @ master is unable to play a single video. In the browser, every video play attempt results in this error: "The media could not be loaded, either because the server or network failed or because the format is not supported."

I have also noticed that general page load performance seems significantly worse for metadata, thumbnails, etc.

Everything was working fine yesterday, so I'm guessing something changed on Google's end.

**Comment by retrocaster** [comment]
No comment? Are you giving up on invidious @unixfox ?

**Comment by unixfox** [comment]
Just look at the pinned issues

**Comment by retrocaster** [comment]
Nah, it's just @unixfox being lazy.

These should have been referenced: 
https://github.com/iv-org/invidious/issues/5108
https://github.com/iv-org/inv_sig_helper/issues/36
