### ISSUE TITLE
[Question] Does invidious support unix sockets / systemd socket activation?

### ISSUE THREAD

**Issue by Caian** [iv-org/invidious#5111]
I'm changing some of my containers to use unix sockets for communication instead of networking for performance reasons, and I would like to know if invidious supports listening to a unix socket instead of a conventional IP:port. If it does, does it also support systemd socket activation to facilitate configuration?

Thank you, and thank you for the great project

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/2111

**Comment by Caian** [comment]
I'll take that as a no...
