### ISSUE TITLE
HTTP 403 from GET /videoplayback

### ISSUE THREAD

**Issue by GreNIX** [iv-org/invidious#5114]
It seems like the problem described below has happened several times, so I didn't want to open a bug ticket.  However, I don't see any open issues for this problem, so I wanted to get one going.

**Describe the bug**
Clicking any video results in the message "The media could not be loaded, either because the server or network failed or because the format is not supported." in the browser and `2024-12-15 02:48:50 UTC [info] 403 GET /videoplayback` in the Invidious container log. 

**Steps to Reproduce**
  1. Start Invidious services
  2. Navigate to Invidious in a browser
  3. Click a video
  4. Observe above-mentioned errors in browser and in container logs

**Additional context**
 - Browser (if applicable): Firefox
 - Container image version: quay.io/invidious/invidious:master-arm64   453d6343f22b

**Comment by unixfox** [comment]
You have to use potoken method and inv_sig_helper now.

**Comment by GreNIX** [comment]
I've had Invidous running in a docker compose configuration for months.  I followed the instructions when creating my setup, which included generating the potoken using the sig helper.  I pass the following into he container at run time, under the `INVIDIOUS_CONFIG` environment variable section:
```
visitor_data: <visitor data> 
po_token: <token>
```
This problem just started happening out of nowhere.  My Invidous container worked two days ago.  I then attempted to regenerate the visitor data and po token, just to ensure that it hadn't changed.  I got the exact same values when they were generated the second time.

**Comment by unixfox** [comment]
Ok. Could be that your IP is banned by youtube servers if you have setup everything well.

Is your IP from a datacenter or it is from your home network?

**Comment by unixfox** [comment]
Hello, we have created a dedicated page for this new error: https://docs.invidious.io/youtube-errors-explained/#videoplayback-urls-that-returns-403-http-errors

**Comment by GreNIX** [comment]
Did some digging about i see this error repeating from the sig helper container:

```
[2024-12-16T22:24:18Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-16T22:24:19Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
[2024-12-16T22:24:21Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
thread 'main' panicked at src/player.rs:185:10:
called `Option::unwrap()` on a `None` value
```

**Comment by unixfox** [comment]
> I am routed through a VPN, maybe they just started blocking its IP...
> 
> Did some digging around and I see this error repeating on the sig helper container:
> 
> ```
> [2024-12-16T22:24:18Z INFO  inv_sig_helper_rust] Fetching player
> [2024-12-16T22:24:19Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
> [2024-12-16T22:24:21Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
> thread 'main' panicked at src/player.rs:185:10:
> called `Option::unwrap()` on a `None` value
> ```

https://github.com/iv-org/inv_sig_helper/issues/41

**Comment by unixfox** [comment]
I'm going to lock this issue as it has been solved: https://github.com/iv-org/invidious/issues/5114#issuecomment-2545045973 and this issue is not a "support center". Please do your searches or join our matrix for asking questions.
