### ISSUE TITLE
[Enhancement] Token Update Helper for Invidious

### ISSUE THREAD

**Issue by D-Hunt3r** [iv-org/invidious#5117]
**Is your enhancement request related to a problem? Please describe.**
There is no automatic process to update the tokens automatically and periodically. 

**Describe the solution you'd like**
This is a script to automatically update tokens for invidious when it is hosted via the portainer stack.

**Describe alternatives you've considered**
Manually updating tokens

**Additional context**
https://gist.github.com/D-Hunt3r/c4287649e216482f575cb750d3991973

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/4985
