### ISSUE TITLE
[Enhancement] Add YouTube embed link to video error page

### ISSUE THREAD

**Issue by zopsicle** [iv-org/invidious#5119]
**Is your enhancement request related to a problem? Please describe.**

I'm always frustrated when visiting YouTube proper. When I have to watch a video on YouTube due to Invidious being unavailable, I prefer the embed page since it loads faster and shows no popups, comments, or other clutter.

**Describe the solution you'd like**

Add a YouTube embed link to the video error page, like so (suggested enhancement in **bold**):

> Error while communicating with Invidious companion: Read timed out
>
> After which you should try to:
>
> - Refresh
> - Switch Invidious Instance
> - Go to YouTube **(Embed)**

**Describe alternatives you've considered**

The user manually edits the URL in the address bar to be of an embed before YouTube finishes loading.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/pull/5003
