### ISSUE TITLE
[Question] About Instance Structure(endpoint)

### ISSUE THREAD

**Issue by Tenakskd** [iv-org/invidious#5127]
an invidious instance, when I access /latest_version?id=VIDEOID&itag=18, I am redirected to a low quality (480p)original video URL, but the Audio URL redirects to the original URL on which endpoint access? What endpoints do I need to access for the Audio URL to be redirected to the original URL? Also, where is the endpoint that redirects to the DASH quality (720p,1080p) video URL?

**Comment by unixfox** [comment]
Hello, I would suggest you to use yt-dlp for downloading videos: https://github.com/yt-dlp/yt-dlp

latest_version endpoint is not designed for this purpose.

And about the different itags you can find your answers in this source code file: https://github.com/iv-org/invidious/blob/master/src/invidious/videos/formats.cr
