### ISSUE TITLE
[Question] invidious video and audio Download ERROR.

### ISSUE THREAD

**Issue by Tenakskd** [iv-org/invidious#5128]
Bug.
In the instance of downloadable, select the video quality or sound quality, press download, and the words “please specify the itag and video id” will appear. So I want to be able to download it correctly.
<instance>
iv.duti.dev

browser- safari 
OS iPad OS 18.1

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious-companion/issues/13

**Comment by Tenakskd** [comment]
All download Button Not Working.
