### ISSUE TITLE
Closed caption and gear quality selector buttons not pressable on Android Chrome browsers

### ISSUE THREAD

**Issue by Pentaphon** [iv-org/invidious#522]
EDIT: Closed caption and gear quality selector buttons not press-able on Android Chrome browsers. They highlight blue but they don't actually pull up any menu or let you select different settings.

![Screenshot_20190507-203854_proc](https://user-images.githubusercontent.com/49374058/57347980-3d622f80-7109-11e9-8137-eeb5c794491d.jpg)

**Comment by omarroth** [comment]
You should be able to scroll along the control bar to view other controls, see #310.

**Comment by Pentaphon** [comment]
@omarroth Thanks. I didn't realize you can scroll. Only things left are that the closed captions and gear quality selector button do not work on Android Chrome browsers.

**Comment by Pentaphon** [comment]
As before to keep this from being closed...

> Only things left are that the closed captions and gear quality selector button do not work on Android Chrome browsers.

**Comment by syeopite** [comment]
Fixed by #2008
