### ISSUE TITLE
Selected quality is not displayed if default quality is set to dash

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#527]
If your default quality in preferences is set to dash and you watch a video first of all nothing is selected in the quality settings for the video

![Screenshot_20190511_161403](https://user-images.githubusercontent.com/26308977/57570957-f83f4580-7407-11e9-8408-dc74eef7e5ae.png)

Than if you try to select another quality in this menu, it gets changed but after clicking again on this menu still nothing is selected. If you select the same quality a few times it will be shown as selected.
I think it is easily to reproduce, if not I can create a video to show what I mean.

**Comment by omarroth** [comment]
I believe this is videojs-http-source-selector#7. As mentioned in the referenced issue, the quality is selected but the styling is not applied.

`auto` should be selected by default, although it won't be highlighted.

**Comment by leonklingele** [comment]
https://github.com/jfujita/videojs-http-source-selector/pull/33 should fix the issue (untested though).

**Comment by omarroth** [comment]
Should be fixed with 3de37a61c51e0fea89fdd9d5be713a82bb366da5, thanks @leonklingele!
