### ISSUE TITLE
[suggestion] search button

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#529]
it would be great to have a button that starts the search next to the search box. in some situations a pointing device is the easier choice and a button would allow this way of usage. maybe put it inside the text field like it is done with the firefox search box

**Comment by elypter** [comment]
this would still be a very welcome everyday life improvement. it should be easy to add. please dont throw this out

**Comment by viciousvex** [comment]
I have added a search button to the search_bar template and issued a pull request to here. My commit can be found here: https://github.com/iv-org/invidious/pull/4098
