### ISSUE TITLE
Add option to change video settings before start playing video

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#537]
Currently it is not possible to interact with the player settings before starting playing the video.
For example muting the video, enabling captions or changing quality/speed is not possible to change. You are basically forced to start the video first.

**Comment by omarroth** [comment]
I've looked around a bit and I don't believe this is possible with Videojs. The best I can find is https://stackoverflow.com/a/22974297.

**Comment by leonklingele** [comment]
https://github.com/omarroth/invidious/issues/670#issuecomment-518127360 would implement that.
