### ISSUE TITLE
Speed options with three digits do not fit into player layout

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#538]
Speed options with three digits do not fit into player layout, an example is below.
![Screenshot_20190519_123839](https://user-images.githubusercontent.com/26308977/57981059-1eca3580-7a33-11e9-832e-751b50182e3b.png)

**Comment by omarroth** [comment]
Appears as expected for me:
![image](https://user-images.githubusercontent.com/14208607/57982519-0eeb2b00-7a0c-11e9-9569-6d5c41c5a4bb.png)

Tested in Chrome and Firefox. Mind providing which browser and version you're using?

**Comment by Perflyst** [comment]
I am using Firefox in version 66.05
Can it be a special display resolution?

**Comment by omarroth** [comment]
Maybe, I'm having trouble replicating at 1600x900 on Firefox 67.0.

**Comment by PrestonN** [comment]
This happens on my machine.  It seems that a scroll bar appears on certain resolutions which messes with the formatting.  There seems to be a couple of ways to fix it but the quickest and easiest is likely removing the `overflow: auto` line from `.vjs-menu-content` in the video.js CSS
