### ISSUE TITLE
Feature Request: Add Plyr Video Player Option

### ISSUE THREAD

**Issue by trymeouteh** [iv-org/invidious#544]
https://plyr.io/

Plyr is a great video player with a nice UI and easy to use controls. I like using it on mobile devices and find it very user friendly.

I would prefer this over the current video player but I know some people will like the current video player over Plyr. I would to suggest to have them both and in the preferences you can choose which video player to use.

**Comment by omarroth** [comment]
Quite impressive list of features from a quick look. Unfortunately there's a couple plugins being used with Video.js that I don't see a good Plyr alternative for:

- [videojs-markers](https://github.com/spchuang/videojs-markers): Used to provide start and end markers for videos when using e.g. `&t=` and `&end=`.
- [videojs-youtube-annotations](https://github.com/afrmtbl/videojs-youtube-annotations): Used to provide legacy annotations (see #110, #303)
- [videojs-share](https://github.com/mkhazov/videojs-share): Used to provide links for email, twitter, reddit, etc. as well as code for embedding (although I wouldn't be surprised if this was something I missed from skimming through the README)

Overall I can see this being an improvement over the current player. Unfortunately I won't have time to look into this much more, but I'd happily look at any PRs adding support for it.

**Comment by elypter** [comment]
@trymeouteh maybe write a feature suggestion on plyrs github for what is missing if these things are not yet possible with plyr.

**Comment by trymeouteh** [comment]
I made a feature request for the video markers on Plyr github. The annotations are legacy if Plyr does not support them, those who want annotations should use the current player. The share button can be added outside the video player and I do believe you can add custom buttons within the player.

**Comment by Mennaruuk** [comment]
I'd hate for this feature request to be closed. It's such a good idea!! Plyr.io is a beautiful player. I understand the concerns, such as regarding legacy annotations (someone created [an issue](https://github.com/sampotts/plyr/issues/383) on it at Plyr's github but unfortunately it was closed.) I hope this can be implemented one day, it'd be a great step forward for Invidious!

**Comment by hackerncoder** [comment]
Annotations have been removed completely, so they are not a problem anymore.

**Comment by Mennaruuk** [comment]
Fan-made concept! (Ignore Firefox's PIP button.)
![4c56ffc5-1ee6-4049-9511-165cca5fa138 sketchpad-layerExport](https://user-images.githubusercontent.com/52135169/106398823-0d7db400-63e3-11eb-9440-7eb0ee84c706.png)

**Comment by Mennaruuk** [comment]
This is a good feature request.

**Comment by unixfox** [comment]
We can't support plyr until this issue is resolved: https://github.com/sampotts/plyr/issues/1455

**Comment by Mennaruuk** [comment]
Interesting. Do you know how [Invuedious ](https://github.com/bocchilorenzo/invuedious)does it? (If you get a connection error, just click the wench and select a working instance like invidious.osi.kr.)

https://bocchilorenzo.github.io/invuedious/watch/4q9o0-oPPTk

**Comment by unixfox** [comment]
They don't use dash, that's it. You can't go over 720p, so they don't offer dash which is a technology that mix both audio and video at the same time. That's what Youtube uses and if you want to watch 1080p+ videos you need to use dash.

More about dash here: https://docs.invidious.io/Geoblocking,-available-video-quality-and-DASH.md

**Comment by unixfox** [comment]
Closing as plyr is going to be abandonned: https://github.com/sampotts/plyr/issues/2408 and the successor only support the very latest version of popular browsers: https://github.com/vidstack/player#%EF%B8%8F-browsers so we don't really want to restrict the amount of people using Invidious.

**Comment by mihar-22** [comment]
Hey @unixfox just to clarify that on Vidstack we're not on the bleeding edge of modern browsers. Pretty much all numbers before our supported versions is `0.00%` (see [usage table](https://caniuse.com/usage-table)). This is the same support matrix we're using at Reddit, so it's unlikely you're supporting something we're not. Let me know what we're missing that you require.

**Comment by unixfox** [comment]
Hi @mihar-22. Thanks for your comment.

Our user base contains people that are using browsers that are not supported by www.youtube.com and thus use Invidious in order to still watch YouTube videos. This includes the browsers that are way older than the one listed here: https://github.com/vidstack/player#%EF%B8%8F-browsers

We also have users using forks of Firefox, one popular fork: https://www.palemoon.org/. Palemoon is based on Firefox 52.

Unfortunately, the usage statistics from caniuse doesn't represent the real user base of Invidious.
