### ISSUE TITLE
Auto - Quality 

### ISSUE THREAD

**Issue by CSDUMMI** [iv-org/invidious#548]
I have noticed that there is no auto-quality option that
would just display in the quality currently available
with the bandwidth of the user.
I think because this doesn't exist videos on invidious
play more stop & hop & stop.

**Comment by omarroth** [comment]
There should be a "auto" quality included as part of #34. I'm unfortunately having trouble understanding the second half of the issue but for pre-muxed sources I would like to keep user choice more explicit, since it's not as easy to swap out sources cleanly (e.g. without interruption).

**Comment by CSDUMMI** [comment]
Many videos I watch on invidious begin for a certain time and start loading again and then repeats.
And I don't see that there is automatic change of the quality or that such a option as auto in quality settings.

**Comment by omarroth** [comment]
If you have `dash` set as your default quality then there should be an "Auto" option.

**Comment by CSDUMMI** [comment]
Shouldn't `dash` be default in this case?

**Comment by omarroth** [comment]
It's a bit misleading, since DASH provides multiple qualities. When `dash` is set, a different set of qualities are displayed, with an "auto" option to choose between them.
