### ISSUE TITLE
Sync/backup playlist to Invidious

### ISSUE THREAD

**Issue by mascherone108** [iv-org/invidious#552]
Whenever a video is deleted from YouTube it leaves an unhelpful [Deleted video] in a playlist instead of at least giving us an idea what the video was called. This feature would basically just copy the playlist from YouTube to Invidious but whenever a video is deleted from YouTube, it would remain with its URL, name, author, etc. in the playlist on Invidious for people to see what the video was. Also IIRC it applies to videos that are made private too.

**Comment by Perflyst** [comment]
What does happen in a playlist on YouTube with such videos?

**Comment by omarroth** [comment]
YouTube still provides the video ID, so it may be possible to recover using something like #393. Otherwise expect this functionality to be added once #114 is implemented.

**Comment by KetchupEnthusiast** [comment]
@Perflyst the playlist just skips the video
@omarroth thank you
