### ISSUE TITLE
preferences question & suggestions

### ISSUE THREAD

**Issue by practik** [iv-org/invidious#563]
I've been having fun trying out Invidious; thanks for making and running and maintaining it!

I have a question and a few suggestions about the preferences. First, what’s the difference between “Play next by default” and “Autoplay next video”? They sound like the same thing to me, but I see that my prefs cookie includes both `continue` and `continue_autoplay` – ??

The second of those was missing from https://github.com/omarroth/invidious/wiki/Preferences, by the way. I added it, along with `annotations`, `annotations_subscribed`, and `local`, but I'm not sure I put everything in the right place, so you might want to check my edit. I also added some more descriptions and changed the pref values to match them.

Last but not least, I'd change some of the preference titles on https://www.invidio.us/preferences to make them a bit clearer and/or shorter:
- Change “Listen by default” to “Audio-only mode.”
- Change “Proxy videos?” to “Proxy videos:” and “Show related videos?” to “Show related videos:”
- Change “Show annotations by default?” to “Show annotations:”

**Comment by omarroth** [comment]
`continue` and `continue_autoplay` could probably be better worded. `continue_autoplay` will automatically add `autoplay=1` (if not already enabled elsewhere) when watching playlists or when `Up next/continue` is enabled. I'd recommend taking a look at #268 for the reasoning behind this. `continue` is the same as YouTube's `Up next` functionality.

Changes look good, thanks! You might also take a look at [List of URL parameters](https://github.com/omarroth/invidious/wiki/List-of-URL-parameters) for a little more explanation of some options.

Main reasoning for questions as preferences is to have the checkbox serve as an answer, so for example `Proxy videos? yes (checked)`. @dimqua or @comradekingu may have some thoughts on this.

I'd rather keep `by default` in preferences to prevent confusion between those settings as they appear on the watch page, although I'd also be curious to hear thoughts on this as well.

**Comment by practik** [comment]
> `continue` and `continue_autoplay`

OK, I'm starting to get it now after playing around with the different permutations. `continue` loads the next video when the current video finishes, but does not automatically start playing it unless `continue_autoplay` (or `autoplay`) is also enabled.

Logically it's a bit inelegant, though, because there are two pairs of combinations that produce the same effect:

`"autoplay":true` + `"continue":true` + `"continue_autoplay":true` =
`"autoplay":true` + `"continue":true` + `"continue_autoplay":false`
(video 1 autoplays, video 2 autoloads & autoplays)
 
`"autoplay":false` + `"continue":false` + `"continue_autoplay":false` =
`"autoplay":false` + `"continue":false` + `"continue_autoplay":true`
(click to play video 1, click to continue, click to play video 2)

It would make more sense, at least to me, to combine `continue` and `continue_autoplay` into a single pref with three options: "Continue to next video," "Autoplay next video," and "Do not continue."

But if you'd rather keep it as two separate preferences, then I'd change the name of 'continue` to "Continue to next video" – it's the word "play" in the current name of that pref that was tripping me up.

**Comment by comradekingu** [comment]
_"Proxy videos" Does that mean cache/buffer? Still a bit technical._
"Prefetch videos" or "Prefetch next video" is at-least a bit simpler.

_"Continue" is not necessarily the same as "enqueue"_

"Skip to" to go directly, and "enqueue" to add to playlist?

**Comment by practik** [comment]
> Main reasoning for questions as preferences is to have the checkbox serve as an answer

I get that; it's just that most if not all of the other preferences could work that way too – "Always loop?" "Autoplay?" etc. – but instead of question marks they have colons. That invites users to wonder, if only unconsciously, why there's a difference. Better to make it consistent – so if you like the question marks, how about giving them all question marks?

**Comment by comradekingu** [comment]
It doesn't need to have a questionmark, it can be assertive, like a button, whether immediate or not.

**Comment by practik** [comment]
> I'd rather keep by default in preferences to prevent confusion between those settings as they appear on the watch page

You are blowing my mind :-)  I was assuming that the settings on the watch page were just another way of accessing the corresponding settings on the prefs page.  I see now that they're two different things, and now I understand why you included "by default."

**Comment by practik** [comment]
@comradekingu, I don't mean to keep you from going to bed, you can just ignore my comments till tomorrow :-) But I like your no-punctuation option too:

> Autoplay [x]

The important point for me is just that all the prefs should have the _same_ punctuation unless there's a good reason for them to be different. Otherwise the differences create the appearance of meaning but don't actually have meaning, which is distracting for users. In this case it's a very minor distraction, I freely admit – but the principle is still a good one.

**Comment by practik** [comment]
> "Proxy" has a very specific meaning … hopefully it's possible to provide a much more concise explanation

I've been thinking about this too, but so far I got nothin'. Proxying just seems like too complex a concept to boil down to anything else. Hover text might be the best answer.

> "Queue next video"?

Aren't they already queued just by being lined up below the current video? In fact, I'd say that when the current video ends and the next video loads, at that point the next video has moved _out_ of the queue – so "Queue next video" seems like almost the opposite of the right description. Or at least that's how I see it.

**Comment by practik** [comment]
Circling back to this question (quoting myself here):

> there are two pairs of [preference] combinations that produce the same effect … It would make more sense, at least to me, to combine `continue` and `continue_autoplay` into a single pref with three options: "Continue to next video," "Autoplay next video," and "Do not continue."

I have a better idea, actually: Change the behavior of `continue_autoplay` so that it causes the next video to autoplay in all cases – both when Invidious is set to autoload the next video after the current video finishes (as the pref does now) _and_ when the user manually loads the next video by clicking on its thumbnail. In other words:

`"autoplay":false` + `"continue":false` + `"continue_autoplay":false` =
click to play video 1, click to continue, click to play video 2
`"autoplay":false` + `"continue":false` + `"continue_autoplay":true` =
click to play video 1, click to continue, video 2 autoplays

That would resolve one of the two redundant preference combinations, and it would also provide a new viewing mode that's currently not available, but which I, for one, would like. Instead of an automated playlist, I often use the "up next" videos as an array of options to choose from when the current video finishes – so when I click on one, it's because I want to play it, not just load it. I suspect I'm not the only person who uses YouTube that way.

**Comment by omarroth** [comment]
To clarify: `continue_autoplay` would essentially add `autoplay=1` (if not already enabled) to any other video on the page, or only recommendations?

**Comment by practik** [comment]
Hmm, I'm not sure. What other videos might be on the page? The pages I've seen just have the current video and the "up next" list – or am I forgetting something?

**Comment by omarroth** [comment]
The description and comment section can also include video links. I think it makes sense to only add it to the recommended since as mentioned it is used much more as a queue than either of the above mentioned.
