### ISSUE TITLE
Suggestion: Domain Name

### ISSUE THREAD

**Issue by trymeouteh** [iv-org/invidious#574]
invidio.us is not a bad one but I did a quick search and invidious.tv is available and is not too expensive. I think this would be a better domain name for invidious since it is a YouTube front-end. I am not suggesting replacing invidio.us with invidious.tv and I do not thing invidious needs several domain names but invidious.tv maybe a good domain name to use.

**Comment by omarroth** [comment]
Maybe as a redirect to https://invidio.us?

**Comment by trymeouteh** [comment]
A redirect will work too! To have two websites being hosted is unnecessary. One of the domains should be a redirect.
