### ISSUE TITLE
Show game/tags of video

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#581]
Currently Invidious shows a Genre. On YouTube you can also select a Game for a video. Would be nice if the selected game would be linked on Invidious too

**Comment by omarroth** [comment]
Is there any other metadata that's provided under videos that Invidious should handle? From a quick look it appears some videos also provide "Music in this video" ([example](https://www.youtube.com/watch?v=QnvSEBVkDF0) from the `Gaming` page).

**Comment by Perflyst** [comment]
I don't know of any other. Maybe Invidious could also show the video tags?
