### ISSUE TITLE
Keep last search term

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#584]
YouTube keeps the last search term in the input field after clicking on a video. This can be useful from time to time. Maybe Invidious could support this too?

**Comment by elypter** [comment]
this is useful however what i dont like is that it stays in the video url.

**Comment by Perflyst** [comment]
Does YouTube has it in the video url? Dont think sk

**Comment by omarroth** [comment]
I'm not quite sure how this could be implemented without putting the query in the URL. Testing with YouTube, this appears to only work when using the polymer redesign, which allows for a page "refresh" while still persisting data.

**Comment by elypter** [comment]
while not quite the intended use case for a cookie it could be used to save temporary information as well
