### ISSUE TITLE
Feature request: Share at current timestamp link

### ISSUE THREAD

**Issue by tuxayo** [iv-org/invidious#586]
From https://github.com/omarroth/invidious/issues/564#issuecomment-499152471

**Comment by tuxayo** [comment]
Circumvention: doing it manually (didn't notice that it actually works!!!) by appending ''&t=185s'' to the URL. In this case it starts at 3:05

**Comment by elypter** [comment]
you can also do &t=3m5s

**Comment by tuxayo** [comment]
Another syntax works
`&start=4m2s`

**Comment by elypter** [comment]
the end attribute works as well &start=1m1s&end=2m2s

**Comment by cauebs** [comment]
This is still relevant.
