### ISSUE TITLE
Feature Request: Mastodon Comments

### ISSUE THREAD

**Issue by linuxr01** [iv-org/invidious#594]
Is it possible to make feature that allow mastodon comments?

**Comment by omarroth** [comment]
Is there a good way to discover comments on Mastadon for a given video? There's a [`/api/v2/search`](https://docs.joinmastodon.org/api/rest/search/) (which requires authentication), but my understanding is that would only search one instance.

**Comment by tleydxdy** [comment]
I think they means commenting with a fedi account like ones peertube has

**Comment by omarroth** [comment]
@linuxr01 Would you mind expanding a bit more on the requested functionality and what would be required for this feature to be implemented (e.g. #264, #364)?

**Comment by linuxr01** [comment]
Thak you for your answer! Yes is like tleydxdy suggests. Like peertube.
