### ISSUE TITLE
Audio only mode (listen=1) not working for livestreams

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#597]
Audio only mode still plays the video of the livestream, example:
https://invidio.us/watch?v=Wl2mrlhE5Ww&listen=1

**Comment by omarroth** [comment]
Currently I'm not sure if it's possible to provide only audio-only streams using the current player. It might make more sense to instead hide the "Audio mode" button if the video is a livestream.

**Comment by ubone** [comment]
this is not a bug as yt live streams don't have audio only source
