### ISSUE TITLE
Feature Request: Mark video as watched after X duration or play button is clicked

### ISSUE THREAD

**Issue by tmiland** [iv-org/invidious#607]
~~Unwatched embedded videos from a web page is showing up in watch history.~~
*Solved

**Comment by omarroth** [comment]
Currently a video is marked as watched when it's requested (mentioned briefly in #129), so I would consider this expected behavior.

Maybe it would make more sense to only mark videos as watched when they're requested from `/watch?v=`?

**Comment by tmiland** [comment]
> Currently a video is marked as watched when it's requested (mentioned briefly in #129), so I would consider this expected behavior.
> 
> Maybe it would make more sense to only mark videos as watched when they're requested from `/watch?v=`?

Aha, i see. Took me a while to figure out why i had videos in my watch history i had no idea where came from 😅 

Is it possible to mark it as watched after play button is clicked? Think that would make more sense. 

Right now, f.eks scrolling down the feed on Reddit, puts all videos embedded in watch history, where most of them i scroll past.

**Comment by omarroth** [comment]
> Is it possible to mark it as watched after play button is clicked? Think that would make more sense.

I agree. Where possible though I would like to avoid using JS, which appears necessary for the above suggestion.

Just pushed 775612ec5a90c4ed4047c0c73e6f73c30abd509a, which will no longer add a video to a user's watch history if it is an embedded video, which I think closes this. I would however be interested in discussing this in either a new issue as an enhancement, or renaming this to a feature request for the proposed change.

**Comment by tmiland** [comment]
> I agree. Where possible though I would like to avoid using JS, which appears necessary for the above suggestion.

I understand. 

Would it be possible to use duration? Like one has to watch the video for X minutes, then it's marked as watched?

Might make it more complicated to implement though.

> Just pushed [775612e](https://github.com/omarroth/invidious/commit/775612ec5a90c4ed4047c0c73e6f73c30abd509a), which will no longer add a video to a user's watch history if it is an embedded video, which I think closes this. I would however be interested in discussing this in either a new issue as an enhancement, or renaming this to a feature request for the proposed change.

Thank you! Much appreciated :+1: 

I'll rename this one.
