### ISSUE TITLE
Invidious does not seem to handle videos with explicit geographic blocks

### ISSUE THREAD

**Issue by CuloArdido** [iv-org/invidious#618]
I have found some videos that from YouTube show the following message:
```
The uploader has not made this video available in your country.
```
It would be expected that Invidious at least show the same error but instead it takes a long time to load (like about a minute) and usually showing the following message:
```
504 Gateway Time-out
The server didn't respond in time.
```
The same happens when you add &local=true at the end of the link and when you try to check some of the videos from the [API](https://github.com/omarroth/invidious/wiki/API#get-apiv1videosid). Below I leave the videos that are causing this:
invidio.us/watch?v=2r-hcnoeYTM
invidio.us/watch?v=uuVqfJnvo0U
invidio.us/watch?v=Z-aLRRLgR3A
invidio.us/watch?v=qod7acTV7H8
invidio.us/watch?v=A-mjDxznYbE
invidio.us/watch?v=FVgV8DpErQk
invidio.us/watch?v=4P7zLp0S9QM

**Comment by omarroth** [comment]
See also #92.

Invidious will attempt to bypass region blocks by cycling through a list of proxies, which I expect is why it appears to be taking a while to load. In most cases it should show the above error message if it is not able to get a good response.

I'm not sure there's a good solution for this. The best would probably be to reduce the list of regions that Invidious checks, but that obviously reduces the number of videos that can be made available.

**Comment by CuloArdido** [comment]
>In most cases it should show the above error message if it is not able to get a good response.

Doesn't it happen when Invidious doesn't find a country where videos aren't blocked? Because those that I put above are from [this channel](https://invidio.us/channel/UCCd-tCMNh_KaHlhd-_cvmPQ) and many of them have a more "normal" block indicating that they can only be seen in some Southeast Asian countries (in these it is possible to see them by adding local = true in the link).
Since there is no obvious way to determine the countries where these videos can be viewed, it occurs to me that one way to deal with that could be by showing to the user a page like this:
```
We're sorry but we could not find a valid proxy for this video with geo-blocking. If you know in which country it is possible to see it, select it below:
<select>
		<option value="" disabled="" selected="">All countries in the world (or at least those with available proxies)</option>
</select>
<input value="Try again" type="submit">
```
If the chosen country makes it possible to watch the video then it could be saved in the database of the site to make it easier for other users to see the same video, otherwise the page already described could be shown again.
