### ISSUE TITLE
Add copy-able link to broken embeds

### ISSUE THREAD

**Issue by jones137** [iv-org/invidious#626]
If a specific embedded video is not supported by Invidious, only this text appears:
`The media playback was aborted due to a corruption problem or because the media used features your browser did not support.`
You have to mess around with finding frame source URL to be able to copy the link and try to download it with "youtube-dl" or even go directly to YT to be able to watch such broken video. I suggest you added, under the error output, a selectable link or a button with video's URL so that you can easily copy it and try to watch it outside of Invidious.

**Comment by omarroth** [comment]
Related: #593.

**Comment by gloschtla** [comment]
I opened an extra issue for this error message here on Github: 
https://github.com/omarroth/invidious/issues/931
