### ISSUE TITLE
Minify video player on scroll down

### ISSUE THREAD

**Issue by trosel** [iv-org/invidious#631]
Minify the video player when a user scrolls below to read comments etc

Behavior is described in [this tutorial](https://webdesign.tutsplus.com/tutorials/how-to-create-a-sticky-floating-video-on-page-scroll--cms-28342) and this [jwplayer guide](https://developer.jwplayer.com/jw-player/demos/advanced/minimize-and-float-video-on-scroll/)

I believe the scroll listeners would need to be added to this watch page  https://github.com/omarroth/invidious/blob/master/src/invidious/views/watch.ecr or this player component https://github.com/omarroth/invidious/blob/master/src/invidious/views/components/player.ecr

**Comment by Perflyst** [comment]
Could be a part of #583

**Comment by Mennaruuk** [comment]
If this ever gets implemented, it’d be cool to have a button for it, like with YouTube. But generally mini player is for multitasking, such as searching for another video while watching the current one in mini. So I’m wondering how one can do a new search that’d refresh the page while the mini player keeps going. Is this possible without JS?
