### ISSUE TITLE
Make a dropdown menu for changing instances 

### ISSUE THREAD

**Issue by R0sinenb0mb3r** [iv-org/invidious#637]
Still have network problem sometimes with some instances (also invidio.us) from good ol' germany. Would be great, if you could implement a dropdown menu on the left side, to change the instance for the same video (at same time position?).

In future it could be important to see the same video delivered from other sites than youtube - when they keep on moving on the censorship road like now.

Somedays: Blockchain plattform integration? Just thinkin'!

**Comment by omarroth** [comment]
See also: #414, #479.

**Comment by Perflyst** [comment]
For this kind of feature the API should also difference between online and offline instances (and maybe also latency).
