### ISSUE TITLE
Option to chose default dash quality

### ISSUE THREAD

**Issue by atahanacar** [iv-org/invidious#646]
The "auto" function is good, but not enough for all use cases. Adding a default quality option to dash would solve a lot of issues. For example, if I want to limit the quality to 480p because of, say, limited data, or to 720p because the monitor itself is 720p, "auto" allows me to do neither. This option would also be good for when "auto" gets buggy because of non-stable net speed.

**Comment by rezad1393** [comment]
I need this too.
the non-dash options are limited but dash option doesnt have a preset quality that user can select.

**Comment by unixfox** [comment]
bump still interested
