### ISSUE TITLE
Footer font color is hard to read when using Dark Mode 

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#672]
In my opinion the color of the font used in the footer is a bit too dark when using dark mode, I don't personally have a problem to read it but I guess it might be better to have a lighter color for people with vision problems.

White would be too "visible" so I guess using a color a bit darker than the one used for the "normal" text (#a0a0a0) would be the way to go.

![footer](https://user-images.githubusercontent.com/47571719/62502877-366abc00-b7e1-11e9-81f2-902997eb4860.png)

**Comment by TheFrenchGhosty** [comment]
Still an issue.

**Comment by saltycrys** [comment]
The color can be adjusted in `default.css`: https://github.com/iv-org/invidious/blob/e036d89a86cb7ab2d65ec2a9c3ea654c9774e70e/assets/css/default.css#L283-L287

**Comment by TheFrenchGhosty** [comment]
bump

**Comment by le-jun** [comment]
Let’s use this opportunity to tackle the interface accessibility question at the same time. According to W3C, the contrast between text and background should be at least 4.5:1 (AA level) and 7:1 (AAA level). Only modifying the text colour (no text size nor background change), then we could use:

* #adadad (7:1)
* #8a8a8a (4.55:1)

Ratio measured using [this tool](https://juicystudio.com/services/luminositycontrastratio.php#specify)

**Comment by ahangarha** [comment]
This issue is already resolved. I see good contrast in dark mode.

**Comment by TheFrenchGhosty** [comment]
@ahangarha No it isn't resolved.

**Comment by ahangarha** [comment]
Based on my test on yewtu.be and invidious.snopyta.org, the contrast between text and background color in the footer and dark mode is 4.99 AA. It is a good contrast.
