### ISSUE TITLE
Short video description (button "show more")

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#677]
Invidious currently shows the full description and with a very long description this does not look very nice by default.
YouTube has this feature to expand a description, would be nice to have this in Invidious too.

**Comment by sh4dowb** [comment]
I am working on this

**Comment by elypter** [comment]
could you please add an option in the settings to always expand the description? in the case i scoll down to read the comments i always read the description before anyway. so its a unneded click every time
