### ISSUE TITLE
Display own username if logged in

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#689]
Currently nowhere in UI is the own username shown. It should be displayed somewhere.

I would like some greetings, e.g. "Welcomer user" or similar as google has

**Comment by trymeouteh** [comment]
Please make this optional by adding a setting to enable/disable this. I like to share my screen when on invidious and would like to keep my username anonymous.

**Comment by makos** [comment]
Will work on this, I haven't seen your comment here.

**Comment by makos** [comment]
@trymeouteh is this (4d6b6f4) what you had in mind? You can find the new option in Preferences, under Visual Preferences.
