### ISSUE TITLE
Link to channel directs back to home page

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#703]
when clicking this [link](https://invidio.us/channel/UCGHZpIpAWJQ-Jy_CeCdXhMA/featured?&ab_channel=CoolWorlds) instead of showing the channel i just get the default page. removing the part of the url after the channel id makes it behave normally

**Comment by omarroth** [comment]
`/featured` is currently not supported, I expect it will be added as part of #483.

**Comment by elypter** [comment]
i dont think /features is really the problem. the channel would display just fine if that information was just ignored
