### ISSUE TITLE
Video stats: show  cumulative views / hour info

### ISSUE THREAD

**Issue by corona-nova** [iv-org/invidious#706]
in the video stats field, 
an average # of views / hour field , might show how viral a video is
and may be less age-skewed than view-count,  

it might be noisy and behave non-linearly over time, but it's another metric

also any thoughts on also showing age (days or weeks) of video
so don't have to recalculate and deal with mixed-units (months, non-decimal, offsets)

**Comment by TheFrenchGhosty** [comment]
From what I know it's impossible to have accurate data about the numbers of views in X time since YouTube count this data internally but display it later (making time-accurate stats impossible)

**Comment by corona-nova** [comment]
maybe do something similar to the wilson's score, or
show more decimal-places as the video gets older

also whether to indicate the about of uncertainty

the rating and other stats also oscillate (maybe not as much over time)
something that a line graph-over time might show
but don't know if it 's feasible

but if the precision is better than approx 10% 
it should be able to differentiate between videos
