### ISSUE TITLE
import youtube subscriptions OPML file: Loading...!

### ISSUE THREAD

**Issue by gloschtla** [iv-org/invidious#716]
I have a OPML file with merely [999 youtube channel subscriptions](https://duckduckgo.com/?q=youtube+limitation+channel+subscriptions+1000). How long will it take to import this file into invidious? Now it has been loading for at least 10 minutes, and the address contains no referrer ID: https://invidio.us/data_control?referer=%2F

**Comment by gbraad** [comment]
It finishes for me, but never shows any imported subscriptions.

The page https://www.youtube.com/subscription_manager says I have 715 Subscriptions, and the file is about 105KB big (non-malformed OPML).

**Comment by gbraad** [comment]
I just split my subscriptions and it seems to be related to the size. I just imported 10 channels, and this took about 2 minutes,
