### ISSUE TITLE
Cursor and bar won't hide.

### ISSUE THREAD

**Issue by atahanacar** [iv-org/invidious#718]
After updating to the latest commit from commit 3de37a61c51e0fea89fdd9d5be713a82bb366da5, the bar and cursor won't auto-hide. This almost always happens after I try set the quality. Sometimes the quality menu closes itself before I can set it, and after that this bug happens.

**Comment by omarroth** [comment]
I'm having trouble reproducing this. What does `./invidious -v` look like? Which browser are you using?

**Comment by atahanacar** [comment]
I'm on Firefox. Also, I've reproduced it wrong. The menu doesn't have to close itself for the bug to exist. Works on both dash and other qualities. I will add the output when I have ssh access.

**Comment by atahanacar** [comment]
How do I run `./invidious -v` on docker?

**Comment by atahanacar** [comment]
One more thing I noticed: After the bug happens, I can't use the space key on search bar unless I refresh the page.

**Comment by Mrfiregem** [comment]
I have this problem on https://invidious.snopyta.org videos when I change dash quality. It does go away if I reload the page and don't change quality, but when I do that, video quality degrades after a moment and it becomes too low quality to watch without changing. That's a separate issue from this, however.
Haven't tried this on other mirrors, but this has been happening only fairly recently

**Comment by atahanacar** [comment]
The issue is still present after 553d52a45e018bbfc4948e8a61411d9449cbbab4. The only way to reproduce is to change quality.

**Comment by unixfox** [comment]
Still having the issue. It's quite annoying that when the video quality degrade I force it to 1080p but then the bar doesn't hide itself.

**Comment by unixfox** [comment]
bump

**Comment by atahanacar** [comment]
bump

**Comment by unixfox** [comment]
I know this bug is fixed in videojs 7.17.

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/1263
