### ISSUE TITLE
Processing videos in Subscriptions page

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#719]
I have noticed that Processing videos (ones with a ... image) are showing in the Subscriptions page (an example is a Playing with Pasta video made by ThreadBanger).

**Comment by Zero3K** [comment]
*bump*

**Comment by SamantazFox** [comment]
@Zero3K  could you provide a screenshot of the issue if that still happens?

**Comment by unixfox** [comment]
Closing due to a lack of replies and procedure to reproduce the issue.
