### ISSUE TITLE
Don't show videos that have been deleted by the user

### ISSUE THREAD

**Issue by paulaime** [iv-org/invidious#726]
Currently, Invidious show all the videos of the channels I'm subscribed, even the ones that have been deleted by the user (see screenshot, when I click on a video without a thumbnail, I have the message “This video has been removed by the user”). It's useless and adds clutter, so it could be a good thing to find a way to hide them (like on YouTube).

![](https://user-images.githubusercontent.com/51381451/63766860-61ba6580-c8cc-11e9-888d-923a0783dc98.jpg)

**Comment by elypter** [comment]
i think it is important to show these. you can look for the video title elsewhere, you know that something is missing for whatever reason

**Comment by paulaime** [comment]
> i think it is important to show these. you can look for the video title elsewhere, you know that something is missing for whatever reason

I don't really see why it's relevant to show deleted videos since they've been, well… deleted.
When you look at my screenshot, you can see that there's the same video showing up 7 times (probably because the user had some issues posting it to YouTube) and it's pretty useless and irrelevant.
We could at least add an option in the settings to hide them.

**Comment by Seneral** [comment]
Another way I could think of is to check the thumbnail.
I know that these grey placeholders, while loaded in place of the expected thumbnail, do in fact throw a 404 (I use that fact to have a fallback, load maxresdefault in an object and nested in that another object with hqdefault, which always exist). Might be able to do something similar with object.onerror?
