### ISSUE TITLE
add Share button for PWA users

### ISSUE THREAD

**Issue by Duckbilled** [iv-org/invidious#741]
Using invidious as a PWA on iOS I am not able to share a video, because there is no share button.  Because it behaves like an app the Safari sharing buttons are hidden and thus there is no way to share it. I would love to see a small share button on the video's page. 

Ps. I saw in another topic #461 there is a share button in the video player, but this is not included in the mobile (at least iOS) player.

**Comment by elypter** [comment]
maybe use a better browser

**Comment by omarroth** [comment]
Would you mind including a screenshot of the player on iOS? You should be able to "scroll" horizontally to view the fullscreen and share buttons if they overflow.

**Comment by Uffje** [comment]
When I use it in the web browser it does, but I added invidious to my home screen so it becomes a PWA. Then it doesn’t work. 

I’ll add a picture soon.
