### ISSUE TITLE
[Bug] New videos don't show up in subscriptions feed

### ISSUE THREAD

**Issue by paulaime** [iv-org/invidious#746]
I'm using Invidious daily to watch videos, but for a couple of days now, new videos don't show up anymore in my subscriptions feed. The last video is from two days ago, but I tested with FreeTube and there are dozens of videos from channels I'm subscribed to that have been released since. Am I the only one that's having this issue?

**Comment by bam2000** [comment]
same problem here, my subscriptions are no longer updating on the official Invidio.us page
