### ISSUE TITLE
Deleted videos in playlist stop playlist

### ISSUE THREAD

**Issue by Wuzzy2** [iv-org/invidious#748]
If you playback a playlist and the playlist reaches a deleted video, there will just be a message that the video is gone with a short reason.
What's annoying about this that I feel the interface misbehaves:

- The auto-playback of the playlist stops. If your playlist hits a deleted video, you have to manually click back on the browser and manually select the next non-deleted video... Really annoying. :(
- The playlist is not displayed anymore

I suggest:

- If in a playlist with auto-playback, automatically skip all deleted videos
- If you selected a deleted video in a playlist (explicitly!), display the playlist in a way that looks exactly like a normal video
- In general, for deleted videos, make the entire page design look mostly like a normal video to advoid disrupting the user flow

**Comment by omarroth** [comment]
Should be fixed with 46a737c7a1c301ee9ed1634a916dc841544e72c9.
