### ISSUE TITLE
Add option to disable or modify privacy policy

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#757]

**Comment by Booteille** [comment]
I am curious about why you are willing an option to disable it.

**Comment by Perflyst** [comment]
I rather want one central privacy policy than a privacy policy on each single service site. I may forget to follow update on the per service policy and then there is some information included which might be wrong.

**Comment by Booteille** [comment]
Okay. I thought you wanted the ability to totally disable the display of a Privacy Policy. Since I think it's mandatory, I was curious about your reasoning.
However, I am all for the ability to modify it.

**Comment by Perflyst** [comment]
Yes, I want an option to completely disable the privacy policy on Invidious. And/or the option to set a custom link to the privacy policy.
