### ISSUE TITLE
[Documentation] Please consider adding a subsection to the main README to explain why people may want to use this

### ISSUE THREAD

**Issue by rubyFeedback** [iv-org/invidious#767]
Hello there,

Would it be possible to add a short subsection or expand on the existing content, to explain to people why they may want to use it? I get the current feature listing overview, but I think for new users (or semi-new ones like me), it would be useful and beneficial if there could be a short explanation as to use cases, e. g. why people may want to use invidious rather than the "default" to just use youtube.com directly. Thanks!

**Comment by Perflyst** [comment]
I am working on this right now! :)

**Comment by omarroth** [comment]
Also see #744.
