### ISSUE TITLE
Incomplete downloads

### ISSUE THREAD

**Issue by illtellyoulater** [iv-org/invidious#793]
Downloads stop before completing.

Example:

https://invidio.us/watch?v=HWhfZk1llUo

(I only tried downloading audio streams)

**Comment by omarroth** [comment]
I'm having trouble reproducing this. Which browser are you using?

**Comment by jjgh** [comment]
@omarroth  Google Chrome - 77.0.3865.90 (official build) (64 bit)

**Comment by HumanG33k** [comment]
Same issue for me with several Firefox Browser 70.0b12 (64-bit) & 60.9.0 (64-bit).
We also use adsblocker : yblock origin & NoScript and more addon but that are the only in common 
On debian stable & testing.

**Comment by jjgh** [comment]
...Just wondering, have downloads been disabled because of this bug?

**Comment by omarroth** [comment]
No, see #883.

**Comment by jjgh** [comment]
Hi, it seems my problems was instance specific. I tried downloading some other big files on invidio.us and after some time they end up failing.
This does not happen using for example vid.puffyan.us.
