### ISSUE TITLE
Arrow keys navigation

### ISSUE THREAD

**Issue by glaucocustodio** [iv-org/invidious#802]
Hi guys, I would to know if would be welcome a PR adding arrow keys (up, down, left, right) navigation to iterate through listed videos in `/` and `/feed/{{whatever}}` in the style of the discontinued http://youtube.com/leanback. 

My final goal is to enable a full watching/navigation experience by just using the keyboard.

**Comment by Booteille** [comment]
If I can recommend to get inspiration on [Pinafore](https://pinafore.social/settings/hotkeys). I find the workflow of their Hotkeys very good.

**Comment by omarroth** [comment]
My only issue would be the overlap between use of `down` and `up` for scrolling. Otherwise a PR would very much be welcome.

**Comment by Booteille** [comment]
Use `k` and `j` could be a good alternative.

**Comment by Kilian** [comment]
I would love this! I've wanted a replacement for leanback since they killed it. It could be an additional mode for invidious just like it was for youtube, so it won't interfere with the regular arrow key usage for users not wanting that mode.

**Comment by glaucocustodio** [comment]
I ended up creating my own browser extension for that: https://github.com/glaucocustodio/youcaptain

**Comment by PiRomant** [comment]
Arrow keys navigation need for Android TV and Smart TV (WebOS. Tizen OS etc)
