### ISSUE TITLE
Add a link to playlists in the menu

### ISSUE THREAD

**Issue by Booteille** [iv-org/invidious#825]
Actually, we need to "know" local playlists are a thing to find them on Invidious (in our settings).
I think it should be better to have a link redirecting to our playlists in the menu of Invidious.

**Comment by elypter** [comment]
i also suggest to have a drop down menu for adding the current video to a playlist akin to the download drop down

**Comment by omarroth** [comment]
Currently they're "View all playlists" under "Data preferences". I agree it should be made more prominent.

**Comment by Booteille** [comment]
> i also suggest to have a drop down menu for adding the current video to a playlist akin to the download drop down

I opened #826 to track this.

**Comment by omarroth** [comment]
Added as part of 7524b5e349ca403d49d4c35c55e9dc161a4e7d59.
