### ISSUE TITLE
Remember current volume setting

### ISSUE THREAD

**Issue by NettoHikari** [iv-org/invidious#846]
Hello guys.

I noticed that when switching to another video, the volume is reset to whatever the account setting is. Maybe we could store the value somewhere else so that it persists at least for the current session?

Greetings from Germany
NH

**Comment by omarroth** [comment]
This is already possible. You should be able to set your default volume in "preferenences", under "Player volume".

**Comment by NettoHikari** [comment]
Yes, it is set to 80%, which is fine. Let's say I'll watch a video and reduce the volume to 30% while watching. When watching yet another video, the value will be 80% again.

**Comment by Perflyst** [comment]
YouTube also remembers last video volume.

**Comment by timokoesters** [comment]
It should also keep track of the audio-only mode and auto-play-next setting
