### ISSUE TITLE
[Question] Can I bind invidious to use specific IP address on my note (multi network interface)

### ISSUE THREAD

**Issue by greentornado** [iv-org/invidious#853]
The case: I have some spare nodes, but also host other things, I can add more IP but dont want to destroy the node. So if the node get banned, i may get other new IP

**Comment by omarroth** [comment]
Yes, in your config:

```yaml
host_binding: 0.0.0.0
```

or as `-b` passed to the executable:
```
$ ./invidious -b 0.0.0.0
```

**Comment by greentornado** [comment]
Thankz. Does this effect the ip when invidious call youtube page ?

**Comment by omarroth** [comment]
Not currently. I expect that would require changes to the standard library.

**Comment by Perflyst** [comment]
I would like to assign a /28 subnet and invidious should automatically randomly uses the available IPv4 addresses for outgoing requests.
