### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by NettoHikari** [iv-org/invidious#857]
Hello guys,

recently, the error "Read timed out" suddenly appears after a random amount of time. It appears when clicking on any video and can only be solved by restarting Invidious.

The logs don't give any information either. I'm pretty sure it has to be some issue on my server or something. But maybe one of you guys might have a clue on why this happens.

Greetings from Germany
- NH

**Comment by omarroth** [comment]
Check to see if 13e7cca1a4b3999188201c242aa50f412426b833 improves the situation for you.

**Comment by NettoHikari** [comment]
Thank you, testing right away.

**Comment by NettoHikari** [comment]
I tested it, and the error still occurs. I moved Invidious from my VPS to a machine at home just a couple days ago. I have Gigabit internet at home, so that's no problem, but the box Invidious is running on is a potato. I might've overburdened it, since Invidious is not the single thing running on that computer. It is swapping a lot right now.

**Comment by r4rdsn** [comment]
I've just encoutered the same issue on my VPS instance.
