### ISSUE TITLE
Images in community tab posts

### ISSUE THREAD

**Issue by smnthermes** [iv-org/invidious#864]
The images displayed are cropped instead of the original ones.

Example: https://invidio.us/ggpht/RkHv5CmWyR-CohLYXMnz4g0p9VEI8f33RhI9bxXiQsx8CQjXQ2i-WORzLKzw9LodtEkb_3jb_Y1Z=s560-c-fcrop64=1,11ef000097e7ffff-nd

**Comment by smnthermes** [comment]
Original image: https://invidio.us/ggpht/I3jTwRWStyiyNmjY6-Ei-NI3gFZ-k8tW5e_ads8AaVPuz9PhC0VgJm6XlXMIePQJSCu5KfC1gkn-EpI

**Comment by omarroth** [comment]
Would you mind providing the channel where the image is displayed?
