### ISSUE TITLE
information how many hours ago was video published is sometimes fuck up

### ISSUE THREAD

**Issue by itsP4trickn** [iv-org/invidious#869]
![Untitled](https://user-images.githubusercontent.com/52964049/68091705-e9978f80-fe7a-11e9-866e-91492b049720.png)

PS: i know that it isn't most important bug u have to fix, so u don't have to fix it any time soon

**Comment by omarroth** [comment]
I'm having trouble understanding what the issue is in this case. Is the published time incorrect?

**Comment by PatrickNogas** [comment]
"2 hours4 views ago" this is bug
