### ISSUE TITLE
music premium only

### ISSUE THREAD

**Issue by HumanG33k** [iv-org/invidious#871]
i just noticed google operate some change on yt & music.yt .
Some videos (on yt)  related to music content become only available for music.yt premium accounts. it s look like it s just show the picture in invidious.
https://www.youtube.com/watch?v=OsxRixd9VP0
https://invidio.us/watch?v=OsxRixd9VP0&listen=0

i go on this page from my previous seen videos. i think it can be act as for vod but i never try it.

**Comment by chaosmonk1** [comment]
@omarroth Is https://github.com/omarroth/invidious/issues/302 still feasible after this change?

**Comment by omarroth** [comment]
@HumanG33k Would you mind providing some more details on this issue? If youtube-dl (for example) is able to download a video but Invidious is not, please provide an example. Content that is only available for users registered on YouTube will not be playable through Invidious.

> Is #302 still feasible after this change?

As far as I am aware this is not a new issue. As mentioned above this appears to only affect some content. Music playlists, search, etc. are still available.

**Comment by HumanG33k** [comment]
of course ict s not a real issue but a error message can be great. and strange thing but video is back online. I prefer report all strange things about Yt because it s a good way to know what yt do.
