### ISSUE TITLE
Tell visitors if the current instance is blocked

### ISSUE THREAD

**Issue by cloudrac3r** [iv-org/invidious#875]
It is possible for Invidious to know if it is blocked or not by examining the response it receives from YouTube. If a request failed because the instance is blocked, relevant information should be shown to the user.

The main way this would be displayed is as a more specific message on the error page.

Similarly, whether the request was blocked should be provided in API responses. This could either be designed as a custom message for the `error` key, or a separate key/value pair present in all API responses.

A field should also be added to /api/v1/stats to show whether any recent requests on this instance were blocked or not, to help automated processes decide if the instance is blocked or not without having to put extra load on it by requesting a video page. "Recent" could be as simple as "the latest one".

This will help users tell the difference between "the video URL is wrong", "the video was removed", and "this instance is blocked, so nothing is available right now".

Perhaps a page explaining how this blocking works should be created and linked in the error page, so that users that are unfamiliar with YouTube's recent automated request policies can understand what is happening. I would be willing to help write this article.

**Comment by omarroth** [comment]
Added error message as part of 0e1d6aa85c40d071270092de0195a75f928e3506.

**Comment by cloudrac3r** [comment]
From instances#6:

> And I just wanted to suggest to add a key to know if an instance is actually available or not (By available, I would like to also know if the instance is blocked by Google or not).

Elaboration: I think this should be implemented as a JSON API, either part of /api/v1/stats or perhaps its own endpoint, which displays the timestamp of that instance's most recent video request (e.g. 1576286344) and whether that request was blocked or not (true/false). This would allow automated tools to detect if an instance is blocked or not without having to put additional load on it with a /api/v1/videos request.

**Comment by Booteille** [comment]
Hey.

Where are we regarding this issue? I didn't follow past discussions around Invidious. 
Will an API endpoint be added?

**Comment by tnyeanderson** [comment]
If I can use an API call to check if my instance is blocked, then I can write a cron script to check it and reconnect my VPN to a different endpoint to eliminate "video not available" errors :)

**Comment by cloudrac3r** [comment]
Heh, that's a pretty creative use ^.^

If you pipe the process output into a program then you can maybe use that to monitor whether it's blocked through the status codes that it returns. Or you can accomplish the same thing with nginx.

**Comment by cloudrac3r** [comment]
I don't think the issue is very relevant anymore.
