### ISSUE TITLE
psql: FATAL:  Peer authentication failed for user "kemal"

### ISSUE THREAD

**Issue by Niemand112233** [iv-org/invidious#881]
Hi,
while trying to install, I face this problem:
psql invidious kemal < /home/invidious/invidious/config/sql/videos.sql
psql: FATAL:  Peer authentication failed for user "kemal"

what's wrong?

**Comment by omarroth** [comment]
Would you mind providing the commands you ran up to this point?

**Comment by m4teh** [comment]
Exactly the same issue. Following the installation instructions exactly yields the error.

**Comment by mavu** [comment]
you probably need to change the line:
```
# "local" is for Unix domain socket connections only
local   all             all                                     peer
```
to 
```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
```
Alternatively you can use "md5" instead of "trust" and should be asked for a password.

**Comment by oleole39** [comment]
@mavu's solution worked for me on a Debian 9 install.

I found pg_hba.conf file at the following path `/etc/postgresql/9.6/main/pg_hba.conf` thanks to [this trick](https://gist.github.com/AtulKsol/4470d377b448e56468baef85af7fd614#gistcomment-2144094): 

> To check location of `pg_hba.conf` connect to `postgres` db using `psql` then type `SHOW hba_file;` command.

**Comment by Vertux** [comment]
You can solve this issue by adding `-h 127.0.0.1`, then you are asked for the password of `kemal`:

```
psql invidious kemal -h 127.0.0.1 < /home/invidious/invidious/config/sql/playlist_videos.sql
```

**Comment by syeopite** [comment]
I'll assume the question has been answered.
