### ISSUE TITLE
Lack of visual buffering indicator

### ISSUE THREAD

**Issue by ulm27661** [iv-org/invidious#904]
On youtube we have white bar indicating buffered video. It would be nice if invidious have something like that.

**Comment by ulm27661** [comment]
I know there is some sort of gray bar if we skip backward but it's not what it appears to be.

**Comment by ulm27661** [comment]
Ok, few more video watched and there is such indicator but it sometimes doesn't work but I can't find exact steps to reproduce this bug every time at this moment.

**Comment by ulm27661** [comment]
It seems that skipping forward a couple of times breaks this buffered bar.

**Comment by ulm27661** [comment]
I mean skipping using keyboard shortcuts (right arrow) but it doesn't seem to work 100% of the time. Also I'm sorry for flood but for some reason comment edit doesn't work.

**Comment by ulm27661** [comment]
Since I have found one example of behavior which causes this bug I created [a new isssue](https://github.com/omarroth/invidious/issues/906). But sometimes it stops working 'just because'.

**Comment by omarroth** [comment]
I'm having trouble understanding this issue. Would you mind providing a screenshot or some description of the expected behavior?
