### ISSUE TITLE
[Feature Request] Provide a way to mute subscriptions

### ISSUE THREAD

**Issue by chocolateboy** [iv-org/invidious#908]
Similar to the [mute button](https://help.twitter.com/en/using-twitter/twitter-mute) on Twitter.

It'd be nice to have the option to silence some channels — e.g. channels which produce videos weekly or even daily —  to prevent them drowning out updates from more leisurely channels on the subscriptions page, while still keeping them around to manually browse for updates.

**Comment by atahanacar** [comment]
Instead of adding a mute button, a "Bookmark Channel" or "Check Later" option for channels would be more logical in my opinion.

**Comment by elypter** [comment]
thinking this further it would be cool to have metaplaylists. lists that cannot just contain videos but also other playlists, channels, search results and recommendations. your subscription feed would then be a mere metaplaylist that is sorted by newest. you could have multiple ones and also one big one that contains all your special ones.

**Comment by chocolateboy** [comment]
@elypter @atahanacar Maybe raise a different issue for these? That way they can be discussed and debated on their on their own merits rather than in an unrelated proposal.

**Comment by omarroth** [comment]
I expect this would be possible as part of #641.
