### ISSUE TITLE
Control bar broken on mobile

### ISSUE THREAD

**Issue by Ruin0x11** [iv-org/invidious#912]
The playback bar is too narrow to accurately seek videos in portrait mode on mobile, making it difficult to navigate very long videos.

In Firefox Preview:

![Screenshot_20191115-093159](https://user-images.githubusercontent.com/6700637/68963751-91229500-078c-11ea-88d5-995fc163bb3b.png)

Contrast with the official YouTube app:

![Screenshot_20191115-093316](https://user-images.githubusercontent.com/6700637/68963782-9e3f8400-078c-11ea-807c-6cdeb091c156.png)

It seems like the other video UI would have to be moved to accommodate this.

**Comment by TheFrenchGhosty** [comment]
Superseded by #1579
