### ISSUE TITLE
Video length doubles when switching from video to audio mode

### ISSUE THREAD

**Issue by mrzool** [iv-org/invidious#913]
When switching from video to audio mode, the length of the video doubles.

So a video that is 5:41 long becomes 11:22 long when switching to audio mode. In the additional 5:41 there is no audio.

Tested on iOS 13 and Safari 11.1.2 on macOS. 

[Sample video](https://invidio.us/watch?v=BsBBJ0IxvW4&listen=1).

Can anyone reproduce?

**Comment by omarroth** [comment]
I can reproduce on Safari 12.1. I'm unfortunately not able to find any information about this, I suspect it's related to using an audio only source in a `<video>` tag.

**Comment by mrzool** [comment]
I have no idea how the audio extraction gets handled, but how about simply changing the tag to `<audio>` when switching mode?

**Comment by ecx86** [comment]
I also have this bug on Safari

**Comment by omarroth** [comment]
> how about simply changing the tag to `<audio>` when switching mode?

This doesn't appear to resolve the issue unfortunately. I expect it's a bug in Safari, since it's possible to reproduce the issue with a plain `<audio>` element and only one source. I can't find any other examples of people encountering this bug however, so I'm still not sure what the issue may be.

**Comment by jbmorris289** [comment]
Hi. I tried playing in audio mode in Firefox for iOS (23.0) and the issue appears there as well 🤔. I'm wondering if the issue is isolated to iOS, because it doesn't happen on my Android.

**Comment by cloudrac3r** [comment]
Relevant:

https://github.com/sedmelluq/lavaplayer/issues/125

https://github.com/UGamer/UMusic/issues/19

**Comment by mrzool** [comment]
@jbmorris289:

> I tried audio mode in Firefox for iOS (23.0) and the issue appears there as well. I'm wondering if the issue is isolated to iOS, because it doesn't happen on my Android.

The issue is related to Safari on macOS and iOS. When you use any browser other than Safari on iOS you're actually still using Safari and the WebKit engine. That's why you can reproduce the same issue on Firefox on iOS.

**Comment by mrzool** [comment]
The issue is still present.

**Comment by syeopite** [comment]
I suppose #1735 didn't fix this then.

**Comment by mrzool** [comment]
Thanks @syeopite I had missed that. I can still reproduce the issue [with the video posted originally on the invidiou.site instance](https://invidiou.site/watch?v=BsBBJ0IxvW4&listen=1). Tested on iOS 14 and macOS 11.

That instance seems to be running a fairly recent build (it says "Current version: 2021.04.01-4b6d0fb @ master" in the footer) so I assume that's a no?

**Comment by mrzool** [comment]
The issue is still present.

**Comment by unixfox** [comment]
Can you reproduce this issue on firefox and chrome on macos?

**Comment by mrzool** [comment]
No, the issue is not present on either Firefox nor Chrome on macOS, only Safari.
