### ISSUE TITLE
Clicking on a video in a playlist doesn't bring you to the playlist nor update the index

### ISSUE THREAD

**Issue by kimimaru4000** [iv-org/invidious#914]
- When clicking on a video from a playlist, it brings you to the video without appending the playlist as a URL parameter. This happens on both YouTube and Invidious playlists.
- On Invidious playlists, if you append the playlist URL yourself and have autoplay set up, unless you specified the correct index of the video, it will play the very first video in the playlist even if you selected one in the middle.

What I feel should happen is clicking on a video in a playlist appends the correct parameters to play that video in that playlist and know where you are in the playlist, regardless if it's YouTube or Invidious.

EDIT: I was in Thin Mode when testing this. After turning off Thin Mode, I found that clicking on the video thumbnails does indeed bring you to the list. However, it still does not bring you to the correct index on the playlist for Invidious playlists.

**Comment by tdeeb** [comment]
A potential fix for this involves adding the index to the URL of each video. [Here's at least one spot it can go](https://github.com/omarroth/invidious/blob/master/src/invidious/playlists.cr#L490).

**Comment by tdeeb** [comment]
I believe this issue is still relevant, as none of the instances I use have it fixed.

**Comment by SamantazFox** [comment]
this has been fixed by #2257
