### ISSUE TITLE
Spoiler for notifications

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#93]
I think it's a good idea to add a spoiler (just a button actually) when there are no unseen notifications.

![](https://i.imgur.com/mGowFFg.png)

**Comment by omarroth** [comment]
I'm assuming this would be when `Only show notifications` is checked?

**Comment by dimqua** [comment]
I think it's a bit confusing to see any unsorted list of videos by default when there are no unseen videos at all. I agree that adding a spoiler isn't great solution for this, but what you think about implementing #62 feature in the future? I think it can make the subscriptions page more understandable.

What about a situation when there is at least 1 unseen notification? I think a spoiler is still better than do not display anything.
