### ISSUE TITLE
Feature Request: Allow API requests for multiple videos at once

### ISSUE THREAD

**Issue by elliotwaite** [iv-org/invidious#936]
Currently, if I want to get data for multiple videos, I have to make a separate request for each video, which can be quite laggy. It would be nice to be able to request data for multiple videos at once by making a batch API call, for example by concatenating multiple video IDs with commas (similar to how YouTude's Data API works).

For example:
https://invidio.us/api/v1/videos/videoid1,videoid2,videoid3

When the request is for multiple videos, instead of returning an object, the API could return an array of objects, one object for each video ID. The batches could be limited to something like 50 videos per request (similar to how YouTube's Data API works).

**Comment by greentornado** [comment]
This could get the node got banned quickly due to (possible) very large requests to Youtube

**Comment by Perflyst** [comment]
Spamming with short requests results in the same, so it doesn't matter

**Comment by omarroth** [comment]
Would you mind going into more detail the intended use-case for this feature? Are e.g. `/api/v1/search` or the `related` field in `/api/v1/videos` not adequate, or is there information that your project needs that is not provided?

**Comment by elliotwaite** [comment]
I need to get the likes and dislikes counts for many videos at a time. It would be used by this browser extension: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube

The extension currently requires users to set up a personal YouTube Data API key, but one of the users suggested I add the option of allowing users to use the invidious API for privacy reasons. However, since the invidious API doesn't support bulk video statistics, it is much slower than using the YouTube Data API directly with a personal API key. If you're interested, you can checkout the discussion about this issue here: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/19#issuecomment-558146904
