### ISSUE TITLE
[improvement] Adding the youtube video link when Invidio is down.

### ISSUE THREAD

**Issue by Rb4eogrl** [iv-org/invidious#940]
Hi, 

Like lots of people, I had the message "Could not extract video info. Instance is likely blocked" ...

The prob is that we only have this message and nothing else. I think it's could be cool to add a message like "you can watch it on youtube directly via ...." with the link. 

Today, I have to copy the link from the url and paste it in youtube.

For information: the reason is because my main goal is to delete my google account once a day (hope this year) sadely, youtube block the process. But what I use in youtube is only one fonctionnality, the subscribe, and it's almost the same in invidio. 
Watching the vidio on youtube because invidio is down is not a issue for me, for a short period. 

But yesterday, impossible to have the link... 

Thanks a lot.

**Comment by elypter** [comment]
or instead: link to another invidious instance or provide a list for users to chose from

**Comment by simoniz0r** [comment]
I think both would be the best solution as often times when one instance is blocked, it's very hard to find another that's working.

**Comment by elypter** [comment]
would be great if this will be also in place with "Service is currently unavailable, please try again later." and 500 server errors.
