### ISSUE TITLE
[improvement] Apply dark theme (if applicable) _before_ remaining page load

### ISSUE THREAD

**Issue by merberich** [iv-org/invidious#945]
Currently, theme is applied to elements after the entire page loads. For slow connections or hosts (and in most cases mobile devices), this means the page spends a fair amount of time with the bright default theme, then enters dark theme. From a UX perspective, it would be nice to avoid the "flash" from default to dark.

**Comment by haizrul** [comment]
I think https://yewtu.be use that on their website. Loads fast too.

**Comment by GauthierPLM** [comment]
The issue is that currently, the theme is handled with JavaScript rather than CSS (which would solve the issue for people with browsers supporting the `prefers-color-scheme` media query).

I will give a look on how to handle this properly.
