### ISSUE TITLE
Search multiple channels at once?

### ISSUE THREAD

**Issue by JaneSmith** [iv-org/invidious#954]
Sorry if this is already a feature - if it is, then I can't figure out how to do it.

I know I can search for videos from one channel using "channel:xxx". But I want to search through multiple channels at once, e.g. using "channel:xxx channel:yyy channel:zzz". I want to have videos from them all returned, sorted by most recent, just the same as if I searched for a single channel.

This would let me bookmark links to groups of channels, e.g. all tech-related channels that I follow, all fashion-related channels, all comedy channels, etc., essentially subscribing to them separately rather than all in one giant group. It would also allow me to search keywords across multiple channels.

Is this a feature? Could it become one? Thanks.

**Comment by elypter** [comment]
this could be done with meta playlists if those get implemented

**Comment by omarroth** [comment]
Currently this is not an available feature. Unless this feature is available on YouTube I don't think it's very practical to implement, since it would require multiple calls to YouTube in order to return the desired results.
