### ISSUE TITLE
Popular page is blank

### ISSUE THREAD

**Issue by haizrul** [iv-org/invidious#955]
My instance got a little problem. Popular page does not display any videos at all. Top and Trending page are working fine. Anyone also face this issue?

**Comment by scsmash3r** [comment]
Same goes with invidio.us main page:
![image](https://user-images.githubusercontent.com/4781532/70556385-78d64800-1b89-11ea-9e1d-06ce42564dc4.png)

Refreshing a page gives some result from time to time.

**Comment by Perflyst** [comment]
Can you open the browser console (F12) if this happen and take a look if there is some error in the console?

**Comment by EntropiaFox** [comment]
Having the same issue with my own instance as well, no error on console, although I can notice there's a request that never seems to resolve:

![brave_ZLaiUp9u5u](https://user-images.githubusercontent.com/1080472/70734542-cd410b00-1ce2-11ea-867d-6a83674ea54a.png)

`https://localhost/api/v1/auth/notifications?fields=videoId,title,author,authorId,publishedText,published,authorThumbnails,liveNow`

**Comment by haizrul** [comment]
Any comment @omarroth ?

**Comment by haizrul** [comment]
@EntropiaFox did you find solution for this problem?

**Comment by B0pol** [comment]
Same here
![image](https://user-images.githubusercontent.com/58657617/83166483-49070680-a10f-11ea-97de-7c971c18311f.png)
![image](https://user-images.githubusercontent.com/58657617/83166572-6b008900-a10f-11ea-97fb-1d726ceee310.png)
![image](https://user-images.githubusercontent.com/58657617/83166675-8ec3cf00-a10f-11ea-85a1-268cabe362fa.png)

/api/v1/popular returns `[]` with HTTP code 200.

**Comment by B0pol** [comment]
… and now it's showing my subscription feed

**Comment by SamantazFox** [comment]
@haizrul do you still have this issue? if yes, make sure that `popular_enabled` is set to `true` in your `config.yml`
