### ISSUE TITLE
Newbie question about video feed crashing

### ISSUE THREAD

**Issue by wongfeihung1984** [iv-org/invidious#958]
Hi everyone, 

as mentionned I'm not tech savvy so my apologies in advance if my question looks stupid to you.

I'm on firefox (ublock+privacy badger+https) and I'd like to know why all videos on invidious regulary crashes ? When I'm using freetube for exemple none of this happens...

Kind regards

**Comment by omarroth** [comment]
Would you mind opening devtools (Ctrl+Shift+I) to see if there are any errors being reported?
