### ISSUE TITLE
full screen button is hidden on mobile

### ISSUE THREAD

**Issue by shultays** [iv-org/invidious#964]
![Screenshot_20191223-022119_Firefox](https://user-images.githubusercontent.com/3469314/71328640-2dc21a80-2523-11ea-9865-f84e96788aee.jpg)

Full screen button is hidden (probably because my phone is not wide enough). When I change the orientation of my screen it shows up and work as expected. It should probably has a higher priority to not get hidden if the phone is not wide enough. Definetely more prio then cc button

My phone is samsung galaxy a7 which has 1080x2020 resolution. I am on firefox 68.3.0

**Comment by haizrul** [comment]
Happen to me too on Pocophone f1 using Opera browser.

**Comment by ChaseHall** [comment]
Can confirm. Happens on iPhone XS using Firefox Focus in portrait mode.

**Comment by rany0** [comment]
You could scroll the bar to the right. This happened to me too, it is not hidden.

**Comment by rany0** [comment]
It is just not obvious.

**Comment by syeopite** [comment]
Fixed by #2008
