### ISSUE TITLE
Unable to import subscriptions

### ISSUE THREAD

**Issue by askious1** [iv-org/invidious#967]
* opml file generated by invidious using 'Export subscriptions as OPML' (first option under export)
* file uploaded via 'Import Invidious data' button (first option under import)
* click import button

 page immediately changes to "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to ..."

have tested a few different opml files to same effect.
have tested on the following instances with same results:
invidious.snopyta.org
invidiou.sh
yewtu.be
invidious.ggc-project.de

opml file used https://0x0.st/zDUS.txt

Thanks and regards,
TT

**Comment by atahanacar** [comment]
I get the same error when I use "Import Invidious data". As a workaround, you can use the "Import YouTube subscriptions" option with the same opml file. It worked for me.

**Comment by m4teh** [comment]
#963
