### ISSUE TITLE
Bug: During playback, the video and audio would freeze, but the player is still going.

### ISSUE THREAD

**Issue by cyberchief1984** [iv-org/invidious#970]
This not only happens on the  official instance, but other instances too.

**Comment by wuniversales** [comment]
That happens when activating the option "Activate the default sound:"

**Comment by cyberchief1984** [comment]
> 
> 
> That happens when activating the option "Activate the default sound:"

Could you explain? I don't see this option.

**Comment by wuniversales** [comment]
> Could you explain? I don't see this option.

In the configuration you can see it

**Comment by cyberchief1984** [comment]
I'm not an admin.
