### ISSUE TITLE
SQL files in the config directory require a "kemal" user

### ISSUE THREAD

**Issue by PureTryOut** [iv-org/invidious#976]
However, I use a different username for my database. Currently (using the docker image), Invidious won't just run with my setup as I first have to edit all instances of "kemal" to the proper username.

Please make it use the configured username as set in `config.yml`.

**Comment by omarroth** [comment]
I'm having trouble understanding this issue. Is Invidious not connecting with the username specified in the config, or are you referring to the username specified in migration scripts and such?

**Comment by PureTryOut** [comment]
The migration scripts. If you modify the scripts and create the database with a different user, Invidious connects to it fine if the user is properly set in the config file.

**Comment by nikaro** [comment]
Put differently, there should not be a "hard-coded" user in the repository.

**Comment by PureTryOut** [comment]
This very much seems to be relevant still. I wonder, is there no migrate functionality somewhere in the Crystal ecosystem? As in, let some tool automatically create SQL scripts based on models in the code, which will use the configuration of the application to determine as what user to create the database.
Something like Alembic in Python and stuff.
