### ISSUE TITLE
Searching for certain words results in no results being shown

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#979]
When I search for unfathomable force, no results are being shown.

**Comment by haizrul** [comment]
Looks okay : https://invidio.us/search?q=unfathomable+force

![Opera Snapshot_2020-01-08_015423_invidio us](https://user-images.githubusercontent.com/8771582/71916860-d629dd00-31b9-11ea-8624-16c72eac64d0.png)

**Comment by Zero3K** [comment]
It happens randomly when refreshing the search results page.

**Comment by syeopite** [comment]
Can you still reproduce this?

**Comment by unixfox** [comment]
Closing due to a lack of replies.

**Comment by Zero3K** [comment]
It is no longer happening for me.
