### ISSUE TITLE
Youtube Originals Video doesn't play

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#982]
It is [this video](https://invidio.us/watch?v=88Cd5H3kmXQ) that isn't working on invidio.us but other Originals probably do not work either. It works just fine on youtube.

**Comment by PendragonII** [comment]
The video played fine for myself; for you, try:
- Clearing your browser cache;
- Disable any VPN and restart your WiFi;
- If your browser has any vigorous security try temporarily disabling them (i.e: [Mozilla FireFox's resistFingerprinting setting](https://www.privacytools.io/browsers/#about_config));
- Make sure that your browser is able to set first-party cookies.

Hope this helps :wave:

**Comment by rex4539** [comment]
I see the following.

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

Plays fine on YouTube.

**Comment by omarroth** [comment]
Likely duplicate of #92.
