### ISSUE TITLE
Automatically change video quality/format to hd720 if dash doesn't work

### ISSUE THREAD

**Issue by zethexx** [iv-org/invidious#989]
Currently if a video doesn't work well with the dash quality/format the player will be stuck at `0:00 / -:-` and playback will not start. The solution is to go into preferences and change "Preferred video quality" to "hd720" in order to play the video, and change it back to dash once you're done. Sometimes it can be easy to forget to change back to the preferred video quality (dash).

What [FreeTube](https://github.com/FreeTubeApp/FreeTube) does is automatically change to hd720 (legacy) formats if the video doesn't play well with dash. It would be nice to see the same feature being implemented on the Invidious front-end website.

**Comment by ExpandingMan** [comment]
Alternatively, there could just be a link somewhere on the page that made this easy to do.
