### ISSUE TITLE
Explanation how to use install and use ?

### ISSUE THREAD

**Issue by dj-sash** [iv-org/invidious#994]
Hello…
Your app Invidious, which I think is an alternative to play youtube videos.
Can you please give a good explanation how to install and use it?

We are not all programmers.

That would be great and thanks.

**Comment by dj-sash** [comment]
In fact, how I reach till here is with an issue with an app called Freetube…
Giving me the error >>  Invidious api error: Error writing to socket: Broken pipe
When I open the video directly on Youtube, the video plays very well.
And another issue with the audio when we are trying to play the video faster, the audio starts to chop with a sort of annoying repeating noise.

**Comment by Perflyst** [comment]
An installation guide is in the readme https://github.com/omarroth/invidious#installation

**Comment by pedrolucasp** [comment]
Also @dj-sash, I would recommend you to use the official instance at: https://invidio.us
