### ISSUE TITLE
[Feature Request] Proper Search-engine-like page

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#996]
After #449 it is now possible to have a page without anything other than a search box:

![1](https://user-images.githubusercontent.com/47571719/72755771-3873dc00-3bc3-11ea-84b7-91a31b296016.png)

However the layout of the page follow the layout of every other page without the unwanted content and doesn't actually looks like a search engine page.

![searx](https://user-images.githubusercontent.com/47571719/72755698-095d6a80-3bc3-11ea-9288-98300d034bd3.png)

The missing things for this to be complete are: search box centered, Invidious displayed above it, footer at the bottom.

Basic sketch of the result:

![result](https://user-images.githubusercontent.com/47571719/72755655-ecc13280-3bc2-11ea-86bf-ec2051aa5894.jpg)

**Comment by stoically** [comment]
Giving the search box the autofocus attribute in that case would be kinda neat as well.

**Comment by elypter** [comment]
id love for it to automatically have auto focus on all sites

**Comment by TheFrenchGhosty** [comment]
Still wanted.
